duckduckgo/Android

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203529428649444/f
Users report that AppTP causes all protected apps to lose connectivity. Reproducing this issue in-house revealed that sometimes two TUN interfaces are created. Upon further inspection, we found the root cause to be the system calling `onStartCommand` twice (even though we call `startForegroundService` once).
The fix here is to detect when we are already in the middle of creating a VPN and not start creating another one.
1. Open an app and then force close it
2. Disable protection for it
3. Re-enable protection
4. Rinse and repeat ~10 times
> Avoid starting VPN twice

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistryImpl.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistryImplTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203553001428526/f
Fix bug that caused AppTP not to get enabled after onboarding
_Test bug fix_
_Test app update_
(you may experience the bug we're fixing here, so ensure you enable it)
> Fix AppTP enable state during onboarding

- privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModel.kt
- privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/SiteViewStateMapper.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203517684270584/f 
Fixes null pointer exception when getting domain from an URI.
Note:
I wasn't able to test a URI that can return null as host, but it seems possible according to crash reports.
We already have a safe check when enable/disable protections from the overflow menu, so taking same approach here.
_Feature 1_
> fix: domain can be null for some URIs

- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/OneLineListItem.kt
- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/TwoLineListItem.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203563042100874/f
- ~~Setting default LeadingIconBackground to none for TwoLineListItem~~ (_Deferred to later_)
- Set background to Transparent when setLeadingIconBackgroundType is called for none/0 for TwoLineListItem and OneLineListItem
- Check Design Preview is as expected.
> Fix support for no leadingImageBackground on OneLineListItem and TwoLineListItem

- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/SearchBar.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203570146222881/f
Fixes the way the `SearchBar` decides to show its clear button (✖️) or not.
> Fix count used for search bar's clear button

- .github/workflows/end-to-end.yml
- .maestro/release_tests/1_-_bookmarks.yaml
- .maestro/release_tests/2_-_browsing.yaml
- .maestro/release_tests/3_-_favorites.yaml
- .maestro/release_tests/4_-_tabs.yaml
- .maestro/release_tests/5_-_app_tp_onboarding.yaml
- .maestro/release_tests/6_-_fire-during-onboarding.yaml
- .maestro/shared/onboarding.yaml
- anvil/anvil-annotations/src/main/java/com/duckduckgo/anvil/annotations/ContributesNonCachingServiceApi.kt
- anvil/anvil-annotations/src/main/java/com/duckduckgo/anvil/annotations/ContributesServiceApi.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203568230967986/f
Add release e2e tests that will run on nightly CI.
Incidentally fixing some unrelated javadocs.
With maestro installed, `cd .maestro/release_tests` and run the following script
```bash
for i in *.yaml; do
maestro test "$i"
done
```
All should pass
Also, tests on movile.dev (https://github.com/duckduckgo/Android/actions/runs/3726837954) have passed
> Add e2e release tests to CI nightlies

- .gitmodules
- build.gradle
- vpn-network/vpn-network-impl/build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1203208709178851/f
Remove netguard submodule and consume it as a library dependency
> Consume netguard as a dependency

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementActivity.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementListMode.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/SaveStateWatcher.kt
- autofill/autofill-impl/src/main/res/drawable/ic_baseline_add_24.xml
- autofill/autofill-impl/src/main/res/menu/autofill_list_mode_menu.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203522700191989/f
Adds ability to manually create logins from the credential management screen.
- updated test case **Navigating back mid-creation** with a new check
- updated test case **Backgrounding the app mid-creation** with a new check
> Add ability to manually create logins from credential management screen.

- app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/trackers/AppTracker.kt
- app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/trackers/AppTrackerJsonParser.kt
- app-tracking-protection/vpn-store/src/test/java/com/duckduckgo/mobile/android/vpn/trackers/AppTrackerJsonParserTest.kt
- app-tracking-protection/vpn-store/src/test/resources/full_app_trackers_blocklist.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1203285431672073/f
Parse and use the `default` field in the AppTP blocklist.
_Test Fresh Install_
_Test App Update_
> Parse and user default action field in blocklist

- app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnServiceCallbacks.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/stats/VpnServiceStateLogger.kt
- app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203586092184943/f
This PR includes resetting the VPN state to DISABLED when any error occurs before the VPN successfully starts.
Smoke test AppTP
_Attempt repro 2 tun interface bug_
> Fix setting state back to DISABLED when vpn fails to start

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementActivity.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementRecyclerAdapter.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/searching/CredentialListFilter.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementListMode.kt
- autofill/autofill-impl/src/main/res/drawable/ic_baseline_search_24.xml
- autofill/autofill-impl/src/main/res/layout/activity_autofill_settings.xml
- autofill/autofill-impl/src/main/res/layout/item_row_search_no_results.xml
- autofill/autofill-impl/src/main/res/menu/autofill_list_mode_menu.xml
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/searching/ManagementScreenAutofillCredentialMatcherTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/searching/ManagementScreenCredentialListFilterTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203563399643944/f
Adds ability to search for saved credentials from the credential management screen. Fields searched for a match are:
- title
- domain
- username
- notes
Note, password field isn't checked for a match.
_With credentials already saved_
_With no credentials saved_
**No credentials saved - no search button**
<hr/>
**Credentials saved - search button is visible**
<hr/>
**Mid-search: results found**
<hr/>
**Mid-search: no results found**
> Search credentials from credential management screen

- app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/rules/ExceptionRulesDebugReceiver.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203536459696139/f
Fix bug where the receiver may clear the exception rules on VPN start
Code review. Reproing may be difficult or involved modifying code to test it, as this would happen only when the DB table is not yet populated
> Fix ExceptionRulesDebugReceiverRegister risk to clear the exclusion list rules

- .github/workflows/end-to-end.yml
- .github/workflows/nightly.yml
- .github/workflows/privacy.yml
- .github/workflows/update-ref-tests.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203673701090347/f
This PR creates an Asana task whenever a nightly workflow fails
For failure examples see:
1. https://github.com/duckduckgo/Android/actions/runs/3875092919 and https://app.asana.com/0/414730916066338/1203675428838182/f
2. https://github.com/duckduckgo/Android/actions/runs/3875095333 and https://app.asana.com/0/414730916066338/1203675149404753/f
> Create asana task when nightly workflows fail

- app/src/androidTest/java/com/duckduckgo/app/referencetests/FirstPartyCookiesReferenceTest.kt
- app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/WebViewCookieManager.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/features/firstparty/FirstPartyCookiesModifier.kt
Task/Issue URL: https://app.asana.com/0/0/1203562061689358/f 
This PR adds fireproofed sites and SERP sites to the exclusion list before changing their expiry date in their 1st party cookies
> Add fireproofed sites and serp sites to the exclusion list for first party cookies expiry

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.css
- node_modules/@duckduckgo/autofill/dist/autofill.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1203674907697557/1203674907697557
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.1.1
Updates Autofill to version [6.1.1](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.1.1).
* Fix types for ID by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/239
* Email Protection sign-up tooltip by @alistairjcbrown in https://github.com/duckduckgo/duckduckgo-autofill/pull/240
* Autofill pixels by @sixers in https://github.com/duckduckgo/duckduckgo-autofill/pull/242
* More minor fixes by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/244
* Fix schema issue in extension repo by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/245
* Remove …
> Update autofill to 6.1.1

- app/src/test/java/com/duckduckgo/app/global/UriStringTest.kt
- common/src/main/java/com/duckduckgo/app/global/UriString.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203568844801448/f
Tweaks the logic used to determine if an inputted query is a web URL or not; better handling for a query like `http://raspberrypi` or `http://raspberry:8080` (has a scheme, does not have a TLD) to navigate rather than search.
> Fix for webUrl detection for local named computers

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203722243925031/f
Prevents our internal edittext field used for passwords from triggering the os-level autofill service.
- Hard to reproduce this, so sanity check the change makes sense is ok
> Flag our internal password field as unimportant for autofill

- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/text/DaxTextInput.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1201131549756894/f
Automatically reveals the password when editing the password field, which uses the `DaxInputText` view.
> Reveal password in DaxTextInput when editing

- app/src/androidTest/resources/reference_tests/domain_matching_tests.json
- app/src/main/java/com/duckduckgo/app/trackerdetection/CloakedCnameDetector.kt
- app/src/test/java/com/duckduckgo/app/trackerdetection/CloakedCnameDetectorImplTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203532296782616/f
This PR: 
- Appends the scheme of the request URL when a CNAME tracker is detected
- Enables the corresponding domain reference test to ignore same entity CNAME trackers
> Ignore same entity CNAMEs

- package-lock.json
- package.json
> Update reference tests to latest version

- app/src/main/java/com/duckduckgo/app/onboarding/di/WelcomePageModule.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModel.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModel.kt
- app/src/test/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModelTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Task/Issue URL: https://app.asana.com/0/0/1203712351528765/f
Added `os_version_13_or_above` param for `m_db_s` and `m_db_ns` pixels fired from onboarding only.
Android 13 
- Scenario: Set DDG as default browser from obnoarding
- Scenario: Set DDG as browser from Settings
- Scenario: Don't set DDG as default browser from obnoarding
Any version strictly below Android 13
- Scenario: Set DDG as default browser from obnoarding
- Scenario: Set DDG as browser from Settings
- Scenario: Don't set DDG as default browser from obnoarding
> Implementation task: Add pixel (updated to use OS version)

- privacy-config/privacy-config-internal/src/main/java/com/duckduckgo/privacy/config/internal/plugins/ApiDevPrivacyConfigInterceptor.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203779625126900/f 
Fixed bug affecting nightlies and internal builds caused by interceptor overriding all request URLs.
Related to: https://github.com/duckduckgo/Android/pull/2650
_Feature 1_
_Test download_
> Fix internal dev interceptor

- app/build.gradle
- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/java/com/duckduckgo/app/pixels/EnqueuedPixelWorker.kt
- app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/pixels/EnqueuedPixelWorkerTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Task/Issue URL:  https://app.asana.com/0/1174433894299346/1203763177144100
This PR modifies the launch pixel to understand if we are the default browser, and creates a new pixel to be launched when another app opens us.
_App Launch_
_Third party launch (as default browser)_
_Third party launch (as default browser)_
> Default Browser on Launch

- app/src/androidTest/java/com/duckduckgo/app/browser/WebViewRequestInterceptorTest.kt
- app/src/androidTest/java/com/duckduckgo/app/referencetests/DomainsReferenceTest.kt
- app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt
- app/src/main/java/com/duckduckgo/app/trackerdetection/CloakedCnameDetector.kt
- app/src/test/java/com/duckduckgo/app/trackerdetection/CloakedCnameDetectorImplTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203771754388225/f
Checks the request URL against the tracker allow-list before doing CNAME detection.
> Check if CNAME request URL is in allow list

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/email/EmailInjectorJsTest.kt
- app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoUrlDetector.kt
- app/src/test/java/com/duckduckgo/app/browser/DuckDuckGoRequestRewriterTest.kt
- app/src/test/java/com/duckduckgo/app/browser/DuckDuckGoUrlDetectorTest.kt
- app/src/test/java/com/duckduckgo/app/browser/QueryUrlConverterTest.kt
- app/src/test/java/com/duckduckgo/app/email/EmailJavascriptInterfaceTest.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/InlineBrowserAutofillConfigurator.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/configuration/InlineBrowserAutofillConfiguratorTest.kt
- browser-api/src/main/java/com/duckduckgo/app/browser/DuckDuckGoUrlDetector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203800330887198/f 
This PR is to honour the autofill remote feature flag
_Autofill is disabled/enabled_
> Honour autofill flag

- app/src/main/java/com/duckduckgo/app/browser/favorites/FavoritesQuickAccessAdapter.kt
Fixes an issue where the popup menu on favorites items would not dismiss after reorder drag. The `popupMenu` variable is now assigned in the `showOverflowMenu` function.
Run on device/emulator.
| ![before](https://user-images.githubusercontent.com/12491712/214262075-04d23bb4-6ce3-467e-8dba-36ad934e342e.gif) | ![after](https://user-images.githubusercontent.com/12491712/214262134-2c108978-3818-4e15-8fce-9ae4e748f814.gif) |
> Fix favorites popup menu still showing after reorder drag

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/global/api/AtbAndAppVersionPixelRemovalInterceptor.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
Task/Issue URL: https://app.asana.com/0/69071770703008/1203490334991976/f 
This PR rollbacks the changes done in https://github.com/duckduckgo/Android/pull/2601
_Feature 1_
> Remove experimental FB pixels

- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DefaultDownloadsRepository.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1203760457164434/f
Updated the downloads repository to not handle any physical file deletion as this is done in the view model.
Reproduce the issue (delete all files scenario + delete individual file scenario)
Test the fix (delete all files scenario + delete individual file scenario)
> Android Bug: Undo doesn't work when deleting downloaded files

- .github/workflows/ads-end-to-end.yml
- .maestro/ads_preview_flows/1-_design-system-components.yaml
Task/Issue URL:  https://app.asana.com/0/1174433894299346/1203827857866586
Adds a Maestro test to open the ADS Preview pages whenever a change to a Component happens
_Non Android 13 device_
---
- https://app.asana.com/0/0/1203827857866586
> ADS: Maestro

- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/cohort/RealCohortCalculatorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203837698579470/f
`whenLocalDate4WeeksAgoThenReturnWeeklyCohort` should assert on week based year and not year directly.
Not doing so makes the expected value to be wrong in cases where the date is a date in a year but falling into a previous year week, like 2023-01-01
PR Unit tests should pass as it was submitted the same day that caused the failure, ie. 2023-01-29
> Fix flaky test expected value

- common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203838208769837/f
Updated the default icon padding for buttons to match the design.
|![Screenshot_20230126_161121](https://user-images.githubusercontent.com/7963079/214890832-ab17bfbd-6dc1-4dcb-8d22-840e48641626.png)|![Screenshot_20230126_161711](https://user-images.githubusercontent.com/7963079/214890878-bab6afaa-9803-488b-b02f-1c60e18a1887.png)|
> Android: Icon padding for buttons is too small 

- app/src/main/res/layout/include_duckduckgo_browser_webview.xml
- common-ui/src/main/res/layout/fragment_components_dialogs.xml
- common-ui/src/main/res/values/design-system-theming.xml
- common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/0/1157893581871903/1203849465655153
Fixes https://github.com/duckduckgo/Android/issues/2774
Date Picker theming is not working
_Feature 1_
| Before  | After - Light Theme | After - Dark Theme |
| ------ | ----- | ----- |
> Fix Date Picker Theming

- app/src/main/java/com/duckduckgo/app/browser/DownloadConfirmationFragment.kt
- app/src/main/java/com/duckduckgo/app/fire/fireproofwebsite/ui/FireproofWebsitesActivity.kt
Task/Issue URL: https://app.asana.com/0/0/1203887624504456/f
Migrate DownloadConfirmationFragment from kotlin synthetic and remove unused import from other class
- Download any document from the browser
> Migrate DownloadConfirmationFragment to viewBinding

- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
- common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/dialogs/DialogsFragment.kt
- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/BackKeyListener.kt
- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/TextAlertDialogBuilder.kt
- common-ui/src/main/res/layout/fragment_components_dialogs.xml
Task/Issue URL:  https://app.asana.com/0/1157893581871903/1203893894847062
This PR makes the TextAlertDialog cancellable. 
We also want to revert the changes in the AppEnjoyment flow, and leave it as it was before.
_App Components Preview_
> ADS: Make TextAlertDialog Cancellable

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203919191204179/f
m_atp_ev_apptp_create_network_stack_error should only be sent when onCreateVpn is failure
Smoke test AppTP
> Fire error pixel only when onCreaterVpn() is failure

- app/src/test/java/com/duckduckgo/app/global/UriExtensionTest.kt
- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/urlmatcher/AutofillUrlMatcher.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/urlmatcher/AutofillDomainNameUrlMatcher.kt
- autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt
- autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/urlmatcher/AutofillDomainNameUrlMatcherTest.kt
- common/src/main/java/com/duckduckgo/app/global/UriExtension.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203892213154867/f 
This PR changes the way that we store URls in autofill to only store host:port
> Change the way we store URLs in autofill

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesPluginPointCodeGenerator.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1203874493929848/f
Memoize the sorted plugins to avoid sorting every time `getPlugins()` is called.
> Memoize sorted plugins in plugin points

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesPluginPointCodeGenerator.kt
- app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/service/FakeVpnEnabledNotificationContentPlugin.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnEnabledNotificationContentPluginPoint.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnTrackerNotificationUpdates.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/service/VpnEnabledNotificationContentPluginPointKtTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203928902312895/f
See [asana task](https://app.asana.com/0/488551667048375/1203928902312895/f) for description
_AppTP Notifications_
> Fix NoSuchElementException in notification content plugin

- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/urlmatcher/AutofillUrlMatcher.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/LoginCredentialTitleExtractor.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/TitleOrDomainExtractorTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/suggestion/SuggestionMatcherTest.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/urlmatcher/AutofillDomainNameUrlMatcher.kt
- autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/urlmatcher/AutofillDomainNameUrlMatcherTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203892213154868/f
Considers port numbers when comparing urls, and displays port number in the UI if set.
This is harder, unless you happen to know a publicly accessible website which uses a non-standard web port. If not, simulate the test by hardcoding a URL for the current site when launching creds management screen.
> Consider ports for autofill matching and for displaying logins

- anvil/anvil-annotations/src/main/java/com/duckduckgo/anvil/annotations/ContributesRemoteFeature.kt
- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
- app/build.gradle
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureExceptions.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureSettings.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggle.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureTogglesPlugin.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/RemoteFeatureStoreNamed.kt
- feature-toggles/feature-toggles-impl/build.gradle
- feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/RealFeatureTogglesImpl.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/FeatureTogglesTest.kt
- feature-toggles/feature-toggles-test/build.gradle
- feature-toggles/feature-toggles-test/src/main/java/com/duckduckgo/feature/toggles/api/FakeToggleStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203898052213031/f
See [asana task](https://app.asana.com/0/1202552961248957/1203898052213029/f) for full background.
The PR adds a code generator for (remote) feature flags. 
For instance, the following remote feature:
```json
{
"myFeatureName": {
"exceptions": [...],
"settings": {...},
"features": {
"remoteFeatureName": {
"state": "disabled"
}
}
"hash": "..."
}
}
```
can be represented with the following code:
```kotlin
@ContributesRemoteFeature(
scope = AppScope::class,
featureName = "name",
//    settingsStore = MyFeatureFeatureSettingStore::class,
//    exceptionsStore = MyFeatureFeatureExceptionStore::class,
)
class MyRemoteFeature {
@Toggle.DefaultValue(false)
fun self(): Toggle
@Toggle.DefaultValue(false) …
```
> Create the feature flag code generator

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/cohort/CohortStore.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/cohort/CohortPixelInterceptorTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/cohort/RealCohortStoreTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203973782879231/f
This PR adds a check if AppTP is registered before updating the cohort.
See Asana task for more info.
> Update cohort when AppTP is enabled only

- app/src/main/res/layout/content_broken_sites.xml
Task/Issue URL: https://app.asana.com/0/1202552961248957/1203975196513828/f
Adds matching right padding to "Report Broken Site".
> Report Broken Site screen not symmetrical

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/1203137811378537/1203972982741396/f
When we fail crating the `tun` iface, we also need to call `stopVpn` otherwise we may get stuck in ENABLING state
NA just code review and AppTP smoke tests
> Call stopvpn upon tun iface creation

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageAppListAdapter.kt
Task/Issue URL: https://app.asana.com/0/0/1203984881672162/f
Removed usage of `kotlinx.android.synthetic` from `ReportBreakageAppListAdapter`.
> Migrate ReportBreakageAppListAdapter

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/AppTPCompanyTrackersActivity.kt
Task/Issue URL: https://app.asana.com/0/0/1203984881672166/f
Removed usage of `kotlinx.android.synthetic` from `AppTPCompanyTrackersActivity`.
> Migrate AppTPCompanyTrackersActivity

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/PastWeekTrackerActivityContentView.kt
Task/Issue URL: https://app.asana.com/0/0/1203984881672167/f
Removed usage of `kotlinx.android.synthetic` from `PastWeekTrackerActivityContentView`.
> Migrate PastWeekTrackerActivityContentView

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionAppsAdapter.kt
Task/Issue URL: https://app.asana.com/0/0/1203984881672161/f
Removed usage of `kotlinx.android.synthetic` in `TrackingProtectionAppsAdapter`.
> Migrate TrackingProtectionAppsAdapter

- app-tracking-protection/vpn-impl/build.gradle
Task/Issue URL: https://app.asana.com/0/1202279501986195/1203985450170811/f
Removed kotlin-android-extensions plugin from AppTP code.
> AppTP: Remove the kotlin-android-extensions plugin

- app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203992422997845/f
Removes Kotlin synthetics from the `Cta` and uses `findViewById` instead.
> Remove Kotlin synthetics from Cta

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/inbox/1157893581871899/1203999234891249/1203999234891253
After updating the Site Permission dialog for location we didn't properly change the title. This PR fixes that.
_Site Location Permissions_
efore screenshot)|
---
- https://app.asana.com/0/0/1203999234891249
> ADS: Fix Site Location permission title

- app-tracking-protection/vpn-impl/build.gradle
Task/Issue URL: https://app.asana.com/0/1202552961248957/1201421366311638/f
Removed different work manager version from vpn-impl.
Develop
This branch
> Upgrade version.androidx.work - AppTP should not specify a different version as that is not used

- app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
- app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
- macos/macos-impl/src/main/java/com/duckduckgo/macos_impl/MacOsActivity.kt
- macos/macos-impl/src/main/java/com/duckduckgo/macos_impl/MacOsViewModel.kt
- macos/macos-impl/src/test/java/com/duckduckgo/macos_impl/waitlist/ui/MacOsViewModelTest.kt
- windows/windows-api/src/main/java/com/duckduckgo/windows.api/WindowsWaitlistFeature.kt
- windows/windows-impl/build.gradle
- windows/windows-impl/src/main/java/com/duckduckgo/windows/impl/UnusedWindowsWaitlistFeatureCodegenTrigger.kt
- windows/windows-impl/src/main/java/com/duckduckgo/windows/impl/WindowsWaitlistFeatureDI.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203935342025551/f
Adds feature flag onto waitlist feature.
There are 2 entry points:
- From macOS screen, if feature disabled, do not show link to waitlist
- From settings screen, if feature disabled, do not show setting item
_Feature 1_
_Feature 2_
> FeatureFlag waitlist

- app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
- app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
- macos/macos-impl/src/main/java/com/duckduckgo/macos_impl/MacOsActivity.kt
- macos/macos-impl/src/main/java/com/duckduckgo/macos_impl/MacOsViewModel.kt
- macos/macos-impl/src/test/java/com/duckduckgo/macos_impl/waitlist/ui/MacOsViewModelTest.kt
- windows/windows-api/src/main/java/com/duckduckgo/windows.api/WindowsWaitlistFeature.kt
- windows/windows-impl/build.gradle
- windows/windows-impl/src/main/java/com/duckduckgo/windows/impl/UnusedWindowsWaitlistFeatureCodegenTrigger.kt
- windows/windows-impl/src/main/java/com/duckduckgo/windows/impl/waitlist/ui/WindowsWaitlistActivity.kt
- windows/windows-impl/src/main/res/layout/activity_windows_waitlist.xml
- windows/windows-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203975081655927/f 
Adds notify me component to waitlist
_Feature 1_
> Add notifyme to waitlist

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1202279501986195/1203207391719615/f
Updated timeWindow to 7 days.
Check the issue in develop
INSERT INTO vpn_tracker VALUES(1380307511,'data.flurry.com','Verizon Media','Verizon Media','2023-02-19T11:42:18','2023-02-19',33,'com.socialnmobile.dictapps.notepad.color.note','ColorNote');
INSERT INTO vpn_tracker VALUES(1380307511,'data.flurry.com','Verizon Media','Verizon Media','2023-02-17T11:47:00','2023-02-17',60,'com.socialnmobile.dictapps.notepad.color.note','ColorNote');
INSERT INTO vpn_tracker VALUES(456730748,'www.google-analytics.com','Google LLC','Google','2023-02-19T11:43:08','2023-02-19',6,'com.soundcloud.android','SoundCloud');
INSERT INTO vpn_tracker VALUES(456730748,'g.doubleclick.net','Google …
> AppTP Bug: Can't access Tracker activity from 7 days ago

- privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204030500871801/f
Updated migration_10_11 in PrivacyConfigDatabase to drop the autofill_exceptions table if it exists.
This crash cannot be reproduced on emulators / pixel devices. Also, there are no reports on Pixel devices.
> Android: Crash in PrivacyConfigDatabaseKt$MIGRATION_10_11$

- app/src/main/java/com/duckduckgo/app/browser/favicon/DuckDuckGoFaviconManager.kt
- app/src/main/java/com/duckduckgo/app/global/image/GlobalGlideModule.kt
- app/src/main/java/com/duckduckgo/app/global/view/FaviconImageView.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementRecyclerAdapter.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/urlmatcher/AutofillDomainNameUrlMatcher.kt
- browser-api/src/main/java/com/duckduckgo/app/browser/favicon/FaviconManager.kt
- common/src/main/java/com/duckduckgo/app/global/UriExtension.kt
Task/Issue URL: https://app.asana.com/0/0/1203994780181874/f
Updates the favicon placeholder used when we can't get a real favicon in the autofill management screens. 
Note, favicons won't show immediately for a manually added site, so you will typically see the placeholder in these scenarios (they'll be cached after next visiting that site so it will show thereafter).
For each of the following; verify the favicon placeholder is correct in **both** management list screen and when clicking into the details for that credential.
> Improve the way we choose the favicon placeholder letter for autofill screens

- autofill/autofill-impl/src/main/res/layout/content_autofill_save_new_credentials.xml
- autofill/autofill-impl/src/main/res/layout/content_autofill_select_credentials_tooltip.xml
- autofill/autofill-impl/src/main/res/layout/content_autofill_update_existing_credentials.xml
- autofill/autofill-impl/src/main/res/values/styles.xml
Task/Issue URL: https://app.asana.com/0/0/1204065996696681/f
Update the style used for the autofill dialog titles (for saving, for updating and for selecting a saved credential):
- updates dialogs to use `DaxTextView` for its title
- using `h2` type as per designs
Complete the following, and verify the title in each of the dialogs looks like the design (linked in the asana task)
> Tweak autofill dialog title style

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
Task/Issue URL: https://app.asana.com/0/0/1204067551190951/f 
This PR avoids emitting the same state several times which can cause the app to crash when creating a drawable
> Avoid emitting same state multiple times

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncDeviceId.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/AppSyncDeviceIdsTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1204039315134731/f
Uses a random UUID as device Id when creating account.
_Feature 1_
> Use random uuid when account created

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsViewModel.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1204099438373198/f
Switches to ensure autofill save dialog prompt always includes the extra _onboarding_ text for now.
> Always show longer-form onboarding-style autofill save dialog

- common-ui/src/main/res/values-v23/design-system-theming.xml
- common-ui/src/main/res/values/design-system-theming.xml
- versions.properties
Task/Issue URL: https://app.asana.com/0/414730916066338/1204003071445738/f
Updated to use the `DayNight` base theme. Increased `webkit` version. Added `android:isLightTheme` with appropriate values in both light and dark themes.
Fixes https://github.com/duckduckgo/Android/issues/2878
Check the issue
Check the fix
> Bug: Dark mode not respected in WebView

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1204082334468711/f
We don't send `location_disabled` pixel anymore when the permission has been revoked forever by the user
- Uninstall previous version of Android app if already have permission configurations (or just clear storage on Settings)
- Install form this branch
- Navigate to maps.google.com
- Tap on "Your Location 🎯" button -> Dialog prompt appears
- Tap on "Enable" option -> System permission prompt appears
- Select "Don't Allow" option
- Tap on "Your Location 🎯" button **again** -> Dialog prompt appears
- Tap on "Enable" option **again**-> System permission prompt appears
- Select "Don't Allow" option **again**
- Tap on "Your Location 🎯" button **(for the 3rd time)**
> Remove location disabled pixel when there's not dialog prompt

- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SystemPermissionsHelper.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204096490114621/f
Fix inconsistency when not allowing camera permissions for the first time.
- First time user doesn't allow -> Show snackbar
- Second time user doesn't allow -> Show settings dialog
__Microphone_
- Uninstall previous version of Android app if already have permission configurations (or just clear storage on Settings)
- Go to `www.mictest.cc`
- Tap on "Test my mic" button -> Rationale dialog appears
- Tap on "Allow" option -> System permission prompt appears
- Select "Don't Allow" option
- Reload the page and tap on "Test my mic" button **again** -> Rationale dialog appears
- Tap on "Allow" option **again** -> System permission prompt appears
- Select "Don't Allow" option
__Camera_
- Go to …
> Fix isPermissionsRejectedForever() for camera permission

- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204096490114623/f
Deny permission request from website when system permissions haven't been allowed
- Uninstall previous version of Android app if already have permission configurations (or just clear storage on Settings)
- Go to `www.mictest.cc`
- Tap on "Test my mic" button -> Rationale dialog appears
- Tap on "Allow" option -> System permission prompt appears
- Select "Don't Allow" option -> Snackbar appears
- Reload the page and tap on "Test my mic" button **again** -> Rationale dialog appears
- Tap on "Allow" option **again** -> System permission prompt appears
- Select "Don't Allow" option -> Open Settings dialog appears
> Fix: Deny request when system permissions are not allowed

- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/global/view/FireDialog.kt
- app/src/main/java/com/duckduckgo/app/launch/LaunchBridgeActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203802507890823/f
Older code had used `MainScope` directly to get a `CoroutineScope`, because it pre-dated AndroidX providing coroutine support into most of the Android components (e.g., lifecycle-aware `lifecycleScope`).
In most places, direct use of `MainScope` can be replaced with `lifecycleScope` where it is available.
There are a few subtle differences (but should be positive, or at least neutral, changes):
- `lifecycleScope` coroutines will be cancelled appropriately with lifecycle changes. With `MainScope`, that wasn't the case and we should have been cleaning up after ourselves manually e.g., in `onDestroy()` but never were.
- `MainScope` uses `Dispatchers.Main` by default, whereas `lifecycleScope` uses …
> Replace usages of MainScope with more modern equivalents

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
> Update content scope scripts to latest version

- autofill/autofill-impl/src/main/res/layout/content_autofill_save_new_credentials.xml
- autofill/autofill-impl/src/main/res/layout/content_autofill_update_existing_credentials.xml
Task/Issue URL: https://app.asana.com/0/0/1204135366588345/f
Updates the button styles used on the "Not now" buttons for saving/update credential
> Update 'not now' buttons on autofill dialog to ghost style

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementRecyclerAdapter.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/suggestion/SuggestionListBuilder.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/suggestion/SuggestionListBuilderTest.kt
Task/Issue URL: https://app.asana.com/0/0/1204135364308878/f
Ensures that the logins appearing in the suggested sites section of credential management are sorted by the same sorting rules the rest of the list is.
From credential management screen, manually add the following logins: 
Visit nytimes.com and then access autofill from the overflow menu
> Fix sort order for autofill suggested sites

- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/text/DaxTextInput.kt
Task/Issue URL: https://app.asana.com/0/0/1204136779081352/f
When editing a passwords we want to restrict input to single lines only (a multi-line password doesn't make sense). However when viewing a long password we do want the text field to expand vertically to show it all (as having to horizontally scroll to see the full password is painful). This PR:
- restricts the password field to a single line **when editing** it
- restricts the password field to a single line when the password is hidden
- allows the password field to grow vertically to reveal the whole password when the password has been revealed, only if non editing it
> Restrict password entry to single lines in DaxTextInput view

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/PulseAnimation.kt
- app/src/main/java/com/duckduckgo/app/browser/shortcut/ShortcutReceiver.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/notifyme/NotifyMeViewModel.kt
- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/viewbinding/FragmentViewBindingDelegate.kt
- lint-rules/src/main/java/com/duckduckgo/lint/NoLifecycleObserverDetector.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1204091058652565/f 
Fixes lint rule.
_Feature 1_
> fixes lint rule and suppress non di usages

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
- app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml
Task/Issue URL: https://app.asana.com/0/1200905986587319/1204131202912051/f
Fixed ripple on view all recent activity item (replaced `OneLineListItem` with `DaxTextView` as pe updated design).
|![view_all_recent_activity_tapped_before](https://user-images.githubusercontent.com/7963079/224310217-ec2cc9e3-8af9-4c07-94fc-7377819b85b9.png)|![view_all_recent_activity_tapped_after](https://user-images.githubusercontent.com/7963079/224310894-c0000576-abd1-4533-8a07-f1bf1c7a9a69.png)|
> Android: Ripple not displayed on the whole item

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/EncodingExtension.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncDeviceId.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncRepository.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncService.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncServiceRemote.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/AppSyncDeviceIdsTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncRepositoryTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncServiceRemoteTest.kt
- sync/sync-lib/src/main/java/com/duckduckgo/sync/crypto/SyncNativeLib.kt
Task/Issue URL: https://app.asana.com/0/1201493110486074/1203835825731590/f 
Encrypts device info (name and type) on all auth flows.
Also changes QR format to follow b64 encoding
(you will need 2 devices to test some of the auth flows)
_create account and login_
_connect_ (device B should have a camera)
> Encrypt device info on auth flows

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
- vpn-network/vpn-network-api/src/main/java/com/duckduckgo/vpn/network/api/VpnNetwork.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204154532535669/f
Move the `tun` configuration for IPv6 from the VPN layer to the network layer.
See the [asana](https://app.asana.com/0/488551667048375/1204154532535669/f) task for more info
_Verify IPv6 configuration_
> Move IPv6 tun configuration from VPN layer to network layer

- app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/service/FakeVpnReminderNotificationContentPlugin.kt
- app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnReminderNotificationContentPlugin.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnReminderReceiverManager.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTpDisabledContentPlugin.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTpReminderNotificationUtils.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTpRevokedContentPlugin.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/VpnReminderNotificationContentPluginPoint.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldAlertNotificationBuilder.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldReminderNotificationScheduler.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/VpnReminderNotificationBuilder.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/service/notification/VpnReminderNotificationContentPluginKtTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldReminderNotificationSchedulerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204088747317856/f
This PR includes introducing content plugins for VPN reminder notifications. See more in task for info.
_Disable AppTP_
_Schedule notif_
_Update App_
_Revoke Notification_
> Create pluginpoint for reminder notifs

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/autofill/AutofillCredentialsSelectionResultHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/autofill/AutofillFireproofDialogSuppressor.kt
- app/src/test/java/com/duckduckgo/app/browser/autofill/AutofillCredentialsSelectionResultHandlerTest.kt
- app/src/test/java/com/duckduckgo/app/browser/autofill/RealAutofillFireproofDialogSuppressorTest.kt
- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillCredentialDialogs.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/updating/AutofillUpdatingExistingCredentialsDialogFragment.kt
Task/Issue URL: https://app.asana.com/0/0/1204135366588349/f
We don't want the fireproofing prompts and autofill prompts to collide as it hurts the UX to have a barrage of prompts. This PR adds a suppression to fireproofing prompts such that fireproofing prompts will not show:
- if the autofill save/update dialog is currently showing
- if the autofill save/update dialog was shown in the last 10 seconds (counted from time it is dismissed)
Logcat filter: `canPromptUserAboutFireproofing|RealAutofillFireproofDialogSuppressor`
- Visit https://fill.dev/form/login-simple and attempt a login. Don't dismiss the autofill dialog.
- Verify autofill save dialog is showing; also verify in logcat that dialog is showing (`dialog visibility changed to true`)
- Verify fireproofing prompt is **not** shown; …
> Suppress fireproof prompts when it would show over (or shortly after) autofill dialog

- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/Theming.kt
- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/store/ThemingSharedPreferences.kt
Task/Issue URL: https://app.asana.com/0/1174433894299346/1204115829299957
We want to ensure that the user's device selected theme is respected in DDG. For that, we are not defaulting to the System Default theme instead of Light. Dax Onboarding will always happen in Light theme, but the Browser and other screens will default to whatever the user selected.
_Light theme as default_
_Dark theme as default_
> System Default as default theme instead of Light

- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/OneLineListItem.kt
- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/TwoLineListItem.kt
- common-ui/src/main/res/layout/view_one_line_list_item.xml
- common-ui/src/main/res/layout/view_two_line_item.xml
- common-ui/src/main/res/values/design-system-dimensions.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204153756556044/f
Increase trailing icon touch target for `OneLineListItem` and `TwoLineListItem` components
_OneLineListItem_
- Go to Settings > App Components Design Preview
- Go to List Items tab
_TwoLineListItem_
- Go to Settings > App Components Design Preview
- Go to List Items tab
_Bookmarks_
- Go to Bookmarks
> ADS: Edit ListItems touch target

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/res/layout/fragment_browser_tab.xml
- app/src/main/res/layout/include_new_browser_tab.xml
- app/src/main/res/layout/include_omnibar_toolbar.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203992423492236/f
Removes Kotlin synthetics from the `BrowserTabFragment`.
> Remove synthetics from BrowserTabFragment

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNamesTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/downloads/DownloadsAdapter.kt
- app/src/main/java/com/duckduckgo/app/downloads/DownloadsItemListener.kt
- app/src/main/java/com/duckduckgo/app/downloads/DownloadsViewModel.kt
- app/src/main/java/com/duckduckgo/app/onboarding/di/WelcomePageModule.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModel.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModel.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/test/java/com/duckduckgo/app/downloads/DownloadsViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptorTest.kt
- app/src/test/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/statistics/pixels/PixelNameTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Task/Issue URL:  
https://app.asana.com/0/69071770703008/1203884929941926/f
https://app.asana.com/0/69071770703008/1203353347663734/f
Removed temporary pixels added as part of notifications permissions changes on Android 13.
- Pixel `m_notify_me_component_notify_me_button_pressed` (AppTP & Browser)
- Pixel `m_notify_me_component_close_button_pressed` (AppTP & Browser)
- Param `os_version_13_or_above` set from onboarding when default browser set / not set (Browser)
DDG set as default browser
DDG NOT set as default browser + notify me
> Followup: New temporary pixels for "Notify Me" component / Follow-up: remove parameter for Android13

- app/src/main/java/com/duckduckgo/app/di/NetworkModule.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204265639917313/f
Defer OkHttp init to reduce start up time.
We're using the `Call.Factory` to lazily initialize the http client. The nice thing about `Call.Factory` is that it is called in a background thread.
Smoke tests
> Deferred okhttp init

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/cohort/CohortStore.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/cohort/CohortPixelInterceptorTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/cohort/RealCohortStoreTest.kt
- common/src/main/java/com/duckduckgo/app/utils/CheckMainThread.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204265639917299/f
Ensure calls to `CohortStore` are not done in the main thread.
The approach taken is has been:
* marking method as `WorkerThread`
* in internal builds `checkMainThread` and throw
* in production build we don't do the `checkMainThread`
_Check cohort is assigned_
Smoke test AppTP as well is useful
> Prevent ANR when assigning AppTP cohort

- app/src/main/java/com/duckduckgo/app/onboarding/di/WelcomePageModule.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingActivity.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingViewModel.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/customisationexperiment/DDGFeatureOnboardingOption.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/customisationexperiment/MultiselectListItem.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageView.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModel.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/res/drawable/background_multiselect_list_item.xml
- app/src/main/res/drawable/background_multiselect_list_item_selected.xml
- app/src/main/res/layout-land/content_onboarding_welcome.xml
- app/src/main/res/layout/content_onboarding_welcome.xml
- app/src/main/res/layout/include_dax_dialog_cta.xml
- app/src/main/res/layout/include_dax_multiselect_dialog_cta.xml
- app/src/main/res/layout/view_multiselect_list_item.xml
- app/src/main/res/values-sw600dp/bools.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/bools.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/com/duckduckgo/app/onboarding/ui/OnboardingViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
- common-ui/src/main/res/values/attrs-lists.xml
- common-ui/src/main/res/values/design-system-colors.xml
- common-ui/src/main/res/values/design-system-theming.xml
- common-ui/src/main/res/values/temp_colors.xml
- common-ui/src/main/res/values/widgets.xml
- statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1203826977705495/f
Implement Onboarding Customisation experiment where experimental group will see an extra onboarding dialog with DDG feature options.
_Change all variants to 0 except for the `mj` variant_
_New multiselect dialog_
- Uninstall previous version of the app or clear storage
- Welcome animation will appear
_Skip selecting options_
- Follow same instructions as "New multiselect dialog" test
- Tap on `Skip This Step`
_Continue without options selected_
- Follow same instructions as "New multiselect dialog" test
- Tap on any option to select it
- Remove the selection tapping again
- Tap on `Continue` button
_Continue with options selected_
- Follow same instructions as "New multiselect dialog" test …
> Onboarding Customisation Experiment

- app/src/androidTest/java/com/duckduckgo/app/notification/NotificationHandlerServiceTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
- app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt
- app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
- app/src/main/java/com/duckduckgo/app/notification/AppNotificationSender.kt
- app/src/main/java/com/duckduckgo/app/notification/NotificationFactory.kt
- app/src/main/java/com/duckduckgo/app/notification/NotificationHandlerService.kt
- app/src/main/java/com/duckduckgo/app/notification/model/AppFeatureNotification.kt
- app/src/main/java/com/duckduckgo/app/notification/model/ClearDataNotification.kt
- app/src/main/java/com/duckduckgo/app/notification/model/PrivacyProtectionNotification.kt
- app/src/main/java/com/duckduckgo/app/notification/model/WebsiteNotification.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
- app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
- browser-api/src/main/java/com/duckduckgo/app/notification/model/SchedulableNotification.kt
- browser-api/src/main/java/com/duckduckgo/app/notification/model/SchedulableNotificationPlugin.kt
- windows/windows-impl/src/main/java/com/duckduckgo/windows/impl/waitlist/WindowsWaitlistCodeNotification.kt
- windows/windows-impl/src/main/java/com/duckduckgo/windows/impl/waitlist/ui/WindowsWaitlistActivity.kt
- windows/windows-impl/src/main/java/com/duckduckgo/windows/impl/waitlist/ui/WindowsWaitlistViewModel.kt
- windows/windows-impl/src/test/java/com/duckduckgo/windows/impl/WindowsWaitlistNotificationPluginTest.kt
- windows/windows-impl/src/test/java/com/duckduckgo/windows/impl/ui/WindowsWaitlistViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204319613139785/f
Refactored inactive user notifications. Fixed opening the app after tap on notification.
> Android bug: Tapping on notifications doesn't open the app

- .github/workflows/ads-end-to-end.yml
- .github/workflows/build-debug-apk.yaml
- .github/workflows/end-to-end.yml
- .github/workflows/privacy-dashboard-end-to-end.yml
- app-build-config/app-build-config-api/src/main/java/com/duckduckgo/appbuildconfig/api/AppBuildConfig.kt
- app/build.gradle
- app/src/main/java/com/duckduckgo/app/buildconfig/RealAppBuildConfig.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204340991927492/f
This PR makes sure the default variant is always used when running end to end tests on CI
> Make sure default variant is always used in CI end-2-end tests

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnOnboardingActivity.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnOnboardingViewModel.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt
- app/src/androidTest/java/com/duckduckgo/app/notification/AndroidNotificationSchedulerTest.kt
- app/src/androidTest/java/com/duckduckgo/app/notification/model/EnableAppTpNotificationTest.kt
- app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt
- app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
- app/src/main/java/com/duckduckgo/app/notification/NotificationRegistrar.kt
- app/src/main/java/com/duckduckgo/app/notification/model/EnableAppTpNotification.kt
- app/src/main/res/values/donottranslate.xml
- app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/0/1204241239463176/f
Added all variants. Implemented the 2 notifications for variants `zm`/`zn`.
_Variant zm_
_Variant zn_
| Variant zm notification  | Variant zn notification |
|![one_easy_step_notification](https://user-images.githubusercontent.com/7963079/230159982-89b9ecdc-62d9-4a4b-9338-a3c9680362fa.png)|![next_level_notification](https://user-images.githubusercontent.com/7963079/230160003-5f6f994d-c605-4fdb-bafc-a4143b19ae09.png)|
> Implement notifications for [Experiment] Increase retention through AppTP promotions

- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillFeature.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillCapabilityCheckerImpl.kt
- privacy-config/privacy-config-impl/src/main/res/raw/privacy_config.json
- privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
Task/Issue URL: https://app.asana.com/0/0/1204370666975082/f
Renames the autofill subfeatures, as is required to prepare for the autofill release.
**Start with develop branch.**
**Use new remote config**
Change URL we use for the remote config (it's defined in `PrivacyFeatureName.PRIVACY_REMOTE_CONFIG_URL`)
**Checkout the branch from this PR**
> Change autofill subfeature names in prep for releasing

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/res/layout/include_dax_dialog_cta.xml
- statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Task/Issue URL: https://app.asana.com/0/0/1204241239463177/f
Added a variation for the last Dax dialog.
_Variant zo_ 
|![dax_dialog_original](https://user-images.githubusercontent.com/7963079/231439651-38d7e285-d027-4f9a-8854-039b64f248fc.png)|![dax_dialog_variant](https://user-images.githubusercontent.com/7963079/231439660-1872a15b-3748-4b91-8021-7f1f0af32b67.png)|
> Implement Dax dialog in the last step of onboarding

- app/src/androidTest/java/com/duckduckgo/app/referencetests/FirstPartyCookiesReferenceTest.kt
- app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/features/firstparty/FirstPartyCookiesModifier.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/features/firstparty/FirstPartyCookiesModifierWorker.kt
- cookies/cookies-impl/src/test/java/com/duckduckgo/cookies/impl/features/firstparty/FirstPartyCookiesModifierWorkerSchedulerTest.kt
- cookies/cookies-impl/src/test/java/com/duckduckgo/cookies/impl/features/firstparty/FirstPartyCookiesModifierWorkerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204397066248837/f 
This PR checks if the cookies table and is_httponly column exist before executing the query.
> Check table and column exist before executing query

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/blocklist/AppTrackerListService.kt
- app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/trackers/AppTracker.kt
- app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/trackers/AppTrackerJsonParser.kt
- app-tracking-protection/vpn-store/src/test/java/com/duckduckgo/mobile/android/vpn/trackers/AppTrackerJsonParserTest.kt
- app-tracking-protection/vpn-store/src/test/resources/full_app_trackers_blocklist.json
Task/Issue URL: https://app.asana.com/0/0/1204239971719179/f
Now that we're using the cumulative blocklist for AppTP, we've decided to use a new endpoint to support the new list format and any future updates. We'll maintain the old endpoint, without updates, for users on earlier versions.
The endpoint is up & running with the old (current) list, but in the new format (which I'll alter today to include entity scores).
To test:
Install app from `develop`, enable AppTP & let block some trackers
Update app from this branch, verify that database transitions smoothly without trying to migrate to a new version
> AppTP: Change endpoint for blocklist to pull new format

- app-tracking-protection/app-tracking-api/src/main/java/com/duckduckgo/mobile/android/app/tracking/ui/AppTrackingProtectionScreens.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnOnboardingActivity.kt
- app/src/main/java/com/duckduckgo/app/notification/model/EnableAppTpNotification.kt
Task/Issue URL: https://app.asana.com/0/0/1204411036946047/f
Used the new navlib to open AppTP onboarding from the notification.
> Replace all intents as the way activities are started has changed in develop

- .github/workflows/external-ref-tests.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204422679933921/f 
This PR adds a new GH workflow for the privacy team so they can run it before releasing new reference tests
[This](https://github.com/duckduckgo/Android/actions/runs/4746189594/jobs/8441926133) workflow should be red. It pulls from a testing branch in the reference tests repo that I created to explicitly make one test fail and prove that our workflow pulls from the branch, copy the files and execute the new tests.
> Add external reference test workflow

- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/TextAlertDialogBuilder.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204423592674026/f 
Fixes asking users multiple times for feedback when they dismiss the dialog.
Issue: `onDialogCancelled` was only triggered when user clicks back button, not if they click outside the container.
_Feature 1_
_Feature 2_
> Fix cancelled callback on dialogs

- app/src/androidTest/java/com/duckduckgo/app/referencetests/FireproofingReferenceTest.kt
- app/src/androidTest/java/com/duckduckgo/cookies/impl/SQLCookieRemoverTest.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/CookiesPixelName.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/SQLCookieRemover.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/features/firstparty/FirstPartyCookiesModifier.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204439154734764/f 
This PR checks it the cookies table exists prior trying to execute the delete query.
> Check if table exists before executing query

- app/src/play/java/com/duckduckgo/referral/PlayStoreAppReferrerStateListener.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1204307243474497/f
Adopt the new [queryIntentServices()](https://developer.android.com/reference/android/content/pm/PackageManager#queryIntentServices(android.content.Intent,%20android.content.pm.PackageManager.ResolveInfoFlags)) on >= API 33
On >= Android 13 / Tiramisu
** On a device with Play Services**
** On an emulator without Play Services**
> Added new queryIntentServices() method for API >= 33

- app/build.gradle
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
- build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1204458968322711/f
Removes the last usages of synthetics in `WelcomeFragment` and removes the `kotlin-android-extensions` plugin.
> Disable Kotlin synthetics

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204454121220459/f
When we detect users are navigating to a URL that could be consumed by a native app, we offer a snackbar with an option to launch that app. However, since we don't control the intent that will be used, there is a possibility our app will crash when we use that intent with `startActivity` due to an `ActivityNotFoundException` (which is happening according to our crash data)
> Ensure we catch ActivityNotFoundExceptions when opening external app links

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/AccountObserver.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncRepository.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncService.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/di/SyncModule.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivity.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModel.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/SaveRecoveryCodeViewModel.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/AppSyncDeviceIdsTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncRepositoryTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModelTest.kt
- sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncStore.kt
- sync/sync-store/src/test/java/com/duckduckgo/sync/store/SyncSharedPrefsStoreTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204341643230613/f 
Ensures if device has been signed out remotely, we remove keys when any request/authentication fails with invalid_code credentials.
_Feature 1_
> Handle being remotely signed out

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/heartbeat/VpnServiceHeartbeat.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/1202279501986195/1204415151858394/f
Updated logic when VPN is restarted to avoid starting it twice.
> Updated logic when VPN is restarted to avoid starting it twice.

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModel.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/VpnLastTrackersBlockedCollector.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/debug/SendTrackerDebugReceiver.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/di/VpnAppModule.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/removal/VpnFeatureRemover.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/tracker/AppTrackerRecorder.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/AppTPCompanyTrackersViewModel.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModel.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModelTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTpEnabledNotificationContentPluginTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/PrivacyReportViewModelTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldDailyNotificationFactoryTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldWeeklyNotificationFactoryTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/AppTPCompanyTrackersViewModelTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModelTest.kt
- app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/rules/ExceptionRulesDebugActivity.kt
- app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/trackers/DeleteTrackersDebugReceiver.kt
- app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/VpnTrackerDao.kt
- app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/model/VpnDatabaseModels.kt
- app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/stats/AppTrackerBlockingStatsRepository.kt
- app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabase.kt
- app-tracking-protection/vpn-store/src/test/java/com/duckduckgo/mobile/android/vpn/stats/AppTrackerBlockingStatsRepositoryTest.kt
- app/src/internal/java/com/duckduckgo/app/flipper/plugins/TrackerProtectionFlipperPlugin.kt
- app/src/main/java/com/duckduckgo/app/privacy/cleanup/TrackersDbCleanerScheduler.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204479514332481/f
See the [asana task](https://app.asana.com/0/488551667048375/1204479514332481/f) for more context but in a nutshel:
* This PR adds support for changes in tracker entities
* It moves the `AppTrackerBlockingStatsRepository` repository to the `store` module and makes the vpn tracker DAO private so that all consumers have to go through the repository
* This way we sealed the UI from any meaningful change
_Test entity changes_
> Support changes in the tracker entities

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204513195956995/f 
Monitor if the webview renderer is killed or gone. 
_Feature 1_
> Monitor webview pixels when renderer crashes

- node_modules/@duckduckgo/autofill/README.md
- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1204538113123459/1204538113123459
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.5.1
Updates Autofill to version [6.5.1](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.5.1).
* Disable pixel for all platforms but extension by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/309
* Fix release script for BSK by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/310
Included in 6.5.0:
- Improve debugging by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/293
- Reduce the calls on check position when there are many mutations by @alistairjcbrown in https://github.com/duckduckgo/duckduckgo-autofill/pull/288
- Window release fetch tags …
> Update autofill to 6.5.1

- cookies/cookies-impl/build.gradle
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/CookiesContentScopeConfigPlugin.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/di/CookiesModule.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/features/CookiesFeaturePlugin.kt
- cookies/cookies-impl/src/test/java/com/duckduckgo/cookies/impl/CookiesContentScopeConfigPluginTest.kt
- cookies/cookies-impl/src/test/java/com/duckduckgo/cookies/impl/features/CookiesFeaturePluginTest.kt
- cookies/cookies-store/src/main/java/com/duckduckgo/cookies/store/CookiesDatabase.kt
- cookies/cookies-store/src/main/java/com/duckduckgo/cookies/store/CookiesDatabaseModels.kt
- cookies/cookies-store/src/main/java/com/duckduckgo/cookies/store/contentscopescripts/ContentScopeScriptsCookieDao.kt
- cookies/cookies-store/src/main/java/com/duckduckgo/cookies/store/contentscopescripts/ContentScopeScriptsCookieRepository.kt
Task/Issue URL: https://app.asana.com/0/0/1204498721431853/f
Implements Android cookie parsing for 'cookie' for ContentScopeScripts to consume.
(x is a random value)
> Add cookie feature to content scope scripts

- app/src/androidTest/java/com/duckduckgo/app/referencetests/FireproofingReferenceTest.kt
- app/src/androidTest/java/com/duckduckgo/cookies/impl/SQLCookieRemoverTest.kt
- cookies/cookies-impl/build.gradle
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/CookiesFeatureNameUtil.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/CookiesPixelName.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/SQLCookieRemover.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/features/firstparty/FirstPartyCookiesModifier.kt
- cookies/cookies-impl/src/test/java/com/duckduckgo/cookies/impl/CookiesFeatureNameUtilTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204599953020604/f 
This PR replaces the crash pixels for cookie queries and instead adds regular pixels.
> Replace cookie crashes with regular pixels

- app/src/main/res/layout/activity_system_search.xml
- app/src/main/res/layout/content_about_duck_duck_go.xml
- app/src/main/res/layout/include_new_browser_tab.xml
- app/src/main/res/layout/include_omnibar_toolbar.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204623212032711/f
On Android M devices, the DDG logo isn't rendering properly, showing only a circle. This PR switches to using `app:srcCompat` to reference the logo which fixes the issue.
Test **both** on an Android M device|emulator and a newer API
|![new-tab-before](https://github.com/duckduckgo/Android/assets/1336281/26904867-890b-4907-a5a0-0af41ec2a33c)|![new-tab-after](https://github.com/duckduckgo/Android/assets/1336281/dc35a819-6d33-4b38-8cf5-36e7865dbd32)|
> Ensure the new DDG logo renders correctly on Android M devices.

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementActivity.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementDeviceUnsupportedMode.kt
- autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_device_unsupported.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
- secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/RealSecureStorage.kt
- secure-storage/secure-storage-impl/src/test/java/com/duckduckgo/securestorage/impl/RealSecureStorageTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204628156369973/f
Adds a screen which shows when a user tries to access Logins on a device where it is unsupported. Unsupported devices are where we can't access EncryptedSharedPreferences.
There's about to be another set of autofill string changes coming that will bring translations for this along with it.
_Logins still works as normal_
_Simulate an supported device_
> Add screen to show when we detect device can't support Logins

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/selecting/AutofillSelectCredentialsListBuilder.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/selecting/RealAutofillSelectCredentialsListBuilderTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204391947652312/f
When offering to autofill saved logins, we show a list of matching logins. Previously, we'd only apply the primary button style to the first URL which perfectly matched the current page.
With this PR, we instead apply the primary button style to the first URL in the list, regardless of whether that is for a perfect or partial match.
> Ensure best autofill match is always primary button style

- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/domain/app/LoginCredentials.kt
- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/store/AutofillStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementActivity.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
- autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt
- secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorageModels.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204238566022609/f
Adds a snackbar shown to the user after they delete a login from the login management screen (both in list view, and in details view). 
The snackbar will have an UNDO button on it, which will reinsert the login credential back into the DB if pressed.
🌏 Translations will follow separately.
> Show snackbar with UNDO button when deleting a login

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204670807847639/f
The AppTP tracking activity screen used to show an incorrect number of tracking companies. This PR fixes that.
> Display correct number of tracking companies

- downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/PendingFileDownloadCompressTest.kt
Task/Issue URL: https://app.asana.com/0/1200905986587319/1204686614376690/f
Updated test.
Tests in `PendingFileDownloadCompressTest` should pass.
> Android: Fix whenDownloadUrlIsTooLargeAndToInputDataCalledThenAddCompressedUrl

- common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/textinput/ComponentTextInputFragment.kt
- common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/text/DaxTextInput.kt
- common-ui/src/main/res/layout/component_text_input_view.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204667366884988/f
Added `fun setEndIcon(endIconRes: Int?, contentDescription: String? = null)` method to TextInput interface so we can edit it programmatically and not only from the xml file
- Go to Settings > App Components Design Preview
- Select Text Input tab
> ADS: Allow set endIcon programmatically on TextInput component

- app/src/test/java/com/duckduckgo/app/sync/SavedSitesSyncDataProviderTest.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt
Task/Issue URL: https://app.asana.com/0/0/1204770002414582/f
We can improve the number of syncable objects sent when requesting a patch to Sync.
Instead of sending the folder and all it’s children as separate objects, we only send the objects needed.
Details in task
> Sync: Optimize bookmarks JSON provision

- app/src/androidTest/java/com/duckduckgo/app/global/view/ClearPersonalDataActionTest.kt
- app/src/main/java/com/duckduckgo/app/di/PrivacyModule.kt
- app/src/main/java/com/duckduckgo/app/global/view/ClearPersonalDataAction.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/service/SavedSitesDataCleaner.kt
- saved-sites/saved-sites-store/src/main/java/com/duckduckgo/savedsites/store/SavedSitesEntitiesDao.kt
Task/Issue URL: https://app.asana.com/0/1201493110486074/1204879487866164/f
Task/Issue URL: https://app.asana.com/0/1201493110486074/1204874751768176/f
_Sync Disabled - App open clearing_
_Sync Disabled - Fire button_
> Saved Sites: prune objects on app launch / fire button

- .github/ISSUE_TEMPLATE/config.yml
- .github/issue-pr-template.md
- .github/issue-reply-template.md
- .github/pr-reply-template.md
- .github/workflows/action-issue-opened.yaml
- .github/workflows/action-pr-merged.yaml
- .github/workflows/action-pr-opened.yaml
- .github/workflows/action-pr-reviewed.yaml
- .github/workflows/ads-end-to-end.yml
- CONTRIBUTING.md
- app/src/main/java/com/duckduckgo/app/survey/api/SurveyService.kt
Task/Issue URL: https://app.asana.com/0/1174433894299346/1204558888185157/f
This PR adds the changes described in the task above.
- New workflows to react to issues created
- New workflow for PR opened
- Updated Contributing guidelines to reflect we don’t take feature requests
> Sunsetting Github AoR

- app/src/androidTest/java/com/duckduckgo/app/di/StubStatisticsModule.kt
- app/src/main/java/com/duckduckgo/app/di/StatisticsModule.kt
- app/src/test/java/com/duckduckgo/app/statistics/AtbInitializerTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/AtbInitializer.kt
Task/Issue URL: https://app.asana.com/0/0/1204904897721603/f
Disable sending retention events pixel for new installs.
_User is not added to the segment_
- Add log in Line 105 on `FeatureSegmentsManager`, before the return line
(e.g. `Timber.d("Feature Segment isSendPixelEnabled: ${featureSegmentsDataStore.featureSegmentsEnabled}")`
- Set DDG as default in onboarding
_Rest of events that need to be tested_ **(Optional)**
- Add log in Line 105 on `FeatureSegmentsManager`, before the return line
(e.g. `Timber.d("Feature Segment isSendPixelEnabled: ${featureSegmentsDataStore.featureSegmentsEnabled}")`
- Choose any event from the list in this task: https://app.asana.com/0/0/1204620497244294/f
_Send daily pixel disabled_
- Add log in Line 105 on …
> Disable segment pixel for new installs

- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataObserver.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1204942882074644/f 
When Sync is in progress, we shouldn’t listen to underlying changes. This is because when a sync is in progress, it could be modifying the SavedSites. The Observer is then triggered since changes are applied to the db.
> Sync: DataObserver should not be triggered when sync in progress

- app/src/androidTest/java/com/duckduckgo/app/notification/AndroidNotificationSchedulerTest.kt
- app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt
- app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/0/1204988347737980/f
Implemented a new experiment which has clear data notifications bug fix in the experiment variant
_Change all variants to 0 except for the `zp` variant_
_Put a log in Line 90 in `AndroidNotificationScheduler.kt` to know if clearData notification is scheduled_
_Clear Data Notification is scheduled the first time the app is opened_
- Uninstall previous version of the app or clear storage
> Experiment for push notification fix

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClient.kt
- content-scope-scripts/content-scope-scripts-api/build.gradle
- content-scope-scripts/content-scope-scripts-api/src/main/java/com/duckduckgo/contentscopescripts/api/ContentScopeScripts.kt
- content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/ContentScopeScriptsFeature.kt
- content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScripts.kt
- content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/RealMessagingContentScopeScripts.kt
- content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScriptsTest.kt
- content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/RealMessagingContentScopeScriptsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204659079168053/f
This PR adds the ability to enable/disable Content Scope Scripts via remote config.
> Add content scope scripts feature toggle

- .maestro/privacy_tests/10_-_Query_Parameters,_utm_source_and_1_standard_parameter.yaml
- .maestro/privacy_tests/11_-_Query_Parameters,_utm_source_and_utm_medium.yaml
- .maestro/privacy_tests/12_-_Query_Parameters,_fbclid,_fb_source_and_1_standard_parameter.yaml
- .maestro/privacy_tests/13_-_Query_Parameters,_link_which_should_not_be_rewritten.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205014184005634/f
This adds Maestro tests for query parameters. 
End-to-End test run here: https://github.com/duckduckgo/Android/actions/runs/5551463161/jobs/10137628334 ✅
> Add query parameter UI tests

- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DownloaderUtil.kt
- downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/DownloaderUtilTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1202994708537217/f
Support getting filename from `filename*` and prioritize over `filename`
- Download the file from https://user.fm/files/v2-a5fa215da9e2d03e1cd4d0674dfdd34c/%E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6%E5%90%8D%E6%B5%8B%E8%AF%95.zip
- Check that the filename is "中文文件名测试.zip” instead of "%E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6%E5%90%8D%E6%B5%8B%E8%AF%95.zip”
> Add support for filename * in Content-Disposition & prioritize it over filename

- .github/workflows/docs.yml
- build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1204998944404726/f 
This PR adds a new workflow to generate docs and deploy them to gh pages when a push is made to develop 
N/A
> Add public API docs

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205077297202827/f
Restricts background tabs from showing user-facing dialogs (which would otherwise appear over the active tab)
_Testing Javascript-driven dialogs_
_Testing native-driven dialogs_
> Restrict dialogs showing when triggered from inactive tabs

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205097693997794/f 
----- 
> Update reference tests to version 1689778581

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205119826833459/f 
----- 
> Update content scope scripts to version 4.27.1

- app/src/main/java/com/duckduckgo/app/tabs/db/TabsDbSanitizer.kt
- app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
- common/common-utils/src/main/java/com/duckduckgo/app/utils/ConflatedJob.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205112415074827/f
Removed `runblocking` block in `TabDbSanitizer` class. 
- create tabs
- delete tabs
- rotate screen while on TabSwitcherActivity
- switch between foreground / background (this triggers the purge for deletable tabs).
> Android ANR: com.duckduckgo.app.tabs.db.TabsDbSanitizer.onStart(TabsDbSanitizer.kt:37)

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205122417156698/f
Updated the default paper size when printing.
> Android: Default to A4 when printing everywhere apart from NA

- app/build.gradle
- build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1205153634789947/f 
This PR fixes a wrong use of an internal module that was using implementation instead of internalImplementation. It also adds a check so it doesn't happen again.
> Fix internal dependencies and add gradle checks

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205177934310069/f 
----- 
> Update content scope scripts to version 4.30.0

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/provider/CredentialsSyncDataProvider.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/provider/CredentialsSyncDataProviderTest.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt
- sync/sync-api/src/main/java/com/duckduckgo/sync/api/engine/Models.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/RealSyncEngine.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/engine/SyncApiClientTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/engine/SyncEngineTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205093266805616/f 
SyncEngine performs a different sync process if it's feature first sync, no matter what the trigger was.
(using 2 devices)
_Feature 1_
> First sync per feature

- app/src/internal/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205183481775449/f 
This PR adds a new UA override
> Add ua override to remove both app id and version

- common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/CustomAlertDialogBuilder.kt
- common/common-ui/src/main/res/values/widgets.xml
https://app.asana.com/0/488551667048375/1204064393605065/f
Fix wrong background for autofill tooltip. Using `background` to set a background color caused an artifact to appear on autofill tooltip. Using `colorOnSurface` instead
Settings -> Web tracking protection -> Unprotected Sites -> Add or edit -> Long press on text field
> Fix incorrect autofill tooltip style on dialogs

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205208355997319/f 
----- 
> Update content scope scripts to version 4.31.0

- app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/rules/ExceptionRulesDebugReceiver.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205207024178124/f
Fix issue where `ExceptionRulesDebugReceiverRegister` was wiping the database in `onVPNStop` even if `exceptionRulesSavedState` was empty. Increase logging slightly for easier debugging of future issues.
> Fix AppTP Bug: Exclusion list wiped on VPN restart - Round 2

- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205182451164978/f
Added confirmation prompt before deleting all tabs.
| Before - No confirmation  | After - Confirmation prompt |
|![tabs_deleted_before](https://github.com/duckduckgo/Android/assets/7963079/7b639628-318c-4a19-8bd0-ab3a0873cc68)|![close_tabs_confirmation](https://github.com/duckduckgo/Android/assets/7963079/26e090d0-a49a-49b3-abba-ad731249d122)|
> ['Close all tabs' confirmation]: Implementation for 'Close all tabs' confirmation

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
- app/src/androidTest/java/com/duckduckgo/app/email/EmailInjectorJsTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/AutofillCapabilityCheckerImplTest.kt
- content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScriptsTest.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
- feature-toggles/feature-toggles-impl/build.gradle
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/FeatureTogglesTest.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/TestTriggerFeature.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205213514616979/f
Incremental rollouts did not maintain backwards compatibility upon app update
Bug repro steps:
- Expected:
- Actual
Bug repro steps:
> Fix incremental rollouts backwards compat upon app updates

- .maestro/autofill/0_all.yaml
- .maestro/autofill/1_autofill_shown_in_overflow.yaml
- .maestro/autofill/2_autofill_reach_creds_management.yaml
- .maestro/autofill/3_autofill_manually_add_cred.yaml
- .maestro/autofill/3_script.js
- .maestro/autofill/4_search_logins.yaml
- .maestro/autofill/smoke.yaml
- .maestro/release_tests/9_-_autofill_available.yaml
- app/build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1203874354762345/f
Adds maestro tests for main autofill flows.
Note, only a subset of the flows are suitable for a general smoke test as at a certain point it relies on the device/emulator having a PIN/Password set. 
`.maestro/autofill/smoke.yaml`: suitable for general purpose smoke testing (will ensure login option appears in the overflow)
`.maestro/autofill/0_all.yaml`: suitable only if the device has device-level authentication configured
> Add maestro tests for autofill flows

- app/src/androidTest/java/com/duckduckgo/app/notification/AndroidNotificationSchedulerTest.kt
- app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
- app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205196199549738/f
Remove previous variants for notification bug fix experiment and add new push notification audience, timing and cadence experiment instead.
_Control variant_
- set `fun VariantManager.isAudienceLeverEnabled() =` **_false_**
- set `fun VariantManager.isTimingLeverEnabled() = ` **_false_**
- set `fun VariantManager.isCadenceLeverEnabled() =` **_false_**
- edit notification delay time to second or minutes so you can test the notifications showing in a shorter time. _e.g. notification1:20sec, notification 2: 40sec_ 
- Fresh install from this branch
- Allow notifications
_Audience variant_
- set `fun VariantManager.isAudienceLeverEnabled() =` **_true_**
- set `fun VariantManager.isTimingLeverEnabled() = ` **_false_**
- …
> Experiment 2: Push notification audience, timing and cadence to increase retention

- .github/workflows/end-to-end.yml
- .maestro/app_tp/app_tp_onboarding.yaml
- .maestro/autofill/smoke.yaml
- .maestro/bookmarks/ensure_bookmarks_can_be_added_and_deleted.yaml
- .maestro/browsing/visit_site.yaml
- .maestro/config.yaml
- .maestro/favorites/favorites_bookmarks_delete.yaml
- .maestro/favorites/favorites_bookmarks_undo.yaml
- .maestro/favorites/favorites_menu_add_remove.yaml
- .maestro/fire_button/fire_during_onboarding.yaml
- .maestro/release_tests/9_-_autofill_available.yaml
- .maestro/tabs/open_multiple_tabs.yaml
- app/build.gradle
Task/Issue URL: https://app.asana.com/0/0/1205234542811811/f
Restructures the maestro release tests to use tagging instead of relying on them being in a certain folder. This approach will allow for more flexibility and reduce the need for so much duplication across the tests.
_Run tests locally_
- ℹ️ This is equivalent to running `maestro test --include-tags releaseTest .maestro`
_Ensure tests run on maestro cloud when triggered locally_
- ℹ️ This is equivalent to running `maestro cloud --include-tags releaseTest app/build/outputs/apk/play/release/duckduckgo-5.165.1-play-release.apk .maestro`
_Ensure CI end-to-end tests pass_
The E2E tests won't run against this branch automatically (they run against `develop` overnight).
> Restructure maestro tests for better reusability

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/DeviceInfoCollector.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/bugreport/DeviceInfoCollectorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205234536443733/f
See [asana](https://app.asana.com/0/488551667048375/1205234536443733/f) task
> report battery optimizations true/false in AppTP breakage

- .maestro/app_tp/app_tp_onboarding.yaml
Task/Issue URL: https://app.asana.com/0/0/1205234542811814/f
Makes it so that the VPN permission dialog step is optional. 
- Otherwise, this appTP test will only pass once and require the APK to be uninstalled and reinstalled before the test will run again.
- Even if the dialog doesn't show (because permission was accepted before on a previous test run), the later assertions would catch a problem if app TP couldn't be enabled.
> Maestro appTP test: make vpn dialog handling optional

- app/src/main/res/layout/activity_bookmarks.xml
- app/src/main/res/layout/activity_downloads.xml
- autofill/autofill-impl/src/main/res/layout/activity_autofill_settings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205238684397185/f
Fix toolbar background color when searchBar is visible
_Bookmarks screen (Light/Dark theme)_
- Go to Overflow Menu > Bookmarks
- Tap on search icon in Toolbar
_Downloads screen (Light/Dark theme)_
- Go to Overflow Menu > Downloads
- Tap on search icon in Toolbar
_Logins screen (Light/Dark theme)_
- Go to Overflow Menu > Logins
- Tap on search icon in Toolbar
> Fix toolbar color when showing SearchBarView

- .github/workflows/end-to-end.yml
- .github/workflows/privacy-dashboard-end-to-end.yml
- .maestro/ad_click_detection_flows/10_-_m.js_bing-provided;_ad_domain_provided_but_incorrect_(dsl_not_needed).yaml
- .maestro/ad_click_detection_flows/11_-_y.js_bing-provided;_ad_domain_provided_but_it's_not_a_domain_(i.e.,_abcedf)_(u3_not_needed).yaml
- .maestro/ad_click_detection_flows/12_-_m.js_bing-provided;_ad_domain_provided_but_it's_not_a_domain_(i.e.,_abcedf)__(dsl_not_needed).yaml
- .maestro/ad_click_detection_flows/13_-_y.js_bing-provided;_ad_domain_provided_but_it's_a_subdomain_of_advertiser_(i.e.,_foo.www.search-company-site)_(u3_not_needed).yaml
- .maestro/ad_click_detection_flows/14_-_m.js_bing-provided;_ad_domain_provided_but_it's_a_subdomain_of_advertiser_(i.e.,_foo.www.search-company-site)__(dsl_not_needed).yaml
- .maestro/ad_click_detection_flows/1_-_y.js_heuristic;_no_ad_domain_param;_u3_param_included.yaml
- .maestro/ad_click_detection_flows/2_-_m.js_heuristic;_no_ad_domain_param;_dsl_param_included.yaml
- .maestro/ad_click_detection_flows/3_-_y.js_heuristic;_no_ad_domain_param,_but_missing_u3_param.yaml
- .maestro/ad_click_detection_flows/4_-_m.js_heuristic;_no_ad_domain_param,_but_missing_dsl_param.yaml
- .maestro/ad_click_detection_flows/5_-_y.js_heuristic;_ad_domain_provided,_but_empty_(u3_not_needed).yaml
- .maestro/ad_click_detection_flows/6_-_m.js_heuristic;_ad_domain_provided,_but_empty_(dsl_not_needed).yaml
- .maestro/ad_click_detection_flows/7_-_y.js_bing-provided;_ad_domain_provided_(u3_not_needed).yaml
- .maestro/ad_click_detection_flows/8_-_m.js_bing-provided;_ad_domain_provided_(dsl_not_needed).yaml
- .maestro/ad_click_detection_flows/9_-_y.js_bing-provided;_ad_domain_provided_but_incorrect_(u3_not_needed).yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205258019391736/f
Restructures the maestro ad-click detection tests to use a tag `adClickTest` and utilise the shared onboarding flow.
> Restructure maestro ad-click detection tests to use tags and shared onboarding flow

- .github/workflows/ads-end-to-end.yml
- .maestro/ads_preview_flows/1-_design-system-components.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205283384588166/f
Changes the directory to upload to maestro cloud for ADS to be the top-level .maestro directory and adds a tag to let only the ADS tests run in isolation.
> Update maestro workflow for ADS to run from the top level directory with tag

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205289848854590/f 
----- 
> Update content scope scripts to version 4.34.0

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204877458059669/f
This PR ensures onStop that we first update the DB state before unbindService(vpnStateServiceConnection) 
Quickly enable - disable AppTP and ensure that always-on dialog is not shown.
> Update VPN state before unbinding service

- app-tracking-protection/app-tracking-api/src/main/java/com/duckduckgo/mobile/android/app/tracking/AppTrackingProtection.kt
- app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSetting.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/app/tracking/AppTPVpnConnectivityLossListener.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/app/tracking/RealAppTrackingProtection.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/settings/RestartOnConnectivityLossSettingPlugin.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/app/tracking/AppTPVpnConnectivityLossListenerTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpFeatureConfigImplTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSettingTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205307434865662/f
Add an AppTP-sspecific connectivity handler
_(Use an emulator)_
> Add AppTP connectivity handler

- app-tracking-protection/vpn-impl/src/main/res/layout/activity_report_breakage_category_single_choice.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205311544271092/f
In an oversight, I forgot to apply the changes made in https://github.com/duckduckgo/Android/pull/3439 to the AppTP breakage form as well, so taking care of that now.
> AppTP: Make entire view clickable when reporting breakage category

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/SyncSetupFlowFragment.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205331909141487/f 
Hides X close icon on the second auth flow screen. That addresses some user feedback-
_Feature 1_
> Remove close icon on 2nd auth screen

- app/src/main/java/com/duckduckgo/app/browser/applinks/AppLinksHandler.kt
- app/src/test/java/com/duckduckgo/app/browser/applinks/DuckDuckGoAppLinksHandlerTest.kt
https://app.asana.com/0/488551667048375/1205272113478379/f
This PR adds:
- A list of domains for which we will always show an app link snackbar.
- A flag to trigger the snackbar on same or subdomains if it hasn't been shown yet.
_Ask every time_
_Always_
> Improve app link handling

- app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsActivity.kt
- app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsViewModel.kt
- app/src/internal/java/com/duckduckgo/app/survey/api/SurveyEndpointDataStore.kt
- app/src/internal/java/com/duckduckgo/app/survey/api/SurveyEndpointInterceptor.kt
- app/src/internal/res/layout/activity_dev_settings.xml
- app/src/internal/res/values/donottranslate.xml
- app/src/main/java/com/duckduckgo/app/survey/api/SurveyRepository.kt
- app/src/main/java/com/duckduckgo/app/survey/db/SurveyDao.kt
- app/src/main/java/com/duckduckgo/app/survey/notification/SurveyAvailableNotification.kt
- app/src/test/java/com/duckduckgo/app/survey/api/SurveyRepositoryImplTest.kt
- app/src/testInternal/java/com/duckduckgo/app/survey/api/SurveyEndpointInterceptorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205305054848475/f
Add a dev setting under Settings -> Dev settins to switch between production and sandbox Surven endpoints
This PR also fixes a bug in the survey logic. When `installationDay` is -1, the survey should be immediately scheduled, but it's not
**Test dev setting**
**Test Bug fixes**
> Add dev setting to change to survey sandbox env

- app/src/androidTest/java/com/duckduckgo/espresso/EspressoUtils.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/RequestBlockingTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/SurrogatesTest.kt
- app/src/main/java/com/duckduckgo/app/trackerdetection/TrackerDetector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205316272499589/f
Adds a delay to privacy tests to ensure config initialization happens before run.
Ensure https://github.com/duckduckgo/Android/actions/runs/5963265139 finishes successfully
> Add Delay to privacy tests

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204721270468631/f
This PR removes the force expand on the search bar when the url is updated but the host remains the same (`WebNavigationStateChange.UrlUpdated`). See linked task to see sample cases why this is not completely necessary.
_Bug fix_
_Site change_
_Background_
_Error_
> Update logic on force expand search bar

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeActivity.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModel.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncConnectActivity.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncConnectViewModel.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupViewModel.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncLoginActivity.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncLoginViewModel.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncAccountRepositoryTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModelTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncConnectViewModelTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncLoginViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205212671337474/f 
Sync QR code reader supports both recovery and connect code, no matter which auth flow the user started.
(for testing you will need 2 devices)
_Feature 1_
> QR reader supports recovery and connect code

- app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabaseCallback.kt
https://app.asana.com/0/488551667048375/1201722332762154/f
Remove the prepopulation method as we no longer need it.
> AppTP: Remove prepopulation of AppTrackerEntity

- app/src/main/java/com/duckduckgo/app/survey/api/SurveyRepository.kt
- app/src/test/java/com/duckduckgo/app/survey/api/SurveyRepositoryImplTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205375055980500/f
This PR ensures that once the survey is done the survey CTA in the new tab is also removed.
> Don't show survey CTA when survey is done

- app/src/main/java/com/duckduckgo/app/browser/WebViewLongPressHandler.kt
- app/src/test/java/com/duckduckgo/app/browser/WebViewLongPressHandlerTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205377355311840/f
Updated the long press menu to show only the download image option in case of data URLs.
Test `https` image URLs (same as in develop)
Test `data` image URLs (changed)
| Before (data image URLs) | After (data image URLs) |
|!(Upload before screenshot)|(Upload after screenshot)|
|![dowlonad_and_open_image](https://github.com/duckduckgo/Android/assets/7963079/8568014d-1783-4dbd-8e82-89840b70baf7)|![download_image](https://github.com/duckduckgo/Android/assets/7963079/8cfef751-64d6-496b-95f9-205d0f10e41f)|
> Android: Don't show the option to "Open Image in Background Tab" in case of data URLs

- app/src/androidTest/java/com/duckduckgo/app/notification/AndroidNotificationSchedulerTest.kt
- app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
- app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205393984088163/f
Remove Experiment Audience, Timing and Cadence
- Change delay for engagement notifications in `AndroidNotificationScheduler` to, for example, 15 and 25 seconds (_Lines 57 & 58_)
- Allow notifications in onboarding
> Remove Experiment Audience, Timing and Cadence

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
- app/src/main/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClient.kt
- privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/AmpLinks.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/amplinks/RealAmpLinks.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/amplinks/RealAmpLinksTest.kt
https://app.asana.com/0/488551667048375/1205278186816256/f
Validates the extracted AMP link canonical URL.
> Check validity of extracted AMP links

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1205338112741811/1205338112741811
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.2.0
Updates Autofill to version [8.2.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.2.0).
* Updates for iOS in-context signup support by @alistairjcbrown in https://github.com/duckduckgo/duckduckgo-autofill/pull/347
* Trigger tooltip option on pointer up by @alistairjcbrown in https://github.com/duckduckgo/duckduckgo-autofill/pull/333
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/8.1.2...8.2.0
> Update autofill to 8.2.0

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205458963331598/f 
----- 
> Update content scope scripts to version 4.36.0

- app/src/main/AndroidManifest.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205464181403832/f
Added `smallestScreenSize` and `screenLayout` to `configChanges` for `BrowserActivity`. 
Reproduce:
Test the fix:
> Android: Resizing screen causes page reload

- .maestro/bookmarks/open_bookmark_and_navigate_back.yaml
- .maestro/bookmarks/open_bookmark_in_folder_and_navigate_back.yaml
- app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt
- app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksScreens.kt
- app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
- app/src/test/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205402504525897/f
Fixed the open bookmark from folder flow. Added maestro tests. 
Test open bookmark from folder and navigate back:
Test open bookmark and navigate back:
Test the gesture navigation in Production to notice the issue:
Test the fixed gesture navigation:
Run the 2 maestro tests:
> Bug: Bookmarks in folders don’t open

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStackTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205295861136336/f
* Add pixel for when we can't stop the VPN
* Update AppTP disabled pixel to queue (in case we lost connectivity)
Mostly code review as this is difficult to test. One way to test the VPN stop timeout pixel is to create a local version of NetGuard with a forced infinite loop and then try to stop AppTP.
> Add AppTP connectivity pixels

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1205515626714180/f
Adds `isForMainFrame` check when showing browser error.
> Add isForMainFrame browser error check

- app/src/main/java/com/duckduckgo/app/global/api/AtbAndAppVersionPixelRemovalInterceptor.kt
- app/src/test/java/com/duckduckgo/app/global/api/AtbAndAppVersionPixelRemovalInterceptorTest.kt
- common/common-utils/src/main/java/com/duckduckgo/app/global/plugins/pixel/PixelRequiringDataCleaningPlugin.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205520159940704/f 
Introduces a plugin point for defining pixels which should have their ATB and app version removed. These pixels are already defined, but defining them via the plugin point approach allows for more flexibility in _where_ the pixels are defined, allowing them to be created in other modules but still contribute towards this list which the `AtbAndAppVersionPixelRemovalInterceptor` will use.
- e.g., `AppPixelName.EMAIL_USE_ADDRESS`
- log into Email Protectio 
- visit https://fill.dev/form/registration-email
- tap on the email field
- choose to use the personal duck address
- verify in the logs or with a breakpoint that this is picked up as a special case and ATP/app version are removed by …
> Plugin point for pixels which get data stripped

- .maestro/bookmarks/ensure_bookmarks_can_be_added_and_deleted.yaml
- .maestro/browsing/visit_site.yaml
- .maestro/favorites/favorites_bookmarks_delete.yaml
- .maestro/favorites/favorites_bookmarks_undo.yaml
- .maestro/favorites/favorites_menu_add_remove.yaml
- .maestro/fire_button/fire_during_onboarding.yaml
- .maestro/privacy_tests/10_-_Query_Parameters,_utm_source_and_1_standard_parameter.yaml
- .maestro/privacy_tests/11_-_Query_Parameters,_utm_source_and_utm_medium.yaml
- .maestro/privacy_tests/12_-_Query_Parameters,_fbclid,_fb_source_and_1_standard_parameter.yaml
- .maestro/privacy_tests/13_-_Query_Parameters,_link_which_should_not_be_rewritten.yaml
- .maestro/tabs/open_multiple_tabs.yaml
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/CookiesTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/GpcTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/HttpsUpgradesTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/RequestBlockingTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/SurrogatesTest.kt
- app/src/internal/java/com/duckduckgo/app/audit/AuditSettingsViewModel.kt
- privacy-config/privacy-config-impl/src/main/res/raw/privacy_config.json
- privacy-config/privacy-config-impl/src/test/resources/json/gpc.json
- privacy-config/privacy-config-impl/src/test/resources/json/gpc_min_supported_version.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205442219109577/f 
Updates the URLs for the privacy test pages since we've moved them to new infrastructure.
`Current: privacy-test-pages.glitch.me`
`New:     privacy-test-pages.site`
ℹ️  Note, `global-privacy-control.glitch.me` remains deliberately, as per [link](https://app.asana.com/0/0/1205403548898249/1205420985241292/f)
> Update tests to point to new privacy page URL

- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/listeningmode/VoiceSearchActivity.kt
- voice-search/voice-search-impl/src/main/res/layout/activity_voice_search.xml
Task/Issue URL: https://app.asana.com/0/0/1205518480388652/f 
Make voice search activity respect the safe area while keeping the status bar transparent
_Feature 1_
> Show toolbar below transparent status bar

- app/src/androidTest/java/com/duckduckgo/widget/VoiceSearchWidgetUpdaterReceiverTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchActivity.kt
- app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
- app/src/main/java/com/duckduckgo/widget/VoiceSearchWidgetUpdaterReceiver.kt
- app/src/main/java/com/duckduckgo/widget/WidgetUpdater.kt
- app/src/main/java/com/duckduckgo/widget/WidgetVoiceSearchStatusListener.kt
- app/src/test/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
- app/src/test/java/com/duckduckgo/widget/WidgetVoiceSearchStatusListenerTest.kt
- voice-search/voice-search-api/src/main/java/com/duckduckgo/voice/api/VoiceSearchStatusListener.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/di/VoiceSearchModule.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/listeningmode/VoiceSearchActivity.kt
- voice-search/voice-search-impl/src/main/res/drawable/ic_microphone_dark.xml
- voice-search/voice-search-impl/src/main/res/layout/activity_voice_search.xml
- voice-search/voice-search-store/build.gradle
- voice-search/voice-search-store/src/main/java/com/duckduckgo/voice/store/VoiceSearchRepository.kt
- voice-search/voice-search-store/src/test/java/com/duckduckgo/voice/store/RealVoiceSearchRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205518480388653/f
* Update widgets whenever voice search feature is toggled on/off
* Fix dark search widget not showing voice search icon
_Feature 1_
_Feature 2_
> Update voice search icon in widget based on settings

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
- app/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205507540854792/f
Updated to show an error screen when ssl protocol handshake error is encountered. 
Title: `DuckDuckGo can't load this page.`
Description: `The certificate for this server is invalid. You might be connecting to a server that is pretending to be [website_url] which could put your confidential information at risk.`
|![ssl_protocol_error_before](https://github.com/duckduckgo/Android/assets/7963079/b54ccbd4-70f2-491a-9620-957b929a051a)|![ssl_error](https://github.com/duckduckgo/Android/assets/7963079/fe14a019-f07d-403f-a89f-9c820aea7d41)|
> Android: Handle SSL protocol error

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/global/api/AtbAndAppVersionPixelRemovalInterceptor.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/test/java/com/duckduckgo/app/browser/autofill/ResultHandlerEmailProtectionChooseEmailTest.kt
- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillEventListener.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/email/ResultHandlerEmailProtectionChooseEmail.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205568952724508/f 
Currently there are some pixels and logic for Email Protection events that are in app module that would be better placed in `autofill-impl`.
In `AtbAndAppVersionPixelRemovalInterceptor`, replace line 47 with the following:
`val url = if (isInPixelsList(pixel).also { if (it) Timber.e("xxx cleaning pixel %s", pixel) }) {`
- this adds a log statement, that you should filter for in logcat
> Move Email Protection event pixels to autofill-impl module

- anrs/anrs-api/src/main/java/com/duckduckgo/anrs/api/AnrRepository.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/AnrOfflinePixelSender.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/AnrSupervisor.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/CrashOfflinePixelSender.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ExceptionModels.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/RealAnrRepository.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/RealCrashLogger.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/di/AnrModule.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/di/CrashModule.kt
- anrs/anrs-store/src/main/java/com/duckduckgo/app/anrs/store/AnrEntity.kt
- anrs/anrs-store/src/main/java/com/duckduckgo/app/anrs/store/AnrsDatabase.kt
- anrs/anrs-store/src/main/java/com/duckduckgo/app/anrs/store/CrashDatabase.kt
- app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/WebViewVersionProvider.kt
- app/src/main/java/com/duckduckgo/app/pixels/EnqueuedPixelWorker.kt
- app/src/test/java/com/duckduckgo/app/pixels/EnqueuedPixelWorkerTest.kt
- browser-api/src/main/java/com/duckduckgo/browser/api/WebViewVersionProvider.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205522974777681/f 
This PR adds the webview version to anr and crash pixels
_Test ANR pixel_
_Test crash pixel_
_Test migration_
> Add webview version to anr and crash pixels

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1205568113205968/f
Changes the image download directory to "Downloads".
**Before**
https://github.com/duckduckgo/Android/assets/3471025/a554c240-fc23-4d02-b711-2355615b48a9
**After**
https://github.com/duckduckgo/Android/assets/3471025/57fb993a-fb9c-4095-8574-e69c5c23fab6
> Change image download location to DIRECTORY_DOWNLOADS

- common/common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/ComponentViewHolder.kt
- common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/DaxListItem.kt
- common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/OneLineListItem.kt
- common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/TwoLineListItem.kt
- common/common-ui/src/main/res/layout/component_two_line_item.xml
- common/common-ui/src/main/res/values/attrs-lists.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205591898713343/f
Add the ability to set the Switch in a Line item as disabled.
* Added a switchEnabled attribute to the xml layout
* Added a setSwitchEnabled method to DaxListItem
* Applied to both TwoLineListItem and OneLineListItem
- install internal build from this branch
- go to Settings -> App Components Design Preview and select List Items
> Add the ability to set the Switch in a Line item as disabled

- app/src/main/java/com/duckduckgo/app/email/sync/EmailSync.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/test/java/com/duckduckgo/app/email/AppEmailManagerTest.kt
- app/src/test/java/com/duckduckgo/app/email/EmailSyncTest.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1205601700770183/f
Adds a pixel when overriding a local duck address when first sync.
_Feature 1_
> add pixel when we override local duck address

- app/src/main/java/com/duckduckgo/app/global/view/FaviconImageView.kt
- app/src/main/java/com/duckduckgo/widget/FavoritesWidgetService.kt
- app/src/main/res/drawable/search_widget_favorite_favicon_dark_background.xml
- app/src/main/res/drawable/search_widget_favorite_favicon_daynight_background.xml
- app/src/main/res/drawable/search_widget_favorite_favicon_light_background.xml
- common/common-ui/src/main/res/values/design-system-dimensions.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205173497854945/f 
* Do not round corners when creating placeholder icon, except for the widget
* Generally, we rely on the surface displaying the placeholder to do the corner rounding, however, this is not possible on the widget due to some 
platform limitations in API < 31. That's why the widget needs to apply a different treatment. Up until now, all placeholders were provided with a 
radius optimized for the widget, which caused them to have a different shape than the actual favicons
* Fix wrong radius in widget background and icons. Shapes were not aligned, and also not aligned with de designs in Figma
_Placeholder favicon for favorites, fireproofed and tab switcher_
_Placeholder favicon for location permissions_ 
Example for …
> Fix wrong placeholder icon radius

- app/src/androidTest/java/com/duckduckgo/app/browser/WebViewRequestInterceptorTest.kt
- app/src/androidTest/java/com/duckduckgo/app/fakes/UserAgentFake.kt
- app/src/androidTest/java/com/duckduckgo/app/global/api/ApiRequestInterceptorTest.kt
- app/src/androidTest/java/com/duckduckgo/app/referencetests/DomainsReferenceTest.kt
- app/src/androidTest/java/com/duckduckgo/app/referencetests/SurrogatesReferenceTest.kt
- privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/UserAgent.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/useragent/RealUserAgent.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/useragent/UserAgentFeature.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/useragent/UserAgentPlugin.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/useragent/RealUserAgentTest.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/useragent/UserAgentPluginTest.kt
- privacy-config/privacy-config-impl/src/test/resources/json/useragent.json
- privacy-config/privacy-config-impl/src/test/resources/json/useragent_disabled.json
- privacy-config/privacy-config-impl/src/test/resources/json/useragent_min_supported_version.json
- privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
- privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabaseModels.kt
- privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/useragent/UserAgentRepository.kt
- privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/useragent/UserAgentSitesDao.kt
- privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/useragent/UserAgentStatesDao.kt
- privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/useragent/UserAgentVersionsDao.kt
- privacy-config/privacy-config-store/src/test/java/com/duckduckgo/privacy/config/store/features/useragent/RealUserAgentRepositoryTest.kt
- user-agent/user-agent-impl/build.gradle
- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/UserAgentProvider.kt
- user-agent/user-agent-impl/src/test/java/com/duckduckgo/user/agent/impl/UserAgentProviderTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205442309571985/f
Sets the user agent based on the config of `ddg`, `ddgFixed` or `closest`.
**_ddg_**
It should look something like this:
`Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile DuckDuckGo/5 Safari/537.36`
Desktop:
`Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 DuckDuckGo/5 Safari/537.36`
**_ddgFixed disabled_**
It should look something like this:
`Mozilla/5.0 (Linux; Android 11) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile DuckDuckGo/5 Safari/537.36`
Desktop:
`Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 DuckDuckGo/5 …
> Use closest most popular user agent

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205676179510308/f 
----- 
> Update content scope scripts to version 4.38.0

- app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt
- app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
- app/src/test/java/com/duckduckgo/app/notification/AndroidSchedulerNotificationTest.kt
- app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205645143594461/f
Disable and remove no-notifications experiment form the code
Change delay time to schedule engagement notifications in `AndroidNotificationScheduler.kt` so you can see notifications after seconds instead days
_(Optional) Engagement notifications_
- Uninstall previous version of the app or clear storage
> Disable no engagement notifications experiment

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205697935999890/f 
----- 
> Update content scope scripts to version 4.39.0

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt
- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/systemautofill/SystemAutofillUsageMonitor.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/systemautofill/RealSystemAutofillUsageMonitor.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205669280706362/f 
Detect system-level `AutofillService` autofill event to gain insights into usage.
> Detect System AutofillService usage within WebView

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1205691418983700/1205691418983700
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.4.2
Updates Autofill to version [8.4.2](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.4.2).
* Ema/perf followups by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/386
* Fix handler regression by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/392
* Bump markdown-it from 13.0.1 to 13.0.2 by @dependabot in https://github.com/duckduckgo/duckduckgo-autofill/pull/388
* Revert mutation observer for forms by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/396
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/8.4.1...8.4.2 …
> Update autofill to 8.4.2

- common/common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/dialogs/DialogsFragment.kt
- common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/TextAlertDialogBuilder.kt
- common/common-ui/src/main/res/layout/fragment_components_dialogs.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205678967478266/f 
Allow text dialogs to have only a primary button
> Change text dialog to allow only one button

- app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserObserver.kt
- app/src/main/java/com/duckduckgo/app/global/install/AppInstallStore.kt
- app/src/main/java/com/duckduckgo/app/notification/NotificationRegistrar.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
- app/src/main/res/values/donottranslate.xml
- app/src/test/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserObserverTest.kt
- app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205645143594459/f
- Remove set-as-default browser dialog logic from disabled experiment
- Remove temporal pixel for setting DDG as default from notification
_[Optional]_ Smoke test
> Remove set-as-default dialog from experiment notification

- network-protection/network-protection-impl/build.gradle
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgTunnel.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/WgTunnelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205712062668046/f
Log crash when registration fails
* Apply the following patch
```diff
Index: statistics/src/main/java/com/duckduckgo/app/statistics/api/OfflinePixelScheduler.kt
<+>UTF-8
diff --git a/statistics/src/main/java/com/duckduckgo/app/statistics/api/OfflinePixelScheduler.kt b/statistics/src/main/java/com/duckduckgo/app/statistics/api/OfflinePixelScheduler.kt
--- a/statistics/src/main/java/com/duckduckgo/app/statistics/api/OfflinePixelScheduler.kt	(revision 219cf9110ac5db4eb11bb7c5bc8e93a2f34870f7)
+++ b/statistics/src/main/java/com/duckduckgo/app/statistics/api/OfflinePixelSched …
```
> Log registration errors

- app-tracking-protection/vpn-impl/build.gradle
- app-tracking-protection/vpn-impl/src/main/AndroidManifest.xml
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/WorkerExtensions.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPCPUMonitor.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/CPUMonitorWorker.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/CPUUsageReaderImpl.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/health/AppTPCPUMonitorTest.kt
- app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205698558631498/f
Fix CPU measurement, it was measure on the wrong process
Apply the following patch
```diff
Index: app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPCPUMonitor.kt
<+>UTF-8
diff --git a/app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPCPUMonitor.kt b/app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPCPUMonitor.kt
--- a/app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPCPUMonitor.kt	(revision …
```
> Fix CPU load measurement for :vpn process

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserChromeClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
- privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/Drm.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/drm/RealDrm.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/drm/RealDrmTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205710253534934/f
* Make sure we deny DRM explicitly to avoid website hangs
* If users disable protections, DRM should be allowed
* Similarly, if we temporarily disable all protections for a site via `unprotectedTemporary`, DRM should be allowed
> Fix DRM permissions

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNamesTest.kt
- app/src/main/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptor.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205722911266481/f
Return `START_STICKY` instead of `START_REDELIVER_INTENT` in the `VpnService`.
See the reasons in the Asana task
Smoke tests AppTP/NP
> Return START_STICKY

- privacy-config/privacy-config-impl/build.gradle
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/PrivacyConfigDownloader.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/PrivacyConfigPersister.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/workers/RemoteConfigDownloadWorker.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigDownloaderTest.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigPersisterTest.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/workers/PrivacyConfigDownloadWorkerTest.kt
- privacy-config/privacy-config-internal/build.gradle
- privacy-config/privacy-config-internal/src/main/java/com/duckduckgo/privacy/config/internal/PrivacyConfigInternalSettingsActivity.kt
- privacy-config/privacy-config-internal/src/main/java/com/duckduckgo/privacy/config/internal/PrivacyConfigInternalViewModel.kt
- privacy-config/privacy-config-internal/src/main/java/com/duckduckgo/privacy/config/internal/store/DevPrivacyConfigSettingsDataStore.kt
- privacy-config/privacy-config-internal/src/main/res/layout/activity_privacy_config_internal_settings.xml
- privacy-config/privacy-config-internal/src/main/res/values/donottranslate.xml
- privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
- privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabaseModels.kt
- privacy-config/privacy-config-store/src/test/java/com/duckduckgo/privacy/config/store/RealPrivacyConfigRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205661297103827/f 
This PR improves the internal settings to load a new remote config
> Better internal settings to force load a custom config

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModel.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/TrackerDividerItemDecoration.kt
- app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml
- app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_activity_entry.xml
Task/Issue URL: https://app.asana.com/0/0/1205217801169328/f 
* Remove divider from the last item
* Add full width divider below "View All Recent Activity"
* Fix bug that caused "View All Recent Activity" to be shown when there were only 4 apps with trackers blocked
_Recent activity isn't shown anymore with trackers blocked in 4 apps_
_Recent activity shows with trackers blocked in 5 apps_
_Last item in activity has no divider_
> Remove divider for last item in tracker feed

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205760598870176/f
Block the Android system from auto-starting the VPN service when it was previously disabled
_Test_
- Ensure always on is disabled for our app
- Enable AppTP and disable it back
- Enable always-on from Android settings
- Enable AppTP
- Disable always-on for our app
- re-enable always on for our app
> Block the system to wrongly auto-start AppTP/NetP

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionExclusionListActivity.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModel.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/TrackerDividerItemDecoration.kt
- app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml
- app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_activity_entry.xml
- app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_excluded_app_entry_skeleton.xml
Task/Issue URL: https://app.asana.com/0/0/1205217801169326/f 
_Feature 1_
> Fix disabled state in Restore Protected Apps

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStackTest.kt
- versions.properties
- vpn-network/vpn-network-api/src/main/java/com/duckduckgo/vpn/network/api/VpnNetworkCallback.kt
- vpn-network/vpn-network-impl/src/main/java/com/duckduckgo/vpn/network/impl/RealVpnNetwork.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205766744020104/f
Report TLS parsing errors from native
Apply the following patch to this branch
```
---
Index: build.gradle
<+>UTF-8
diff --git a/build.gradle b/build.gradle
--- a/build.gradle	(revision d11f7491d7ab4b27223fd352f83c26be403e79ed)
+++ b/build.gradle	(revision 3b1fe446b5d33e4d8a7f400137134ea0b5a797d7)
@@ -40,6 +40,7 @@
repositories {
google()
mavenCentral()
+        mavenLocal()
}
configurations.all {
resolutionStrategy.force 'org.objenesis:objenesis:2.6'
Index: versions.properties
<+>ISO-8859-1 …
```
> Report TLS parsing errors

- common/common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/ComponentViewHolder.kt
- common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/expand/DaxExpandableMenu.kt
- common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/expand/DaxExpandableMenuDsl.kt
- common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/expand/DaxExpandableMenuItem.kt
- common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/expand/DaxExpandableMenuItemDsl.kt
- common/common-ui/src/main/res/layout/component_expandable_layout.xml
- common/common-ui/src/main/res/layout/view_expandable_menu_item_expanded_layout_demo.xml
- common/common-ui/src/main/res/values/attrs-expandablelemenu.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205738768210349/f
Adds the ability to set a custom expandable layout in DaxExpandableMenuItem
```
<com.duckduckgo.mobile.android.ui.view.expand.DaxExpandableMenuItem
android:id="@+id/expandable3”
android:layout_width=“match_parent”
android:layout_height=“wrap_content”
app:primaryText=“Sync”
app:leadingIcon="@drawable/ic_globe_gray_16dp”
app:leadingIconSize=“small”
app:expandedLayout="@layout/view_expandable_menu_item_expanded_layout_demo” />
```
```
LayoutInflater.from(context).inflate(R.layout.view_expandable_menu_item_expanded_layout_demo, this, false).apply {
findViewById<DaxButtonSecondary>(R.id.daxExpandableMenuItemSecondaryButton).apply {
setOnClickListener {
Snackbar.make(this, component.name, Snackbar.LENGTH_SHORT).show()
} …
```
> ADS: Custom Expandable Layout for DaxExpandableMenuItem

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205790416790343/f 
----- 
> Update content scope scripts to version 4.41.0

- common/common-ui/src/main/res/values/design-system-theming.xml
- common/common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/0/1174433894299346/1205760186931919 
This PR fixes the buttons styling issue in the time picker.
Also fixes https://github.com/duckduckgo/Android/issues/2976
- Visit fastjp.com
- Tap on the time input (4th box)
- Verify dialog buttons are visible
> ADS: Time picker theming

- app/src/main/java/com/duckduckgo/app/pixels/EnqueuedPixelWorker.kt
- app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
- app/src/test/java/com/duckduckgo/app/pixels/EnqueuedPixelWorkerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205787440131230/f
Change the name of the feature flag from `browser` to `androidBrowserConfig`.
> Android: Update the "browser" remote flag name

- app/src/androidTest/java/com/duckduckgo/app/referencetests/FirstPartyCookiesReferenceTest.kt
- app/src/androidTest/java/com/duckduckgo/app/referencetests/HttpsReferenceTest.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/PrivacyConfigPersister.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/models/JsonPrivacyConfig.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigDownloaderTest.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigPersisterTest.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/gpc/GpcHeaderReferenceTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205795095480230/f 
This PR makes reason optional for unprotected temporary.
> Make reason optional for unprotected temporary

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillJavascriptInterface.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/AutofillDeduplicationBestMatchFinder.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/AutofillDeduplicationMatchTypeDetector.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/AutofillDeduplicationUsernameAndPasswordMatcher.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/AutofillLoginDeduplicator.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/RealLoginSorterForDeduplication.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/AutofillStoredBackJavascriptInterfaceTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealAutofillLoginDeduplicatorTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealAutofillMatchTypeDetectorTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealLoginDeduplicatorBestMatchFinderTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealLoginDeduplicatorUsernameAndPasswordMatcherTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealLoginSorterForDeduplicationTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205369440069078/f 
De-duplicates logins which are offered for autofilling into a page. The de-duplication only happens at the UI layer, and only for the bottom-sheet autofill prompt (duplicates continue to be supported in the DB and in the login management screens).
Rules for de-duplicating are described in [Validating business rules for de-duplicating logins](https://app.asana.com/0/1205729146579121/1205729146579121/f), but to summarise:
- only considered a duplicate if both username and password are perfect matches
- de-deduplication is applied at the last step before presenting the autofill login options, meaning all of the existing rules on which saved logins are considered still apply; this just filters that list down if it …
> De-duplicate login suggestions offered to a user for autofilling credentials

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillJavascriptInterface.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/AutofillDeduplicationBestMatchFinder.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/AutofillDeduplicationMatchTypeDetector.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/AutofillDeduplicationUsernameAndPasswordMatcher.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/AutofillLoginDeduplicator.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/RealLoginSorterForDeduplication.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDisablingDeclineCounter.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/AutofillStoredBackJavascriptInterfaceTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealAutofillLoginDeduplicatorTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealAutofillMatchTypeDetectorTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealLoginDeduplicatorBestMatchFinderTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealLoginDeduplicatorUsernameAndPasswordMatcherTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealLoginSorterForDeduplicationTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDisablingDeclineCounterTest.kt
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
- autofill/autofill-internal/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/0/1205768484548248/f
Adds dev settings for autofill logins, allowing for quickly:
- adding some sample logins
- adding duplicate logins for the same domain
- adding duplicate logins for same e-TLD+1 but different subdomains
- deleting all saved logins
> Add dev settings for quickly adding Logins for testing (including duplicates)

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1205821878475376/f 
when multiple tabs are alive, fullscreen mode can be received by a non-visible tab. If that tab renders that mode, it will affect visible tab.
PR fixes the issues ensuring only visible tab renders full screen mode viewstate.
_Feature 1_
> Allow fullscreen control only to the visible fragment

- app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt
- app/src/test/java/com/duckduckgo/app/brokensite/api/BrokenSiteSubmitterTest.kt
- app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesReferenceTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205836086617635/f 
This PR adds a new parameter to the broken sites report to know when protections were on or off.
> Add parameter to broken sites for protections on or off

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteActivity.kt
- app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt
- app/src/test/java/com/duckduckgo/app/feedback/BrokenSiteViewModelTest.kt
- browser-api/src/main/java/com/duckduckgo/app/global/model/Site.kt
- browser-api/src/main/java/com/duckduckgo/browser/api/brokensite/BrokenSiteNav.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205855094135462/f 
This PR changes the logic that sets siteType to follow user's selection rather than how the URL looks like.
> Change siteType logic to be based on user choice rather than URL

- build.gradle
- voice-search/voice-search-store/build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1205853717890734/f 
This PR adds a new gradle rule to avoid the usage of kapt in favour of ksp
> Add gradle rule to avoid the usage of kapt

- remote-messaging/remote-messaging-impl/build.gradle
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/AppRemoteMessagingRepository.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/di/RemoteMessagingModule.kt
- remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/AppRemoteMessagingRepositoryTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205846766235726/f
Adds an `isDefaultBrowser` check to ensure that the experiment is not shown for non-default users.
> Only show default browser experiment if not default browser

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/internal/SyncInternalEnvInterceptor.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205629126158773/f 
Fixes rewrite url logic to keep query params. Interceptor was added as part of https://app.asana.com/0/1202552961248957/1205489036222328/f
Bug: when building a new requests, params were not included, only the path.
_Feature 1_
> Fix sync env endpoint rewrite logic

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205866472468407/f 
----- 
> Update content scope scripts to version 4.42.0

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205880315699690/f 
----- 
> Update content scope scripts to version 4.43.0

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205843589662925/f 
Move showShowVoiceSearch to browserViewState
Having it on omnibarViewState interferes with text changes, causing either textinput not to updated, or it to be updated too frequently, causing rq pixels to fire
_Check pixels fired_
_Check voice search icon behavior_
No UI changes
> Fix rq pixels being fired when queryt didn't change

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205892363792858/f 
----- 
> Update content scope scripts to version 4.44.0

- app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteActivity.kt
- app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteViewModel.kt
- app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt
- app/src/main/java/com/duckduckgo/app/brokensite/model/BrokenSite.kt
- app/src/main/res/layout/content_broken_sites.xml
- app/src/main/res/values/donottranslate.xml
- app/src/test/java/com/duckduckgo/app/brokensite/api/BrokenSiteSubmitterTest.kt
- app/src/test/java/com/duckduckgo/app/feedback/BrokenSiteViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesMultipleReportReferenceTest.kt
- app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesReferenceTest.kt
- common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/text/DaxTextInput.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205834027224168/f
This PR adds a new field to the broken site report so users can input the site they were trying to sign into when reporting a login issue.
> Add new field when category is login

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesSubComponentCodeGenerator.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205898947038393/f
Only scopes that have `AppScope` as direct parent allow delayed subcomponent generation
QA optional
> Delay subcomponent generation only for direct children of appScope

- app/src/androidTest/java/com/duckduckgo/app/referencetests/SurrogatesReferenceTest.kt
- app/src/androidTest/resources/reference_tests/domain_matching_tests.json
- app/src/androidTest/resources/reference_tests/tracker_radar_reference.json
- app/src/test/resources/reference_tests/brokensites/multiple_report_tests.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205912857649722/f 
----- 
> Update reference tests to version 1699439919

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205912727864258/f 
----- 
> Update content scope scripts to version 4.45.0

- app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt
- app/src/test/java/com/duckduckgo/app/brokensite/api/BrokenSiteSubmitterTest.kt
Task/Issue URL:  https://app.asana.com/0/0/1205915950517978/f
Switching to true|false instead of 1|0 for cross-platform consistency. See the parent task https://app.asana.com/0/1201141132935289/1205644489547731
> switch to true|false for protectionsState param

- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillFeature.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/di/AutofillModule.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/AutofillCapabilityCheckerImplTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/email/incontext/availability/RealEmailProtectionInContextAvailabilityRulesTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/store/RealAutofillPrefsStoreTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/store/feature/RealAutofillDefaultStateDeciderTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/feature/toggles/api/toggle/AutofillTestFeature.kt
- autofill/autofill-internal/src/main/AndroidManifest.xml
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
- autofill/autofill-store/build.gradle
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/AutofillPrefsStore.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/feature/AutofillDefaultStateDecider.kt
Task/Issue URL: https://app.asana.com/0/0/1205811927559467/f 
Integrates with remote config to determine if Autofill should be enabled by default, for new users only. 
- New remote config Autofill subfeature `onByDefault` will be introduced and incrementally rolled out 
- For now, a user will get Autofill enabled by default only if the incremental rollout enables it for a brand new user (installed today). If on the first day the incremental rollout determines a user:
- can have it enabled by default, it'll be enabled. And this will be recorded locally so we know they had it enabled by default. 
- can not have it enabled by default, it won't be enabled by default
- Even if it later becomes available to them through the incremental rollout then they still won't have it on by default if that …
> Integrate with remote config to determine if autofill is on by default

- app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesReferenceTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205924265528360/f
Updating tests to suit this recent change https://github.com/duckduckgo/privacy-reference-tests/pull/112
> updating reference tests for protectionsState

- app/src/test/resources/reference_tests/brokensites/multiple_report_tests.json
- app/src/test/resources/reference_tests/brokensites/tests.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205935778872726/f 
----- 
> Update reference tests to version 1699613603

- privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModel.kt
- privacy-dashboard/privacy-dashboard-impl/src/test/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205916361591091/f
- Whenever protections are toggled we should close the Privacy Dashboard.
https://github.com/duckduckgo/Android/assets/4212474/f3dbb21f-f4be-4590-8a47-9fc56db754f2
> Close Privacy Dashboard after toggling protections on Broken Site screen

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Task/Issue URL: https://app.asana.com/0/1163321984198618/1200978700861007/f
Updated to show an ssl error page when explicitly receiving ssl error from webview client (when we're notified via `onReceivedSslError`).  
|![bad_ssl_before](https://github.com/duckduckgo/Android/assets/7963079/5292639e-29bc-4063-811d-578692d6c611)|![bad_ssl_after](https://github.com/duckduckgo/Android/assets/7963079/95c63d68-1efa-4323-8bed-f0cccb6723cc)|
> Provide more info / allow loading sites with certificate issues (Android)

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205946016107233/f 
----- 
> Update content scope scripts to version 4.48.0

- macos/macos-impl/build.gradle
- macos/macos-impl/src/main/AndroidManifest.xml
- macos/macos-impl/src/main/java/com/duckduckgo/macos/impl/MacOsActivity.kt
- macos/macos-impl/src/main/java/com/duckduckgo/macos/impl/MacOsLinkShareBroadcastReceiver.kt
- macos/macos-impl/src/main/java/com/duckduckgo/macos/impl/MacOsPixelNames.kt
- macos/macos-impl/src/main/java/com/duckduckgo/macos/impl/MacOsViewModel.kt
- macos/macos-impl/src/main/res/layout/activity_macos.xml
- macos/macos-impl/src/test/java/com/duckduckgo/macos/impl/MacOsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205884745797986/f
Changes macos-impl namespace from `com.duckduckgo.macos_impl` to  `com.duckduckgo.macos.impl`
> Standardize macos namespace

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserChromeClientTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
- site-permissions/readme.md
- site-permissions/site-permissions-api/src/main/java/com/duckduckgo/site/permissions/api/SitePermissionsDialogLauncher.kt
- site-permissions/site-permissions-api/src/main/java/com/duckduckgo/site/permissions/api/SitePermissionsManager.kt
- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerImpl.kt
- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsRepository.kt
- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/di/SitePermissionsModule.kt
- site-permissions/site-permissions-impl/src/test/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205815328063411/f 
This PR refactors permissions so the ones that can be accepted or denied automatically are done within the module rather than the fragment.
_Camera/mic deny_
_Camera/mic allow_
_Camera/mic allow within 24h_
_Camera/mic always allow_
_Camera/mic always deny
_Session-based Consent_
_Random tests_
> Refactor permissions

- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/di/VoiceSearchModule.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/remoteconfig/VoiceSearchFeatureSettingStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205939214156691/f 
We saw some ANRs due to the way we were eagerly instantiating the JSON adapter on process lifecycle start.
This PR defers the creation until it's needed (which is on a worker thread).
> Defer voice search JSON adapter creation until it's off main thread

- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/0/1205900373687630/f 
Updates copy, preferring to use terminology "password" instead of "login" in the autofill dialogs.
Includes translations.
- QA optional
> Update autofill dialog copy, changing "logins" to "passwords"

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncAccountRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204909556811580/f 
This PR ensures that the UI login an account is not blocked until the first sync operation finishes.
- Import html file attached to Asana task
- Remove folder with 500 bookmarks to avoid object limit
- You’ll need two devices for this
_Login (this branch)_ 
For comparison, do the same operations from develop and verify that the “Device Synced” screen takes much longer to appear
> Sync: Move login sync to io

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/notification/NetPDisabledNotificationScheduler.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205967226515880/f
https://app.asana.com/0/0/1205967324060545/f
> Fix bug is disabled notif after beta

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205964225225766/f 
----- 
> Update content scope scripts to version 4.50.0

- app/src/internal/java/com/duckduckgo/app/browser/webview/InternalWebContentDebugging.kt
- app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsActivity.kt
- app/src/internal/res/layout/activity_dev_settings.xml
- app/src/internal/res/values/donottranslate.xml
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/webview/WebContentDebugging.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205969526566822/f
Add web content debugging to internal builds
_Test Internal Build_
_Test Play Build_
> Add web content debugging to internal builds

- app/src/main/java/com/duckduckgo/app/brokensite/view/SiteProtectionsToggle.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205947853089389/f
In the BrokenSiteViewModel, the onProtectionsToggled() method is invoked right after the view is initialized, which leads to sending m_broken_site_allowlist_remove pixel even though the user didn't interact with the protections toggle.
> Fix pixels related to protections toggle on Broken Site screen

- app/src/test/java/com/duckduckgo/app/firebutton/FireButtonViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModelTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205977462737330/f 
Fixes NPE which happen after updating to Kotlin 1.9
QA-optional
> Fix null pointers in unit tests

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205977462737331/f 
Attempt at fixing the timeout occasionally experienced because of the new 10s `runTest` execution timeout.
While reviewing the failing tests, two things sprung to mind:
- `whenTrackingParametersDetectedAndIsForMainFrameAndIsAppLinkAndAppLinkIsHandledThenReturnTrueAndLoadCleanedUrl` is suspect, because it's a test, but it's also called from inside another test. This would result in a nested `runTest`. This isn't fixed in this PR yet (if the tests pass, will defer changing it)
- there are many tests which mock a `WebView` which is a slow operation (over 1.5s on my fast local setup). 
- Feasible this could result in tripping the 10s threshold on CI. 
- But also, none of the tests seem to require `runTest` anyway
_Feature 1_
> Attempt to fix test failing due to exceeding 10s timeout

- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1205409122994449/f
Fixes a NullPointerException in okhttp due to certificate corruption.
Changes:
- `version.google.dagger`=`2.46.1` → `2.48.1`
- `version.okhttp3`=`4.11.0` → `4.12.0`
> Fix okhttp3 NullPointerException

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt
- app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchActivity.kt
- app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
- app/src/test/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205171041444238/f
This PR changes how undo works at a UI layer level for saved sites.
Until now, when the user wanted to delete a bookmark, we were directly removing it from the DB. In the case that the user were to undo the change, we were adding a new row to the DB. This is problematic in many levels, changing order of Favourites and also triggering unnecessary Sync operations.
All test cases assume that Sync is enabled
_Remove Favourite from Bookmarks screen_
_Remove Bookmark from Browser_
_Remove Favourite from Browser_
_Remove Bookmark from Browser_
_Remove Favourite from New Tab_
_Remove Favourite from Omnibar Quick Access_
_Remove Favourite from Favourites Widget_
> Bookmarks: Undo behavior

- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1205874074739543/f
Bump NG to 1.6.9 to workaround TLS fragmented records. See Asana for more info
Smoke test AppTP and VPN
> Bump ng to 1.6.9 to woraround TLS fragmented records

- build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1206001791999899/f 
Since lint version and gradle plugin version have a rule determining what the former should be based on the latter, might as well calculate this instead of having to update lint version independently.
QA optional
> Calculate lint version automatically instead of hardcoding specific version

- .github/CODEOWNERS
- app/build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/java/com/duckduckgo/gradle/BuildGradleModifier.kt
- buildSrc/src/main/java/com/duckduckgo/gradle/InputExtractor.kt
- buildSrc/src/main/java/com/duckduckgo/gradle/IntermoduleDependencyManager.kt
- buildSrc/src/main/java/com/duckduckgo/gradle/ModuleCreator.kt
- buildSrc/src/main/java/com/duckduckgo/gradle/ModuleType.kt
- buildSrc/src/test/java/com/duckduckgo/gradle/InputExtractorTest.kt
- buildSrc/src/test/java/com/duckduckgo/gradle/ModuleTypeTest.kt
- example-feature/example-feature-api-android/build.gradle
- example-feature/example-feature-api/build.gradle
- example-feature/example-feature-impl/build.gradle
- example-feature/example-feature-impl/lint-baseline.xml
- example-feature/readme.md
Task/Issue URL: https://app.asana.com/0/0/1205678561572065/f 
Adds tooling to allow for creation of new modules which come with the recommended structure and gradle dependencies. Supported module types:
- Pure Kotlin API modules
- Android-aware API modules
- impl modules
Note: `store` modules have recently became redundant and is therefore not supported through this tooling.
For safety, the tooling will fail if you run it against an existing module
> Add module templating to streamline new module creation

- app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteActivity.kt
- app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteViewModel.kt
- app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt
- app/src/main/java/com/duckduckgo/app/brokensite/model/BrokenSite.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/test/java/com/duckduckgo/app/brokensite/BrokenSiteDataTest.kt
- app/src/test/java/com/duckduckgo/app/brokensite/api/BrokenSiteSubmitterTest.kt
- app/src/test/java/com/duckduckgo/app/feedback/BrokenSiteViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesMultipleReportReferenceTest.kt
- app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesReferenceTest.kt
- browser-api/src/main/java/com/duckduckgo/browser/api/brokensite/BrokenSiteNav.kt
- common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/IntentExtensions.kt
- privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModel.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205957959864913/f
Add the reportFlow parameter to the broken site report pixel
> Add reportFlow param to the broken site report pixel

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessaging.kt
- content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessagingTest.kt
- site-permissions/site-permissions-api/src/main/java/com/duckduckgo/site/permissions/api/SitePermissionsManager.kt
- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerImpl.kt
- site-permissions/site-permissions-impl/src/test/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205860617093733/f
Add support for [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query)
First, update your local copy of contentScope.js to include changes in https://github.com/duckduckgo/content-scope-scripts/pull/820
_Session-based permissions: deny_
* **Note**: ideally this should be "denied", but we don't store denials on-disk. 
* We can revisit how to better handle this in https://app.asana.com/0/1200396763693192/1205944992235904/f
_Session-based permissions: allow_
_Permanent permissions_
_Unsupported_
None
> Add support for permissions API

- app/src/test/java/com/duckduckgo/app/statistics/api/StatisticsRequesterTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/api/StatisticsRequester.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205887954648090/f
Remove variant when receiving a generalised ATB from atb.js
- Ensure you have a variant allocated. e.g `ma`
- Ensure you have an old ATB value persisted. e.g `v230-5`
- Put a log in Line 169 on StatisticsRequester : e.g. `Timber.e("updatedVersion from atb.js: newATB=${retrievedAtb.updateVersion}, newVariant=${store.variant}")`
_app_use_
- Open the app
_search_
- Perform a search
> Remove variant when updated generalised ATB

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/res/layout/content_site_location_permission_dialog.xml
- app/src/main/res/layout/content_system_location_permission_dialog.xml
- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
- site-permissions/site-permissions-impl/src/main/res/layout/content_site_drm_permission_dialog.xml
Task/Issue URL: https://app.asana.com/0/0/1206009544951106/f 
This PR makes the EME and location dialogs scrollable and dismissible
* Test on a device/emulator with a small screen (e.g., Pixel 1)
_DRM_
_Location_
> Fix dialog permissions

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206015104790530/f 
----- 
> Update content scope scripts to version 4.52.0

- app/src/test/java/com/duckduckgo/app/browser/autofill/ResultHandlerSaveLoginCredentialsTest.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/ResultHandlerSaveLoginCredentials.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDisablingDeclineCounter.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/CredentialEverPopulatedObserver.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDisablingDeclineCounterTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/CredentialEverPopulatedObserverTest.kt
Task/Issue URL: https://app.asana.com/0/1203822806345703/1205939031559534/f 
Change the way the Autofill decline counter works to ensure it is disabled when credentials are added regardless of how they were added. 
Previously, this required the decline counter to be manually disabled at the point in the code that was adding a credential (e.g., when handing the result of save credential prompt) but wasn't handling the other places that a credential could be created (sync + manually created). 
This PR introduces a dedicated observer on the credential count that will automatically disable the decline counter if it detects one or more credentials exist.
Logcat filter: `package:mine & (message~:"CredentialEverPopulatedObserver" | message~:"Permanently disabling Autofill decline counter" | …
> Ensure autofill disable prompt disabled no matter how a credential is saved

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillScreens.kt
- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/domain/app/LoginCredentials.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementActivity.kt
- autofill/autofill-internal/build.gradle
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205232499768032/f 
Migrate from Autofill's bespoke Activity launcher mechanism (which pre-dated the existence of `GlobalActivityStarter`) to using `GlobalActivityStarter`.
Test using `internal` build type.
(You should still have a credential saved for fill.dev and be on fill.dev from the previous step)
> Migrate from Autofill's bespoke activity launcher to GlobalActivityStarter

- app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/state/VpnStateMonitor.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/removal/VpnFeatureRemoverStateListener.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/heartbeat/VpnServiceHeartbeat.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/state/RealVpnStateMonitor.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/state/VpnStateMonitorService.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/AppTPReminderNotificationScheduler.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModel.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/app/tracking/AppTPVpnConnectivityLossListenerTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/health/AppTPCPUMonitorTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/service/RestartReceiverTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/AppTPReminderNotificationSchedulerTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModelTest.kt
- app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/model/VpnDatabaseModels.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/WgVpnNetworkStack.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModel.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/notification/NetPDisabledNotificationScheduler.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/WgVpnNetworkStackTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModelTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/notification/NetPDisabledNotificationSchedulerTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206000100414553/f
Improve VPNServiceState to avoid hardcoding snooze duration and define it in a single place only.
repeat https://app.asana.com/0/0/1205989766118758/f
> Improve handling for snooze state

- privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModel.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1206017073615834/f
Fixes issue where privacy dashboard immediately closes when site is allow listed.
> Fix privacy dashboard closing when site is allow listed

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/survey/db/SurveyDaoTest.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/java/com/duckduckgo/app/survey/api/SurveyDownloader.kt
- app/src/main/java/com/duckduckgo/app/survey/api/SurveyRepository.kt
- app/src/main/java/com/duckduckgo/app/survey/db/SurveyDao.kt
- app/src/main/java/com/duckduckgo/app/survey/ui/SurveyViewModel.kt
- app/src/test/java/com/duckduckgo/app/survey/api/SurveyDownloaderTest.kt
- app/src/test/java/com/duckduckgo/app/survey/api/SurveyRepositoryTest.kt
- app/src/test/java/com/duckduckgo/app/survey/ui/SurveyViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204904890200326/f
Removed surveyDao instances from external constructors so only surveyRepository is injected
- Change survey endpoints to `https://ddg-sandbox.s3.amazonaws.com/survey/v2/survey-mobile.json` in SurveyService
- Go to the browser screen
> Remove surveyDao injections from external classes

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206026908343659/f 
----- 
> Update content scope scripts to version 4.53.0

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1205967799812886/f
- Fixes a crash when an app intent fallback URL opens in a new tab.
- Fixes an issue where the "Open in another app" dialog is not shown.
_With Amazon app not installed_
_With Amazon app installed_
> Fix new tab threading issue and external dialog not showing

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205966157363555/f 
See task
See task
> Add restore option

- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1206049262682135/f
Revert Fix `get_server_name` crash when TLS record fragmentation
Smoke tests for AppTP and VPN, fresh install and app update
> Revert Fix `get_server_name` crash when TLS record fragmentation

- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/dialog/ActionBottomSheetDialog.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/dialog/PromoBottomSheetDialog.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206057713910059/f
Hide bottom sheet dialog when an action button is tapped. This will affect to ADS components:
- ActionBottomSheetDialog
- PromoBottomSheetDialog
- Go to Settings > ADS preview
- Go to DIALOGS Tab
> ADS: Dismiss dialog when action button is tapped in BottomSheet components

- autofill/autofill-impl/build.gradle
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsRateLimitSyncMessagePlugin.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsRateLimitView.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsRateLimitViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSyncDataPersister.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSyncFeatureListener.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSyncNotificationBuilder.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSyncStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/SyncMessagePluginModule.kt
- autofill/autofill-impl/src/main/res/layout/credentials_notification_rate_limit.xml
- autofill/autofill-impl/src/main/res/layout/view_credentials_rate_limit_warning.xml
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/AppCredentialsSyncFeatureListenerTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/CredentialsRateLimitViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/CredentialsSyncDataPersisterTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/RealCredentialsSyncStoreTest.kt
- sync/sync-impl/src/main/res/layout/view_sync_enabled.xml
- sync/sync-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206017382069031/f 
Notify user when sync is paused due collection limit or payload too large.
_Feature 1_
```
is Success -> {
persisterPlugins.getPlugins().forEach {
it.onError(SyncErrorResponse(changes.type, COLLECTION_LIMIT_REACHED))
}
//persistChanges(result.data, conflictResolution)
}
```
> Credentials rate limit ui

- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/FeatureTogglesTest.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/TestTriggerFeature.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206058566871760/f
`ForcesDefaultVariantIfNull` was added with the intent to be used by experiments very close to the app creation.
However after discussing internally (see asana) this should be the default hardcoded behavior. And so the `ForcesDefaultVariantIfNull` annotation is not needed
_Test_
Repeat tests from https://github.com/duckduckgo/Android/pull/3758
> Remove ForcesDefaultVariantIfNull and make it default behavior

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/res/layout/content_site_location_permission_dialog.xml
- app/src/main/res/layout/content_system_location_permission_dialog.xml
- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
- site-permissions/site-permissions-impl/src/main/res/layout/content_site_drm_permission_dialog.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206052137816789/f
* Remove icon from location + DRM dialogs
* Deny permission if user clicks outside the dialog
> Remove icon from location + DRM dialogs

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/camera/CameraHardwareChecker.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/CameraCaptureResultHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/launcher/UploadFromExternalCameraLauncher.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/permission/RealExternalCameraSystemPermissionsHelper.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/postprocess/CameraCaptureDelayedDeleter.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/postprocess/CameraCaptureImageMover.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/postprocess/DeleteCameraCaptureWorker.kt
- app/src/main/res/values/donottranslate.xml
- common/common-ui/src/main/res/drawable/ic_camera_24.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206005059663926/f 
When encountering webpages which allow users to upload an image, currently the only option is to choose an existing image from the gallery.
With this PR, users will have the ability to choose between uploading an existing image from their gallery or taking a new photo from the camera and uploading that. 
Translations will follow separately.
<hr/>
<hr/>
> Support taking a new photo when prompted to upload an image

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206145818662390/f
This PR adds new pixel to measure pull-to-refresh usage. We already have similar one for the refresh button in the options menu.
> Send pixel when page reload is triggered by pull-to-refresh

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206156219234206/f 
----- 
> Update content scope scripts to version 4.55.0

- app/src/main/AndroidManifest.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206133268245246/f 
Adds the fullBackupOnly set to false to hopefully avoid some devices to do a full backup instead of a key-value.
> Add flag to set fullbackup to false

- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/RealSyncSavedSitesRepository.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SyncSavedSitesRepository.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/store/SavedSitesSyncMetadataDao.kt
Task/Issue URL: https://app.asana.com/0/1157893581871903/1206091622490132
This PR enables the reaction to sync events for the metadata table.
When sync is disabled (logout or account deletion) we want to delete the content of the metadata table.
_Account logout_
_Account deletion_
> Sync: Improve lists mechanism - sync events

- app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml
Task/Issue URL: https://app.asana.com/0/715106103902962/1206159443951469/f
See title
_Feature 1_
> Remove reference to beta in AppTP banner after 1 day 

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt
- browser-api/src/main/java/com/duckduckgo/app/global/model/Site.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1206139108436193/f 
This task removes errors from a site after a manual refresh has been triggered. It also fixes the yeti screen stuck even after a successul refresh of the page. It doesn't add the pull to refresh capability though. Comming soon.
> Removes errors after a manual refresh

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt
- app/src/main/res/layout/fragment_browser_tab.xml
- browser-api/src/main/java/com/duckduckgo/app/global/model/Site.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205928683641648/f 
This PR adds pull to refresh when the error screen is shown. Fixes https://github.com/duckduckgo/Android/issues/3801
> Add pull to refresh when the error screen is shown

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/CountryUtils.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/CountryUtilsKtTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/FakeNetpEgressServersProvider.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206158080167031/f
Servers in UK come with GB country code not UK
See Asana task
> Fix GB location UI

- app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1206153302008458/f 
This PR adds support for advanced syntax in SERP
> Support advanced syntax in SERP

- app/src/main/AndroidManifest.xml
- autofill/autofill-impl/src/main/AndroidManifest.xml
Task/Issue URL: https://app.asana.com/0/414730916066338/1206189169008466/f 
The default side-effect of a config change is for activities to be destroyed and re-created. However, this is a jarring UX for the browser so there are a number of config changes we exclude from this process, which prevents the Activities from being destroyed.
When a bluetooth keyboard connects/disconnects, that might trigger `keyboard|navigation` config changes. At the moment, that means the current page tab is destroyed and recreated / reloaded when the keyboard (dis)connects.
This PR excludes those events from trigger activity death, like we do for many other config changes.
- QA optional
If you do have a bluetooth keyboard to hand, you can load up a page in the browser and connect or disconnet the keyboard; …
> Add additional configChanges to stop Activities being destroyed when bluetooth keyboard (dis)connects

- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206082649420187/f
* Fix bug where selecting Always Allow set DRM to Ask.
* Don't store session-based DRM permission
> Fix DRM permission saving

- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/GlobalUncaughtExceptionHandler.kt
- app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
- app/src/test/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
- lint-rules/src/main/java/com/duckduckgo/lint/NonCancellableDetector.kt
- lint-rules/src/main/java/com/duckduckgo/lint/registry/DuckDuckGoIssueRegistry.kt
- lint-rules/src/test/java/com/duckduckgo/lint/NonCancellableDetectorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205269597285007/f 
Replaces usages of NonCancellable when launching a coroutine.
Replaced by AppCoroutineScope.
_Smoke test_
> Stop using NonCancellable when launching coroutines

- .maestro/security_tests/5_-_AddressBarSpoof,_downloadpath.yaml
Task/Issue URL:  https://app.asana.com/0/414730916066338/1206201528208884/f
The e2e tests were failing due to us relying on a third party site to perform a redirect for us. This was moved to privacy-test-pages in this commit: https://github.com/duckduckgo/privacy-test-pages/commit/f56ef132715362eba1a08449fa168f394aec216e. To accommodate for the new redirector, the test needs to be updated as well since the browser behaved slightly differently under the previous redirector.
maestro test
E2E test result: https://github.com/duckduckgo/Android/actions/runs/7286394253
> Update downloadPath security test to match new test case result.

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/AppDeviceSyncState.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncFeature.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncFeatureToggle.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/RealSyncEngine.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/SyncNotificationBuilder.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivity.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModel.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncDisabledView.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncDisabledViewModel.kt
- sync/sync-impl/src/main/res/layout/notification_sync_paused.xml
- sync/sync-impl/src/main/res/layout/view_sync_disabled.xml
- sync/sync-impl/src/main/res/layout/view_sync_disabled_warning.xml
- sync/sync-impl/src/main/res/layout/view_sync_enabled.xml
- sync/sync-impl/src/main/res/values/donottranslate.xml
- sync/sync-impl/src/test/java/com/duckduckgo/sync/AppSyncDeviceIdsTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppDeviceSyncStateTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncRemoteFeatureToggleTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/engine/SyncEngineTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModelTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncDisabledViewModelTest.kt
- sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206046777189412/f 
Add Remote flags around sync.
https://app.asana.com/0/0/1206190385973972/f
> Feature flag sync

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/1114857721287938/1206213247675490/f 
Fixes a bug where going to the home screen after being in the browser blocks the favorite UX and you can pull to refresh.
> Hide browser layout when in home screen

- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206199606526279/f 
Removes a trailing `.` from an autofill string in password management screen.
> Update autofill enabled toggle's subtitle to remove trailing period

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/0/1206243311279019/f
Updated the file chooser code to show the camera option when a mime type starting with `image/` is found.
> Android: Add support to upload camera images for OnlyFans and Instagram

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206197392286444/f
Converted file extensions to mime types when uploading files. 
This fixes https://app.asana.com/0/1200277586140538/1205993679840904/f
See the task for the website used for testing.
> Android: allow to upload files when "accept" values are file extensions

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/1163321984198618/1206248386427115/f
Added support for the capture field used in conjunction with the image accept type.
We start the camera (not the file chooser) when the `capture` is enabled, camera is available and only "image" is accepted.
_Capture enabled with "image" only_
_Capture enabled with "image" and other types_
_Capture not enabled_
> Android: Add support for the capture field

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206293582077378/f 
----- 
> Update content scope scripts to version 4.59.0

- app/src/test/java/com/duckduckgo/app/bookmarks/model/SavedSitesRepositoryTest.kt
- app/src/test/java/com/duckduckgo/app/bookmarks/service/SavedSitesExporterTest.kt
- app/src/testInternal/java/com/duckduckgo/app/bookmarks/model/SavedSitesParserTest.kt
- saved-sites/saved-sites-api/src/main/java/com/duckduckgo/savedsites/api/SavedSitesRepository.kt
- saved-sites/saved-sites-api/src/main/java/com/duckduckgo/savedsites/api/models/Models.kt
- saved-sites/saved-sites-api/src/main/java/com/duckduckgo/savedsites/api/service/SavedSitesImporter.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/SavedSitesRepository.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/service/SavedSitesExporter.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/service/SavedSitesImporter.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/service/SavedSitesParser.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithm.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205538580267653/f
Fixes two issues:
- Favorited bookmarks are no longer duplicated on import
- Bookmark/folder order is respected for import and export
> Fix bookmarks import and export bug

- app/src/main/java/com/duckduckgo/app/global/install/AppInstallStore.kt
- app/src/main/java/com/duckduckgo/app/reinstalls/DownloadsDirectoryManager.kt
- app/src/main/java/com/duckduckgo/app/reinstalls/ReinstallAtbListener.kt
- app/src/test/java/com/duckduckgo/app/reinstalls/ReinstallAtbListenerTest.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/VariantManagerImpl.kt
- experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/ExperimentationVariantManagerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206329522328638/f
Add implementation for creating a new DuckDuckGo directory in Downloads folder for Android 11 onwards
_User with Android version < 11_
- Download an image giving storage permissions
- Close and open the app again
**_Android version > 10_**
_Existing user_
- Make sure you have a previous install
_New user install_
- Fresh install from branch
_Returning user install_
- Fresh install from branch
- Uninstall and install the app again from branch
_Manual directory removal_
- Fresh install from branch
- Remove `DuckDuckGo' directory manually from your device Downloads folder
- Open the app again
- Check new `DuckDuckGo` directory has **NOT** been created again in …
> new DuckDuckGo directory in Downloads

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/test/java/com/duckduckgo/app/bookmarks/model/SavedSitesRepositoryTest.kt
- app/src/test/java/com/duckduckgo/app/bookmarks/service/SavedSitesExporterTest.kt
- app/src/testInternal/java/com/duckduckgo/app/bookmarks/model/SavedSitesParserTest.kt
- saved-sites/saved-sites-api/src/main/java/com/duckduckgo/savedsites/api/SavedSitesRepository.kt
- saved-sites/saved-sites-api/src/main/java/com/duckduckgo/savedsites/api/models/Models.kt
- saved-sites/saved-sites-api/src/main/java/com/duckduckgo/savedsites/api/service/SavedSitesImporter.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/SavedSitesRepository.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/service/SavedSitesExporter.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/service/SavedSitesImporter.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/service/SavedSitesParser.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithm.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205538580267653/f
Fixes two issues:
- Favorited bookmarks are no longer duplicated on import
- Bookmark/folder order is respected for import and export
> Fix bookmarks import and export bug retry

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/VpnPixelParamRemovalPlugin.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/DnsChangeCallback.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStackTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203410036713941/f
Try out a fix for a subset of moto g devices for which AppTP doesn't work properly.
Check the configurations in the table below and verify the outcome, where
TLS blocking means
* DnsChangeCallback is never registered
* When AppTP only is enabled, `VpnTunnelConfig` never configures a DNS
* When VPN is enabled (irregardless of AppTP), VPN DNS is always configured
* Tracker attempts are blocked when AppTP is enabled
* 
DNS blocking
* DnsChangeCallback is registered
* Network changes (WIFI<>CELL) are detected and DNS is reconfigured (you can check this with DNS leak test app)
* Tracker attempts are blocked when AppTP is enabled
| moto g | private DNS | apptp | netp | Outcome        | …
> Fix moto g shortlist of devices for AppTP

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/dialog/AutofillOverlappingDialogDetector.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelInterceptor.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/DefaultAutofillOverlappingDialogDetector.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/DefaultAutofillOverlappingDialogDetectorTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206318827324908/f 
Adds temporary logic to detect scenarios where we are trying to show an Autofill dialog and there is already one showing. We are trying to run down a theory that perhaps this is leading to an anomaly.
This code will be removed again in the near future.
Testing this requires using Chrome DevTools to trigger arbitrary JS. 
- `Found 1 existing autofill tags: [ CredentialAutofillPickerDialog ]` 
- `Pixel sent: m_autofill_overlapping_dialog with params: {urlMatch=true, newDialogTag=CredentialSavePickerDialog, existingDialogTags=CredentialAutofillPickerDialog} {}`
> Detect scenarios where Autofill dialogs would overlap

- app/src/androidTest/java/com/duckduckgo/app/email/EmailInjectorJsTest.kt
- app/src/main/java/com/duckduckgo/app/autofill/DefaultEmailProtectionJavascriptInjector.kt
- app/src/main/java/com/duckduckgo/app/email/EmailInjectorJs.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/AutofillJavascriptEnvironmentConfiguration.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/AutofillJavascriptLoader.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/InlineBrowserAutofillConfigurator.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/configuration/InlineBrowserAutofillConfiguratorTest.kt
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
- autofill/autofill-internal/src/main/res/values/donottranslate.xml
- browser-api/src/main/java/com/duckduckgo/app/autofill/EmailProtectionJavascriptInjector.kt
Task/Issue URL: https://app.asana.com/0/1203115518054842/1206299001940948/f 
Adds a dev setting supporting switching between normal production `Autofill.js` usage to a debug version. This is to make autofill-related things easier to debug, especially for the javascript engineers.
> Add internal dev setting to allow debug autofill JS to be selected on the fly

- experiments/experiments-api/src/main/java/com/duckduckgo/experiments/api/VariantConfig.kt
- experiments/experiments-impl/build.gradle
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/ExperimentFiltersManager.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/ExperimentVariantRepository.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/VariantManagerImpl.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/di/ExperimentsModule.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/store/ExperimentsDatabase.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/store/VariantManagerEntity.kt
- experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/ExperimentFiltersManagerImplTest.kt
- experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/VariantManagerImplTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206193424728741/f
- Change `const val PRIVACY_REMOTE_CONFIG_URL` to `https://www.jsonblob.com/api/1168612786158034944`
- There is a log in `VariantManagerImpl` _Line 136_ when a new variant allocation is made. This way, you can check if the variant has been allocated correctly
_Android version filter_
- Add the API version of your device you are testing with in the `filters` parameter.in the JSONBlob endpoint e.g.
_Android version filter doesn't match_
- Add a different API version from your device you are testing with in the `filters` parameter in the JSONBlob endpoint e.g.
_No filters_
- Remove filters parameter or leave it empty
_Filters combined 1_
- Add the API version of your …
> Android version filter for experiments

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/RealSyncCrypto.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/di/SyncModule.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/error/SyncOperationErrorRecorder.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/error/SyncOperationErrorRepository.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/stats/SyncStatsRepository.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncCryptoTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/error/SyncOperationErrorRecorderTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/error/SyncOperationErrorRepositoryTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/pixels/SyncPixelsTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/stats/SyncStatsRepositoryTest.kt
- sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncDatabase.kt
- sync/sync-store/src/main/java/com/duckduckgo/sync/store/dao/SyncOperationErrorDao.kt
- sync/sync-store/src/main/java/com/duckduckgo/sync/store/model/SyncDatabaseModels.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205581521828305/f 
This PR brings back the Encrypy / Decrypt pixel.
Instead of launching it when it happens, we are sending the stats in the daily pixel.
- In RealSyncCrypto, make sure that encrypting always calls:
`syncOperationErrorRecorder.record(SyncOperationErrorType.DATA_ENCRYPT)`
- In RealSyncCrypto, make sure that decrypting always calls:
`syncOperationErrorRecorder.record(SyncOperationErrorType.DATA_DECRYPT)` 
- Change getYesterdayDailyStats in RealSyncStatsRepository to return today’s data
_Daily Pixel_
> try-catch encrypt decrypt and pixel

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/provider/CredentialsSyncDataProvider.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt
- sync/sync-api/src/main/java/com/duckduckgo/sync/api/engine/SyncableDataProvider.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/RealSyncEngine.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/error/SyncOperationErrorRecorder.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/error/SyncOperationErrorRepository.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/engine/FakeSyncableDataProvider.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/engine/SyncEngineTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/error/SyncOperationErrorRepositoryTest.kt
- sync/sync-settings-impl/src/main/java/com/duckduckgo/sync/settings/impl/SettingsSyncDataProvider.kt
- sync/sync-store/src/main/java/com/duckduckgo/sync/store/model/SyncDatabaseModels.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206158813217559/f 
Capture exceptions if they happen inside provider or persister implementation. And add an event to receive it in our daily stats.
_Feature 1_
> Add errors from provider and persister to daily stats

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/RealSyncEngine.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/error/SyncOperationErrorRecorder.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/error/SyncOperationErrorRepository.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/engine/SyncEngineTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/error/SyncOperationErrorRepositoryTest.kt
- sync/sync-store/src/main/java/com/duckduckgo/sync/store/model/SyncDatabaseModels.kt
Task/Issue URL: https://app.asana.com/0/0/1206402944085410/f
Add timestamp and orphans conflict to daily pixel
_Timestamp conflict_
_Orphans present_
> Sync: Timestamp and Orphans as daily stats

- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/dialog/CustomAlertDialogBuilder.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/dialog/RadioListAlertDialogBuilder.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/dialog/StackedAlertDialogBuilder.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/dialog/TextAlertDialogBuilder.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204448904099019/f
Add cancellable callback to Dax Alert dialogs
- [Android Component: TextAlertDialog](https://app.asana.com/0/0/1202943892847396/f)
[Android Component: StackedAlertDialog](https://app.asana.com/0/0/1202943892847397/f)
[Android Component: RadioListAlertDialog](https://app.asana.com/0/0/1202943892847398/f)
[Android Component: CustomAlertDialog](https://app.asana.com/0/0/1203508448986202/f)
- Tap on DIALOGS tab
- Tap on "Text Alert Dialog Cancellable"
> ADS: onDialogCancelled callback added to alert dialogs

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandlerTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedOfflinePixelSender.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedPixelEntity.kt
- app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
- app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
- app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/OptimizeTrackerEvaluationRCWrapper.kt
Task/Issue URL: https://app.asana.com/0/0/1206427492016652/f 
Read `optimizeTrackerEvaluation`, use it to decide whether or not to execute the optimized tracker logic and add its status to page loaded pixel
_Database migration_
_Check pixels sent_
_Check pixels sent_
(*): Pixels aren't fired immediately, they might take up to 3 hours to appear
No UI changes
> Add support for running A/B test on performance optimizations

- app/src/main/java/com/duckduckgo/app/onboarding/di/WelcomePageModule.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/NotificationPermissionsFeatureToggles.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModel.kt
- app/src/test/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206161927270269/f
Android experiment implementation where the experimental group won't see notifications permissions prompt when app is installed.
_Pre Steps_
_Experimental variant_
```
{
"desc": "No notifications permissions prompt experimental group",
"variantKey": "mg",
"weight": 1,
"filters": {
"androidVersion": [
"34",
"33"
]
}
}
```
_Control variant_
```
{
"desc": "No notifications permissions prompt experimental group",
"variantKey": "mf",
"weight": 1,
"filters": {
"androidVersion": [
"34",
"33"
]
}
}
```
> Experiment: Remove notifications prompt for Android 13+

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206447940396946/f 
----- 
> Update content scope scripts to version 4.59.2

- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/ExperimentVariantRepository.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/VariantManagerImpl.kt
- privacy-config/privacy-config-impl/src/main/res/raw/privacy_config.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206462881489059/f
Load experiment variants from local `privacy_config` to remove the welcome animation delay
_Pre Steps_
-  [ ] Before every test you need to delete the DuckDuckGo folder from downloads
_Experimental variant_
```
{
"desc": "No notifications permissions prompt experimental group",
"variantKey": "mg",
"weight": 1,
"filters": {
"androidVersion": [
"34",
"33"
]
}
}
```
_Android >= 13_
_Android < 13_
_Control variant_
```
{
"desc": "No notifications permissions prompt experimental group",
"variantKey": "mf",
"weight": 1,
"filters": {
"androidVersion": [
"34",
"33"
]
}
}
```
_Returning users_
> Bundle notifications experiment in privacy_config.json

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deviceauth/AuthLauncher.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deviceauth/DeviceAuthenticator.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementActivity.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
- autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_list_mode.xml
- autofill/autofill-impl/src/main/res/menu/autofill_list_mode_menu.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deviceauth/FakeAuthenticator.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deviceauth/RealDeviceAuthenticatorTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
- autofill/autofill-internal/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/0/1206374582118438/f 
ℹ️ if you are using `internal` build type to test this, you can visit `Settings` -> `Autofill Dev Settings` to access options like adding hundreds of sample logins with one tap.
In this scenario, we have slightly different copy than when deleting-all with multiple passwords
> Autofill, support deleting all passwords, UI changes

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSyncMetadata.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/SyncCredentialsListener.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStoreTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/CredentialsSyncMetadataTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/SyncCredentialsListenerTest.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/CredentialsSyncMetadataDao.kt
Task/Issue URL: https://app.asana.com/0/0/1206350245635305/f 
Bulk notifies sync listener when delete-all is used.
> Autofill, support deleting all passwords, notifiy sync listener

- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesTimestampPersister.kt
Task/Issue URL:  https://app.asana.com/0/1174433894299346/1206474912857922/f
This PR changes the way we compare modifications. If the local object doesn’t
have a modifedDate, we assume that any comparison will not return as modifiedAfter.
> Sync: Modified After Behaviour

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
- app/src/main/java/com/duckduckgo/app/browser/mediaplayback/MediaPlayback.kt
- app/src/main/java/com/duckduckgo/app/browser/mediaplayback/MediaPlaybackFeature.kt
- app/src/main/java/com/duckduckgo/app/browser/mediaplayback/UnusedMediaPlaybackFeatureFeatureCodegenTrigger.kt
- app/src/main/java/com/duckduckgo/app/browser/mediaplayback/store/MediaPlaybackDao.kt
- app/src/main/java/com/duckduckgo/app/browser/mediaplayback/store/MediaPlaybackDatabase.kt
- app/src/main/java/com/duckduckgo/app/browser/mediaplayback/store/MediaPlaybackExceptionEntity.kt
- app/src/main/java/com/duckduckgo/app/browser/mediaplayback/store/MediaPlaybackRepository.kt
- app/src/main/java/com/duckduckgo/app/browser/mediaplayback/store/MediaPlaybackStore.kt
- app/src/test/java/com/duckduckgo/app/browser/mediaplayback/store/RealMediaPlaybackRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206024383416124/f
Added feature flag to control autoplay. 
_Without the flag_
_With the flag enabled_
_With the flag disabled_
> Android: play() can only be initiated by a user gesture issue

- .maestro/autofill/0_all.yaml
- .maestro/autofill/1_autofill_shown_in_overflow.yaml
- .maestro/autofill/2_autofill_reach_creds_management.yaml
- .maestro/autofill/3_autofill_manually_add_cred.yaml
- .maestro/autofill/4_search_logins.yaml
- .maestro/autofill/5_autofill_manually_updating_an_existing_credential.yaml
- .maestro/autofill/6_delete_logins.yaml
- .maestro/autofill/7_autofill_prompted_to_save_creds_on_form.yaml
- autofill/autofill-impl/build.gradle
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillGlobalCapabilityChecker.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deviceauth/DeviceAuthenticator.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementActivity.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/AutofillGlobalCapabilityCheckerImplSecureStorageAvailableTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
- versioning.gradle
Task/Issue URL: https://app.asana.com/0/1203822806345703/1206452714902883/f 
Since we require a device-level authentication mechanism (e.g., PIN/Password/Pattern etc...) to be in place to fully use `Autofill`, there are many parts of `Autofill` that we can't currently write UI tests for.
This PR allows setting a build flag when building the APK that will remove that limitation and will be set only for when running autofill UI tests. There are no changes to production behaviour.
**New build flag:** `autofill-disable-auth-requirement`
**Usage example:** `./gradlew assembleIR -Pautofill-disable-auth-requirement`
Under the hood, this will set a boolean which can be interrogated by `autofill-impl`'s `BuildConfig`.
This PR also introduces more maestro tests and convenience methods to run them: …
> Increase ability to run Android UI tests for Autofill by allowing device auth requirement to be bypassed (for UI testing builds only)

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/FeatureTogglesTest.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206413338208929/f
Improve the feature flagging system to:
* not require rollout steps
* allocate the rollout threshold just once
* other simplifications
All changes should be backwards compatible and don't modify behavior for existing or future flags
Perform test cases in https://app.asana.com/0/0/1206413338208951/f
> Improve FF framework

- autofill/autofill-impl/build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1206512928267585/f 
Remove `versioning.gradle` from being applied inside `autofill-impl`'s gradle (and the convenience function that used it). This was added to support a test convenience function, however, unintentionally meant that the `gradlew incrementBuildNumber` task was applied twice, and therefore broke when the nightly tried to call it (it ended up calling through to `:autofill-impl:incrementBuildNumber` which isn't intended.
QA optional
> Removes the dependency of autofill-impl's gradle file on versioning.properties as it breaks incrementBuildNumber task

- anvil/anvil-annotations/build.gradle
- anvil/anvil-annotations/src/main/java/com/duckduckgo/anvil/annotations/PriorityKey.kt
- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesPluginPointCodeGenerator.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/settings/SubsSettingsPlugin.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/DisplayModeSyncSettingsPlugin.kt
- settings/settings-api/src/main/java/com/duckduckgo/settings/api/ProSettingsPlugin.kt
- settings/settings-impl/build.gradle
- settings/settings-impl/src/main/java/com/duckduckgo/settings/impl/ProSettingModule.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/plugins/SubsSettingsPlugins.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206484244032077/f
See [asana task](https://app.asana.com/0/488551667048375/1206484244032077/f) and [API proposal](https://app.asana.com/0/488551667048375/1206484244031915)
Smoke test the app, this is backwards compatible change
> Sorted plugin points

- app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt
- app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
- app/src/test/java/com/duckduckgo/app/notification/AndroidSchedulerNotificationTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206420860078750/f
Check if notifications permissions have been granted in order to send a pixel for engagement notification shown
_Pre steps_
_Allow notifications permissions_
_Reject notifications permissions_
> Remove sending 'mnot' pixel when notifications disabled

- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
Task/Issue URL: https://app.asana.com/0/0/1206522179596625/f
See title
No UI changes
> Remove NYTimes from page loaded pixel allowlist

- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedOfflinePixelSender.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedPixelDao.kt
Task/Issue URL: https://app.asana.com/0/0/1206522173508080/f 
See title
_Test pixels sent_
* Replace `fun scheduleOfflinePixels()` with:
```
rivate fun scheduleOfflinePixels() {
Timber.v("Scheduling offline pixels to be sent")
val constraints = Constraints.Builder()
.setRequiredNetworkType(NetworkType.CONNECTED)
.build()
val request = PeriodicWorkRequestBuilder<OfflinePixelWorker>(SERVICE_INTERVAL, SERVICE_TIME_UNIT)
.addTag(WORK_REQUEST_TAG)
.setConstraints(constraints)
.setInitialDelay(0, SECONDS)
.setBackoffCriteria(BackoffPolicy.EXPONENTIAL, BACKOFF_INTERVAL, BACKOFF_TIME_UNIT)
.build()
workManager.enqueueUniquePeriodicWork(WORK_REQUEST_TAG, ExistingPeriodicWorkPolicy.REPLACE, request)
}
```
Pixels will be sent on next app launch
No UI changes
> Fix issue that caused only 1st page loaded pixel to be sent

- common/common-ui/src/main/java/com/duckduckgo/common/ui/themepreview/ui/component/textinput/ComponentTextInputFragment.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/text/DaxTextInput.kt
- common/common-ui/src/main/res/layout/component_text_input_view.xml
- common/common-ui/src/main/res/values/attrs-text-input.xml
- common/common-ui/src/main/res/values/widgets.xml
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetPWaitlistRedeemCodeActivity.kt
- network-protection/network-protection-impl/src/main/res/layout/activity_netp_waitlist_redeem_code.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204338910522509/f 
Add error state support to DaxtextInput and use it in NetP waitlist
_Check error status_
_Check single line and caps_
> Add error state support to DaxTextInput

- node_modules/@duckduckgo/content-scope-scripts/README.md
- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206568918219129/f 
----- 
> Update content scope scripts to version 4.63.0

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/TestTriggerFeature.kt
- privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeaturePlugin.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/PrivacyConfigPersister.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigPersisterTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206560594088721/f
We have an edge case where if a feature flag is present in the remote config before it's handled in the app, it will not be re-evaluated unless its `hash` changes.
This causes an issue in cases like the following example:
* release app version 1, that doesn't have any `testFlag` feature flag
* release to remote config a feature flag called `testFlag` rolled out to 99%
* app version 1 downloads the config that contains `testFlag` and ignores it as it doesn't know about it
* release app version 2 that contains and handles `testFlag`
* remote config is re-downloaded
* `testFlag` continues to be ignored because nothing has changed in it and its feature `hash` is the same
* to force a re-evaluation we'll need to eg. …
> Ensure we re-evaluate newly added feature flags

- app/src/androidTest/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandlerTest.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedOfflinePixelSender.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedPixelEntity.kt
- app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
- autoconsent/autoconsent-api/src/main/java/com/duckduckgo/autoconsent/api/Autoconsent.kt
- autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/RealAutoconsent.kt
- autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/di/AutoconsentModule.kt
- autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/ui/AutoconsentSettingsViewModelTest.kt
- autoconsent/autoconsent-store/src/main/java/com/duckduckgo/autoconsent/store/AutoconsentSettingsDataStore.kt
Task/Issue URL: https://app.asana.com/0/0/1206446781259752/f 
Add CPM status information to page loaded pixel
_Feature 1_
_Feature 2_
No UI changes
> Add CPM status to page load pixel

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206608309382825/f
Cancel always on previous monitor on VPN start
_Test_
> Cancel previous always on monitor on VPN start

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/applinks/AppLinksLauncher.kt
- app/src/main/java/com/duckduckgo/app/browser/applinks/AppLinksSnackBarConfigurator.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206614754803818/f
This extracts and refactors the app link logic into two classes: `AppLinkSnackBarConfigurator` and `AppLinksLauncher`.
> Extract applink logic from BrowserTabFragment

- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/domain/app/LoginCredentials.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/SecureStorage.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/SecureStorageModels.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/store/InternalAutofillStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/selecting/AutofillSelectCredentialsGrouper.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/selecting/AutofillSelectCredentialsSorter.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/selecting/ResultHandlerCredentialSelection.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/RealDuckAddressLoginCreatorTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStoreTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/securestorage/RealSecureStorageTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/passwordgeneration/ResultHandlerUseGeneratedPasswordTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/selecting/LastUpdatedCredentialSorterTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/selecting/LastUsedCredentialSorterTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/selecting/RealAutofillSelectCredentialsGrouperTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/selecting/ResultHandlerCredentialSelectionTest.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/db/SecureStorageDatabase.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/db/WebsiteLoginCredentialsEntity.kt
- autofill/autofill-store/src/test/java/com.duckduckgo.autofill.store/RealSecureStorageRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206534334888412/f 
Adds `last-used` as a field for saved credentials so that it can used in the sort order when presenting a list of passwords to autofill into a form.
ℹ️ When instructions say to add a saved login, it means:
- visiting `Overflow -> Passwords`
- Adding a login using the ➕ button
- Ensure it both a username and a password
> Surface the last-used password first in Autofill dialog for filling passwords

- app/src/test/java/com/duckduckgo/autofill/pixel/AutofillUniquePixelSenderTest.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillDeviceCapabilityReporter.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelSender.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206638124888251/f 
Re-establishes the hardware check for Autofill device capabilities (including the encrypted storage check). This was removed previously as it was assumed the values were unlikely to change over time, but recently seen an increase in feedback suggesting a newer device (Samsung S24) is hitting this scenario indicating it is something that can and will change over time. 
Logcat Filter: `package:mine message~:"capabilit"`
> Re-establish hardware check reporting for autofill capabilities

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206628523510268/f
See [task](https://app.asana.com/0/488551667048375/1206628523510268/f) for full context explanation
_Test_
-- repeat 3 times --
-- END repeat 3 times --
```kotlin
Index: app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
<+>UTF-8
diff --git a/app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt b/app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
--- a/app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt	(revision …
```
> Enforce declaredMethods order when evaluating FFs

- privacy-config/privacy-config-impl/src/main/res/raw/privacy_config.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206465832156620/f
Disable experiment from local privacy_config.json
_Android >= 13_
_Android < 13_
_Existing sample users_
> Disable no notifications prompt experiment

- app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModel.kt
- app/src/test/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModelTest.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/SavedSitesRepository.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206579231041835/f
This PR fixes the issue that adding a favourite doesn’t immediately trigger Sync
The modified date wasn’t correct, so we fixed that.
_From develop_
❌ neither operation triggers sync (sync is triggered, but bookmarks says no changed)
_From this branch_
> Sync: Add a Favourite triggers Sync

- app/src/main/AndroidManifest.xml
- app/src/main/res/xml/backup_rules_android_11_and_older.xml
- app/src/main/res/xml/backup_rules_android_12_upwards.xml
Task/Issue URL: https://app.asana.com/0/0/1206667832334038/f 
Device backups are mostly disabled except for one instance where device-to-device backups are allowed. I've only noticed it happening for recent Samsung devices (specifically, the Samsung S24) but might be the same for others. For these devices:
- they ignore `appBackup="false"` (which might be reasonable, given it's deprecated)
- they do a device-to-device back (e.g., as part of the new device setup wizard where you can copy from your old phone)
- this leaves the app working except for the secure functions (Autofill, Email Protection, Sync) which indicate that the "device is not supported". The reason for this is that encrypted data has been migrated between the devices but the decryption key was not, leaving those secure …
> Introduce backup rules to exclude backups

- app/src/main/java/com/duckduckgo/app/email/db/EmailEncryptedSharedPreferences.kt.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1206692157281177/f 
Attempts to detect when user is in a state whereby the encrypted data is not accessible and tests whether they could access encrypted data on a new test file.
- if they can access encrypted data on a new test file, this is indicative that their local encrypted shared preferences is permanently undecryptable, and we should consider if we need a (possibly user-facing) mitigation to let them wipe it and re-initialise
- if they can't access encrytped data on a new test file, it's probable their device just can't support it
Also brings in the latest version of the AndroidX security library, as there are some related changes to the exception that is thrown in this scenario (including changing the thrown exception type …
> Detect encryption error state that could be recoverable

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/pixels/RealNetworkProtectionPixelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206685546588309/f
See [asana](https://app.asana.com/0/488551667048375/1206685546588309/f) task
> Daily to weekly cohort

- downloads/downloads-impl/build.gradle
- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DataUriDownloader.kt
- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DownloadConfirmationFragment.kt
- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DownloaderUtil.kt
- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/FileDownloadCallback.kt
- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/FileDownloadNotificationActionReceiver.kt
- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/FilenameExtractor.kt
- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/NetworkFileDownloader.kt
- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/UrlFileDownloadCallManager.kt
- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/UrlFileDownloader.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206718079780225/f
Fix a OOM crash that happens in production when using Timber.d() and parameters are larged. In this case a url that embeds a file to download
The fix is replacing Timber by logcat, which is something we wanted to do anyways little by little.
> Fix OOM crash on Timber.d

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206720880171667/f 
----- 
> Update content scope scripts to version 5.0.0

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncAccountRepositoryTest.kt
To prevent phantom devices being allowed to sync a user's data, we automatically logout devices that cannot be decrypted, instead of just ignoring them.
Task/Issue URL:  https://app.asana.com/0/0/1206693867033120/f
It is possible for someone to sync a device to another user's account such that the device data cannot be decrypted. This results in an invalid "phantom" device that can sync data from a user's account without their knowledge (and they are unable to view or remove said device from the UI).
As a result, we introduce a fix that automatically logs out invalid devices to prevent this issue from occurring. In the very rare case that a device accidentally contains invalid encrypted data, the rightful owner of that device should be able to just re-sync it.
Note: requires two devices …
> Automatically logout invalid sync devices

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206718079780252/f
Ensure the `nullTun` is set to `null` upon failure so that we stop the VPN rather than risking progressing in unstable state
Smoke tests AppTP/VPN
> Ensure nullTun is null on error/timeout

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206733226973439/f 
----- 
> Update content scope scripts to version 5.1.0

- app/src/main/java/com/duckduckgo/app/privacy/db/RealUserAllowListRepository.kt
- app/src/test/java/com/duckduckgo/app/privacy/db/UserAllowListRepositoryTest.kt
- autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/di/AutoconsentModule.kt
- autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/remoteconfig/AutoconsentFeatureSettingsRepository.kt
- autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/remoteconfig/RealAutoconsentFeatureSettingsRepositoryTest.kt
- web-compat/web-compat-impl/src/main/java/com/duckduckgo/webcompat/impl/di/WebCompatModule.kt
- web-compat/web-compat-store/src/main/java/com/duckduckgo/webcompat/store/WebCompatRepository.kt
- web-compat/web-compat-store/src/test/java/com/duckduckgo/webcompat/store/WebCompatRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206738751021077/f
Fix `SQLiteDatabaseLockedException` crash that happens because vpn process unnecessarily warms in memory cache for something that is not use in vpn process. Causing it to race with main process
Related to https://github.com/duckduckgo/Android/pull/4189
Code review and smoke test the app
Make sure the dbs involved load data normally when opening the browser
> Fix SQLiteDatabaseLockedException

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206743589402889/f 
----- 
> Update content scope scripts to version 5.2.0

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserChromeClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206703905023237/f
Removes `WebChromeClient`’s default video poster image
> Add transparent video poster image

- app/src/main/java/com/duckduckgo/app/browser/menu/BrowserPopupMenu.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206738710607101/f
Makes the browser menu the same width in portrait and landscape.
> Fix landscape menu width

- voice-search/voice-search-impl/src/main/AndroidManifest.xml
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/RealVoiceSearchAvailability.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/language/LanguageSupportChecker.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/language/LanguageSupportCheckerDelegate.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/language/LocaleChangeReceiver.kt
- voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/RealVoiceSearchAvailabilityTest.kt
- voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/language/RealLanguageSupportCheckerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206752616572876/f
Determines if the matching locale language packs are installed for voice search.
- Uses `SpeechRecognizer.checkRecognitionSupport()` to determine `isLanguageSupported()`.
- Uses `Intent.ACTION_LOCALE_CHANGED` to update the UI if the locale is changed.
_With matching locale and voice pack_
_With non-matching locale and voice pack_
> Add voice language check

- app/src/androidTest/java/com/duckduckgo/app/browser/WebViewRequestInterceptorTest.kt
- app/src/androidTest/java/com/duckduckgo/app/global/api/ApiRequestInterceptorTest.kt
- app/src/androidTest/java/com/duckduckgo/app/referencetests/DomainsReferenceTest.kt
- app/src/androidTest/java/com/duckduckgo/app/referencetests/SurrogatesReferenceTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- user-agent/user-agent-api/src/main/java/com/duckduckgo/user/agent/api/ClientBrandHintProvider.kt
- user-agent/user-agent-api/src/main/java/com/duckduckgo/user/agent/api/UserAgentProvider.kt
- user-agent/user-agent-impl/build.gradle
- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/ClientBrandHintProvider.kt
- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/UserAgentProvider.kt
- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/di/ClientBrandHintModule.kt
- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/remoteconfig/ClientBrandHintFeature.kt
- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/remoteconfig/ClientBrandHintFeatureModels.kt
- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/remoteconfig/ClientBrandHintFeatureSettingsRepository.kt
- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/remoteconfig/ClientBrandHintFeatureSettingsStore.kt
- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/store/ClientBrandHintDao.kt
- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/store/ClientBrandHintDatabase.kt
- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/store/ClientBrandHintDatabaseModels.kt
- user-agent/user-agent-impl/src/test/java/com/duckduckgo/user/agent/impl/UserAgentProviderTest.kt
Task/Issue URL: https://app.asana.com/0/1174433894299346/1206613427401112
For Branding enabled replace PrivacyConfigService URL with https://jsonblob.com/api/jsonBlob/1215300292118962176
For Branding disabled replace PrivacyConfigService URL with https://jsonblob.com/api/jsonBlob/1215411576298659840
Filter log with ClientBrandHintProvider
Use chrome dev tools to inspect header
_Default when branding enabled_
_Default when branding disabled_
_Branding enabled in exception “as.com” (Chrome branding)_
_Branding enabled in exception “example.com” (Android WebView branding)_
_Branding enabled navigate through links_
_Branding disabled in exception “as.com"_
---
- https://app.asana.com/0/0/1206765381189699
> CH - set per site basis

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206847749423469/f 
----- 
> Update content scope scripts to version 5.5.0

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
> Update content scope scripts to version 5.6.0

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206937254485445/f 
----- 
> Update content scope scripts to version 5.8.0

- app/src/main/java/com/duckduckgo/app/global/install/AppInstallStore.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/ExperimentVariantRepository.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/VariantManagerImpl.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/reinstalls/BackupServiceDataStore.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/reinstalls/DownloadsDirectoryManager.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/reinstalls/ReinstallAtbListener.kt
- experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/reinstalls/ReinstallAtbListenerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206965708683424/f
Move the `ReinstallAtbListener` into the `experiments-impl` module
_User with Android version < 11_
- Download an image giving storage permissions
- Close and open the app again
**_Android version >= 11_**
_Existing user_
- Make sure you have a previous install
_New user install_
- Fresh install from branch
_Returning user install_
- Fresh install from branch
- Uninstall and install the app again from branch
_Manual directory removal_
- Fresh install from branch
- Remove `DuckDuckGo' directory manually from your device Downloads folder
- Open the app again
- Check new `DuckDuckGo` directory has **NOT** been created again in _Downloads_
> Move the ReinstallAtbListener inside experiments-impl module

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
- browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206101789026134/f
Remove livetabs() usages and replace it with flowtabs()
>  Android: Fix RTE caused by liveTabs()

- app/src/test/java/com/duckduckgo/app/sync/SavedSitesSyncDataProviderTest.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSync.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/provider/CredentialsSyncLocalValidationFeature.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/CredentialsInvalidItemsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/CredentialsSyncTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/FakeCredentialsSyncLocalValidationFeature.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/persister/CredentialsLastModifiedWinsStrategyTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/persister/CredentialsLocalWinsStrategyTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/persister/CredentialsRemoteWinsStrategyTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/persister/CrendentialsDedupStrategyTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/provider/CredentialsSyncDataProviderTest.kt
- saved-sites/saved-sites-impl/build.gradle
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/BookmarksSyncLocalValidationFeature.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206995306603643/f
Introduces a FF around local invalid field filtering so we can merge and wait until all platforms have implemented the required changes.
_Feature 1_
> Sync local invalid field filter FF

- app/src/test/java/com/duckduckgo/app/sync/SavedSitesSyncDataProviderTest.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsInvalidItemSyncMessagePlugin.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsInvalidItemsView.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsInvalidItemsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSync.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSyncStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/provider/CredentialsSyncLocalValidationFeature.kt
- autofill/autofill-impl/src/main/res/layout/view_credentials_invalid_items_warning.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/CredentialsFixtures.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/CredentialsInvalidItemsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/CredentialsSyncTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/FakeCredentialsSyncLocalValidationFeature.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/persister/CredentialsLastModifiedWinsStrategyTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/persister/CredentialsLocalWinsStrategyTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/persister/CredentialsRemoteWinsStrategyTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/persister/CrendentialsDedupStrategyTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/provider/CredentialsSyncDataProviderTest.kt
- saved-sites/saved-sites-impl/build.gradle
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/BookmarksSyncLocalValidationFeature.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206852460574032/f 
Some users have Logins that fail in the sync BE validation because some of their fields exceed length.
PR includes changes to :
- Filtering invalid logins
- Display a message to notify users some logins are not syncing
_Feature 1_
> Filte sync invalid logins from request and notify user

- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DownloadConfirmationFragment.kt
- downloads/downloads-impl/src/main/res/drawable/rounded_top_corners_bottom_sheet_background.xml
- downloads/downloads-impl/src/main/res/layout/download_confirmation.xml
- downloads/downloads-impl/src/main/res/values/styles.xml
Task/Issue URL: https://app.asana.com/0/715106103902962/1206905297723362/f
Expanded the download bottom sheet.
| Before (landscape) | After (landscape) |
|![Download_land_before](https://github.com/duckduckgo/Android/assets/7963079/1c6ded92-a8b9-4027-b145-27fdad959e6b)|![Download_land_after_v2](https://github.com/duckduckgo/Android/assets/7963079/ec77759c-9148-4e24-a4a0-1e0b63a645bb)|
| Before (portrait) | After (portrait) |
|![Download_portrait_before](https://github.com/duckduckgo/Android/assets/7963079/1c0acfa4-4a9a-4c43-a94a-152f6027fb3b)|![Download_portrait_after](https://github.com/duckduckgo/Android/assets/7963079/3122a3b9-aa31-41ce-8f43-b824b95830c9)|
> Github Issue: [Bug] Download confirmation dialog is cut off in vertical/tablet mode

- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ExceptionModels.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207030958834222/f
Return original stack trace instead of empty string when redaction throws
QA optional
> Return this instead of empty when stack trace redaction throws

- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/RemoteMessagingConfigMatcher.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/di/RemoteMessagingModule.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/mappers/JsonRulesMapper.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/mappers/RemoteMessagingConfigJsonMapper.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/matchers/AndroidAppAttributeMatcher.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/matchers/UserAttributeMatcher.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/models/JsonRemoteMessagingConfig.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/models/MatchingAttributes.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/models/RemoteConfig.kt
- remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/fixtures/FakeJsonMatchingAttributeMapper.kt
- remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/fixtures/FakeJsonMatchingAttributeMapperPlugins.kt
- remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/JsonRulesMapperTest.kt
- remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/RealRemoteMessagingConfigProcessorTest.kt
- remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/RemoteMessagingConfigJsonMapperTest.kt
- remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/RemoteMessagingConfigMatcherTest.kt
- sync/sync-impl/build.gradle
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/rmf/SyncJsonMatchingAttributeMapper.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/rmf/SyncMatchingAttributes.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1207001823978864/f 
Api proposal change: https://app.asana.com/0/1202552961248957/1207001823978859/f
The PR allows modules to contribute with matching attribute mappers to the remote messaging processor.
As part of the new api we are introducing a new matching attribute that makes use of new api.
_Feature 1_
> allow contributing from modules to matching attributes mappers

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1207014985604648/f
Handled target=_blank links in Custom Tabs.
Test link in DDG app
Test link in DDG Custom Tab
> Some links aren't working in custom tabs

- app/src/main/res/layout/include_new_browser_tab.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207024411305243/f
Constrains the width of the RMF dialog to 600dp.
_Point at the JSON blob linked in the task_
> Constrain RMF dialog

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/prefs/SafeSharedPreferences.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/prefs/VpnSharedPreferencesProvider.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/prefs/VpnSharedPreferencesProviderImplTest.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/store/SubscriptionsDataStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207043620647316/f
Ensure encrypted shared prefs can't crash when decryption fails.
Decryption can fail eg. as a result of phone backups that do not copy the keys across.
Code review and smoke test PPro
> Make encrypted shared preferences safe

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207042481202251/f 
----- 
> Update content scope scripts to version 5.10.0

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207061285775794/f 
----- 
> Update content scope scripts to version 5.11.0

- .maestro/security_tests/3_-_AddressBarSpoof,_appschemes.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207057471208066/f
Two issues:
- assertVisible: "Privacy, simplified." is not true anymore for all cases.
- duckduckgo.com has too frequent updates/experiments that affect our test assertions.
Therefore, I changed the exploit target to spreadprivacy.com for this specific test (as other tests do not rely on specific content being visible on duckduckgo.com). Now we can assert on a more reliable string ("Spread Privacy").
- `maestro test .maestro/security_tests/3_-_AddressBarSpoof,_appschemes.yaml`
> Update app scheme test to assert on spreadprivacy instead of duckduckgo

- app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksBottomSheetDialog.kt
- app/src/main/res/drawable/rounded_top_corners_bottom_sheet_drawable.xml
- app/src/main/res/layout/bottom_sheet_add_bookmark.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206893161772617/f
Ensures that the bookmarks bottom sheet is always expanded.
> Expand bookmarks bottom sheet

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
- autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_list_mode.xml
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206831477446960/f
Adds a warning panel to the top of password management screen if the system WebView is incompatible with autofilling. We still let the user manage their saved passwords manually.
The UI change will only show if the system WebView's feature capabilities reveal it cannot support autofilling. Easiest way to see the UI warning therefore is to manually edit `AutofillCapabilityCheckerImpl.webViewSupportsAutofill()` to return `false`.
> Add warning to password management screen for incompatible WebViews

- privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModel.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206003719166625/f
The following line is fundamentally broken, because `site.userAllowList` also takes content blocking exceptions into account, so we're comparing apples to oranges: 
`site.userAllowList != site.domain in allowlistedDomains`
As a quick workaround, `.drop(1)` was added, and this PR fixes it properly by not depending on `site.userAllowList` at all, just observing the user allowlist state.
No behavior changes are expected as a result of this PR.
> Refactor closing Privacy Dashboard on allowlist change

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207035311210656/f
Catches exceptions and shows the default error toast when launching an external app.
> Catch exceptions when launching external app

- app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
- app/src/main/java/com/duckduckgo/app/browser/applinks/AppLinksLauncher.kt
- app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
- browser-api/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207056767580178/f
This PR will open an app link if it is:
- The default or first activity
- Is a non-browser acitivity
This fixes: https://app.asana.com/0/1202552961248957/1206992174651170/f
_Install Ticketmaster US (Link in task)_
_Maps_
_Ticketmaster_
> Always use default or first non-browser app link activity

- app/src/main/java/com/duckduckgo/app/browser/customtabs/IntentDispatcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/browser/customtabs/IntentDispatcherViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207136535292676/f
Sanitized the url inside the intent for Custom Tab. 
| Before - using oauth URL unchanged | After - fixed oauth URL |
|![mastify_before](https://github.com/duckduckgo/Android/assets/7963079/65232995-7b51-4a42-b52f-cdc0c5693684)|![mastify_after](https://github.com/duckduckgo/Android/assets/7963079/586d2574-6dcc-411d-b802-aaaae3aef9bc)|
> Android: Mastify app login not working in Custom Tab

- common/common-utils/src/main/java/com/duckduckgo/common/utils/notification/NotificationUtils.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207068928136802/f
Ensure previous notifs are cancel before showing new ones. This seems to trip in some OEMs
smoke test VPN/AppTP notifs
> cancel previous notifs ID before showing new one

- app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt
- app/src/test/java/com/duckduckgo/app/brokensite/api/BrokenSiteSubmitterTest.kt
- app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesMultipleReportReferenceTest.kt
- app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesReferenceTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207135101272466/f
Send `vpnOn` parameter to broken site reports
> Add VPN state to broken sites report

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207155651458025/f 
----- 
> Update content scope scripts to version 5.13.0

- app/src/main/java/com/duckduckgo/app/browser/applinks/AppLinksHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/applinks/AppLinksLauncher.kt
- app/src/test/java/com/duckduckgo/app/browser/applinks/DuckDuckGoAppLinksHandlerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207158394406477/f
- For better compatibility, adds additional configuration to the intent we use to open app links.
- Halts navigation for links that are in the “always trigger” list.
- Fixes: https://app.asana.com/0/414730916066338/1207137747934827/f
_Sanity check_
> Update app link handling

- .github/workflows/sync-critical-path.yml
- .maestro/config.yaml
- .maestro/sync_flows/sync_data_p1.yaml
- .maestro/sync_flows/sync_data_p2.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207158873962452/f 
Splits long maestro E2E test into 2 test so we can run them sequentially
_Feature 1_
https://github.com/duckduckgo/Android/actions/runs/8815711077/job/24198207620
> split sync data e2e to avoid timeout

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/InlineBrowserAutofill.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207161413236108/f 
Ensures `WebViewCompat.addDocumentStartJavaScript` is invoked on main thread, as well as ensuring web message listeners are registered from main thread.
From testing, it didn't seem like it mattered from where `WebViewCompat.addDocumentStartJavaScript` was invoked, but we observed a crash indicating there was a potential deadlock and flagging it was called from the wrong thread.
```
java.lang.RuntimeException: Probable deadlock detected due to WebView API being called on incorrect thread while the UI thread is blocked.
```
> Ensure addDocumentStartJavaScript is called on main thread

- app/src/main/java/com/duckduckgo/app/sync/FakeDeviceSyncState.kt
- build.gradle
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/integration/NetpVpnNetworkStackProviderImpl.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/NetPInternalDefaultConfigProvider.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/WgServerInternalProvider.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/AppDeviceSyncState.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207159274091706/f 
Updates anvil to `2.5.0-beta07`
The current version requires a clean build every other build, meaning even small code changes are taking ~2 mins to test. This problem is resolved on 2.5 branch, so even though there isn't a stable release it's worth it to avoid this tedious build issue and get the code deploying again within seconds.
**Typical build times i'm seeing**
| Before | Now
|--------|--------|
| 1m 40s | 25s | 
Anvil changed how you indicate which binding has priority if there are competing ones.
| Old Way | New Way |
|--------|--------|
|`priority = ContributesBinding.Priority.NORMAL` |`rank = ContributesBinding.RANK_NORMAL` |
|`priority = ContributesBinding.Priority.HIGHEST` | `rank = …
> Update anvil to 2.5 beta to fix every other build needing a clean

- app/build.gradle
- internal-features/internal-features-api/src/main/java/com/duckduckgo/internal/features/api/InternalFeaturePlugin.kt
- remote-messaging/remote-messaging-internal/build.gradle
- remote-messaging/remote-messaging-internal/lint-baseline.xml
- remote-messaging/remote-messaging-internal/src/main/AndroidManifest.xml
- remote-messaging/remote-messaging-internal/src/main/java/com/duckduckgo/remote/messaging/internal/feature/InternalViews.kt
- remote-messaging/remote-messaging-internal/src/main/java/com/duckduckgo/remote/messaging/internal/feature/RMFInternalSettingsActivity.kt
- remote-messaging/remote-messaging-internal/src/main/java/com/duckduckgo/remote/messaging/internal/feature/RmfSettingPlugin.kt
- remote-messaging/remote-messaging-internal/src/main/java/com/duckduckgo/remote/messaging/internal/feature/RmfStagingEnvInterceptor.kt
- remote-messaging/remote-messaging-internal/src/main/java/com/duckduckgo/remote/messaging/internal/setting/RmfInternalSettings.kt
- remote-messaging/remote-messaging-internal/src/main/java/com/duckduckgo/remote/messaging/internal/setting/RmfStagingEndpointSettingView.kt
- remote-messaging/remote-messaging-internal/src/main/res/layout/activity_rmf_internal_settings.xml
- remote-messaging/remote-messaging-internal/src/main/res/layout/rmf_simple_view.xml
- remote-messaging/remote-messaging-internal/src/test/java/com/duckduckgo/remote/messaging/internal/feature/RmfStagingEnvInterceptorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206858506810306/f
Add dev setting to change to /remotemessaging staging
_Test_
> Add remote messaging internal feature

- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207136067990307/f
Adds translations for the warning message shown inside the password managements screen if WebView is too old to work with autofilling passwords.
> Translations for warning message in passwords screen when webview too old

- common/common-utils/src/main/java/com/duckduckgo/common/utils/notification/NotificationUtils.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207173112197170/f
Revert cancel notifs before notify as it's causing pulsing notif icon in the status bar in some OEMs
NA
> Revert "cancel previous notifs ID before showing new one (#4447)"

- anrs/anrs-api/src/main/java/com/duckduckgo/anrs/api/AnrRepository.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/AnrOfflinePixelSender.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/AnrSupervisor.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/CrashOfflinePixelSender.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ExceptionModels.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/RealAnrRepository.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/RealCrashLogger.kt
- anrs/anrs-store/src/main/java/com/duckduckgo/app/anrs/store/AnrEntity.kt
- anrs/anrs-store/src/main/java/com/duckduckgo/app/anrs/store/AnrsDatabase.kt
- anrs/anrs-store/src/main/java/com/duckduckgo/app/anrs/store/CrashDatabase.kt
- anrs/anrs-store/src/main/java/com/duckduckgo/app/anrs/store/ExceptionEntity.kt
- app/src/main/java/com/duckduckgo/app/browser/customtabs/RealCustomTabDetector.kt
- browser-api/src/main/java/com/duckduckgo/app/browser/customtabs/CustomTabDetector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207164955333549/f
Added the `customTab` flag to the crashes and anrs to identify the custom tab scenario.
_Test ANR pixel with customTab=false (Browser)_
```
Handler(Looper.getMainLooper()).post {
Thread.sleep(10000)
}
```
_Test ANR pixel with customTab=true (Custom Tab)_
```
Handler(Looper.getMainLooper()).post {
Thread.sleep(10000)
}
```
_Test Crash pixel with customTab=false (Browser)_
```
throw IllegalStateException("test")
```
_Test Crash pixel with customTab=true (Custom Tab)_
```
throw IllegalStateException("test")
```
_Test the DB migration_
```
Handler(Looper.getMainLooper()).post {
Thread.sleep(10000)
}
```
```
throw IllegalStateException("test")
```
> Android: distinguish browser vs custom tabs Crash/ANRs

- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/system_apps/NetPSystemAppsExclusionListActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206363377509730/f
Fix crash in manage system apps VPN internal setting.
The activity was in the wrong scope and now that we moved to monolithic activity component it was crashing
> Fix crash in VPN internal sysapps dev setting

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207192888968116/f
Removed extra check when handling `OpenMessageInNewTab` command in Custom Tab.
Test link in DDG Custom Tab
> Android: Remove webView?.hitTestResult?.extra

- network-protection/network-protection-impl/src/main/AndroidManifest.xml
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModel.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPSettingsLocalConfig.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsViewModel.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/snooze/VpnCallStateReceiver.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/snooze/VpnDisableOnCall.kt
- network-protection/network-protection-impl/src/main/res/layout/activity_netp_vpn_settings.xml
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsViewModelTest.kt
- network-protection/network-protection-internal/src/main/AndroidManifest.xml
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/NetPInternalSettingsActivity.kt
- network-protection/network-protection-internal/src/main/res/layout/activity_netp_internal_settings.xml
- network-protection/network-protection-internal/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/1203137811378537/1206289136451167/f
https://app.asana.com/0/0/1207157151658716/f
> Make pause vpn during calls available to prod

- app/src/main/java/com/duckduckgo/app/browser/customtabs/IntentDispatcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/browser/customtabs/IntentDispatcherViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207192888968125/f
Fixed link sharing from another app to DDG.
See the issue in develop
Test the fix
| Issue  | Fix |
|![issue](https://github.com/duckduckgo/Android/assets/7963079/99b86ddc-eac9-49ce-8e33-ebbcfba60200)|![fix](https://github.com/duckduckgo/Android/assets/7963079/90355fb8-e045-4ad4-a39d-eebcf233785f)|
> Android: Link sharing from another app to DDG is broken

- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207191338636817/f
try-catch calls to site permissions grant to ensure `Either grant() or deny() has been already called.` exception doesn't crash the app
QA optional
> try-catch sitePermissionRequest.grant call

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/integration/modern/listener/WebMessageListenerGetAutofillConfig.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/integration/modern/listener/WebMessageListenerGetAutofillData.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/integration/modern/listener/email/WebMessageListenerEmailGetAlias.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/integration/modern/listener/email/WebMessageListenerEmailGetCapabilities.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/integration/modern/listener/email/WebMessageListenerEmailGetUserData.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/integration/modern/listener/email/WebMessageListenerEmailRemoveCredentials.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/integration/modern/listener/email/WebMessageListenerEmailStoreCredentials.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/integration/modern/listener/email/incontext/WebMessageListenerGetIncontextSignupDismissedAt.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/integration/modern/listener/email/incontext/WebMessageListenerShowInContextEmailProtectionSignupPrompt.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/integration/modern/listener/password/WebMessageListenerStoreFormData.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207224424059893/f 
In investigating crashes, we think it's possible that an exception happening in the web message listener `onPostMessage` callbacks can result in webview crashing. In order to help pin down whether that's what is causing those crashes, will add `runCatching` guards inside the web message listeners.
QA-optional
> Wrap web message listener onPostMessage calls in a runCatching

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/AutofillJavascriptLoader.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207229909321475/f 
In `DefaultAutofillJavascriptLoader`, we lazily load JS from disk which will be injected into the WebView. At the moment, each new tab creation will result in yet another disk read for the JS.
With this PR, we construct javascript loader as a singleton so that the JS is more quickly available to each subsequent tab that is created.
QA-optional
> Better caching of js to inject for autofill

- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/FeatureTogglesTest.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207205379865938/f
FF that had the default value set to true and use it would no longer evaluate the rollout threshold.
See integration tests added
> Fix: FF with defaultValue set to true should evaluate threshold

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/0/1207230436936681/f 
Avoids the cost of initialising the `WebView` twice on a new tab screen.
- We initialise a `WebView` when creating the new tab
- We destroy it and rebuild a new one when loading the first site
For testing, essentially want to ensure that the behavior is exactly the same as production right now (except under the hood, `WebView` not created twice). 
In particular, want to ensure the previous fix is still good meaning the following steps are true:
e.g.,:
> Avoid double WebView initialisation on new tab screen

- build.gradle
- buildSrc/build.gradle
- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1207208354433631/f
Since we moved to Anvil 2.5 (https://github.com/duckduckgo/Android/pull/4462), this PR updates these matching dependencies:
`kotlin_version = ‘1.9.20'` → `‘1.9.22'`
`version.google.dagger=2.48.1` → `2.51.1`
- Nightly run: https://github.com/duckduckgo/Android/actions/runs/8908351852 ✅
- Tested with IntelliJ 2024.1.1 ✅
> Update dependencies to match Anvil 2.5

- .maestro/config.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207274917087185/f 
Re-enables the Maestro [retry behavior](https://cloud.mobile.dev/reference/retries). These were disabled in https://github.com/duckduckgo/Android/pull/4438 but we've seen global test flakiness since.
QA-optional
> Re-enable Maestro's automatic test retries

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/InlineBrowserAutofill.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207278694825695/f 
Adds a `yield` call after adding web message listeners to give the main thread some breathing space if it's struggling with WebView init.
QA-optional
> Add a yield after adding web message listeners

- app/src/main/java/com/duckduckgo/app/usage/app/AppDaysUsedDatabaseRepository.kt
- browser-api/src/main/java/com/duckduckgo/app/usage/app/AppDaysUsedRepository.kt
Task/Issue URL: https://app.asana.com/0/0/1207179707350731/f 
Moves a class from app module to `browser-api` so it can be used in autofill survey.
> Move AppDaysUsedRepository to browser-api so it can be accessed from autofill

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/survey/AutofillSurveyStore.kt
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
- autofill/autofill-internal/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/0/1207179707350730/f 
Adds a dev setting to reset previous surveys so you can test taking the survey again.
QA-optional since it's just dev settings. but steps to test are below:
> Add dev settings to clear previously seen surveys so they can be tested again

- anrs/anrs-impl/CMakeLists.txt
- anrs/anrs-impl/build.gradle
- anrs/anrs-impl/src/main/cpp/android.h
- anrs/anrs-impl/src/main/cpp/jni.cpp
- anrs/anrs-impl/src/main/cpp/ndk-crash.cpp
- anrs/anrs-impl/src/main/cpp/ndk-crash.h
- anrs/anrs-impl/src/main/cpp/pixel.cpp
- anrs/anrs-impl/src/main/cpp/pixel.h
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ndk/NativeCrashFeature.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ndk/NativeCrashInit.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207205378744694/f
Add native crash handler and basic reporting
_Test native crash handing_
> Native crash handling

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/SyncGzipInterceptor.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/SyngGzipInterceptor.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixelParamRemovalPlugin.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207259077953491/f 
Debug pixel in case of failure when trying to compress patch
_Feature 1_
> adds error pixel when compress fails

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207310385312049/f 
----- 
> Update content scope scripts to version 5.15.0

- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/play/java/com/duckduckgo/referral/PlayStoreAppReferrerStateListener.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207300933614494
Add two temporary pixels that allow us to measure installs in legacy Android devices.
> Add temporary pixels for DMA choice screens

- .github/workflows/custom-tabs-nightly.yml
- .maestro/custom_tabs/custom_tabs_navigation.yaml
- .maestro/custom_tabs/custom_tabs_navigation_new_tab.yaml
- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/internal/AndroidManifest.xml
- app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsActivity.kt
- app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsViewModel.kt
- app/src/internal/java/com/duckduckgo/app/dev/settings/customtabs/CustomTabsInternalSettingsActivity.kt
- app/src/internal/res/layout/activity_custom_tabs_internal_settings.xml
- app/src/internal/res/layout/activity_dev_settings.xml
- app/src/internal/res/values/donottranslate.xml
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/customtabs/CustomTabActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/customtabs/CustomTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207186871481910/f
Adds navigation in custom tabs via gestures or the UI.
(You can check that it has opened in a custom tab by clicking the 3 dots and in the menu it will say "Running in DuckDuckGo")
Forward nav is now enabled:
> Add custom tab navigation

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt
- app/src/main/java/com/duckduckgo/app/browser/webview/DummyWebMessageListenerFeature.kt
- app/src/main/java/com/duckduckgo/app/browser/webview/WebMessageListenerFeature.kt
Task/Issue URL: https://app.asana.com/0/1200204095367872/1207300292572452/f
Adds a no-op WebMessageListener in order to debug https://issuetracker.google.com/issues/338340758
> Add no-op WebMessageListener

- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/matchers/InteractedWithMessageMatcher.kt
- remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/matchers/InteractedWithMessageMatcherTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207357586624436/f 
Allows including/filtering users that interacted with a previous RMF
_Feature 1_
> InteractedWithMessage attribute matcher

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/engagement/EngagementPasswordAddedListener.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/engagement/EngagementPasswordAddedListenerTest.kt
Task/Issue URL: https://app.asana.com/0/608920331025315/1207360368013215/f 
Prevent onboarding metric getting over-triggered if multiple credentials added quickly in a short amount of time
QA-optional
> Prevent onboarded autofill metric overfiring if called multiple times quickly

- fastlane/Fastfile
- fastlane/README.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1207360448878908/f 
We experience lengthy Play Store reviews and pay the price twice for each release:
- one review is triggered when we upload our APK to the `staging` track
- a second review is triggered when we promote from `staging` to begin the `production` rollout
Each of the reviews can amount to many hours each. This PR changes it so that we skip `staging` and go straight to production at 0.01% rollout so that the review clock starts immediately and we only have to wait for a single app review instead of needlessly waiting on two for the same release.
> Update fastlane to upload APK straight to production to reduce wasted time on double reviews

- node_modules/@duckduckgo/content-scope-scripts/README.md
- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207367485604645/f 
----- 
> Update content scope scripts to version 5.17.0

- anrs/anrs-impl/build.gradle
- anrs/anrs-impl/src/main/cpp/jni.cpp
- anrs/anrs-impl/src/main/cpp/pixel.cpp
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/AnrOfflinePixelSender.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ndk/NativeCrashFeature.kt
- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ndk/NativeCrashInit.kt
- anrs/anrs-impl/src/test/java/com/duckduckgo/app/anr/ndk/NativeCrashFeatureMultiProcessStoreTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207294405155930
Add native crash handling for VPN process now that we also have it for the main process
_Test native crash handing_
_(pixels should have `pn=vpn` and the right version, may be difficult to find them as now we send for `pn=main` in production. Logcats above should be enough)_
_Test disabling crash handling_
```json
"androidNativeCrash": {
"hash": "38",
"features": {
"nativeCrashHandlingSecondaryProcess": {
"state": "enabled"
}
}
}
```
> Register in VPN process as well

- app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
- app/src/test/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt
Task/Issue URL: https://app.asana.com/0/0/1207300113417901/f 
_Feature 1_
_Feature 1_
> Allow bookmarks to be shown in top hits

- anvil/anvil-annotations/src/main/java/com/duckduckgo/anvil/annotations/ContributesActivePlugin.kt
- anvil/anvil-annotations/src/main/java/com/duckduckgo/anvil/annotations/ContributesActivePluginPoint.kt
- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesActivePluginPointCodeGenerator.kt
- common/common-utils/src/main/java/com/duckduckgo/common/utils/plugins/ActivePluginPoint.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/TestActivePlugins.kt
- lint-rules/src/main/java/com/duckduckgo/lint/WrongPluginPointCollectorDetector.kt
- lint-rules/src/main/java/com/duckduckgo/lint/registry/DuckDuckGoIssueRegistry.kt
- lint-rules/src/test/java/com/duckduckgo/lint/WrongPluginPointCollectorDetectorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207400224799044/f
Ensure that normal plugin points can't collect active plugins
See lint test.
You can also try to collect an ActivePlugin (aka, plugin interface that extends from ActivePlugin) in a normal `PluginPoint<T>` and see lint failing
> Enforce that Active plugins can't be collected by normal plugin point

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207418287456970/f 
----- 
> Update content scope scripts to version 5.18.0

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementStringBuilder.kt
- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementStringBuilderImplTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206638124888258/f 
Copy changes around deleting passwords (now showing a different message when sync is enabled vs disabled). 
Translations will come in https://github.com/duckduckgo/Android/pull/4446
> Update copy when deleting passwords to consider whether sync enabled or not

- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ndk/NativeCrashInit.kt
- library-loader/library-loader-api/build.gradle
- library-loader/library-loader-api/src/main/java/com/duckduckgo/library/loader/LibraryLoader.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207420696563461/f
Load native crash library off class instance construction
_Test_
_Test main process crash_
```diff
Subject: [PATCH] fix
---
Index: anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ndk/NativeCrashInit.kt
<+>UTF-8
diff --git a/anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ndk/NativeCrashInit.kt b/anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ndk/NativeCrashInit.kt
--- a/anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ndk/NativeCrashInit.kt	(revision 3eb803331a644de40af37e35fc0b355770961350)
+++ …
```
> Load library outside instance creation

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesActivePluginPointCodeGenerator.kt
- lint-rules/src/main/java/com/duckduckgo/lint/WrongPluginPointCollectorDetector.kt
- lint-rules/src/test/java/com/duckduckgo/lint/WrongPluginPointCollectorDetectorTest.kt
- lint-rules/src/test/java/com/duckduckgo/lint/utils/PluginUtils.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207420696744032/f
Detect active plugin point naming clash and break build.
The PR incidentally fixes `WrongPluginPointCollectorDetector` that was obsolete after #4585
_Test_
```diff
Index: feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/Test.kt
<+>UTF-8
diff --git a/feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/Test.kt b/feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/Test.kt
new file mode 100644
--- /dev/null	(date 1716970458191)
+++ …
```
> Check possible active plugin or plugin point naming clashes

- app/src/main/res/layout/item_autocomplete_search_suggestion.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207407556106269/f
Fixes the issue reported in https://github.com/duckduckgo/Android/issues/4564
(Tested on a Pixel 2, Android 11)
> Adapt autocomplete item to system font size

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207490363402682/f 
----- 
> Update content scope scripts to version 5.19.0

- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/internal/res/values/donottranslate.xml
- app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/res/layout/include_onboarding_view_dax_dialog.xml
- app/src/main/res/layout/pre_onboarding_comparison_chart.xml
- statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Task/Issue URL: https://app.asana.com/0/1201807753394693/1207353075657638/f
Add new onboarding _End_ dialog when the onboarding flow finishes without the fire button animation
| Light  | Dark |
> Onboarding end Dax dialog

- privacy-config/privacy-config-internal/src/main/java/com/duckduckgo/privacy/config/internal/PrivacyConfigInternalViewModel.kt
Task/Issue URL: https://app.asana.com/0/1204912272578138/1207434405087911/f
Ditto
> Fix: force load config reports success with invalid URLs

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/engagement/store/AutofillEngagementRepository.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/engagement/store/DefaultAutofillEngagementRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/1149059203486286/1207512213117499/f
and: https://app.asana.com/0/0/1207512940049066/f
Updates existing enabled user metric.
New metric for search dau autofill.
_Feature 1_
_Feature 2_
_Feature 3_
_Feature 3_
> Update autofill engagement metrics

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/StringExtensions.kt
- common/common-utils/src/test/java/com/duckduckgo/common/utils/extensions/StringExtensionsTest.kt
Task/Issue URL: https://app.asana.com/0/1200204095367872/1207470485890046/f
- Adds a check for `WebView` v126, so that we can test that `WebMessageListener` is working as expected.
- See: https://issues.chromium.org/issues/338340758#comment41
> Add WebView version check to no-op WebMessageListener

- app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
Task/Issue URL: https://app.asana.com/0/1198194956794324/1207518429728858/f
Enable StrictMode in debug builds, configure it for:
* detect disk reads/writes
* detect network
* log a message to the system log when a violation is detected
* log to dropbox so that it can be retrieve later on using `adb`
_Test_
> Enable strict mode in debug builds

- app/src/internal/java/com/duckduckgo/app/dev/settings/customtabs/CustomTabsInternalSettingsActivity.kt
- app/src/internal/res/layout/activity_custom_tabs_internal_settings.xml
- app/src/internal/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207482546194311/f
Adds a default browser shortcut to easily change the default browser when testing Custom Tabs.
> Add default browser shortcut to Custom Tabs dev setting

- app/src/main/res/layout/content_settings_other.xml
Task/Issue URL: https://app.asana.com/0/1201048563534612/1207326238853107/f
Remove the BETA labels for Desktop browsers
_Settings_
---
- https://app.asana.com/0/0/1207326238853107
> Settings: Remove BETA label for Desktop settings

- app/src/main/java/com/duckduckgo/app/appearance/AppearanceActivity.kt
- app/src/main/java/com/duckduckgo/app/appearance/AppearanceViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/java/com/duckduckgo/app/settings/db/SettingsDataStore.kt
- app/src/main/res/layout/activity_appearance.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/duckduckgo/app/appearance/AppearanceViewModelTest.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/store/AppTheme.kt
Task/Issue URL: https://app.asana.com/0/715106103902962/1206630026838095/f
This PR adds support for [algorithmically forced dark mode.](https://developer.android.com/reference/androidx/webkit/WebSettingsCompat#setAlgorithmicDarkeningAllowed(android.webkit.WebSettings,boolean))
_Dark mode_
| ------ | ------
|![Screenshot_20240605_125706](https://github.com/duckduckgo/Android/assets/531613/e4b1c23d-b64d-4ff4-baf3-0c0b844c1524)|![Screenshot_20240605_125744](https://github.com/duckduckgo/Android/assets/531613/32ecb093-80ec-4435-8ace-ee407f1eab1c)|
> Force Algorithmically dark mode

- app/src/main/java/com/duckduckgo/app/global/view/RecyclerViewExtension.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207526694527888/f
- Fix for an `IllegalArgumentException` when re-arranging the favorites grid (By checking `isComputingLayout` before updating the `itemAnimator` in a `post`)
- Also updates `enableAnimation` with the same logic.
> Fix RecyclerView.disableAnimation() crash

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/1125189844152671/1207572075253654/f 
Fixes a crash when Webview doesn't support algorithmic darkening.
> Fix when forcing dark mode

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/extendedonboarding/ExtendedOnboardingFeatureToggles.kt
Task/Issue URL: https://app.asana.com/0/1201807753394693/1207385522349489/f
Retention Experiment where the experimental variant won't see onboarding Dax dialogs in the browser.
- _mp_: Control variant
- _mo_: Experimental variant
**_Pre steps_**
**_Control variant_**
```
{
"desc": "Control group for not showing onboarding CTAs experiment",
"variantKey": "mp",
"weight": 1
},
{
"desc": "Dax dialogs removal during onboarding experimental group",
"variantKey": "mo",
"weight": 0
}
```
**_Experimental variant_**
```
{
"desc": "Control group for not showing onboarding CTAs experiment",
"variantKey": "mp",
"weight": 0
},
{
"desc": "Dax dialogs removal during onboarding experimental group",
"variantKey": "mo",
"weight": 1
}
```
> Experiment: Removing Browser Onboarding CTAs

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207578347439866/f 
----- 
> Update content scope scripts to version 5.21.0

- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/TypeAnimationTextView.kt
Task/Issue URL: https://app.asana.com/0/1201807753394693/1207291831514025/f
Cancel current typing animation if a new one starts
> Fix for IndexOutOfBoundsException

- subscriptions/subscriptions-impl/src/main/res/layout/activity_subscription_settings.xml
Task/Issue URL: https://app.asana.com/0/1205648422731273/1207605998461325/f
This PR increases bottom padding on subscriptions settings screen to match top-level settings screen.
(Optional) Navigate to subscription settings screen and verify the bottom padding matches the top-level settings screen.
|![Screenshot_20240618_235937](https://github.com/duckduckgo/Android/assets/4212474/7550a285-ccbc-419a-ab47-f173ab945b44)|![Screenshot_20240619_000123](https://github.com/duckduckgo/Android/assets/4212474/eb9f93fb-345d-4173-9f37-eefe62fb83ff)|
> Fix subscription settings screen bottom padding

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207610505138605/f
Prevent early taps on DaxBubble to avoid firing events too quickly.
_Feature 1_
> Onboarding: Prevent taps in suggestions until text animation has finished

- app/src/main/res/layout/include_new_browser_tab.xml
- common/common-ui/src/main/res/values/design-system-dimensions.xml
Task/Issue URL: https://app.asana.com/0/0/1207453843423098/f
Make new tab page Dax logo smaller
> Resize Dax logo in new tab page

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/di/SyncModule.kt
- sync/sync-lib/src/main/java/com/duckduckgo/sync/crypto/SyncNativeLib.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207535395708800/f
Defer loading the sync native library to when it's actually used. This avoids:
- loading the library on process launch when not necessary
- loading the library at all for the `:vpn` process
Filter logcat by `Loading native SYNC library`
_Test_
Note: if you repeat the test in `develop` the `Loading native SYNC library` shows every time both the main and `:vpn` processes are created, irregardless of whether sync is enabled or not
> Defer the loading of Sync native lib to when necesasry

- app/src/main/java/com/duckduckgo/app/browser/customtabs/CustomTabActivity.kt
Task/Issue URL: https://app.asana.com/0/1200581511062568/1207587829937580/f
Set the custom tab mode from `onCreate` in `CustomTabActivity`.
Check testing done on https://github.com/duckduckgo/Android/pull/4469
> Fix CustomTab crash/anr attribution

- node_modules/@duckduckgo/autofill/README.md
- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.css
- node_modules/@duckduckgo/autofill/dist/autofill.js
- node_modules/@duckduckgo/autofill/dist/shared-credentials.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1207623126907992/1207623126907992
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/12.0.0
Updates Autofill to version [12.0.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/12.0.0).
* Major version bump to 12.0.0 caused by #396, which impacts only Android.
* This release also translates the autofill experience to the following language codes:
* bg
* cs
* da
* de
* el
* en
* es
* et
* fi
* fr
* hr
* hu
* it
* lt
* lv
* nb
* nl
* pl
* pt
* ro
* ru
* sk
* sl
* sv
* tr
* Ema/more minor fixes by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/556
* l10n: extract remaining strings to prepare for localization by @sjbarag in https://github.com/duckduckgo/duckduckgo-autofill/pull/558
* …
> Update autofill to 12.0.0

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1207634174804391/1207634174804391
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/12.0.1
Updates Autofill to version [12.0.1](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/12.0.1).
* generation: ensure password gen feature flag is respected by @sjbarag in https://github.com/duckduckgo/duckduckgo-autofill/pull/583
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/12.0.0...12.0.1
> Update autofill to 12.0.1

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillScreens.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementActivity.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsInvalidItemsView.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSyncPausedView.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
Task/Issue URL: https://app.asana.com/0/1203822806345703/1207602891714016/f 
Adds secondary KPIs for autofill.
Add the following logcat filter: 
```
"Opened autofill management screen" | "Pixel sent: m_autofill_management_opened" | "Pixel sent: m_autofill_management_delete_login" | "Pixel sent: m_autofill_management_delete_all_logins" | "Pixel sent: m_autofill_management_update_login" | "Pixel sent: m_autofill_management_save_login  | "Pixel sent: m_autofill_management_copy_username  | "Pixel sent: m_autofill_management_copy_password" 
```
> Add autofill secondary KPIs

- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
Task/Issue URL: https://app.asana.com/0/1200204095367872/1207640706766042/f
- Guards against committing the fragment if `onSaveInstanceState` has already been called.
> Fix IllegalStateException on addOrReplaceNewTab

- common/common-ui/src/main/java/com/duckduckgo/common/ui/menu/PopupMenu.kt
- common/common-ui/src/main/res/drawable/ripple_bottom_rounded.xml
- common/common-ui/src/main/res/drawable/ripple_rectangle_rounded.xml
- common/common-ui/src/main/res/drawable/ripple_top_rounded.xml
Task/Issue URL: https://app.asana.com/0/1200204095367872/1201672589972569/f
- Ensures that the first item's ripple has rounded corners on the top left and top right.
- Ensures that the last item's ripple has rounded corners on the bottom left and bottom right.
- If there is only one item in the `PopupMenu`, all of the ripple corners are rounded.
> Round PopupMenu ripple corners

- app/build.gradle
- subscriptions/subscriptions-dummy-impl/build.gradle
- subscriptions/subscriptions-dummy-impl/lint-baseline.xml
- subscriptions/subscriptions-dummy-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsDummy.kt
Task/Issue URL: https://app.asana.com/0/1205648422731273/1207600736669442/f
This PR adds dummy implementation of subscriptions-api and makes the fdroid flavor of the app depend on it instead of the actual implementation. The goal is to remove dependency on Google Play Billing Library from the F-Droid builds of the app.
See task.
> Use dummy subscriptions for fdroid flavor

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207652843451543/f 
----- 
> Update content scope scripts to version 5.22.0

- app/build.gradle
- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/NewStateKillSwitch.kt
- app/src/main/java/com/duckduckgo/app/browser/WebNavigationState.kt
- app/src/test/java/com/duckduckgo/app/browser/WebNavigationStateComparisonTest.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1207666379072710/f
Change URL state when input URL is different than URL loaded
---
- https://app.asana.com/0/0/1207666379072710
> Fix url state when input url is different than loaded url

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProBillingPeriodMatchingAttribute.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProDaysUntilExpiryRenewalMatchingAttribute.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriptionStatusMatchingAttribute.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/survey/PproSurveyParameters.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProBillingPeriodMatchingAttributeTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProDaysUntilExpiryRenewalMatchingAttributeTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriptionStatusMatchingAttributeTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/survey/PproSurveyParameterPluginsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207640571466121/f
https://app.asana.com/0/488551667048375/1207655226002947/f
> Add all ppro matching attributes

- app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabGridItemDecorator.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1202148076467684/f
This PR selects the last tab in the list after the currently-selected tab is deleted. This fixes the behaviour when no tab was selected and when the user went back to the browser, the first tab was shown.
1. Create at least 3 tabs (with the last tab being selected)
2. Delete the last (selected) tab
3. Notice the tab is removed and the last of the remaining tab is selected
4. Tap on `Undo`
5. Notice the previous tab is shown and selected again
6. Delete the selected tab again
7. Tap on the back button
8. Notice the correct tab is shown
[Screen_recording_20240626_151442.webm](https://github.com/duckduckgo/Android/assets/1522856/2ae2fe33-275b-4eb8-a33c-62b647715d09)
> Select the last tab and update selection after deleting the current tab

- autofill/autofill-impl/src/main/res/layout/overflow_menu_list_item.xml
Task/Issue URL: https://app.asana.com/0/608920331025315/1207675108702975/f 
Left-aligns the text for overflow menus of the individual passwords in the password management screen. This makes it consistent with such menus used elsewhere.
QA-optional
> Left-align text in individual overflow menus in password manager

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207662819078366/f 
----- 
> Update content scope scripts to version 5.23.0

- common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/ContextExtensions.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/custom_dns/VpnCustomDnsActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/custom_dns/VpnCustomDnsViewModel.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1207692081807518/f
Remove the warning on custom DNS screen when private DNS is set to automatic
_Test automatic mode_
> Allow custom DNS on opportunistic DoT

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207690974857672/f 
----- 
> Update content scope scripts to version 5.25.0

- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/MessageCta.kt
Task/Issue URL: https://app.asana.com/0/1201807753394693/1207619945513388/f
Support HTML text in RMF title
> Add HTML support in RMF title

- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillFeature.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillGlobalCapabilityChecker.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/AutofillGlobalCapabilityCheckerImplGlobalFeatureTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/feature/toggles/api/toggle/AutofillTestFeature.kt
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
Task/Issue URL: https://app.asana.com/0/1203822806345703/1207471701495238/f 
Adds a new check for autofill subfeature flag before injecting autofill Javascript.
Adding this check gives us the ability to selectively disable just the JS injection while keeping other parts of autofill active, namely, access to the stored passwords in the password management screen.
The check is added as a kill-switch, meaning it defaults to `true` unless remote config says otherwise.
**Check upgrade path**
**[optional] Test kill switch**
> Add kill-switch for remote subfeature flag whether to inject Autofill javascript

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/1200204095367872/1207702094588632/f
Catches a `NullPointerException` sometimes thrown by `getHitTestResult`.
> Catch HitTestResult NullPointerException

- versions.properties
Task/Issue URL: https://app.asana.com/0/1207701481229686/1207706722437057/f 
Updates `DataStore` dependency to `1.1.1`. 
No breaking changes reported in the changelog.
> Update DataStore, from 1.0.0 to 1.1.1

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/ImportPasswordsActivity.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/ImportPasswordsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/desktopapp/ImportPasswordsGetDesktopAppViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/ImportPasswordsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/desktopapp/ImportPasswordsGetDesktopAppViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1207657337829081/f 
General pixels for importing via desktop sync.
Suggested logcat filter: `"Pixel sent: "`
**Import Passwords (blue button)**
**No action taken**
**Import Passwords (from overflow menu)**
**Get Desktop Browser**
**Sync With Desktop**
> Pixels for importing passwords via desktop sync

- app/src/main/java/com/duckduckgo/app/sync/FakeDeviceSyncState.kt
- autofill/autofill-impl/build.gradle
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/ImportPasswordsActivity.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/ImportPasswordsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/desktopapp/ImportPasswordsUserJourneyLifecycleObserver.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/desktopapp/ImportPasswordsViaDesktopSyncDataStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/desktopapp/ImportPasswordsViaDesktopSyncDataStoreModule.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/desktopapp/UserJourneyEndRecorder.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/ImportPasswordsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/desktopapp/ImportPasswordsUserJourneyLifecycleObserverTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/desktopapp/UserJourneyEndRecorderImplTest.kt
- sync/sync-api/src/main/java/com/duckduckgo/sync/api/DeviceSyncState.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/AppDeviceSyncState.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncDeviceId.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/AppSyncDeviceIdsTest.kt
Task/Issue URL: https://app.asana.com/0/1203822806345703/1207149249611733/f 
Suggest logcat filter: `message~:"user-journey" message~:"Pixel sent: .*autofill"`
**Testing the "immediate success" flow**
**Testing the timed out failure flow**
**Testing the delayed success flow**
**Restarting the clock**
> Add user-journey completion check for importing passwords via desktop sync

- remote-messaging/remote-messaging-impl/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
- subscriptions/subscriptions-impl/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- versions.properties
Task/Issue URL: https://app.asana.com/0/1207701481229686/1207716076931920/f 
Updates Mockito to latest version. This lets us run the tests on all Android APIs instead of being limited to ~API 30 like we are now.
> Update mockito to 5.12.0 and fix failing tests

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/custom_dns/VpnCustomDnsSettingView.kt
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207614156872048/f
> Custom DNS fixes in VPN Screen

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriptionStatusMatchingAttribute.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriptionStatusMatchingAttributeTest.kt
Task/Issue URL: https://app.asana.com/0/1201462763415876/1207718752492279/f
Previously, we map n`ot-auto-renewable` to `ACTIVE` and `EXPIRING` states. For consistency with other platforms, considering we accept an `array` in `pproSubscriptionStatus` already, we don't need to map `not-auto-renewable` to 2 states anymore.
To fix this, we are only mapping `not-auto-renewable` to `ACTIVE` state.
Qa-optional
> Remove not-auto-renewable from ACTIVE mapping

- downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DownloadConfirmationFragment.kt
- downloads/downloads-impl/src/main/res/layout/download_confirmation.xml
- downloads/downloads-impl/src/main/res/values-bg/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-cs/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-da/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-de/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-el/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-es/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-et/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-fi/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-fr/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-hr/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-hu/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-it/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-lt/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-lv/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-nb/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-nl/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-pl/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-pt/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-ro/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-ru/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-sk/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-sl/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-sv/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values-tr/strings-downloads.xml
- downloads/downloads-impl/src/main/res/values/strings-downloads.xml
Task/Issue URL: https://app.asana.com/0/1142021229838617/1207476479082856/f
This PR modifies the download confirmation dialog to show host extracted from download url.
> Show host in download confirmation dialog

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/print/PrintDocumentAdapterFactory.kt
- app/src/main/java/com/duckduckgo/app/browser/print/SinglePrintSafeguardFeature.kt
- app/src/main/java/com/duckduckgo/app/browser/viewstate/BrowserViewState.kt
Task/Issue URL: https://app.asana.com/0/1200204095367872/1207700638247735/f
Fixes an IllegalStateException that is thrown when a printing job is already pending.
_Printing pages_
_Cancelling a print_
_Feature toggle (Disabled)_
> Fix printing IllegalStateException

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/error/SyncApiErrorRecorder.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/error/SyncApiErrorRecorderTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/pixels/SyncPixelsTest.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1207559244852257/f 
Fires a pixel on first event of api error per day.
Suggestion: Use `message~:"Pixel sent"` filter
_Feature 1_
Just one scenario for manual QA, other scenario should behave similar but more difficult to test. Tests cover all scenarios.
(if you lose the logs, you can check directly in db if the pixel was sent. Go to database inspector -> pixels.db -> daily_pixels_fired)
> Add sync api errors daily pixels

- app/build.gradle
Task/Issue URL: https://app.asana.com/0/1202552961248957/1207182540886158/f 
Enables a custom signing certificate to be specified for `debug` builds. 
By default, behavior is the same as it's always been. To override the default and specify a custom debug signing cert:
- create a signing certificate / keystore and store it somewhere
- in `local.properties` in the project, add the following values:
```
useCustomDebugCert=true
customDebugCertPath=<path_to_keystore>
customDebugCertAlias=<alias>
customDebugCertStorePassword=<store_password>
customDebugCertKeyPassword=<key_password>
```
> Add support for specifying a custom debug signing certificate

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207763697290294/f 
----- 
> Update content scope scripts to version 6.0.0

- anrs/anrs-internal/src/test/java/com/duckduckgo/app/anr/internal/store/DatabaseCleanupObserverTest.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1207773361177582/f
Tries to fix flaky test by using different timestamp for old entity objects
_Feature 1_
> Fixing internal flaky test round 2

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageView.kt
- app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/viewstate/CtaViewState.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/res/layout/view_new_tab_legacy.xml
- app/src/test/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModelTest.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/network/RemoteMessagingService.kt
Task/Issue URL: https://app.asana.com/0/1157893581871903/1207769731595075/f
This PR ensures that RMF and New Tab are only visible if onboarding has finished
_RMF Pixels_
_New Tab_
> New Tab: Fix RMF Pixels

- fastlane/Fastfile
- fastlane/README.md
Task/Issue URL: https://app.asana.com/0/608920331025315/1207796666154886/f 
Adds a new fastlane script which can be used to update release notes on the Play Store for a particular app version.
Typically, this will be executed from CI. 
Example usage: `fastlane update_release_notes_playstore release_number:5.208.0 release_notes:"Bug fixes and other improvements"`
QA-optional
> Update fastlane to allow for updating release notes of an existing release in Play Store

- app/src/main/java/com/duckduckgo/app/SelectedTextSearchActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207778360497709/f
Closes the current tab when searching selected text and pressing back.
> Fix selected text search back navigation

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207819010442214/f 
----- 
> Update content scope scripts to version 6.2.0

- fastlane/Fastfile
- fastlane/README.md
Task/Issue URL: https://app.asana.com/0/608920331025315/1207811052233538/f 
Adds fastlane lane for updating GitHub release notes
Lane: `update_release_notes_github`
Params: 
- `release_number`
- `release_notes`
Both params above are optional; if you don't provide them via the command line you'll be prompted to enter them interactively.
Example of calling the command with the params on the command line:
- `fastlane update_release_notes_github release_number:5.205.0 release_notes:"Bug fixes and other improvements"`
QA-optional
> Add fastlane lane for updating GitHub release notes (using `gh`)

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/res/layout/fragment_browser_tab.xml
Task/Issue URL: https://app.asana.com/0/1157893581871903/1207816154536989/f
Delay the addition of the FocusedView until it’s necessary
_Enable FocusedView_
> Delay adding FocusedView until it's necessary

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207828754892904/f 
----- 
> Update content scope scripts to version 6.3.0

- app/src/main/java/com/duckduckgo/app/browser/print/PrintDocumentAdapterFactory.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207831722240169/f
Handles the case where a print job has not been cleaned up before starting a new one.
| API 27  | API 34 | Video |
| ------ | ----- | ----- |
> Handle print exception onWrite

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207845944313951/f
Fix for not showing favorites displayed underneath the 'visit site' Dax dialog
On each step, wait for searches and sites to fully load in the browser
> Fix favorites displayed underneath Dax dialog

- app/src/main/java/com/duckduckgo/app/browser/newtab/FocusedViewProvider.kt
- app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabPageProvider.kt
- new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/NewTabPage.kt
Task/Issue URL: https://app.asana.com/0/608920331025315/1207866714282844/f 
Enforces legacy UX for new tab and focussed views. 
We will probably have to revisit this in future to give the _new_ UX for internal users because this PR will enforce legacy experience regardless.
> Enforce legacy UX for new tab and focussed view

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/userstate/UserStateReporterTest.kt
Task/Issue URL: https://app.asana.com/0/1207418217763355/1207689147487669/f
This PR adds the following pixels:
- `m_tab_manager_rearrange_tabs`: When a user long-presses and drags a tab to rearrange the order
- `m_tab_manager_rearrange_tabs_daily`: When a user long-presses and drags a tab to rearrange the order (fired only once per day per user who takes this action)
- `m_tab_manager_clicked_daily`: When a user opens the tab manager screen (fired only once per day per user who takes this action)
_Opening the tab manager_
_Rearranging the tabs_
> Rearranging tabs: Pixels

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementRecyclerAdapter.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/suggestion/SuggestionListBuilder.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
- autofill/autofill-impl/src/main/res/drawable/autofill_rounded_report_breakage_icon_background.xml
- autofill/autofill-impl/src/main/res/drawable/ic_alert_24.xml
- autofill/autofill-impl/src/main/res/layout/item_row_autofill_report_breakage_management_screen.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/suggestion/SuggestionListBuilderTest.kt
Task/Issue URL: https://app.asana.com/0/608920331025315/1207767049586685/f 
Adds the UI for showing the option to send an autofill breakage report.
Note, this branch doesn't actually submit the report or suppress the prompt from showing again.
ℹ️  Local hack to enable feature: In `AutofillSiteBreakageReportingFeature`, set default value to `true`
---
**Verifying it doesn't show unexpectedly**
**Verifying it does show when it should**
**Verifying it behaves when tapped on**
**Verifying feature flag works**
> UI for autofill breakage reports

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillScreens.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/AutofillBreakageReportSender.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementActivity.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/reporting/AutofillBreakageReportSenderImplTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207769724660967/f 
Handles the actual submission of the autofill breakage report.
ℹ️ Local hack to enable feature: In `AutofillSiteBreakageReportingFeature`, set default value to `true`
ℹ️ Logcat filter: `autofill_logins_report_failure` 
---
> Submit autofill feedback report

- app/src/test/java/com/duckduckgo/app/browser/autofill/RealAutofillFireproofDialogSuppressorTest.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillFireproofDialogSuppressor.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deviceauth/AutofillAuthorizationGracePeriod.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/AutofillBreakageReportCanShowRules.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/AutofillSiteBreakageReportingDataStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/time/TimeProvider.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deviceauth/AutofillTimeBasedAuthorizationGracePeriodTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/reporting/AutofillBreakageReportCanShowRulesImplTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/reporting/AutofillSiteBreakageReportingDataStoreImplTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/reporting/AutofillSiteBreakageReportingFeatureRepository.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207767049586678/f 
After submitting an autofill breakage report for a site, the user won't be prompted to send another report for the next _n_ days, where _n_ is a value from remote config (defaulting to `42`).
ℹ️  Local hack to enable feature: In `AutofillSiteBreakageReportingFeature`, set default value to `true`
---
**Verifying you don't see the prompt again for the exact same site**
**Verifying another page on same website isn't shown prompt**
**Verifying on a totally different website you do see the prompt again**
> Suppress report autofill breakage prompt after previous submission

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207772527673440/f 
General pixels around reporting autofill breakage dialog
ℹ️ Local hack to enable feature: In `AutofillSiteBreakageReportingFeature`, set default value to `true`
ℹ️ Logcat filter: `message~:"Pixel sent:.*autofill_logins_report"`
---
**Verifying cancellations**
**Verifying acceptance**
> Pixels for reporting autofill breakage UI

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/AutofillSiteBreakageReportingDataStore.kt
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
- autofill/autofill-internal/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/608920331025315/1207855335711810/f 
Adds a new developer setting for clearing previous reports. This makes it easier to test since you won't have to wait for the timeout period to expire before you can submit again for the same site.
QA-optional. If you want to test it out manually:
> Add dev settings for clearing breakage reports for easier testing

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207893198734467/f 
----- 
> Update content scope scripts to version 6.4.0

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementRecyclerAdapter.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
Task/Issue URL: https://app.asana.com/0/608920331025315/1207876502054844/f 
Moves some of the heavier work in grouping and sorting passwords off of the main thread.
> Improve password list view performance, more work done away from main thread

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207911008828962/f 
----- 
> Update content scope scripts to version 6.5.0

- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Task/Issue URL: https://app.asana.com/0/1200905986587319/1207921881230819/f
Moved crashLogger.logCrash off the main thread.
QA-optional.
To test this, you can throw an exception at the beginning of the `try` block in `BrowserWebViewClient.shouldOverride` and see it is caught in the `catch` block. The app crashes as `logCrash` is called on the main thread.
> Android: Crash in BrowserWebViewClient.shouldOverride

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt
- app/src/main/java/com/duckduckgo/app/browser/webview/safewebview/SafeWebViewFeature.kt
Task/Issue URL: https://app.asana.com/0/1200204095367872/1207860204325574/f
This task adds `isDestroyed` checks to all the `WebView` methods used in `DuckDuckGoWebView`.
> Add isDestroyed guard to WebView methods

- .github/workflows/update-content-scope.yml
- .github/workflows/update-ref-tests.yml
Task/Issue URL: https://app.asana.com/0/1205648422731273/1207923237973390/f
This PR updates the peter-evans/create-pull-request action to the latest version. It fixes a bug, which causes workflow failures whenever there is an existing PR to update.
QA-optional
> Bump create-pull-request GH action to 6.1.0

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206222240301795/f
Fixes an `UninitializedPropertyAccessException` when `onFireDialogVisibilityChanged` is called.
> Fix onFireDialogVisibilityChanged crash

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/test/java/com/duckduckgo/app/browser/newtab/NewTabPageProviderTest.kt
- app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt
Task/Issue URL: https://app.asana.com/0/1157893581871903/1207939900109577/f
- Improve the check for Onboarding is complete
- Add tests to make the implementation more robust
On each step, wait for searches and sites to fully load in the browser
_Onboarding not complete_
_Favorites under Onboarding_
> Tests for onboarding steps

- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherAdapter.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1207940772480311/f
This PR removes the call to add a placeholder with the existing image drawable, which was causing a crash when scrolling.
> Tab manager crash fix

- app/src/main/AndroidManifest.xml
Task/Issue URL: https://app.asana.com/0/1200581511062568/1207877791850324/f
Removed `excludeFromRecents` flag associated with `IntentDispatcherActivity`.
> Github Issue: [Bug] App hides itself when minimizing and sometimes even close

- app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageView.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/network/PrivacyConfigService.kt
Task/Issue URL: https://app.asana.com/0/1114857721287938/1207910885306190
Fixes issue when navigating from landscape to portrait in the NTP legacy view
_From develop _
_From this branch_
> NTP legacy view should respect orientation changes

- app/src/test/java/com/duckduckgo/app/pixels/campaign/params/RealAdditionalPixelParamsGeneratorTest.kt
Task/Issue URL: https://app.asana.com/0/1201462763415876/1207948877341495/f
The test before can fail at random since we can't guarantee that the 2 generated values will never be the same. We attempt to randomize but it is not worth investing in more complex logic to ensure randomness.
Unit tests pass
> Fix flaky campaign test

- build.gradle
- buildSrc/build.gradle
- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1207912454820662/f
- Updates Anvil `2.5.0-beta09` → `2.5.0-beta11`.
- Anvil `2.5.0-beta10+` uses Kotlin `1.9.24`, so this also bumps Kotlin `1.9.22` → `1.9.24`.
> Update Kotlin to 1.9.24 + Anvil to 2.5.0-beta11

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/1125189844152671/1207821290657757/f 
Reset cpm state when manually refreshing page
> Reset cpm state on refresh

- autofill/autofill-internal/build.gradle
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
- autofill/autofill-internal/src/main/res/values/donottranslate.xml
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/AutofillPrefsStore.kt
Task/Issue URL: https://app.asana.com/0/0/1207954526931535/f 
Adds an internal setting to reset values used by counter decliner logic
_Feature 1_
> Autofill: adds internal setting to reset decline counter

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/store/InternalAutofillStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDeclineStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDisablingDeclineCounter.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/DisablePromptCredentialsObserver.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDisablingDeclineCounterTest.kt
- autofill/autofill-internal/build.gradle
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
- autofill/autofill-internal/src/main/res/values/donottranslate.xml
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/AutofillPrefsStore.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1207943705873936/f 
Aligns logic with other platforms around when don't ask users about disabling autofill:
- if a password has been stored or user manually enabled autofill, then don't ask.
_Feature 1_
_Feature 2_
> Autofill: update logic to decide if user is onboarded

- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillFeature.kt
- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillScreens.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/store/InternalAutofillStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementActivity.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsViewModel.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/ResultHandlerPromptToDisableCredentialSaving.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDeclineStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDisablingDeclineCounter.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/DisablePromptCredentialsObserver.kt
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/AskToDisableDialogTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/DisableInSettingsSnackbarTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/ResultHandlerPromptToDisableCredentialSavingTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDisablingDeclineCounterTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/feature/toggles/api/toggle/AutofillTestFeature.kt
- autofill/autofill-internal/build.gradle
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
- autofill/autofill-internal/src/main/res/values/donottranslate.xml
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/AutofillPrefsStore.kt
- autofill/autofill-test/src/main/AndroidManifest.xml
- autofill/autofill-test/src/main/java/com/duckduckgo/autofill/api/TestActivity.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1207895626594373/f 
Updates logic to show snackbar instead of Dialog after user dismisses twice our save dialog.
_Feature 1_
> Autofill: update dismiss logic to show snackbar

- common/common-ui/src/main/res/layout/dialog_single_choice_alert.xml
Task/Issue URL: https://app.asana.com/0/1205008441501016/1207953456660783/f 
Fix buttons cut off in Dialog single choice landscape. This was particularly noticeable in Duck Player, where the settings dialog had title and subtitle
_Feature 1_
> Fix buttons cut off in Dialog single choice landscape

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldRetentionPixelSender.kt
- app/src/androidTest/java/com/duckduckgo/app/integration/AtbIntegrationTest.kt
- app/src/androidTest/java/com/duckduckgo/app/statistics/api/StatisticsRequesterJsonTest.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/engagement/AutofillRefreshRetentionListener.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionRetentionPixelSender.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/api/AtbLifecyclePlugin.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/api/StatisticsRequester.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/pixels/FeatureRetentionPixelSender.kt
- statistics/src/test/java/com/duckduckgo/app/statistics/api/StatisticsRequesterTest.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionRefreshRetentionAtbPlugin.kt
Task/Issue URL: https://app.asana.com/0/0/1207965428441026/f 
- Renames `RefreshRetentionAtbPlugin` ➡️ `AtbLifecyclePlugin`
- Adds atb initialized callback
- Makes default implementation of the callbacks no-ops
No other changes in this PR.
> Add ATB initialized callback to ATB plugin, and rename for clarity

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/ResultHandlerPromptToDisableCredentialSaving.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDisablingDeclineCounter.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/ResultHandlerPromptToDisableCredentialSavingTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/declines/AutofillDisablingDeclineCounterTest.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/AutofillPrefsStore.kt
Task/Issue URL: https://app.asana.com/0/0/1207978333418692/f 
Adds an additional check that the snackbar informing users they can configure autofill in settings will be shown only once.
This fixes a bug whereby it would show repeatedly if you kept declining a login for the same site
- same site meaning the decline counter wouldn't keep increasing, and therefore the condition to show the snackbar was continually being met
- this PR adds in a timestamp for when user was last given the option, and is checked before offering to do it again (timestamp rather than a boolean to give us more flexibility in future if we need to show it again).
> Ensure snackbar shows only once that informs users they can configure autofill

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/inbox/1157893581871899/1207984745988817/1207988320986561
Autocomplete pixels stopped being sent after the NTP refactor. This PR fixes that.
_Pixels sent_
---
- https://app.asana.com/0/0/1207984745988817
> Fix autocomplete pixels not being sent

- .github/workflows/action-issue-opened.yaml
- .github/workflows/ads-end-to-end.yml
- .github/workflows/build-debug-apk.yaml
- .github/workflows/ci.yml
- .github/workflows/custom-tabs-nightly.yml
- .github/workflows/docs.yml
- .github/workflows/e2e-nightly-autofill.yml
- .github/workflows/end-to-end.yml
- .github/workflows/external-css-tests.yml
- .github/workflows/external-ref-tests.yml
- .github/workflows/nightly.yml
- .github/workflows/privacy-dashboard-end-to-end.yml
- .github/workflows/privacy.yml
- .github/workflows/sync-critical-path.yml
- .github/workflows/update-content-scope.yml
- .github/workflows/update-ref-tests.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207965178064690/f
Update the following to latest versions:
- `actions/checkout` to `v4`
-  `actions/setup-java` to `v4`
- `gradle/gradle-build-action@v2 `to `gradle/actions/setup-gradle@v3`
- `actions/setup-go@v2` to` actions/setup-go@v5`
- `actions/upload-artifact@v3` to `actions/upload-artifact@v4`
The following actions pass:
- Build debug apk: https://github.com/duckduckgo/Android/actions/runs/10244411392
- ADS e2e https://github.com/duckduckgo/Android/actions/runs/10244396942
- Custom tabs nightly https://github.com/duckduckgo/Android/actions/runs/10244422913
- E2e https://github.com/duckduckgo/Android/actions/runs/10244447653
- NIghtly https://github.com/duckduckgo/Android/actions/runs/10244475866
- CI Tests: …
> Update outdated actions used in out workflows

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1207980975183570/f
Ensure only NTP constructs the new tab pixel avoding a race and eventual ANR
_Test_
> Fix ANR due race accessing DAO in NTP

- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
Task/Issue URL: https://github.com/duckduckgo/Android/pull/4878
`onTabMoved` is scheduled to be run, so the `to` and/or `from` may be invalid by the time they are actually run. This PR removes that scheduling, so `onTabMoved` is called immediately in response to the tab being moved, and there is no time between scheduling and running this for the repository to emit and change the data by the time we handle this touch event.
---
- https://app.asana.com/0/0/1207990892540430
> Fix Tab manager crash

- app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
Task/Issue URL: https://app.asana.com/0/1201807753394693/1208012448385248/f
Replace deprecated ViewCompat.animate(view) method
> Replace deprecated animate() method

- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeatureModels.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeatureSettingsStore.kt
- ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/referencetests/AdClickAttributionAllowlistReferenceTest.kt
- ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/referencetests/AdClickAttributionLinkFormatsReferenceTest.kt
- ad-click/ad-click-impl/src/test/resources/reference_tests/adclickattribution/ad_click_attribution_reference.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1208032966372991/f
Removes the `settings` container object from the JSON model.
Passing tests
- [Autofill Feature Critical Path End-to-End tests](https://github.com/duckduckgo/Android/actions/runs/10353975695) ✅
- [Privacy Tests](https://github.com/duckduckgo/Android/actions/runs/10354131289) ✅
> Fix parsing issue

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/httperrors/HttpErrorDailyReportingWorker.kt
- app/src/main/java/com/duckduckgo/app/browser/httperrors/HttpErrorPixelName.kt
- app/src/main/java/com/duckduckgo/app/browser/httperrors/HttpErrorPixels.kt
- app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
- app/src/test/java/com/duckduckgo/app/browser/httperrors/HttpErrorDailyReportingWorkerTest.kt
- app/src/test/java/com/duckduckgo/app/browser/httperrors/RealHttpErrorPixelsTest.kt
Task/Issue URL: https://app.asana.com/0/1200581511062568/1208001712805221/f
Added daily pixels to count 400, 4xx, 5xx http errors. 
`Pixel sent: m_webview_received_http_error_400_daily with params: {count=2} {}`
`Pixel sent: m_webview_received_http_error_4xx_daily with params: {count=1} {}`
`Pixel sent: m_webview_received_http_error_5xx_daily with params: {count=3} {}`
Notice  the actual pixel url request does not have atb.
> Android: Track HTTP errors

- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208019450206551/f
The status bars icons were dark in dark mode in onboarding. We were explicitly setting the status bar icon colours to dark regardless of light/dark mode. We can just let the default handle this for us based on mode.
While doing the changes I noticed we were using some deprecated functions/settings so I removed and updated them where appropriate.
| Before                                                                                                     | After                                                                                                      |
|------------------------------------------------------------------------------------------------------------|----------------------------------------------- …
> Fix dark status bar icon colours in dark mode in onboarding 

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208046461855770/f
Fixes a crash when the “Add Bookmarks” `BottomSheetDialog` is dismissed when it isn't showing. 
_Add bookmark_
_Add bookmark (Manual dismissal)_
> Fix IllegalArgumentException - savedSiteAdded

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1208060223871210/f 
----- 
> Update content scope scripts to version 6.8.0

- app/src/main/java/com/duckduckgo/app/global/shortcut/AppShortcutCreator.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksActivity.kt
Task/Issue URL: https://app.asana.com/0/1207908166761516/1208043907427492/f
Clicking a bookmarked site from the list when accessed via the “Bookmarks” app shortcut would **not** open the bookmarked site in the app, instead the app would close. 
This fixes that by putting back an activity launch when clicking the bookmark, specifically after it’s been launched with an intent to `VIEW` which was removed when BookmarksActivity was moved to the `savedsites` module.
I took the opportunity to tie up the loose end where the app would close when pressing the back or up button after accessing it via the “Bookmarks” shortcut by stacking the `BrowserActivity` first before launching the `Bookmarks ` my suspicion this stopped working because of the module move as well, as we’re now missing a …
> Fix Bookmarks not opening when opened via Shortcut access

- app/src/main/java/com/duckduckgo/app/onboarding/store/OnboardingStoreImpl.kt
Task/Issue URL: https://app.asana.com/0/0/1207863588162441/f
Update onboarding site suggestions for some countries
_Germany_
- Set your device language to German (Germany)
- Perform a search
- SERP dialog will appear, tap on 'Got it!' button
- New sites in-context dialog will appear
_Canada_
- Set your device language to English (Canada)
- Perform a search
- SERP dialog will appear, tap on 'Got it!' button
- Open new tap
_Australia_
- Set your device language to English (Australia)
- Perform a search
- SERP dialog will appear, tap on 'Got it!' button
- Open new tap
> Update onboarding site suggestions

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1208098000878038/f 
----- 
> Update content scope scripts to version 6.9.0

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
- app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
- content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessaging.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerScriptsJsMessaging.kt
Task/Issue URL: https://app.asana.com/0/1204920898013511/1207777888338891/f 
https://app.asana.com/0/0/1207704461779423/f
_Feature 1_
_Open settings_
> Update initial setup message for Duck Player page

- app/src/androidTest/java/com/duckduckgo/app/browser/WebViewRequestInterceptorTest.kt
- app/src/androidTest/java/com/duckduckgo/app/referencetests/DomainsReferenceTest.kt
- app/src/androidTest/java/com/duckduckgo/app/referencetests/SurrogatesReferenceTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt
- app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
- app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
- duckplayer/duckplayer-api/src/main/java/com/duckduckgo/duckplayer/api/DuckPlayer.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerLocalFilesPath.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/di/DuckPlayerModule.kt
Task/Issue URL: https://app.asana.com/0/0/1207562793310532/f 
_Feature 1_
> Navigate to YT from Duck Player

- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208062551083727/f
This PR fixes the initial scroll position after a tab manager is opened. The position should now be centered to the current tab.  
The problem was that the call to scroll to the selected tab was in the `render()` function, which would not always happen before the `LayoutManager` was initialized because the `LiveData` observers were called in different/inconsistent order. This was causing the tabs to sometimes show the first tab when initially opening the tab manager.
The PR also improves the scroll position when switching between the list mode and grid mode, which should now be pretty much centered around the same middle item.
I was able to reproduce this only when I had a lot of tabs open. If you don’t have many, …
> Tab manager scrolling fix

- app/src/main/res/layout/include_omnibar_toolbar.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1208089433074776/f
Fixes the ripple on the fire button which clipped on the left side.
> Fix fire button ripple

- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/newtab/BookmarksShortcut.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1208094509610766/f 
Fixes a bug where clicking on a bookmark after coming from the NTP takes you nowhere
> Fix bookmarks from NTP

- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeature.kt
- ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickDataTest.kt
- app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
- app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
- app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
- app/src/main/java/com/duckduckgo/app/tabs/db/TabsDbSanitizer.kt
- app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
- browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207991167374138/f
Updated the code to make sure the exemption is kept after undoing a tab close action.
See the **Tests** section in the description of https://app.asana.com/0/488551667048375/1207991167374138/f
> Keep exemptions in case of closing a tab and subsequently undoing the action

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208092525366316/f 
Adds a few more launch sources to the autofill management screen pixel, and ensures the pixel fires regardless of the source of entry.
> Add missing launch sources to autofill management screen

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/newtab/AppTrackingProtectionStateView.kt
- app/src/main/java/com/duckduckgo/app/browser/newtab/FocusedViewProvider.kt
- app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabPageProvider.kt
- app/src/main/java/com/duckduckgo/app/downloads/DownloadsNewTabShortcutPlugin.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsNewTabShortcutPlugin.kt
- app/src/test/java/com/duckduckgo/app/browser/newtab/NewTabPageProviderTest.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/newtab/AutofillNewTabShortcut.kt
- new-tab-page/new-tab-page-api/src/main/java/com/duckduckgo/newtabpage/api/FocusedViewPlugin.kt
- new-tab-page/new-tab-page-api/src/main/java/com/duckduckgo/newtabpage/api/NewTabPagePlugin.kt
- new-tab-page/new-tab-page-api/src/main/java/com/duckduckgo/newtabpage/api/NewTabPageSectionPlugin.kt
- new-tab-page/new-tab-page-api/src/main/java/com/duckduckgo/newtabpage/api/NewTabPageShortcutPlugin.kt
- new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/NewTabPage.kt
- new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/shortcuts/NewTabShortcuts.kt
- new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/shortcuts/ShortcutsNewTabSectionView.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/newtab/RemoteMessageView.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/newtab/BookmarksShortcut.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/newtab/FavouritesNewTabSectionView.kt
Task/Issue URL: https://app.asana.com/0/1198194956794324/1208113353562028/f
Move plugin priorities to the priority interface for discoverability.
I have also convert priorities 1, 2, 3 etc to 10, 20, 30 subsequently so that it's simpler to insert plugins in the future
Incidentally, the second commit removes the `name` property from couple plugins as it's not used.
Code review to double check priorities/order remain the same.
Smoke test NTP
> Move priorities inside plugin APIs to make them more discoverable

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
> Update content scope scripts to version 6.10.0

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
Task/Issue URL: https://app.asana.com/0/1201807753394693/1208142627859298/f
Implement change to not show onboarding dialogs in PrivacyPro site
> Add onboarding exception for Privacy Pro site

- anrs/anrs-store/src/main/java/com/duckduckgo/app/anrs/store/UncaughtExceptionDao.kt
Task/Issue URL: https://app.asana.com/0/1208134428464537/1208151264908063/f 
Crash data has a computed hash which is used as the primary key in the DB. There are reports of crashes because of duplicate key insertion attempts.
We should ignore subsequents attempts to add the same hash.
> Add conflict strategy of ignore to stored crash hash keys

- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
Task/Issue URL: https://app.asana.com/0/1176956903599313/1208030810715640/f
Skip displaying major network onboarding dialog if other trackers dialog has been shown
Fix a bug where we weren't showing major network dialog in websites like instagram or youtube.
_Skip additional major network dialog display_
_Bug fix_
> Skip additional Trackers dialogs during onboarding

- duckplayer/duckplayer-impl/src/main/res/values-bg/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-cs/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-da/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-de/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-el/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-es/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-et/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-fi/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-fr/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-hr/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-hu/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-it/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-lt/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-lv/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-nb/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-nl/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-pl/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-pt/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-ro/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-ru/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-sk/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-sl/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-sv/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-tr/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values/strings-duckplayer.xml
Task/Issue URL: https://app.asana.com/0/1205008441501016/1208132429682162/f 
Translations + remove description from Duck Player settings dialog
_Feature 1_
> Update Duck Player copy

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1208187358475152/f 
----- 
> Update content scope scripts to version 6.12.0

- app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
- app/src/test/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208160020676247/f
- This fixes a `CompositeException` that is caused when an exception is thrown in `onError`.
- To fix this, instead of throwing an exception, we return an empty observable instead.
> Fix CompositeException
