- network-protection/readme.md
Task/Issue URL: https://app.asana.com/0/0/1205687772894398/f 
Add readme for np
N/A
> Add readme for netp

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgServerApi.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerService.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModel.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModel.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/FakeWgVpnControllerService.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/RealWgServerApiTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModelTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205651876758230/f
https://app.asana.com/0/0/1205768861130372/f
> Implement functionality

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/CoordinatorLayoutHelper.kt
- app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt
Task/Issue URL: https://app.asana.com/0/1163321984198618/1205404061469342/f 
This PR is a first attempt to fix our viewport issues
> Fix viewport

- app/src/main/res/values-hr/strings.xml
- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/0/1205747023822410/f
> Update button copy for 'not now' buttons

- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1205803419871701/f
Bump to 1.6.7
AppTP smoke tests
> Bump network lib to 1.6.7

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205785591351760/f
See asana
Same tests done in https://app.asana.com/0/1198194956794324/1205760598870176/f
> Ensure start/stop forground calls on wrong auto-start

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/cohort/NetpCohortPixelInterceptor.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPNotificationSettingsActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModel.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205657190386366/f
https://app.asana.com/0/0/1205802524286065/f
> Add pixels for geoswitching

- subscriptions/subscriptions-impl/build.gradle
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/AddDeviceActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/AddDeviceViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionViewModel.kt
- subscriptions/subscriptions-impl/src/main/res/layout/activity_add_device.xml
- subscriptions/subscriptions-impl/src/main/res/layout/activity_restore_subscription.xml
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/AddDeviceViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205795095480220/f 
See task
See task
> Remove sync from subs recover

- app/src/main/res/raw/login_form_detection_functions.js
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205715279846266/f
Prevent exceptions when DOM access inside iframes is not allowed 
_Feature 1_
> try/catch around iframe DOM access

- lint-rules/src/main/java/com/duckduckgo/lint/strings/MissingInstructionDetector.kt
- lint-rules/src/main/java/com/duckduckgo/lint/strings/PlaceholderDetector.kt
- lint-rules/src/test/java/com/duckduckgo/lint/strings/MissingInstructionDetectorTest.kt
- lint-rules/src/test/java/com/duckduckgo/lint/strings/PlaceholderDetectorTest.kt
- sync/sync-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205782622663832/f 
This PR adds donottranslate to string lint checks
> Add donotranslate files to string lint checks

- package-lock.json
- package.json
- privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackerallowlist/tracker_allowlist_matching_tests.json
- privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackerallowlist/tracker_allowlist_reference.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205810043069390/f 
----- 
> Update reference tests to version 1698156591

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetworkProtectionWaitlistImpl.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/waitlist/NetworkProtectionWaitlistTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205785591351675/f
See asana
See asana
> US only waitlist

- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1205811169823599/f
See Asana
Smoke tests AppTP
> Bump NG to 1.6.8

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1205774587219225/f 
Includes site title as title in share chooser, also as subject when sharing with email.
_Feature 1_
> add site title as subject when share

- app/src/main/res/values-ru/strings.xml
- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205707833624110/f
Translations for Email Protection in-context sign up
> Translations for email protection in-context signup

- .github/workflows/nightly.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205793949269201/f
Uses ubuntu-20.04 instead of latest to avoid issues on ci
More info: https://github.com/actions/runner-images/issues/6709
_Feature 1_
> Use ubuntu 20.04 for nightly GA

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/FeatureTogglesTest.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/TestTriggerFeature.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205806409373153/f
See asana task and the [API proposal](https://app.asana.com/0/1202552961248957/1205806409373059) for more info
PR contains full truth table integration tests.
Smoke test app update and new install for existing features using feature flags.
> Add capability for internal-only feature flags

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/0/1205823859163167/f
Adds translations for the updated site breakage report screen.
> Translations for the updated site breakage report screen

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPNotificationSettingsActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsActivity.kt
- network-protection/network-protection-impl/src/main/res/layout/activity_netp_notification_settings.xml
- network-protection/network-protection-impl/src/main/res/layout/activity_netp_vpn_settings.xml
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/0/1205832882507439/f 
Address a couple of ship review feedback:
https://app.asana.com/0/0/1205832882507439/f
https://app.asana.com/0/0/1205843183214548/f
QA-optional
> Address few ship review changes

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/config/NetPDefaultConfigProvider.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/config/WgVpnRoutes.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPSettingsLocalConfig.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsViewModel.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/WgVpnNetworkStackTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/FakeNetPSettingsLocalConfigFactory.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsViewModelTest.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/NetPInternalDefaultConfigProvider.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205852060630307/f
See asana
_Test exclude local routes_
> Make Exclude local networks a configurable setting

- app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt
- app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesMultipleReportReferenceTest.kt
- app/src/test/resources/reference_tests/brokensites/multiple_report_tests.json
- copy-files-from-to.json
Task/Issue URL: https://app.asana.com/0/0/1205851239813216/f
Added `multiple_report_tests.json` (and tests) and updated `BrokenSiteSubmitter` to not send the `lastSentDay` if empty.
Reference tests are passing.
Tests are passing.
> Shared reference testing

- common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/notifyme/NotifyMeView.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/config/NetPDefaultConfigProvider.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/config/WgVpnRoutes.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPNotificationSettingsActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPSettingsLocalConfig.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsViewModel.kt
- network-protection/network-protection-impl/src/main/res/layout/activity_netp_notification_settings.xml
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/WgVpnNetworkStackTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/FakeNetPSettingsLocalConfigFactory.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsViewModelTest.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/NetPInternalDefaultConfigProvider.kt
Task/Issue URL: https://app.asana.com/0/0/1205842615842261/f
See asana
_Notify me_
> Add notify me component to VPN notification settings

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205866455141643/f 
----- 
> Update reference tests to version 1698918761

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/PrivateDnsSettingReporter.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205846464751234/f
Report private DNS enabled
See Asana
> Report private DNS

- anvil/anvil-annotations/src/main/java/com/duckduckgo/anvil/annotations/InjectWith.kt
- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesSubComponentCodeGenerator.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205868479342965/f
Allow delayed component generation for specific components
QA optional, CI should be green
> Targeted component delay generation

- network-protection/network-protection-impl/src/main/res/layout/activity_netp_vpn_settings.xml
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/0/1205867926312721/f
Remove redundant text
QA-optional
> Remove redundant text

- autoconsent/readme.md
- common/readme.md
- cookies/readme.md
- internal-features/readme.md
- js-messaging/readme.md
- macos/readme.md
- privacy-config/readme.md
- request-filterer/readme.md
- settings/readme.md
- subscriptions/readme.md
- user-agent/readme.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205869617409241/f 
Add readmes
N/A
> Add readmes

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnOnboardingActivity.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
- common/common-utils/src/main/java/com/duckduckgo/app/global/extensions/ActivityExtensions.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsActivity.kt
- network-protection/network-protection-impl/src/main/res/drawable/ic_open_in_24.xml
- network-protection/network-protection-impl/src/main/res/layout/activity_netp_vpn_settings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205851614399912/f
See asana task
Smoke tests VPN and always on setting
> VPN always on setting

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetPRemoteFeature.kt
Task/Issue URL: https://app.asana.com/0/0/1205811419978625/f
QA optional
> Enable VPN settings to all

- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/PrivacyConfigDownloader.kt
Task/Issue URL: https://app.asana.com/0/0/1205878800415640/f 
This PR returns an error when the body return by the privacy config is null
> Return error if body is null

- sync/readme.md
Task/Issue URL: https://app.asana.com/0/0/1205687772894418/f 
Adds Sync Readme
_Feature 1_
> add sync readme

- windows/readme.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205687772894430/f
Adds readme to windows module
_Feature 1_
> add readme to windows module

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205896474029450/f
QA optional
> Remove redundant pixel

- ad-click/readme.md
Task/Issue URL: https://app.asana.com/0/0/1205687770304772/f
Added readme file for ad-click module.
> Add readme for feature: ad-click

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205911542931688/f
See [asana](https://app.asana.com/0/488551667048375/1205911542931688/f) for better explanation
Smoke test AppTP/VPN enable/disable and general functionality
> Retry notifyVpnStart to allow value propagation

- app/build.gradle
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/BillingClientWrapper.kt
Task/Issue URL: https://app.asana.com/0/0/1205834026864474/f 
See task
See task
> Move subs to ddg

- .maestro/app_tp/app_tp_onboarding.yaml
Task/Issue URL: https://app.asana.com/0/414730916066338/1205936253216099/f 
_Feature 1_
> Fix appTP onboarding release test

- .maestro/app_tp/app_tp_onboarding.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205939362024713/f 
- Test was looking for `Having issues?` when it should have been an uppercase `I` (i.e., `Having Issues?`)
> Fix casing on test expectation to ensure it matches the app

- app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205930296525293/f 
Changes the test url for fingerprinting
> Change fingerprinting url

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1205938901087974/1205938901087974
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.0
Updates Autofill to version [10.0.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.0).
* Don't call getAvailableInputTypes from topFrame by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/411
* Super small fix by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/412
* Send getRuntimeConfiguration to native on macOS by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/379
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/9.1.0...10.0.0
This release has been tested during autofill development. For smoke test steps …
> Update autofill to 10.0.0

- app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsViewModel.kt
- traces/traces-api/build.gradle
- traces/traces-api/src/main/java/com/duckduckgo/traces/api/StartupTraces.kt
- traces/traces-impl/build.gradle
- traces/traces-impl/src/main/AndroidManifest.xml
- traces/traces-impl/src/main/java/com/duckduckgo/traces/impl/AppStartUpTracer.kt
- traces/traces-impl/src/main/java/com/duckduckgo/traces/impl/RealStartupTraces.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205884745797973/f
Changes traces namespace from `com.duckduckgo.app.traces` to  `com.duckduckgo.traces`
> Standardize traces namespace

- app/src/main/java/com/duckduckgo/app/bookmarks/migration/AppDatabaseBookmarksMigrationCallback.kt
- saved-sites/saved-sites-store/src/main/java/com/duckduckgo/savedsites/store/SavedSitesEntitiesDao.kt
Task/Issue URL: https://app.asana.com/0/1174433894299346/1204733967627383
> Sync: Migrate old favourites

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerRequestInterceptor.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerService.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpEgressServersProvider.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModel.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/FakeWgVpnControllerService.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/FakeNetpEgressServersProvider.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModelTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/RealNetpEgressServersProviderTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205842615840144/f
Migrate geoswitching to use /locations instead
https://app.asana.com/0/0/1205937644199354/f
> Migrate geoswitching to locations

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/1200277586140538/1205815026944164/f
Fixed domain matching for site location permissions.
Follow the instructions in the Asana task as you need an account, US VPN and Fake location. -> https://app.asana.com/0/0/1205815026944164/1205924990018517/f
> Android: location permission silently fails on marlboro.com

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/DeviceShieldTileService.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1205958704775590/f
Avoid lateinit crash when accessing dispatcherProvider
Inside Asana task
> ensure dispatcher provider injected before init serviceScope

- .github/workflows/sync-critical-path.yml
- .github/workflows/sync-end-to-end.yml
- .maestro/sync_flows/critical_path_recover_account.yaml
Task/Issue URL: https://app.asana.com/0/0/1205947939113341/f 
This PR updates the skeleton test used to test the recovery code generation in sync.
Run Sync Critical Test worfllow
https://github.com/duckduckgo/Android/actions/runs/6877821735/job/18706171596
---
- https://app.asana.com/0/0/1205946625717016
> Sync: Critical Path Skeleton Test

- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/listitem/SectionHeaderListItem.kt
- common/common-ui/src/main/res/color/tertiary_text_color_selector.xml
- common/common-ui/src/main/res/values/design-system-colors.xml
- common/common-ui/src/main/res/values/design-system-theming.xml
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncAccountRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205910347984891/f
New text color added to design system and applied to `SectionHeaderListItem`
- Go to Settings
> ADS: Section Header List Item update

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Task/Issue URL: https://app.asana.com/0/1200905986587319/1205978524013477/f
This reverts commit f2f6508d025095b1aff4ca3f6d3f47d2c7d7208d.
See Asana task.
> Android: Revert the "Provide more info / allow loading sites with certificate issues (Android)"

- common/common-utils/src/main/java/com/duckduckgo/common/utils/UriString.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/useragent/RealUserAgent.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205957264014376/f 
Use etld+1 instead of sameorsubdomain for UA exceptions
> Use etld+1 to compare exceptions for the user agent

- common/common-utils/src/main/java/com/duckduckgo/common/utils/UriString.kt
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/useragent/RealUserAgent.kt
Reverts duckduckgo/Android#3886
> Revert "Use etld+1 to compare exceptions for the user agent"

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpRemoteFeatures.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
- app/src/test/java/com/duckduckgo/app/firebutton/FireButtonViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
- build.gradle
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModelTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModelTest.kt
- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1205249419591210/f
Changes:
- `kotlin_version` = `1.8.10` → `1.9.20`
-  `anvil_version` = `2.4.4` → `2.4.8`
- `ksp_version` = `1.8.10-1.0.9` → `1.9.20-1.0.14`
- `compile_sdk` = `33` → `34`'
- `version.androidx.room` = `2.5.0` → `2.6.0`
- `version.robolectric` = `4.9.2` → `4.11.1`
> Update to Kotlin 1.9.20

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModel.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1174433894299346/1205965902577857/f
This PR adds the missing triggers for Sync. More details in the description
All steps assume Sync is enabled
_New Tab - Favourites present_
_New Tab - Favourites not present_
_Sync Settings_
> Sync: Align platform triggers

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsViewModel.kt
- network-protection/network-protection-impl/src/main/res/layout/activity_netp_vpn_settings.xml
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205997010028871/f
See Asana task
_Test_
> Add battery usage setting to VPN

- app-tracking-protection/vpn-impl/src/main/AndroidManifest.xml
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnActionReceiver.kt
- network-protection/network-protection-impl/src/main/AndroidManifest.xml
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/notification/NetPDisabledNotificationBuilder.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/notification/NetPEnableReceiver.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNamesTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205947647495715/f
https://app.asana.com/0/0/1206000100414551/f
> Add pixels for snooze

- app-tracking-protection/vpn-impl/src/main/res/values/donottranslate.xml
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/notification/NetPDisabledNotificationBuilder.kt
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/0/1206000100414542/f
See attached task
QA optional
> Implement snooze copy changes

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessaging.kt
- content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessagingTest.kt
- js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/JsMessaging.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205984446323518/f 
This PR changes the messaging public API
See task
> Modify public api to simplify code

- content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessaging.kt
- js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/JsMessaging.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205966157363554/f 
See task
See task
> Add welcome screen

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpRemoteFeatures.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1206027622911786/f
Lazy create json adapter that is causing some ANRs
QA optional
> Lazy create json Adapter

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206034608846569/f 
QA-optional
>  Remove unused autofill system service pixel name

- app/src/internal/AndroidManifest.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206043444843087/f
Remove unnecessary manifest entry, see asana task for more info
Smoke tests AppTP/VPN, app update and fresh install
> Clean up unnecesary VPN service internal manifest entry

- .maestro/app_tp/app_tp_onboarding.yaml
- app-tracking-protection/vpn-impl/src/main/res/values-bg/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-cs/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-da/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-de/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-el/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-es/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-et/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-fi/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-fr/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-hr/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-hu/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-it/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-lt/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-lv/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-nb/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-pl/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-pt/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-ro/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-ru/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-sk/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-sl/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-sv/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-tr/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-ru/strings.xml
Task/Issue URL: https://app.asana.com/0/0/1205217801169320/f 
Smartling job: https://dashboard.smartling.com/app/projects/b01b53ede/account-jobs/b01b53ede:xb9jhwltidzn?filter=ALL&projectIds[]=b01b53ede
See title
_Feature 1_
> Remove Beta from copy in my apps view

- app/src/main/res/xml/provider_paths.xml
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/RecoveryCodePDF.kt
Task/Issue URL: https://app.asana.com/0/1174433894299346/1204602339432017/f 
This PR changes where we store the pdf for the sync recovery code
_Save PDF_
> Sync: Recovery PDF Location

- subscriptions/subscriptions-impl/build.gradle
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205966157363556/f 
See task
See task
> Add features to subs

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
- browser-api/src/main/java/com/duckduckgo/browser/api/JsInjectorPlugin.kt
- content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/ContentScopeScriptsJsInjectorPlugin.kt
- content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScripts.kt
- content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/ContentScopeScriptsJsInjectorPluginTest.kt
- content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScriptsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206016824322724/f 
Adds a desktop mode flag to css before injecting it
N/A
> Add desktop mode to css

- app/src/main/java/com/duckduckgo/app/job/JobCleaner.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionStatusReporting.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206058566872873/f
Increase frequency from 24h -> 2h
QA optional, ensure that in logs work is scheduled
> DAU reporting from 24h -> 2h

- sync/sync-impl/src/main/res/layout/view_sync_enabled.xml
- sync/sync-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206051770773058/f 
Shows Notify me view for Android 13+ users if notifications are disabled
_Feature 1_
> Add notify me view to sync settings

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/cohort/NetpCohortStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206074870029724/f
Use `commit` when setting cohort
Ensure cohort is assigned upon fresh install and enable of VPN
> Use commit rather than apply for cohortLocalDate write

- .maestro/ads_preview_flows/1-_design-system-components.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206072563649378/f
> Fix maestro tests for ActionBottomSheetDialog which now auto-dismisses on button press

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/main/res/layout/activity_subscriptions_webview.xml
Task/Issue URL: https://app.asana.com/0/0/1206034166295745/f 
See task
See task
> Modify toolbar for subs

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsActivity.kt
- network-protection/network-protection-impl/src/main/res/drawable/ic_info_gray.xml
- network-protection/network-protection-impl/src/main/res/layout/activity_netp_vpn_settings.xml
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206002582493449/f
Check attached screenshot in task, smoke test vpn settings
> Apply changes to VPN Settings

- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1206119523583181/f 
Updates coroutines to `1.7.3`. 
- currently specified explicitly to use `1.6.4` but is is already using coroutines `1.7.2` due to transitive dependencies, so this is effectively a minor bump
ℹ️ the maestro release tests passed (see link in task)
> Update coroutines lib dependency to latest stable (1.7.3)

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- node_modules/@duckduckgo/autofill/dist/shared-credentials.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1206111598841000/1206111598841000
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.1
Updates Autofill to version [10.0.1](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.0.1).
* Tweak pulldown menu copy on desktop by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/433
* Update password-related json files (2023-12-06) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/434
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/10.0.0...10.0.1
> Update autofill to 10.0.1

- app/src/androidTest/java/com/duckduckgo/app/browser/cookies/AppThirdPartyCookieManagerTest.kt
- app/src/androidTest/java/com/duckduckgo/app/referencetests/FireproofingReferenceTest.kt
- app/src/androidTest/java/com/duckduckgo/app/referencetests/FirstPartyCookiesReferenceTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/cookies/ThirdPartyCookieManager.kt
- app/src/main/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClient.kt
- cookies/cookies-api/src/main/java/com/duckduckgo/cookies/api/CookieManagerProvider.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/DefaultCookieManagerProvider.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/SQLCookieRemover.kt
- cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/WebViewCookieManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206114567373959/f
See asana task
QA optional. Smoke test clear data entry points
> Make cookie manager provider nullable

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/pixels/RealNetworkProtectionPixelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206114567373973/f
Ensure VPN enqueues contain ET ts.
QA optional
> Add ts to enqueue

- build.gradle
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-subscription-internal/build.gradle
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/settings/ProSettingNetPView.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/settings/ProSettingNetPViewModel.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/settings/SubsSettingsPlugin.kt
- network-protection/network-protection-subscription-internal/src/main/res/layout/view_settings_netp.xml
- network-protection/network-protection-subscription-internal/src/main/res/values/donottranslate.xml
- network-protection/network-protection-subscription-internal/src/test/java/com/duckduckgo/networkprotection/subscription/settings/ProSettingNetPViewModelTest.kt
- settings/settings-api/build.gradle
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/plugins/SubsSettingsPlugins.kt
Task/Issue URL: https://app.asana.com/0/0/1206070233895163/f 
See task
See task
> Adds NetP setting to new section in settings

- app-tracking-protection/vpn-impl/src/main/res/values-el/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-it/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-lv/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-ru/strings-vpn.xml
- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206111463804169/f 
Translations for the work to support uploading an image from the camera as well as from an existing file.
QA optional.
> Trigger translations for uploading an image from the camera

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/services/AuthService.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/services/SubscriptionsService.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModel.kt
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206024785662125/f 
See task
See task
> Add subs info in settings screen

- app/src/main/java/com/duckduckgo/app/di/DaoModule.kt
- app/src/test/java/com/duckduckgo/app/bookmarks/model/SyncSavedSitesRepositoryTest.kt
- app/src/test/java/com/duckduckgo/app/sync/SavedSitesSyncDataProviderTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDeduplicationPersisterTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDuplicateFinderTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesLocalWinsPersisterTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesRemoteWinsPersisterTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesTimestampPersisterTest.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/di/SavedSitesModule.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/Models.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/RealSyncSavedSitesRepository.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SyncSavedSitesRepository.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithm.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/store/SavedSitesSyncMetadataDao.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/store/SavedSitesSyncMetadataDatabase.kt
- saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithmTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206091622490129/f
This PR updates the PATCH request to the new format
> Sync: Improve lists mechanism - patch request

- app/src/test/java/com/duckduckgo/app/bookmarks/model/SyncSavedSitesRepositoryTest.kt
- app/src/test/java/com/duckduckgo/app/sync/SavedSitesSyncDataProviderTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDeduplicationPersisterTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDuplicateFinderTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesLocalWinsPersisterTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesRemoteWinsPersisterTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesTimestampPersisterTest.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/Models.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/RealSyncSavedSitesRepository.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SyncSavedSitesRepository.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesDeduplicationPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesLocalWinsPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesRemoteWinsPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithm.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterStrategy.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesTimestampPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/store/SavedSitesSyncMetadataDao.kt
- saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithmTest.kt
- saved-sites/saved-sites-store/src/main/java/com/duckduckgo/savedsites/store/SavedSitesRelationsDao.kt
Task/Issue URL: https://app.asana.com/0/1201493110486074/1205755865657794/f
This PR fixes https://app.asana.com/0/1157893581871903/1204732743092820
Steps in https://app.asana.com/0/1157893581871903/1204732743092820
> Sync: Improve lists mechanism - overwrite folders locally

- app/src/main/java/com/duckduckgo/app/di/DaoModule.kt
- app/src/test/java/com/duckduckgo/app/bookmarks/model/SyncSavedSitesRepositoryTest.kt
- app/src/test/java/com/duckduckgo/app/sync/SavedSitesSyncDataProviderTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDeduplicationPersisterTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDuplicateFinderTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesLocalWinsPersisterTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesRemoteWinsPersisterTest.kt
- app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesTimestampPersisterTest.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/di/SavedSitesModule.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/Models.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/RealSyncSavedSitesRepository.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SyncSavedSitesRepository.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesDeduplicationPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesLocalWinsPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesRemoteWinsPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithm.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterStrategy.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesTimestampPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/store/SavedSitesSyncMetadataDao.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/store/SavedSitesSyncMetadataDatabase.kt
- saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersisterTest.kt
- saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithmTest.kt
- saved-sites/saved-sites-store/src/main/java/com/duckduckgo/savedsites/store/SavedSitesRelationsDao.kt
Task/Issue URL: https://app.asana.com/0/0/1206091622490128/f
See Asana task
https://app.asana.com/0/1157893581871903/1206091622490138
> Sync: Improve lists mechanism - store children

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgServerApi.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpEgressServersProvider.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/FakeWgVpnControllerService.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/RealWgServerApiTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/FakeNetpEgressServersProvider.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModelTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/RealNetpEgressServersProviderTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206158080166975/f
Ensure we fallback to nearest server if user selected server is not present
Code review and check unit tests.
Also smoke test NetP.
> Fallback to nearest available server if user selected is gone

- httpsupgrade/httpsupgrade-impl/src/main/java/com/duckduckgo/httpsupgrade/impl/HttpsDataPersister.kt
Task/Issue URL: https://app.asana.com/0/0/1206139533408464/f 
Capture exceptions when persisting bloom filter data.
> Catch exceptions when persisting bloom filter

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206188777926610/f 
----- 
> Update content scope scripts to version 4.56.0

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModel.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/store/NetworkProtectionRepository.kt
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/fakes/FakeNetworkProtectionRepository.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206195889067599/f
Remove the reconnecting state
VPN smoke test
> Clean unused reconnecting state

- app/src/main/res/values-it/strings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206205808453374/f 
Italian translations were updated manually. This PR just brings them back in from the translation system.
QA-optional
> Get updated Italian strings from Smartling

- app-tracking-protection/vpn-impl/lint-baseline.xml
- app-tracking-protection/vpn-impl/src/main/res/values-bg/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-cs/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-da/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-de/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-el/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-es/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-et/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-fi/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-fr/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-hr/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-hu/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-it/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-lt/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-lv/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-nb/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-nl/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-pl/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-pt/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-ro/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-ru/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-sk/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-sl/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-sv/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values-tr/strings-vpn.xml
- app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206212313947171/f
See title
https://dashboard.smartling.com/app/projects/b01b53ede/account-jobs/b01b53ede:mpylah7djakw?filter=ALL
---
- https://app.asana.com/0/0/1206212313947171
> Remove reference to beta in AppTP banner after 1 day

- network-protection/network-protection-api/src/main/java/com/duckduckgo/networkprotection/api/NetworkProtectionState.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/state/NetworkProtectionStateImpl.kt
- network-protection/network-protection-subscription-internal/build.gradle
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetpAuthManager.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetpSubscriptionChecker.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetpSubscriptionManager.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetworkProtectionAccessState.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/configuration/NetpSubscriptionRequestInterceptor.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/ui/NetpVerifySubscriptionViewModel.kt
Task/Issue URL: https://app.asana.com/0/0/1206140936022689/f
https://app.asana.com/0/0/1206170013724657/f
> Add netp check for subscription

- sync/sync-impl/src/main/res/layout/view_sync_enabled.xml
Task/Issue URL: https://app.asana.com/0/0/1206207944257160/f 
_Favicons option_
> Sync: Remove Favicons Option

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/RealSecureStorageRepositoryFactory.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/SecureStorage.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/store/NeverSavedSiteRepository.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStoreTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/store/RealNeverSavedSiteRepositoryTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/FakeSecureStorage.kt
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
- autofill/autofill-internal/src/main/res/values/donottranslate.xml
- autofill/autofill-store/build.gradle
- autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageRepository.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/db/NeverSavedSiteEntity.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/db/NeverSavedSitesDao.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/db/SecureStorageDatabase.kt
- autofill/autofill-store/src/test/java/com.duckduckgo.autofill.store/RealSecureStorageRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206017917054330/f 
This stack of PRs will offer users a way of saying to _never ask to save a password for this site again_. This particularly PR focusses on:
- The underlying DB and the data APIs for adding sites to the excluded list, resetting the list and getting the count from the list.
- It also includes additional dev settings related to the "never saved" sites
Most of the testing will happen in the PR above, where the UI-based live. For this PR, just need to verify the DB migration happens ok.
There is a database schema change, so need to check the migration is ok.
---
- https://app.asana.com/0/0/1206071669665237
> Never save passwords for this site: api and storage

- package-lock.json
- package.json
- privacy-config/privacy-config-impl/src/test/resources/reference_tests/amplinks/config_reference.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206227003280415/f 
----- 
> Update reference tests to version 1703196979

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/connectionclass/ConnectionClassManager.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/connectionclass/ConnectionClassManagerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206222242762043/f
Fix NPE when aggregating connection quality
Requirements:
* test in emulator
* mac computer connected to VPN
_Test_
> Fix NPE in connection quality

- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncRemoteFeatureToggleTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206228939045921/f 
Fixes compilation error in test class
> Fix compilation error by making TestSharedPrefsProvider override getEncryptedSharedPrefs

- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetpSubscriptionChecker.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetpSubscriptionManager.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetworkProtectionAccessState.kt
- network-protection/network-protection-subscription-internal/src/test/java/com/duckduckgo/networkprotection/subscription/NetworkProtectionAccessStateTest.kt
- subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/Subscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingViewModel.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206170093899196/f
https://app.asana.com/0/0/1206210733915500/f
> Propagate NP settings entry state

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillJavascriptInterface.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/jsbridge/request/AutofillRequestParser.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/AutofillStoredBackJavascriptInterfaceTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/jsbridge/request/AutofillJsonRequestParserTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206229501650259/f 
Adds more validation to the JSON received from JS layer for autofill functions.
QA optional
> Improve validation on the data received from autofill JS functions

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/SaveRecoveryCodeFragment.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/SaveRecoveryCodeViewModel.kt
- sync/sync-impl/src/main/res/layout/fragment_recovery_code.xml
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncRemoteFeatureToggleTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/setup/SaveRecoveryCodeViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206142623045115/f 
This PR removes the QR code present in the post setup screen
_Create account_
> Sync: Remove QR code from Post - Setup screen

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206250815752484/f
Remove useless collection copies in checkAndReturnDns
Smoke test VPN and AppTP
> Remove useless collection copies

- app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserDetector.kt
Task/Issue URL: https://app.asana.com/0/1205847412641758/1206290274844724/f
https://app.asana.com/0/1202552961248957/1205083156611885/f
Fixed default browser issue (not reproducible on all devices). It's fixed now on the devices where it was discovered.
It was already tested on the device where the issue was noticed.
> Fixed default browser.

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/integration/NetPStateCollector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206197347970840/f 
https://app.asana.com/0/0/1206286083138218/f
> Add additional  netpbreakage metadata

- sync/sync-impl/src/main/res/layout/view_sync_disabled.xml
- sync/sync-impl/src/main/res/layout/view_sync_enabled.xml
- sync/sync-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206308364133285/f 
Adds banner for public release rollout.
Updates copies as part of prep. for requesting translations.
_Feature 1_
_Feature 2_ (optional)
- just smoke testing around updated copies
> Rollout banner and copy updates

- build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1206311795464810/f
Updates to Anvil 2.4.9
> Update to Anvil 2.4.9

- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1206287150356144/f 
Upgrade some libraries to the latest stable version
> Update gradle versions

- sync/sync-store/src/main/java/com/duckduckgo/sync/store/SharedPrefsProvider.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206135732984562/f 
Catch Throwable instead of exception when creating encrypted shared pref.
N/A
> Capture throwable instead of exception

- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1206260097920813/f
Update ng to 1.6.11 to include https://app.asana.com/0/488551667048375/1206260097920813/f
Smoke tests AppTP and VPN
> Update NG 1.6.11

- app-tracking-protection/vpn-impl/src/main/AndroidManifest.xml
Task/Issue URL: https://app.asana.com/0/0/1206023003085403/f 
Smoke test starting AppTP and Netp
> Add foregroundServiceType for relevant services

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206327228913421/f
Translations for https://github.com/duckduckgo/Android/pull/4034
N/A
> Bookmark translations

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSyncDataPersister.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersister.kt
- sync/sync-api/src/main/java/com/duckduckgo/sync/api/engine/SyncableDataPersister.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/di/SyncModule.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/RealSyncEngine.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/engine/FakeSyncableDataPersister.kt
- sync/sync-settings-impl/src/main/java/com/duckduckgo/sync/settings/impl/SettingsSyncDataPersister.kt
- sync/sync-store/src/main/java/com/duckduckgo/sync/store/SharedPrefsProvider.kt
- sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206319609422779/f 
Fixes using normal shared prefs on sync store
_Feature 1_
_Feature 2_ (using 2 devices)
_Feature 3_ (using 2 devices)
> Use encrypted shared prefs - Sync

- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/reddit/RedditBlockWorkaround.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206373903645207/f
Workaround reddit blocks when VPN is enabled
All tests in our browser and start being logged out from www.reddit.com
_1_
_2_
> Workaround reddit.com issues when VPN enabled

- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206350885255025/f 
Translations for copy used in the Autofill "never save for this site" functionality.
> Translations for "never save for this site" feature

- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1206399526867562/f
Ditto
Smoke tests VPN
> Update NG to 1.6.12 to downgrade WG lib version

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206405649234091/f 
Set metadata only when webview is created
See task
> Set metadata when webview is created

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/MediaCaptureResultHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/launcher/UploadFromExternalMediaAppLauncher.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/permission/RealExternalMediaSystemPermissionsHelper.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/postprocess/DeleteMediaCaptureWorker.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/postprocess/MediaCaptureDelayedDeleter.kt
- app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/postprocess/MediaCaptureImageMover.kt
Task/Issue URL: https://app.asana.com/0/0/1206339479527382/f
Renamed files, comments to avoid confusion. No other changes.
> Android: Rename files to avoid confusion

- app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206413338208880/f
Provided the same handling to `UndeliverableException` in the `vpn` process as well
> Handle UndeliverableException in the :vpn process

- .github/workflows/ci.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206419665418067/f
Uses large runner to run ci jobs
N/A
> use large android runner for ci.yml

- subscriptions/subscriptions-impl/src/main/AndroidManifest.xml
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/repository/AuthRepository.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/services/SubscriptionsService.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/ChangePlanActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModel.kt
- subscriptions/subscriptions-impl/src/main/res/drawable/ic_apple_logo.xml
- subscriptions/subscriptions-impl/src/main/res/layout/activity_change_plan.xml
- subscriptions/subscriptions-impl/src/main/res/layout/activity_subscription_settings.xml
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/FakeAuthDataStore.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/RealAuthRepositoryTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModelTest.kt
- subscriptions/subscriptions-store/src/main/java/com/duckduckgo/subscriptions/store/AuthDataStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205557379404217/f 
See task
See task
> Handle subs across platforms

- .github/workflows/update-content-scope.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206418414402174/f 
Fixes the css workflow
> Fix css workflow

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/WebViewRequestInterceptorTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandlerTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
- app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedOfflinePixelSender.kt
- app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
- app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
- app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/OptimizeTrackerEvaluationRCWrapper.kt
- app/src/main/java/com/duckduckgo/app/privacy/model/TrustedSites.kt
- app/src/main/java/com/duckduckgo/app/trackerdetection/Client.kt
- app/src/main/java/com/duckduckgo/app/trackerdetection/TdsClient.kt
- app/src/main/java/com/duckduckgo/app/trackerdetection/TdsEntityLookup.kt
- app/src/main/java/com/duckduckgo/app/trackerdetection/TrackerDetector.kt
- app/src/test/java/com/duckduckgo/app/global/UriStringTest.kt
- app/src/test/java/com/duckduckgo/app/trackerdetection/TdsClientTest.kt
- app/src/test/java/com/duckduckgo/app/trackerdetection/TrackerDetectorClientTypeTest.kt
- app/src/test/java/com/duckduckgo/app/trackerdetection/TrackerDetectorTest.kt
- browser-api/src/main/java/com/duckduckgo/app/global/model/Site.kt
- browser-api/src/main/java/com/duckduckgo/app/trackerdetection/EntityLookup.kt
- common/common-utils/src/main/java/com/duckduckgo/common/utils/UriString.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1206301192455389 
Optimize tracker evaluation by avoiding back and forth conversion of String to Uri and unneeded precautions for edge cases. 
Note: The methods I optimized are used in several places, where we can't be sure the URL is correctly formed (or can only be sure for some parameters but not others), and therefore we need to keep the old implementation as well as create several variants to make sure nothing breaks while optimizing whenever possible. Further optimizations might be possible but they would require a larger investment
A follow-up PR will setup an A/B test
_Feature 1_
No UI changes
> Optimize tracker evaluation

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/RealSyncEngine.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncDailyReportingWorker.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/engine/SyncEngineTest.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/pixels/SyncPixelsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206421064288087/f
_Daily Pixel_
> Sync: Fire Daily Sync Pixel

- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206462881489060/f
Fix welcome animation from getting stuck
_Android <13_
_Android >=13_
> Fix welcome animation

- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-bg/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-cs/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-da/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-de/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-el/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-es/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-et/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-fi/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-fr/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-hr/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-hu/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-it/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-lt/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-lv/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-nb/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-nl/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-pl/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-pt/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-ro/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-ru/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-sk/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-sl/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-sv/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values-tr/strings-privacy-protections-popup.xml
- privacy-protections-popup/privacy-protections-popup-impl/src/main/res/values/strings-privacy-protections-popup.xml
Task/Issue URL: https://app.asana.com/0/1205648422731273/1206443945558852/f
> Translations for the Privacy Protections Popup

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/SecureStorage.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/store/InternalAutofillStore.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStoreTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/securestorage/RealSecureStorageTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/FakeSecureStorage.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageRepository.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/db/WebsiteLoginCredentialsDao.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206040725837863/f 
Just the underlying API changes to support this feature. Including as a separate PR to make reviewing easier, but can consider this one QA-optional since nothing in this bottom branch calls the APIs.
> Autofill, support deleting all passwords, api changes

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206473929453281/f
Add service type when calling startForeground()
Smoke test AppTP / Netp
> Fix securityexception in VPNService

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- node_modules/@duckduckgo/autofill/dist/shared-credentials.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1206475855296108/1206475855296108
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.1.0
Updates Autofill to version [10.1.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.1.0).
* Support shadow dom by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/485
* New batch of fixes + integration test improvements by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/489
* Update password-related json files (2024-01-17) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/474
* Bump playwright from 1.38.1 to 1.40.1 by @dependabot in https://github.com/duckduckgo/duckduckgo-autofill/pull/458
* Update password-related json files (2024-01-26) by …
> Update autofill to 10.1.0

- app-tracking-protection/vpn-impl/src/main/AndroidManifest.xml
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206473929453281/f 
Smoke test Apptp / netp
> Replace foreground service type to specialuse

- .maestro/sync_flows/create_account.yaml
- .maestro/sync_flows/delete_server_data.yaml
- .maestro/sync_flows/recover_account.yaml
- .maestro/sync_flows/sync_data.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206472633555558/f 
This PR re-organises the Sync critical path test
Release Test  (Tests run when releasing the app):
- Create account
Sync Critical Path (Run every night):
- Recover account (also runs create account)
- Delete data
- Sync data
Maestro run
> Sync: Organise Critical Path Tests

- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/VariantManagerImpl.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1206491548019426/f
Change a log parameter to avoid workflow failure
> Replaced variant allocation log for variantKey

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/VpnEnabledNotificationBuilder.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206484244032061/f 
Notification badge on the app icon is shown even for persistent notifications that can't be dismissed in pre Android 14 devices
https://app.asana.com/0/0/1206503116417171/f
> Fix badge showing for persistent notif

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
- browser-api/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
- content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessaging.kt
- js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/JsMessaging.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/ItrMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingView.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingView.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/AddDeviceActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewClient.kt
- subscriptions/subscriptions-impl/src/main/res/drawable/ic_information_remover.xml
- subscriptions/subscriptions-impl/src/main/res/layout/view_itr_settings.xml
- subscriptions/subscriptions-impl/src/main/res/layout/view_pir_settings.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/ItrMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206414641255151/f 
See tasl
See task
> Add itr screen

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
- browser-api/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
- content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessaging.kt
- js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/JsMessaging.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/ItrMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingView.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingView.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/AddDeviceActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewClient.kt
- subscriptions/subscriptions-impl/src/main/res/drawable/ic_information_remover.xml
- subscriptions/subscriptions-impl/src/main/res/layout/view_itr_settings.xml
- subscriptions/subscriptions-impl/src/main/res/layout/view_pir_settings.xml
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/ItrMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206454043535976/f 
Amend copy
N/A
> Amend recover copy

- common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/StringExtensions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/ItrMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/ItrMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206093040131785/f 
See task
See task
> Check for etld in allowed domains

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/CurrentTimeProvider.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgServerApi.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgTunnel.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerService.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/failure/FailureRecoveryHandler.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/WireguardHandshakeMonitor.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/WgTunnelTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/failure/FailureRecoveryHandlerTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206063664298512/f 
See attached description
https://app.asana.com/0/0/1206483769461553/f
> Implement failure recovery

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/VpnEnabledNotificationBuilder.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206484244032061/f
https://app.asana.com/0/0/1206503116417171/f
> Replace channel with correct config

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/connectionclass/ConnectionClassManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206514199358868
Fix bug when calculating bottom band for terrible latency
QA optional, code review and test pass
> Fix bug when computing the terrible latency bottom band

- app/src/testInternal/java/com/duckduckgo/app/bookmarks/model/SavedSitesParserTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206545183445130/f 
Value should be int instead of long.
CI is green
> Fix develop test

- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorBucketAssignmentTest.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206514199358858/f
Integration test to test incremental rollout bucket allocation
Test shall pass
> Add test to verify bucket assignment

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/notification/NetPDisabledNotificationBuilder.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/notification/NetPNotificationActions.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/VpnSettingPlugin.kt
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/FeaturePriorities.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/unsafe_wifi/NetworkObserver.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/unsafe_wifi/UnsafeWifiDetectionSettingView.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/unsafe_wifi/UnsafeWifiDetectionViewModel.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/unsafe_wifi/UnsafeWifiMonitor.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/settings/VpnInternalSettingHeading.kt
- network-protection/network-protection-internal/src/main/res/layout/vpn_view_settings_unsafe_wifi.xml
- network-protection/network-protection-internal/src/main/res/values/donottranslate.xml
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/notification/SubsNetpDisabledNotificationBuilder.kt
Task/Issue URL: https://app.asana.com/0/42792087274227/1206484244031873/f
Unsafe wi-fi detection as internal feature
You will need to have a WIFI without eg. password to connect to
_test_
> Unsafe WIFI detection (internal only)

- app/src/main/res/values-hu/strings.xml
- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206537538410237/f 
Translations for `delete-all passwords` feature
QA-optional
> Translate autofill delete-all passwords feature

- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/notification/SubsNetpDisabledNotificationBuilder.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206579032673527/f
Update scope
QA optional
> Fix binding for SubsNetpDisabledNotificationBuilder

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandlerTest.kt
- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedOfflinePixelSender.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedPixelEntity.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
- autoconsent/autoconsent-api/src/main/java/com/duckduckgo/autoconsent/api/Autoconsent.kt
- autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/RealAutoconsent.kt
- autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/di/AutoconsentModule.kt
- autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/ui/AutoconsentSettingsViewModelTest.kt
- autoconsent/autoconsent-store/src/main/java/com/duckduckgo/autoconsent/store/AutoconsentSettingsDataStore.kt
Task/Issue URL: https://app.asana.com/0/0/1206468033249591/f 
Remove DaxAutoconsentCTA
No behavior changes, as the code triggering the dialog was already commented out
No UI changes
> Remove autoconsent cta

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandlerTest.kt
- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedOfflinePixelSender.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedPixelEntity.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
- autoconsent/autoconsent-api/src/main/java/com/duckduckgo/autoconsent/api/Autoconsent.kt
- autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/RealAutoconsent.kt
- autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/di/AutoconsentModule.kt
- autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/remoteconfig/AutoconsentFeature.kt
- autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/ui/AutoconsentSettingsViewModelTest.kt
- autoconsent/autoconsent-store/src/main/java/com/duckduckgo/autoconsent/store/AutoconsentSettingsDataStore.kt
- autoconsent/autoconsent-store/src/main/java/com/duckduckgo/autoconsent/store/AutoconsentSettingsRepository.kt
Task/Issue URL: https://app.asana.com/0/0/1206503102127836/f 
_Feature 1_
_Feature 2_
> Process autoconsent onbydefault

- .maestro/sync_flows/create_account.yaml
- .maestro/sync_flows/delete_server_data.yaml
- .maestro/sync_flows/recover_account.yaml
- .maestro/sync_flows/steps/action_add_bookmarks_and_folders.yaml
- .maestro/sync_flows/steps/action_add_new_device.yaml
- .maestro/sync_flows/steps/action_recover_account.yaml
Task/Issue URL: https://app.asana.com/0/414730916066338/1206502132931124/f
Update Sync tests so we don’t look for the QR image anymore
Run flow in maestro or locally creating a test account
> Sync: Update Maestro Flows to new Sync screen

- network-protection/network-protection-api/src/main/java/com/duckduckgo/networkprotection/api/NetworkProtectionState.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModel.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/state/NetworkProtectionStateImpl.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206654529735313/f 
https://app.asana.com/0/0/1206655219268367/f
> Fix unable to refresh keypair

- app/src/main/java/com/duckduckgo/app/browser/applinks/AppLinksLauncher.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206655694493738/f
These are no longer needed since https://github.com/duckduckgo/Android/pull/4177
> Remove SDK checks from AppLinksLauncher

- subscriptions/subscriptions-impl/build.gradle
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/BillingClientWrapper.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionRefreshRetentionAtbPlugin.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingView.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/AddDeviceViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionRefreshRetentionAtbPluginTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/AddDeviceViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1205648422731273/1206637905023887/f
See task.
> Pixels to measure subscription funnel

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/failure/FailureRecoveryHandler.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/failure/FailureRecoveryHandlerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206664411884204/f
See asana task https://app.asana.com/0/488551667048375/1206664411884204/f
Code review and unit tests
> Consider allowedIPs when failure recovery mode

- app/src/test/resources/reference_tests/brokensites/tests.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1206685188109106/f 
----- 
> Update reference tests to version 1708702034

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/ExclusionListAdapter.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/ManageRecentAppsProtectionActivity.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionAppsAdapter.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionExclusionListActivity.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/AppTPCompanyTrackersActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206702056869257/f
When AppTP is disabled, all places where the app can be included/excluded should be enabled. (View apps, Having issues with an app? and App tracking details)
https://app.asana.com/0/0/1206712558371850/f
> Allow exclusion list to be toggled when AppTP is disabled

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModel.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206744144956190/f
Fix NPE when trying to get location state
NA, code review
> Fix NPE getting country code

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206744144956192/f
Fix monitorVpnAlwaysOnState, see asana task
NA, code review
> Fix monitorVpnAlwaysOnState

- app/src/main/java/com/duckduckgo/app/referral/AppInstallationReferrerParser.kt
- app/src/play/java/com/duckduckgo/referral/PlayStoreAppReferrerStateListener.kt
- app/src/test/java/com/duckduckgo/app/referral/QueryParamReferrerParserTest.kt
- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/VariantManagerImpl.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206729008769465/f
Adds new referrer for the DMA choice screen.
Tests running
> Add new referrer for DMA choice screen

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserChromeClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
This reverts commit 8efab4040b55aae6538d699fc3a0fd2b920b2ec5.
Task/Issue URL: https://app.asana.com/0/488551667048375/1206752620492414/f
Reverts https://github.com/duckduckgo/Android/pull/4228
> Revert "Add transparent video poster image (#4228)"

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/BillingClientWrapper.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/services/SubscriptionsService.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206498134325580/f 
https://app.asana.com/0/0/1206755988821843/f
> Implement subscription confirmation

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserChromeClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
This reverts commit 86bf8a3680639b237332d935764ae6a10d6c3ff1.
Task/Issue URL: https://app.asana.com/0/488551667048375/1206765309823854/f
Reverts https://github.com/duckduckgo/Android/pull/4243
> Revert "Revert "Add transparent video poster image (#4228)" (#4243)"

- app/src/main/java/com/duckduckgo/app/browser/webview/WebViewFeatureFlagReporter.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206771419588506/f 
Catches exceptions that can happen inside WebView feature reporter when a valid `WebView` isn't installed.
QA-optional
> Catch exceptions inside WebViewFeatureFlagReporter if webview not available

- app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModel.kt
- app/src/test/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206765310240126/f
Cleans up the version on the “About” screen.
> Update About version

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206636072031849/f
This PR prevents logic inside onPageFinished to be executed unless progress is 100.
Smoke tests
> Avoid multiple calls to onPageFinished

- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ExceptionModels.kt
- anrs/anrs-impl/src/test/java/com/duckduckgo/app/anr/RedactDomainTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206793506985873/f
See [asana](https://app.asana.com/0/488551667048375/1206793506985873/f) task
Code review and unit tests
> Sanitize crash reports

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/0/1206753896577885/f
Added translations for Custom Tab.
N/A
> [Implementation] Translations for Custom Tab

- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ExceptionModels.kt
- anrs/anrs-impl/src/test/java/com/duckduckgo/app/anr/RedactDomainTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206797327447163/f
See [asana task](https://app.asana.com/0/488551667048375/1206797327447163/f)
Code review and unit tests
> Sanitize crash logs

- common/common-ui/src/main/java/com/duckduckgo/common/ui/notifyme/NotifyMeView.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/notifyme/NotifyMeViewModel.kt
- common/common-utils/src/main/java/com/duckduckgo/common/utils/ViewViewModelFactory.kt
- common/common-utils/src/main/java/com/duckduckgo/common/utils/plugins/view_model/ViewViewModelFactoryPluginPoint.kt
Task/Issue URL: https://app.asana.com/0/276630244458377/1206794624404182/f
Being able to inject ViewModelFactory for ViewScope
Use ContributesViewModel from CustomViews
Refactor one CustomView as proof of concept during review
_Feature 1_
> Allow injecting View ViewModelFactory

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/AddDeviceActivity.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/ItrMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206807350622744/f
> Update subscriptions FE staging urls

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/notification/NetPDisabledNotificationBuilder.kt
Task/Issue URL:  https://app.asana.com/0/488551667048375/1206764047349501/f
Rename VPN disabled channel
QA-optional
> Rename disabled channel

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesSubComponentCodeGenerator.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/DeviceShieldTileService.kt
- app/src/main/java/com/duckduckgo/app/di/ActivityComponent.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/DuckDuckGoActivity.kt
- di/src/main/java/dagger/android/AndroidInjector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206793506985940/f
Move to monolithic Activity component.
This reduces the `DaggerAppComponent` from 20+MB to 1MB
Smoke test the app
> Move to monolithic activity component

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedSites.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/firstpaint/PagePaintedHandler.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/firstpaint/PagePaintedOfflinePixelSender.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/firstpaint/PagePaintedPixelDao.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/firstpaint/PagePaintedPixelEntity.kt
- app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
- app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206728780511327/f 
Adds `page paint` duration following the same pattern as for page loaded.
https://app.asana.com/0/0/1206808799656005/f
> Add pixels for time to first paint

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/prefs/VpnSharedPreferencesProvider.kt
- network-protection/network-protection-impl/build.gradle
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetPRemoteFeature.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206806997674078/f
See Asana task
See [test cases](https://app.asana.com/0/0/1206806997674080/f)
> Fix vpn disable notification wrongly showing upon beta ending

- app/src/main/java/com/duckduckgo/app/accessibility/AccessibilitySettingsViewModel.kt
- app/src/test/java/com/duckduckgo/app/accessibility/AccessibilitySettingsViewModelTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/pixels/FeatureRetentionPixelSender.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
- voice-search/voice-search-impl/src/main/AndroidManifest.xml
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/RealVoiceSearchAvailability.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/RealVoiceStateReporterPlugin.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/VoiceSearchActivityLauncher.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/VoiceSearchPixelNames.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/language/LanguageSupportChecker.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/language/LanguageSupportCheckerDelegate.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/language/LocaleChangeReceiver.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/remoteconfig/VoiceSearchFeatureModels.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/remoteconfig/VoiceSearchFeatureRepository.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/remoteconfig/VoiceSearchFeatureSettingStore.kt
- voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/RealVoiceSearchActivityLauncherTest.kt
- voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/RealVoiceSearchAvailabilityTest.kt
- voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/language/RealLanguageSupportCheckerTest.kt
- voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/remoteconfig/RealVoiceSearchFeatureRepositoryTest.kt
- voice-search/voice-search-store/src/main/java/com/duckduckgo/voice/store/VoiceSearchDao.kt
- voice-search/voice-search-store/src/main/java/com/duckduckgo/voice/store/VoiceSearchDatabase.kt
- voice-search/voice-search-store/src/main/java/com/duckduckgo/voice/store/VoiceSearchDatabaseModels.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206638699302466/f
- Removes hardcoded `en-US`
- Gets locale exceptions from config
_No locale exceptions_
_With locale exceptions_
> Expand voice search locales

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/BillingClientAdapter.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/PlayBillingManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/RealBillingClientAdapter.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/Retry.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/billing/RealPlayBillingManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/billing/RetryTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1206760049330314/f
See task.
> BillingClient connection retries

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesSubComponentCodeGenerator.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/DeviceShieldTileService.kt
- app/src/main/java/com/duckduckgo/app/notification/NotificationHandlerService.kt
- di/src/main/java/com/duckduckgo/di/scopes/ServiceScope.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206806997674125/f
Fix service scope
code review
> Fix scope for NotificationHandlerService

- user-agent/user-agent-impl/src/main/java/com/duckduckgo/user/agent/impl/remoteconfig/ClientBrandHintFeatureSettingsRepository.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1206830301588062/f 
Tries to fix android tests failing due to nullpointerexception
Android ci should pass
> Fix flaky test on ClientBrand

- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetpSubscriptionManager.kt
- subscriptions/subscriptions-api/build.gradle
- subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/Subscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/repository/AuthRepository.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingViewModel.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206820564959242/f 
See task
See task
> Modify subs public API to return Flow

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/main/res/layout/activity_subscriptions_webview.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206793766473899/f 
See task
See task
> Enable purchase button depending on state and remove native spinner

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsChecker.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionRefreshRetentionAtbPlugin.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/repository/AuthRepository.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingView.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/main/res/drawable/ic_info_16.xml
- subscriptions/subscriptions-impl/src/main/res/layout/view_settings.xml
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionRefreshRetentionAtbPluginTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/RealAuthRepositoryTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206350282230199/f 
See task
See task
> Handle be error after purchase

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206350282230200/f 
See task
See task
> Better error handling for subs

- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/InfoPanel.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206840919603466/f 
Add support to Spannable in InfoPanel ADS component
_smoke test_
> Support spannable in infopanel api

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModel.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/ItrSettingViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206832754348922/f 
See task
See task
> Update UX when status changes

- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/language/LanguageSupportCheckerDelegate.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/listeningmode/OnDeviceSpeechRecognizer.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1206850916238195/f
This catches any errors when creating the on-device speech recognizer.
> Catch SpeechRecognizer errors

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206853350033015/f 
See task
See task
> Implement kill switch for purchases

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206858506446098/f
Select a more uncommon address for null tun
NA, smoke test VPN / AppTP on fresh install and app update
> Better address for null tun

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingView.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsActivity.kt
- subscriptions/subscriptions-impl/src/main/res/drawable/background_email_card.xml
- subscriptions/subscriptions-impl/src/main/res/layout/card_manage_email.xml
- subscriptions/subscriptions-impl/src/main/res/layout/view_settings.xml
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/0/1206850980150824/f 
See task
See task
> Add FAQs and final design changes

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt
- network-protection/network-protection-impl/src/main/res/layout/activity_netp_management.xml
- network-protection/network-protection-impl/src/main/res/layout/section_about.xml
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206850772484455/f
Update share feedback link for VPN
QA-optional / Check share feedback in VPN
> Remove beta info in share feedback

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetPWaitlistEndedChecker.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206836019887774/f
Add pixels to monitor VPN beta transition to subs
> Pixels to monitor VPN beta transition to subs

- .github/PULL_REQUEST_TEMPLATE.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1206864659419417/f
Updated the API level mentioned in `PULL_REQUEST_TEMPLATE.md` to `26`.
N/A
> Update API level mentioned in PULL_REQUEST_TEMPLATE.md

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/repository/AuthRepository.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/FakeSubscriptionsDataStore.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/RealAuthRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206868882992217/f 
See task
See task
> Add checks for encryption and refresh token

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingView.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1205648422731273/1206840909377306/f
See task.
> Updates to subscription pixels

- app/build.gradle
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/services/AuthService.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/services/SubscriptionsService.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/AddDeviceActivity.kt
Task/Issue URL: https://app.asana.com/0/0/1206872885477591/f 
See task
See task
> Subs ready for prod

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
Task/Issue URL: https://app.asana.com/0/0/1206872885477604/f 
See task
See task
> Use final skus

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206879686784829/f 
See task
See task
> Refresh token before deleting if needed

- network-protection/network-protection-api/src/main/java/com/duckduckgo/networkprotection/api/NetworkProtectionWaitlist.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetworkProtectionWaitlistImpl.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetpSubscriptionManager.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetworkProtectionAccessState.kt
- network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/settings/ProSettingNetPViewModel.kt
- network-protection/network-protection-subscription-internal/src/test/java/com/duckduckgo/networkprotection/subscription/NetworkProtectionAccessStateTest.kt
- network-protection/network-protection-subscription-internal/src/test/java/com/duckduckgo/networkprotection/subscription/settings/ProSettingNetPViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206875694725593/f
https://app.asana.com/0/0/1206886319244643/f
> Convert state to use flow

- common/common-utils/src/main/java/com/duckduckgo/common/utils/network/NetworkExtensions.kt
- common/common-utils/src/test/java/com/duckduckgo/common/utils/network/NetworkExtensionsTest.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/integration/NetPStateCollector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206880901864330/f
See asana task
Submit VPN report and see CGNATed going in the metadata
> Add CGNATed to vpn report

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/AddDeviceViewModel.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/AddDeviceViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206871724255891/f 
See task
See task
> React whenever a change happens in the add email screen

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1205648422731273/1206880159543045/f
See task.
> Fix sending "add email clicked" pixel after FE update 

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
Task/Issue URL: https://app.asana.com/0/0/1206864329754299/f 
See task
See task
> Fix delete sub account

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206897712272977/f 
See task
See task
> Guard against wrong states from be

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingView.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingViewModel.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1205648422731273/1206896593937389/f
See task.
> Send pixel on restore subscription setting click

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206897712273008/f 
See task
> Show popup when subscription recovered that already expired via email

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206930008157028/f 
See task
See task
> Change copy when recovering via email

- subscriptions/subscriptions-impl/build.gradle
- subscriptions/subscriptions-internal/build.gradle
- subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/InternalViews.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206920646035584/f 
See task
See task
> Add internal setting so internal users can recover a sub

- app/src/main/java/com/duckduckgo/app/bookmarks/migration/AppDatabaseBookmarksMigrationCallback.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1206912668071189/f
try-catch NPE we're seeing in production
NA just code review
> try-catch imgration NPE

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/RealBillingClientAdapter.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206930012661896/f
See task.
> Fix crash in onBillingSetupFinished()

- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1206460288078606/f
try-catch code that can throw illegal state exception
NA just code review
> Fix IllegalStateException when granting/denying site permissions

- app/src/main/java/com/duckduckgo/app/browser/tabpreview/WebViewPreviewGenerator.kt
- lint-rules/src/main/java/com/duckduckgo/lint/NoDispatcherComputation.kt
- lint-rules/src/main/java/com/duckduckgo/lint/registry/DuckDuckGoIssueRegistry.kt
- lint-rules/src/test/java/com/duckduckgo/lint/NoDispatcherComputationTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206120696346286/f
Introduces a lint rule around usages of computation dispatcher.
_Feature 1_
> Lint usages of computation dispatcher

- sync/sync-impl/src/main/res/layout/activity_connect_sync.xml
Task/Issue URL: https://app.asana.com/0/1201493110486074/1206542898886222/f
Fix layout for sync connect screen in smaller devices
Results: https://app.asana.com/0/0/1206948358341237/f
> Fix sync connect for small screens

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
- app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
- app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
- app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
- browser-api/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
- subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/Subscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
Task/Issue URL: https://app.asana.com/0/0/1206957384492835/f
See task
See task
> Redirect PPro

- app/src/main/java/com/duckduckgo/app/browser/customtabs/IntentDispatcherViewModel.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1207012396546155/f
Guard against exceptions when handoing custom tabs intents
> Fix ClassNotFoundException handling intent for custom tabs

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/cohort/CohortStore.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/cohort/RealCohortStoreTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205765828999962/f
See attached task
https://app.asana.com/0/0/1206987395274711/f
> Assign apptp cohort on reconfigure

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/PlayBillingManager.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/billing/RealPlayBillingManagerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207003406045665/f
See Asana task
Smoke test PPro
> Fix possible ANR in billing client

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
- browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207010355108255/f
Reverts duckduckgo/Android#4361
N/A
> Revert " Android: Fix RTE caused by liveTabs()"

- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206994138177836/f
Adding integration test to cover FF roll backs.
Incidentally also improved the `full feature lifecycle` test
NA, test pass
> Add FF roll back integration test

- app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
- httpsupgrade/httpsupgrade-impl/src/main/java/com/duckduckgo/httpsupgrade/impl/HttpsUpgrader.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207030969079654/f
add catch when creating bloomfilter to avoid crashing the app is something goes wrong with DB
QA optional
> try-catch SQLiteDiskIOException

- app/src/main/java/com/duckduckgo/app/di/DevicePropertiesModule.kt
- app/src/main/java/com/duckduckgo/app/global/store/AndroidUserBrowserProperties.kt
- browser-api/src/main/java/com/duckduckgo/browser/api/UserBrowserProperties.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/mappers/JsonRulesMapper.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/matchers/UserAttributeMatcher.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/models/MatchingAttributes.kt
- voice-search/voice-search-impl/build.gradle
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/rmf/VoiceSearchAttributeMatcher.kt
Task/Issue URL: https://app.asana.com/0/0/1207037593679449/f
PR migrates voice search matching attributes added in previous PRs in the same stack to the new interace.
To test once this is merged in the parent branch
> Migrate voice search matching attribute to new interface using plugin

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/BillingClientAdapter.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/PlayBillingManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/RealBillingClientAdapter.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207045790899643/f
Add error types to `reportPurchaseFailureStore` pixel
Code review
> Add error types to reportPurchaseFailureStore

- app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsFeature.kt
- app/src/internal/java/com/duckduckgo/app/audit/AuditSettingsFeature.kt
- app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsFeature.kt
- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/InternalAutofillFeature.kt
- common/common-ui-internal/build.gradle
- common/common-ui-internal/src/main/java/com/duckduckgo/common/ui/internal/ThemesPreviewInternalFeature.kt
- internal-features/internal-features-api/src/main/java/com/duckduckgo/internal/features/api/InternalFeaturePlugin.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/NetPInternalSettingsFeature.kt
- subscriptions/subscriptions-internal/src/main/AndroidManifest.xml
- subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/InternalViews.kt
- subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/SubsSettingPlugin.kt
- subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/SubscriptionsInternalSettingsActivity.kt
- subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/settings/CopySubscriptionDataView.kt
- subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/settings/DeleteSubscriptionView.kt
- subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/settings/RecoverSubscriptionView.kt
- subscriptions/subscriptions-internal/src/main/res/layout/activity_subs_internal_settings.xml
- subscriptions/subscriptions-internal/src/main/res/layout/subs_simple_view.xml
- sync/sync-internal/build.gradle
- sync/sync-internal/src/main/java/com/duckduckgo/sync/internal/InternalSyncFeature.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207003406045647/f
Move PPro internal settings under one screen.
Incidentally I have also explicitely sorted the other internal settings using priority keys.
Smoke test PPro internal settings
> PPro internal settings

- app/src/main/java/com/duckduckgo/app/accessibility/AccessibilityActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
- app/src/main/java/com/duckduckgo/app/browser/remotemessage/CommandActionMapper.kt
- app/src/main/java/com/duckduckgo/app/global/store/AndroidUserBrowserProperties.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
- app/src/main/res/layout/activity_accessibility_settings.xml
- browser-api/src/main/java/com/duckduckgo/app/accessibility/AccessibilityScreens.kt
- browser-api/src/main/java/com/duckduckgo/browser/api/UserBrowserProperties.kt
- navigation/navigation-api/src/main/java/com/duckduckgo/navigation/api/GlobalActivityStarter.kt
- remote-messaging/remote-messaging-api/src/main/java/com/duckduckgo/remote/messaging/api/MessageActionMapperPlugin.kt
- remote-messaging/remote-messaging-api/src/main/java/com/duckduckgo/remote/messaging/api/RemoteMessage.kt
- remote-messaging/remote-messaging-impl/build.gradle
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/mappers/JsonActionMappers.kt
- voice-search/voice-search-impl/build.gradle
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/rmf/VoiceSearchAttributeMatcher.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206596674293772/f
Adds the ability to perform navigation via RMF.
_Point to the RMF config linked in the task_
> Add RMF deep link navigation

- anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/GlobalUncaughtExceptionHandler.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207070178029312/f
try-catch ANR recording to avoid unintended crashes like OOM
> runCatching ANR recording

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/BillingClientAdapter.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/RealBillingClientAdapter.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207070178029317/f
try-catch get subscriptions
NA, code review
> try-catch getSubscriptions for OOMs

- common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/LocaleExtensions.kt
- common/common-utils/src/test/java/com/duckduckgo/common/utils/extensions/LocaleExtensionsTest.kt
- statistics/src/main/java/com/duckduckgo/app/statistics/pixels/FeatureRetentionPixelSender.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/VoiceSearchAvailabilityConfig.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207056773051316/f
Improves private voice search compatibility.
_With a compatible locale/device_
> Improve voice search compatibility

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/integration/NetPStateCollector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207146898981406/f
QA optional
> Add subscriptionActive in metadata

- .github/workflows/ads-end-to-end.yml
- .github/workflows/e2e-nightly-autofill.yml
- .github/workflows/end-to-end.yml
- .github/workflows/privacy-dashboard-end-to-end.yml
- .github/workflows/sync-critical-path.yml
- .maestro/config.yaml
- .maestro/shared/open_bookmarks.yaml
- .maestro/sync_flows/steps/action_add_bookmarks_and_folders.yaml
- .maestro/sync_flows/steps/action_verify_bookmarks_and_folders.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1206929980548371/f
Fixes failing Sync test
Run Action
> Maestro: e2e retries

- app/src/main/java/com/duckduckgo/app/trackerdetection/TrackerDataLoader.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207158909138057/f
Fix java.lang.OutOfMemoryError in updateTdsFromFile
NA
> Catch issues when loading TDS from file

- app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
- app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207141032969903/f
Fixed issue with blob URL in iframe.
See how it looks in the current version:
Test the fix
> Fixed issue with blob url in iframe.

- buildSrc/src/main/java/com/duckduckgo/gradle/BuildGradleModifier.kt
- buildSrc/src/main/java/com/duckduckgo/gradle/IntermoduleDependencyManager.kt
- buildSrc/src/main/java/com/duckduckgo/gradle/ModuleCreator.kt
- buildSrc/src/main/java/com/duckduckgo/gradle/ModuleType.kt
- buildSrc/src/test/java/com/duckduckgo/gradle/InputExtractorTest.kt
- buildSrc/src/test/java/com/duckduckgo/gradle/ModuleTypeTest.kt
- example-feature/example-feature-internal/build.gradle
- example-feature/example-feature-internal/lint-baseline.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207135101272582/f
Add internal module type to module-creator 
Run `./gradlew newModule test-feature/internal
Expect to create internal module
> Add internal module type to module-creator

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/app/tracking/AppTPRMFMatchingAttribute.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/app/tracking/AppTPRMFMatchingAttributeTest.kt
- app/src/main/java/com/duckduckgo/app/di/DevicePropertiesModule.kt
- app/src/main/java/com/duckduckgo/app/global/store/AndroidUserBrowserProperties.kt
- browser-api/src/main/java/com/duckduckgo/browser/api/UserBrowserProperties.kt
- network-protection/network-protection-impl/build.gradle
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/rmf/VpnRMFMatchingAttribute.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/mappers/JsonRulesMapper.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/matchers/UserAttributeMatcher.kt
- remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/models/MatchingAttributes.kt
- remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/matchers/UserAttributeMatcherTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207135101272551/f
Move NetP and AppTP to matching attributes plugin point
Test https://github.com/duckduckgo/Android/pull/4457
> Move AppTP and VPN matching attrs out of rmf modules

- anvil/anvil-annotations/src/main/java/com/duckduckgo/anvil/annotations/ContributeToActivityStarter.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
- app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207164955333567/f
Onboard the screen shortlisted in Asana task to rmf deeplink
_Feature 1_
> Onboard screens shortlist to RMF deeplink

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/customtabs/CustomTabActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207149305479467/f
Addressed the issue where permissions popups were not displayed in Custom Tab.
> Android: Permissions issue in Custom Tab

- subscriptions/subscriptions-impl/build.gradle
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProEligibleMatchingAttribute.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriberMatchingAttribute.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/FakeBooleanMatchingAttribute.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProEligibleMatchingAttributeTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriberMatchingAttributeTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206990668213579/f
Add PPro eligible/subscriber matching attrs to RMF
See [Asana task](https://app.asana.com/0/0/1207185787167221/f)
> Add pproEligible and pproSubscriber matching attrs

- app/build.gradle
- app/src/androidTest/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandlerTest.kt
- app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
- app/src/test/java/com/duckduckgo/store/HistoryDaoTest.kt
- history/history-api/build.gradle
- history/history-api/src/main/java/com/duckduckgo/history/api/HistoryApi.kt
- history/history-api/src/main/java/com/duckduckgo/history/api/HistoryEntry.kt
- history/history-api/src/main/java/com/duckduckgo/history/api/NavigationHistory.kt
- history/history-impl/build.gradle
- history/history-impl/lint-baseline.xml
- history/history-impl/src/main/java/com/duckduckgo/history/impl/History.kt
- history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryEntry.kt
- history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryModule.kt
- history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryRepository.kt
- history/history-impl/src/main/java/com/duckduckgo/history/impl/RealNavigationHistory.kt
- history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryDao.kt
- history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryDatabase.kt
- history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryEntryEntity.kt
- history/history-impl/src/test/java/com/duckduckgo/history/impl/HistoryTest.kt
- history/history-impl/src/test/java/com/duckduckgo/history/impl/store/HistoryDaoTest.kt
- history/readme.md
Extract history to its own module
> Extract history to a new module

- app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
Task/Issue URL: https://app.asana.com/0/0/1206889126871834/f
Defer local results until remote ones are available
_Feature 1_
_Feature 1_
> Defer local results until remote ones are available

- app/version/release-notes-suffix
- fastlane/Fastfile
Task/Issue URL: https://app.asana.com/0/488551667048375/1207185787211376/f
Remote RN footer and trim down heading
QA optional
> Trim down RN

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgServerApi.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/RealWgServerApiTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207220082784434/f
- Attempt to enable netp using the VPN staging patch
> Call server in internal only

- common/common-utils/src/main/java/com/duckduckgo/common/utils/notification/NotificationUtils.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1207205379865873/f
try-catch calls to notify to avoid crashes related to "Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS"
QA optional
> try-catch calls to notify

- fastlane/Fastfile
- fastlane/README.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1207185787211286/f
Created a new fastlane to annotate the releases when we deploy to play store
code review
In addition one can replace the `m_new_release_android` by eg. `test` and execute the lane and see the pixel arrives normally
> Anontate releases

- fastlane/Fastfile
Task/Issue URL: https://app.asana.com/0/488551667048375/1207185787211286/f
Missed one comment in https://github.com/duckduckgo/Android/pull/4507
Done in this PR
QA optional
> Make annotate_release a private lane

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deviceauth/SupportedDeviceAuthChecker.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207235055389762/f
Fix NPE crash when checking if device supports legacy auth
QA optional
> Fix NPE when getting isDeviceSecure

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/provider/CredentialsSyncLocalValidationFeature.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/BookmarksSyncLocalValidationFeature.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207226998070167/f 
Enable local field validation for bookmarks and credentials
_Feature 1_
> Enables sync local field validation

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncFeature.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/SyngGzipInterceptor.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncRemoteFeatureToggleTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206919211758353/f 
Compress PATCH sync request and use conten-encoding: gzip
_Feature 1_
> add interceptor to gzip sync requests

- app/src/main/java/com/duckduckgo/app/browser/remotemessage/CommandActionMapper.kt
- app/src/main/java/com/duckduckgo/app/survey/rmf/SurveyActionMapper.kt
- app/src/test/java/com/duckduckgo/app/survey/rmf/SurveyActionMapperTest.kt
- remote-messaging/remote-messaging-api/src/main/java/com/duckduckgo/remote/messaging/api/MessageActionMapperPlugin.kt
- remote-messaging/remote-messaging-api/src/main/java/com/duckduckgo/remote/messaging/api/RemoteMessage.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207226466353801/f 
Adds survey RMF action.
_Feature 1_
In case you don't see the survey, you are not in the cohort.
(if you want to try multiple times, perform fresh install, change endpoint, and try again)
> Adds survey rmf action

- app/src/main/java/com/duckduckgo/app/tabs/ui/GridViewColumnCalculator.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207235055389858/f
Ensure grid layout span cannot be below 1, otherwise it'll crash
Code review
> Ensure the grid layout span is never below 1

- app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/network/FakeDnsProvider.kt
- app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/network/FakeVpnNetworkStack.kt
- app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/network/DnsProvider.kt
- app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/network/VpnNetworkStack.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpRemoteFeatures.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/network/DnsProviderImpl.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/network/util/NetworkUtil.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStackTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207235055389832/f
Include more devices to the shortlist for dns-based blocking and  configure search domains in the VPN tunnel
Smoke tests AppTP and VPN
> Add devices to "dns-based blocking shortlist" and for all configure search domains in the VPN tunnel

- fastlane/Fastfile
Task/Issue URL: https://app.asana.com/0/488551667048375/1207235055389847/f
Release directly to prod at 0.1% to minimise PS review time.
Code review
> Skip open and close testing tracks when releasing

- fastlane/Fastfile
Task/Issue URL: https://app.asana.com/0/488551667048375/1207254853869852/f
N/A
> Fix syntax error Fastfile

- app/src/main/java/com/duckduckgo/app/global/file/FileDeleter.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207230693471364/f 
I've seen occasional crashes in the recursive file deleter which are possibly happening due to trying to recursively delete directories that are also being modified, triggered by events like having received a new favicon or trying to update a tab preview image.
In all likelihood the files will delete properly on next attempt, so adding a guard to catch exceptions to prevent app crashes.
QA-optional
> Catch exceptions on file deleter to prevent against app crashes

- fastlane/Fastfile
Task/Issue URL: https://app.asana.com/0/414730916066338/1207279249880434/f
See asana task
code review
> Fix rollout, needs to be a String

- fastlane/Fastfile
Task/Issue URL: https://app.asana.com/0/414730916066338/1207279626222679/f
See Asana
No code changes
> Fix Jenkins job failure: Google Api Error: Invalid request - The caller does not have permission

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
- subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/Subscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelParamRemovalPlugin.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205406454505228/f 
This PR adds the url origin to a new pixel once a purchase has been successful
- See task
> Add origin to PPro purchase

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/survey/AutofillSurvey.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/survey/AutofillSurveyImplTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207286758117876/f 
Removes survey's check on JS communication approach (this is getting imminently reverted so the API won't exist to call)
QA-optional
> Remove survey check on js communication support

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
This reverts commit 4acc7c8bdff5c27421a68adc051752dc0f0a0dbf.
Task/Issue URL: https://app.asana.com/0/0/1207292044111140/f
Reverts css update as tests failed
QA-optional
> Revert "Update content scope scripts to version 5.14.0 (#4537)"

- common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/ContextExtensions.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207164955333544/f
Smoke test app (a bit of focus on download and widgets)
> Fix RTE in register not exported receiver

- .maestro/bookmarks/open_bookmark_and_navigate_back.yaml
- .maestro/bookmarks/open_bookmark_in_folder_and_navigate_back.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207314595975833/f
_Feature 1_
> Fix back button not found on devices with gesture navigation

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/config/NetPDefaultConfigProvider.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/SystemAppUtils.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/systemapps/SystemAppsExclusionRepository.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/ui/AppExclusionListAdapter.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/ui/NetpAppExclusionListActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/ui/NetpAppExclusionListViewModel.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPSettingsLocalConfig.kt
- network-protection/network-protection-impl/src/main/res/drawable/ic_platform_android_24.xml
- network-protection/network-protection-impl/src/main/res/layout/item_exclusion_list_systemapp_category.xml
- network-protection/network-protection-impl/src/main/res/layout/item_exclusion_list_systemapp_header.xml
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/WgVpnNetworkStackTest.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/exclusion/ui/NetpAppExclusionListViewModelTest.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/NetPInternalDefaultConfigProvider.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207245564389818/f
https://app.asana.com/0/0/1207258329215938/f
> Implement system app category exclusion

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207254853869855/f 
https://app.asana.com/0/488551667048375/1207254853869855/f
> Add missing pixels for VPN SLIs

- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/38424471409662/1207344664175730/f
Updated copy from "when" to "if"
N/A
> Updated system apps exclusion copy

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207351226753468/f
Gracefully stop the VPN in case of `code 1555 SQLITE_CONSTRAINT_PRIMARYKEY` db error
> Fix SQLiteConstraintException spike crashes

- experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/VariantManagerImpl.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1207333077622726/f
Replace logging variants with the VariantConfig class
> ANR fix: com.duckduckgo.experiments.impl.Variant.toString

- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207390073646402/f
Change copy according to asana task
QA optional
> Change VPN FAQ copy

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/RealBillingClientAdapter.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207335546470325/f
Catch security exception when trying to connect to billing
> Catch security exception when connecting to billing

- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/608920331025315/1207245335603019/f 
Translations
> Translate copy changes for deleting passwords

- app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/res/layout/item_autocomplete_default.xml
- app/src/main/res/values/donottranslate.xml
- history/history-impl/src/main/java/com/duckduckgo/history/impl/RealNavigationHistory.kt
> Address ship review issues

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/0/1207432247916613/f
Translations for site and search suggestions
> Update search suggestions translations

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207453843423106/f
Hide onboarding dialog when back pressed
> Fix onboarding dialog when onBackPressed()

- history/history-api/build.gradle
- history/history-impl/build.gradle
Task/Issue URL: https://app.asana.com/0/0/1207493232239625/f 
_Feature 1_
> Fix dependencies

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/systemapps/SystemAppsExclusionRepository.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/integration/NetPStateCollector.kt
Task/Issue URL: https://app.asana.com/0/1203137811378537/1207488292683323/f
https://app.asana.com/0/0/1207511672435752/f
> Add excluded system apps in breakage metadata

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpRemoteFeatures.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpRemoteFeaturesStoreTest.kt
Task/Issue URL: https://app.asana.com/0/1198194956794324/1207518427354793/f
Gracefully handle the case where shared prefs can't be created in `AppTpRemoteFeaturesStore`
Added unit test check the handling.
Code review.
> Greatfully handle IOException when creating harmony shared prefs

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerService.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/failure/ServerDrainingMonitor.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/failure/ServerMigrationMonitor.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/FakeWgVpnControllerService.kt
Task/Issue URL: https://app.asana.com/0/1201462763415876/1207467139497225/f
https://app.asana.com/0/1201462763415876/1207492537012633/f
> Implement support for server draining

- history/history-impl/src/main/java/com/duckduckgo/history/impl/remoteconfig/HistoryRemoteFeature.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207530788464919/f 
Enables by default history to internal users
_Feature 1_
> History enabled by default to internal users

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/1203137811378537/1207529492824734/f
Add missing success pixels
QA-optional
> Add vpn start attempt success pixels

- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickManager.kt
- ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickManagerTest.kt
Task/Issue URL: https://app.asana.com/0/1200581511062568/1207538089069338/f
Fixed an issue where we did not recognize an ad click.
Check this comment -> https://app.asana.com/0/0/1207538089069338/1207542088379653/f
> Android: Incorrect exemption check

- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickManager.kt
- ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickManagerTest.kt
- app/src/main/java/com/duckduckgo/app/global/api/PixelAdClickAttributionRemovalInterceptor.kt
Task/Issue URL: https://app.asana.com/0/1200581511062568/1205280202205517/f
Fixed original implementation.
For testing see https://app.asana.com/0/0/1205280202205517/1207538549229511/f
> Implement m.pageloads.with.ad.attribution.android

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
Task/Issue URL: https://app.asana.com/0/1205648422731273/1207492658883339/f
Sign user out when request to /subscriptions returns 401 response code.
See task.
> Sign out on 401 from /subscriptions

- app/src/main/java/com/duckduckgo/app/browser/customtabs/CustomTabActivity.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1207553561239861/f
Updated `minActiveState` in `onCreate` from `CustomTabActivity`.
Could not reproduce this.
> java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState - CustomTabActivity

- subscriptions/subscriptions-impl/src/main/res/layout/view_settings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207581867216628/f
This PR fixes Privacy Pro section layout after recent updates to our design system components.
QA-optional
|![unsubscribed-before](https://github.com/duckduckgo/Android/assets/4212474/1adc90bc-0885-4244-bcd4-4cfde60637ba)|![unsubscribed-after](https://github.com/duckduckgo/Android/assets/4212474/948503a7-e1ec-40d3-9733-2210f6ec3f74)|
|![waiting-before](https://github.com/duckduckgo/Android/assets/4212474/5a6b41bc-8f11-42ce-b65b-bd45e265c962)|![waiting-after](https://github.com/duckduckgo/Android/assets/4212474/c8a3dac0-2aa0-4894-9fd7-d4804d721bc2)|
|![subscribed-before](https://github.com/duckduckgo/Android/assets/4212474/bdee433e-ac5e-4380-ae0f-0acc0c3de7f1)|![subscribed-after …
> Fix Privacy Pro app settings layout

- .maestro/ads_preview_flows/1-_design-system-components.yaml
Task/Issue URL: https://app.asana.com/0/1201807753394693/1207608009906874/f
Update ADS maestro tests with updated switch id
> ADS workflow: update switch id

- app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/flipper/PreferencesFlipperPlugin.kt
- app/src/internal/java/com/duckduckgo/app/flipper/FlipperInitializer.kt
Task/Issue URL: https://app.asana.com/0/1198194956794324/1207535395708803/f
Move flipper loading process off main thread as it has disk io
Flipper should still work when showing shared prefs
> Fix DiskReadViolation loading flipper in internal builds

- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207622026745026/f
Updated code to use `ConcurrentHashMap`.
Ad click Maestro flows should pass.
> Android Crash: com.duckduckgo.adclick.impl.DuckDuckGoAdClickData.getExemption

- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/play/java/com/duckduckgo/referral/PlayStoreAppReferrerStateListener.kt
Task/Issue URL: https://app.asana.com/0/home/1157893581871899/1207268538033883
Remove temporary pixels, as they are no longer needed
---
- https://app.asana.com/0/0/1207268538033883
> Remove temporary DMA legacy pixels

- app/src/androidTest/java/com/duckduckgo/espresso/TestExtensions.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/CookiesTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/GpcTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/HttpsUpgradesTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/PrivacyTestExtensions.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/RequestBlockingTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/SurrogatesTest.kt
Task/Issue URL: https://app.asana.com/0/1157893581871903/1207635301134661/f
Fix Privacy Tests, so they can work with the new Bottom Sheet
Run https://github.com/duckduckgo/Android/actions/runs/9650380487/job/26615880889
> Privacy Tests: Make it compatible with new Bottom Sheet

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/1200204095367872/1207640706936089/f
- Adds an `isInitialized` check when removing views from `webViewContainer`.
> Fix webViewContainer UninitializedPropertyAccessException

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/integration/NetPStateCollector.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/custom_dns/VpnCustomDnsViewModel.kt
Task/Issue URL: https://app.asana.com/0/0/1207500898026381/f
See attached task for pixel specifics
https://app.asana.com/0/0/1207610569621328/f
> Add pixels for custom dns

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProDaysSinceSubscribedMatchingAttribute.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207658463781438/f
Replace verification with try catch instead. The current solution incorrectly fails the check even if the value is of the correct type.
Instead of verifying the values, we just try catch it. If an exception occurs, we don’t match it.
Tests pass + QA optional
> Remove incorrect verification

- versions.properties
Task/Issue URL: https://app.asana.com/0/1207701481229686/1207714805957734/f 
Removes unused dependency declarations from `versions.properties`
QA-optional
> Cleanup library dependency file, remove unusued declarations

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModel.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoswitchingActivity.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207718554839880/f
Fix issue in VPN Geoswitching where changing server sometimes doesn't get applied.
https://app.asana.com/0/1202552961248957/1207717605286620/f
> Fix geoswithing race condition

- downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/DataUriParserTest.kt
- downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/DownloaderUtilTest.kt
- downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/UriUtilsFilenameExtractorTest.kt
- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1207744343982964/f 
Updates `Robolectric`. Requires some methods to be changed as they removed a function which had a typo in it.
> Update dependency: Robolectric. From 4.11.1 to 4.12.2

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/1200204095367872/1207733727777585/f
Only executes tab hidden/shown logic if the fragment is attached.
> Fix ViewModels IllegalStateException

- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/608920331025315/1207739557695203/f 
Adds translations for the updated copy around deleting all passwords
QA-optional
> Apply autofill translations for deleting all passwords

- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/newtab/FavouritesNewTabSectionsAdapter.kt
> fixing wrong reference

- anrs/anrs-internal/src/test/java/com/duckduckgo/app/anr/internal/store/DatabaseCleanupObserverTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207766557111776/f 
Fixes flaky test
_Feature 1_
> Fix internal flaky test

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/EngagementPixelsParamRemovalPlugin.kt
- app/src/main/java/com/duckduckgo/app/browser/newtab/FocusedLegacyViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModel.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherAdapter.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherListener.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/SavedSitesPixelName.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/SavedSitesPixelsParamRemovalPlugin.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarkScreenViewHolders.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksViewModel.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/dialogs/EditBookmarkFolderDialogFragment.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/dialogs/EditSavedSiteDialogFragment.kt
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/dialogs/SavedSiteDialogFragment.kt
- saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1206975542817143/f
Added pixels to understand navigation and search entry points.
See https://app.asana.com/0/488551667048375/1206975817853363/f
> Android: Add pixels to understand navigation and search entry points

- app/src/test/resources/reference_tests/brokensites/tests.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207783146236860/f 
----- 
> Update reference tests to version 1720621685

- build.gradle
Task/Issue URL: https://app.asana.com/0/1200204095367872/1207786068216975/f
Updates Anvil `2.5.0-beta07` → `2.5.0-beta09`
End-to-end test run: https://github.com/duckduckgo/Android/actions/runs/9894234137 ✅
Nightly test run: https://github.com/duckduckgo/Android/actions/runs/9909474905 ✅
> Update Anvil to 2.5.0-beta09

- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/72649045549333/1207655254348190/f 
Translations
QA-optional
> Translations for autofill import via desktop sync

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/DeviceInfoCollector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207809479817019/f
QA optional
> Add additional metadata for breakage pixel

- app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207806134837281/f
Ignore the property order in `FingerprintProtectionTest`
> Ignore FingerprintProtectionTest property order

- app/src/test/resources/reference_tests/brokensites/tests.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1207828713976554/f 
----- 
> Update reference tests to version 1721137609

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1207845944313948/f 
Disable omnibar scrolling on new tab page.
See task
> Disable omnibar scrolling when on new tab page

- app/src/test/java/com/duckduckgo/app/global/UriStringTest.kt
- browser-api/src/main/java/com/duckduckgo/app/browser/UriString.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1207180035648641/f
Addresses issue raised here: https://github.com/duckduckgo/Android/issues/4472
> Handle quote input

- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/firebutton/FireButtonStore.kt
- app/src/main/java/com/duckduckgo/app/global/view/FireDialog.kt
- app/src/main/java/com/duckduckgo/app/pixels/campaign/params/BrowserAdditionalPixelParams.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
- app/src/test/java/com/duckduckgo/app/pixels/campaign/params/BrowserAdditionalPixelParamPluginTest.kt
Task/Issue URL: https://app.asana.com/0/0/1207834698165873/f
https://app.asana.com/0/0/1207839964595094/f
> Add count for firebutton use

- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/userstate/UserStateReporterTest.kt
Task/Issue URL: https://app.asana.com/0/1207418217763355/1207775879598725/f
This PR adds unit tests to for the new tab manager drag & drop functionality, feature announcement banner and user state detection.
Running the tests and verifying that everything is green should be enough.
> Rearranging tabs: Unit tests

- app/src/main/java/com/duckduckgo/app/browser/newtab/FocusedViewProvider.kt
- app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabPageProvider.kt
- new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/NewTabPage.kt
Task/Issue URL: https://app.asana.com/0/1125189844152671/1207866683543525/f 
Change priorities to show NTP with internal flavour
> Change priorities of plugins to show with internal

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/AutofillSiteBreakageReportingDataStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/remoteconfig/AutofillSiteBreakageReportingExceptionsPersister.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/remoteconfig/AutofillSiteBreakageReportingFeature.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/remoteconfig/AutofillSiteBreakageReportingModule.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/remoteconfig/AutofillSiteBreakageReportingRemoteSettingsPersister.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/reporting/remoteconfig/AutofillSiteBreakageReportingRemoteSettingsPersisterTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/feature/toggles/api/toggle/AutofillTestFeature.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/reporting/AutofillSiteBreakageExceptionDatabase.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/reporting/AutofillSiteBreakageReportingFeatureRepository.kt
Task/Issue URL: https://app.asana.com/0/608920331025315/1207767049586664/f 
Basic plumbing for the feature flag
QA-optional
> Feature flag for autofill site breakage reporting

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207882500600720/f
Adds translations for general settings.
> General settings translations

- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
Task/Issue URL: https://app.asana.com/0/1200204095367872/1207920168100495/f
Renames `m_settings_general_open` to `ms_settings_general_pressed`
> Rename General settings pixel

- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/0/1207887150800792/f 
Translations for autofill breakage reporting
QA-optional
> Trigger translations for autofill breakage reporting

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageCategorySingleChoiceActivity.kt
Task/Issue URL: https://app.asana.com/0/1200204095367872/1207920168100501/f
Fixes a `BadTokenException` when showing the `RadioListAlertDialogBuilder`.
> Fix RadioListAlertDialogBuilder BadTokenException

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- node_modules/@duckduckgo/autofill/dist/shared-credentials.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1207920271697429/1207920271697429
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/12.1.0
Updates Autofill to version [12.1.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/12.1.0).
* [Form] Skip autofilling select input if it was changed already by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/580
* scanner: discard Form instances with no classified inputs by @sjbarag in https://github.com/duckduckgo/duckduckgo-autofill/pull/574
* [Credentials] Autofill when elements are in shadow by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/592
* Update password-related json files (2024-07-19) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/607 …
> Update autofill to 12.1.0

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/ResultHandlerPromptToDisableCredentialSaving.kt
Task/Issue URL: https://app.asana.com/0/0/1207978140984198/f 
Changes snackbar duration.
QA-optional
> Update snackbar duration for telling users autofill can be changed in settings

- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/1142021229838617/1207966810094056/f 
Request translations for the save dialog onboarding key features.
N/A
> Autofill: save onboarding translations

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1207418217763355/1207870191742618/f
This PR adds unit tests for the new functionality (toggling of the layout and pixel firing).
Verifying the tests are passing should be enough.
> List mode: Tests

- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1207418217763355/1207870191742619/f
This PR adds pixels for tracking the usage of tab layout changes.
> List mode: Pixels

- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/trackingparameters/RealTrackingParameters.kt
- privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackingparameters/tests.json
Task/Issue URL: https://app.asana.com/0/414730916066338/1207905708148686/f
Fixed ad click.
See task description for detailed steps.
> Android ad click giving 'Web page not available' error

- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/trackingparameters/RealTrackingParameters.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/trackingparameters/RealTrackingParametersTest.kt
Task/Issue URL: https://app.asana.com/0/1200204095367872/1208009677259118/f
As mentioned in https://github.com/duckduckgo/Android/pull/4871, this adds some unit tests and cleans up the code in this class to make it a bit more readable.
> Refactor tracking parameter removal

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/AppTPCompanyDetailsAdapter.kt
- build.gradle
Task/Issue URL: https://app.asana.com/0/414730916066338/1208000370605688/f
Updates AGP `8.2.0` → `8.5.1`
_Additional_
> Update AGP to 8.5.1

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- node_modules/@duckduckgo/autofill/dist/shared-credentials.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1208019514044452/1208019514044452
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/13.0.0
Updates Autofill to version [13.0.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/13.0.0).
Minor version update, adding a new feature behind `unknown_username_categorization` featureToggle, but the toggle is optional in JS and doesn't introduce regression.
* Update password-related json files (2024-07-30) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/621
* [Form] allow reconciling full credential by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/620
* [Form] Check if form.elements is iterable before destructuring by @dbajpeyi in …
> Update autofill to 13.0.0

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModel.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/feedback/RealPrivacyProUnifiedFeedbackTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1201462763415876/1207977042649727/f 
Add tests for the unified ppro feature
> Add tests for unified feedback flow

- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/main/AndroidManifest.xml
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/FeedbackHelpUrlProvider.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/FeedbackSubCategoryProvider.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackParams.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackSubmitFragment.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModel.kt
- subscriptions/subscriptions-impl/src/main/res/layout/content_feedback_submit.xml
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/feedback/RealPrivacyProUnifiedFeedbackTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1207977044044823/f
UI changes have been approved by design. Smoke test if needed each item in description if needed.
> Address ship review feedback

- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/build.gradle
- subscriptions/subscriptions-impl/src/main/AndroidManifest.xml
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/FeedbackCustomMetadataProvider.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/FeedbackHelpUrlProvider.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/FeedbackSubCategoryProvider.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackParams.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackSubmitFragment.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/pixels/PrivacyProUnifiedFeedbackPixel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/pixels/PrivacyProUnifiedFeedbackPixelSender.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelParamRemovalPlugin.kt
- subscriptions/subscriptions-impl/src/main/res/layout/content_feedback_submit.xml
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/feedback/RealPrivacyProUnifiedFeedbackTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1207815400172107/f 
ihttps://app.asana.com/0/72649045549333/1207978090216091/f
> Add pixels for unified feedback

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1207981775109564/f
Translations for https://github.com/duckduckgo/Android/pull/4861
> Translations for recent item removal

- subscriptions/subscriptions-dummy-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/DummyPrivacyProUnifiedFeedback.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208047268001821/f
Provide a dummy for fdroid builds
Before the fix `./gradlew assembleFR` would fail
After the fix it should build normally
> Add fdroid dummy for PrivacyProUnifiedFeedback

- app/src/main/java/com/duckduckgo/app/feedback/ui/common/FeedbackActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModel.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208045844925126/f
This PR contains the following:
- Fix for the back button bug in Browser Feedback
- Use OnBackPressedCallback instead of overriding onBackPressed in Ppro unified feedback
_Browser Feedback_
_PPro Unified Feedback_
Follow https://app.asana.com/0/0/1208071203780039/f
> Improve back button handling in feedback

- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/NetPInternalSettingsActivity.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/NetPInternalEnvDataStore.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/NetPInternalEnvInterceptor.kt
- network-protection/network-protection-internal/src/main/res/layout/activity_netp_internal_settings.xml
- network-protection/network-protection-internal/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/1201462763415876/1208075739156181/f
https://app.asana.com/0/1201462763415876/1208075739156185/f
> Allow changing VPN staging url"

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/global/model/SiteFactoryImpl.kt
- app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
- browser-api/src/main/java/com/duckduckgo/app/global/model/SiteFactory.kt
Task/Issue URL: https://app.asana.com/0/1200581511062568/1208075248978457/f
Updated the cache key for the cache used in site factory.
See test case (Issue section) in the description of https://app.asana.com/0/1200581511062568/1208075248978457/f
> Updated the cache key for the cache used in site factory.

- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeature.kt
- ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickDataTest.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207935486792481/f
Added `persistExemptions` sub-feature flag for `adClickAttribution`.
See the **Tests** section in the description of https://app.asana.com/0/488551667048375/1207935486792481/f
> Add the feature flag to switch off the new implementation

- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeature.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsDao.kt
- ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickDataTest.kt
- app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
- app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
- app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
- app/src/main/java/com/duckduckgo/app/tabs/db/TabsDbSanitizer.kt
- app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
- browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1207935486792488/f
Cleared the stored exemptions.
See the **Tests** section in the description of https://app.asana.com/0/488551667048375/1207935486792488/f.
> Clear the stored exemptions

- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeature.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsDao.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsDatabase.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsEntities.kt
- ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickDataTest.kt
- app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
- app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
- app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
- app/src/main/java/com/duckduckgo/app/tabs/db/TabsDbSanitizer.kt
- app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
- browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
Task/Issue URL: https://app.asana.com/0/1200581511062568/1207935486792480/f
Added `adclick_exemptions` db and stored tab exemptions.
See the **Tests** section in the description of https://app.asana.com/0/1200581511062568/1207935486792480/f.
> Add the DB and store exemptions 

- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeature.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsDao.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsDatabase.kt
- ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsEntities.kt
- ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickDataTest.kt
- app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
- app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
- app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
- app/src/main/java/com/duckduckgo/app/tabs/db/TabsDbSanitizer.kt
- app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
- browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
Task/Issue URL: https://app.asana.com/0/1200581511062568/1207747699651306/f
This is the feature branch for the implementation of https://app.asana.com/0/0/1207644177832301
See stacked PRs.
> Feature branch for Persist Exemption on Android App Restart

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/1201807753394693/1208043135771710/f
Added new strings for Privacy Pro onboarding dialog
> Privacy Pro onboarding dialog translations

- package-lock.json
- package.json
- privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackingparameters/tests.json
> Update reference tests to version 1724449523

- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
Task/Issue URL: https://app.asana.com/0/0/1208157486001226/f 
_Feature 1_
> Fire pixel when skipping onboarding

- .github/workflows/build-fdroid-apk.yml
Task/Issue URL: https://app.asana.com/0/1205648422731273/1208148719076002/f
This PR adds a GHA workflow that checks if FDroid apk can be built.
Note that FDroid build is currently broken on develop. There is a PR stacked on top of this one that fixes the issue and shows the new PR check in action.
QA-optional
> Add FDroid build check

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt
- subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/Subscriptions.kt
- subscriptions/subscriptions-dummy-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsDummy.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208148719076009/f
> Fix FDroid build

- .maestro/privacy_tests/7_-_Browser_restart_mid-session.yaml
Task/Issue URL: https://app.asana.com/0/414730916066338/1208189024953404/f
Updated maestro tests after persisting ad click exemptions.
`maestro test privacy_tests/7_-_Browser_restart_mid-session.yaml`
> Updated maestro tests after persisting ad click exemptions.

- app/src/main/java/com/duckduckgo/app/appearance/AppearanceActivity.kt
- app/src/main/java/com/duckduckgo/app/appearance/AppearanceViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/omnibar/BottomAppBarBehavior.kt
- app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/java/com/duckduckgo/app/settings/db/SettingsDataStore.kt
- app/src/main/res/layout/activity_appearance.xml
- app/src/main/res/layout/fragment_browser_tab.xml
- app/src/main/res/layout/include_omnibar_toolbar.xml
- app/src/main/res/layout/include_omnibar_toolbar_bottom.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/duckduckgo/app/Fakes.kt
- app/src/test/java/com/duckduckgo/app/appearance/AppearanceViewModelTest.kt
- browser-api/src/main/java/com/duckduckgo/app/browser/omnibar/model/OmnibarPosition.kt
Task/Issue URL: https://app.asana.com/0/1207418217763355/1207988999525948/f
This PR implements the bottom omnibar layout, including the hide animation on scroll. The position of the omnibar is determined based on the setting stored in the shared preferences.
https://github.com/user-attachments/assets/edfad444-e6df-4bee-bcd8-81cfe6d0e4f1
> Omnibar position: Bottom app bar layout

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/reddit/RedditBlockWorkaround.kt
Task/Issue URL: https://app.asana.com/0/1198194956794324/1208180779425187/f
Fix potential ANR during reddit workaround
Repeat test in https://github.com/duckduckgo/Android/pull/4591
> removeRedditEmptyCookie in io()

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldRetentionPixelSender.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/engagement/AutofillRefreshRetentionListener.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionRetentionPixelSender.kt
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionRetentionPixelSenderTest.kt
- statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/api/AtbLifecyclePlugin.kt
- statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
- statistics/statistics-impl/build.gradle
- statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/api/StatisticsRequester.kt
- statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/api/StatisticsService.kt
- statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/pixels/FeatureRetentionPixelSender.kt
- statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/user_segments/SegmentCalculation.kt
- statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/user_segments/StringAtbExtensions.kt
- statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/user_segments/UsageHistory.kt
- statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/user_segments/UserSegmentsPixelSender.kt
- statistics/statistics-impl/src/test/java/com/duckduckgo/app/statistics/user_segments/SegmentCalculationTest.kt
- statistics/statistics-impl/src/test/resources/json/mobile_segments_test_cases.json
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionRefreshRetentionAtbPlugin.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionRefreshRetentionAtbPluginTest.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1206955287217878/f
Add user segmentation
The tests added should ensure the functionality works as expected.
To run manual test, one needs to set up charles and proxy/change the `/atb.js` response
> User Segment calculations

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/VpnPixelParamRemovalPlugin.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PProUpsellBannerPlugin.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PproUpsellDisabledMessagePlugin.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PproUpsellRevokedMessagePlugin.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/ActionRequiredDisabledMessagePluginTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/DisabledBySystemMessagePluginTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/DisabledMessagePluginTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/FakeVPNStore.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/NextSessionEnabledMessagePluginTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/OnboardingEnabledMessagePluginTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PProUpsellBannerPluginTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PproUpsellDisabledMessagePluginTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PproUpsellRevokedMessagePluginTest.kt
- app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/RevokedMessagePluginTest.kt
Task/Issue URL: https://app.asana.com/0/0/1207152602150364/f
https://app.asana.com/0/0/1208182688782600/f
> Add pixels for upsell

- duckplayer/duckplayer-impl/src/main/res/values-bg/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-cs/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-da/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-de/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-el/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-es/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-et/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-fi/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-fr/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-hr/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-hu/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-it/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-lt/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-lv/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-nb/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-nl/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-pl/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-pt/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-ro/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-ru/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-sk/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-sl/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-sv/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-tr/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values/strings-duckplayer.xml
> Replace "Always Ask" with "Ask Every Time"

- network-protection/network-protection-impl/build.gradle
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/VpnRemoteFeatures.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModel.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/VpnExcludeAppPromptDialogBuilder.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPSettingsLocalConfig.kt
- network-protection/network-protection-impl/src/main/res/layout/dialog_vpn_disable.xml
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208221898644925/f
Adds a new exclude app prompt when attempting to disable VPN.
More info in the attached task description.
https://app.asana.com/0/0/1208233455261636/f
> Add Exclude app prompt to VPN

- sync/sync-impl/src/main/res/values-bg/strings-sync.xml
- sync/sync-impl/src/main/res/values-cs/strings-sync.xml
- sync/sync-impl/src/main/res/values-da/strings-sync.xml
- sync/sync-impl/src/main/res/values-de/strings-sync.xml
- sync/sync-impl/src/main/res/values-el/strings-sync.xml
- sync/sync-impl/src/main/res/values-es/strings-sync.xml
- sync/sync-impl/src/main/res/values-et/strings-sync.xml
- sync/sync-impl/src/main/res/values-fi/strings-sync.xml
- sync/sync-impl/src/main/res/values-fr/strings-sync.xml
- sync/sync-impl/src/main/res/values-hr/strings-sync.xml
- sync/sync-impl/src/main/res/values-hu/strings-sync.xml
- sync/sync-impl/src/main/res/values-it/strings-sync.xml
- sync/sync-impl/src/main/res/values-lt/strings-sync.xml
- sync/sync-impl/src/main/res/values-lv/strings-sync.xml
- sync/sync-impl/src/main/res/values-nb/strings-sync.xml
- sync/sync-impl/src/main/res/values-nl/strings-sync.xml
- sync/sync-impl/src/main/res/values-pl/strings-sync.xml
- sync/sync-impl/src/main/res/values-pt/strings-sync.xml
- sync/sync-impl/src/main/res/values-ro/strings-sync.xml
- sync/sync-impl/src/main/res/values-ru/strings-sync.xml
- sync/sync-impl/src/main/res/values-sk/strings-sync.xml
- sync/sync-impl/src/main/res/values-sl/strings-sync.xml
- sync/sync-impl/src/main/res/values-sv/strings-sync.xml
- sync/sync-impl/src/main/res/values-tr/strings-sync.xml
- sync/sync-impl/src/main/res/values/donottranslate.xml
- sync/sync-impl/src/main/res/values/strings-sync.xml
Task/Issue URL: https://app.asana.com/0/608920331025315/1208185599849132/f 
Translations for:
- sync promos
- instructions on getting DDG on other platforms (from sync flow)
> Translations for sync promos and getting on other platforms from sync flow

- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/menu/BrowserPopupMenu.kt
- app/src/main/res/layout/activity_browser.xml
- app/src/main/res/layout/include_omnibar_toolbar_mockup.xml
Task/Issue URL: https://app.asana.com/0/0/1208157864474373/f
> Omnibar position: Dummy toolbar

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1208267771530755/f 
----- 
> Update content scope scripts to version 6.15.0

- app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerFeature.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
- duckplayer/duckplayer-impl/src/test/kotlin/com/duckduckgo/duckplayer/impl/RealDuckPlayerTest.kt
> Add support for rollout

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- site-permissions/site-permissions-api/src/main/java/com/duckduckgo/site/permissions/api/SitePermissionsManager.kt
- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerImpl.kt
- site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsRepository.kt
- site-permissions/site-permissions-impl/src/test/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerTest.kt
- site-permissions/site-permissions-impl/src/test/java/com/duckduckgo/site/permissions/impl/SitePermissionsRepositoryTest.kt
- site-permissions/site-permissions-store/src/main/java/com/duckduckgo/site/permissions/store/sitepermissions/SitePermissionsDao.kt
- site-permissions/site-permissions-store/src/main/java/com/duckduckgo/site/permissions/store/sitepermissionsallowed/SitePermissionsAllowedDao.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1208294040908744/f
_Feature 1_
> Fix database access on main thread that caused a crash

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerDataStore.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerFeatureRepository.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1208263793923549/f
_Feature 1_
> Fix failing privacy tests

- .maestro/shared/onboarding.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1208302163064617/f
Add scroll down to an onboarding maestro test
> Update onboarding maestro test

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
Task/Issue URL: https://app.asana.com/0/1198194956794324/1208310633343744/f
Verify FF and Stores cross-reference each other. See Asana for more info
> Verify feature and store reference each other

- app/build.gradle
- fastlane/Fastfile
- fastlane/README.md
Task/Issue URL: https://app.asana.com/0/1202552961248957/1208202742960277/f
This PR updates fastlane script to use App Bundle format when uploading app to the Play Store
QA-Optional
> Update fastlane script to work with Play App Signing

- app/build.gradle
- versions.properties
Task: https://app.asana.com/0/1207908166761516/1208315099637999/f
[Venom](https://github.com/YarikSOffice/venom) accidentally made it into my previous PR as I’d been using it to kill the app to test my App Launch feature. Lets remove it 😬
> Remove Venom Gradle plugin

- app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserDetector.kt
- app/src/main/java/com/duckduckgo/app/email/AppEmailManager.kt
- app/src/main/java/com/duckduckgo/app/feedback/api/FeedbackSubmitter.kt
- common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/BooleanExtensions.kt
- common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/StringExtensions.kt
- statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/api/BrowserFeatureStateReporterPlugin.kt
- statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/pixels/FeatureRetentionPixelSender.kt
- voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/RealVoiceStateReporterPlugin.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1208307454923082/f
This PR changes the signature of `BrowserFeatureStateReporterPlugin` to be more flexible and return a map of key-value pairs.
> API change: Change BrowserFeatureStateReporterPlugin signature

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/72649045549333/1208294136875672/f
Translations for new strings added in highlights experiment
> Translations: Highlights Onboarding Experiment

- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/TypeAnimationTextView.kt
Task/Issue URL: https://app.asana.com/0/1125189844152671/1208318107615954/f 
Fixes formatting issues
CI passes
> Fix formatting from external contribution

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/VpnRemoteFeatures.kt
- network-protection/network-protection-impl/src/main/res/layout/dialog_vpn_disable.xml
- network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
- network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1142021229838617/1208316612251365/f
Enable the exclude app prompt shown everytime the VPN is attempted to be disabled by the user.
https://app.asana.com/0/1142021229838617/1208233455261636/f
> Ship VPN exclude app prompt

- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1205278999335242/1207870191742638/f
This PR removes the temporary pixel used by the list tab mode.
> List mode: Remove temporary pixel

- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/NetPInternalFeatureToggles.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/NetPInternalSettingsActivity.kt
- network-protection/network-protection-internal/src/main/res/layout/activity_netp_internal_settings.xml
- network-protection/network-protection-internal/src/main/res/values/donottranslate.xml
- network-protection/network-protection-internal/src/test/java/com/duckduckgo/networkprotection/internal/feature/TestNetPInternalFeatureToggles.kt
Task/Issue URL: https://app.asana.com/0/1198194956794324/1208368538104406/f
Remove unused dev setting to set fallback DNS
N/A just code review
Optionally smoke test VPN
> Remove VPN DNS fallback dev setting

- .maestro/autofill/steps/search_logins.yaml
Task/Issue URL: https://app.asana.com/0/414730916066338/1208406680151445/f
QA-optional
> Fix Autofill E2E test

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/survey/PproSurveyParameters.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/survey/PproSurveyParameterPluginsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208377228655940/f
Fix the ppro_status values in the survey params.
See more info in linked task.
QA-optional (Unit tests should pass)
> Fix mapping for ppro-status in survey params

- feature-toggles/feature-toggles-test/build.gradle
Task/Issue URL: https://app.asana.com/0/608920331025315/1208419567946879/f 
Ensures we are compatible with java 17 for `feature-toggles-test` module
> Ensure feature-toggles-test module is compatible with java 17

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ClipboardManager.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1208362038343242/f
Tries to fix NullPointer when accessing primaryClip text
_Feature 1_
> Fix null pointer when getting primary clip text

- app/src/main/java/com/duckduckgo/app/global/shortcut/AppShortcutCreator.kt
- common/common-ui-internal/src/main/java/com/duckduckgo/common/ui/internal/ThemesPreviewInternalFeature.kt
- common/common-ui/src/main/res/layout/activity_app_components.xml
- common/common-ui/src/main/res/layout/component_buttons.xml
- common/common-ui/src/main/res/layout/component_checkbox.xml
- common/common-ui/src/main/res/layout/component_expandable_layout.xml
- common/common-ui/src/main/res/layout/component_radio_button.xml
- common/common-ui/src/main/res/layout/component_switch.xml
- common/common-ui/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/5439528766830/1208417779579894/f
Add missing elements and move text around for the ADS demo.
> ADS: Meetup Presentation

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/extendedonboarding/ExtendedOnboardingFeatureToggles.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208366976833801/f
Remove aestheticUpdates Toggle from ExtendedOnboarding feature
> Remove aestheticUpdates Toggle

- .maestro/ads_preview_flows/1-_design-system-components.yaml
Task/Issue URL: https://app.asana.com/0/414730916066338/1208465588390866/f
Fix ADS maestro tests
> ADS: Fix maestro tests

- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Task/Issue URL: https://app.asana.com/0/1207252092703676/1208500665899984/f 
_Feature 1_
> Correctly load intercepted URLs

- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerPixelName.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
- duckplayer/duckplayer-impl/src/test/kotlin/com/duckduckgo/duckplayer/impl/RealDuckPlayerTest.kt
Task/Issue URL: https://app.asana.com/0/1207252092703676/1208512706836798/f 
_Feature 1_
> Rename duck-player pixel id to duckplayer

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/1202552961248957/1208503210252691/f
Translations for updated 'Surprise me' search suggestion
> Translations: Search Suggestion Update

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
- feature-toggles/feature-toggles-impl/lint-baseline.xml
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
Task/Issue URL: https://app.asana.com/0/0/1208490557030191/f 
Adds config map to Toggle
> Add config to toggle

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/1202552961248957/1208521491372569/f
Update translations for updated 'End dialog' in highlights experiment
> Translations: Update onboarding highlights end dialog

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
- app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
- app/src/test/java/com/duckduckgo/duckplayer/impl/DuckPlayerSettingsViewModelTest.kt
- duckplayer/duckplayer-api/src/main/java/com/duckduckgo/duckplayer/api/DuckPlayer.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerDataStore.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerFeatureRepository.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerSettingsActivity.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerSettingsViewModel.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
- duckplayer/duckplayer-impl/src/main/res/layout/activity_duck_player_settings.xml
- duckplayer/duckplayer-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1208500747095741/f
_Feature 1_
---
- https://app.asana.com/0/0/1208500747095741
> Add settings for opening Duck Player in new tab

- duckplayer/duckplayer-impl/src/main/res/values-es/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-et/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-fi/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-sv/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values/strings-duckplayer.xml
> Fix YouTube capitalization

- duckplayer/duckplayer-impl/src/main/res/layout/activity_duck_player_settings.xml
- duckplayer/duckplayer-impl/src/main/res/values-bg/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-cs/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-da/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-de/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-el/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-es/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-fi/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-fr/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-hr/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-hu/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-it/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-lt/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-lv/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-nb/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-nl/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-pl/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-pt/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-ro/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-ru/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-sk/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-sl/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-sv/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values-tr/strings-duckplayer.xml
- duckplayer/duckplayer-impl/src/main/res/values/strings-duckplayer.xml
Note: Estonian Strings are missing due to a delay in translations. Created https://app.asana.com/0/0/1208558284050278/f as a follow up to add them when ready
_Feature 1_
> Send missing string for translation

- .github/workflows/release_create_tag.yml
- fastlane/Fastfile
- fastlane/README.md
Reverts duckduckgo/Android#5159
> Revert "Release/0.0.1"

- .github/workflows/release_create_tag.yml
- .github/workflows/release_create_task.yml
- .github/workflows/release_production.yml
- fastlane/Fastfile
> GHA: Wrong parameter passing to fastlane

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
- app/src/main/java/com/duckduckgo/app/fire/FireActivity.kt
- app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsActivity.kt
- app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
- app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchFeature.kt
- app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchOptionHandler.kt
- app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImpl.kt
- app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/model/ShowOnAppLaunchOption.kt
- app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchOptionDataStore.kt
- app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
- app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt
- app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchOptionHandlerImplTest.kt
- app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImplTest.kt
- app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/FakeShowOnAppLaunchOptionDataStore.kt
- browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
- common/common-utils/src/main/java/com/duckduckgo/common/utils/UriExtension.kt
Task/Issue URL: https://app.asana.com/0/1205782002757341/1208523107235076/f 
Adds a feature toggle for the Show on App Launch feature that defaults to on.
N/A
> Show on App Launch: Feature toggle

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureTogglesInventory.kt
- feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/RealFeatureTogglesInventory.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
Task/Issue URL: https://app.asana.com/0/1125189844152671/1208600117694850/f 
Adds new public APIs to Toggles and FeatureTogglesInventory
> Adds new public APIs to Toggles and FeatureTogglesInventory

- app/src/main/java/com/duckduckgo/app/accessibility/AccessibilityActivity.kt
- app/src/main/java/com/duckduckgo/app/appearance/AppearanceActivity.kt
- app/src/main/java/com/duckduckgo/app/appearance/AppearanceScreen.kt
- app/src/main/java/com/duckduckgo/app/browser/omnibar/rmf/OmnibarPositionAttributeMatcher.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
- app/src/main/res/layout/activity_appearance.xml
- app/src/test/java/com/duckduckgo/app/browser/omnibar/rmf/OmnibarPositionAttributeMatcherPluginTest.kt
Task/Issue URL: https://app.asana.com/0/1207418217763355/1208589583700802/f
This PR adds support for:
- RMF navigation to the Appearance settings
- Highlighting the address bar option in the settings
- Filtering out users who already have the address bar position set to the bottom
Apply the following patch to test the PR (it will always evaluate the test remote config file):
```kotlin
Index: remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/network/RemoteMessagingService.kt
<+>UTF-8
diff --git a/remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/network/RemoteMessagi …
```
> Bottom omnibar RMF feature announcement

- new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/NewTabPage.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208621031521321/f
Disable NTP for internal users
_Open New Tab_
> NTP: use legacy for internal users also

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.css
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1208654379001281/f 
----- 
> Update content scope scripts to version 6.27.0

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchActivity.kt
- app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1208634701288221/f
Fixed suggestions changing issue.
To reproduce the issue:
To test the fix:
> Android: Address bar suggestions keep changing

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsChecker.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/auth/AuthInterceptor.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/ItrMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/repository/AuthRepository.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/services/SubscriptionsService.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/auth/AuthInterceptorTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/ItrMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/RealAuthRepositoryTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProBillingPeriodMatchingAttributeTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProDaysSinceSubscribedMatchingAttributeTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProDaysUntilExpiryRenewalMatchingAttributeTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProPurchasePlatformMatchingAttributeTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriptionStatusMatchingAttributeTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/survey/PproSurveyParameterPluginsTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionViewModelTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModelTest.kt
- subscriptions/subscriptions-internal/build.gradle
- subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/settings/AccountDeletionHandler.kt
- subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/settings/DeleteSubscriptionView.kt
- subscriptions/subscriptions-internal/src/test/java/com/duckduckgo/subscriptions/internal/settings/AccountDeletionHandlerImplTest.kt
Task/Issue URL: https://app.asana.com/0/1205648422731273/1208643784411875/f
_Smoke test Privacy Pro (no behavior changes are expected)_
> SubscriptionsManager refactoring

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1208660715919846/1208660715919846
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/15.1.0
Updates Autofill to version [15.1.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/15.1.0).
* [Form] expand username re-categorization to phone by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/691
* [Matching] Add 'search' for forceUnknown by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/692
* [Release automation] Update asana usage by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/693
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/15.0.0...15.1.0
This release has been tested during autofill development. For smoke test …
> Update autofill to 15.1.0

- app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
> Link follow-up task

- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/1149059203486286/1208634215033039/f
Request translations from Smartling for secondary button
N/A
> Request new copies for autofill onboarding secondary button

- .github/workflows/release_create_tag.yml
- fastlane/Fastfile
Task/Issue URL: https://app.asana.com/0/488551667048375/1208707081604791
https://github.com/duckduckgo/Android/actions/runs/11706637463
> GHA: Clean up tag workflow

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.css
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.js
- package-lock.json
- package.json
> Update content scope scripts to version 6.29.0

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/FeedbackCustomMetadataProvider.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackSubmitFragment.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionSupportInbox.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/services/SubscriptionsService.kt
- subscriptions/subscriptions-impl/src/main/res/layout/content_feedback_submit.xml
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/feedback/FakeCustomMetadataProvider.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/feedback/FakeSubscriptionSupportInbox.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModelTest.kt
Task/Issue URL:  https://app.asana.com/0/1200019156869587/1207815400172115/f
See more information in https://app.asana.com/0/1200019156869587/1207962930855838/f
https://app.asana.com/0/1200019156869587/1208675181927862/f
> Android: Send Privacy Pro Feedback to Support Inbox

- broken-site/broken-site-impl/build.gradle
- broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSitePomptDataStore.kt
- broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSitePromptRCFeature.kt
- broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSiteReportRepository.kt
- broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/di/BrokenSiteModule.kt
- broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/di/BrokenSitePromptDataStoreModule.kt
- broken-site/broken-site-impl/src/test/java/com/duckduckgo/brokensite/impl/RealBrokenSiteReportRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/0/1208572901396838/f 
_Feature 1_
> Add FF for enabling behavioral toast report

- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/storage.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/utils.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1208721460896060/f 
----- 
> Update content scope scripts to version 6.30.0

- .github/workflows/release_nightly.yml
Task/Issue URL: https://app.asana.com/0/414730916066338/1208721570762160
Use the checkout action to fetch all tags, instead of fetching them manually
https://github.com/duckduckgo/Android/actions/runs/11741977861/workflow
> GHA: fetch latest tag

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/subscription/NetpSubscriptionManager.kt
Task/Issue URL: https://app.asana.com/0/1208589375218614/1208715446356293/f
Remove unused API
QA-optional
> Remove unused getToken method

- app/src/main/java/com/duckduckgo/app/browser/trafficquality/AndroidFeaturesPixelSender.kt
- app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/test/java/com/duckduckgo/app/browser/trafficquality/AndroidFeaturesPixelSenderTest.kt
Task/Issue URL: https://app.asana.com/0/1200905986587319/1208698915378414/f
Added temporary pixel for android features enabled during search.
See Asana -> https://app.asana.com/0/0/1208698915378414/1208697268653508/f
> [Implementation]: Android - Getting base rates on user-enabled protections during search

- .github/workflows/release_upload_play_store.yml
Task/Issue URL: https://app.asana.com/0/1174433894299346/1208236772414095/f
This PR adds the final workflow for production releases
Run job
> GHA: Upload to Production workflow

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
- app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- duckplayer/duckplayer-api/src/main/java/com/duckduckgo/duckplayer/api/DuckPlayer.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerLocalFilesPath.kt
- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
- duckplayer/duckplayer-impl/src/test/kotlin/com/duckduckgo/duckplayer/impl/RealDuckPlayerTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1208676143593571/f
_Feature 1_
> Improve FF and files path caching

- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
- app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
Task/Issue URL: https://app.asana.com/0/1204920898013511/1208577246155731/f 
_Feature 1_
> Add pixels and remove ATB

- .gitignore
- node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
Task/Issue URL: https://app.asana.com/0/0/1208812661441521/f 
- Adds missing `autofillPasswordImport.js` which wasn't showing up because it was excluded in `gitignore` previously
- updates `gitignore` to no longer ignore it.
> Fix missing c-s-s password import JS file and gitignore

- app/src/main/java/com/duckduckgo/app/pixels/campaign/CampaignPixelParamsAdditionInterceptor.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208836497763122/f
Add code comment for `CampaignPixelParamsAdditionInterceptor`
QA-optional
> Add code comment

- privacy-config/privacy-config-impl/build.gradle
- privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigDownloader.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigDownloaderTest.kt
- privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigPersisterTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208034017399945/f
Log the different error types when DL(ding) the remote config
_Test_
> Log RC download error types

- app/src/main/java/com/duckduckgo/app/pixels/campaign/CampaignPixelParamsAdditionInterceptor.kt
Task/Issue URL: https://app.asana.com/0/0/1208864432139933/f
None
> Finalize code comment

- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
- malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/RealMaliciousSiteProtection.kt
Task/Issue URL: https://app.asana.com/0/1203249713006009/1208871416380593/f 
_Feature 1_
> Bind PrivacyConfigCallbackPlugin

- app/src/main/java/com/duckduckgo/app/widget/FavoritesObserver.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1208841273777750/f
Fix NPE when trying to get `AppWidgetManager.getInstance`
NA, code review
> Fix crash on FavoritesObserver

- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/extendedonboarding/HighlightsOnboardingExperimentManager.kt
Task/Issue URL: https://app.asana.com/0/1201807753394693/1208893694149809/f
Set experiment variants weight to 0 to include more users in experiment
N/A
> Disable onboarding Highlights experiment

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/integration/NetPStateCollector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208627799127675/f
Add auto exclude broken apps status in VPN feedback metadata + restructure some other info in VPN feedback
QA-optional
> Restructure feedback metadata for VPN

- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- subscriptions/subscriptions-impl/src/main/res/values-bg/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-cs/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-da/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-de/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-el/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-es/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-et/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-fi/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-fr/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-hr/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-hu/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-it/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-lt/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-lv/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-nb/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-nl/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-pl/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-pt/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-ro/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-ru/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-sk/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-sl/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-sv/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-tr/strings-subscriptions.xml
Task/Issue URL: https://app.asana.com/0/1205648422731273/1208917047742015/f
This PR add translations for string resources in subscriptions-impl module.
QA-optional
No UI changes other than translations.
> Add translations to subscriptions module

- app/src/main/java/com/duckduckgo/app/trackerdetection/blocklist/BlockList.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1208954147561552/f 
Adds more baseline subfeatures
N/A
> Adds more baseline subfeatures just in case

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
- app/src/main/java/com/duckduckgo/app/browser/autocomplete/BrowserAutoCompleteSuggestionsAdapter.kt
- app/src/main/java/com/duckduckgo/app/browser/autocomplete/SuggestionViewHolderFactory.kt
- app/src/test/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt
- app/src/test/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1174433894299346/1208855071397751/f
Ensure that Navigational links can be shown as Top Hits
Check https://app.asana.com/0/1174433894299346/1208909865959915/f for different scenarios
> Navigational links as top hits

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1209009001482464/1209009001482464
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.1.0
Updates Autofill to version [16.1.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.1.0).
* [DeviceInterface] Call closeautofillparent only after openManage calls by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/718
* [CredentialsImport] Call credentials flow call first, and then close parent by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/723
* [FeatureToggle] Add new autofill config for partial save trigger by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/724
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/16.0.0.. …
> Update autofill to 16.1.0

- .github/workflows/pr-review-notifications.yaml
Task/Issue URL: https://app.asana.com/0/1174433894299346/1208848095612597/f
Update PR Workflow to latest version
> GHA: Update Notifications PR

- subscriptions/subscriptions-impl/build.gradle
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsChecker.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsCheckerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/SubscriptionsCheckWorkerTest.kt
Task/Issue URL: https://app.asana.com/0/1205648422731273/1209011223549610/f
In certain scenarios, the app makes unnecessary requests to api/subscriptions endpoint - this PR addresses that. More context in the linked task.
See task.
> Fix trying to get non-existent subscription

- versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1208893769470376/f
Updates Anvil 2.5.0-beta11 to 2.5.0.
> Update Anvil to 2.5.0

- duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerSettingsActivity.kt
- duckplayer/duckplayer-impl/src/main/res/layout/activity_duck_player_settings.xml
- duckplayer/duckplayer-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/1207908166761516/1209098231830092/f 
Prerequisites: Enable `newSettings` feature flag
_New DuckPlayer_
_Old DuckPlayer_
|![Screenshot_20250107_165937](https://github.com/user-attachments/assets/fe4974cc-dfcd-4e54-9cfb-232d44aecb99)|![Screenshot_20250107_165910](https://github.com/user-attachments/assets/4a65741e-6c27-4c5e-9986-141a032df121)|
> Update Settings: Update DuckPlayer settings screen

- app/src/main/java/com/duckduckgo/app/trackerdetection/blocklist/BlockListInterceptorApiPlugin.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1209150899635962/f 
This PR fixes a bug where users on blocklist experiments won't get new remote config versions
> Fixes a bug where remote config is not downloaded correctly

- .github/workflows/build-ad-hoc.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1209097575356124/f
Allows to use a specific build variant
> GHA: Allow ad-hoc workflow to build different variants

- versions.properties
Task/Issue URL: https://app.asana.com/0/1209138401863706/1209159587067384/f 
Updates `AndroidX lifecycle` dependency version
> Update dependency: AndroidX Lifecycle to 2.8.7

- .github/workflows/ps-review-analysis.yml
- scripts/ps-analysis/ps_review_anomaly.py
- scripts/ps-analysis/requirements.txt
Task/Issue URL: https://app.asana.com/0/1198194956794324/1209163509371063/f
Creates a new workflow called "Play Store Review Analysis" that will perform some analysis on PS reviews trying to find anomalous patterns. And report those back in an Asana task.
I've tested the PR modifying the `release_report_error.yml` workflow and triggering it. [This](https://app.asana.com/0/414730916066338/1209164067982381/f) is a test task that was created.
> Add PS analysis workflow

- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/1157893581871903/1209111051208753/f
Translations for Duck.AI
> Translations for Chat

- app/src/main/java/com/duckduckgo/app/browser/apppersonality/AppPersonalityFeature.kt
Task/Issue URL: https://app.asana.com/0/0/1209204421122114/f
Added feature flags for app personality feature.
Code review only.
> Add feature flag to enable / disable the Tracker Blocking Animation

- app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
Task/Issue URL: https://app.asana.com/0/1200905986587319/1209217680221694/f
Cancelled the coroutine scope when the view is detached.
Code review.
> Trackers blocked animations and cookies animations playing inconsistently

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/settings/InvalidateV2TokensView.kt
Task/Issue URL: https://app.asana.com/0/1205648422731273/1209230625930643/f
See task.
See task.
> Handle correct HTTP status code when refreshing v2 token fails

- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1209200821186635/f 
QA optional but if you want to….
Fixes https://github.com/duckduckgo/Android/issues/5499
> Add WebView compatibility check before launching GPM in dev settings

- .github/workflows/ps-review-analysis.yml
Task/Issue URL: https://app.asana.com/0/1198194956794324/1209235567837627/f
Fix scheduled runs the ps-analysis GHA
Code review
> Fix schedule runs for PS analysis

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1209239539307487/f
> Update reference tests to version 1737732449

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/FakeSubscriptionsDataStore.kt
Task/Issue URL: https://app.asana.com/0/1205648422731273/1209247061971056/f
This PR adds two pixels to monitor potential issues with validating or storing auth v2 tokens.
QA-optional
> Add pixels to monitor v2 token validation and store errors

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/1205008441501016/1209225018365506/f 
No QA needed, not easy to reproduce
> Fix NPE in onUserSubmittedQuery

- app/src/main/java/com/duckduckgo/app/browser/menu/BrowserPopupMenu.kt
- app/src/main/java/com/duckduckgo/app/downloads/DownloadsAdapter.kt
- app/src/main/res/values/dimens.xml
- common/common-ui/src/main/java/com/duckduckgo/common/ui/menu/PopupMenu.kt
- common/common-ui/src/main/res/values/design-system-dimensions.xml
- saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksActivity.kt
- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncedDevicesAdapter.kt
Task/Issue URL: https://app.asana.com/0/inbox/1157893581871899/1209241492038549/1209247138084841
This PR fixes the non showing of the PopupMenu, by ensuring there’s a default width. 
_Test trailing icons in_
> Fix PopupMenu width

- app/src/androidTest/resources/reference_tests/domain_matching_tests.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1209277179409140/f 
----- 
> Update reference tests to version 1738159777

- app/src/main/res/layout/view_menu_item_default_browser.xml
- app/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/1208671518894266/1209289799103141/f
> Additional "default browser" prompts: copy updates

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/1209268903907280/1209268903907280
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.2.0
Updates Autofill to version [16.2.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.2.0).
* [Matching] Update regex to match for 'confirm password' by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/719
* Update password-related json files (2025-01-06) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/730
* [FormAnalyzer] Use conservative regex for attributes by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/735
* [FormAnalyzer] Don't flip scores on buttons with specific text by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/725 …
> Update autofill to 16.2.0

- node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1209314797124477/f 
----- 
> Update content scope scripts to version 7.13.0

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
Task/Issue URL: https://app.asana.com/0/0/1209302824452673/f 
_Feature 1_
_Feature 1_
_Feature 1_
_Feature 1_
> Close custom tab on leave site

- .github/workflows/release_nightly.yml
Task/Issue URL: https://app.asana.com/0/414730916066338/1209333922482831 
_Feature 1_
> Fix duplicate env definition

- app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
Task/Issue URL: https://app.asana.com/0/1198194956794324/1209332000250207
Remove unused FF
> Remove unused optimizeTrackerEvaluation FF

- app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/1201807753394693/1209308870570409
Translations for highlight copy changes
_Translations_
_Onboarding copy_
- Tap on "Let's do it"
- Tap on "Choose Your Browser" (doesn't matter if you set DDG as default or not)
- Tap on "Next"
- Go to any website
- Dismiss Trackers Dialog
> Instantly clear your browsing activity with the Fire Button.
>
> Give it a try! 🔥
- Tap on `Skip` button
- Check end dialog primary button copy is `High five!`
> Highlights onboarding copy changes & translations

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerService.kt
- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/WireguardHandshakeMonitor.kt
- network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/NetPInternalSettingsActivity.kt
- network-protection/network-protection-internal/src/main/res/layout/activity_netp_internal_settings.xml
- network-protection/network-protection-internal/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1209389726956604
smoke test enabling VPN on a few devices and emulator
> Revert "Make sure UnprotectedVpnControllerService requests go outside the VPN tunnel (#5635)"

- scripts/piranha/README.md
- scripts/piranha/clean.py
- scripts/piranha/configurations/rules.toml
- scripts/piranha/requirements.txt
Task/Issue URL: https://app.asana.com/0/488551667048375/1209355305106376
Toll to flean up staled feature flags
_Test_
> Feature flag debt cleaner

- autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
- autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
- autofill/autofill-internal/src/main/res/values/donottranslate.xml
- common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/ActivityExtensions.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1209397886769939 
Introduce a quick access to system settings from our internal Autofill Setting
_Feature 1_
> Autofill system setting, internal quick access

- autofill/autofill-impl/src/main/res/xml/service_configuration.xml
Task/Issue URL: https://app.asana.com/0/1200156640058969/1209399093019367 
Declare and enable compatibility mode with browsers for better experience
_Feature 1_
> enable compatibility mode in autofill service

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillSimpleCredentialsListFragment.kt
Task/Issue URL: https://app.asana.com/0/1200156640058969/1209408434408905
Focus search bar when user access the screen from Search Password Suggestion
_Feature 1_
> Focus search bar when user accesses Search Passwords screen

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1209428714920155/f 
----- 
> Update reference tests to version 1739774089

- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.css
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/bg/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/cs/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/da/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/de/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/el/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/en/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/es/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/et/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/fi/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/fr/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/hr/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/hu/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/it/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/lt/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/lv/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/nb/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/nl/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/pl/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/pt/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/ro/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/ru/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/sk/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/sl/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/sv/duckplayer.json
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/tr/duckplayer.json
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1209461511113841/f 
----- 
> Update content scope scripts to version 7.20.0

- app/src/test/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1209489004733339
Add missing test in AboutDuckDuckGoViewModelTest
Verify that the test coverage has increases
| Before  | 
After
> Add missing test in AboutDuckDuckGoViewModelTest

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillServiceSuggestionCredentialFormatter.kt
- autofill/autofill-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/1142021229838617/1209495490720437 
Updates copy for DDG app entry point (Autofill service suggestion)
_Feature 1_
> Update Autofill suggestion quick access copy

- app/src/main/java/com/duckduckgo/app/tabs/TabSwitcherAnimationFeature.kt
Task/Issue URL: https://app.asana.com/0/1207908166761516/1209367716237175
Introduces a new remote feature toggle for tab switcher animation functionality. The feature is disabled by default and can be controlled remotely through the `tabSwitcherAnimation` feature flag.
_Feature Toggle Implementation_
No UI changes in this PR.
> Tab Switcher Animation: Introduce TabSwitcherAnimation feature toggle

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/freetrial/FreeTrialExperimentDataStore.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/freetrial/FreeTrialPrivacyProMetricsPixelPlugin.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/freetrial/FreeTrialPrivacyProPixelsPluginTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt
> Free Trials: Experiment pixel metrics

- app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
- app/src/main/java/com/duckduckgo/app/launch/LaunchBridgeActivity.kt
- app/src/main/java/com/duckduckgo/app/launch/LaunchViewModel.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/test/java/com/duckduckgo/app/launch/LaunchViewModelTest.kt
- common/common-ui/src/main/res/drawable-night/splash_screen_wink.xml
- common/common-ui/src/main/res/drawable/splash_screen_wink.xml
- common/common-ui/src/main/res/values-v32/design-system-theming.xml
- common/common-ui/src/main/res/values-v33/design-system-theming.xml
- common/common-ui/src/main/res/values/design-system-theming.xml
Task URL: https://app.asana.com/0/488551667048375/1209483504518112
We removed the splashscreen animation while investigating issues due to a user report of a black screen when launching. This reverts that removal and will be a feature branch for adding upcoming mitigations to reduce chances of this happening.
> Revert "SplashScreen Animation: Add wink animation (#5565)" removal

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillProviderSuggestions.kt
Task/Issue URL: https://app.asana.com/0/1200156640058969/1209226370597334 
Signal autofill Ids not classified to be ignored
(optional) just smoke test the feature
> ignore views not classified from autofilling

- autofill/autofill-impl/build.gradle
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillServiceExceptions.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillServiceFeature.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/RealAutofillService.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/store/AutofillFeatureRepository.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/store/AutofillServiceDatabase.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/store/AutofillServiceExceptionsStore.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/store/AutofillServiceModule.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/store/ExceptionsDao.kt
Task/Issue URL: https://app.asana.com/0/1200156640058969/1209552039022764 
Adds support to remote exceptions if any
_Feature 1_
> Autofill Service: Adds support to remote exceptions

- malicious-site-protection/malicious-site-protection-impl/build.gradle
- malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionRCFeature.kt
- malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/RealMaliciousSiteProtectionRCFeatureTest.kt
Task/Issue URL: https://app.asana.com/0/0/1209560625119542/f 
Disable MSP in F-Droid builds 
_Feature 1_
---
- https://app.asana.com/0/0/1209568836821773
> Disable MSP in F-Droid builds

- app/src/main/java/com/duckduckgo/app/settings/NewSettingsActivity.kt
Task/Issue URL: https://app.asana.com/0/1201048563534612/1209582795212674
- Go to the settings page and click "DuckDuckGo on Other Platforms" and verify that the page loads correctly.
> Update "other platforms" URL

- di/src/main/java/dagger/android/AndroidInjector.kt
Task/Issue URL: https://app.asana.com/0/1198194956794324/1209647530372570
Remove unused code related to BackupAgentHelper dagger inject
NA just removing unused code
> Remove BackupAgentHelper inject method

- pir/pir-internal/build.gradle
- pir/pir-internal/schemas/com.duckduckgo.pir.internal.store.PirDatabase/2.json
- pir/pir-internal/src/main/AndroidManifest.xml
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/component/PirActionsRunner.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/component/PirActionsRunnerFactory.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/component/PirDetachedWebViewProvider.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/di/PirModule.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scan/BrokerStepsParser.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scan/PirForegroundScanService.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scan/PirScan.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scripts/BrokerActionProcessor.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scripts/PirCssScriptLoader.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scripts/PirMessagingInterface.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/service/PirForegroundScanService.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/service/PirRemoteWorkerService.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/service/PirScheduledScanWorker.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/service/PirSupportedBrokers.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirDevSettingsActivity.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirResultsActivity.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/store/PirDatabase.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/store/PirRepository.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/store/db/UserProfileDao.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/store/db/UserProfileEntities.kt
- pir/pir-internal/src/main/res/layout/activity_pir_internal_results.xml
- pir/pir-internal/src/main/res/layout/activity_pir_internal_settings.xml
- pir/pir-internal/src/main/res/values/donottranslate.xml
Task/Issue URL: Implement debug UI + store profile  
See attached description
https://app.asana.com/0/1201462763415876/1209580146536605
> Implement debug UI + store profile

- app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt
- app/src/main/res/layout/view_fade_omnibar_bottom.xml
Addresses:
- https://github.com/duckduckgo/Android/pull/5780#discussion_r1998740754
- https://github.com/duckduckgo/Android/pull/5780#discussion_r1998742017
> minor fixes for "improve omnibar-minibar transition"

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt
- app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockerWebViewIntegration.kt
- app/src/test/java/com/duckduckgo/app/browser/webview/RealMaliciousSiteBlockerWebViewIntegrationTest.kt
- malicious-site-protection/malicious-site-protection-api/src/main/kotlin/com/duckduckgo/malicioussiteprotection/api/MaliciousSiteProtection.kt
- malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/MaliciousSiteRepository.kt
- malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/domain/RealMaliciousSiteProtection.kt
- malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/models/MaliciousSiteProtectionDataModels.kt
- malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/RealMaliciousSiteRepositoryTest.kt
- malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/domain/RealMaliciousSiteProtectionTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1209678802700350?focus=true 
Fix regression in spoofing tests. Only execute the "Safe" logic if the previous site was malicious
_Feature 1_
> Fix broken spoofing test

- app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockerWebViewIntegration.kt
Task/Issue URL: https://app.asana.com/0/0/1209714809028807 
FF onPageLoadStarted for MaliciousSiteBlockerWebViewIntegration for extra safety
n/a
n/a
> FF onPageLoadStarted

- node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1209720531816277/f 
----- 
> Update content scope scripts to version 8.0.0

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/1200581511062568/1209643930390968
Translations.
N/A
> Updated string.

- node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1209734912649825/f 
----- 
> Update content scope scripts to version 8.3.0

- node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
> Update content scope scripts to version 8.9.0

- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1209132189739314/f
This PR adds the pixels and unit tests for the multi-selection feature.
Here are the test instructions for each of the specified pixels:
1. **m_tab_manager_new_tab_click**:
2. **m_tab_manager_menu**:
3. **m_tab_manager_menu_new_tab**:
4. **m_tab_manager_menu_close_all_tabs** and **m_tab_manager_menu_close_all_tabs_confirm**:
5. **m_tab_manager_select_mode_menu_close_tabs** and **m_tab_manager_confirm_close_tabs**:
6. **m_tab_manager_select_mode_menu_close_other_tabs**:
7. **m_tab_manager_menu_select_tabs**:
8. **m_tab_manager_select_mode_menu_clicked**:
9. **m_tab_manager_tab_selected** and **m_tab_manager_tab_deselected**:
10. **m_tab_manager_close_tabs**:
11. **m_tab_manager_select_mode_menu_select_all** and …
> Multi-selection: Pixels

- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
- app/src/test/java/com/duckduckgo/tabs/db/TabsDaoTest.kt
- app/src/test/java/com/duckduckgo/tabs/model/TabDataRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1209118961868656/f
This PR adds new unit tests for the new functionality and updates the existing ones to reflect the changed behavior.
Make sure all tests are green.
> Multi-selection: Tests

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelParamRemovalPlugin.kt
Task/Issue URL: https://app.asana.com/0/1205617573940217/1209736878587863/f
This PR removes the ATB parameter from pixels related to monitoring authentication errors.
See task
> Remove ATB from auth-related pixels

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/settings/SettingsPixelDispatcher.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/settings/SettingsPixelDispatcherTest.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
- duckchat/duckchat-impl/src/main/AndroidManifest.xml
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/di/DuckChatDataStoreModule.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/feature/AIChatDownloadFeature.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/feature/DuckChatFeature.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/helper/DuckChatJSHelper.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/pixel/DuckChatPixels.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/repository/DuckChatFeatureRepository.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/store/DuckChatDataStore.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsActivity.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsViewModel.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewActivity.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewClient.kt
- duckchat/duckchat-impl/src/main/res/layout/activity_duck_chat_settings.xml
- duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt
- duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/helper/RealDuckChatJSHelperTest.kt
- duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/repository/DuckChatFeatureRepositoryTest.kt
- duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/store/SharedPreferencesDuckChatDataStoreTest.kt
- duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsViewModelTest.kt
- duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewClientTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1209880305397052/f
- Moves code into corresponding packages in `duckchat` module.
> Reorganize duckchat module

- .github/workflows/action-issue-opened.yaml
- .github/workflows/action-pr-merged.yaml
- .github/workflows/action-pr-opened.yaml
- .github/workflows/custom-tabs-nightly.yml
- .github/workflows/e2e-nightly-autofill.yml
- .github/workflows/pr-review-notifications.yaml
- .github/workflows/ps-review-analysis.yml
- .github/workflows/release_create_tag.yml
- .github/workflows/release_create_task.yml
- .github/workflows/release_nightly.yml
- .github/workflows/release_tests.yml
- .github/workflows/release_update_release_notes.yml
- .github/workflows/release_upload_play_store.yml
- .github/workflows/sync-critical-path.yml
- .github/workflows/update-content-scope.yml
- .github/workflows/update-ref-tests.yml
Task/Issue URL: https://app.asana.com/0/1209289464394287/1209893022340538/f
This PR updates all uses of the GHA to the latest version.
> GHA: Update to latest version

- .maestro/privacy_tests/6_-_Multi-tab.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1209887205055754/f
- Removes step no longer needed due to tab switcher changes.
> Fix multi-tab Maestro test

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1209900729045449/f 
----- 
> Update reference tests to version 1743747763

- sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt
- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncAccountRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/1149059203486286/1209909263379242/f 
Adds a guard against malformed json when polling connection
N/A
> Sync: guard against malformed json when polling

- anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
- autoconsent/autoconsent-impl/build.gradle
- autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/ui/AutoconsentSettingsViewModelTest.kt
- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1209892744822627/f
Add Togle#getExceptions(). Exceptions will be available for both parent and sub-features
QA-optional, added e2e tests that verify remote config updates.
Alternatively, use the dev settings to pass exceptions in some feature/sub-feature and see it's available via getExceptions
> getExceptions for features and sub-features

- app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockerWebViewIntegration.kt
- malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/MaliciousSiteRepository.kt
- malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/db/MaliciousSiteDao.kt
- malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/domain/RealMaliciousSiteProtection.kt
- malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/models/MaliciousSiteProtectionDataModels.kt
- malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/RealMaliciousSiteRepositoryTest.kt
- malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/db/MaliciousSiteDaoTest.kt
- malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/domain/RealMaliciousSiteProtectionTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1209921604835831/f 
* Optimize db operations
* Define dispatchers for suspend functions
* Optimize hash generation
* Don't block read operations if write is in progress
* Reduce the number of times URI is converted to String 
_Feature 1_
_Feature 2_
> Address ANR on isMalicious

- node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1209957566599335/f 
----- 
> Update content scope scripts to version 8.14.0

- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/webview/WebViewActivity.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1209956357445578
- Removing these pixels as they are no longer needed.
> Remove m_dedicated_webview* pixels

- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirRunStateHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/pixels/PirPixelSender.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/45878998844068/task/1209960031709338
Remove recordId as we don't need it.
QA-optional
> PIR/Internal: Remove recordId from pixels

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/integration/NetPStateCollector.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1209948991762148?focus=true
Separates values for subscriptionState to isActive and hasVpnEntitlement
https://app.asana.com/1/137249556945/task/1209959086486425?focus=true
> Improve feedback metadata for VPN

- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirActionsRunner.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirDetachedWebViewProvider.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirJobConstants.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirUtils.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/optout/PirOptOut.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scan/PirScan.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scan/PirScheduledScanWorker.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirDevScanActivity.kt
- pir/pir-internal/src/main/res/layout/activity_pir_internal_scan.xml
- pir/pir-internal/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1209907364560297/f
- Fail fast when loaded urls fail
- Restart js script when failure occur
- Increase parallel runs to max 15
- Trim input to avoid testing mistakes
More: See attached description
https://app.asana.com/0/488551667048375/1209907364560297/f
> PIR/Internal: Improve handling for load failures

- .github/workflows/action-issue-opened.yaml
- .github/workflows/action-pr-merged.yaml
- .github/workflows/action-pr-opened.yaml
- .github/workflows/custom-tabs-nightly.yml
- .github/workflows/e2e-nightly-autofill.yml
- .github/workflows/pr-review-notifications.yaml
- .github/workflows/ps-review-analysis.yml
- .github/workflows/release_create_tag.yml
- .github/workflows/release_create_task.yml
- .github/workflows/release_nightly.yml
- .github/workflows/release_tests.yml
- .github/workflows/release_update_release_notes.yml
- .github/workflows/release_upload_play_store.yml
- .github/workflows/sync-critical-path.yml
- .github/workflows/update-content-scope.yml
- .github/workflows/update-ref-tests.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1209976423514820?focus=true
Update GHA to latest version to support new Asana URL format
> GHA: Update Asana Sync to 1.8

- build.gradle
Task/Issue URL: https://app.asana.com/1/137249556945/project/414730916066338/task/1209979907476102?focus=true 
Use new recommended device. Pixel 3 is deprecated (and seems to have been removed)
_Feature 1_
> Fix: pixel3 is deprecated (replace with recommended device)

- app/src/main/res/layout/view_indonesia_new_tab_section.xml
- app/src/main/res/layout/view_new_tab_legacy.xml
- saved-sites/saved-sites-impl/src/main/res/layout/view_new_tab_favourites_section.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1174433894299346/task/1209989364538199?focus=true
This PR fixes the padding and clip issues from the new tab favourites grid list. 
Check task for more details
> Visual design: New Tab Page

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1200581511062568/task/1209980207851048?focus=true
Moved onboarding-related string resources from `donottranslate.xml` to `strings.xml` to make them translatable. 
Lint passes.
---
- https://app.asana.com/0/0/1209991870686125
> Translations.

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingView.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1209874163042986?focus=true
Add origin when paywall is opened from settings screen
> Update origins to new format

- common/common-ui/src/main/res/drawable/bottom_nav_fire_button_foreground.xml
- common/common-ui/src/main/res/drawable/selectable_item_experimental_background.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1157893581871903/task/1210010583570039
This PR updates the touch feedback to the new specs
> Visual deisgn: Omnibar touch feedback

- app/src/main/res/layout/view_fade_omnibar.xml
- common/common-ui/src/main/res/drawable/ic_close_24_secondary.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1157893581871903/task/1210010583570047?focus=true
Update clear icon in omnibar to use secondary color
> Visual design: Secondary color for clear icon in Omnibar

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/res/values-fr/strings.xml
- duckchat/duckchat-impl/src/main/res/values-bg/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-cs/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-da/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-de/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-el/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-es/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-et/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-fi/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-fr/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-hr/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-hu/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-it/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-lt/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-lv/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-nb/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-nl/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-pl/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-pt/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-ro/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-ru/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-sk/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-sl/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-sv/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-tr/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values/strings-duckchat.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1210055352874003?focus=true
- Translations for https://github.com/duckduckgo/Android/pull/5692
> Translate Show Duck.ai in Address Bar

- app/src/main/res/layout/view_browser_navigation_bar.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210044827862245?focus=true
Adjusts icon scale type.
> fix nav bar icon scaling

- .github/workflows/action-issue-opened.yaml
- .github/workflows/action-pr-merged.yaml
- .github/workflows/action-pr-opened.yaml
- .github/workflows/ads-end-to-end.yml
- .github/workflows/build-ad-hoc.yml
- .github/workflows/build-fdroid-apk.yml
- .github/workflows/custom-tabs-nightly.yml
- .github/workflows/e2e-nightly-autofill.yml
- .github/workflows/end-to-end-robintest.yml
- .github/workflows/nightly.yml
- .github/workflows/pr-review-notifications.yaml
- .github/workflows/privacy.yml
- .github/workflows/ps-review-analysis.yml
- .github/workflows/release_create_tag.yml
- .github/workflows/release_create_task.yml
- .github/workflows/release_nightly.yml
- .github/workflows/release_production.yml
- .github/workflows/release_report_error.yml
- .github/workflows/release_tests.yml
- .github/workflows/release_update_release_notes.yml
- .github/workflows/release_upload_play_store.yml
- .github/workflows/sync-critical-path.yml
- .github/workflows/update-content-scope.yml
- .github/workflows/update-ref-tests.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1145118180374825/task/1207025544169944?focus=true
_Feature 1_
> Use Asana token org secret instead of repo secret.

- malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/network/MaliciousSiteDatasetService.kt
- malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/network/MaliciousSiteService.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205008441501016/task/1210034340140266?focus=true 
Update endpoints for consistency with other platforms, although there's no technical difference
n/a
> Update MSP endpoints to v2

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1210077403129559/f 
----- 
> Update reference tests to version 1745528586

- app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt
- app/src/main/res/layout/view_fade_omnibar.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210078584031841?focus=true
Fixes an issue where the find in page layout was obstructed by the Custom Tab page title layout.
> fix an issue where find in page was invisible in Custom Tab

- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillFeature.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/L2DataTransformer.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/SecureStorage.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/SecureStorageDatabaseFactory.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/SecureStorageKeyProvider.kt
- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/di/SecureStorageModule.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/securestorage/Fakes.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/securestorage/RealL2DataTransformerTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/securestorage/RealSecureStorageKeyProviderTest.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/securestorage/RealSecureStorageTest.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageKeyRepository.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/keys/SecureStorageKeyStore.kt
- autofill/autofill-store/src/test/java/com.duckduckgo.autofill.store/RealSecureStorageKeyRepositoryTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210067151874996?focus=true
* Smoke test autofill
_Feature 1_
> FF removing synchronized implementations for encrypted shared preferences

- broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSitePomptDataStore.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210111594589774?focus=true
_Feature 1_
> Fix broken site prompt

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205008441501016/task/1209908507294162?focus=true 
Wait for https://dashboard.smartling.com/app/projects/b01b53ede/account-jobs/b01b53ede:nwwveffcmesp to finish
_Feature 1_
> Submit maliciousSiteScamHeadline for translation

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210004588627880?focus=true
Fixes an issue with the omnibar not showing up when scrolling up by ensuring we always expand it when top of the page is reached. Details in the task.
You can also try scrolling up slowly and check for any jitter - should be none. However, if you creep up very very slowly to the top of the page, without flinging and without allowing the omnibar to expand, it won't automatically expand to prevent it being misinterpreted as a gesture in the opposite direction and causing unintended content shift.
> always expand the omnibar when top of the page is reached

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/encryption/EncryptionHelper.kt
- autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/securestorage/Fakes.kt
- autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/keys/SecureStorageKeyStore.kt
Task/Issue URL: https://app.asana.com/1/137249556945/task/1210112602367622?focus=true 
Use mutex instead of synchronized in encrypt/decrypt to prevent thread starvation
_Feature 1_
> FF remove synchronized from EncryptionHelper

- app/src/androidTest/java/com/duckduckgo/espresso/JsObjectIdlingResource.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/GpcTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/414730916066338/task/1210052596373218?focus=true
PoC, don't merge at all.
_Feature 1_
> Check for definition presence in privacy test pages

- node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- package-lock.json
- package.json
> Update content scope scripts to version 8.18.0

- app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
- app/src/androidTest/java/com/duckduckgo/espresso/privacy/GpcTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210159559557010?focus=true
This PR temporarily disables some privacy tests.
Verify all tests pass.
> Fix: Disable failing privacy tests

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1210181457241426/f 
----- 
> Update reference tests to version 1746537866

- app/src/androidTest/java/com/duckduckgo/app/browser/favicon/FileBasedFaviconPersisterTest.kt
- app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
- app/src/main/java/com/duckduckgo/app/browser/favicon/FaviconPersister.kt
- app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210122551240113?focus=true
> FF suspend version of writing favicon to disk

- app/src/main/res/layout/view_fade_omnibar.xml
- common/common-ui/src/main/res/drawable/ic_arrow_left_small_24.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1174433894299346/task/1210056293401143
Update back arrow as small icon
| New  | Old |
|![Screenshot_20250506_171621](https://github.com/user-attachments/assets/eb440caa-c9b5-4a27-9c06-aa7e0bc0529e)|![Screenshot_20250506_172238](https://github.com/user-attachments/assets/76f0f056-56e1-4831-bd33-8ea17008c788)|
|![Screenshot_20250506_171643](https://github.com/user-attachments/assets/7efd1d02-6c9b-4913-99d4-60448f743a18)|![Screenshot_20250506_172228](https://github.com/user-attachments/assets/0074e1e0-77e8-43ef-a8aa-2729a1050298)|
> Visual design: small icon version in omnibar

- app/src/main/java/com/duckduckgo/app/browser/omnibar/TopAppBarBehavior.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/view/ViewExtension.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1209909977029784?focus=true
This PR fixes the wrong position of the snackbar in both prod and visual design world
|![Screenshot_20250507_155154](https://github.com/user-attachments/assets/bf1a064b-23df-48cc-807f-63e26fc8d96e)|![Screenshot_20250507_172650](https://github.com/user-attachments/assets/d6b5e1b6-5919-4b8f-adaf-7bf62b9600b1)|
|![Screenshot_20250507_155105](https://github.com/user-attachments/assets/963e5397-4fd2-4bf5-aa37-4ed4e216ddc4)|![Screenshot_20250507_172901](https://github.com/user-attachments/assets/47ea5405-0f33-4220-b170-e7b835fed19a)|
> Visual design: snackbar

- app/src/main/res/layout/activity_tab_switcher.xml
- common/common-ui/src/main/res/color/fab_primary_ripple_selector.xml
- common/common-ui/src/main/res/color/fab_secondary_ripple_selector.xml
- common/common-ui/src/main/res/drawable/ic_ai_chat_24_solid_color.xml
- common/common-ui/src/main/res/values/design-system-colors.xml
- common/common-ui/src/main/res/values/design-system-theming.xml
- common/common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210044097895977?focus=true
This PR updates the secondary FAB light & dark color background and icon colors and fixes the primary and secondary pressed background colors
https://github.com/user-attachments/assets/51a25bd3-cd7a-47a1-9c4b-eaf370305c61
> Visual update: Update FAB colors

- app/src/main/res/layout/view_fade_omnibar.xml
- common/common-ui/src/main/res/drawable/ic_close_24_secondary.xml
- common/common-ui/src/main/res/drawable/ic_close_circle_small_secondary_24.xml
- common/common-ui/src/main/res/values/design-experiments-colors.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1174433894299346/task/1210184414984705?focus=true
Theme colors updated for May. Design review in main task
> Visual design: May colors

- app/src/main/res/layout/item_autocomplete_default.xml
- app/src/main/res/layout/item_autocomplete_search_suggestion.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210198169211629?focus=true
This PR updates the tap background of the autocomplete item button to match the design.
https://github.com/user-attachments/assets/302326a6-1499-4499-be21-1723be1d4f18
> Visual update: Update the autocomplete item button background

- feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210218578062547?focus=true
Check minSupportedVersion and remote feature flag state before assigning cohort.
Cohort is only assign if:
* min supported version matches AND
* feature remote state is enabled (this includes state=`internal`)
New 2e2 tests should pass.
> Check minSupportedVersion and remote enable state before assigning cohort

- common/common-ui/src/main/res/drawable/ic_arrow_left_24.xml
- common/common-ui/src/main/res/drawable/ic_arrow_right_24.xml
- common/common-ui/src/main/res/drawable/text_cursor.xml
- common/common-ui/src/main/res/layout/view_dax_text_input.xml
- common/common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1174433894299346/task/1210223529532768?focus=true
This PR adds the latest changes asked in the design review
> Visual Designs: Review II

- .github/workflows/privacy.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210230564880352?focus=true
Removes labeled rule from workflow (privacy test)
N/A
> removes labeled rule from workflow (privacy test)

- sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModelTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210249296938447?focus=true
Fixes a failing test.
Make sure all checks are green.
> Fix the failing unit test in EnterCodeViewModelTest

- app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/FragmentStateAdapter.java
- app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/FragmentViewHolder.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/tabs/SwipingTabsFeature.kt
- common/common-ui/src/main/java/com/duckduckgo/common/ui/tabs/SwipingTabsFeatureProvider.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210187246401089?focus=true
This PR removes unused fixes and the associated feature flags.
---
- https://app.asana.com/0/0/1208271988740971
> Tab swiping: Clean up unused fixes behind feature flags

- .maestro/autofill/2_autofill_add_search_update_delete_creds.yaml
- .maestro/autofill/4_autofill_settings_creds.yaml
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210251123773109?focus=true 
Update Maestro Autofill E2E workflows
Should pass https://github.com/duckduckgo/Android/actions/runs/15025185850
> Update Maestro E2E tests Autofill

- app/src/main/res/layout/view_fade_omnibar.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210250712494534?focus=true
Aligns shield's pulsating circle.
> align shield's pulsating circle

- app/src/main/java/com/duckduckgo/app/browser/navigation/bar/BrowserNavigationBarViewIntegration.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210267290350843?focus=true
When opening the new tab page, we initial don't show the keyboard. This scheduled a delayed task to execute and show the navigation bar. Before the time elapses to run the task, we automatically show the keyboard and focus on the omnibar, which hides the nav bar. However, the initially scheduled task would eventually execute and re-show the navigation bar even though the keyboard was also already visible.
The fix is to cancel the delayed task to show the navigation bar whenever the keyboard state changes.
> fix an issue where nav bar would stay visible together with the keyboard when NTP was opened

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/blocklist/AppTrackerListUpdateWorker.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
- app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/VpnAppTrackerBlockingDao.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202096681738622/task/1210212720766789?focus=true
Ditto
> Add AppTP blocklist stat pixel

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/mapper/RemoteDomainTargetAppDataDownloader.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1149059203486286/task/1210344745720537?focus=true 
Fixes ANR when checking FF in main thread
N/A
> Fix ANR produced in RemoteDomainTargetAppDataDownloader

- feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorBucketAssignmentTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1207989251288356?focus=true 
_Feature 1_
> ContributesRemoteFeatureCodeGeneratorBucketAssignmentTest can be flakey; add logs for when it next fails

- .maestro/ads_preview_flows/1-_design-system-components.yaml
- .maestro/custom_tabs/custom_tabs_navigation.yaml
- .maestro/custom_tabs/custom_tabs_navigation_new_tab.yaml
- .maestro/shared/open_bookmarks.yaml
- .maestro/shared/open_sync_dev_settings_screen.yaml
- .maestro/shared/open_sync_screen.yaml
- app/src/main/res/layout/view_browser_navigation_bar.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210381345437646?focus=true
Adapts the code and E2E test suite that relies on internal builds to execute correctly with the new visual design.
> make e2e tests that run on internal builds compatible with new visual design

- app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210381575256073?focus=true
Remove setSession temporarily as we are not sure if it could negatively effect VPN on other OEMs
Qa-optional
> Remove setSession from VPNService

- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirActionsRunner.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/BrokerCompletedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/CaptchaInforReceivedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/EmailConfirmationLinkReceivedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/EmailReceivedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/EventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/ExecuteNextBrokerActionEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/ExecuteNextBrokerEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/ExecuteNextProfileForBrokerEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/JsActionFailedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/JsActionSuccessEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/LoadUrlCompleteEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/LoadUrlFailedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/PirActionsRunnerStateEngine.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/PirActionsRunnerStateEngineFactory.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/RealPirActionsRunnerStateEngine.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/RetryAwaitCaptchaSolutionEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/RetryGetCaptchaSolutionEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/StartedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/di/PirModule.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scan/PirScan.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirDevScanActivity.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/store/PirRepository.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/store/db/ScanLogDao.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201462763415876/task/1210261934912353?focus=true
https://app.asana.com/1/137249556945/project/1201462763415876/task/1210170762644463?focus=true
> Break down PirActionRunner to make it readable

- dax-prompts/dax-prompts-impl/src/main/java/com/duckduckgo/daxprompts/impl/ReactivateUsersToggles.kt
Task/Issue URL: https://app.asana.com/1/137249556945/task/1210391900429638?focus=true
Updated cohort names in `ReactivateUsersToggles.kt` to use camelCase format:
- Changed `duckplayer_prompt` to `duckplayerPrompt`
- Changed `browser_prompt` to `browserPrompt`
_Cohort naming_
---
- https://app.asana.com/0/0/1210391900429638
> Renamed cohorts for experiment reactivateUsersExperimentMay25.

- node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1210396173758884/f 
----- 
> Update content scope scripts to version 9.0.0

- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/BrokerStepsParser.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/EmailReceivedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/ExecuteNextBrokerActionEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scripts/models/PirScriptProfile.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scripts/models/PirScriptResponseParams.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirDevScanActivity.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirResultsActivity.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/store/PirRepository.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210386349388281?focus=true
https://app.asana.com/1/137249556945/task/1210437341069871?focus=true
> PIR: User Extract actionr response instead of meta

- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/helper/DuckChatJSHelper.kt
- duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt
- duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/helper/RealDuckChatJSHelperTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210498773096178?focus=true
- Disables native experimental omnibar on the Duck.ai WebView.
> Disable native omnibar on Duck.ai WebView

- .github/workflows/release_upload_play_store.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210449274691654?focus=true 
NO QA
https://github.com/duckduckgo/Android/actions/runs/15415195433 should complete
> GHA: Fix duplicate id for messaging

- .github/workflows/test_workflow.yml
- .github/workflows/validate_workflows.yml
- .github/workflows/validate_wortkflows.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1157893581871903/task/1210508233008771?focus=true
This PR adds a new workflow that validates if any changes were made to workflows and runs actionlint to them
> GHA: Lint workflows

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201807753394693/task/1210376609028447?focus=true
Update copy in comparison chart
> Onboarding: Comparison Chart copy update

- duckchat/duckchat-impl/src/main/res/drawable/tab_indicator.xml
- duckchat/duckchat-impl/src/main/res/drawable/tab_layout_background.xml
- duckchat/duckchat-impl/src/main/res/layout/activity_search_interstitial.xml
- duckchat/duckchat-impl/src/main/res/layout/view_duck_chat_omnibar.xml
- duckchat/duckchat-impl/src/main/res/values/styles.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1210535569818733?focus=true
- Updates the mode switcher UI
> Update interstitial mode switcher

- versions.properties
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210513464852529?focus=true
Following the PR in https://github.com/duckduckgo/netguard/pull/39, update the networking library to the 1.9.0
Smoke test the VPN
> Update ddg networking library to 1.9.0

- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/navigation/AppBrowserNav.kt
- app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- browser-api/src/main/java/com/duckduckgo/app/tabs/BrowserNav.kt
- duckchat/duckchat-api/src/main/java/com/duckduckgo/duckchat/api/DuckChat.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/pixel/DuckChatPixels.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/repository/DuckChatFeatureRepository.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/store/DuckChatDataStore.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewFragment.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewPoCActivity.kt
> skeleton to keep the session alive

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionActivity.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210578937175629?focus=true
> Navigate to /subscriptions/welcome after successfully activating subscription

- node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1210583689812578/f 
----- 
> Update content scope scripts to version 9.9.0

- network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/systemapps/SystemAppsExclusionRepository.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1208416919273982/f
Smoke test VPN - attempt calling  / wifi calling
> Add new apps to system app category exclusion

- duckchat/duckchat-impl/build.gradle
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatOmnibarLayout.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/SearchInterstitialActivity.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/SearchInterstitialFragment.kt
- duckchat/duckchat-impl/src/main/res/layout/activity_search_interstitial.xml
- duckchat/duckchat-impl/src/main/res/layout/fragment_search_interstitial.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210573023021045?focus=true
- Shows favorites in the search interstitial
- Shows the DDG logo when the view is empty
> Show favorites in search interstitial

- .github/workflows/release_nightly.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1198194956794324/task/1210599816763429?focus=true
Remove working directory to fix GHA to create nightly release asana task
NA, just pray
> Remove working-directory to fix nightly GHA issue

- .github/workflows/action-pr-sync.yaml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1209289464394287/task/1208973765774654?focus=true
Remove the label dependency for the sync steps
> GHA: Remove label need for Sync workflow

- .github/workflows/action-issue-opened.yaml
- .github/workflows/action-pr-merged.yaml
- .github/workflows/action-pr-opened.yaml
- .github/workflows/custom-tabs-nightly.yml
- .github/workflows/e2e-nightly-autofill.yml
- .github/workflows/ps-review-analysis.yml
- .github/workflows/release_create_tag.yml
- .github/workflows/release_create_task.yml
- .github/workflows/release_nightly.yml
- .github/workflows/release_tests.yml
- .github/workflows/release_update_release_notes.yml
- .github/workflows/release_upload_play_store.yml
- .github/workflows/sync-critical-path.yml
- .github/workflows/update-content-scope.yml
- .github/workflows/update-ref-tests.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1174433894299346/task/1210540690964476?focus=true
Update Asana task to latest version
> GHA: Update Asana Sync to 2.0

- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirActionsRunner.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/BrokerStepCompletedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/CaptchaInforReceivedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/CaptchaServiceFailedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/EmailFailedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/EmailReceivedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/ExecuteBrokerStepActionEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/ExecuteNextBrokerStepEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/JsActionFailedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/JsActionSuccessEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/JsErrorReceivedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/LoadUrlCompleteEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/PirActionsRunnerStateEngine.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/RealPirActionsRunnerStateEngine.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210510624222698?focus=true
https://app.asana.com/1/137249556945/task/1210591513987829
> PIR: Implement json action retry on failure

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/ui/experiment/OnboardingHomeScreenWidgetExperiment.kt
- app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/ui/experiment/OnboardingHomeScreenWidgetToggles.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
- app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
- app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
- app/src/main/java/com/duckduckgo/app/widget/experiment/PostCtaExperienceExperiment.kt
- app/src/main/java/com/duckduckgo/app/widget/experiment/store/WidgetSearchCountDataStore.kt
- app/src/test/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/ui/experiment/OnboardingHomeScreenWidgetExperimentImplTest.kt
- app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt
- app/src/test/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
- app/src/test/java/com/duckduckgo/widget/experiment/PostCtaExperienceExperimentTest.kt
- app/src/test/java/com/duckduckgo/widget/experiment/store/WidgetSearchCountDataStoreTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1200581511062568/task/1210403485354654?focus=true
Set up experiment for improve prompts for home screen widget. 
See Asana task -> https://app.asana.com/1/137249556945/project/1200581511062568/task/1210403485354654?focus=true
See Asana task -> https://app.asana.com/1/137249556945/project/1200581511062568/task/1210403485354654?focus=true
---
- https://app.asana.com/0/0/1210403485354654
> Experiment set-up: A more recognizable widget prompt

- autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/promo/ImportInPasswordsPromotion.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210614812231762?focus=true 
Adds icon to the CTA button
_Feature 1_
- QA optional
> Add icon to the import promo's CTA button

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
- app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
- app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210657930367705?focus=true
Revert back to the original omnibar content if Duck.ai Input screen query was not submitted.
> do not change address bar content if no query was made in the Duck.ai Input Screen

- autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillFeature.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/608920331025315/task/1210712811013384?focus=true 
Enables the password import promo in management screen by default.
QA optional
> Enable feature for showing password promo in management screen

- node_modules/@duckduckgo/autofill/dist/autofill-debug.js
- node_modules/@duckduckgo/autofill/dist/autofill.js
- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/1/137249556945/task/1210687641368247
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/18.1.0
Updates Autofill to version [18.1.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/18.1.0).
* Feat: enable iOS QuickType by toggling autocomplete on input focus/blur by @borgateo in https://github.com/duckduckgo/duckduckgo-autofill/pull/860
* Fix: add "date" to Skip and add immitracker form to the tests by @borgateo in https://github.com/duckduckgo/duckduckgo-autofill/pull/866
* Chore: Update node and dependencies by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/850
* Chore: Update password-related json files by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/863
* …
> Update autofill to 18.1.0

- common/common-ui/src/main/java/com/duckduckgo/common/ui/experiments/visual/ExperimentalThemingFeature.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210728138839415
This PR makes sure the internal users always see the new visual update UI.
> Visual update: Update feature flag for internal users

- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/autocomplete/AutoCompleteViewState.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenFragment.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/state/InputScreenVisibilityState.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/tabs/SearchTabFragment.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/viewmodel/InputScreenViewModel.kt
- duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenViewModelTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210740194621787?focus=true
Cleans up unused variables and code copied from integration with the browser tab fragment.
> Clean up input screen autocomplete integration

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
- app/src/main/res/layout/view_fade_omnibar.xml
- app/src/main/res/layout/view_single_omnibar.xml
- common/common-ui/src/main/res/anim/overshoot_interpolator_tension_1.xml
- common/common-ui/src/main/res/anim/slide_in_from_bottom_fade_in.xml
- common/common-ui/src/main/res/anim/slide_in_from_top_fade_in.xml
- common/common-ui/src/main/res/anim/slide_out_to_bottom_fade_out.xml
- common/common-ui/src/main/res/anim/slide_out_to_top_fade_out.xml
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenActivity.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/tabs/SearchTabFragment.kt
- duckchat/duckchat-impl/src/main/res/layout/view_input_mode_switch_widget.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210750831271803?focus=true
Updates the Input Screen in/out transitions
> update input screen in/out transitions

- app/src/main/java/com/duckduckgo/app/tabs/TabFeatureFlags.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210728360131191?focus=true
This PR adds a new feature flag and caches its value in the `TabSwitcherViewModel`.
QA-optional
---
- https://app.asana.com/0/0/1210760591708462
> Tab manager update: Add a feature flag

- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenFragment.kt
- duckchat/duckchat-impl/src/main/res/layout/fragment_input_screen.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1210761463003851?focus=true
- Makes the Floating Action Buttons on the Input Screen round.
> Update Input Screen FABs

- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenFragment.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210830942545664?focus=true
- Hides the unimplemented WebRAG button.
> Hide WebRAG button on Duck.ai Input Mode

- .maestro/onboarding/onboarding_dismiss_all_dialogs.yaml
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210845436825540?focus=true
Updated the assertion text in the onboarding maestro test flow to match the updated widget promotion text. Changed from "Try our search widget!" to "Try our Home screen widget!".
Maestro tests should pass.
> Update maestro tests - home screen widget text

- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/view/InputModeWidget.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsActivity.kt
- duckchat/duckchat-impl/src/main/res/layout/activity_duck_chat_settings.xml
- duckchat/duckchat-impl/src/main/res/layout/view_chat_tab_indicator.xml
- duckchat/duckchat-impl/src/main/res/layout/view_input_mode_switch_widget.xml
- duckchat/duckchat-impl/src/main/res/layout/view_search_tab_indicator.xml
- duckchat/duckchat-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210835166205909?focus=true
Updates hints and cleans up unused resources.
> update search and chat input hints

- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/view/InputModeWidget.kt
- duckchat/duckchat-impl/src/main/res/layout/view_input_mode_switch_widget.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210814996510644?focus=true
Enables auto-correct and auto capitalization of new sentences in Chat Mode.
> enable auto-correct feature in Chat Mode

- pir/pir-internal/schemas/com.duckduckgo.pir.internal.store.PirDatabase/4.json
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/BrokerStepsParser.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirActionsRunner.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirRunStateHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/BrokerStepCompletedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/EmailReceivedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/ExecuteBrokerStepActionEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/JsActionSuccessEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/PirActionsRunnerStateEngine.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/PirActionsRunnerStateEngineFactory.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/RealPirActionsRunnerStateEngine.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/StartedEventHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/models/ExtractedProfile.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scripts/models/PirScriptProfile.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scripts/models/PirScriptResponseParams.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirDevScanActivity.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirResultsActivity.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/store/PirDatabase.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/store/PirRepository.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/store/db/ScanResultsDao.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/store/db/ScanResultsEntities.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201462763415876/task/1210822243603918?focus=true 
Implements https://app.asana.com/1/137249556945/project/1201462763415876/task/1210808280474678?focus=true
https://app.asana.com/1/137249556945/project/1201462763415876/task/1210845409422515?focus=true
> PIR: Update ExtractedProfile storage 

- app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/DefaultSnackbar.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
- app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
- app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210830437493077?focus=true
This PR contains the following changes based on the ship review feedback:
- Fixed table layout padding
- Fixed Duck.ai button visibility settings option (Address bar option used now)
- Fixed bottom toolbar snackbar position
_Feature 1_
> Tab manager update: Ship review fixes

- subscriptions/subscriptions-dummy-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionRebrandingFeatureToggleDummy.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201807753394693/task/1210911335127069?focus=true
Added SubscriptionRebrandingFeatureToggleDummy so F-droid builds are fixed
> Fix F-droid build: Added SubscriptionRebrandingFeatureToggleDummy

- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/optout/PirOptOut.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scan/PirScan.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scheduling/PirJobsRunner.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirDevScanActivity.kt
- pir/pir-internal/src/main/res/layout/activity_pir_internal_scan.xml
- pir/pir-internal/src/main/res/values/donottranslate.xml
- pir/pir-internal/src/test/kotlin/com/duckduckgo/pir/internal/optout/RealPirOptOutTest.kt
- pir/pir-internal/src/test/kotlin/com/duckduckgo/pir/internal/scan/RealPirScanTest.kt
- pir/pir-internal/src/test/kotlin/com/duckduckgo/pir/internal/scheduling/RealPirJobsRunnerTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/481882893211075/task/1210919128590032?focus=true 
https://app.asana.com/1/137249556945/project/481882893211075/task/1210919128590035?focus=true
> PIR: Integrate optout to scheduling

- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirDevSettingsActivity.kt
- pir/pir-internal/src/main/res/layout/activity_pir_internal_settings.xml
- pir/pir-internal/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210930214825588?focus=true
> PIR: Add cancel work option to debug screen

- duckchat/duckchat-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210948174591277?focus=true
- Updates the copy for the Input Screen setting.
> Update Input Screen setting copy

- duckchat/duckchat-api/src/main/res/anim-v33/slide_in_from_bottom_fade_in_dark.xml
- duckchat/duckchat-api/src/main/res/anim-v33/slide_in_from_bottom_fade_in_light.xml
- duckchat/duckchat-api/src/main/res/anim-v33/slide_out_to_bottom_fade_out_dark.xml
- duckchat/duckchat-api/src/main/res/anim-v33/slide_out_to_bottom_fade_out_light.xml
- duckchat/duckchat-api/src/main/res/anim-v33/slide_out_to_top_fade_out.xml
- duckchat/duckchat-api/src/main/res/anim/fade_in.xml
- duckchat/duckchat-api/src/main/res/anim/fade_out.xml
- duckchat/duckchat-api/src/main/res/values/animation-settings.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210941653913093?focus=true
- Decreases transition speed from 300ms to 200ms.
> Update Input Screen animation speed

- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-da/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-lv/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sl/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210957392094151
Translations for both the Buck and BB variants
Apply patch
```
Index: app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingPageManager.kt
<+>UTF-8
diff --git a/app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingPageManager.kt b/app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingPageManager.kt
--- a/app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingPageManager.kt	(revision 7232e8b3fafb87f610a12b1812f239a55e19cb50)
+++ b/app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingPageManager.kt	(date …
```
> Onboarding Experiment translations

- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirRunStateHandler.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/pixels/PirPixel.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/pixels/PirPixelInterceptor.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/pixels/PirPixelSender.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scan/PirScan.kt
- pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/scheduling/PirJobsRunner.kt
- pir/pir-internal/src/test/kotlin/com/duckduckgo/pir/internal/common/RealPirRunStateHandlerTest.kt
- pir/pir-internal/src/test/kotlin/com/duckduckgo/pir/internal/scan/RealPirScanTest.kt
- pir/pir-internal/src/test/kotlin/com/duckduckgo/pir/internal/scheduling/RealPirJobsRunnerTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201462763415876/task/1210648231323874?focus=true
https://app.asana.com/1/137249556945/project/1201462763415876/task/1210960977706939?focus=true
> PIR: Add pixels for scheduling

- subscriptions/subscriptions-impl/src/main/res/values-bg/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-cs/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-da/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-de/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-el/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-es/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-et/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-fi/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-fr/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-hr/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-hu/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-it/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-lt/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-lv/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-nb/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-nl/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-pl/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-pt/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-ro/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-ru/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-sk/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-sl/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-sv/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values-tr/strings-subscriptions.xml
- subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
- subscriptions/subscriptions-impl/src/main/res/values/strings-subscriptions.xml
Task/Issue URL: https://app.asana.com/1/137249556945/task/1211005937813705?focus=true
More rebranding & duck.ai translations
_Subscriptions_
> Rebranding & duck.ai paid translations (round 3)

- app/src/main/java/com/duckduckgo/app/onboarding/ui/page/BbWelcomePage.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/414730916066338/task/1211043239331636
Fixed memory leaks in the BbWelcomePage by properly canceling animations when the view is destroyed. Added references to ViewPropertyAnimator and ValueAnimator instances and ensured they are canceled in onDestroyView().
Apply patch
```
Index: app/src/main/java/com/duckduckgo/app/onboardingdesignexperiment/OnboardingDesignExperimentManager.kt
<+>UTF-8
diff --git a/app/src/main/java/com/duckduckgo/app/onboardingdesignexperiment/OnboardingDesignExperimentManager.kt b/app/src/main/java/com/duckduckgo/app/onboardingdesignexperiment/OnboardingDesignExpe …
```
> Onboarding Experiment BB: Fix skip onboarding crash

- pir/pir-impl/schemas/com.duckduckgo.pir.impl.store.PirDatabase/8.json
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/service/DbpService.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/PirDatabase.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/PirRepository.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/db/BrokerDao.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/db/BrokerEntities.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210459849416503?focus=true 
See attached task descriptionn
https://app.asana.com/1/137249556945/task/1211044309629869?focus=true
> Pir: Store MirrorSites

- autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
- autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
- subscriptions/subscriptions-impl/src/main/res/values-pl/strings-subscriptions.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/38424471409662/task/1210889211567957?focus=true 
Changing some strings to make messaging around importing passwords more consistent.
> Update copy for importing passwords from google for consistency

- code-formatting.gradle
- versions.properties
Task/Issue URL: https://app.asana.com/1/137249556945/project/608920331025315/task/1211065867354946?focus=true 
Update to latest stable version of spotless
> Update spotless version, from 6.1.2 to 7.2.1

- versions.properties
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211065997417983?focus=true 
Removes unused/redundant items from project dependencies' versions declaration file
> Cleaup unused items from versions.properties

- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebGetDataBrokersMessageHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/PirRepository.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/db/BrokerDao.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211088335699800?focus=true
Adds proper implementation of the getDataBrokers message for PIR Web UI.
https://app.asana.com/1/137249556945/task/1211095110950029?focus=true
No UI changes
> PIR: Implement getDataBrokers message

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/internal/DefaultSubscriptionsBaseUrl.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1125189844152671/task/1211094091148565?focus=true 
Fixes subscriptions url
Code Review
> Fixes the subscriptions url

- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebGetFeatureConfigMessageHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebJsMessageHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/model/PirWebMessageResponse.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211095110950031?focus=true
Adds support for the ´getFeatureConfig´ web message
https://app.asana.com/1/137249556945/task/1211102791780022?focus=true
No UI changes
> PIR: Add getFeatureConfig message

- duckchat/duckchat-impl/src/main/res/values-bg/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-cs/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-da/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-de/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-el/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-es/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-et/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-fi/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-fr/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-hr/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-hu/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-it/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-lt/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-lv/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-nb/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-nl/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-pl/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-pt/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-ro/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-ru/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-sk/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-sl/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-sv/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-tr/strings-duckchat.xml
Translations for https://github.com/duckduckgo/Android/pull/6586.
> Translations for "Update Duck.ai / AI Features settings page"

- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebSaveProfileMessageHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/state/PirWebOnboardingStateHolder.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/PirRepository.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/db/UserProfileDao.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211075568938200?focus=true
Validates that all profiles are saved on ´saveProfile´ message.
https://app.asana.com/1/137249556945/task/1211099146322592?focus=true
No UI changes
> PIR: Add profile saving validation

- privacy-config/privacy-config-internal/build.gradle
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211110301513546
Fixes an issue with Gradle config.
> make internal config patch tool compatible with Gradle Cache

- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/PirRunStateHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebInitialScanStatusMessageHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/model/PirWebMessageResponse.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/models/ExtractedProfile.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/scheduling/JobRecordUpdater.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/PirRepository.kt
- pir/pir-impl/src/test/kotlin/com/duckduckgo/pir/impl/common/RealPirRunStateHandlerTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211113778872819?focus=true
https://app.asana.com/1/137249556945/project/488551667048375/task/1211113778872820?focus=true
> PIR: Fix address and dates in Dashboard

- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/actions/ExecuteBrokerStepActionEventHandler.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211124441214725?focus=true
See attached task description. 
https://app.asana.com/1/137249556945/task/1211134814919961?focus=true
No UI changes
> PIR: Fix email action

- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/state/PirWebOnboardingStateHolder.kt
- pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/state/RealPirWebOnboardingStateHolderTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/task/1211134926977198?focus=true
- Uses an interface for `PirWebOnboardingStateHolder`
- Adds unit tests for `RealPirWebOnboardingStateHolder`
Run unit tests in `RealPirWebOnboardingStateHolderTest`
No UI changes
> PIR: Add unit tests for PirWebOnboardingStateHolder

- pir/pir-impl/build.gradle
- pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/PirDashboardWebMessagingInterfaceTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211134926977199?focus=true
Adds unit tests for `PirDashboardWebMessagingInterface`
Run tests in `PirDashboardWebMessagingInterface`
No UI changes
> PIR: Add unit tests for PirDashboardWebMessagingInterface

- pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebSaveProfileMessageHandlerTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211137752462445?focus=true
Adds unit tests for the `PirWebSaveProfileMessageHandler` message handler. 
Run unit tests in `PirWebSaveProfileMessageHandlerTest`
No UI changes
> PIR: Add tests for SaveProfile message handler

- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebInitialScanStatusMessageHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebJsMessageHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebMaintenanceScanStatusMessageHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/model/PirWebMessageResponse.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/state/PirDashboardInitialScanStateProvider.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/state/PirDashboardMaintenanceScanDataProvider.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/state/PirDashboardModels.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/state/PirDashboardStateProvider.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/scan/PirScanScheduler.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211032724430686?focus=true
Testing should be done on the stacked PR
> PIR: Implement and Integrate Maintenance scan status

- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/state/PirDashboardInitialScanStateProvider.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/state/PirDashboardMaintenanceScanDataProvider.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/state/PirDashboardStateProvider.kt
- pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/state/RealPirDashboardInitialScanStateProviderTest.kt
- pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/state/RealPirDashboardMaintenanceScanDataProviderTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211174699675657?focus=true
See attached task
Smoke test dashboard
> PIR: Fix initialScanStatus resultsFound and maintenanceScanStatus completedOptOut 

- .maestro/input_screen/input_screen_chat_mode.yaml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1211205565809652?focus=true
Updates the assertion based on changes in https://github.com/duckduckgo/Android/pull/6692.
QA optional. If you want to try the test locally, run:
```
./gradlew installInternalRelease
maestro test .maestro/input_screen/input_screen_preference_management.yaml
```
> Fix Input Screen E2E tests

- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/state/PirDashboardMaintenanceScanDataProvider.kt
- pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/state/RealPirDashboardMaintenanceScanDataProviderTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/45878998844068/task/1211195932240353?focus=true 
Smoke test dashboard
> PIR: Fix next scan details

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/browser/santize/NonHttpAppLinkChecker.kt
- app/src/test/java/com/duckduckgo/app/browser/santize/RealNonHttpAppLinkCheckerTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/608920331025315/task/1211244379062806?focus=true
See linked task
> Prevent external intents triggering file sharing

- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1211033154154785/task/1211257220446956?focus=true
Updated copy.
QA-Optional, see screenshots in https://app.asana.com/1/137249556945/task/1211219207830198/comment/1211257472223938?focus=true
> Fix copy for [Android] Add Duck.ai entry points to widgets plus additional widgets

- app/src/main/res/drawable/search_widget_favorites_dark_background.xml
- app/src/main/res/drawable/search_widget_favorites_daynight_background.xml
- app/src/main/res/drawable/search_widget_favorites_light_background.xml
- app/src/main/res/values/dimens.xml
- common/common-ui/src/main/res/values/design-system-dimensions.xml
- common/common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/1/137249556945/task/1211257220446959?focus=true
Added extra large corner radius for search widget backgrounds and update favorites corner radius.
QA-optional.
See screenshots in https://app.asana.com/1/137249556945/task/1211219207830215/comment/1211248774089180?focus=true
> Fix design for [Android] Add Duck.ai entry points to widgets plus additional widgets

- app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
- app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
- app/src/main/java/com/duckduckgo/app/autocomplete/impl/AutoCompletePixelNames.kt
- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
- app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
- app/src/test/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt
- browser-api/src/main/java/com/duckduckgo/browser/api/autocomplete/AutoComplete.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/viewmodel/InputScreenViewModel.kt
- duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/pixel/DuckChatPixels.kt
- duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenViewModelTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1174433894299346/task/1211199636994638?focus=true
This PR unifies to pixel logic so it’s used in Autocomplete and DuckChat
> Autocomplete: Fix pixels un Duck.ai

- privacy-config/privacy-config-impl/src/main/res/raw/privacy_config.json
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211301604994554?focus=true
This PR stops enrolling users to the onboarding design experiment when local privacy config is used. Users that are already enrolled should continue to see the experimental UI.
QA-optional
> Stop onboarding design experiment enrolment

- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/BillingClientAdapter.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/PlayBillingManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/RealBillingClientAdapter.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/billing/RealPlayBillingManagerTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211320822502364?focus=true
This PR implements the foundational billing infrastructure required for subscription plan switching functionality. It adds the core Google Play Billing integration without exposing any UI changes to users.
> Subscription switching: Billing integration

- duckchat/duckchat-impl/src/main/res/values-bg/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-cs/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-da/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-de/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-el/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-es/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-et/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-fi/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-fr/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-hr/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-hu/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-it/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-lt/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-lv/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-nb/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-nl/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-pl/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-pt/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-ro/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-ru/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-sk/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-sl/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-sv/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values-tr/strings-duckchat.xml
- duckchat/duckchat-impl/src/main/res/values/strings-duckchat.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1211326131595801?focus=true
Updates the copy for the exp. address bar setting on the Ai Features page.
> update AI Features setting page's exp. address bar copy

- app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205008441501016/task/1211371004653652?focus=true 
* Fix broken check for breakageReportResult and initialPing. We trying to match feature name instead of method
n/a
> Fix breakage reporting handling

- package-lock.json
- package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1211391205772136/f 
----- 
> Update reference tests to version 1758095627

- subscriptions/subscriptions-impl/src/main/res/values-pl/strings-subscriptions.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1211047862448590?focus=true
Update a couple of translations in Polish after review
> Improve some Polish translations

- app/src/main/java/com/duckduckgo/app/browser/animations/AddressBarTrackersAnimationFeatureToggle.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211450804802436?focus=true
This PR introduces a new remote feature toggle for the address bar trackers animation. The toggle is set to be disabled by default. Additionally, it removes the empty implementation files for the Sense of Protection experiment.
N/A
N/A
> Add feature toggle for address bar trackers animation

- app/src/test/java/com/duckduckgo/subscriptions/impl/wideevents/SubscriptionPurchaseWideEventTest.kt
- statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/wideevents/WideEventSender.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/BillingClientAdapter.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/PlayBillingManager.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/RealBillingClientAdapter.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
- subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/wideevents/SubscriptionPurchaseWideEvent.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/billing/RealPlayBillingManagerTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211444639001948
See task
> Add subscription purchase wide event

- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/NativeBrokerActionHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/PirRunStateHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/actions/BrokerStepCompletedEventHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/actions/PirActionsRunnerStateEngine.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/actions/StartedEventHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/email/PirEmailConfirmationJobsRunner.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/PirRepository.kt
- pir/pir-impl/src/test/kotlin/com/duckduckgo/pir/impl/common/RealPirRunStateHandlerTest.kt
- pir/pir-impl/src/test/kotlin/com/duckduckgo/pir/impl/store/RealPirRepositoryTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/481882893211075/task/1211521224940839?focus=true
QA-optional, we can test later.
Unit tests should pass.
> PIR: Batch requests for email link fetch and deletion

- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/NativeBrokerActionHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/PirJob.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/PirJobConstants.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/PirRunStateHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/actions/BrokerStepCompletedEventHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/actions/ExecuteNextBrokerStepEventHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/actions/PirActionsRunnerStateEngine.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/common/actions/StartedEventHandler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/email/PirEmailConfirmation.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/email/PirEmailConfirmationJobsRunner.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/email/PirEmailConfirmationRemoteWorker.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/scan/PirScanScheduler.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/scheduling/JobRecordUpdater.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/service/DbpService.kt
- pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/PirRepository.kt
- pir/pir-impl/src/test/kotlin/com/duckduckgo/pir/impl/common/RealPirRunStateHandlerTest.kt
- pir/pir-impl/src/test/kotlin/com/duckduckgo/pir/impl/store/RealPirRepositoryTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/481882893211075/task/1211356569822390?focus=true 
No testing required
> PIR: Add support for new email confirmation apis

- design-system/src/main/res/drawable/ic_enter_24.xml
- duckchat/duckchat-impl/src/main/res/layout/view_input_screen_buttons.xml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1211476028776908?focus=true
Updates the return icon.
> update return icon

- subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
Task/Issue URL: https://app.asana.com/1/137249556945/project/1209991789468715/task/1211521379345860?focus=true
> Fix unit tests with subscriptions staging patch
