app/src/main/java/com/duckduckgo/app/appearance/AppearanceActivity.kt
app/src/main/java/com/duckduckgo/app/appearance/AppearanceViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/java/com/duckduckgo/app/settings/db/SettingsDataStore.kt
app/src/main/res/layout/activity_appearance.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/duckduckgo/app/Fakes.kt
app/src/test/java/com/duckduckgo/app/appearance/AppearanceViewModelTest.kt
browser-api/src/main/java/com/duckduckgo/app/browser/omnibar/model/OmnibarPosition.kt

Task/Issue URL: https://app.asana.com/0/1207418217763355/1206100017017597/f
Figma link: https://www.figma.com/design/Z4TFKpzzc02naMpqYO9ehv/Bottom-URL-bar-(Android)?node-id=1-2&t=oeftk6SHYD0A2iwr-1
This PR adds a new Settings option to change the position of the browser address bar. The selected value is saved in the user preferences.
https://github.com/user-attachments/assets/f2fb8635-6e96-4439-a130-dea91e7b11de

Omnibar position: Settings and store

---

app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1208134428464537/1207998553475892/f 
Currently any text shared into the app (e.g., using `Search DuckDuckGo` from elsewhere) doesn't handle the case where apostrophes are in it (might also do it with some other special characters). 
This fix addresses that. In case of any unintended side-effects, `androidSkipUrlConversionOnNewTab` remote feature flag could be created and set to `false` to revert back to the old behaviour.

Shared queries into the app containing apostrophes better handled

---

new-tab-page/new-tab-page-impl/build.gradle
new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/settings/DragLinearLayout.kt

Task/Issue URL: https://app.asana.com/0/1200204095367872/1208202859730178/f
Adds the Timber dependency to the `new-tab-page-impl` module and replaces `Log` usages in `DragLinearLayout`.

Use Timber instead of Log in DragLinearLayout

---

experiments/experiments-api/src/main/java/com/duckduckgo/experiments/api/VariantConfig.kt
experiments/experiments-impl/build.gradle
experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/ExperimentFiltersManager.kt
experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/ExperimentFiltersManagerImplTest.kt
statistics/statistics-impl/build.gradle
statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/api/RxPixelSender.kt
statistics/statistics-impl/src/test/java/com/duckduckgo/app/statistics/api/RxPixelSenderTest.kt

Task/Issue URL: https://app.asana.com/0/1201807753394693/1208158029105828/f
Add new filter `privacyProEligible` to remote experiment framework
_Pre steps_
_privacyProEligible filter disabled_
>         "filters": {
>           "privacyProEligible": false
>         }
_privacyProEligible filter enabled_
>         "filters": {
>           "privacyProEligible": true
>         }

New privacyProEligible filter for experiments

---

app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/browser/indonesiamessage/IndonesiaNewTabSectionDataStore.kt
app/src/main/java/com/duckduckgo/app/browser/indonesiamessage/IndonesiaNewTabSectionView.kt
app/src/main/java/com/duckduckgo/app/browser/indonesiamessage/IndonesiaNewTabSectionViewModel.kt
app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/res/layout/view_indonesia_new_tab_section.xml
app/src/main/res/layout/view_new_tab_legacy.xml
app/src/main/res/values/donottranslate.xml
app/src/test/java/com/duckduckgo/app/browser/indonesiamessage/IndonesiaNewTabSectionViewModelTest.kt
app/src/test/java/com/duckduckgo/app/browser/indonesiamessage/RealIndonesiaNewTabSectionDataStoreTest.kt
new-tab-page/new-tab-page-api/src/main/java/com/duckduckgo/newtabpage/api/NewTabPageSectionPlugin.kt
new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/RealNewTabPageSectionProvider.kt
new-tab-page/new-tab-page-impl/src/test/java/com/duckduckgo/newtabpage/impl/NewTabPageSectionProviderTest.kt
new-tab-page/new-tab-page-impl/src/test/java/com/duckduckgo/newtabpage/impl/TestPluginPoints.kt
privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeatureName.kt
saved-sites/saved-sites-impl/src/main/res/layout/view_new_tab_favourites_section.xml

Task/Issue URL: https://app.asana.com/0/1200581511062568/1208125695673129/f
Added a new section in the New Tab Page and a view in the Legacy Tab Page.
See https://app.asana.com/0/0/1208180779804579/f
See https://app.asana.com/0/1200581511062568/1208180779804556/f

Implementation: [Android] Show a special notice to users in Indonesia 

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1208219084344626/f 
----- 

Update content scope scripts to version 6.14.0

---

app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
app/src/test/java/com/duckduckgo/app/statistics/pixels/PixelNameTest.kt
statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/pixels/FeatureRetentionPixelSender.kt
statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/pixels/StatisticsPixelName.kt
statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/pixels/StatisticsPixelParamsRemovalPlugin.kt
statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/user_segments/UserSegmentsPixelSender.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208217925635108/f
Remove all default pixel params from user segment pixel.
Incidentally I have also moved all statistics pixels from the `statistics-api` module to the `-impl` module, as there's no reason for them to be public API
Just moving code around, there's no behavior change

Remove params from user segment pixel

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1208241984651435/f 
----- 

Update content scope scripts to version 6.14.1

---

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesActivePluginPointCodeGenerator.kt
app/src/main/java/com/duckduckgo/app/browser/newtab/FocusedViewProvider.kt
new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/FocusedViewPluginPointTrigger.kt

Task/Issue URL: https://app.asana.com/0/1198194956794324/1208197444733454/f
Active plugins can only be used in AppScope. Break the build if they're wrongly scoped.
_Test_
* Change the scope of an already existing plugin (eg. `AutofillNewTabShortcutPlugin`)
* clean build
[ ] verify build fails with proper message

Break build if active plugins are not in app scope

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/menu/BrowserPopupMenu.kt
app/src/main/res/layout/popup_window_browser_menu_bottom.xml

Task/Issue URL: https://app.asana.com/0/72649045549333/1208157245002308/f

Omnibar position: Menu

---

fastlane/Fastfile

Task/Issue URL: https://app.asana.com/0/488551667048375/1208270529332156/f 
Sets the initial rollout percentage to a lower value.
| Before | After |
|--------|--------|
| 0.1% | 0.0001% |
Can't find a definitive answer on what the smallest possible value is that the Play Store will still accept, but anecdotally this should work.  
QA-optional; will find out next time a release is cut if it works (and can revert if it doesn't)

Reduce the initial prod rollout percentage from 0.1% to 0.0001%

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/survey/AutofillSurveyFeature.kt

Task/Issue URL: https://app.asana.com/0/608920331025315/1208317909207871/f 
To support saving the feature's settings for autofill surveys, we added a `AutofillSurveyFeatureSettingsStore`. However, the config of the autofill feature wrongly stated which settings store to use: 
- specified: `AutofillSiteBreakageReportingRemoteSettingsPersister`
- should have been: `AutofillSurveyFeatureSettingsStore`
This doesn't matter in terms of functionality. i.e., it works as expected (hence why it wasn't caught in testing), but still good to tidy up.
- QA optional

Fix survey's store declaration

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/di/NetworkModule.kt
app/src/main/java/com/duckduckgo/app/feedback/api/FeedbackService.kt
app/src/main/java/com/duckduckgo/app/feedback/api/FeedbackSubmitter.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/java/com/duckduckgo/app/survey/ui/SurveyViewModel.kt
app/src/test/java/com/duckduckgo/app/survey/ui/SurveyViewModelTest.kt
experiments/experiments-api/src/main/java/com/duckduckgo/experiments/api/loadingbarexperiment/LoadingBarExperimentManager.kt
experiments/experiments-impl/build.gradle
experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/loadingbarexperiment/DuckDuckGoLoadingBarExperimentManager.kt
experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/loadingbarexperiment/LoadingBarExperimentDataStore.kt
experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/loadingbarexperiment/LoadingBarExperimentFeature.kt
experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/loadingbarexperiment/LoadingBarExperimentPixels.kt
experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/loadingbarexperiment/LoadingBarExperimentVariantInitializer.kt
experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/loadingbarexperiment/DuckDuckGoLoadingBarExperimentManagerTest.kt
experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/loadingbarexperiment/LoadingBarExperimentSharedPreferencesTest.kt
experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/loadingbarexperiment/LoadingBarExperimentVariantInitializerTest.kt
statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
statistics/statistics-impl/src/main/java/com/duckduckgo/app/statistics/pixels/FeatureRetentionPixelSender.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208210291365732/f
- Adds a custom experiment to measure the perceived performance of the loading bar on existing users.
- The experiment randomly assigns a variant on-update, with percentage roll-out controlled by the loadingBarExp feature toggle.
_Point at the config linked in the task_
-------
_In `LoadingBarExperimentVariantInitializer` set `val probabilities = doubleArrayOf(0.0, 1.0)`_
_Enrolment_
_Daily_
_URI loaded_
_Pull to refresh_
_Refresh_
_Refresh action daily_
_Loading bar_
_Feedback_
-------
_In `LoadingBarExperimentVariantInitializer` set `val probabilities = doubleArrayOf(1.0, 0.0)`_
_Enrolment_
_Daily_
_URI loaded_
_Pull to refresh_
_Refresh_
_Refresh action daily_
_Loading bar_
_Feedback_
-------
_In the config, …

Add loading bar performance experiment

---

app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt

Task/Issue URL: https://app.asana.com/0/1201807753394693/1208330088276454/f
set onClickListener for search/site suggestions when typing animation is finished

Fix for search/site suggestions not working after skipping typing animation

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208310633343752/f
Fix blob download when the page contains both parent and child frames
_Test 1_
_Test2_

Fix blob download for parent frames when they have child frames

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/view/ViewExtension.kt
common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/ActivityExtensions.kt
common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/FragmentExtensions.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1208339084893367/f 
We saw some keyboard crashes due to some recent refactoring of the Omnibar.
The Omnibar was previously solely bound in onActivityCreated.
It was never nulled out in `onDestroyView` so the Fragment held on to it, and when the delay concluded it would happily try to call show/hideKeyboard using the Omnibar without issue.
Now, we’re using the FragmentViewBindingDelegate for the Omnibar, which gets nulled out in onDestroy, so when the delay concluded we tried calling show/hideKeyboard on a null object. 
To fix this we’re introducing new extension functions that follow the [recommended way](https://developer.android.com/develop/ui/views/touch-and-input/keyboard-input/visibility#kotlin) to show and hide the keyboard. …

Fix keyboard crashes in BrowserFragment

---

node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Update content scope scripts to version 6.16.0

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
experiments/experiments-api/src/main/java/com/duckduckgo/experiments/api/loadingbarexperiment/LoadingBarExperimentManager.kt
experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/loadingbarexperiment/DuckDuckGoLoadingBarExperimentManager.kt
experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/loadingbarexperiment/UriLoadedPixelFeature.kt
experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/loadingbarexperiment/DuckDuckGoLoadingBarExperimentManagerTest.kt

Task/Issue URL: https://app.asana.com/0/1200204095367872/1208349807308363/f
- Updates the caching logic to load to memory on init.
- Also adds a kill switch to disable the URI loaded pixel.
Remove this from `LoadingBarExperimentVariantInitializer`:
```
loadingBarExperimentFeature.self().isEnabled() &&
loadingBarExperimentFeature.allocateVariants().isEnabled()
```
_Kill switch_
Privacy tests passed: https://github.com/duckduckgo/Android/actions/runs/10946311836 ✅

Update Loading Bar Experiment caching logic

---

app/build.gradle

Task/Issue URL: https://app.asana.com/0/1205617573940217/1208355525889878/f
This PR disables C2 compiler in unit tests. C2 compiler provides no value in the context of unit tests and may be responsible for JVM crashes that we're experiencing.
QA-optional

Disable C2 compiler in unit tests

---

app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPlugin.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModel.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/model/ShowOnAppLaunchOption.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPluginTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModelTest.kt
app/src/test/java/com/duckduckgo/fakes/FakePixel.kt
statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/1207908166761516/1208156273709090/f
Adds three pixels to the Show on App Launch feature:
- When the Show on App Launch screen is opened from General settings (temporary pixel)
- When selecting a new Show on App Launch option (temporary pixel)
- When the daily pixel is fired (permanent pixel)
_App launch pressed pixel_
_New option selected pixel_
_Daily pixel_
N/A

Show on App Launch: Add pixels

---

app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPlugin.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModel.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/model/ShowOnAppLaunchOption.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchOptionDataStore.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPluginTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModelTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/FakeShowOnAppLaunchOptionDataStore.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchPrefsDataStoreTest.kt
app/src/test/java/com/duckduckgo/fakes/FakePixel.kt
statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/1207908166761516/1208156273709083/f 
Adds some additional tests for the BrowserViewModel and the ShowOnAppLaunch store
N/A
N/A

Show on App Launch: Add additional tests

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPlugin.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImpl.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModel.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/UrlConverter.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/model/ShowOnAppLaunchOption.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchDataStoreModule.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchOptionDataStore.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPluginTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImplTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModelTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/FakeShowOnAppLaunchOptionDataStore.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchPrefsDataStoreTest.kt
app/src/test/java/com/duckduckgo/fakes/FakePixel.kt
browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/1207908166761516/1208167186867417/f 
Adds functionality to open the show on app launch option based on what has been set. 
If there is no specialised launch happening then we check the show on app launch setting:
1. If LastOpenedTab is set, we do nothing as this is current behaviour
2. If NewTabPage is set then we open a new tab
3. If SpecificPage is set we compare the url to the current selected tab, if it's not the same we open a new tab otherwise we do nothing 
Also as part of this PR, we add validation to the URL:
1. It is blank will set it as a default to duckduckgo.com
2. If it has no scheme will add http (in case the website does not currently support https)
3. Otherwise return the url what was passed in
_Last Opened Tab_
_New Tab Page_ …

Show on App Launch: Open launch option when set

---

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/ui/NetpAppExclusionListActivity.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208280638257502/f
On the VPN exclusion list screen:
- Show context menu > Restore defaults IF there is something to restore
- ELSE, hide it

Remove restore protections when protection have been restored

---

node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.css
node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1208405283799536/f 
----- 

Update content scope scripts to version 6.19.0

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt
app/src/main/java/com/duckduckgo/app/browser/RealWebViewCapabilityChecker.kt
browser-api/src/main/java/com/duckduckgo/app/browser/api/WebViewCapabilityChecker.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1208402254099284/f 
Extracts some of the checks around safely using WebMessageListeners and AddDocumentStartJavacscript APIs so that they can be queried outside of a `DuckDuckGoWebView` instance, and therefore makes the checks possible from outside of the `app` module

Add APIs for safely interacting with some trickier WebView APIs

---

common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/ActivityExtensions.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1208407851630430/f
After we did https://github.com/duckduckgo/Android/pull/5033 the omnibar is taking focus more than usual, triggering onFocus changes in some unexpected scenarios (e.g: if we send the app to background, etc.)
After taking a look, the logic to show/hide keyboard was changed, and we now, for both methods, execute `editText.requestFocus()`. That seems correct for showing, but unsure for hiding. 
_Feature 1_
- just smoke test

fix omnibar taking focus when hiding keyboard

---

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/promotion/PasswordsScreenPromotionPlugin.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillDisabledByConfigWarningUI.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/InlineBrowserAutofill.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/main/res/layout/view_autofill_config_disabled_warning.xml
autofill/autofill-impl/src/main/res/values/donottranslate.xml
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/InlineBrowserAutofillTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/0/1208236187388612/f 
When remote flag disabled, we warn the user about it and disable autofill toggle.
_Feature 1_

Adds logic and UI when Autofill Remote feature flag disabled

---

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/promotion/PasswordsScreenPromotionPlugin.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillDisabledByConfigWarningUI.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillSupportWarningUI.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/InlineBrowserAutofill.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
autofill/autofill-impl/src/main/res/layout/view_autofill_config_disabled_warning.xml
autofill/autofill-impl/src/main/res/layout/view_autofill_warning_support.xml
autofill/autofill-impl/src/main/res/values/donottranslate.xml
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/InlineBrowserAutofillTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/0/1208350515967413/f
When WebView version <  `126.0.6478.40` autofill is not supported.
We warn the user about it and disable autofill toggle.
_Feature 1_
_Feature 2_

adding a warning message when webview not supported

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserChromeClientTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
app/src/main/java/com/duckduckgo/app/global/model/SiteFactoryImpl.kt
app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt
app/src/main/res/layout/include_custom_tab_toolbar.xml
app/src/test/java/com/duckduckgo/app/brokensite/BrokenSiteDataTest.kt
app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
app/src/test/java/com/duckduckgo/app/global/model/SiteMonitorTest.kt
browser-api/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
common/common-utils/src/main/java/com/duckduckgo/common/utils/UriExtension.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt

Task/Issue URL: https://app.asana.com/0/1207252092703676/1208391013610683/f 
* Show Duck Player icon and not privacy shield in custom tabs
* Fix bug where tracking links redirecting to YouTube wouldn't trigger Duck Player
* Display duck://player instead of youtube-nocookie in custom tabs
_Feature 1_
Task/Issue URL: https://app.asana.com/0/1207252092703676/1208391013610683/f 
_Feature 2_
_Feature 3_

Show Duck Player icon and not privacy shield in custom tabs

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
app/src/test/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208403817322208/f
- Adds an `AUTOCOMPLETE_RESULT_DELETED_DAILY` pixel that's fired once per day when an autocomplete result is deleted.
- This is fired from both the browser tab and system search.
_Browser tab_
_System search_

Add autocomplete deletion daily pixel

---

installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/InstallSourcePrivacyConfigObserver.kt
installation/installation-impl/src/test/java/InstallSourcePrivacyConfigObserverTest.kt

Task/Issue URL: https://app.asana.com/0/608920331025315/1208315780180365/f 
Ensures install source extraction logic runs after privacy config has been downloaded. 
- This is needed by a higher level branch on the stack where remote config is read and used in the install source extraction. 
- This PR just lays the groundwork to support that use case

Ensure InstallSource extraction logic runs after privacy config downloaded

---

installation/installation-impl/build.gradle
installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/di/InstallerModule.kt
installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/fullpackage/InstallSourceFullPackageStore.kt
installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/fullpackage/feature/InstallSourceFullPackageFeature.kt
installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/fullpackage/feature/InstallSourceFullPackageListJsonParser.kt
installation/installation-impl/src/test/java/com/duckduckgo/installation/impl/installer/fullpackage/IncludedPackagesTest.kt
installation/installation-impl/src/test/java/com/duckduckgo/installation/impl/installer/fullpackage/InstallSourceFullPackageStoreImplTest.kt
installation/installation-impl/src/test/java/com/duckduckgo/installation/impl/installer/fullpackage/feature/InstallSourceFullPackageListJsonParserImplTest.kt
installation/installation-impl/src/test/resources/json/installerFullSource_emptyList.json
installation/installation-impl/src/test/resources/json/installerFullSource_multipleEntryList.json
installation/installation-impl/src/test/resources/json/installerFullSource_singleEntryList.json

Task/Issue URL: https://app.asana.com/0/608920331025315/1208315780180367/f 
Defines a feature flag for how to handle full installer package IDs. 
**QA-optional**
- no observable change of behaviour in this PR (branch above will cover full testing). 
If you do want to check:
- Check the contents of the data store (e.g., using `Device Explorer`), which will live in `com.duckduckgo.mobile.android.debug/files/datastore/com.duckduckgo.installation.impl.installer.preferences_pb`

Add feature flag for sending full installer package ID

---

common/common-ui/src/main/res/values/design-system-theming.xml

Task/Issue URL: https://app.asana.com/0/1200204095367872/1208412577276091/f
- Currently, an unintended overlay is being applied to elevated surfaces.
- Setting elevationOverlayEnabled to false removes the overlay.
- With this change, surfaces will always be `daxColorSurface`, regardless of elevation (Expected behavior).
_Try all combinations of OS theme / app theme (i.e. App set to light, OS set to dark)_

Fix surface theming

---

.maestro/autofill/2_autofill_add_search_update_delete_creds.yaml
.maestro/autofill/3_autofill_prompted_to_save_creds_on_form.yaml
.maestro/autofill/steps/delete_logins.yaml
.maestro/autofill/steps/manual_update.yaml

Task/Issue URL: https://app.asana.com/0/608920331025315/1208459234138716/f 
Autofill nightlies are failing because as of https://github.com/duckduckgo/Android/pull/5007, we require a more modern `WebView` than is available in Maestro Cloud emulators.
This PR:
- fixes one of the ways the tests fail, by ensuring the warning banner in password management screen doesn't upset the tests
- stops running the test which tests _actual_ `WebView` autofill as part of the nightly (won't be possible to run this on CI until either Maestro Cloud ships their emulators with a decent `WebView` version, or we run the tests on different infrastructure)
- adds some `scrollUntilVisible` to help add resilience to the tests running on smaller devices or when there are extra warning/promo banners above the items …

Ensure autofill nightly tests succeed

---

content-scope-scripts/content-scope-scripts-impl/build.gradle
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessaging.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessagingTest.kt
duckplayer/duckplayer-api/src/main/java/com/duckduckgo/duckplayer/api/DuckPlayer.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerScriptsJsMessaging.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1208375755367840/f
Only process duck-player related messages if the origin belongs to a given set of domains
_Feature 1_

Add allowList for Duck Player message handlers

---

app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt
app/src/main/java/com/duckduckgo/app/browser/RealWebViewCapabilityChecker.kt
app/src/main/java/com/duckduckgo/app/browser/SafeWebMessageHandlerImpl.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/InlineBrowserAutofill.kt
browser-api/build.gradle
browser-api/src/main/java/com/duckduckgo/app/browser/api/SafeWebMessageHandler.kt

Task/Issue URL: https://app.asana.com/0/608920331025315/1208501035862472/f 
Pulls the logic for safely adding/removing a web message listener outside of `app` module so that it can be used elsewhere, and lets autofill use it for its WebView integration.
Nothing else using that extracted logic yet, so nothing else will have changed.

Use safeWebMessageHandler code for autofill integration

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/browser/menu/RefreshPixelSender.kt
app/src/main/java/com/duckduckgo/app/browser/refreshpixels/RefreshDao.kt
app/src/main/java/com/duckduckgo/app/browser/refreshpixels/RefreshEntity.kt
app/src/main/java/com/duckduckgo/app/browser/refreshpixels/RefreshPixelSender.kt
app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/browser/refreshpixels/RefreshPixelSenderTest.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1208470923077006/f
This adds two pixels:
- One for when the user refreshes twice within 12 seconds.
- And another when the user refreshes three times within 20 seconds.
It also refactors all the refresh pixel sending logic into `RefreshPixelSender`, removing it from `BrowserTabFragment`.
Filter by `m_reload`
_Two refreshes in twelve seconds_
_Three refreshes in twenty seconds_
_Three refreshes in twenty seconds and two refreshes in twelve seconds_
_Two refreshes in twelve seconds after killing the app_

Add pixels for multiple refreshes

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
app/src/test/java/com/duckduckgo/duckplayer/impl/DuckPlayerSettingsViewModelTest.kt
duckplayer/duckplayer-api/src/main/java/com/duckduckgo/duckplayer/api/DuckPlayer.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerDataStore.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerFeatureRepository.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerSettingsActivity.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerSettingsViewModel.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
duckplayer/duckplayer-impl/src/main/res/layout/activity_duck_player_settings.xml
duckplayer/duckplayer-impl/src/main/res/values/donottranslate.xml

Task/Issue URL: https://app.asana.com/0/72649045549333/1208500747095747/f 
_Always Ask + Open in new tab + YT video -> New tab_
_Always Ask + Not open in new tab + YT video -> No new tab_
_Always + Open in new tab + From omnibar -> No new tab_
_Always + Open in new tab + Not from omnibar -> New tab_
_Always ask + Open in new tab + From SERP -> New tab_
_Always ask + Not open in new tab + From SERP -> No new tab_

Open Duck Player videos in new tab

---

versioning.gradle

Task/Issue URL: https://app.asana.com/0/1174433894299346/1208382292008137/f
_Nightly_
_Production_

Use latest tag to retrieve versionCode for nightly releases

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/LegacyOmnibarView.kt
app/src/main/res/layout/view_legacy_omnibar.xml
app/src/main/res/layout/view_legacy_omnibar_bottom.xml

Task/Issue URL: https://app.asana.com/0/1174433894299346/1208502796109620/f
This PR adds a safe way to call methods in the `LegacyOmnibarView`. This is needed because the way we interact with the Omnibar doesn’t take into account that Dagger might not have injected yet.
Smoke tests and QA

Omnibar: safe calling Android methods

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/LegacyOmnibarView.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/TopAppBarBehavior.kt

Task/Issue URL: https://app.asana.com/0/0/1208417966104900/f
This PR fixes the missing last item from the autocomplete list, which is hidden when the omnibar position feature is available and the omnibar position is set to TOP.
_Feature 1_

Fix the missing last item in autocomplete list

---

saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/service/SavedSitesExporter.kt

Task/Issue URL: https://github.com/duckduckgo/Android/issues/3069
In Android 10/11, the "w" write mode no longer truncates the file during an overwrite. More details about this workaround can be found at https://issuetracker.google.com/issues/180526528
1. Add some bookmarks to DDG and export them.
2. Delete half of the bookmarks and export them again to the same file, confirming overwriting.
3. Observe the size and contents of the file.
<details>
<summary>Example non-truncated output pre-fix</summary>
```
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<Title>Bookmarks</Title>
<H1>Bookmarks</H1>
<DL><p>
<DT><H3 ADD_DATE="1618844074" LAST_MODIFIED="1618844074" PERSONAL_TOOLBAR_FOLDER="true">DuckDuckGo Bookmarks</H3>
<DL><p>
<DT><A …
```

Truncate export bookmarks file on overwrite

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/engagement/store/AutofillEngagementRepository.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/engagement/store/DefaultAutofillEngagementRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208140129736905/f 
Set logcat filter: `message~:"Unable to determine autofill toggle status" | message~:"Pixel sent: m_autofill_toggled"`
**Autofill working as normal**
Ensure autofill is supported (device auth set, modern WebView version)
**Autofill not available due to device auth being unset**
Remove system device auth

Omit autofill toggled pixel in certain conditions

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/BottomAppBarBehavior.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/LegacyOmnibarView.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/TopAppBarBehavior.kt
app/src/main/res/layout/view_legacy_omnibar.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1208503210252671/f
Also: https://app.asana.com/0/488551667048375/1208503210253722/f.
This PR fixes 2 connected issues:
- A gap at the bottom of a screen is visible when scroll flags are set on a toolbar container to disable toolbar scrolling
- Bottom omnibar not visible or is incorrectly scrollable while an omnibar icon is highlighted 
The solution unifies how the scrolling is enabled/disabled for both the top and bottom bar. The scroll flags are not set anymore, which fixes the gap problem.
_Bottom bar scrolling with highlighted icons_
_Extra gap at the bottom_
_Bottom bar scrolling with highlighted icons_
https://github.com/user-attachments/assets/17405aff-34ca-4f6f-a705-94de45bc207d
_Extra gap at the bottom_ …

Fix omnibar scrolling and browser layout gap

---

app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
duckplayer/duckplayer-impl/src/test/kotlin/com/duckduckgo/duckplayer/impl/RealDuckPlayerTest.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1208529859806622/f 
_Always Ask + videos vertical_
_Always ask + organic links_ 
_Always ask + overlay_ 
_Always + videos vertical_
_Always + organic links_ 
_Always_

Add missing auto pixel when Duck Player set to always and navigating from YT thumbnail

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/0/1200204095367872/1208539373099910/f
Fixes a `IllegalStateException` when showing the omnibar menu.

Fix popup menu IllegalStateException

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoUrlDetector.kt
app/src/test/java/com/duckduckgo/app/browser/DuckDuckGoUrlDetectorTest.kt
browser-api/src/main/java/com/duckduckgo/app/browser/DuckDuckGoUrlDetector.kt
common/common-utils/src/main/java/com/duckduckgo/common/utils/AppUrl.kt
privacy-protections-popup/privacy-protections-popup-impl/src/test/java/com/duckduckgo/privacyprotectionspopup/impl/PrivacyProtectionsPopupManagerImplTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208539436428546/f
This PR avoids showing the location permission snackbar when user is in AI Chat
_Enable location permission from SERP_
_Duck AI directly_
_AI Chat via SERP_

Avoid location permission messages for Duck AI

---

app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerLocalFilesPath.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
duckplayer/duckplayer-impl/src/test/kotlin/com/duckduckgo/duckplayer/impl/RealDuckPlayerTest.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1208539373099857/f 
_Feature 1_
- Smoke test Duck Player and navigation

Cache assets path loading

---

privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/network/PrivacyConfigService.kt

Very quick at merging https://github.com/duckduckgo/Android/pulls?q=is%3Apr+is%3Aclosed+author%3Amalmstein, didn’t realise Privacy Config was pointing to a JsonBlob
Verify Privacy Config Service points to the correct address

rollback privacy config

---

versioning.gradle

Task/Issue URL:  https://app.asana.com/0/414730916066338/1208559052787559
Fix versionCode script so it returns the proper number.
The first nightly after a prod release should be a 1, not a 0
_Current repo state, fetch all tags_

Version Code for first Nightly ends in 1

---

experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/ExperimentFiltersManager.kt
experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/VariantManagerImpl.kt
experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/ExperimentFiltersManagerImplTest.kt
experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/VariantManagerImplTest.kt
feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
feature-toggles/feature-toggles-impl/lint-baseline.xml
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt

Task/Issue URL: https://app.asana.com/0/1198194956794324/1208490749815531/f
Consider newly added (in abn) targets in normal feature and experiment features
Incidentally, I looked into the experiments and rename/documented some of the methods in there. As they were not clear to me. That's in the second commit, https://github.com/duckduckgo/Android/pull/5118/commits/6f578d9133220a12f7032e0bc4e6ce12803934d6

Consider targets for normal and experiment features

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
app/src/test/java/com/duckduckgo/duckplayer/impl/DuckPlayerSettingsViewModelTest.kt
duckplayer/duckplayer-api/src/main/java/com/duckduckgo/duckplayer/api/DuckPlayer.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerDataStore.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerFeature.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerSettingsActivity.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerSettingsViewModel.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeatureName.kt

Task/Issue URL: https://app.asana.com/0/0/1208511584623404/f 
_Feature 1_
_Feature 2_

Add feature flag for opening in new tab

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerPixelName.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
duckplayer/duckplayer-impl/src/test/kotlin/com/duckduckgo/duckplayer/impl/RealDuckPlayerTest.kt

Task/Issue URL: https://app.asana.com/0/1142021229838617/1208511584623405/f 
_Feature 1_
_Feature 2_

Add pixels for open in new tab

---

duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1208567891699607/f 
Fixes https://github.com/duckduckgo/Android/issues/5148
Looks like there's a bug in MimeTypeMap on Android that causes it to return null for JS files in some Android versions, which prevents Duck Player from loading. Added a fallback for such cases
_Feature 1_

Fix Duck Player not loading in Android 8. Fixes #5148

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchActivity.kt
app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
browser-api/build.gradle
browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208592488628219/f
Fixed item deletion from suggestions.
Test in Browser:
Verify:
Test using the widget
Verify:

Bug: Unable to delete autocomplete history items

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchActivity.kt
app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
browser-api/build.gradle
browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt

Task/Issue URL: https://app.asana.com/0/0/1208581391309609/f
Fixed autocomplete flow and pixels.
Steps to repro:
m_autocomplete_displayed_bookmark
m_autocomplete_displayed_switch_to_tab
Test the fix:

Bug: autocomplete pixels firing when Adding Bookmark

---

app/src/main/res/layout/view_new_omnibar.xml
app/src/main/res/layout/view_new_omnibar_bottom.xml

Task/Issue URL: https://app.asana.com/0/1201807753394693/1208590487067540/f
Center highlight alignment for privacy shield icon in address bar

New Omnibar: Fix privacy shield highlight alignment

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208580918293540/f
- Another attempt at fixing an `IllegalArgumentException` when `savedSiteAdded`.
- First attempt: https://github.com/duckduckgo/Android/pull/4900
_Add bookmark_

Fix IllegalArgumentException when savedSiteAdded

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/fire/FireActivity.kt

Task/Issue URL: https://app.asana.com/0/1207908166761516/1208588631698784/f 
When clearing data with the fire button the website set for Specific Page would load if that option was enabled.
This stops that happening and instead shows the new tab page.
_Fire button_
N/A
https://github.com/user-attachments/assets/03298b73-9682-485d-8be7-50b5ad5d13a4

Show on App Launch: Fix website showing after clear data action

---

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/Vpn.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistryImpl.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/di/VpnAppModule.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnActionReceiver.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTPAndNetPEnabledNotificationContentPlugin.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTpEnabledNotificationContentPlugin.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistryImplTest.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTPAndNetPEnabledNotificationContentPluginTest.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTpEnabledNotificationContentPluginTest.kt
network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/snooze/VpnCallStateReceiver.kt
network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/WgVpnNetworkStackTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208536273997127/f
Fix bug when both AppTP and VPN are enabled and user `disconnects` from the notification. 
When that happens two notifications are showed with CTAs to re-enable AppTP and VPN resp.
Expected:
* AppTP enable enables just ApptP
* VPN enable just enables VPN
Actual
* either ApptP or VPN enable enable both
_Test Fix_
_Test combined notification_
_Test AppTP_
_Test VPN_

Fix Disconnect/re-connect from notification when both VPN and AppTP are enabled

---

app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
duckplayer/duckplayer-api/src/main/java/com/duckduckgo/duckplayer/api/DuckPlayer.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerDataStore.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerFeatureRepository.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerSettingsViewModel.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1208580918293550/f 
* Remove unnecessary async/await
* Improve caching strategy by migrating Flows to StateFlows and using .value instead of .first(). Since .value is a sync operation, this also allowed to get rid of quite a few suspend functions
* Remove manual caching from `DuckPlayerFeatureRepository`, as it's no longer needed and we can rely on StateFlows instead
_Feature 1_

Fix ANR caused by Duck Player

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208618045189439/f
We need to make sure all attempts to access the `OmnibarLayout`’s ViewModel are checked to make sure the window is attached, otherwise the view may not be injected yet.

Fix the OmnibarLayout crash

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt

Task/Issue URL: https://app.asana.com/0/1198194956794324/1208351041752901/f
Remove the `fixBlobDownloadWithIframes` kill switch and all the (deactivated) code behind it
Just code review, we're removing code that doesn't execute

Remove fixBlobDownloadWithIframes kill switch

---

app/src/main/java/com/duckduckgo/app/browser/indonesiamessage/IndonesiaNewTabSectionView.kt
app/src/main/java/com/duckduckgo/app/browser/indonesiamessage/IndonesiaNewTabSectionViewModel.kt
app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/browser/indonesiamessage/IndonesiaNewTabSectionViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208610845437915/f
Removed temporary pixels for Indonesia message.
Code review only.

Android: Remove pixels for Indonesia message

---

node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.css
node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.js
package-lock.json
package.json

Update content scope scripts to version 6.23.0

---

app/src/main/res/layout/fragment_browser_tab.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1208619432765760/f
When a pulse animation is playing we don’t allow omnibar scrolling.
In that scenario, if autocomplete results are visible, we are scrolloing over the transparent bar.
_Feature 1_

Avoid autocomplete scrolling over omnibar

---

package-lock.json
package.json

Update content scope scripts to version 6.24.0

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1208628973892718/f
Only add Origin param if query will navigate to Duck Player
_Test origin param is still added if navigating to Duck Player_
_Test origin param is still added if navigating to Duck Player and opening in new tab_
_Test origin param is not added if not navigating to Duck Player_

Only add Origin param if query will navigate to Duck Player

---

app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchActivity.kt

Task/Issue URL: https://app.asana.com/0/1207908166761516/1208637287651029/f 
Fixes no options being selected then the phone is rotated.
https://github.com/user-attachments/assets/2fabd7ae-15c5-41e6-8b04-c78c13483d71

Show on App Launch: Fix no option selected on rotation

---

common/common-ui/src/main/java/com/duckduckgo/common/ui/themepreview/ui/dialogs/DialogsFragment.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/view/dialog/RadioListAlertDialogBuilder.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/view/dialog/TextAlertDialogBuilder.kt

Task/Issue URL: https://app.asana.com/0/1205648422731273/1208638453759884/f
_TextAlertDialog_
_RadioListAlertDialog_

Fix incorrect listeners invoked in dialogs

---

feature-toggles/feature-toggles-impl/lint-baseline.xml
feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/MetricsPixelStore.kt
feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/metrics/AppUseMetricPixelsPlugin.kt
feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/metrics/RetentionMetricsAtbLifecyclePlugin.kt
feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/metrics/SearchMetricPixelsPlugin.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/impl/MetricPixelInterceptorTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/impl/metrics/RetentionMetricsAtbLifecyclePluginTest.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1208600117694835/f 
Adds search and app_use metrics definitions as well as firing pixels with them.

Add first batch of search/app_use retention pixels

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/refreshpixels/RefreshPixelSender.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/blocklist/BlockList.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/blocklist/BlockListInterceptorApiPlugin.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/blocklist/BlockListPrivacyTogglePlugin.kt
app/src/test/java/com/duckduckgo/app/brokensite/api/BrokenSiteSubmitterTest.kt
app/src/test/java/com/duckduckgo/app/browser/refreshpixels/RefreshPixelSenderTest.kt
app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesMultipleReportReferenceTest.kt
app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesReferenceTest.kt
app/src/test/java/com/duckduckgo/app/trackerdetection/blocklist/BlockListInterceptorApiPluginTest.kt
app/src/test/java/com/duckduckgo/app/trackerdetection/blocklist/BlockListPrivacyTogglePluginTest.kt
feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/MetricPixelInterceptor.kt
feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/MetricsPixelStore.kt
feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/metrics/RetentionMetricsAtbLifecyclePlugin.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/impl/MetricPixelInterceptorTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/impl/metrics/RetentionMetricsAtbLifecyclePluginTest.kt
privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeatureName.kt
privacy-dashboard/privacy-dashboard-api/src/main/java/com/duckduckgo/privacy/dashboard/api/PrivacyProtectionTogglePlugin.kt
privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/di/PrivacyProtectionTogglePluginPoint.kt
privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModel.kt
privacy-dashboard/privacy-dashboard-impl/src/test/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1208618649788232/f 
Adds pixels for blocklist experiments as well as a new parameter to the breakage form

Add pixels to blocklist experiments

---

remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/pixels/RemoteMessagingPixels.kt

Task/Issue URL: https://app.asana.com/0/1207619243206445/1208647599954669/f 
When sending unique RMF pixel, include tag so we can differentiate between other remote message pixels.
_Feature 1_

Fix RMF unique pixel: adding tag as part of unique type

---

app/src/main/res/layout/activity_show_on_app_launch_setting.xml
common/common-ui/src/main/java/com/duckduckgo/common/ui/view/listitem/RadioListItem.kt
common/common-ui/src/main/res/layout/view_radio_list_item.xml
common/common-ui/src/main/res/values/attrs-radio-list-item.xml
network-protection/network-protection-impl/src/main/res/layout/item_geoswitching_country.xml

Task/Issue URL: https://app.asana.com/0/1207908166761516/1208648215243996/f
Fixes the height of the options on the Show on App Launch screen to 48dp. As a result of this we should do a follow up to add the possibility to our OneLine and TwoLineListItems to allow for a `RadioButton`
This was done with minimal code changes to reduce any effect on the VPN country selection list. 
_Show on App Launch_
_VPN Location List_
|![Screenshot_20241029_181258](https://github.com/user-attachments/assets/97e6c3c0-d7a3-441c-ace8-54a21e459703)|![Screenshot_20241029_181003](https://github.com/user-attachments/assets/2782c2d8-54c2-47f0-9fcd-0b021db29819)

Show on App Launch: Fix option item height

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt

Task/Issue URL: https://app.asana.com/0/1207252092703676/1208638046607284/f 
_Feature 1_

Fix unresponsive Duck Player button in custom tabs

---

common/common-ui/src/main/java/com/duckduckgo/common/ui/themepreview/ui/component/ComponentViewHolder.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/view/listitem/DaxListItem.kt
common/common-ui/src/main/res/layout/component_one_line_item.xml
common/common-ui/src/main/res/layout/component_two_line_item.xml
common/common-ui/src/main/res/values/donottranslate.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1208662352677643/f
Support HTML tags in List Items

ADS: Support HTML tags in List Items text

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt

Task/Issue URL: https://app.asana.com/0/1174433894299346/1208667044987440/f
Ensure that the Omnibar code doesn’t hide the Omnibar view when the privacy config flag changes.
_From develop_
_From this branch_

Omnibar: React to Bottom Bar feature flag changes

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/BottomAppBarBehavior.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/TopAppBarBehavior.kt
app/src/main/res/layout/include_new_browser_tab.xml

Task/Issue URL: https://app.asana.com/0/1207418217763355/1208607329826486/f
This PR removes the extra gap in the new NTP. Even though it’s currently disabled, it might be enabled in the future and it might cause issues.
Before testing, please enable the new NTP by setting `internalAlwaysEnabled = true` in `NewTabPage`.

Fix: Remove extra gap from the NTP

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerScriptsJsMessaging.kt

Task/Issue URL: https://app.asana.com/0/0/1208637207606569/f
The DuckPlayer frontend will send an event when the landscape view is shown, this PR adds a pixel for it.
- Fire `duckplayer_landscape_layout_impressions` when the FE sends a telemetry event (https://app.asana.com/0/69071770703008/1208686513106880/f)
- iOS PR: https://github.com/duckduckgo/iOS/pull/3493
- ~install CSS at branch pr-releases/pr-1164~
- load DuckPlayer in landscape (or rotate)
- you should receive 1 event per page-load, and the pixel should fire.

Adding DuckPlayer Telemetry events

---

feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
feature-toggles/feature-toggles-internal/src/main/java/com/duckduckgo/examplefeature/internal/ui/FeatureToggleInventoryActivity.kt

Task/Issue URL: https://app.asana.com/0/1198194956794324/1208633884628758/f
Improve the (internal) feature flag inventory screen search logic:
Before:
* searches would filter feature flags that match the search text
After:
* searches filter feature flags that match the search text, but:
* if match is a top-level features, all sub-features are also considered a match (even if their name doesn't match)
* if match is a sub-feature, parent feature is also considered a match (even if its name doesn't match)
_Test_

Improve search logic in feature inventory screen

---

app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchActivity.kt

Task/Issue URL: https://app.asana.com/0/1207908166761516/1208685892092430/f 
- Disables Specific Url EditText if it Specific Url is not selected using updated disabled state from DS
- Saves user input for Specific Url when switching options
https://github.com/user-attachments/assets/92158d39-9ddc-43b0-81f3-77017a8ce767

Show on App Launch: Disable text entry when Specific Url not selected

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsViewModel.kt
autofill/autofill-impl/src/main/res/layout/content_autofill_save_new_credentials.xml
autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values/donottranslate.xml
autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml

Task/Issue URL: https://app.asana.com/0/1203822806345703/1208592982102639/f 
During Autofill Onboarding show "Not Now" as secondary button.
_Feature 1_

Show Not now as secondary button during autofill onboarding

---

app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchFeature.kt
app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208705964260532/f 
Defaults the feature toggle to off. I will raise a PR to add this to the remote config.
N/A

Show on App Launch: Set feature toggle to off by default

---

app/src/main/java/com/duckduckgo/app/browser/favicon/DuckDuckGoFaviconManager.kt
app/src/main/java/com/duckduckgo/app/sitepermissions/SitePermissionsActivity.kt
app/src/main/java/com/duckduckgo/app/sitepermissions/SitePermissionsAdapter.kt
app/src/main/java/com/duckduckgo/app/sitepermissions/SitePermissionsViewModel.kt
app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/PermissionsPerWebsiteViewModel.kt
app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/WebsitePermissionSettingOption.kt
app/src/main/res/layout/view_site_permissions_site.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/duckduckgo/app/sitepermissions/PermissionsPerWebsiteViewModelTest.kt
app/src/test/java/com/duckduckgo/app/sitepermissions/SitePermissionsViewModelTest.kt
site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsRepository.kt

Task/Issue URL: https://app.asana.com/0/1174433894299346/1208578724221048
This PR updates the Site Permissions screens to match the Figma designs
_Site Permissions_
_Site Permissions Removed on Fire Button (Fireproof)_
_Site Permissions Removed on Fire Button_
_Individual Site Permissions_
_Disable overall location permission_

Permissions: Site Permissions screen

---

app/src/main/java/com/duckduckgo/app/browser/favicon/DuckDuckGoFaviconManager.kt
app/src/main/java/com/duckduckgo/app/sitepermissions/SitePermissionsActivity.kt
app/src/main/java/com/duckduckgo/app/sitepermissions/SitePermissionsAdapter.kt
app/src/main/java/com/duckduckgo/app/sitepermissions/SitePermissionsViewModel.kt
app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/PermissionsPerWebsiteViewModel.kt
app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/WebsitePermissionSettingOption.kt
app/src/main/res/layout/view_site_permissions_site.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/duckduckgo/app/sitepermissions/PermissionsPerWebsiteViewModelTest.kt
app/src/test/java/com/duckduckgo/app/sitepermissions/SitePermissionsViewModelTest.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/view/dialog/TextAlertDialogBuilder.kt
common/common-ui/src/main/res/color/text_input_color_selector.xml
site-permissions/site-permissions-api/src/main/java/com/duckduckgo/site/permissions/api/SitePermissionsDialogLauncher.kt
site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerImpl.kt
site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsRepository.kt

Task/Issue URL: https://app.asana.com/0/1174433894299346/1208578724221050/f
Update Camera and Microphone dialogs to use a checkbox
It also updates the DRM dialog to match the other dialogs
_Camera - Allow Remember + System Permission Allowed_
_Camera - Allow  + System Permission  Allowed_
_Camera - Deny Remember_
_Camera - Deny_
_Microphone- Allow Remember + System Permission Denied_
_Microphone - Allow  + System Permission Denied_
_Microphone - Deny Remember_
_Microphone - Deny_
_DRM - Allow Remember_
_DRM - Allow_
_DRM - Deny Remember_
_DRM - Deny_

Permissions: Update DRM, Camera and Microphone dialogs

---

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/config/WgVpnRoutes.kt

Task/Issue URL: https://app.asana.com/0/1198194956794324/1208714463179856/f
10.x.x.x range (traffic) should go through the VPN when local networks are included.
_Test_

Include 10.x.x.x local net traffic through VPN

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
broken-site/broken-site-api/src/main/java/com/duckduckgo/brokensite/api/BrokenSitePrompt.kt
broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSitePromptInMemoryStore.kt
broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSitePromptRCFeature.kt
broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSiteReportRepository.kt
broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/RealBrokenSitePrompt.kt
broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/di/BrokenSiteModule.kt
broken-site/broken-site-impl/src/test/java/com/duckduckgo/brokensite/impl/RealBrokenSitePromptTest.kt
broken-site/broken-site-impl/src/test/java/com/duckduckgo/brokensite/impl/RealBrokenSiteReportRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/1204920898013511/1208572901396836/f 
**pre-requisites:** Onboarding is completed, brokenSitePrompt RC flag is on (needs app restart)
_Feature 1_
_Feature 1_

Handle user refreshes

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
broken-site/broken-site-api/src/main/java/com/duckduckgo/brokensite/api/BrokenSitePrompt.kt
broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSitePomptDataStore.kt
broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSitePromptInMemoryStore.kt
broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSiteReportRepository.kt
broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/RealBrokenSitePrompt.kt
broken-site/broken-site-impl/src/test/java/com/duckduckgo/brokensite/impl/RealBrokenSitePromptTest.kt
broken-site/broken-site-impl/src/test/java/com/duckduckgo/brokensite/impl/RealBrokenSiteReportRepositoryTest.kt
common/common-utils/src/main/java/com/duckduckgo/common/utils/CurrentTimeProvider.kt

Task/Issue URL: https://app.asana.com/0/1204920898013511/1208572901396846/f 
> [!WARNING]
> **pre-requisites:** Onboarding is completed, brokenSitePrompt RC flag is on (needs app restart)
> [!TIP]
> Cooldown is 7 days, and dismissStreakResetDays is 30 days. For easier testing, apply this patch (adds 7 seconds and 30 seconds instead) https://app.asana.com/app/asana/-/get_asset?asset_id=1208700930411217. Fresh install with this patch
> [!TIP]
> Filter logs for Next shown date to check when the prompt can be shown again
_Feature 1_
_Feature 1_
_Feature 1_
_Feature 1_
_Feature 1_
_Feature 1_
_Feature 1_
_Feature 1_
> [!WARNING]
> If you haven't applied the patch before, it's required for this test. https://app.asana.com/app/asana/-/get_asset?asset_id=1208700930411217. Fresh install and …

Add limiting logic

---

subscriptions/subscriptions-impl/build.gradle
subscriptions/subscriptions-impl/lint-baseline.xml
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/repository/AuthRepository.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/serp_promo/SerpPromo.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/store/SubscriptionsDataStore.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/RealAuthRepositoryTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/serp_promo/FakeSerpPromo.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/serp_promo/SerpPromoTest.kt
subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/settings/CopySubscriptionDataView.kt

Task/Issue URL: https://app.asana.com/0/1198194956794324/1208264562025856/f
Enable SERP Promo for PPro
_Test_

Enable SERP promo for PPro

---

package-lock.json
package.json

Update content scope scripts to version 6.32.0

---

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillFeature.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/gpm/feature/AutofillImportPasswordSettings.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/importing/gpm/feature/AutofillImportPasswordConfigStoreImplTest.kt

Task/Issue URL: https://app.asana.com/0/608920331025315/1207446004465151/f 
Sets up new remote config handling for autofill subfeature: `canImportFromGooglePasswordManager`
This dictates whether we offer up the option to import passwords directly from Google Password Manager or not. 
Additional config:
| Key | Type | Description |
|--------|--------|--------|
| `launchUrl` | `String` | The initial URL to launch for Google Password Manager |
| `javascriptConfig` | `String` | The config to pass onto the JS layer handling GPM imports |
- QA optional; they'll be tested more easily in the branches above
**Optional**
```
Index: privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeatureName.kt
Subsystem: …
```

Add feature flag for importing passwords via Google Password Manager

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
duckplayer/duckplayer-api/src/main/java/com/duckduckgo/duckplayer/api/DuckPlayer.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
duckplayer/duckplayer-impl/src/test/kotlin/com/duckduckgo/duckplayer/impl/RealDuckPlayerTest.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1208700688753511/f
_Feature 1_
_Feature 1_
_Feature 1_
_Feature 1_

Remove origin param from Duck Player

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/BottomAppBarBehavior.kt

Task/Issue URL: https://app.asana.com/0/1207418217763355/1208722298581325/f
This PR fixes an issue with bottom omnibar scrolling.
_The fix_
_Smoke tests_

Fix and optimize the bottom bar scrolling

---

app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchActivity.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/view/text/DaxTextInput.kt
common/common-ui/src/main/res/layout/component_text_input_view.xml
common/common-ui/src/main/res/values/attrs-text-input.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1208740714999313/f 
Separates non-editable state from disabled state of `DaxTextInput`. An input can be:
- non-editable but enabled (i.e., read-only text that isn't greyed out, with buttons in the view still working)
- disabled (i.e., non-editable and greyed out, and all buttons disabled too)
**Passwords**
**App launch setting**
**Anything else that might be affected?**

Separate disabled state from non-editable state for DaxTextInput

---

node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1208752777730434/f 
----- 

Update content scope scripts to version 6.33.0

---

app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsPixelName.kt

Task/Issue URL: https://app.asana.com/0/0/1208750400255371/f
PIxels for the new site permission dialogs
_Impression pixel_
_Click pixel_
Notes: Pixels don’t include ATB

Site Permissions: Pixels

---

anvil/anvil-annotations/src/main/java/com/duckduckgo/anvil/annotations/ContributesRemoteFeature.kt
anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/blocklist/BlockList.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/blocklist/BlockListInterceptorApiPlugin.kt
app/src/test/java/com/duckduckgo/app/brokensite/api/BrokenSiteSubmitterTest.kt
app/src/test/java/com/duckduckgo/app/browser/refreshpixels/RefreshPixelSenderTest.kt
app/src/test/java/com/duckduckgo/app/trackerdetection/blocklist/BlockListInterceptorApiPluginTest.kt
app/src/test/java/com/duckduckgo/app/trackerdetection/blocklist/BlockListPrivacyTogglePluginTest.kt
autofill/autofill-impl/build.gradle
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/gpm/feature/AutofillImportPasswordSettings.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/importing/gpm/feature/AutofillImportPasswordConfigStoreImplTest.kt
common/common-test/build.gradle
common/common-test/src/main/java/com/duckduckgo/common/test/json/JSONObjectAdapter.kt
feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureSettings.kt
feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
feature-toggles/feature-toggles-impl/lint-baseline.xml
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt

Task/Issue URL: https://app.asana.com/0/1198194956794324/1208740919623939/f
We want to support `settings` for all top-level and sub-features because we can define schemas and validate them in the remote config
As a result we can remove the sub-feature `config`
_Test_

Support settings for top-level and sub-feature and remove sub-feature config

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208660560293084/f
Fire skip network pixel only if onboarding is still active
_Send pixel_
_Ignore pixel_
_Pixel **not** fired_

Edit temporary pixel for not showing trackers network dialog

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PProUpsellBannerPlugin.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PproUpsellDisabledMessagePlugin.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PproUpsellRevokedMessagePlugin.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/SubscriptionsExt.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PProUpsellBannerPluginTest.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PproUpsellDisabledMessagePluginTest.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PproUpsellRevokedMessagePluginTest.kt
subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/Subscriptions.kt
subscriptions/subscriptions-dummy-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsDummy.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriberMatchingAttribute.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriberMatchingAttributeTest.kt

Task/Issue URL: https://app.asana.com/0/1205648422731273/1208750628818068/f
This is a preparation for the upcoming behavior change of getAccessToken() - it will no longer guarantee a non-null response for a signed-in user.
QA-optional

add isSignedIn() to Subscriptions interface

---

app/src/main/java/com/duckduckgo/app/dispatchers/IntentDispatcherViewModel.kt
app/src/test/java/com/duckduckgo/app/dispatchers/IntentDispatcherViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1208671518894266/1207149305479429/f
This change ensures that if DDG browser is selected to handle the browsable intent, and the URL is a `duckduckgo.com` domain, a new browser tab will be opened instead of an "embedded" Custom Tab.
There 3 easy ways to test, all require DDG to be the default browser application:
1. Use an external app like the [Android Browser Helper](https://github.com/GoogleChrome/android-browser-helper/) (method used in the video below).
2. Go to Settings -> Developer Settings -> Custom Tabs.
3. Inject an intent from ADB, for example:
```shell
adb shell am start -a android.intent.action.VIEW -d "https://duckduckgo.com/?q=test" --es "android.support.customtabs.extra.SESSION" "" com.duckduckgo.app.browser
```
| …

Open intents with direct DDG URL in a new browser tab, instead of Custom Tab

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1208772371483449/f 
----- 

Update content scope scripts to version 6.35.0

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/1208781796802502/1208781796802502
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v11.5.0
Updates Autoconsent to version [v11.5.0](https://github.com/duckduckgo/autoconsent/releases/tag/v11.5.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v11.5.0/CHANGELOG.md)
This release has been tested during Autoconsent development. You can check the release notes for more information.
1. Make sure that there's no unexpected failures in CI checks
2. (optional) smoke test some of the sites mentioned in the release notes
3. If there are problems, reach out to a CPM DRI

Update autoconsent to v11.5.0

---

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
experiments/experiments-impl/src/main/java/com/duckduckgo/experiments/impl/ReturningUserToggleTargetMatcher.kt
experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/ReturningUserToggleTargetMatcherTest.kt
feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
feature-toggles/feature-toggles-impl/lint-baseline.xml
feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/RealFeatureTogglesCallback.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/FeatureTogglesTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/fakes/FakeFeatureTogglesCallback.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/impl/LocaleToggleTargetMatcherTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/impl/RealFeatureTogglesCallbackTest.kt
feature-toggles/feature-toggles-internal-api/src/main/java/com/duckduckgo/feature/toggles/internal/api/FeatureTogglesCallback.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsToggleTargetMatcherPlugin.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/SubscriptionsToggleTargetMatcherPluginTest.kt

Task/Issue URL: https://app.asana.com/0/1198194956794324/1208710375047087/f
This PR adds couple new targets for FF, ie. isReturningUser and isPrivacyProEligible, both of type `Boolean`
The PR also modularizes the way we hande targets, turning them into plugins so that it's easier in the future to add targets without (almost) touching the toggles API
Added unit and integration tests 
_Test new targets_

Add isReturningUser and isPrivacyProEligible targets and modularize target management

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/engagement/store/AutofillEngagementBucketing.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/engagement/store/AutofillEngagementRepository.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/gpm/feature/AutofillImportPasswordSettings.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/gpm/webflow/ImportGooglePasswordUrlToStageMapper.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/gpm/webflow/ImportGooglePasswordsWebFlowFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/gpm/webflow/ImportGooglePasswordsWebFlowViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/ImportPasswordsPixelSender.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/google/ImportFromGooglePasswordsDialog.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/google/ImportFromGooglePasswordsDialogViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/survey/AutofillSurvey.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/engagement/store/DefaultAutofillEngagementBucketingTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/importing/gpm/feature/AutofillImportPasswordConfigStoreImplTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/importing/gpm/webflow/ImportGooglePasswordUrlToStageMapperImplTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/importing/gpm/webflow/ImportGooglePasswordsWebFlowViewModelTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/google/ImportFromGooglePasswordsDialogViewModelTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/survey/AutofillSurveyImplTest.kt

Task/Issue URL: https://app.asana.com/0/608920331025315/1208787586139232/f 
Adds metrics around the import password flow. To support this in a flexible way, it also allows for the url mappings to be defined remotely for which stage of the flow a user dropped out at if they didn't go all the way through; if we ever need to, can override the default url mappings.
Logcat filter: `message~:"Pixel sent: autofill_import_google_passwords"`
**Setup**
**Cancelling the user journey**
**Succeeding**
**Overflow menu**
**Encrypted passphrase scenario**
**CSV parsing scenario**
**URL mapping via remote config**
**Selectively disabling JS injection**

Add pixels for importing google passwords metrics

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1208822553682950/f 
----- 

Update content scope scripts to version 6.39.0

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/1201807753394693/1208788897307853/f
Dismiss in-context Dax dialog when opening new tab
_Tab Icon_
_Long press in Tab Icon_

Onboarding: Dismiss in-context Dax dialog when opening new tab

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt

Task/Issue URL: https://app.asana.com/0/69071770703008/1208808769852413/f
Add a pixel for AppTP MAU.
The pixel fires at most once every 28 days
You may want to change the polici to `REPLACE` in `scheduleDeviceShieldStatusReporting()` to trigger the pixel on every app  `onCreate`
_Test_

Add AppTP WAU pixel

---

.github/actions/check-for-changes-since-tag/action.yml
.github/workflows/release_nightly.yml

Task/Issue URL: https://app.asana.com/0/1174433894299346/1208527152986496
Currently we make nightly releases daily, even if there are no new changes in develop.
This PR fixes that, so we only make nightly releases when there are new commits since the last tag.
See task for examples of runs

GHA: Only execute nightly if changes made

---

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncFeature.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixelParamRemovalPlugin.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeActivity.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModel.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherActivityViewModel.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherDeviceActivity.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1208755822305614/f 
Adds metrics around dialog engagement and errors.
_single device flow metrics_
_multiple devices flow metrics_
_error metrics_

add metrics for account switching

---

sync/sync-impl/lint-baseline.xml
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncFeature.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixelParamRemovalPlugin.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeActivity.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModel.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherActivityViewModel.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherDeviceActivity.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncAccountRepositoryTest.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModelTest.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherDeviceViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1203822806345703/1208755822305613/f 
Introduces logic to switch the user account if sync has only 1 device connected.
When multiple devices connected, we still ask the user.
_Feature 1_
_Feature 1_

Auto switch account if user only has 1 device connected when login

---

sync/sync-impl/lint-baseline.xml
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncFeature.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixelParamRemovalPlugin.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeActivity.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModel.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivity.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncConnectActivity.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncLoginActivity.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherActivityViewModel.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherDeviceActivity.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/EnterCodeContract.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/SyncWithAnotherDeviceContract.kt
sync/sync-impl/src/main/res/values/donottranslate.xml
sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncAccountRepositoryTest.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModelTest.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherDeviceViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1208755822305612/f 
When a Sync signed in user reads a recovery code, ask them to confirm if they want to switch account.
Includes:
- Remote FF (disabled by default until implementation is completed)
- Logic to handle that scenario when reading a QR code or introducing text manually.
_Feature 1_
_Feature 2_ (continuation from previous test)

Ask user to swith account when reading code while signed in

---

remote-messaging/remote-messaging-api/src/main/java/com/duckduckgo/remote/messaging/api/RemoteMessagingRepository.kt
remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/AppRemoteMessagingRepository.kt
remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/matchers/ShownMessageMatcher.kt
remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/matchers/ShownMessageMatcherTest.kt

Task/Issue URL: https://app.asana.com/0/1207619243206445/1208819791054807/f
Adds a new matching attribute to filter messages based on previously shown messages
_Feature 1_

RMF: shown message matching attribute implementation

---

app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208815135507669/f
Added a null check to the ViewState when attempting to update via observing the selected ShowOnAppLaunch option. 
No UI changes

Show on App Launch: Fix option observation race condition 

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208833556472473/f
Add privacy pro onboarding dialog under a disabled feature flag
_FF disabled (default)_
_FF enabled_

Onboarding: Privacy Pro dialog FF

---

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/volume/NetpDataVolumeStore.kt

Task/Issue URL: https://app.asana.com/0/1198194956794324/1208858014826586/f
Guard against possible crashes on NetpDataVolumeStore (we've seen single user spikes)
NA, smoke test vpn data volume

Guard against crashes in NetpDataVolumeStore

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
privacy-dashboard/privacy-dashboard-api/src/main/java/com/duckduckgo/privacy/dashboard/api/ui/PrivacyDashboardHybridScreenParams.kt
privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridActivity.kt

Task/Issue URL: https://app.asana.com/0/1163321984198618/1208852264436742/f 
Set report flow to form (not menu) when launching hybrid site from the prompt
Rename pixels according to spec
_Feature 1_

Set report flow to form when launchiung hybrid site from the prompt

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1208868850993344/f 
----- 

Update content scope scripts to version 6.41.0

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/onboarding/store/OnboardingStore.kt
app/src/main/java/com/duckduckgo/app/onboarding/store/OnboardingStoreImpl.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208778105886340/f
Add temporary pixel for counting display of visit site suggestions dialog
_Feature 1_

Temporary pixel for visit site suggestions CTA display count

---

app/src/androidTest/java/com/duckduckgo/app/browser/logindetection/BrowserTabFireproofDialogsEventHandlerTest.kt
app/src/androidTest/java/com/duckduckgo/app/fire/fireproofwebsite/data/FireproofWebsiteRepositoryImplTest.kt
app/src/androidTest/java/com/duckduckgo/app/location/data/LocationPermissionsRepositoryImplTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/db/NetworkLeaderboardDaoTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/db/UserAllowListDaoTest.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
app/src/test/java/com/duckduckgo/tabs/db/TabsDaoTest.kt
app/src/test/java/com/duckduckgo/tabs/model/TabDataRepositoryTest.kt
common/common-test/build.gradle
common/common-test/src/main/java/com/duckduckgo/common/test/LiveDataTestExtensions.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1208839731155341/f 
Fixes flaky test due time reference.
Moves it as jvm.
_Feature 1_

Move Android test as jvm test: TabDataRepository, and fix flaky test

---

autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/RealAutoconsent.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/store/AutoconsentSettingsDataStore.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/Fakes.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1208826230694543/f 
Fixes autoconsent config not refreshed untill app restart
_Feature 1_

Fixes autoconsent remote config not refreshed until app restart

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt

Task/Issue URL: https://app.asana.com/0/1205648422731273/1208883453990680/f
This PR fixes a bug that puts subscription settings UI in an incorrect state after removing email from the subscription.

Refresh v2 access token when email is removed from subscription

---

.maestro/privacy_tests/7_-_Browser_restart_mid-session.yaml

Task/Issue URL: https://app.asana.com/0/488551667048375/1208915665635635/f 
Simplifies a UI test which currently kills the app by activating multi-tasking view and swiping the app away. Replaces with a method which also works with gesture navigation.
- qa optional
- [optional] run `.maestro/privacy_tests/7_-_Browser_restart_mid-session.yaml` where gesture navigation on and off (e.g., on emulators running API 30 and API 34 which have different nav behaviours by default)

Ensure maestro test works with and without gesture navigation

---

.maestro/autofill/steps/search_logins.yaml

Task/Issue URL: https://app.asana.com/0/488551667048375/1208921295229158/f 
Change to UI maestro test steps: Change order of banner dismissal in password management screen to reflect the priority order they would be shown.

Switch order of autofill banner dismissals in maestro test

---

.maestro/app_tp/app_tp_onboarding.yaml

Task/Issue URL: https://app.asana.com/0/488551667048375/1208918464533042/f 
Change maestro release test for AppTP to handle when banner might not show
-  QA optional

Fix flakey release test for AppTP, banner won't always show

---

.maestro/bookmarks/ensure_bookmarks_can_be_added_and_deleted.yaml
.maestro/bookmarks/open_bookmark_and_navigate_back.yaml
.maestro/bookmarks/open_bookmark_in_folder_and_navigate_back.yaml
.maestro/browsing/visit_site.yaml
.maestro/favorites/favorites_bookmarks_add.yaml
.maestro/favorites/favorites_bookmarks_delete.yaml
.maestro/fire_button/fire_during_onboarding.yaml
.maestro/tabs/open_multiple_tabs.yaml

Task/Issue URL: https://app.asana.com/0/488551667048375/1208921164205364/f 
Replace the instances where we look for a soft keyboard button with a specific ID and directly press enter key
**Before**
```
tapOn:
id: "com.google.android.inputmethod.latin:id/key_pos_ime_action"
```
**After**
```
- pressKey: Enter
```
- QA optional as long as https://github.com/duckduckgo/Android/actions/runs/12197659365 passes
- If you want to test, run one or more of the changed test files

In maestro tests, use the press enter command instead of using soft keyboard

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/1208921166781775/1208921166781775
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v12.2.0
Updates Autoconsent to version [v12.2.0](https://github.com/duckduckgo/autoconsent/releases/tag/v12.2.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v12.2.0/CHANGELOG.md)
This release has been tested during Autoconsent development. You can check the release notes for more information.
1. Make sure that there's no unexpected failures in CI checks
2. (optional) smoke test some of the sites mentioned in the release notes
3. If there are problems, reach out to a CPM DRI

Update autoconsent to v12.2.0

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1208930104860728/f
Added a return statement after handling shortcut URLs to prevent unintended processing of the same URL through multiple paths.
_Shortcut Handling_
No UI changes

Fix Show on App Launch opening after opening a website shortcut

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt

Task/Issue URL: https://app.asana.com/0/1205648422731273/1208929009317918/f
This PR fixes an issue where with auth v2 enabled, users may see an error popup instead of the payment method selection if they cancel and retry a subscription purchase. 
QA-optional

Fix subscription purchase error after cancelling purchase flow

---

.github/workflows/end-to-end-robintest.yml

Task/Issue URL: https://app.asana.com/0/0/1208926527656098/f 
Enables nightly UI builds to execute in Robin. These are going to run in parallel to the nightly UI builds in Maestro Cloud for some time (probably a number of weeks).
- tests are pretty close to being all-green, but with a small amount of flakiness 
- waiting for `retry` functionality to become available which will help them to be reliably green
- failure alerting is deliberately disabled for now (until `retry` functionality available)
Can see an example of it running successfully here: https://github.com/duckduckgo/Android/actions/runs/12236736123

Enable nightly builds for execution in robin

---

duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerLocalFilesPath.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1208851110314077/f 
Smoke test Duck Player

Fix ANR in DuckPlayerLocalFilesPath

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1205782002757341/1208820359395089/f
Looks at this task for different scenarios: https://app.asana.com/0/1174433894299346/1208812333027437/f
_Pixel for clearing address bar - Site_
_Pixel for clearing address bar - SERP_
_Pixel for clearing address bar - NTP_
_Swipe gesture to close keyboard - Site_
_Swipe gesture to close keyboard - SERP_
_Manually close keyboard  + Scroll- Site_
_Manually close keyboard  + Scroll- SERP_
_Close keyboard - Site_
_Close keyboard - SERP_

Omnibar: Pixel and Clear action regressions

---

app/src/androidTest/java/com/duckduckgo/espresso/privacy/RequestBlockingTest.kt
app/src/androidTest/java/com/duckduckgo/espresso/privacy/SurrogatesTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1208945103446235/f
Fixes the tests which are failing due to a new screen being presented when privacy protections are disabled. The fix is simply backing out of those screens as part of the test scripts.

Fix privacy tests which are currently getting interrupted with the privacy toggle check screen

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt

Task/Issue URL: https://app.asana.com/0/1207418217763355/1205772199506591/f
This fix prevents showing the find-in-page bar when changing the omnibar position.

Fix: Don't show the find-in-page bar if it's hidden

---

network-protection/network-protection-impl/src/main/java/com/wireguard/android/backend/GoBackend.kt
versions.properties

Task/Issue URL: https://app.asana.com/0/1142021229838617/1208368538104397/f
This PR bumps the our netguard (vpn) library to 1.7.0
Also adds the `recordMalwareBlock` callback, called from native when malware is blocked.
_Test_

Record malware blocks

---

autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_list_mode.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1208758825735780/f 
This PR tweaks the layout params for the password recycler view so that the whole view content, already encapsulated in a `NestedScrollView`, is scrollable.
- Before, you had to scroll on the list view directly, and then only the passwords list would scroll while the rest of the views above were fixed. 
- Now, the entire view (including the toggle) is scrollable
### New behavior

Allow scrolling all of the password management list mode screen

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt

Task/Issue URL: https://app.asana.com/0/1174433894299346/1208763092216879/f
This PR adds an origin to the pixels sent when the tab manage is open
_From SERP_
_From any site_
_From new tab_

Tab Manager: Origin pixels

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModel.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1205648422731273/1208993054177524/f
In subscription settings, we display a date when subscription expires or renews. It is currently using fixed pattern `MMMM dd, yyyy`, which is correct in USA, but potentially confusing or grammatically incorrect in other parts of the world.
QA-optional
|![subs-active-date-format-broken](https://github.com/user-attachments/assets/afcc3342-d236-4a92-bc13-2dbf08a4b791)|![subs-active-date-format-fixed](https://github.com/user-attachments/assets/94e64c68-9179-4970-8240-7a29a38532d5)|
|![subs-expired-date-format-broken](https://github.com/user-attachments/assets/57c2f37a-599e-415e-a6c4-1683ea2d22c6)|![subs-expired-date-format-fixed](https://github.com/user-attachments/assets/8b2f0f6 …

Fix date format localization in subscription settings

---

app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1208737359937198/f 
Moves to io main threads db access detected in CtaViewmodel 
_Feature 1_

move out of main cta viewmodel checks

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/LegacyProSettingViewModel.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingViewModel.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/LegacyProSettingViewModelTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingViewModelTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1201807753394693/1209007672205184/f
Update some subscriptions models in order to support free trials on mobile:
- `SubscriptionOffer` model
- `OptionsJson` model
- `getSubscriptionOffer()` method
_Pre steps_
_Privacy Pro Eligible US_
_Privacy Pro Eligible ROW (Optional)_
_Privacy Pro No Eligible_

Privacy Pro Subscriptions: Update some internal models and methods

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/AutofillRuntimeConfigProvider.kt

Task/Issue URL: https://app.asana.com/0/1200905986587319/1209069285792741/f
Optimized string manipulation within getRuntimeConfiguration function.
Smoke test for autofill.

Android Crash: java.lang.OutOfMemoryError - com.duckduckgo.autofill.impl.configuration.RealAutofillRuntimeConfigProvider.getRuntimeConfiguration

---

app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherAdapter.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209069285792730/f
Moved file operations to background.

Android ANR: com.duckduckgo.app.tabs.ui.TabSwitcherAdapter.loadTabPreviewImage

---

app/src/main/res/layout/fragment_browser_tab.xml

Task/Issue URL: https://app.asana.com/0/715106103902962/1209003862601172/f
Fixed scrolling issue on focused view.
See task description for video https://app.asana.com/0/715106103902962/1209003862601172/f
Steps to reproduce:
Steps to test the fix:

Android Bug: Address Bar can be hidden on NTP by user and doesn't reappear until background/foreground

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209095880220827/f 
----- 

Update content scope scripts to version 6.44.0

---

CONTRIBUTING.md
STYLEGUIDE.md

Task/Issue URL: https://app.asana.com/0/1202552961248957/1209069202192275
Update styleguide to match current state.

Update Styleguide file

---

app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/java/com/duckduckgo/app/settings/NewSettingsViewModel.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/pixels/AutoConsentPixel.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/ui/AutoconsentSettingsViewModel.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/ui/AutoconsentSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1207908166761516/1208880593716452/f
Adds new pixels to Settings where we were missing some compared to iOS. See task for more details.
Prerequisite: Enable `newSettings` feature toggle
_Cookie Pop-Up Protection_
_Next Steps: Address Bar Position_
_Next Steps: Enable Voice Search_
N/A

Update Settings: Add new pixels

---

autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_list_mode.xml

Task/Issue URL: https://app.asana.com/0/608920331025315/1209106756565265/f 
Reverts changes made in https://github.com/duckduckgo/Android/pull/5377 as it introduces performance issues on the password management screen with larger password list sizes. Depending on the device / list size, it can be crippling performance.
For contrast, if you try this on `develop` you will notice a large perf issue.

Revert "Allow scrolling all of the password management list mode screen"

---

node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.css
node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209113171823443/f 
----- 

Update content scope scripts to version 7.2.0

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
duckplayer/duckplayer-impl/src/test/kotlin/com/duckduckgo/duckplayer/impl/RealDuckPlayerTest.kt

Task/Issue URL: https://app.asana.com/0/1203249713006009/1209098737366580/f
Only load Duck Player if YouTube requests come from mainFrame
Do not open Duck Player in new tab if the original link already opened a new tab
_Feature 1_
_Feature 2_
_Feature 3_
_Feature 4_

Only navigate to Duck Player if YT was loaded in mainframe

---

app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt
app/src/test/java/com/duckduckgo/app/browser/webview/RealMaliciousSiteBlockerWebViewIntegrationTest.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteModule.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/MaliciousSiteRepository.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/db/MaliciousSiteDao.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/embedded/MaliciousSiteEmbeddedDataProvider.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/network/MaliciousSiteService.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/domain/RealMaliciousSiteProtection.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/domain/RealMaliciousSiteProtectionTest.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1207151848931036/f 
Add algorithm to determine whether a URL is malicious or not. Details are described [here](https://app.asana.com/0/481882893211075/1207273224076497/f) (Approach A, _"Implement MaliciousSiteDetection client library that"_ section). API was discussed [here](https://app.asana.com/0/1202552961248957/1208934234411796/f)
_Feature 1_
n/a, toast is temporary, an error page will be added in the next PR

Add blocking algorithm (isMalicious)

---

app/src/main/java/com/duckduckgo/app/tabs/store/TabStatsBucketing.kt
app/src/test/java/com/duckduckgo/app/tabs/store/TabStatsBucketingTest.kt

Task/Issue URL: https://app.asana.com/0/1207418217763355/1208798050088814/f
This PR removes the temporary high-count buckets from a tab-count pixel so that the highest one is 81+, as agreed in the privacy review.

Reduce the high-count buckets

---

app/src/main/java/com/duckduckgo/app/browser/weblocalstorage/WebLocalStorageManager.kt
app/src/test/java/com/duckduckgo/app/browser/DuckDuckGoWebLocalStorageManagerTest.kt

Task/Issue URL: https://app.asana.com/0/1200204095367872/1209128100809324/f
- Closes the `DBIterator` after local storage has been cleared.
- Also keeps the DB open and updates the DB initialization to be `Lazy`.
_Filter logcat by WebLocalStorageManager_

Ensure LevelDB Iterator is closed

---

app/src/androidTest/java/com/duckduckgo/app/browser/WebViewDataManagerTest.kt
app/src/main/java/com/duckduckgo/app/browser/WebDataManager.kt

Task/Issue URL: https://app.asana.com/0/1200204095367872/1209144640221025/f
- Currently the `webLocalStorage` toggle only toggles `clearWebViewDirectories()`, it should also toggle `clearWebStorage()`.
- Also only sends the clearWebStorage crash pixel for internal builds.
_Filter by WebLocalStorageManager_

Add feature toggle around clearWebStorage

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209143210335480/f
This PR fixes an issue where subscription details aren't fetched from BE after activating subscription using email. The issue only occurs when auth v2 is enabled.

Fix subscription activation using email when auth v2 is enabled

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt

Task/Issue URL: https://app.asana.com/0/1205278999335242/1208163185498327/f
Remove temporary pixel when skipping major network onboarding dialog when Duck Player dialog is shown
_Pixel removed_

Remove temporary pixel when not showing trackers network dialog

---

node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Update content scope scripts to version 7.6.0

---

.github/workflows/docs.yml

Task/Issue URL: https://app.asana.com/0/488551667048375/1209176012992017/f
CI is failing because our action is using a deprecated version of upload artifact.

GHA: Update upload artifact version

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/1209184566247340/1209184566247340
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v12.6.0
Updates Autoconsent to version [v12.6.0](https://github.com/duckduckgo/autoconsent/releases/tag/v12.6.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v12.6.0/CHANGELOG.md)
This release has been tested during Autoconsent development. You can check the release notes for more information.
1. Make sure that there's no unexpected failures in CI checks
2. (optional) smoke test some of the sites mentioned in the release notes
3. If there are problems, reach out to a CPM DRI

Update autoconsent to v12.6.0

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/onboarding/store/OnboardingStore.kt
app/src/main/java/com/duckduckgo/app/onboarding/store/OnboardingStoreImpl.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt

Task/Issue URL: https://app.asana.com/0/1205278999335242/1208790610656152/f
Remove temporary pixel for counting display of visit site suggestions dialog

Remove temporary pixel when visit site dialog is shown

---

package-lock.json
package.json

Update content scope scripts to version 7.7.0

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/duckplayer/DuckPlayerJSHelper.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerScriptsJsMessaging.kt

Task/Issue URL: https://app.asana.com/0/1201141132935289/1209187970943576/f
Removal of temporary pixel.
The FE will still send an event, but it will no-op now, as designed :)
_Feature 1_

duckplayer: revert landscape impression pixel

---

voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/VoiceSearchActivityLauncher.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1209201227256746/f
Ensure late property is init before using it

Check late property is isInitialized

---

node_modules/@duckduckgo/privacy-dashboard/build/app/public/js/base.js
package-lock.json
package.json
privacy-dashboard/privacy-dashboard-api/src/main/java/com/duckduckgo/privacy/dashboard/api/ui/PrivacyDashboardHybridScreenParams.kt
privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/pixels/PrivacyDashboardPixels.kt
privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridActivity.kt
privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModel.kt
privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardJavascriptInterface.kt
privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardRenderer.kt
privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardRendererFactory.kt
privacy-dashboard/privacy-dashboard-impl/src/test/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModelTest.kt
privacy-dashboard/privacy-dashboard-impl/src/test/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardRendererTest.kt

Task/Issue URL: https://app.asana.com/0/0/1209173355503844/f
- Implements Privacy Dashboard message ReportBrokenSiteShown
- New pixels:
- `m_report-broken-site_shown` triggered when the broken site form is presented
- `m_report-broken-site_sent` triggered when the broken site form is sent. This is fired alongside the existing `epbf` pixel, but without any of the form data.
1. Invoke the breakage form in the two possible ways:
- Open the Privacy Dashboard and click on "Report a problem with this site"
- Open the app menu ••• and click on "Report Broken Site” (iOS)
2. Confirm that the pixel `m_report-broken-site_shown` was fired
3. Submit a report
4. Confirm that the pixels `epbf` and `m_report-broken-site_sent` were fired
N/A

Native handing of ReportBrokenSiteShown message

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt

Task/Issue URL: https://app.asana.com/0/1205648422731273/1209217826294375/f
/api/subscription endpoint currently returns 400 when no subscription is found, but that will change to 404. We should handle both 400 and 404 for now. 
QA-optional

Handle 404 from /api/subscription

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/extendedonboarding/ExtendedOnboardingFeatureToggles.kt
app/src/main/res/values/donottranslate.xml
app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt

Task/Issue URL: https://app.asana.com/0/0/1209206973663840/f
Remove logic added for Privacy Pro CTA copy test
_Privacy Pro eligible user, device locale set to `en-US`_
_Privacy Pro eligible user, device locale set to something other than `en-US`_
_Privacy Pro NOT eligible user_

Remove Privacy Pro CTA test

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt

Task/Issue URL: https://app.asana.com/0/1205648422731273/1209217826294377/f
This PR ensures JWKs are fetched before refreshing auth v2 tokens. Existing refresh token may be invalidated upon obtaining new one. If fetching JWKs fails for any reason, the app can't validate and store new token and is left with an invalid refresh token.
QA - optional

Avoid auth v2 refresh token reuse on JWKs fetch error

---

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModel.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherActivityViewModel.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/SyncAccountFixtures.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModelTest.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherDeviceViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1200156640058969/1209059053489790/f 
Ensure we send a switch pixel only when the user has changed to another sync account.
!! In order to test this you will need 2 devices, and add filter in logcat to only visualize pixels
_Feature 1_
_Feature 2_

Send switch pixel only when user changes to a different sync account

---

app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/api/TrackerListService.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/blocklist/BlockList.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/blocklist/BlockListInterceptorApiPlugin.kt
app/src/test/java/com/duckduckgo/app/trackerdetection/blocklist/BlockListInterceptorApiPluginTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209138858416176/f 
This PR reenables the blocklist feature but this time checking the full tds URL rather than the base url only.

Reenable blocklist experiment feature

---

.github/workflows/ps-review-analysis.yml
scripts/ps-analysis/ps_review_anomaly.py

Task/Issue URL: https://app.asana.com/0/1198194956794324/1209186880742773/f
Improvements to the PS review analysis automation
* print information for all star revies, not only anomalies
* reviews are not shown if z-score is negative
* added z-score information
* added info table to know how to interpret data
* added visuals to spot anomalies
* generate the report later in the day so that it includes more reviews
Run workflow for this branch and verify the task is created properly. If the task was already created it'll need to be closed, else creation will be skipped.

Improvements to the PS review script

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/duckchat/DuckChatJSHelper.kt
app/src/main/java/com/duckduckgo/app/browser/duckchat/DuckChatPreferencesStore.kt
app/src/main/java/com/duckduckgo/app/browser/webview/WebViewActivity.kt
app/src/test/java/com/duckduckgo/app/browser/duckchat/RealDuckChatJSHelperTest.kt
app/src/test/java/com/duckduckgo/app/browser/duckchat/RealDuckChatPreferencesStoreTest.kt
breakage-reporting/breakage-reporting-impl/src/main/java/com/duckduckgo/breakagereporting/impl/BreakageReportingMessageHandlerPlugin.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessaging.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessagingTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209228531591905/f
- Uses the C-S-S navigatorInterface + messageBridge to link directly from SERP into the dedicated AI Chat WebView.
- Tapping the "Ask AI Chat" button in SERP will auto-prompt the dedicated WebView with the pre-filled prompt (Also works for "DuckAssist").
- The functionality is disabled when aiChat is disabled in the config.
_Apply the patch linked in the task_
_Disable `aiChat` in the config linked in the task and load it up_

Add AI Chat SERP integration

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/PlayBillingManager.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt

Task/Issue URL: https://app.asana.com/0/1201807753394693/1209226459318682/f
Include `offerId` argument in subscriptions purchase method
_Pre steps_
_Privacy Pro Eligible US_
_Privacy Pro Eligible ROW (Optional)_

Add offerId to purchase method in SubscriptionsManager

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/updating/AutofillUpdatingExistingCredentialsDialogFragment.kt

Task/Issue URL: https://app.asana.com/0/1202926619870900/1208976665268815/f 
Logcat filter: `message~:"Determined that username" message~:"Storing username " message~:"partial form" message~:"Pixel sent:..*backf”`
**Saving 1st login (onboarding prompt)**
**Updating password (with backfilling)**
**Updating password (without backfilling)**

Modify autofill update credential pixel to include backfilled parameter

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/414730916066338/1209239612696930/f

Update content scope scripts to version 7.10.0

---

app/src/main/java/com/duckduckgo/app/browser/duckchat/DuckChatJSHelper.kt
app/src/test/java/com/duckduckgo/app/browser/duckchat/RealDuckChatJSHelperTest.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessaging.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessagingTest.kt

Task/Issue URL: https://app.asana.com/0/1205782359654716/1209252104628635/f
- Renamed getUserValues to getAIChatNativeHandoffData
- Added getAIChatNativeConfigValues
- - This method is the same as getAIChatNativeHandoffData but does not contain a payload.
_Apply the patch linked in the task_
_Standard flow_
_DuckAssist_
_Chat tab pill button_

Update methods for Duck.ai <> Native integration

---

app/src/main/res/layout/activity_show_on_app_launch_setting.xml

Task/Issue URL: https://app.asana.com/0/1202552961248957/1209246799465881/f 
Replaced hardcoded strings with string resources in the app launch settings screen for better localization support. Updated text references for "Last Opened Tab," "New Tab Page," and "Specific Page" options.
_String Resources Implementation_
|![Screenshot_20250127_160409](https://github.com/user-attachments/assets/39c0ed22-a23a-4fe4-b137-c88cf04f2cf1)|![Screenshot_20250127_161411](https://github.com/user-attachments/assets/40026550-b30a-46bd-9e9e-89b45362c4cc)|

Show on App Launch: Use string resources for settings 

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementRecyclerAdapter.kt
autofill/autofill-impl/src/main/res/values/autofill-impl-dimensions.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1209252957928805/f 
Updates the password management screen so that popup menus (triggered from a password’s overflow menu) take on the default size instead of specifying a custom width.

Remove custom logic for sizing autofill overflow menu popup

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209261327263714/f 
----- 

Update content scope scripts to version 7.12.0

---

app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1209267733740226/f
Added new method in `CtaViewModel` to check if all in-context dialogs have been shown

New areInContextDaxDialogsCompleted onboarding method

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/store/DefaultBrowserPromptsPrefsDataStoreImplTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperiment.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentImpl.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentVariants.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsFeatureToggles.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/di/DefaultBrowserPromptsDataStoreModule.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/diagrams/default_browser_prompts_experiment_class_diagram.puml
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/diagrams/default_browser_prompts_experiment_variant_2_flow_diagram.puml
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/store/DefaultBrowserPromptsDataStore.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/ui/DefaultBrowserBottomSheetDialog.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/main/res/drawable/ic_circle_7_accent_blue.xml
app/src/main/res/layout/view_new_omnibar.xml
app/src/main/res/layout/view_new_omnibar_bottom.xml
app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/test/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentImplTest.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1208671518894266/1208944504536347/f
Introduces variant 2 of the experiment that proposes new CTAs around setting DDG as a default browser. The PR also adds all of the experiment foundations and abstractions, so the remaining two variants will only be a small formality.
I'm going to follow up on pixels in a separate PR.
This PR relies on the new A/B/N framework for rollout, so to test you'll need a custom privacy config which includes the feature definition, for example:
```json
"features": {
"additionalPrompts": {
"rollout": {
"steps": [
{
"percent": 100
}
]
},
"settings": {
"activeDaysUntilStage1": 1,
"activeDaysUntilStage2": 3,
"activeDaysUntilStop": 5
}, …
```

Additional "default browser" prompts: variant 2

---

app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentVariants.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsFeatureToggles.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1208944504536348/f
Builds on top of https://github.com/duckduckgo/Android/pull/5476 and adds variant 1.
This PR relies on the new A/B/N framework for rollout, so to test you'll need a custom privacy config which includes the feature definition, for example:
```json
"features": {
"additionalPrompts": {
"rollout": {
"steps": [
{
"percent": 100
}
]
},
"settings": {
"activeDaysUntilStage1": 1,
"activeDaysUntilStage2": 3,
"activeDaysUntilStop": 5
},
"cohorts": [
{
"name": "control",
"weight": 0
},
{
"name": "variant_1",
"weight": 1
},
{
"name": "variant_2",
"weight": 0
}
]
}
},
}
```
or you can apply this JSON Blob:
```diff
diff --git …
```

Additional "default browser" prompts: variant 1

---

app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentVariants.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsFeatureToggles.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1208944504536349/f
Builds on top of https://github.com/duckduckgo/Android/pull/5476 and adds variant 3.
This PR relies on the new A/B/N framework for rollout, so to test you'll need a custom privacy config which includes the feature definition, for example:
```json
"features": {
"additionalPrompts": {
"rollout": {
"steps": [
{
"percent": 100
}
]
},
"settings": {
"activeDaysUntilStage1": 1,
"activeDaysUntilStage2": 3,
"activeDaysUntilStop": 5
},
"cohorts": [
{
"name": "control",
"weight": 0
},
{
"name": "variant_1",
"weight": 0
},
{
"name": "variant_2",
"weight": 0
},
{
"name": "variant_3",
"weight": 1
}
]
}
},
}
```
or you can apply this JSON Blob: …

Additional "default browser" prompts: variant 3

---

app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentVariants.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsFeatureToggles.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1209176678727048/f
Builds on top of https://github.com/duckduckgo/Android/pull/5476 and adds control.
This PR relies on the new A/B/N framework for rollout, so to test you'll need a custom privacy config which includes the feature definition, for example:
```json
"features": {
"additionalPrompts": {
"rollout": {
"steps": [
{
"percent": 100
}
]
},
"settings": {
"activeDaysUntilStage1": 1,
"activeDaysUntilStage2": 3,
"activeDaysUntilStop": 5
},
"cohorts": [
{
"name": "control",
"weight": 1
},
{
"name": "variant_1",
"weight": 0
},
{
"name": "variant_2",
"weight": 0
},
{
"name": "variant_3",
"weight": 0
}
]
}
},
}
```
or you can apply this JSON Blob: …

Additional "default browser" prompts: control

---

app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1206857429109107/f
try-catch the call to queryIntentActivities and return empty list instead

Try catch queryIntentActivities else return emptylist

---

app/src/test/java/com/duckduckgo/app/brokensite/api/BrokenSiteSubmitterTest.kt
app/src/test/java/com/duckduckgo/app/browser/refreshpixels/RefreshPixelSenderTest.kt
app/src/test/java/com/duckduckgo/app/trackerdetection/blocklist/BlockListPrivacyTogglePluginTest.kt
feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/MetricsPixelPlugin.kt
feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/RealFeatureTogglesCallback.kt
feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/metrics/RetentionMetricsAtbLifecyclePlugin.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/impl/MetricPixelInterceptorTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/impl/RealFeatureTogglesCallbackTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/impl/metrics/RetentionMetricsAtbLifecyclePluginTest.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1209213126411295/f 
This PR stores the full enrollment date for better comparison but still truncates it when sending pixels.

Store full enrollment date on a/b/n and truncate before sending pixels

---

feature-toggles/feature-toggles-internal/src/main/AndroidManifest.xml

Task/Issue URL: https://app.asana.com/0/608920331025315/1209308971637996 
In internal builds, we have Feature Flag Inventory available for toggling features flags from the UI inside our app.
It can only be launched from the settings UI:
- (exit whatever screen you might have been in)
- Overflow
- Settings
- Scroll
- Feature Flag Inventory
Objective
- Mark the activity as exported
- This would allow it to be launched directly. e.g., an alias from the command line. 
- As well as being easier to trigger as a developer, it would also have the advantage that you can quickly get to the screen without losing your current place in the app.
QA optional

Export Feature Flag Inventory so it can be accessed more quickly

---

app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt

Task/Issue URL: https://app.asana.com/0/1205008441501016/1209303563866691 
Do not wait for the full onboarding to be completed to be able to show the broken site prompt, just wait for all in-context dialogs to show
_Feature 1_

Show prompt if all in-context dialogs have been shown

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1201807753394693/1209307760721992
Remove highlight on fire button after Fire dialog is dismissed

Fire Button Highlight bug

---

.github/workflows/ads-end-to-end.yml
.github/workflows/custom-tabs-nightly.yml
.github/workflows/e2e-nightly-autofill.yml
.github/workflows/end-to-end-robintest.yml
.github/workflows/privacy-dashboard-end-to-end.yml
.github/workflows/release_tests.yml
.github/workflows/sync-critical-path.yml

Task/Issue URL: https://app.asana.com/0/608920331025315/1209118297419133/f 
Adds `timeout-minutes` to all the steps which are triggering a Maestro test run on Robin.
- we want timeouts to be treated as a failure, not for the CI to give up on a timeout and report as a success
- configuring the timeouts this way gives us genuine timeouts that will fail the build if the `timeout-minutes` value is exceeded for that step.
- QA optional
- From a [manual test](https://github.com/duckduckgo/Android/actions/runs/13008016261/job/36279174407),  i confirmed using this approach will successfully time out and fail the build if the Robin tests take too long to run 👇

Configure timeout-minutes for GH actions which run Maestro tests

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt

Task/Issue URL:https://app.asana.com/0/1205008441501016/1209289567264349 
Fix Globe icon not always shown on error pages
_Feature 1_

Fix Globe icon not always shown

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt
app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockerWebViewIntegration.kt

Task/Issue URL: https://app.asana.com/0/1205008441501016/1209289574297312 
Scope exemptions per tab, not per app
_Feature 1_

Scope exemptions to tab

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/WebViewRequestInterceptorTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClientTest.kt
app/src/androidTest/java/com/duckduckgo/app/fakes/FakeMaliciousSiteBlockerWebViewIntegration.kt
app/src/androidTest/java/com/duckduckgo/app/referencetests/DomainsReferenceTest.kt
app/src/androidTest/java/com/duckduckgo/app/referencetests/SurrogatesReferenceTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt
app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockedWarningLayout.kt
app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockerWebViewIntegration.kt
app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt
app/src/test/java/com/duckduckgo/app/browser/webview/RealMaliciousSiteBlockerWebViewIntegrationTest.kt
browser-api/src/main/java/com/duckduckgo/app/global/model/Site.kt
malicious-site-protection/malicious-site-protection-api/src/main/kotlin/com/duckduckgo/malicioussiteprotection/api/MaliciousSiteProtection.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/MaliciousSiteRepository.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/db/MaliciousSiteDao.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/network/MaliciousSiteService.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/domain/RealMaliciousSiteProtection.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/models/MaliciousSiteProtectionDataModels.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/RealMaliciousSiteRepositoryTest.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/db/MaliciousSiteDaoTest.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/domain/RealMaliciousSiteProtectionTest.kt

Task/Issue URL: https://app.asana.com/0/1205008441501016/1209270355529418/f
Add feed to isMalicious return type and update error page with feed info
_Feature 1_
_Feature 2_

Add feed to isMalicious return type and update error page with feed info

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209324863462807/f 
----- 

Update content scope scripts to version 7.16.0

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperiment.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentImpl.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentMetrics.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/ui/DefaultBrowserBottomSheetDialog.kt
app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/test/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentImplTest.kt

Task/Issue URL: https://app.asana.com/0/1201621853593513/1208697958169120/f
Marking as blocked until all pixels are confirmed with the DS team. This is generally ready for a first round of reviews but some additional changes may be still introduced because of that.
You can follow instructions from https://github.com/duckduckgo/Android/pull/5476 to go through the experiment.
Test for below pixels:
| Action  | Pixel |
| Enrolled | `experiment_enroll_defaultBrowserAdditionalPrompts202501_variant_2 with params: {enrollmentDate=2025-01-27}` |
| Reached Stage 1 | `experiment_metrics_defaultBrowserAdditionalPrompts202501_variant_2 with params: {metric=stageImpression, value=stage_1, enrollmentDate=2025-01-27, conversionWindowDays=1-X}` (`X` is 20, 40, 60) |
| Reached Stage 2 | …

Additional "default browser" prompts: metrics

---

app/src/main/res/layout-land/content_onboarding_welcome_page.xml
app/src/main/res/layout/content_onboarding_welcome_page.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1208088786036608
Fix Dax dialog being cut off on the bottom of the pre-onbaording screen in small devices

Fix Dax dialog scrolling for small devices

---

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillFeature.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStoreTest.kt

Task/Issue URL: https://app.asana.com/0/1203822806345703/1209273715877308/f 
- Right now, we will offer to autofill into a page which is considered an E-TLD+1 match
- But when it comes to offering to save a password, or update an existing one, we don’t consider E-TLD+1 which leads to more scenarios with duplicate passwords.
Detailed in [Test scenarios](https://app.asana.com/0/1209279526650235/1209279526650235/f)

Perform deeper domain comparison for saving/updating autofill passwords

---

app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
app/src/main/java/com/duckduckgo/app/launch/LaunchBridgeActivity.kt
app/src/main/java/com/duckduckgo/app/launch/LaunchViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/launch/LaunchViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1207908166761516/1209192748061745
Added a new pixel tracking event `m_splashscreen_shown` that fires when the app's splash screen is displayed. The pixel is configured to remove all parameters for privacy protection.
_Splash Screen Pixel Cold Start_
_Splash Screen Pixel Warm Start_
No UI changes were made in this PR.

SplashScreen Animation: Add pixel

---

app/src/main/java/com/duckduckgo/app/survey/rmf/DefaultSurveyParameters.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209346433224872
Update locale survey param format from `en-US` to `en-US`
> {
"id": "android_privacy_pro_exit_survey_1",
"content": {
"messageType": "big_single_action",
"titleText": "Tell Us Why You Left Privacy Pro",
"descriptionText": "By taking our brief survey, you'll help us improve Privacy Pro for all subscribers. ",
"placeholder": "PrivacyShield",
"primaryActionText": "Take Survey",
"primaryAction": {
"type": "survey",
"value": "https://selfserve.decipherinc.com/survey/selfserve/32ab/privacypro_exitsurvey?list=3",
"additionalParameters": {
"queryParams":"var;ddgv;man;mo;av;ppro_platform;ppro_billing;ppro_days_since_purchase;locale"
}
}
},
"matchingRules": []
},
- Replace endpoint for the JSONBlob one in …

Update survey param: locale

---

app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentImpl.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/di/DefaultBrowserPromptsExperimentModule.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/store/ExperimentAppUsageRepository.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/store/ExperimentAppUsageRepositoryImpl.kt
app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
app/src/test/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentImplTest.kt
app/src/test/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/store/ExperimentAppUsageRepositoryImplTest.kt
browser-api/src/main/java/com/duckduckgo/app/usage/app/AppDaysUsedRepository.kt
feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt

Task/Issue URL: https://app.asana.com/0/1208671518894266/1209329916239779
Adds `ExperimentAppUsageRepository` with an ability to store and query the "app days used" variable that is based on the ET timezone, instead of local timezone. This in turn is used in the default browser prompts experiment to ensure that the stages are triggered precisely at the same time as the A/B/N experiment shifts the app use day counter (used for validating conversion windows).
Apply this JSON Blob:
```diff
diff --git a/privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeatureName.kt b/privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeatureName.kt
index ca0870311..5a904f76b 100644
--- …
```

Additional "default browser" prompts: fixed an issue with active days conversion window

---

app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt

Fixes a missing DB migration from https://github.com/duckduckgo/Android/pull/5599

Add app.db migration to v57

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt
app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt

Task/Issue URL:  https://app.asana.com/0/1201870266890790/1209289574297311/f
Don't show preview of blocked page in tab switcher when malicious site warning has been triggered
_Block tab previews for warning page_

Eliminate preview for tabs showing malicious site warning

---

package-lock.json
package.json

Update content scope scripts to version 7.17.0

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209289574297311 
Also delete favicon when deleting tab preview
_Feature 1_

Delete favicon along with preview

---

common/common-ui/src/main/java/com/duckduckgo/common/ui/view/listitem/SettingsListItem.kt

Task/Issue URL: https://app.asana.com/0/1207908166761516/1209246799465871/f 
Added ripple effect to clickable settings list items and removed background from non-clickable items to improve visual feedback and user interaction consistency.
_Settings List Items_
**Before** 
https://github.com/user-attachments/assets/c13d1be6-dc71-4e08-bad8-8a08ac295d50
**After**
https://github.com/user-attachments/assets/e33059d7-9698-473b-8a76-c09ca29c7c6c

Update Settings: Remove ripple for disabled ppro items

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL:  https://app.asana.com/0/0/1209359933476105/f
We should be firing all pixel params in lowercase, so need to convert the malicious feed category param before sending.
_Feature 1_

Send pixel category param as lowercase

---

app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
app/src/main/java/com/duckduckgo/app/launch/LaunchBridgeActivity.kt
app/src/main/java/com/duckduckgo/app/launch/LaunchViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/launch/LaunchViewModelTest.kt
common/common-ui/src/main/res/drawable-night/splash_screen_wink.xml
common/common-ui/src/main/res/drawable/splash_screen_wink.xml
common/common-ui/src/main/res/values-v32/design-system-theming.xml
common/common-ui/src/main/res/values/design-system-theming.xml

Task/Issue URL: https://app.asana.com/0/1207908166761516/1209192748061740/f
Adds a new wink animation to the splashscreen for devices on sdk 32+😉 
On devices <32 we show the existing static logo splashscreen.
_Splashscreen on SDK 32+_
_Splashscreen on SDK < 31_
**Light**
https://github.com/user-attachments/assets/1bd02a3a-0c9b-4bba-814f-fab2a4af9f5d
**Dark**
https://github.com/user-attachments/assets/fdb63c14-7f84-44a1-92e0-3f2a8a0539e9
---
- https://app.asana.com/0/0/1209331097372337

SplashScreen Animation: Add wink animation

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209368325379704
- `aichat_open` is currently measuring total opens, it should only measure menu clicks.
_Overflow menu_
_Tabswitcher_

Update AI chat open pixel

---

subscriptions/subscriptions-impl/src/main/res/values-bg/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-cs/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-da/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-de/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-el/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-es/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-et/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-fi/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-fr/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-hr/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-hu/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-it/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-lt/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-lv/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-nb/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-nl/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-pl/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-pt/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-ro/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-ru/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-sk/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-sl/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-sv/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-tr/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values/strings-subscriptions.xml

Task/Issue URL: https://app.asana.com/0/1205648422731273/1209235571983213
Apple ID is now called Apple Account. This PR updates string resources to reflect that change.
QA-optional

Change Apple ID to Apple Account

---

.maestro/autofill/backfillingUsername/multi_step_registration_username_backfilled_password_manually_entered.yaml
.maestro/autofill/backfillingUsername/password_reset_flow_for_existing_credential_manual_password.yaml
node_modules/@duckduckgo/autofill/dist/autofill-debug.js
node_modules/@duckduckgo/autofill/dist/autofill.js
node_modules/@duckduckgo/autofill/dist/shared-credentials.json
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/1209376474235068/1209376474235068
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.2.1
Updates Autofill to version [16.2.1](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.2.1).
* Update password-related json files (2025-01-31) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/750
* [Logging] Add debug logs for recategorization by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/753
* [Formatters] re-add partial save logic behind a feature toggle by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/757
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/16.2.0...16.2.1
This release has been tested during autofill …

Update autofill to 16.2.1

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/viewstate/CtaViewState.kt

Task/Issue URL: https://app.asana.com/0/0/1209363619593651/f 
* Do not auto-focus omnibar on error page
* Do not show trackers blocked animation on error page
* Update URL on omnibar even if site was prevented from loading
* Do not show search icon on error page
_Feature 1_
_Feature 2_
_Feature 3_

Do not autofocus omnibar on error page

---

app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentImpl.kt
app/src/test/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentImplTest.kt

Task/Issue URL: https://app.asana.com/0/1208671518894266/1209349005070380
Checks whether there are valid evaluators for a cohort, or clean ups side effects if not. This helps with a situation when the experiment is disabled remotely and there's no current active cohort.
1. Open the app and go through onboarding. DDG **should not** be set as your default browser.
2. Load this config https://www.jsonblob.com/api/1337370852936835072 which contains the experiment enabled for variant 3.
3. Change the device's date to next day, a CTA dialog will show and a menu item will be added.
4. Load this config https://www.jsonblob.com/api/1337385724919603200 which has the experiment disabled.
5. The menu item should be gone.
Example video:
[Screen_recording_20250207_124710.webm](https://github.com/user-at …

Additional "default browser" prompts: fixed an issue with disabling the experiment remotely

---

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerService.kt
network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/WireguardHandshakeMonitor.kt
network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/NetPInternalSettingsActivity.kt
network-protection/network-protection-internal/src/main/res/layout/activity_netp_internal_settings.xml
network-protection/network-protection-internal/src/main/res/values/donottranslate.xml

Task/Issue URL: https://app.asana.com/0/1198194956794324/1209378254127336
Make sure the `WgVpnControllerService` service marked as `UnprotectedVpnControllerService` makes calls outside the VPN tunnel.
This seems to fix rekey
_Test_

Make sure UnprotectedVpnControllerService requests go outside the VPN tunnel

---

app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsActivity.kt
app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
app/src/main/res/layout/activity_general_settings.xml
app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/0/1209386990832086/f 
Check enableMaliciousSiteProtection flag to set settings visibility
_Feature 1_
_Feature 2_

Check enableMaliciousSiteProtection flag to set settigns visibility

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/viewstate/OmnibarViewState.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209104073191021
This PR fixes the backwards typing bug (typing from right-to-left) by replacing the `shouldMoveCaretToStart` ViewState parameter with a command, so that it's executed only once when the omnibar loses focus. 
I've also removed `shouldMoveCaretToEnd` because it was not used (enabled) anywhere in the code. 
_The fix_
_Long URL shown from the start_

Fix for the backwards typing bug

---

.maestro/app_tp/app_tp_onboarding.yaml

Remove assertion for App Tracking Protection subtitle text which is no longer displayed in settings
Task/Issue URL: https://app.asana.com/0/488551667048375/1209394870150674
The settings menu item for App Tracking Protection no longer displays the subtitle "Block app trackers on your device", so the corresponding assertion check has been removed from the test.
Run `maestro test .maestro/app_tp/app_tp_onboarding.yaml` locally
N/A

Remove App Tracking subtitle assertion from Maestro test

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209394211370089/f 
----- 

Update content scope scripts to version 7.18.0

---

app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt
malicious-site-protection/malicious-site-protection-api/src/main/kotlin/com/duckduckgo/malicioussiteprotection/api/MaliciousSiteProtection.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/domain/RealMaliciousSiteProtection.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1209390510093034 
Check maliciousSiteProtection flag to set settings visibility
_Feature 1_
_Feature 2_ 
_Feature 3_ 

Check maliciousSiteProtection flag to set settigns visibility

---

app/src/main/java/com/duckduckgo/app/browser/BrowserStateModifier.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/WebNavigationState.kt
app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
app/src/main/java/com/duckduckgo/app/browser/viewstate/BrowserViewState.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1209377556005337 
Fix back navigation when site blocked before added to webview history, which was causing omnibar URL and privacy shield icon not to update correctly
_Feature 1_

Fix back navigation when site blocked before added to webview history

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillServiceFeature.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/RealAutofillService.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209399460038441 
show suggestions inside DDG app
Put it behind a FF in case we uncover unexpected behaviors
_Feature 1_

enable showing suggestions inside DDG (behind FF)

---

app/src/main/java/com/duckduckgo/app/notification/NotificationFactory.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209283169834729
- `context.getColorFromAttr` already returns a `ColorInt`, so `setColor(ContextCompat.getColor(…` causes: https://github.com/duckduckgo/Android/issues/5563

Fix notification set color

---

app/src/internal/AndroidManifest.xml
app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsActivity.kt
app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsViewModel.kt
app/src/internal/java/com/duckduckgo/app/dev/settings/tabs/DevTabsActivity.kt
app/src/internal/java/com/duckduckgo/app/dev/settings/tabs/DevTabsViewModel.kt
app/src/internal/res/layout/activity_dev_settings.xml
app/src/internal/res/layout/activity_dev_tabs.xml
app/src/internal/res/values/donottranslate.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1209407906356235
Added a new developer settings screen for managing tabs, allowing developers to quickly create or clear multiple tabs for testing purposes. The screen includes functionality to specify the number of tabs to create and automatically generates tabs with random privacy-focused URLs.
_Tab Management_
https://github.com/user-attachments/assets/187de4a3-433d-497f-8782-f591a41ff59e

Add ability to generate Tabs from Developer Settings

---

.github/workflows/ci.yml
scripts/check_elf_alignment.sh

Task/Issue URL: https://app.asana.com/0/488551667048375/1209378846484863
Added ELF alignment verification to the CI pipeline to ensure native libraries are properly aligned at 16KB or 64KB boundaries. This includes a new shell script that checks alignment in APK files and reports any misaligned libraries.
A passing build using playDebug: https://github.com/duckduckgo/Android/actions/runs/13291887849/job/37114510525?pr=5634
A failing build using internalDebug (because of Flipper which we know about)
https://github.com/duckduckgo/Android/actions/runs/13292470506/job/37116369658?pr=5634
_ELF Alignment Verification_
No UI changes in this PR

Target Android 15: Add ELF alignment verification CI check

---

saved-sites/saved-sites-impl/src/main/res/values-bg/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-cs/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-da/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-de/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-el/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-es/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-et/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-fi/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-fr/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-hr/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-hu/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-it/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-lt/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-lv/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-nb/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-nl/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-pl/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-pt/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-ro/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-ru/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-sk/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-sl/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-sv/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values-tr/strings-saved-sites.xml
saved-sites/saved-sites-impl/src/main/res/values/strings-saved-sites.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1209407999578316
"Location", "Choose location" in the Edit bookmark dialog is wrongly translated to Russian as "Геопозиция", "Выберите геопозицию" ("Geolocation", "Choose geolocation").
QA-optional

Fix translation in Russian

---

app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModel.kt
app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/model/ShowOnAppLaunchOption.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1207908166761516/1208302992661645 
Removes pixel tracking for app launch settings options. This includes removing the pixel firing logic from the ShowOnAppLaunchViewModel and deleting the associated pixel names from AppPixelName.
_App Launch Settings_
No UI changes

Show on App Launch: Remove temporary pixels

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/1201870266890790/1209422420805301
We should check for duckplayer url when setting canReportSite
_Feature 1_

Disable broken site reporting & privacy protections toggle when viewing through Duck Player

---

node_modules/@duckduckgo/autofill/README.md
node_modules/@duckduckgo/autofill/dist/autofill-debug.js
node_modules/@duckduckgo/autofill/dist/autofill.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/1209465117664023/1209465117664023
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.2.2
Updates Autofill to version [16.2.2](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.2.2).
* chore: update actions cache to v3 by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/759
* Update Apple project file references in the release workflow by @samsymons in https://github.com/duckduckgo/duckduckgo-autofill/pull/758
* Update release workflow to support Apple monorepo by @samsymons in https://github.com/duckduckgo/duckduckgo-autofill/pull/756
* [Formatters] Make fixes for credentials less restrictive by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/763
* @samsymons …

Update autofill to 16.2.2

---

site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SystemPermissionsHelper.kt

Task/Issue URL: https://app.asana.com/0/1205648422731273/1209434223230239
_Grant approximate location permission_
_Verify SERP can access approximate location_
- You might want to use VPN to be able to easily tell the difference between IP geolocation and real approximate location
_Precise location permission granted_
_Location permission not granted_
_Location permission granted (not system granted)_

Use approximate location permission

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillServiceViewProvider.kt

Task/Issue URL: https://app.asana.com/0/1149059203486286/1209453476472064
Hide subtitle when string is empty, making suggestion a single line.
_Feature 1_

Autofill suggestion: hide second line if subtitle empty

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209492594044014/f 
----- 

Update content scope scripts to version 7.22.0

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1209512583266733
Fixes a bug when tapping on a link that opens a new tab is broken.

Fix: Navigation of a link that opens a new tab is broken

---

.github/workflows/build-ad-hoc.yml

Task/Issue URL: https://app.asana.com/0/1202552961248957/1209524992278444
build-ad-hoc.yml has a ref input parameter to specify a branch, tag or commit, which is never used. When checking out the repo, a non-existing variable is read instead, defaulting to develop. Therefore, it's not possible to produce ad-hoc apks for branches other than develop
**Before**
Setting `feature/cris/malicious-site-protection/fix-back-nav-from-error-page` as ref, produces the following output:
```
usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +2b158df88972514f2bac3bc68b9acb82361b64cb:refs/remotes/origin/develop
From [https://github.com/duckduckgo/Android](https://github.com/duckduckgo/Android)
\* \[new ref\] 2b158df88972514f2bac3bc68b9acb82361b64cb -> …
```

Fix build-ad-hoc ref input

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.css
node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209531901562272/f 
----- 

Update content scope scripts to version 7.23.0

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/engagement/store/AutofillEngagementRepository.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillProviderChooseActivity.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillProviderChooseViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillProviderCredentialsListViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillServiceStatusLifecycleObserver.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillSimpleCredentialsListFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/RealAutofillService.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/store/AutofillServiceModule.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/store/AutofillServiceStore.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/FakeAutofillServiceStore.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/engagement/store/DefaultAutofillEngagementRepositoryTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/service/AutofillProviderChooseViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1200156640058969/1209303556783952
Adds metrics around the autofill service
Notice: specs are present in https://app.asana.com/0/1200156640058969/1209115687167237
Use `message~:"Pixel sent: autofill_"` as filter
Test cases in https://app.asana.com/0/488551667048375/1209504798589773

Add Autofill service metrics

---

malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionFeature.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/db/MaliciousSiteDao.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/db/MaliciousSitesDataEntities.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/db/MaliciousSitesDatabase.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/domain/RealMaliciousSiteProtection.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/remoteconfig/MaliciousSiteProtectionExceptionsStore.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/remoteconfig/MaliciousSiteProtectionRCRepository.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/domain/RealMaliciousSiteProtectionTest.kt

Task/Issue URL: https://app.asana.com/0/1205008441501016/1209426268774143 
Process exceptions from RC and don't flag a site as malicious if domain matches an exception
_Feature 1_
* Note: if this doesn't work, check the following:
* Reinstall the app. Since exceptions were already present in the JSON but not parsed, there's a chance RC update logic hasn't triggered 
* Check https://staticcdn.duckduckgo.com/trackerblocking/config/v4/android-config.json and see if broken.third-party.site is still added as an exception to maliciousSiteProtection

Add support for Malicious Site Protection RC exceptions

---

malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionFeature.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionFiltersUpdateWorker.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionHashPrefixesUpdateWorker.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionRCFeature.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionFiltersUpdateWorkerTest.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionHashPrefixesUpdateWorkerTest.kt

Task/Issue URL: https://app.asana.com/0/1205008441501016/1209119876664187 
* Add visibleAndOnByDefault subfeature, so we can perform an incremental rollout
* Add canUpdateDatasets subfeature, so we can turn off dataset downloads if needed
* Force update datasets when RC flag is turned on

Add killswitch, support incremental rollouts, and force update when downloading privacy config

---

saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarkScreenViewHolders.kt
saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksAdapter.kt
saved-sites/saved-sites-impl/src/main/res/layout/activity_bookmarks.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1209489657638562
This PR fixes 2 bookmarks screen UI issues:
- display of long bookmark folder titles in the toolbar
- incorrect more menu button alignment for folders in the bookmark list
_Title_
_List_
_Title_
_List_

Fix: Bookmarks screen UI issues

---

app/src/androidTest/java/com/duckduckgo/app/fakes/FakeMaliciousSiteBlockerWebViewIntegration.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt
app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockerWebViewIntegration.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/browser/webview/RealMaliciousSiteBlockerWebViewIntegrationTest.kt
malicious-site-protection/malicious-site-protection-impl/build.gradle
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSitePixelName.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/MaliciousSiteRepository.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/RealMaliciousSiteRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209304069660515
*  Add Malicious Site Protection algorithm pixels
_Feature 1_
_Feature 2_
_Feature 3_

Add Malicious Site Protection algorithm pixels

---

app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
app/src/main/java/com/duckduckgo/app/launch/LaunchBridgeActivity.kt
app/src/main/java/com/duckduckgo/app/launch/LaunchViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/launch/LaunchViewModelTest.kt
common/common-ui/src/main/res/values-v33/design-system-theming.xml

Task/Issue URL: https://app.asana.com/0/1207908166761516/1209495201524764 
Added a fallback mechanism to handle cases where the splash screen exit animation fails to trigger. The fallback automatically proceeds to the next screen after a 1.5-second delay if the normal exit animation doesn't occur.
We now also only target Android 13 and above with the Splashscreen animation after seeing mention of issues on Android 12L.
_Android 12L testing fallback_
_Android 12L testing normal launch_
_Test other OS versions_
Test that the splashscreen still works on other Android OS versions. A suggested range could be 26, 30, 33, 35
On 33+
On <= 32
No visual changes to the splash screen appearance or animation.
**Emulator Android 12L Simulating fallback** …

SplashScreen Animation: Add fail to launch mitigation

---

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillCredentialDialogs.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillFeature.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/AutofillDeduplicationBestMatchFinder.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/AutofillDeduplicationUsernameAndPasswordMatcher.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deduper/AutofillLoginDeduplicator.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/username/AutofillUsernameComparer.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/AutofillStoreFixtures.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/FakeSecureStorage.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStoreTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealAutofillLoginDeduplicatorTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealLoginDeduplicatorBestMatchFinderTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deduper/RealLoginDeduplicatorUsernameAndPasswordMatcherTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/service/AutofillServiceSuggestionsTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/username/RealAutofillUsernameComparerTest.kt
autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
autofill/autofill-internal/src/main/res/values/donottranslate.xml

Task/Issue URL: https://app.asana.com/0/608920331025315/1209488709393051 
Changes how we compare usernames to make them case-insensitive. 
Autofill subfeature `ignoreCaseOnUsernameComparisons` guards the new behaviour.
- new behaviour is enabled by default 
- disable the flag to revert to old behaviour
- If multiple credentials saved which are identical apart from casing on username, these will be considered duplicates from the credential picker view (meaning they’ll be de-duped)
- If you already have a credential saved and are trying to save a new one with same username, the comparison between usernames will be case insensitive. So if `user` is saved and `USER` comes from the JS, these will be treated as equivalent
- The password management view will always show all saved credentials (no …

Make autofill username comparison case insensitive

---

app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentImpl.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsFeatureToggles.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/diagrams/default_browser_prompts_experiment_class_diagram.puml
app/src/test/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/DefaultBrowserPromptsExperimentImplTest.kt

Task/Issue URL: https://app.asana.com/0/1208671518894266/1209523191422601
Adjust the implementation to be able to use config entry that matches the schema.
Test config:
```json
"features": {
"defaultBrowserAdditionalPrompts202501": {
"settings": {
"activeDaysUntilStage1": "1",
"activeDaysUntilStage2": "3",
"activeDaysUntilStop": "5"
},
"cohorts": [
{
"name": "control",
"weight": 0
},
{
"name": "variant1",
"weight": 0
},
{
"name": "variant2",
"weight": 1
},
{
"name": "variant3",
"weight": 0
}
]
}
}
}
```
1. Load this config: https://www.jsonblob.com/api/1344630015471575040
2. Move the device's calendar date by one day.
3. Restart/resume the app - a CTA should be shown.
4. Move the device's calendar date by …

Additional "default browser" prompts: refactored remote config parsing code to match expected schema

---

app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/global/MultiProcessApplication.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209504297651004 
- Added dependency tree creation for pir process
- Made getCache and getDir run on any secondary process
Make sure on a fresh install VPN doesn’t crash.

Add support for pir in DuckDuckGoApplication

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt

Task/Issue URL: https://app.asana.com/0/1142021229838617/1209560036159812 
Fix privacy shield flickering by not updating the animation if unchanged
_Feature 1_
- Smoke test privacy shield in both MSP and regular sites. The icon shouldn't flicker with the same status
---
- https://app.asana.com/0/0/1209567544947320

Don't update privacy shield animation if unchanged

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209571266884765
Don't call renderPrivacyIcon if another leadingIcon is being shown. Otherwise, lastSeenPrivacyShield might contain inaccurate data of a state that was never displayed, leading to inconsistent UI
_Feature 1_

Do not render privacy shield if not shown

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209564665484120/f 
----- 

Update content scope scripts to version 7.24.0

---

app/src/main/java/com/duckduckgo/app/launch/LaunchBridgeActivity.kt
app/src/main/java/com/duckduckgo/app/launch/LaunchViewModel.kt
app/src/test/java/com/duckduckgo/app/launch/LaunchViewModelTest.kt
app/src/test/java/com/duckduckgo/fakes/FakePixel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209572281087336
Added temporary pixel parameters to the splash screen failed to launch pixel to help diagnose splash screen issues.
_Splash Screen Pixel Params_
No UI changes

Splashscreen Animation: Add error pixel params

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209576197948280/f 
----- 

Update content scope scripts to version 7.25.0

---

subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1209584430633449 
Added `offerId` parameter with null default value to the `purchase` method call in `RealSubscriptionsManagerTest`.
The PR where the test was added: [`d5315e0` (#5608)](https://github.com/duckduckgo/Android/pull/5608/commits/d5315e07a1862157885ca0042a2f8f3d1cd9a252#r1983806357)
_Purchase Method Testing_
No UI changes in this PR

Fix purchase method call in RealSubscriptionsManagerTest

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209603311550623/f 
----- 

Update content scope scripts to version 7.27.0

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt

Task/Issue URL: https://app.asana.com/0/1205617573940217/1209600288549962/f
QA-optional

Don't force auth v2 on internal builds

---

package-lock.json
package.json

Update reference tests to version 1741215780

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209620190947490/f 
----- 

Update content scope scripts to version 7.28.0

---

app-tracking-protection/vpn-api/build.gradle
app-tracking-protection/vpn-api/src/main/AndroidManifest.xml
app-tracking-protection/vpn-impl/build.gradle
app-tracking-protection/vpn-impl/src/main/AndroidManifest.xml
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPCPUMonitor.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/CPUMonitorWorker.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/worker/VpnRemoteWorkerService.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/worker/WorkerExtensions.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1209631586705997
Create the specialized VpnRemoteWorkerService to create workers in the VPN process
_Test_

Use specialized VpnRemoteWorkerService

---

app/src/main/res/layout/content_settings_main_settings.xml

Task/Issue URL: https://app.asana.com/0/1202552961248957/1209646376530330
Moved the DuckChat setting to the bottom of the settings menu, placing it after the DuckPlayer section.
_Settings Menu Order_
[See iOS Designs
](https://www.figma.com/design/CjH849hL53lhsPlf6Ufeo4/%E2%9A%99%EF%B8%8F-Browser-Settings-Documentation-(All-Platforms)?node-id=7605-431388&t=M5NCXq9ECQAtY1ek-0)
|![Screenshot_20250312_090329](https://github.com/user-attachments/assets/540eab67-4ea8-4614-aea5-0554f8457462)|![Screenshot_20250312_090117](https://github.com/user-attachments/assets/f11af23e-2053-4339-8dff-12ac0cf6ddc4)|

Move Duck.AI Settings Item below DuckPlayer

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt

Task/Issue URL: https://app.asana.com/0/1205648422731273/1209601572682035/f
This PR addresses an edge case where the device could migrate to auth v2 after the server has already removed the account.
See task.

Handle invalid_token error during migration to auth v2

---

app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
autofill/autofill-impl/src/main/AndroidManifest.xml
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/RealAutofillService.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/store/AutofillFeatureRepository.kt
autofill/autofill-impl/src/main/res/values/donottranslate.xml
autofill/autofill-internal/src/main/AndroidManifest.xml

Task/Issue URL: https://app.asana.com/0/1200156640058969/1209537052601451 
Moves Autofill Service (and activities) to its own process
_Feature 1_
then smoke test the service

moves autofill service (and activities) to its own process

---

app/src/main/java/com/duckduckgo/app/browser/weblocalstorage/WebLocalStorageManager.kt
app/src/test/java/com/duckduckgo/app/browser/DuckDuckGoWebLocalStorageManagerTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1209656726579252
- Use `fireproofWebsitesSync` instead of `fireproofWebsites` when preserving local storage.

Use fireproofWebsitesSync when preserving local storage

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/WebNavigationState.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt
app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockerWebViewIntegration.kt
app/src/test/java/com/duckduckgo/app/browser/ErrorNavigationStateTest.kt
app/src/test/java/com/duckduckgo/app/browser/TestBackForwardList.kt
app/src/test/java/com/duckduckgo/app/browser/TestHistoryItem.kt
app/src/test/java/com/duckduckgo/app/browser/WebViewNavigationStateTest.kt
app/src/test/java/com/duckduckgo/app/browser/webview/RealMaliciousSiteBlockerWebViewIntegrationTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1142021229838617/task/1209533874972459
Includes: 
* [Better handling of back navigation](https://app.asana.com/0/0/1209599023979002/f)
* [Fix shield icon shown on race condition after starting trackers animation](https://app.asana.com/0/0/1209599023979004/f)
* [Fix shield icon sometimes being shown after closing and reopening the app](https://app.asana.com/0/0/1209599023979006/f)
* Fix back navigation issues: Allow back navigation if iframe blocked, or mainframe blocked from client
* Fix wrong omnibar icon shown when closing and reopening the app with error tab inactive
* Fix error page not shown for popup with blank target
_Test 1_
- Open https://privacy-test-pages.site/security/badware/phishing-popups.html
- Tap on Open …

Fix ship review issues

---

app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/TabSwitcherItemDiffCallback.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabItemDecorator.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherAdapter.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherDynamicMenu.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherItem.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
app/src/main/res/layout/item_tab_grid.xml
app/src/main/res/layout/item_tab_list.xml
app/src/main/res/layout/popup_tabs_menu.xml
app/src/main/res/values/donottranslate.xml
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
common/common-ui/src/main/res/drawable/ic_check_blue_round_24.xml
common/common-ui/src/main/res/drawable/shape_grey_circle_24.xml

Task/Issue URL: https://app.asana.com/0/72649045549333/1207969573539955
This PR adds the tab selection UI and allows the tabs to be selected after triggering the selection mode. The selection mode can be cancelled by tapping anywhere outside a tab.
Some menu items and buttons are already functional, namely:
- New Tab
- FAB New Tab
- Select Tabs (triggers the selection mode)
- Select All (in selection mode)
- Close All Tabs (in selection mode)
Non-functional items:
- All sharing menu items and toolbar buttons
- All bookmarking menu items and toolbar buttons
- All selection-related tab closing (including the FAB)
_Entering and leaving the selection mode_
_Selecting all tabs_
_Closing all tabs_
_Adding a new tab_
_List layout selection_ …

Multi-selection: Selection mode

---

node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
package-lock.json
package.json

Update content scope scripts to version 7.29.0

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt

Task/Issue URL: https://app.asana.com/0/1176956903599313/1209163229346625
Show context onboarding Dax dialogs when they are shown
_Opening a New Tab_
_Visit a site dialog not appearing twice_
_Close and open the app again_

Onboarding: Dismiss contextual onboarding dialogs after 1 view

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206716555947156/task/1209669823663214
Update onboarding Privacy Pro subscription origin

Onboarding: Change origin for privacy pro subscriptions

---

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncFeature.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncFeatureToggle.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModel.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncDisabledViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/608920331025315/task/1209669301264637 
Allows the sync settings screen to automatically refresh while it is being viewed. This is in part to provide a better UX to https://github.com/duckduckgo/Android/pull/5762.

Refresh sync settings screen automatically

---

app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherSnackbar.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
app/src/main/res/values/donottranslate.xml
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1209118961868653
This PR adds the bookmarking functionality to the tab switcher.
_Bookmarking selected tabs_
_Undo bookmark action_
_Bookmarking unique and non-NTP tabs_

Multi-selection: Bookmarking

---

app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209726056913497/f
This PR improves the tab switcher scrolling behaviour by:
1. Moving the `scrollToActiveTab()` call to happen after tabs are loaded, ensuring it only runs once the tab list is populated
2. Renaming `scrollToShowCurrentTab()` to `scrollToActiveTab()` for clarity
3. Implementing debounce and conflate on tab repository flow to prevent rapid UI updates
_Tab Switcher Scrolling_
N/A
https://github.com/user-attachments/assets/f45495e3-fc05-413a-b80b-bd2ddcd61eae

Fix not scrolling to active tab in TabSwitcher

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/onboarding/store/OnboardingStore.kt
app/src/main/java/com/duckduckgo/app/onboarding/store/OnboardingStoreImpl.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt

Task/Issue URL: https://app.asana.com/0/1204912272578138/1209163229346626/f
Add temporary pixel for counting display of visit site suggestions dialog
_Feature 1_

Onboarding: Add pixel count for 'visit site' CTA

---

duckchat/duckchat-impl/src/main/AndroidManifest.xml
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/DuckChatWebViewActivity.kt

Task/Issue URL: https://app.asana.com/0/1200204095367872/1209507829379943/f
- Fixes a bug where chat history was lost when rotating the device.

Duck.ai rotation fix

---

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncFeature.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncService.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncServiceRemote.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModel.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncConnectViewModel.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncLoginViewModel.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherActivityViewModel.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncAccountRepositoryTest.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncWithAnotherDeviceViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1209272522976873/1209569901379925 
Aligns recovery code flow with connect code flow. 
- The feature is **disabled** by default. It will be enabled for all later via a FF update.
- You’ll need 2 or more devices to complete the tests.
- Suggested logcat filter: `package:mine & (message~:"Sync-exchange|InvitationFlow”)`
There is a matrix of test cases detailed here: [test scenarios](https://app.asana.com/0/1209272522976873/1209569901379925/f)
In these tests, we want to ensure existing behaviour happens and there’s no regressions introduced even when the FF is disabled. 
- [iOS](https://app.asana.com/0/0/1209666996614195/f)
- [macOS](https://app.asana.com/0/1209272522976873/1209666996614200/f)
- …

Aligning recovery code with connect flow

---

app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1207908166761516/1209726015931612/f
Added tracking for the tab manager info panel with three new pixels:
- `m_tab_manager_info_panel_impressions` - Fired when the panel becomes visible
- `m_tab_manager_info_panel_dismissed` - Fired when the panel is dismissed, includes tracker count
- `m_tab_manager_info_panel_tapped` - Fired when the panel is tapped
Implemented visibility detection for the tracker animation info panel in the tab switcher to accurately track impressions.
Pre-requisite: Enable `tabSwitcherAnimation` feature flag
_m_tab_manager_info_panel_impressions_
_m_tab_manager_info_panel_tapped_
_m_tab_manager_info_panel_dismissed_
N/A

Tab Switcher Animation: Add pixels

---

app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
app/src/main/res/values-bg/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-da/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-el/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-et/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-hr/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-lv/strings.xml
app/src/main/res/values-nb/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-ro/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sk/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209710789450014/f 
Moved TabSwitcher Animation Tile Dialog string resources from `donottranslate.xml` to `strings.xml` to enable translation of these user-facing messages.
_TabSwitcher Animation Tile Dialog_
N/A

Tab Switcher Animation: Ship Review Change Translations

---

.github/workflows/ads-end-to-end.yml
.github/workflows/custom-tabs-nightly.yml
.github/workflows/sync-critical-path.yml
app-build-config/app-build-config-api/src/main/java/com/duckduckgo/appbuildconfig/api/AppBuildConfig.kt
app/build.gradle
app/src/main/java/com/duckduckgo/app/buildconfig/RealAppBuildConfig.kt
common/common-ui-internal/src/main/java/com/duckduckgo/common/ui/internal/experiments/visual/VisualDesignExperimentViewModel.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/experiments/visual/store/VisualDesignExperimentDataStore.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/experiments/visual/store/VisualDesignExperimentDataStoreImpl.kt

Task/Issue URL: https://app.asana.com/0/1208671518894266/1209736451015483/f
Disables experimental UI changes by default.
Note, the experimental UI will stay enabled if you've previously manually interacted with the settings toggle. It will only automatically switch off if you relied on the default behavior.

disable design experiment by default

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Update content scope scripts to version 8.5.0

---

malicious-site-protection/malicious-site-protection-impl/src/test/resources/reference_tests/canonicalization/canonicalization_tests.json
package-lock.json
package.json

Update reference tests to version 1743047884

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209740252113712/f
This PR fixes unnecessary pixel reporting and redundant store login attempts when a token refresh fails due to an account being deleted (indicated by the unknown_account error).
QA-optional

Improve handling of the unknown_account error during token refresh

---

app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerPixelParamRemovalPlugin.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209569372746396/f
Removed ATB from:
- `m_autofill_management_opened` (passwords settings opened)
- `ms_sync_pressed` (sync settings opened)
- `duckplayer_setting_pressed` (duck player settings opened)
- `ms_email_protection_setting_pressed` (email protection settings opened)
Verify that none of the above pixels send ATB.

remove ATB from some pixels

---

node_modules/@duckduckgo/autofill/dist/autofill-debug.js
node_modules/@duckduckgo/autofill/dist/autofill.js
node_modules/@duckduckgo/autofill/dist/shared-credentials.json
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/1209843505405123/1209843505405123
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/17.0.1
Updates Autofill to version [17.0.1](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/17.0.1).
* Update password-related json files (2025-03-17) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/779
* display all Autofill UI elements in 1 HTML page by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/781
* [Scanner] add form only when it's not available by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/782
* Update Apple BSK path by @samsymons in https://github.com/duckduckgo/duckduckgo-autofill/pull/784
* Update password-related json files (2025-03-28) …

Update autofill to 17.0.1

---

.maestro/custom_tabs/custom_tabs_navigation.yaml
app/src/main/java/com/duckduckgo/app/browser/menu/BrowserPopupMenu.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/1157893581871903/1209822654738726/f
The custom tab mode wasn’t rendering properly. This PR fixes it
_Custom Tab_
_Malicious site protection_

Fix custom tab mode:

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/SwipingTabsFeature.kt
app/src/main/java/com/duckduckgo/app/browser/SwipingTabsFeatureProvider.kt
app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1209846575622295/f
This PR adds a subfeature flag `onForInternalUsers` and `onForExternalUsers` (the feature flag for prod users to enable staged rollout).
The flag is used inside a `SwipingTabsFeatureProvider` wrapper so nothing else should be affected. The original flag feature flag will be used to keep the feature enabled for all internal users.
After this, the updated privacy config will look like this:
```
"swipingTabs": {
"minSupportedVersion": 52271000,
"features": {
"onForInternalUsers": {
"state": "internal"
},
"onForExternalUsers": {
"rollout": {
"steps": [
{
"percent": 20
}
]
}
}
}
}
```
_Internal test_

Tab swiping: Add a subfeature flag

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/httperrors/HttpErrorDailyReportingWorker.kt
app/src/main/java/com/duckduckgo/app/browser/httperrors/HttpErrorPixels.kt
app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
app/src/test/java/com/duckduckgo/app/browser/httperrors/HttpErrorDailyReportingWorkerTest.kt
app/src/test/java/com/duckduckgo/app/browser/httperrors/RealHttpErrorPixelsTest.kt

Task/Issue URL: https://app.asana.com/0/1200581511062568/1209741376363526/f
Added more params to the m_webview_received_http_error_5xx_daily pixel.
_HTTP Error Tracking_
NO UI changes.

[Android] Increase in 5xx errors

---

app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt

Task/Issue URL: https://app.asana.com/0/1201807753394693/1209870056514404/f
Added a check for onboarding active in order to show the new tab page
_Existing user_
_New user_

Onboarding: Added onboarding active check to New Tab Page

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt

Task/Issue URL: https://app.asana.com/0/1205648422731273/1209714124375337/f
This PR adds a temporary pixel to measure how often existing account is restored when purchasing subscription.
See task

Send pixel when existing account is restored during successful purchase

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt

Task/Issue URL: https://app.asana.com/0/0/1209754552084246
Adds logic to always complete the omnibar/minibar transition.
The behavior is as follows:
- If user scrolls down, we always immediately start transitioning to minibar.
- If user scrolls up, we only start transitioning back to omnibar after a scroll threshold since the start of last gesture is reached. This is done so that as users scroll back-and-forth around the page we don't switch between omnibar/minibar all the time - only significant scroll gestures and flings, hitting top of the page, or clicking the minibar, will reveal the omnibar back.
- If gesture has any velocity, we complete the transition in the direction of the gesture.
Known issues:
- If we're near the bottom of the page, and **omnibar** is visible, scrolling very …

always complete omnibar/minibar transitions with an animation

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherMenuExt.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
app/src/main/res/layout/popup_tabs_menu.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchOptionHandlerImplTest.kt
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
app/src/test/java/com/duckduckgo/tabs/db/TabsDaoTest.kt
app/src/test/java/com/duckduckgo/tabs/model/TabDataRepositoryTest.kt
browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1209846575622288/f
This PR implements the following changes:
- Implement undo snackbar after tab deletion in the browser screen
- Add the AI chat back to the normal mode menu
- Reverse the order of share/bookmark tabs in selection mode
- Revert the tab switcher title back to "Tabs"
_Undo snackbar_
_AI chat_
_Selection mode menu_
_Tab switcher screen title_

Multi-selection: Ship review change requests

---

node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209891408682992/f 
----- 

Update content scope scripts to version 8.11.0

---

app/src/main/java/com/duckduckgo/app/trackerdetection/blocklist/BlockList.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209712273096812/f 
This PR adds more blocklist experiments

Add more blocklist experiments

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/navigation/bar/BrowserNavigationBarViewIntegration.kt
app/src/main/java/com/duckduckgo/app/browser/navigation/bar/view/BrowserNavigationBarView.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/TopAppBarBehavior.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/ScrollingOmnibarLayout.kt
app/src/main/res/layout/fragment_browser_tab.xml
app/src/main/res/layout/view_browser_navigation_bar.xml
app/src/main/res/layout/view_fade_omnibar.xml

Task/Issue URL: https://app.asana.com/0/0/1209874980847231
Removes the minibar implementation and reconsolidates the FadeOmnibarLayout and BrowserNavigationBarView with the CoordinatorLayout implementation.
Known issues:
- When the top omnibar is enabled, some pages might have the navigation bar overlapping with content. Not an issues when the bottom omnibar is enabled.
_before_
https://github.com/user-attachments/assets/7c0d2bc0-29db-4ba0-b2d2-299b3de87312
_after_
https://github.com/user-attachments/assets/204489c5-2245-4903-b7f8-f7fc4824d417

remove minibar

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209900850846011/f 
----- 

Update content scope scripts to version 8.12.0

---

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
experiments/experiments-impl/src/test/java/com/duckduckgo/experiments/impl/ReturningUserToggleTargetMatcherTest.kt
feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt
feature-toggles/feature-toggles-impl/lint-baseline.xml
feature-toggles/feature-toggles-impl/src/main/java/com/duckduckgo/feature/toggles/impl/RealFeatureTogglesCallback.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/FeatureTogglesTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/fakes/FakeFeatureTogglesCallback.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/impl/LocaleToggleTargetMatcherTest.kt
feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/impl/MinSdkToggleTargetMatcherTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/SubscriptionsToggleTargetMatcherPluginTest.kt

Task/Issue URL: https://app.asana.com/0/1200581511062568/1209869840246080/f
Added support for minimum SDK version targeting in experiments. This allows features to be enabled only for devices running a specific Android SDK version or higher. 
Added unit and integration tests 
_Test minSdkVersion target_

Experiment framework: Add minSdkVersion to Target 

---

app/src/main/java/com/duckduckgo/app/browser/navigation/bar/view/BrowserNavigationBarView.kt
app/src/main/java/com/duckduckgo/app/browser/webview/BrowserContainerLayoutBehavior.kt
app/src/main/res/layout/fragment_browser_tab.xml

Task/Issue URL: https://app.asana.com/0/0/1209897414427802
Adds to the browser container a behavioral dependency on the navigation bar, so that the content of the browser doesn't overlap with the bar.
_before_
https://github.com/user-attachments/assets/d6c73985-b667-4c85-a29d-e7381e2fd44d
_after_
https://github.com/user-attachments/assets/c48f8c3c-3641-4b72-89ab-ca920287d36a

fix web view container to shift content up when bottom navigation bar is visible

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1209918883790892/f 
----- 

Update content scope scripts to version 8.13.0

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PProUpsellBannerPlugin.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PproUpsellDisabledMessagePlugin.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/message/PproUpsellRevokedMessagePlugin.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1209860021472115/f
Update origins for AppTP entry points to PrivacyPro
_Pre steps_
- Make sure you are Privacy Pro eligible
_Banner_
_Revoked_
_Disabled_

Update origins: AppTP entry points to Privacy Pro

---

app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/browser/duckchat/AIChatQueryDetectionFeature.kt
app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1209440300063888/f
- Improves handling of Duck.ai bangs in order to prevent a blank screen upon launch.
- Bang regex and list of supported bangs is set in the config.
_Load the config linked in the task_
<table>
<tr>
<td align="center">
<strong>Before</strong><br>
</td>
<td align="center">
<strong>After</strong><br>
</td>
</tr>
</table>

Improve Duck.ai bang handling

---

app-tracking-protection/vpn-impl/src/main/res/values-bg/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-cs/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-da/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-de/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-el/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-es/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-et/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-fi/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-fr/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-hr/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-hu/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-it/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-lt/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-lv/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-nb/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-nl/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-pl/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-pt/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-ro/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-ru/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-sk/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-sl/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-sv/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values-tr/strings-vpn.xml
app-tracking-protection/vpn-impl/src/main/res/values/donottranslate.xml
app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml

Task/Issue URL: https://app.asana.com/0/0/1209734846386434
Translate AppTP Privacy Pro entry points
- banner
- revoked
- disabled
_Pre steps_
- Make sure you are Privacy Pro eligible
- Switch your device language to something other than English
_Banner_
_Revoked_
_Disabled_

Translations for AppTP Privacy Pro entry points

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/viewstate/CtaViewState.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1209868780091258
- Added a temporary pixel to catch an edge case where onboarding remains active even after all dialogs have been shown. 
- Also included logic to complete onboarding in that scenario, and 
- renamed a few variables for clarity
_Onboarding_
_Temporary pixel (Optional)_

Onboarding: Auto complete temporary pixel

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/VpnPixelParamRemovalPlugin.kt
app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
app/src/test/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptorTest.kt
common/common-utils/src/main/java/com/duckduckgo/common/utils/plugins/pixel/PixelParamRemovalPlugin.kt
downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/pixels/DownloadsPixelName.kt
statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1209956345642687?focus=true
This PR removes an API that is effectively a no-op, as it doesn’t impact pixel behavior. PixelParamRemovalPlugin.OS_VERSION is never added to pixels and thus doesn’t need removal. 
QA-optional

Remove OS_VERSION from PixelParamRemovalPlugin

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1209964667726374?focus=true
This PR fixes one of the E2E tests, which fails because onboarding does not resume correctly after the fire button is used to clear the data.

Fix: E2E tests

---

.maestro/onboarding/onboarding_dismiss_all_dialogs.yaml
.maestro/onboarding/onboarding_dismiss_try_a_search_dialog.yaml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200581511062568/task/1209976250734772?focus=true
Updated the names of two Maestro test files to better reflect their purpose:
- Changed `onboarding_dismiss_all_dialogs.yaml` test name to "Onboarding: Ensuring we can navigate through pre-onboarding flow and dismissing all dialogs"
- Changed `onboarding_dismiss_try_a_search_dialog.yaml` test name to "Onboarding: Ensuring we can navigate through pre-onboarding flow and dismissing the fire dialog"
_Maestro Tests_
Tests are passing -> https://github.com/duckduckgo/Android/actions/runs/14444800539/job/40502769051

Renamed tests to avoid Robin errors due to name conflict.

---

malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteModule.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1209959841243986?focus=true 
Use dedicated executor for MSP transactions to prevent thread exhaustion on Room executors
_Feature 1_

Add executor for MSP Room transactions

---

.maestro/ppro/launch_privacy_pro_from_special_url.yaml
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt

This PR adds the missing SettingsScreenNoParams annotation to enable launching the Settings screen with the GlobalActivityStarter. 
A release Maestro test has been added to verify that launching Privacy Pro from a special URL works correctly.
I've also moved to using GlobalActivityStarter to launch Settings via the Browser screen so this becomes more obvious if it happens again.
_Privacy Pro URL Test_
_Open settings_
_Maestro test_
No UI changes in this PR.

Fix privacy pro not launching from ppro url

---

app/src/main/res/layout/include_custom_tab_toolbar.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1209987826470158?focus=true
All the of the text views are anchored to the title, so to fix the content jump I'm making sure that the title view is always present in the layout and hidden instead of removed when title text is not available.
_before_
https://github.com/user-attachments/assets/acafa3cf-6e11-4c8d-bca2-3520562b9e75
_after_
https://github.com/user-attachments/assets/3267bda7-0e83-4853-8cf4-1e9936ae127a

fix Omnibar's content jump when Custom Tab's title becomes available

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/navigation/bar/view/BrowserNavigationBarViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/dispatchers/IntentDispatcherActivity.kt
app/src/main/res/layout/view_fade_omnibar.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1209703519253563?focus=true
Updated the behavior of navigation bar to hide when in Custom Tab. Also re-aligned Custom Tab design with production, only with the updated background colors.
I tried reusing as much from the production implementation as possible, since the designs are nearly identical.
1. Experiment before
2. Experiment after
3. Production
| 1 | 2 | 3 |
| ------ | ------ | ------ |
|  ![Screenshot_20250414_135544](https://github.com/user-attachments/assets/b56af895-f104-420d-8aa0-843eb42519b1) | ![Screenshot_20250414_164147](https://github.com/user-attachments/assets/641f7784-f02d-4af3-8d9b-8641d3ec17c7) | ![Screenshot_20250414_144119](https://github.com/user-attachments/assets/d6a295fe-c17d-4a73 …

update Custom Tab omnibar and navigation bar behavior/layout

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1174433894299346/task/1209989368141940?focus=true
This PR hides / shows duck.ai in the new visual design based on the user selection.
_Enabled_
_Disabled_
_Update value_

Visual design: AI Chat

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
app/src/test/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1208855331182033?focus=true
This PR filters out the current tab from the switch-to-tab suggestion list.

Quick win: Skip the current tab in switch-to-tab suggestions

---

app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200581511062568/task/1209979916234701?focus=true
Added a few conditions for when onboarding is considered complete in NewTabLegacyPageViewModel: `noBrowserCtas` toggle enabled or tips hidden or add widget dismissed.

Android: NewTabLegacyPage onboardingComplete logic incomplete

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSitePomptDataStore.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210012823537208?focus=true
This PR replaces usages of `first()` with `firstOrNull()` in two locations to prevent potential crashes when collecting from empty flows.
N/A

Android Crash: [Not fixed in 5.230.0] java.util.NoSuchElementException - kotlinx.coroutines.flow.FlowKt__ReduceKt.first(Reduce.kt:92)

---

app/src/main/java/com/duckduckgo/app/browser/navigation/bar/BrowserNavigationBarViewIntegration.kt
app/src/main/java/com/duckduckgo/app/browser/navigation/bar/view/BrowserNavigationBarView.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/BottomAppBarBehavior.kt
app/src/main/java/com/duckduckgo/app/browser/webview/BrowserContainerLayoutBehavior.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210010551182684?focus=true
Fixes an issue where navigation bar, even when gone when keyboard is inflated, would still retain the offset applied to the web view content.
The fix is to notify the coordinator layout that navigation bar changed, when its visibility changes, which doesn't happen by default.
We already have handling of that available in the behavior that adjusts browsers padding:
https://github.com/duckduckgo/Android/blob/c0e22478de53029ceb4f6f80188c97782a74562a/app/src/main/java/com/duckduckgo/app/browser/webview/BrowserContainerLayoutBehavior.kt#L53-L78
1. Before
2. After
| 1  | 2 |
| ------ | ------ |

fix WebView offset when navigation bar enabled and keyboard visible

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/FindInPage.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt
app/src/main/res/drawable/ic_chevron_down_24e.xml
app/src/main/res/drawable/ic_chevron_up_24e.xml
app/src/main/res/drawable/ic_close_24e.xml
app/src/main/res/drawable/ic_find_in_page_24e.xml
app/src/main/res/layout/include_fade_omnibar_find_in_page.xml
app/src/main/res/layout/view_fade_omnibar.xml
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1209874980847232
Updates the "find in page" design for the `FadeOmnibarLayout`.
Functionally, there’s no change for the production omnibar. But in the experimental omnibar - where the "find in page" UI is moved inside the card - we can now detect when it’s shown and hide other content accordingly. This lets us reuse the omnibar card’s existing design and animations.
This PR keeps the changes minimal, focused on adapting "find in page" for the experimental omnibar. As a follow up, in https://github.com/duckduckgo/Android/pull/5926, I'm attempting to migrate the whole of "find in page" state management out of `BrowserTabViewModel` and into the omnibar, along with further cleanup.
| ------ …

update find in page feature in FadeOmnibarLayout

---

broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSitePomptDataStore.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210033439367731?focus=true 
Replace first() with firstOrNull() in BrokenSitePromptDataStore

Replace first() with firstOrNull() in BrokenSitePromptDataStore

---

common/common-ui/src/main/res/values/design-experiments-colors.xml
common/common-ui/src/main/res/values/design-experiments-theming.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1142021229838617/task/1210010466569435?focus=true
Adds the missing icon tertiary colors, and applies them in the experimental theme.
With the experimental flag enabled, try and button that has an enabled and disabled state, whether it's represented correctly. For example, when adding a bookmarks folder.

fix disabled icon colors in the ui experiment

---

app/src/main/res/layout/include_onboarding_bubble_dax_dialog.xml
app/src/main/res/layout/include_onboarding_in_context_dax_dialog.xml
common/common-ui/src/main/res/values/widgets.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210045609366338?focus=true
Added a circular style to the close button in onboarding dialogs by applying the `Widget.DuckDuckGo.FloatingActionButton.Circular` style to the FAB in both bubble and in-context DAX dialog layouts. Created a new style in widgets.xml that uses the Material Components circular shape appearance overlay.
_Verify close button appearance_
| Before (context dialog) | After (context dialog) | After (in-context dialog)|
| ------ | ----- | ----- |
|![Screenshot 2025-04-22](https://github.com/user-attachments/assets/88788640-3f2c-42fd-9bd0-de157f447f4d)|![Screenshot_20250422_185631](https://github.com/user-attachments/assets/4abd7f1d-4f87-4b1f-a286-499c35557d11)|![Screenshot_20250422_185648]( …

Android: FAB button looks different on different OS versions

---

app/src/main/java/com/duckduckgo/app/browser/navigation/bar/view/BrowserNavigationBarView.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/BottomAppBarBehavior.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
app/src/main/java/com/duckduckgo/app/browser/webview/BrowserContainerLayoutBehavior.kt
app/src/main/res/layout/fragment_browser_tab.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210046079393105?focus=true
Continues building on https://github.com/duckduckgo/Android/pull/5931, where the full intended behavior for the bottom omnibar wasn't actually being applied.

fix browser content offset when interacting with web forms

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1209917212981563?focus=true
Handle experiment metadata and pass to `/confirm` endpoint for a future Front End experiment. For the moment, this change shouldn't make any difference in the paywall
_Pre steps_
_Regression check: Paywall unaffected_
_Experiment integration (tratment A)_

Handle experiment metadata from subscriptionSelected message

---

malicious-site-protection/malicious-site-protection-api/src/main/kotlin/com/duckduckgo/malicioussiteprotection/api/MaliciousSiteProtection.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionFeature.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionFiltersUpdateWorker.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionHashPrefixesUpdateWorker.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/MaliciousSiteRepository.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/network/MaliciousSiteDatasetService.kt
malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/network/MaliciousSiteService.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionFiltersUpdateWorkerTest.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionHashPrefixesUpdateWorkerTest.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionReferenceTest.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/RealMaliciousSiteRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/0/1209893469792815/f 
_Feature 1_
_Feature 2_

Add separate worker for scam, so it can handle RC updates immediately

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/repository/DuckChatFeatureRepository.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/store/DuckChatDataStore.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/repository/DuckChatFeatureRepositoryTest.kt
privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeatureName.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1210070864871955?focus=true
- Fixes a race condition where Duck.ai settings are accessed before they are initialized.
_Point at the config linked in the task_

Fix Duck.ai settings race condition

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/navigation/bar/BrowserNavigationBarViewIntegration.kt
app/src/main/java/com/duckduckgo/app/browser/navigation/bar/view/BrowserNavigationBarView.kt
app/src/main/java/com/duckduckgo/app/browser/navigation/bar/view/BrowserNavigationBarViewModel.kt
app/src/main/res/layout/view_fade_omnibar.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210067401123378
This PR fixes the position and clipping of the privacy shield highlight (pulsating animation) during onboarding.
The class responsible for the animation (`PulseAnimation`) makes _a lot_ of assumptions about the target view hierarchy into which it injects an animated image view. I made the simplest fix possible to adjust the animated circle's position while fitting these assumptions but the solution comes with some hardcoded values. We should separately consider revisiting how the `PulseAnimation` class is built to allow more flexibility.
Additionally, to fix the clipping I moved the animation outside of the omnibar card. Even though the `PulseAnimation` forcefully disables clipping for all …

fix onboarding privacy shield and fire button highlights

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsActivity.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1209630328746101?focus=true
- Fixes `aichat_menu_setting_on` being fired when entering Duck.ai settings.

Fix toggle pixel fired when entering Duck.ai settings

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/pixel/DuckChatPixels.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1210081600357643?focus=true
- Adds pixels when toggling "Show Duck.ai in Address Bar”.
---
- https://app.asana.com/0/0/1210084233810306

Add Duck.ai address bar settings pixels

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/store/DuckChatDataStore.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/store/SharedPreferencesDuckChatDataStoreTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210096722341711?focus=true
- If the Duck.ai menu setting was initially disabled and the user updates, then the address bar setting is also disabled.
- However, if the the menu setting is toggled, then both settings toggle because there is no initial stored value for the address bar setting.
- This fixes that use-case.

Store initial Duck.ai address bar setting

---

app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210095429446719?focus=true
This pixel changes the pixel string, which was incorrect.

Multi-selection: Fix the close tabs daily pixel

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt
app/src/main/res/layout/view_fade_omnibar.xml
common/common-ui/src/main/res/values/design-experiments-dimens.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210095910664825?focus=true
This PR makes 3 small changes to the omnibar.
1. Stop the contents of the omnibar "wiggling" when transitioning between focus and unfocused state. Below videos are in slow motion:
2. Do not visually enlarge the omnibar's card when focus, only resize enough for the stroke to appear outside:
3. Decrease the bottom omnibar card's shadow and get it closer aligned with the shadow visible on the top omnibar card:

Omnibar outline and transition adjustments

---

node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/1/137249556945/project/414235014887631/task/1210128066798031?focus=true
Bumps C-S-S to version 8.19.0, which adds the `color=white` to Duck Player embedded URLs. This forces the classic YouTube player UI to display.
- Open Duck Player on any video
- Use Chrome to inspect the Duck Player window
- Confirm that the iframe has a src attribute that includes the query param `color=white` . You can run this on the console to confirm `document.querySelector('iframe').src.includes('color=white');`
- Confirm that the player interface looks like this
and not like this

Bump C-S-S to 8.19.0

---

versions.properties

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210142390986838?focus=true 
We saw a crash in `DataStore` code which looks like a race condition that is fixed in `DataStore 1.1.3`. There is a newer `1.1.4` and `1.1.5` both improving the same kinds of issues
- `1.1.5` is a broken release though so I'm pretending that doesn't exist
- this PR updates `DataStore` to use `1.1.4` (currently `1.1.1`)

Update DataStore to 1.1.4 to hopefully prevent a race condition

---

app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherAdapter.kt
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210140687033716
This PR fixes and edge case where only 1 tracker has been blocked and we display the tile animation.
This only applies to English, other languages in this edge case will see the english text.
Instructions - [instructions.mp4](https://app.asana.com/app/asana/-/get_asset?asset_id=1210103609702441)
Install apk and open Settings / Experimental UI Settings
Enable any of the O-10 Experiments. Restart the app to ensure it works as expected.
Note: This is not compatible with the O-A Experiment, please disable it for proper testing
_1 tracker blocked_

Tile experiment text edge case

---

app/src/main/java/com/duckduckgo/app/browser/tabpreview/WebViewPreviewGenerator.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210108991225075?focus=true
This fixes a bug when the WebView scrollbars would stay hidden if the preview generation threw an exception. This may happen fairly often with tab swiping when you swipe between tabs fast so that the webview doesn't get a chance to get laid out.

Fix: Ensure the scrollbars are always restored

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1209581454593298?focus=true
This PR fixes an issue when the WebView content is not rendered in the browser.
Before
https://github.com/user-attachments/assets/c5a0fcf0-3ac9-446f-8a81-d61bf74fae4e
After
https://github.com/user-attachments/assets/ca0bc4e0-ec20-4304-b30c-5154c4b11e41

Ensure the webview content is always rendered when fragment is resumed

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210186654423822?focus=true
This PR just calls `TabPagerAdapter.saveState()` and `restoreState()` whenever the activity is saved and restored.

Swiping tabs: Save tab pager state

---

app/src/main/java/com/duckduckgo/app/browser/tabs/DefaultTabManager.kt
app/src/test/java/com/duckduckgo/app/browser/tabs/DefaultTabManagerTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210095537840719?focus=true
This PR fixes the NTP creation. There was a logical error in the previous implementation when the wrong boolean was being returned in `transformWhile()` when requesting a new tab, which in some situation might result in the flow completion without emitting any value, which resulted in a crash.
I added code that throws an exception when a new tab is not created because it's an invalid state in the DB that I'm not sure how we should recover from. I don't think that's what was happening but in case it does, we'll know where to start looking.
I wasn't able to reproduce it, however, I added unit tests that should verify the fix works as expected.

Fix: NTP creation crash with tab swiping

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1174433894299346/task/1210122474301984?focus=true
The location permission messages are being shown more than expected.
_Message shown once_
_Message doesn’t show_
_Message shown on app restart_

Fix location permissions messaging

---

app/src/main/res/layout/item_autocomplete_bookmark_suggestion.xml
app/src/main/res/layout/item_autocomplete_history_search_suggestion.xml
app/src/main/res/layout/item_autocomplete_history_suggestion.xml
app/src/main/res/layout/item_autocomplete_switch_to_tab_suggestion.xml
common/common-ui/src/main/res/values/design-experiments-theming.xml
common/common-ui/src/main/res/values/design-system-attrs.xml
common/common-ui/src/main/res/values/design-system-theming.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210187246401092?focus=true
This PR updates the end paddings for the autocomplete suggestion items that don't have a trailing icon, as requested by design.
| Old  | New |

Visual update:Adjust the end autocomplete item paddings

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210194113621115?focus=true
Improve crash messaging when creating null tun.
Also add a small delay to give `startForeground` time to "settle".
Smoke test VPN and AppTP

Narrow down errors when creating null tunnel

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/blocklist/AppTrackerListUpdateWorker.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/settings/ExceptionListsSettingStore.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/settings/ExceptionListsSettingStoreTest.kt
app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/VpnAppTrackerBlockingDao.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202279501986195/task/1210112806879953?focus=true
Remove the eTag checks to ensure blocklist is always stored
_Test 1_
_Test 2_

Ensure blocklist is updated always

---

.github/workflows/privacy.yml
app/build.gradle
app/src/androidTest/java/com/duckduckgo/espresso/JsObjectIdlingResource.kt
app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
app/src/androidTest/java/com/duckduckgo/espresso/privacy/GpcTest.kt
build.gradle

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210170077557891?focus=true 
Tries to fix issues on privacy tests so we can re-enable them again.
Also updates workflow triggers so they run if CSS path changes.
Should pass -> https://github.com/duckduckgo/Android/actions/runs/14960434017

Re-enable Privacy Test cases

---

app/src/main/java/com/duckduckgo/app/browser/navigation/bar/view/BrowserNavigationBarViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/navigation/bar/view/BrowserNavigationBarViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/715106103902962/task/1210224367817693?focus=true
Fixes a regression from https://github.com/duckduckgo/Android/pull/6039 where we disconnected the fire button handler from the `BrowserNavigationBarViewModel`.
While I was there, I added unit test for all click handlers in the bottom nav bar.

fix fire button not responding to clicks

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deviceauth/AuthLauncher.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1209519141368890?focus=true 
Pixels the scenario whereby auth library returns that the required hardware isn’t present. We expected this not to happen because we check hardware in advance but we’ve seen a few reports indicating this might be happening still and we want to understand it more.
Since it’s not an error that’s possible to reproduce naturally, there is a patch that will map user-cancellations of the auth dialog to act as `ERROR_HW_NOT_PRESENT` errors for testing.
```
Index: autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deviceauth/AuthLauncher.kt
<+>UTF-8 …
```

Add pixel where auth indicates a hardware missing error

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/BottomAppBarBehavior.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
app/src/main/res/layout/include_new_browser_tab.xml
common/common-ui/src/main/res/layout/view_promo_message_cta.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210194248346098
The RMF `promo_single_action` was squished and misaligned in horizontal orientation because it lacked the vertical space to fit all of its elements in correct sizes.
To resolve that issue, we primarily need to make the new tab content page scrollable, which coincidentally is already happening in https://github.com/duckduckgo/Android/pull/6035, so I'm basing this PR on top it.
Additionally:
1. I'm making sure that the new tab page uses the correct behaviors to ensure that content is not clipped by the bottom navigation bar (when the UI experiment is enabled).
2. I'm updating the action button to `DaxButtonSecondary`.
Apply this diff to show a promo message:
```diff
diff --git …
```

Fix RMF promo_single_action layout when vertical space is constrained

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockedWarningLayout.kt
app/src/main/java/com/duckduckgo/app/browser/webview/SslWarningLayout.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210226097518216?focus=true
This PR disables the swiping on the following views:
- Loading error view
- Malicious site protection view
- SSL error view
_Loading error view_
_Malicious site error view_
```kotlin
Subject: [PATCH] Malicious site
---
Index: app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockerWebViewIntegration.kt
<+>UTF-8
diff --git a/app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockerWebViewIntegration.kt b/app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockerWebViewIntegration.kt
--- …
```

Tab swiping: Disable swiping on error views

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/repository/AuthRepository.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProBillingPeriodMatchingAttribute.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/services/SubscriptionsService.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/store/SubscriptionsDataStore.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/survey/PproSurveyParameters.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionWebViewViewModel.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/FakeSubscriptionsDataStore.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/RealAuthRepositoryTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProBillingPeriodMatchingAttributeTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProDaysSinceSubscribedMatchingAttributeTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProDaysUntilExpiryRenewalMatchingAttributeTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProPurchasePlatformMatchingAttributeTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriptionStatusMatchingAttributeTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/survey/PproSurveyParameterPluginsTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionViewModelTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210199014409745?focus=true
Parse `billingPeriod` from ConfirmResponse request and add it to Subscription Object
_Existing PPro user_
_Purchase yearly subscription_
_Purchase yearly subscription (Optional)_

Subscriptions: fetch billingPeriod property from BE

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1210232911000167/f 
----- 

Update content scope scripts to version 8.21.0

---

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeActivity.kt
sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModel.kt
sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/EnterCodeViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203822806345703/task/1210183822217249?focus=true 
Disables paste button while processing request.
Includes fix: update viewstate to idle after error.
Disables paste button while processing request.
Includes fix: update viewstate to idle after error.
_Test the connect device sync flow (manually enter code) under the following scenarios_
-> ensure in all of them, button is disabled while processing, enabled once finished (error or success)

Disable Paste button while processing request

---

remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/RealRemoteMessageModel.kt
remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/RemoteMessagingModelTests.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210248635492286
Don't dismiss `promo_single_action` remote message on action click, if the action is of type "share". 
Apply this diff to get an RMF config with the message:
```diff
diff --git a/remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/network/RemoteMessagingService.kt b/remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/network/RemoteMessagingService.kt
index 7c0e619ba..cc34cfa5d 100644
--- a/remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/network/RemoteMessagingService.kt
+++ b/remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/network/Rem …
```

RMF: do not dismiss promo_single_action on share action click

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/blocklist/AppTrackerListUpdateWorker.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/di/VpnAppModule.kt
app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabase.kt
app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabaseCallback.kt
app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabaseCallbackProvider.kt
app-tracking-protection/vpn-store/src/test/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabaseCallbackTest.kt
app-tracking-protection/vpn-store/src/test/java/com/duckduckgo/mobile/android/vpn/trackers/AppTrackerRepositoryTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202279501986195/task/1210212546082973?focus=true
Fix a race condition that can happen upon first install. Both the vpn db callbacks (onCreate) and the AppTP blocklist worker race to update the db.
It can happen that worker wins, updates db, then callback overrides it. Leaving an inconsistent state
_Test #1_
_Test #2_
_Test #3_

Avoid race condition when pre-populating VPN db

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1210257699578837/f 
----- 

Update content scope scripts to version 8.22.0

---

app/src/main/res/layout/view_browser_navigation_bar.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210248310047072?focus=true
Use primary icon color for menu icon on the nav bar.

use primary icon color for menu icon on the nav bar

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210251609451227?focus=true
When new visual design enabled, show the same hint in the omnibar when both text cleared on a page or NTP opened.

show the same omnibar hint on pages and NTP

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessaging.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessagingTest.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionsJSHelper.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/RealSubscriptionsJSHelperTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201807753394693/task/1210023557524902?focus=true
- Uses the C-S-S navigatorInterface + messageBridge to request information about the subscription status.
- The functionality is disabled when aiChat is disabled in the config.
_Pre steps_
- In line _3577_  log JS request `Timber.d("JsRequestMessage, featureName: $featureName, method: $method, id: $id")`
- In line _3631_  log JS response `Timber.e("JS response: $it")`
_Subscriptions message non US_
_Handshake request_
...
_subscriptionDetails request with no Subscription_
...
_subscriptionDetails request with active Subscription_
...
_subscriptionDetails request with expired Subscription_

Add Subscriptions SERP integration

---

app/src/main/res/layout/item_autocomplete_bookmark_suggestion.xml
app/src/main/res/layout/item_autocomplete_default.xml
app/src/main/res/layout/item_autocomplete_history_search_suggestion.xml
app/src/main/res/layout/item_autocomplete_history_suggestion.xml
app/src/main/res/layout/item_autocomplete_search_suggestion.xml
app/src/main/res/layout/item_autocomplete_switch_to_tab_suggestion.xml
common/common-ui/src/main/res/values/design-system-attrs.xml
common/common-ui/src/main/res/values/design-system-theming.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204284606155124/task/1210251609451243?focus=true
Remove extra padding for items, so that the touch listener can also look nicer

Visual design: Autocomplete

---

app/src/internal/java/experiments/trackersblocking/TrackersBlockingExperimentViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/senseofprotection/SenseOfProtectionExperimentImpl.kt
app/src/main/java/com/duckduckgo/app/browser/senseofprotection/SenseOfProtectionExperimentToggles.kt
app/src/main/java/com/duckduckgo/app/survey/rmf/TemporaryDefaultSurveyParameters.kt
app/src/test/java/com/duckduckgo/app/browser/senseofprotection/SenseOfProtectionExperimentImplTest.kt
app/src/test/java/com/duckduckgo/app/survey/rmf/TemporaryDefaultSurveyParametersPluginTest.kt
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207908166761516/task/1210235542874003
Update the Sense of Protection experiment toggle names from April to May, changing all references from `senseOfProtectionNewUserExperimentApr25()` to `senseOfProtectionNewUserExperimentMay25()` and `senseOfProtectionExistingUserExperimentApr25()` to `senseOfProtectionExistingUserExperimentMay25()`.
_Sense of Protection Experiment_
No UI changes in this PR.

Sense of Protection Experiment: Add new experiments

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/tabs/DefaultTabManager.kt
app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/FragmentStateAdapter.java
app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/TabPagerAdapter.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210250194815685?focus=true
This PR fixes a crash caused by `FragmentStateAdapter` attempting to restore fragment state when `FragmentManager` loses its fragments after activity recreation.

Fix: IllegalStateException crash

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210137390470561?focus=true
Adds a missing change to https://github.com/duckduckgo/Android/pull/5829 and ensures that the domain and/or duck chat icon are updated when Custom Tab page loads and redirects.

fix an issue where Custom Tab URL or icon wouldn't update according to page redirects

---

app/src/internal/AndroidManifest.xml
app/src/internal/java/com/duckduckgo/app/browser/webview/WebViewDevSettings.kt
app/src/internal/java/com/duckduckgo/app/browser/webview/WebViewDevSettingsActivity.kt
app/src/internal/java/com/duckduckgo/app/browser/webview/WebViewDevSettingsViewModel.kt
app/src/internal/java/com/duckduckgo/app/browser/webview/WebViewInformationExtractor.kt
app/src/internal/res/layout/activity_web_view_dev_settings.xml
app/src/internal/res/values/donottranslate.xml
internal-features/internal-features-api/src/main/java/com/duckduckgo/internal/features/api/InternalFeaturePlugin.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1209643196618443?focus=true 
Adds an internal dev settings screen for `WebView` debug info and accessing tooling.

Add WebView dev settings screen for internal builds

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
package-lock.json
package.json

Update content scope scripts to version 8.24.0

---

common/common-ui/src/main/res/drawable/selectable_item_experimental_background.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210251609451213?focus=true
Uses a fully opaque (100% alpha) color for the ripple mask.
The actual color doesn't matter, but devices handle the alpha channel differently:
- On tested devices, a 0% alpha mask makes the ripple effect invisible.
- On tested Pixels, any alpha > 0% applies the ripple color correctly.
- On tested Samsungs, the ripple alpha is affected by both the mask and the ripple color alpha, summing them up and causing unexpected results.
To ensure consistent ripple visibility across devices, always use a fully opaque mask.
The screenshots come from a Samsung Tab S9+. You can see that on the _before_ screenshot, the ripple is barely visible because the …

use fully opaque ripple mask

---

malicious-site-protection/malicious-site-protection-impl/src/main/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/MaliciousSiteRepository.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/MaliciousSiteProtectionReferenceTest.kt
malicious-site-protection/malicious-site-protection-impl/src/test/kotlin/com/duckduckgo/malicioussiteprotection/impl/data/RealMaliciousSiteRepositoryTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210226116146307?focus=true 
We still see some ANRs that seem to be related to a database connection not being acquired on first app run. Looking at the logs, it looks like it happens on devices with 1GB RAM, which only allow for 1 simultaneous SQLite connection. 
Add mutex to get revisions, so if another DB operation needs to happen at the same time, it can decide whether to wait for the lock to be acquired or use a default value 
_Feature 1_

Expand mutex setup to revisions and exceptions

---

versions.properties

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210239213905771?focus=true 
Updates `DataStore` to the latest stable version: [`1.1.6`](https://developer.android.com/jetpack/androidx/releases/datastore#1.1.6). 
Smoke test, especially anything you know touches `DataStore`.

Update DataStore to 1.1.6

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsActivity.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210318903201897?focus=true 
Send import shown pixel when option available when screen renders
_Feature 1_
_Feature 2 (optional)_
Run this on a device where option is not available

Send shown pixel if option to import available

---

app/src/main/java/com/duckduckgo/app/onboardingdesignexperiment/OnboardingDesignExperiment.kt

This PR adds a new remote feature toggle for the onboarding design experiment. The feature includes two toggles:
- `self()`: Main toggle for the entire experiment (default: OFF)
- `buckOnboarding()`: Toggle for the buck onboarding variant (default: OFF)
_Onboarding Design Experiment_

Add onboarding design experiment feature toggles

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1157893581871903/task/1210317910216891?focus=true
Fixes an issue where omnibar would be stuck in wrong width after orientation change.
Initially, I thought this is because of the state update which occurs right after `onSizeChanged` and re-locks the dimensions but after refactoring the code to ensure animation is started only when needed, I realized that the issue was due to some race condition within the Android framework while the layout params were being updated directly in the `onSizeChanged` loop.
With the layout inspector, this is what I found out:
1. We are in an unfocused state, the card's content is `match_parent`, as expected:
2. We click into the omnibar and grab focus, the card's contents get locked so that they …

fix an issue where omnibar would be stuck in wrong width after orientation change

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210331174511735
Remove logic for sending Free trials experiment details to BE metrics
_Pre steps_
_Experiment data sent to BE_

Remove Blocking Free Trial Experiment Code

---

remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/di/RMFMapperModule.kt
remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/mappers/MessageMapper.kt
remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/fixtures/TestMessageMapper.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210331622687071?focus=true
Moves creation of RMF JsonAdapter to lazy so it inits on background thread
_Feature 1_

Move RMF jsonAdapter to lazy

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208589375218614/task/1210288585414843?focus=true
The motog workaround is executed in the NgVpnNetworkStack.
We only need to report the fix when it is actually implemented.

VPN/AppTP: Fix incorrect reporting for motogFix

---

app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsActivity.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/view/DaxSwitch.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsActivity.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210337463408658?focus=true
The toggle's view state that gets restored after a configuration change triggers the `OnCheckChanged` listeners and resets the saved values on settings screens that use it. This PR disables the view state saving, which fixes the issue.
_General settings_
_Duck.AI settings_
Before
[Screen_recording_20250521_151134.webm](https://github.com/user-attachments/assets/8745ac50-3e5a-471d-87ab-d026a1a22d31)
After
[Screen_recording_20250521_150543.webm](https://github.com/user-attachments/assets/7b477bec-4ab9-490d-9ae3-2512b6e8a715)

Fix: Settings toggle is reset on config change

---

.maestro/autofill/1_autofill_shown_in_overflow.yaml
.maestro/autofill/2_autofill_add_search_update_delete_creds.yaml
.maestro/autofill/3_autofill_prompted_to_save_creds_on_form.yaml
.maestro/autofill/4_autofill_settings_creds.yaml
.maestro/autofill/backfillingUsername/multi_step_login_username_backfilled.yaml
.maestro/autofill/backfillingUsername/multi_step_login_username_backfilled_for_an_update.yaml
.maestro/autofill/backfillingUsername/multi_step_login_username_not_backfilled_if_provided_explicitly.yaml
.maestro/autofill/backfillingUsername/multi_step_registration_username_backfilled_password_autogenerated.yaml
.maestro/autofill/backfillingUsername/multi_step_registration_username_backfilled_password_manually_entered.yaml
.maestro/autofill/backfillingUsername/password_reset_flow_autogenerated_password.yaml
.maestro/autofill/backfillingUsername/password_reset_flow_for_existing_credential_generated_password.yaml
.maestro/autofill/backfillingUsername/password_reset_flow_for_existing_credential_manual_password.yaml
.maestro/autofill/passwordGeneration/autosaves_credential_when_password_generated_with_username.yaml
.maestro/autofill/passwordGeneration/autosaves_credential_when_password_generated_without_username.yaml
autofill/autofill-impl/build.gradle

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210387502072421?focus=true 
Updates the remaining Autofill tests to run against `internal` build types. The critical tests were updated already.
This is **QA optional**. If you want to test:

Update non-critical Autofill tests so they can run against internal builds again

---

app/src/internal/java/experiments/trackersblocking/TrackersBlockingExperimentViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/senseofprotection/SenseOfProtectionExperimentImpl.kt
app/src/main/java/com/duckduckgo/app/browser/senseofprotection/SenseOfProtectionExperimentToggles.kt
app/src/main/java/com/duckduckgo/app/survey/rmf/TemporaryDefaultSurveyParameters.kt
app/src/test/java/com/duckduckgo/app/browser/senseofprotection/SenseOfProtectionExperimentImplTest.kt
app/src/test/java/com/duckduckgo/app/survey/rmf/TemporaryDefaultSurveyParametersPluginTest.kt
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/experiments/visual/store/VisualDesignExperimentDataStoreImpl.kt
common/common-ui/src/test/java/com/duckduckgo/common/ui/experiments/visual/store/VisualDesignExperimentDataStoreImplTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207908166761516/task/1210385405168427 
Updated the Sense of Protection experiment toggle names from `senseOfProtectionNewUserExperimentMay25` and `senseOfProtectionExistingUserExperimentMay25` to `senseOfProtectionNewUserExperiment27May25` and `senseOfProtectionExistingUserExperiment27May25` respectively. Also added these new toggle names to the list of visual design experiment toggles.
_Sense of Protection Experiment_
N/A

Sense of Protection Experiemnt: Add new experiment names

---

app/src/main/java/com/duckduckgo/app/onboarding/ui/page/BuckOnboardingDialogView.kt
app/src/main/res/drawable/background_buck_onboarding_dialog.xml
common/common-ui/src/main/res/values/design-system-theming.xml
common/common-ui/src/main/res/values/temp_colors.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205648422731273/task/1210409460462702?focus=true
This PR adds new dialog component for use in the upcoming onboarding design experiment.
QA-optional

Dialog component for the onboarding design experiment 

---

common/common-ui/src/main/java/com/duckduckgo/common/ui/experiments/visual/store/VisualDesignExperimentDataStoreImpl.kt
common/common-ui/src/test/java/com/duckduckgo/common/ui/experiments/visual/store/VisualDesignExperimentDataStoreImplTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210411891798809?focus=true
The Duck.ai experimental UI toggle always resets to false, this fixes it and adds some tests.

Fix Duck.ai PoC toggle

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210392359930072?focus=true
Fixes an omnibar layout bug with tab swiping when new UI is enabled and the omnibar position is set to bottom.
_Feature 1_

Fix: Swiping with new UI & bottom bar

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixel.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/pixels/SubscriptionPixelSender.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205648422731273/task/1209739160375703?focus=true
This PR removes a pixel that was used to measure how often an expired account is restored during Privacy Pro purchase.

Remove temporary pixel to measure expired account restore while purchasing Privacy Pro

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/billing/PricingPhaseTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201807753394693/task/1210432795362321?focus=true
Refactor getBillingPeriodInDays() so we support all Google Play date ranges
_Free Trial purchase_
_Unit tests_

Refactor getBillingPeriodInDays to support all values

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/launch/LaunchBridgeActivity.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/experiments/visual/store/VisualDesignExperimentDataStore.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/experiments/visual/store/VisualDesignExperimentDataStoreImpl.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/experiments/visual/store/VisualDesignExperimentDataStoreLazyProvider.kt
common/common-ui/src/test/java/com/duckduckgo/common/ui/experiments/visual/store/VisualDesignExperimentDataStoreLazyProviderTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210355090527279
1. `LaunchBridgeActivity` now extends `DaggerActivity` directly instead of `DuckDuckGoActivity`. Since it doesn't include any styleable elements, it doesn't need to load the app theme. This allows the visual design data store - needed later to retrieve the theme instance - to be prepared asynchronously.
2. `VisualDesignExperimentDataStoreImpl` is now wrapped in `VisualDesignExperimentDataStoreLazyProvider`, which adds an initialize function. This allows `LaunchBridgeActivity` to pre-warm the data store while the splash screen is visible, before launching other activities.
Together, these changes fully move `VisualDesignExperimentDataStore` initialization to a worker thread, avoiding any …

initialize VisualDesignExperimentDataStore on a worker thread

---

common/common-ui/src/main/res/animator/buck_button_animator_set.xml
common/common-ui/src/main/res/drawable/buck_button_primary_container_selector.xml
common/common-ui/src/main/res/drawable/buck_primary_button_background.xml
common/common-ui/src/main/res/layout/component_buttons.xml
common/common-ui/src/main/res/values-night/temp_colors.xml
common/common-ui/src/main/res/values/temp_colors.xml
common/common-ui/src/main/res/values/widgets.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207908166761516/task/1210435540768301 
Added new button styles for the onboarding experiment. Created primary and secondary "buck" button variants with custom animations, colors, and styling for both light and dark themes.
Note: As we're using temp colors and not making this part of the theme, enabling "Dark Theme" on the ADS screen will not work. 
This is of no consequence for the experiment as we'll be targeting people new to the app and we'll be using system theme settings (not app theme settings) to determine the button theme.
_Button Styles_
| Light  | Dark |
|![Screenshot_20250602_112101](https://github.com/user-attachments/assets/72b9aaca-41b4-4c91-8966-a3f6aed8328f)|![Screenshot_20250602_112126](https: …

Onboarding Experiment: Add button styles

---

common/common-ui/src/main/java/com/duckduckgo/common/ui/Theming.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/414730916066338/task/1210402384079670?focus=true
Fixes the theme radio to pre-select correct theme.

fix incorrectly selected current theme in the theme radio

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/tabs/TabFeatureFlags.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
app/src/test/java/com/duckduckgo/tabs/db/TabsDaoTest.kt
app/src/test/java/com/duckduckgo/tabs/model/TabDataRepositoryTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203249713006009/task/1210059188286306?focus=true
Fix Duck Player video not being shown because of:
1. In TabsRepository we were using postValue instead of setValue, and therefore in some cases the new value was not emitted in time
2. This X post generates a temporary intermediate tab when clicking the link, that then launches the Duck Player video on a new tab. This intermediate tab has no URL, and therefore when the Duck Player tab is inserted via addAndSelectTab (which removes tabs with null URL as the first step), insertion fails because of a foreign key violation (sourceTabId doesn't exist anymore)
_Feature 1_
_Feature 2_

Fix tab not being inserted when opening in new tab

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsActivity.kt
subscriptions/subscriptions-impl/src/main/res/values-bg/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-cs/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-da/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-de/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-el/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-es/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-et/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-fi/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-fr/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-hr/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-hu/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-it/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-lt/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-lv/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-nb/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-nl/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-pl/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-pt/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-ro/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-ru/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-sk/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-sl/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-sv/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values-tr/strings-subscriptions.xml
subscriptions/subscriptions-impl/src/main/res/values/strings-subscriptions.xml

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210449725813015?focus=true
Split the subscription renewal information string into separate monthly and yearly resources

Fix Translation of Subscription Settings Strings

---

app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
app/src/main/res/drawable/ic_home_screen_widget_color_24.xml
app/src/main/res/layout/content_settings_protections.xml
app/src/main/res/values/donottranslate.xml
app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
settings/settings-api/src/main/java/com/duckduckgo/settings/api/SettingsPageFeature.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200581511062568/task/1210403485354666?focus=true
Added a Home Screen Widget option to the Protections section in Settings. This feature is controlled by the `widgetAsProtection` toggle in `SettingsPageFeature`. When enabled, the widget option appears in the Protections section and is removed from the Next Steps section.
_Widget in Protections Section (widgetAsProtection flag enabled)_
| Flag disabled (widget in Next Steps) | Flag enabled (widget in Protections) |
|![flag_disabled](https://github.com/user-attachments/assets/28f1a23e-30f9-48aa-8a43-9ebc6a89ba24)|![flag_enabled](https://github.com/user-attachments/assets/b77387bd-0ad9-45ad-b9f9-7cf12a10e513)|

Implement change in Settings (widget as a protection)

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt
app/src/main/res/layout/view_fade_omnibar.xml
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatOmnibarLayout.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/SearchInterstitialActivity.kt
duckchat/duckchat-impl/src/main/res/layout/view_duck_chat_omnibar.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210498773096186?focus=true
- Updates the transition from the browser tab to search interstitial

Update web to search interstitial transition

---

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/TimerUtils.kt
network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208589375218614/task/1210383294207835?focus=true
Improve VPN timer to show days, hours, minutes and seconds.
We also don't show 0 values except when it is the starting value which is 0s.
Optionally you can check hours and days values but that could take time

Show days in VPN timer

---

app/src/main/java/com/duckduckgo/app/global/shortcut/AppShortcutCreator.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210512060310715?focus=true
- This is a speculative fix for https://app.asana.com/1/137249556945/project/414730916066338/task/1210509768361310

Fix Duck.ai shortcut not showing on internal

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/BottomAppBarBehavior.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarBehaviour.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/TopAppBarBehavior.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/experiments/FadeOmnibarLayout.kt
downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DefaultFileDownloadNotificationManager.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1157893581871903/task/1210530805272776?focus=true
This PR fixes the wrong position of the Snackbar when the omnbiar at the top
_Visual Designs Disabled_
_Visual Designs Enabled_

Bug: Snackbars shown at the top

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/715106103902962/task/1210556246664919?focus=true
This PR adds a feature flag that controls the visibility of the duck.ai button in the omnibar.

Duck.ai: Browser button feature flag

---

app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210572537804655?focus=true
This fixes an issue when a bookmark was opened in a new tab.

Fix: Open bookmarks with tab swiping

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt
duckchat/duckchat-api/src/main/java/com/duckduckgo/duckchat/api/DuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/feature/DuckChatFeature.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210579127221598?focus=true
This PR fixes the Duck.ai button display logic so that the original behavior is independent of the "Duck.ai in browser" feature flag.

Fix: Duck.ai button visibility

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210510700371845?focus=true
Added an additional check in isFreeTrialEligible to handle the edge case where the feature flag is enabled, the user hasn’t had a free trial before, but the product is not available on the Play Store.
_ROW & deactivated Free Trial offers_
_US & Free Trial offered_

Add extra check for Free Trials availability on Play Store

---

.github/workflows/release_nightly.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1198194956794324/task/1210615704320806?focus=true
Trigger the Asana task creation only when nightlies are generated rather than always (even if develop hasn't changed)
NA, Code review

Trigger Asana task creation only when nightly is created

---

voice-search/voice-search-impl/src/main/res/layout/view_voice_recognizing_indicator.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210621076566331?focus=true
- Fixes the clipped mic icon when using private voice search.

Fix clipped mic icon

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210398081973867?focus=true
Adds missing pixel parameter.

add missing discovery param to autofill_settings_opened pixel

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarEntryConverter.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/QueryUrlConverter.kt
app/src/main/java/com/duckduckgo/app/browser/viewstate/BrowserViewState.kt
app/src/test/java/com/duckduckgo/app/browser/QueryUrlConverterTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210647917463143?focus=true
This PR fixes an issue when opening a bookmark from a NTP hides the loaded website.

Fix: Bookmark loading bug

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatOmnibarLayout.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/SearchInterstitialFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/inputscreen/Command.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/inputscreen/DuckAiInputScreenDataStore.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenDataStore.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenViewModel.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210658958592463
Persist the last used Input Screen mode and restore it when user opens the screen again.

restore last selected Duck.ai input screen mode

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt
app/src/test/java/com/duckduckgo/app/brokensite/api/BrokenSiteSubmitterTest.kt
app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesMultipleReportReferenceTest.kt
app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesReferenceTest.kt
broken-site/broken-site-api/build.gradle
broken-site/broken-site-api/src/main/java/com/duckduckgo/brokensite/api/BrokenSiteSender.kt
browser-api/build.gradle
browser-api/src/main/java/com/duckduckgo/app/global/model/Site.kt
browser-api/src/main/java/com/duckduckgo/browser/api/JsInjectorPlugin.kt
content-scope-scripts/content-scope-scripts-api/src/main/java/com/duckduckgo/contentscopescripts/api/contentscopeExperiments/ContentScopeExperiments.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/ContentScopeScriptsJsInjectorPlugin.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScripts.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/features/contentscopeexperiments/RealContentScopeExperiments.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/ContentScopeScriptsJsInjectorPluginTest.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScriptsTest.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/features/contentscopeexperiments/RealContentScopeExperimentsTest.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewClientTest.kt
privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModel.kt
privacy-dashboard/privacy-dashboard-impl/src/test/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205008441501016/task/1209783667491175?focus=true 
Send active cohorts for C-S-S experiments to broken site report
_Feature 1_

Send active cohorts to broken report site

---

.github/workflows/end-to-end-robintest.yml
.maestro/privacy_tests/14_-_Api_manipulation.yaml
.maestro/privacy_tests_internal/1_-_Api_manipulation.yaml
app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt
app/src/test/java/com/duckduckgo/app/brokensite/api/BrokenSiteSubmitterTest.kt
app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesMultipleReportReferenceTest.kt
app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesReferenceTest.kt
broken-site/broken-site-api/src/main/java/com/duckduckgo/brokensite/api/BrokenSiteSender.kt
browser-api/src/main/java/com/duckduckgo/app/global/model/Site.kt
common/common-ui/src/main/java/com/duckduckgo/common/ui/view/text/DaxTextInput.kt
common/common-ui/src/main/res/values/attrs-text-input.xml
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessaging.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsJsMessagingTest.kt
privacy-config/privacy-config-internal/src/main/res/layout/activity_privacy_config_internal_settings.xml
privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModel.kt
privacy-dashboard/privacy-dashboard-impl/src/test/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205008441501016/task/1210579835428579?focus=true
Send active cohorts for C-S-S experiments to broken site report
_Feature 1_
n/a

Send debug flags to broken site report

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Update content scope scripts to version 10.2.0

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatOmnibarLayout.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/SearchInterstitialFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenViewModel.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenVisibilityState.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210658486266625?focus=true
1. Show voice input button when input screen is initially opened (and all text is selected).
2. Show voice input button when input box is empty.
3. Hide the button in all other cases.

hide voice input button when duck.ai text changes

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/main/java/com/duckduckgo/app/global/shortcut/AppShortcutCreator.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt
app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
duckchat/duckchat-api/src/main/java/com/duckduckgo/duckchat/api/DuckAiFeatureState.kt
duckchat/duckchat-api/src/main/java/com/duckduckgo/duckchat/api/DuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210625163271723
Extracts Duck.ai feature state from `DuckChat` to `DuckAiFeatureState` public API.

Extract Duck.ai feature state to DuckAiFeatureState public API

---

app/src/test/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/ui/experiment/OnboardingHomeScreenWidgetExperimentImplTest.kt
app/src/test/java/com/duckduckgo/widget/experiment/PostCtaExperienceExperimentTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210683053177448?focus=true
The tests for `fireWidgetSearchXCount` in `OnboardingHomeScreenWidgetExperimentImplTest` and `PostCtaExperienceExperimentTest` have been updated.
The changes ensure that when testing the 3x search pixel, the 5x search pixel is explicitly mocked to return null, and vice-versa
N/A

Attempt to fix widget test failures on Nightlies

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillPasswordsManagementViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/google/ImportFromGooglePasswordsDialog.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/google/ImportFromGooglePasswordsDialogViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListModeLegacy.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsActivity.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsActivityScreenViewModelTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/google/ImportFromGooglePasswordsDialogViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210614808079934?focus=true 
Skips showing the "preimport" dialog for Google Import Passwords flow if launched from the import promo.
_For context, this is the preimport dialog_

Don't show preimport dialog when launching from password import promo

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/CredentialImporter.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/importing/CredentialImporterImplTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210619659166977?focus=true 
Changes the requirements around how many passwords must be imported to mark a previous import as having happened. 
- **Before:** we required 1 or more passwords were imported
- **Now:** we require that the user has finished the import flow, regardless of the number of credentials imported.
- QA optional

Change requirement for marking a previous password import as having happened

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/AutofillImportLaunchSource.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/promo/ImportInPasswordsPromotionViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillPasswordsManagementViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/ImportPasswordsPixelSender.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/google/ImportFromGooglePasswordsDialog.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/google/ImportFromGooglePasswordsDialogViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListModeLegacy.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsActivity.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsActivityScreenViewModelTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/importpassword/google/ImportFromGooglePasswordsDialogViewModelTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210421589932466 
Updates the pixels around password import prompts/buttons/dialogs, namely to include a `source` parameter indicating where the import was launched from.
Possible values: 
- `password_management_promo`
- `password_management_empty_state`
- `password_management_overflow`
- `autofill_settings_button`
- `unknown` (should never happen in reality)
Suggested logcat filter: `message~:"Pixel sent.*source="`

Add source to import flow pixels

---

app/src/test/java/com/duckduckgo/app/browser/defaultbrowsing/prompts/ui/experiment/OnboardingHomeScreenWidgetExperimentImplTest.kt
app/src/test/java/com/duckduckgo/widget/experiment/PostCtaExperienceExperimentTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210689268710086
Fixed timezone-related issues in widget experiment tests by explicitly specifying the timezone as "America/New_York" when creating test dates. This ensures consistent test behavior regardless of the environment's default timezone.
_Widget Experiment Tests_

Attempt 2 to fix widget experiment nightly test failures

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201807753394693/task/1210694952143862?focus=true
Launch Privacy Pro activity when users navigate to  duckduckgo.com/subscriptions URL

Support launching Privacy Pro paywall for subscriptions path

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/res/layout/activity_browser.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210708810784116?focus=true
Make `duckAiFragmentContainer` gone when the `DuckChatWebViewFragment` is not visible as well.

make Duck.ai container gone when it's unused

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210705948833249?focus=true 
- Adds support for getFeatureConfig and getAuthAccessToken
- Preparation work to fully migrate subscriptions flows to v2 ([Migrate Subscriptions flows to v2](https://app.asana.com/1/137249556945/task/1210705424261806?focus=true))
- Include FF for rollout and kill switch if necessary
- New messaging FF will be enabled
- V2 flows FF will be disabled until fully migrated
_Feature 1_
(add any smoke testing to ensure subscription flow is not impacted)

Adds support for getFeatureConfig and getAuthAccessToken in subscriptions flows

---

autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPlugin.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/ReplyHandler.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/RealAutoconsentTest.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/EvalMessageHandlerPluginTest.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPluginTest.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/OptOutAndAutoconsentDoneMessageHandlerPluginTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210704553451145?focus=true 
This PR tries to fix and ANR and crash in the autoconsent init handler. It does remove the call to trimIndent() which is not very performant for long strings (and doesn't seem to be needed) and it moves all the logic to IO leaving only the webview call to evaluate JS in main.

Fix ANR/Crash on autoconsent init handler

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/state/InputScreenVisibilityState.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/tabs/SearchTabFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/viewmodel/InputScreenViewModel.kt
saved-sites/saved-sites-api/src/main/java/com/duckduckgo/savedsites/api/views/SavedSitesViewsProvider.kt
saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/newtab/FavouritesNewTabSectionView.kt
saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/newtab/FavouritesNewTabSectionViewModel.kt
saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/views/SavedSitesViewsProviderImpl.kt
saved-sites/saved-sites-impl/src/main/res/layout/view_new_tab_favourites_section.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210708810784115?focus=true
Exposes favorites grid view so that it can be independently displayed on the Input Screen without having to bundle the whole NTP.

show only favorites without other NTP content on the Input Screen

---

app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsActivity.kt
app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsViewModel.kt
app/src/internal/java/com/duckduckgo/app/dev/settings/tabs/DevTabsActivity.kt
app/src/internal/java/com/duckduckgo/app/dev/settings/tabs/DevTabsViewModel.kt
app/src/internal/res/layout/activity_dev_settings.xml
app/src/internal/res/layout/activity_dev_tabs.xml
app/src/internal/res/values/donottranslate.xml
saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksActivity.kt
saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksAdapter.kt
saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksQueryListener.kt
saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksViewModel.kt
saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/414730916066338/task/1210718637089838?focus=true
1. Adds a new dev setting to populate saved sites repo with random bookmarks.
2. Optimizes bookmark search by skipping relative position recalculations. When filtering, item order remains unchanged, allowing us to bypass an extra round of equality checks.
3. Moves bookmark update diff computation to a worker thread to avoid UI thread contention and ANRs.
4. Decouples bookmark items to display from the rest of the state to avoid unnecessary computations and UI updates. Previously, updating the search query triggered a view state change (due to the persisted `ViewState#searchQuery`), which caused the `RecyclerView` to recalculate before the actual filtering occurred. As a result, …

Optimize bookmarks filtering and sorting

---

autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
autofill/autofill-impl/src/main/res/values/donottranslate.xml
autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/608920331025315/task/1210709764115871?focus=true 
Translations for the password import promo in password management screen.
- qa optional (lint check passing)

Translations for promoting password import in management screen

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewActivity.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/SubscriptionsHandler.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/SubscriptionsHandlerTest.kt
subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/SubscriptionScreens.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionsContentScopeJsMessageHandler.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionsJSHelper.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingView.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/RestoreSubscriptionActivity.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionSettingsActivity.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/RealSubscriptionsJSHelperTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionsContentScopeJsMessageHandlerTest.kt
subscriptions/subscriptions-internal/build.gradle
subscriptions/subscriptions-internal/src/main/java/com/duckduckgo/subscriptions/internal/settings/RecoverSubscriptionView.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210461583262416?focus=true 
Adds integration between duck.ai and subscriptions.
Includes:
- messaging for Feature Flags in FE
- share token
- navigational events
_Feature 1_
(after subscription restart the app, this is to avoid Duck.ai chat being restored, something we need to fix in https://app.asana.com/1/137249556945/project/1149059203486286/task/1210671370392466?focus=true)

Add duck.ai chat - subscriptions integration

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/FeedbackSubCategoryProvider.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackCategoryFragment.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackParams.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModel.kt
subscriptions/subscriptions-impl/src/main/res/layout/content_feedback_category.xml
subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210461583262423?focus=true 
We are adding new categories and subcategories to feedback flows to subscribers.
From settings -> feedback / settings -> subscriptions -> feedback: user is able to select new duck.ai category and subcategories.
Pixels and BE request are triggered at the end of the flow.
First apply subscription staging patch.
_No subscription_
_Settings feedback with Subscription_
_Subscription Settings feedback with Subscription_
_Feedback with Subscription (feature flag disabled)_

Add duck.ai categories to feedback

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/tabs/SearchTabFragment.kt
saved-sites/saved-sites-api/src/main/java/com/duckduckgo/savedsites/api/views/SavedSitesViewsProvider.kt
saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/newtab/FavouritesNewTabSectionView.kt
saved-sites/saved-sites-impl/src/main/res/layout/view_new_tab_favourites_section.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210771657899806?focus=true
This reverts commit cba06921f59efe724d1cb551c64e79c29bb604e6.

Don't show dax when favorites empty (Input Screen)

---

.github/workflows/update-content-scope.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210785772751175?focus=true
This PR enhances the automated content scope scripts update workflow by:
1. Clarifying when tests need to run:
- Tests will only run if the `node_modules/@duckduckgo/content-scope-scripts` folder content has changed
- If only the package version changed, tests don't need to run
2. Adding clearer PR checklist with two scenarios:
- When content-scope-scripts folder is updated: all tests and privacy tests must pass
- When only the package version is updated: all tests must pass but privacy tests can be skipped
3. Updating the Asana task description to include the same clarification about when tests need to run
_Workflow Changes_

Update content scope scripts workflow description

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/tabs/SearchTabFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/view/BottomBlurView.kt
duckchat/duckchat-impl/src/main/res/drawable/bottom_fade_overlay.xml
duckchat/duckchat-impl/src/main/res/layout/fragment_search_tab.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210740454247760?focus=true
- Blurs and fades the bottom of the autocomplete list on API 33+
- Falls back to just a gradient fade on < API 33
_On API 33+_
_On < API 33_

Blur bottom of Input Screen autocomplete

---

app/src/main/res/layout/view_new_omnibar.xml
app/src/main/res/layout/view_new_omnibar_bottom.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210803032371220?focus=true
Adds the missing `omnibarTextInputClickCatcher` to the old omnibars to stop the app crashing if the user is seeing these omnibar variants 
_Old top omnibar_
_Old bottom omnibar_
N/A

Add missing omnibarTextInputClickCatcher to "old" new_omnibars

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1210817225484607/f 
----- 

Update content scope scripts to version 10.13.0

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/viewmodel/InputScreenViewModel.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210716487258255?focus=true
- Suppresses the initial autocomplete request when user open the Input Screen if the input text is the current web page's URL.
- Updates the autocomplete request logic to not debounce the initial request. This helps speed up autocomplete results, for example, when user comes from SERP or from NTP. In these situations, they don't need to wait additional 300ms for us to request suggestions which visibly speeds up the interaction.

suppress autocomplete when Input Screen initially opened from a web page

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewActivity.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewActivityViewModel.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewViewModel.kt
duckchat/duckchat-impl/src/test/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewActivityViewModelTest.kt
duckchat/duckchat-impl/src/test/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewViewModelTest.kt
subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/Subscriptions.kt
subscriptions/subscriptions-dummy-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsDummy.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionsJSHelper.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealProductSubscriptionManagerTest.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/RealSubscriptionsJSHelperTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1149059203486286/task/1210671370392466?focus=true
Signals FE to refresh Duck.ai when subscription state changes
_Feature 1_

Refresh duck.ai when subscription state changes

---

app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/res/layout/activity_tab_switcher.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210728360131190?focus=true
This PR adds the bottom toolbar support, which displays the tab manager toolbar in a position set in the Appearance settings.

Tab manager update: Add a bottom toolbar position support

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherMenuExt.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
app/src/main/res/layout/activity_tab_switcher.xml
app/src/main/res/layout/popup_tabs_menu.xml
app/src/main/res/menu/menu_tab_switcher_activity.xml
app/src/main/res/menu/menu_tab_switcher_activity_with_selection.xml
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210543205190057?focus=true
This PR hides the FABs and replaces them with toolbar buttons (NTP, Duck.ai).
_Normal mode_
_Selection Mode_

Tab manager update: Replace FABs with buttons

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/tabs/SearchTabFragment.kt
duckchat/duckchat-impl/src/main/res/layout/fragment_search_tab.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210856945683405?focus=true
Adds new tab page content to the Input Screen's search mode.

add NTP to Input Screen

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1210875164740412/f 
----- 

Update content scope scripts to version 10.14.0

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1210885353817364/f 
----- 

Update content scope scripts to version 10.15.0

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/InBrowserImportPromo.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/InSettingsPasswordImportPromoRules.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/capability/ImportGooglePasswordsCapabilityChecker.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/promo/ImportInPasswordsVisibility.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillPasswordsManagementViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/importing/RealInBrowserImportPromoTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/importing/RealInSettingsPasswordImportPromoRulesTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/importing/capability/DefaultImportGooglePasswordsCapabilityCheckerTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/importing/promo/RealImportInPasswordsVisibilityTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsActivityScreenViewModelTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsViewModelTest.kt
autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210877903986238?focus=true 
Extracts the two checks we do against the `WebView` capabilities to ensure we can support importing Google passwords. Instead of every place which might interact with importing passwords having to know the nuances of which `WebView` APIs are needed, now they can just check against a single API.

Extract checks for if the WebView capabilities support importing Google passwords

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207418217763355/task/1210832415028455?focus=true
This PR adds a `from_focused_ntp` parameter that indicates, whether a pixel was triggered when an omnibar was focused on a NTP. The parameter is added to the following pixels:
- MENU_ACTION_POPUP_OPENED("m_nav_pm_o")
- FORGET_ALL_PRESSED_BROWSING("mf_bp")
- TAB_MANAGER_OPENED_FROM_NEW_TAB("m_tab_manager_open_from_newtabpage")
_Fire button_
_Tab switcher button_
_Menu button_
_Unfocused_
_Not in NTP_

Pixels: Measure omnibar clicks from NTP

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
duckchat/duckchat-api/src/main/java/com/duckduckgo/duckchat/api/inputscreen/InputScreenActivityParams.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenActivity.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenFragment.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210846340363977?focus=true
Cleans up the Input Screen's internal module references made outside of the implementation.

extract Input Screen's public API

---

app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/FragmentStateAdapter.java
app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/TabPagerAdapter.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/414730916066338/task/1210856603267238?focus=true
This PR implements a cleanup mechanism that checks if some tabs were removed and if they were, it cleans up fragments.

Fix: WebView not destroyed when tab closed

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/duckduckgo/app/dispatchers/IntentDispatcherActivity.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/414730916066338/task/1210860582231062?focus=true
This PR fixes an issue when using the "Web Search" context menu did not work sometimes.
Regression testing #1
Regression testing #2

Fix: Web Search not working reliably

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarEntryConverter.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/QueryUrlConverter.kt
app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/test/java/com/duckduckgo/app/browser/QueryUrlConverterTest.kt
browser-api/src/main/java/com/duckduckgo/app/browser/UriString.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210862419441744?focus=true
This PR adds support for extracting an URL from an externally shared text if it can find one. Typing some text that contains an URL in the search box treats it like a normal query, as before.
_External text containing a single URL_
_Search query_

Fix: Extract a single URL from an external shared text

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/command/SearchCommand.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/tabs/SearchTabFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/viewmodel/InputScreenViewModel.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210730276212926?focus=true
- Adds the ability to delete previously searched autocomplete entires (Scrolling back to last position will be handled in a follow-up PR).

Handle remove search suggestion from Input Screen autocomplete

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/state/SubmitButtonIconState.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/viewmodel/InputScreenViewModel.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210902983583192?focus=true
- Removes the globe icon when searching for a URL and replaces it with a right arrow.
- Also replaces the Duck.ai send button with a right arrow.

Update chat send and search URL icon to right arrow

---

node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
package-lock.json
package.json

Update content scope scripts to version 10.16.0

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/command/InputFieldCommand.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/state/InputBoxState.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/state/InputFieldState.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/view/InputModeWidget.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/viewmodel/InputScreenViewModel.kt
duckchat/duckchat-impl/src/main/res/layout/view_input_mode_switch_widget.xml
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210835160047735?focus=true
If the initial Input Screen content carried over from the omnibar is a URL, keep the Input Screen's text box a single line high unless clicked.
The idea is that the `EditText` is initialized as one line, which requires it to be scrollable horizontally. This means that operations on URL initiated by a long-click (context menus for copy/cut, and selection management) can be done within the horizontally scrolling box. This behavior exactly matches production omnibar.
However, as soon the input box is clicked, it expands to a maximum of 8 lines.
I also cleaned up unused now transition params.
Example:
https://github.com/user-attachments/assets/42ad7047-f26d-4db3-aa64-33c045051be0 …

keep input text box one line until interaction

---

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/AutofillFeature.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210879739526768?focus=true 
Updates default feature flag state to `enabled` instead of `internal` for showing import passwords option in app settings
- qa optional

Set default state to enabled for showing import password option in settings

---

app/build.gradle
pir/pir-api/build.gradle
pir/pir-api/src/main/java/com/duckduckgo/pir/api/PirFeature.kt
pir/pir-api/src/main/java/com/duckduckgo/pir/api/PirFeatureToggle.kt
pir/pir-api/src/main/java/com/duckduckgo/pir/api/dashboard/PirDashboardScreen.kt
pir/pir-impl/build.gradle
pir/pir-impl/lint-baseline.xml
pir/pir-impl/src/main/AndroidManifest.xml
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/PirRemoteFeatures.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/PirDashboardActivity.kt
pir/pir-impl/src/main/res/layout/activity_pir_dashboard.xml
pir/pir-impl/src/main/res/values/donottranslate.xml
pir/pir-internal/build.gradle
pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/brokers/PirDataUpdateObserver.kt
pir/readme.md
subscriptions/subscriptions-impl/build.gradle
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingView.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingViewModel.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/settings/views/PirSettingViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210856899271207?focus=true
Creates new `pir-impl` and `pir-api` modules and adds a new empty PIR dashboard activity that is opened from the existing PIR entry point when FF enabled.
Removing testing IDs, moving `PirDataUpdateObserver` and canceling already scheduled jobs will be done in later PRs to keep it easier to review.
https://app.asana.com/1/137249556945/task/1210885772041360?focus=true

PIR: Create PIR modules and new entry point

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/view/InputModeWidget.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210902938749438?focus=true
- When Input Screen launched with URL, the action button should have a right arrow icon.

Search icon should be a right arrow when opened with URL (Input Screen)

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/state/AutoCompleteScrollState.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/tabs/SearchTabFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/viewmodel/InputScreenViewModel.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210893251369089?focus=true
- Scrolls back to the same position in the autocomplete list after deleting an item.
This should also be the same if you dismiss/cancel the dialog.

Scroll to last position when deleting autocomplete entry (Input Screen)

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1210911991307391/f 
----- 

Update content scope scripts to version 10.17.0

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/SubscriptionsHandler.kt
subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/SubscriptionScreens.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1149059203486286/task/1210891403305047?focus=true
Includes featurePage in url when capturing subscription navigation from duckai chat. 
Use filter in logcat `message~:"Subscription Flow:"`
_Feature 1_

Include FeaturePage when navigating from Duckai to subscription flow

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/SubscriptionsHandler.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/SubscriptionsHandlerTest.kt
subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/SubscriptionScreens.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsConstants.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1149059203486286/task/1210858657604808?focus=true
Capture feature page query param when redirecting to subscription flows
_Feature 1_

capture featurepage when redirecting to subscription flows

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/feature/DuckChatFeature.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/subscription/DuckAiPlusSettingsViewModel.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/subscription/DuckAiPlusSettingsViewModelTest.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingView.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/settings/views/ProSettingViewModel.kt
subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1149059203486286/task/1210908317304409?focus=true 
Replace duckai FF by relying on subscription ff and filtering entitlements
_Feature 1_
_Feature 2_

Replace duckai ff by filtering subscription entitlements

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1210939806484672?focus=true
- Fixes the "Disable Duck.ai" button on the Duck.ai onboarding screen.

Fix disable Duck.ai in Duck.ai onboarding

---

node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1210945464995929/f 
----- 

Update content scope scripts to version 11.2.0

---

duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerFeature.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerFeatureRepository.kt
duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
duckplayer/duckplayer-impl/src/test/kotlin/com/duckduckgo/duckplayer/impl/RealDuckPlayerTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210811808963690?focus=true 
Set referer header to local assets directory in compliance with new TOS
_Feature 1_
n/a

Add referer header for Duck Player

---

app/src/main/java/com/duckduckgo/app/onboarding/ui/page/BbWelcomePage.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/BuckWelcomePage.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
app/src/main/res/layout/content_onboarding_welcome_page_buck.xml
common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/StringExtensions.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207908166761516/task/1210943043006448?focus=true
Fixes
- Orphaned "Bar" word on omnibar top or bottom picker screen
- Title on "Welcome Screen" wrapping to next line via autosizing the title
_Welcome Screen title sizing_
_Address bar orphaning_

Fix Onboarding Experiment nice-to-haves 

---

app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherAdapter.kt
app/src/main/res/layout/item_tab_grid_new.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210935007420667?focus=true
Removes nested `MaterialCardView` that was used only to apply rounded corners to the image. Now, we're using glide transformation instead.
Verify that tab switcher previews look exactly the same before and after the change.

remove nested material cards in tab switcher adapter

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/internal/SubscriptionsUrlProvider.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210974305229051?focus=true
The subscription activation URL had an extra `/subscriptions/` in the URL causing a loop where you can't activate the subscription
_Feature 1_

Fix subscription activation url

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/PasswordStoreEventListener.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/engagement/EngagementPasswordAddedListener.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSync.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/engagement/EngagementPasswordAddedListenerTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210974473587922?focus=true 
- We have a `PasswordStoreEventListener` plugin which allows other code to be notified when a password has been saved
- This is called for individual password saves, but bulk insertions doesn't trigger it
Suggested logcat filter: `m_autofill_onboardeduser`

Ensure bulk saves also trigger the password saved listeners

---

app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageView.kt
app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabPageProvider.kt
app/src/test/java/com/duckduckgo/app/browser/newtab/NewTabPageProviderTest.kt
new-tab-page/new-tab-page-api/src/main/java/com/duckduckgo/newtabpage/api/NewTabPagePlugin.kt
new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/NewTabPage.kt
new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/view/NewTabPageView.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1210986747757521?focus=true
- Adds an optional `showLogo` param to hide the logo from NTP.

Add showLogo param to NTP

---

app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageView.kt
app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabPageProvider.kt
app/src/test/java/com/duckduckgo/app/browser/newtab/NewTabPageProviderTest.kt
new-tab-page/new-tab-page-api/src/main/java/com/duckduckgo/newtabpage/api/NewTabPagePlugin.kt
new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/NewTabPage.kt
new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/view/NewTabPageView.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210986747757664?focus=true
- Adds an optional `hasContent` callback to `NewTabPageView` in order to notify of content to the Input Screen.

Add hasContent param to NTP

---

app/src/main/java/com/duckduckgo/app/fire/AppCacheClearer.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionFeaturesFetcher.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/services/SubscriptionNetworkModule.kt
subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/services/SubscriptionsCachedService.kt
subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/SubscriptionFeaturesFetcherTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210997377644545?focus=true 
Adds cache support to subscription feature endpoints.
It uses custom one to avoid being affected by other network requests and have a better cache hit rate.
Also adds the file as fire button exception, same we do for the other api requests
_Feature 1_

Use http client with cache support on subscriptions feature endpoint

---

.github/workflows/release_nightly.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/608920331025315/task/1211012979872021?focus=true 
The internal builds GHA workflow is using `gradle` instead of the gradle wrapper `gradlew`
- This means it might use a different version of gradle than we expect to use
- This just started happening; this job failed because it picked up Gradle 9 and had issues using it while the rest of the CI jobs use Grade 8

Ensure gradle wrapper is used in internal builds

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1210763884565991?focus=true
- Handles URI_INTENT_SCHEME and opens the market place using the package name if a link not present in the fallback. 
_Feature flag disabled_

Handle URI_INTENT_SCHEME scheme and open market place when no fallback

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211022417452920?focus=true 
After downloading a file we have a callback which shows a snackbar; there is button on it to open the file. From a stack trace it seems possible the activity is gone and the use of `requireActivity()` results in a crash. Switching to avoiding the crash and doing nothing if the `activity` is null when we try.
Fixes https://github.com/duckduckgo/Android/issues/6557

Avoid usage of requireActivity in download callback

---

common/common-ui/src/main/java/com/duckduckgo/common/ui/experiments/visual/ExperimentalThemingFeature.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1211021941669104?focus=true
- Sets the `singleOmnibarFeature` to true by default.

Enable singleOmnibarFeature by default

---

app/src/main/java/com/duckduckgo/app/di/NetworkModule.kt
app/src/main/java/com/duckduckgo/app/feedback/api/FeedbackSubmitter.kt
app/src/main/java/com/duckduckgo/app/onboardingdesignexperiment/OnboardingDesignExperimentManager.kt
app/src/test/java/com/duckduckgo/app/settings/clear/OnboardingExperimentFireAnimationHelperTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210930516193739?focus=true 
This PR adds the onboarding experiment cohort as part of the atb when sending feedback

Send experiment cohorts in feedback form

---

downloads/downloads-impl/build.gradle
downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DownloadFileService.kt
downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/UrlFileDownloader.kt
downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/feature/FileDownloadFeature.kt
downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/UrlFileDownloaderTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211033344698349?focus=true 
From https://github.com/duckduckgo/Android/issues/6516, investigated and found that empty `Cookie` HTTP headers are tripping up Calibre's web server. 
- Empty `Cookie` headers are legal but there are some sparse reports of web servers failing to parse them
- Rather than an empty `Cookie` header, we can just omit sending it at all
That fixes the problem for Calibre (and i'm sure a few other services). Fixes https://github.com/duckduckgo/Android/issues/6516.
Feature flagged so we can revert to the existing behaviour if we notice problems because of this change.

Omit Cookie downloads header when empty rather than empty string

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsViewModel.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211021941669121?focus=true
- Moves settings pixels from `RealDuckChat` to `DuckChatSettingsViewModel`

Move Duck.ai settings pixels to ViewModel

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211057743083072
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v14.13.0
Updates Autoconsent to version [v14.13.0](https://github.com/duckduckgo/autoconsent/releases/tag/v14.13.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v14.13.0/CHANGELOG.md)
This release has been tested during Autoconsent development. You can check the release notes for more information.
1. Make sure that there's no unexpected failures in CI checks
2. (optional) smoke test some of the sites mentioned in the release notes
3. If there are problems, reach out to a CPM DRI

Update autoconsent to v14.13.0

---

app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1211066471579596?focus=true
This PR changes the pixel sent when the Duck.ai toolbar button is clicked to `aichat_open_tab_switcher_fab`.

Fix: Use the previous pixel to measure Duck.ai discovery in tab switcher

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1211056807546917?focus=true
With this PR, whenever a New Tab Page is opened, the Input Screen will be launched automatically.
Implementing this had some challenges given how complex and fragile the keyboard management implementation is.
I couldn't rely on the `BrowserTabFragment#onViewVisible`, which is currently used to auto-focus on the omnibar, because that's getting called whenever the fragment is resumed. So, if the logic to open the Input Screen was part of this function, closing the Input Screen (which is a separate activity) would resume the fragment and open the Input Screen again, resulting in a loop.
Instead, I added the logic to observe whenever the tab changes and dispatch a command to launch …

automatically launch the Input Screen when New Tab Page opened

---

app/src/androidTest/java/com/duckduckgo/widget/SearchAndFavoritesGridCalculatorKtTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/duckduckgo/widget/DuckAiSearchWidgetUpdaterReceiver.kt
app/src/main/java/com/duckduckgo/widget/SearchWidget.kt
app/src/main/java/com/duckduckgo/widget/SearchWidgetConfigurator.kt
app/src/main/res/drawable/ic_duck_ai_24_dark.xml
app/src/main/res/drawable/ic_duck_ai_24_light.xml
app/src/main/res/drawable/ic_vertical_separator_dark.xml
app/src/main/res/drawable/ic_vertical_separator_light.xml
app/src/main/res/drawable/search_widget_background_black.xml
app/src/main/res/drawable/search_widget_background_white.xml
app/src/main/res/layout/search_widget_dark.xml
app/src/main/res/layout/search_widget_light.xml
app/src/main/res/xml/search_widget_info_light.xml
common/common-ui/src/main/res/drawable/ic_find_search_24_dark.xml
common/common-ui/src/main/res/drawable/ic_find_search_24_light.xml
common/common-ui/src/main/res/values/design-system-dimensions.xml
common/common-ui/src/main/res/values/widgets.xml
duckchat/duckchat-api/src/main/java/com/duckduckgo/duckchat/api/DuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/repository/DuckChatFeatureRepository.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsActivity.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/repository/DuckChatFeatureRepositoryTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/276630244458377/task/1210378258410691?focus=true
This PR updates the search widget to include Duck.ai functionality by:
- Adding a new Duck.ai icon to the search widget
- Replacing RelativeLayout with LinearLayout for better control of widget elements
- Creating a SearchWidgetConfigurator to handle widget configuration based on feature availability
- Adding a vertical separator between voice search and Duck.ai icons
- Implementing a broadcast receiver to update widgets when Duck.ai becomes available
- Increasing corner radius for the widget background for a more modern look
- Updating the search icon to a 24dp version for better visual consistency
- Adjusting padding and layout dimensions for improved appearance
_Widget UI …

[Implementation] Widget 1: Search + Duck.ai

---

app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
duckchat/duckchat-api/src/main/java/com/duckduckgo/duckchat/api/DuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/helper/DuckChatJSHelper.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/helper/RealDuckChatJSHelperTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1211088838900418?focus=true
- Modifies `DuckChat.isEnabled` to check the config flag and user pref.
_Sanity check_

Update DuckChat.isEnabled to check config flag and user pref

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1211082171468041?focus=true
Moved the `launchDownloadMessagesJob()` call from the ViewModel creation to the `onActivityCreated` lifecycle method in `BrowserTabFragment`. This removes the self-reference from BrowserTabFragment#viewModel init.
_ViewModel init lazy block called once_
`logcat { "BrowserTabViewModel lazy block -- ${System.identityHashCode(viewModel)}" }`
_Download Messages_

Remove self-reference from BrowserTabFragment#viewModel init

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/BbWelcomePage.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207908166761516/task/1211042630873651?focus=true
This PR fixes several animation issues in the onboarding experience:
1. Added proper handling for hiding the Buck magnifying glass animation when showing DaxIntroSearchOptionsCta
2. Fixed the BB shield animating up as the text animation starts playing
3. Fixed a bug where click listeners were being set before animations completed
_BB Fixes_
_Buck Fixes_
N/A

Onboarding Design Experiment: Final fixes

---

.github/workflows/ci.yml
.github/workflows/external-ref-tests.yml
.github/workflows/nightly.yml
gradle.properties

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207908166761516/task/1211090750035753?focus=true
Enable Gradle configuration cache by adding `org.gradle.configuration-cache=true` to gradle.properties. This optimization will speed up build times by caching the configuration phase of the build process.
_Build Performance_
No UI changes in this PR.

Enable Gradle configuration cache

---

app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageView.kt
app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModelTest.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/tabs/SearchTabFragment.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1211046517836482?focus=true
Fixes the NTP's `hasContent` callback to also report content when only AppTP is enabled (no RMF, favorites, etc). This in turn fixes the Input Screen and makes it display AppTP banners.
I also moved the logic that determined whether the Dax logo and other content should be shown on NTP into the ViewModel, so that it can be unit tested.
```diff
diff --git a/remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/network/RemoteMessagingService.kt b/remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/network/RemoteMessagingService.kt
index 7c0e619ba4..cd65aa542d 100644
--- …
```

Show AppTP on the Input Screen

---

app/src/internal/java/com/duckduckgo/app/dev/settings/tabs/DevTabsActivity.kt
app/src/internal/java/com/duckduckgo/app/dev/settings/tabs/DevTabsViewModel.kt
app/src/internal/res/layout/activity_dev_tabs.xml
app/src/internal/res/values/donottranslate.xml
duckchat/duckchat-impl/src/main/res/layout/fragment_search_tab.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1210986778088959?focus=true
Fixes an issue where the AppTP banner wouldn't scroll on the Input Screen until bounds of the scrolling container where reached.
Also adds a dev tool to create/clear favorites and improves the existing one that adds bookmarks so that it doesn't generate duplicates.
- You can use a new option to generate favorites under Settings -> Developer Settings -> Tabs and Saved Sites
_Before_
https://github.com/user-attachments/assets/701b81e1-7476-46b7-a19b-e2c08e45737c
_After_
https://github.com/user-attachments/assets/a87c5e10-fda2-4aa5-94ce-4a7aed558c1d

Fix AppTP scrolling behavior on the Input Screen

---

.github/workflows/release_nightly.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211121590401637?focus=true 
our ` getBuildVersionName` gradle task is trying to call `buildVersionName()` which is defined in the `ext` block, but configuration cache doesn't allow tasks to access project extensions during execution phase.
This PR changes the nightly job which uses that task to pass `--no-configuration-cache` to bypass it.
- QA optional
- [Optional] you can check that while the existing 
- `./gradlew getBuildVersionName -PversionNameSuffix=-nightly -PlatestTag=5.245.0.1-nightly` fails, 
- `./gradlew --no-configuration-cache getBuildVersionName -PversionNameSuffix=-nightly -PlatestTag=5.245.0.1-nightly` succeeds

Fix nightly builds to ensure they get the version number correctly

---

.github/actionlint.yaml
.github/workflows/ci.yml
.github/workflows/external-css-tests.yml
.github/workflows/external-ref-tests.yml
.github/workflows/nightly.yml
.github/workflows/privacy.yml
.github/workflows/validate_workflows.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1210856879005136?focus=true
Fixes actionlint warnings
- `android-large-runner` is a valid runner
- Fix useless cat warning
- Fix potential globbing of $Flank
N/A

Fix actionlint warnings

---

saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/newtab/FavoritesSwipeHandling.kt
saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/newtab/FavouritesNewTabSectionView.kt
saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/newtab/FavouritesNewTabSectionViewModel.kt
saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/newtab/FavouritesNewTabSectionViewModelTests.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210986778088960?focus=true
- Enables swiping on favorites on the Input Screen.
_Feature flag disabled_

Enable swiping on favorites

---

pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/PirConstants.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/PirDashboardWebViewActivity.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/di/PirModule.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/notifications/PirNotificationManager.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/optout/PirForegroundOptOutService.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/scan/PirForegroundScanService.kt
pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirDevOptOutActivity.kt
pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirDevScanActivity.kt
pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/settings/PirDevSettingsActivity.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211055607216972?focus=true
Moves creation of notification channel to dashboard activity instead of dev settings activity.
https://app.asana.com/1/137249556945/project/488551667048375/task/1211110897738706?focus=true
No UI changes

PIR: Move notification channel creation to PirDashboardWebViewActivity

---

node_modules/@duckduckgo/content-scope-scripts/build/android/adsjsContentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
package-lock.json
package.json

Update content scope scripts to version 11.8.0

---

app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoRequestRewriter.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
app/src/test/java/com/duckduckgo/app/browser/DuckDuckGoRequestRewriterTest.kt
app/src/test/java/com/duckduckgo/app/browser/QueryUrlConverterTest.kt
common/common-utils/src/main/java/com/duckduckgo/common/utils/AppUrl.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1209671977594486/task/1211122605729914?focus=true
Respect duck.ai setting in SERP
_Test_

Respect SERP duck.ai setting

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/InputScreenFragment.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/state/InputScreenVisibilityState.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/viewmodel/InputScreenViewModel.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/inputscreen/InputScreenViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211147839324405?focus=true
- Removes the new line button from the search input mode.

Hide new line button in Search Input Mode

---

pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirMessageHandlerUtils.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebAddAddressToCurrentUserProfileMessageHandlerTest.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebAddNameToCurrentUserProfileMessageHandlerTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211134926977200?focus=true
Adds tests for `PirWebAddAddressToCurrentUserProfileMessageHandler` and `PirWebAddNameToCurrentUserProfileMessageHandler`.
It's necessary to run them with `AndroidJUnit4` runner as we need access to `JSONObject`.
Run unit tests in `PirWebAddAddressToCurrentUserProfileMessageHandler` and `PirWebAddNameToCurrentUserProfileMessageHandler`
No UI changes

PIR: Add tests for AddAddress and AddName message handlers

---

pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebGetCurrentUserProfileMessageHandlerTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211137752462443?focus=true
Adds unit tests for `PirWebGetCurrentUserProfileMessageHandler`
Run unit tests in `PirWebGetCurrentUserProfileMessageHandlerTest`
No UI changes

PIR: Add tests for GetCurrentUserProfile message handler

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/SingleOmnibarLayout.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/414730916066338/task/1211147614566539?focus=true
Fixes an issue where the whole omnibar container was hidden in Custom Tab mode, which also made the Find In Page layout inaccessible.
Side note - I think the Find In Page feature state might need an update given all the workarounds that were incorporated throughout the omnibars experiments iterations. Now that we're cleaning it up in https://github.com/duckduckgo/Android/pull/6658, the next step could be cleaning up the Find In Page impl as well.

fix an issue where Find In Page didn't show in Custom Tabs

---

app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageView.kt
app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModelTest.kt
new-tab-page/new-tab-page-api/src/main/java/com/duckduckgo/newtabpage/api/NewTabPagePlugin.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1211121230931120?focus=true
Changes the NTP logic to not display Dax logo until favorites are loaded, and then only show the logo if favorites are empty.

do not display Dax logo if favorites are loading

---

node_modules/@duckduckgo/content-scope-scripts/build/android/adsjsContentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Update content scope scripts to version 11.12.0

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/viewmodel/InputScreenViewModel.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1211163531745283?focus=true
Decreases Input Screen's autocomplete debounce to 100 ms
QA optional. If you can, verify autocomplete works as expected while on the Input Screen.

decrease Input Screen's autocomplete debounce to 100 ms

---

duckchat/duckchat-impl/src/main/res/layout/view_input_mode_switch_widget.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671518894266/task/1211196787859247?focus=true
Fixes a regression from https://github.com/duckduckgo/Android/pull/6686 where the input box would be prohibited from expanding when new lines were added in Chat Mode.

fix an issue where creating a new line in Chat Mode wouldn't expand the input box

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
app/src/main/java/com/duckduckgo/app/browser/webshare/WebViewCompatWebShareChooser.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsWebMessagingPlugin.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/DebugFlagGlobalHandler.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/GlobalContentScopeJsMessageHandlersPlugin.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsWebMessagingPluginTest.kt
js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/WebMessagingPlugin.kt
js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/WebViewCompatMessaging.kt
web-compat/web-compat-impl/src/main/java/com/duckduckgo/webcompat/impl/messaging/webviewcompat/WebViewCompatWebCompatContentScopeJsMessageHandler.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205008441501016/task/1211080061667204?focus=true
**Pre-requisites**
_Feature enabled_
n/a

Support message responses

---

duckchat/duckchat-impl/src/main/res/layout/fragment_input_screen.xml
duckchat/duckchat-impl/src/main/res/layout/fragment_search_tab.xml
duckchat/duckchat-impl/src/main/res/layout/view_input_mode_switch_widget.xml
duckchat/duckchat-impl/src/main/res/values/dimens.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1211224065958257?focus=true
- Fixes an issue where the autocomplete list is clipped and the top padding is too large.
- Adds `12dp` top padding/margin to the logo/NTP content to remove the jump on transition.

Fix regression to autocomplete top padding (Input Screen)

---

pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebInitialScanStatusMessageHandler.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/model/PirWebMessageResponse.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebInitialScanStatusMessageHandlerTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203581873609357/task/1211255677689944?focus=true
Fixes an issue with initial scan response at the start of onboarding that caused a "Back to Dashboard" button to show at the final step of onboarding.
See https://app.asana.com/1/137249556945/project/1203581873609357/task/1211255677689959?focus=true for instructions
See task

PIR: Fix dashboard button showing on onboarding

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/ui/view/InputModeWidget.kt
duckchat/duckchat-impl/src/main/res/drawable/input_mode_widget_background_gradient.xml
duckchat/duckchat-impl/src/main/res/layout/fragment_input_screen.xml
duckchat/duckchat-impl/src/main/res/layout/view_input_mode_switch_widget.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1211244094853968?focus=true
- Fixes an issue where content is visible behind the input when scrolling under certain scenarios.

Set background of Input Mode Widget

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/715106103902962/task/1211257529601162?focus=true
This fixes a bug when the voice search button would not show up if full URL was disabled.

Fix: Voice search button not displayed when short URL configured

---

node_modules/@duckduckgo/content-scope-scripts/build/android/adsjsContentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Update content scope scripts to version 11.16.0

---

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/ui/SubscriptionsWebViewActivity.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211073283656160?focus=true 
This PR changes the way navigating back works letting the FE decide in some cases when it can and cannot happen

Subscription webview go back action

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/duckduckgo/widget/DuckAiPinShortcutActivity.kt
app/src/main/res/values/donottranslate.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211289267231652?focus=true
Added the ability to create a Duck.ai shortcut on the home screen directly from the widget picker. This implementation includes a new transparent activity `DuckAiPinShortcutActivity` that handles shortcut creation requests and registers the shortcut with the system.
_Duck.ai Shortcut Creation_
Check screenshots attached on task URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211289267231652?focus=true

Duck.ai: Use a shortcut that is added from the widget picker

---

package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1211310673449977/f 
----- 

Update content scope scripts to version 11.19.0

---

package-lock.json
package.json

Update content scope scripts to version 11.25.0

---

saved-sites/saved-sites-impl/src/main/res/menu/bookmark_popup_menu.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/414730916066338/task/1211322673312843?focus=true
Previously, we are using newTabPageMenuEdit which is in donottranslate.xml.
I don't think we should use a non translated screen here if everything else on the page is translated.
|(<img width="349" height="132" alt="Screenshot 2025-09-15 at 10 57 36" src="https://github.com/user-attachments/assets/2b046a0b-d33d-446d-a508-d3afb2521fcd" />)|(<img width="360" height="173" alt="Screenshot 2025-09-15 at 10 57 43" src="https://github.com/user-attachments/assets/01a00aea-1a77-4816-a045-1f51f6b1f38c" />)|

Use translated string for edit text

---

app/src/main/java/com/duckduckgo/app/browser/newaddressbaroption/NewAddressBarOptionManager.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingViewModel.kt
app/src/test/java/com/duckduckgo/app/browser/newaddressbaroption/NewAddressBarOptionManagerTest.kt
app/src/test/java/com/duckduckgo/app/onboarding/ui/OnboardingViewModelTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200204095367872/task/1211370918087169?focus=true
- Skips the new address bar option when skipping onboarding

Skip new address bar option when onboarding is skipped

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202552961248957/task/1206535923706701?focus=true
Work around platform bug ([b/229000935](https://issuetracker.google.com/issues/229000935)) where startForegroundService() for
VpnService can throw ForegroundServiceStartNotAllowedException when called
from background. We now catch this and fall back to startService(), which
is allowed for VPNs. Service still promotes itself to foreground as usual.
Smoke test AppTP and VPN on off scenarios for Android on 31+ and below 31

Add fallback for ForegroundServiceStartNotAllowedException in Android 31+

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsPostMessageWrapperPlugin.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsPostMessageWrapperPluginTest.kt
js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/PostMessageWrapperPlugin.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211382186881405?focus=true
Fallback for subscriptions when new APIs not enabled was failing due to injecting different instances in the fragment and the messaging wrapper, so WebView was not initialized and messages were never sent
_Feature 1_

Fix fallback subscriptions

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/newaddressbaroption/NewAddressBarOptionBottomSheetDialog.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/newaddressbaroption/NewAddressBarOptionBottomSheetDialogFactory.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/pixel/DuckChatPixels.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211358524399131?focus=true
- Adds pixels to the new address bar option choice screen
_Search & Duck.ai_
_Search_
_Search_

New address bar option choice screen pixels

---

saved-sites/saved-sites-impl/src/main/res/layout/dialog_fragment_saved_site.xml

Task/Issue URL: https://app.asana.com/1/137249556945/project/414730916066338/task/1211370193812374?focus=true
Makes edit bookmark screen scrollable.
Note: NesterScrollView have issues with DialogFragment so I opted to use ScrollView which seem to work better
_Bookmark with long url (ebay for example)_
_Bookmark with short url (ddg for example)_
Some videos of my testing:
https://github.com/user-attachments/assets/3f2f106e-ec3a-419c-8dac-60efa7c9cb0d
https://github.com/user-attachments/assets/82473146-023b-4de0-a45e-93a425b6958e
https://github.com/user-attachments/assets/ff390b55-26da-456d-af88-a3af84e2611b

Make bookmark edit screen scrollable

---

duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/feature/DuckChatFeature.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/inputscreen/newaddressbaroption/NewAddressBarOptionBottomSheetDialog.kt
duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/pixel/DuckChatPixels.kt
duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211427333122830?focus=true
- Adds a pixel if the New Address Bar Option dialog is cancelled (i.e. by swiping or hardware back)

Add New Address Bar Option cancelled pixel

---

privacy-config/privacy-config-impl/src/main/res/raw/privacy_config.json

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211213870765252?focus=true
Removed the `onboardingDesignExperiment` feature from the privacy configuration. This experiment with three cohorts (modifiedControl, bb, and buck) is no longer needed in the privacy config.
_Verify experiment removal_
No UI changes as this is a configuration update that removes an expired experiment.

Disable onboarding design experiment in privacy configuration

---

node_modules/@duckduckgo/content-scope-scripts/build/android/adsjsContentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1211484160461076/f 
----- 

Update content scope scripts to version 11.29.0

---

node_modules/@duckduckgo/content-scope-scripts/build/android/adsjsContentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Update content scope scripts to version 11.30.0

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211370636939092?focus=true
- Hides the keyboard in the unfocussed state when the Input Screen is enabled.
_Input Screen enabled_
_Input Screen disabled_

Hide keyboard in unfocussed state when Input Screen enabled

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt
app/src/main/java/com/duckduckgo/app/browser/RealWebViewCapabilityChecker.kt
app/src/main/java/com/duckduckgo/app/browser/RealWebViewCompatWrapper.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
app/src/test/java/com/duckduckgo/app/browser/RealWebViewCompatWrapperTest.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/blob/ImportGooglePasswordBlobConsumer.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/blob/WebViewBlobDownloader.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/importing/gpm/webflow/ImportGooglePasswordsWebFlowFragment.kt
browser-api/src/main/java/com/duckduckgo/browser/api/webviewcompat/WebViewCompatWrapper.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/ContentScopeScriptsAddDocumentStartJavaScriptPlugin.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/features/contentscopeexperiments/RealContentScopeExperiments.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsPostMessageWrapperPlugin.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsWebMessagingPlugin.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/ContentScopeScriptsAddDocumentStartJavaScriptPluginTest.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsPostMessageWrapperPluginTest.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsWebMessagingPluginTest.kt
js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/AddDocumentStartJavaScriptPlugin.kt
js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/WebMessagingPlugin.kt
js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/WebViewCompatMessaging.kt
lint-rules/src/main/java/com/duckduckgo/lint/WebViewCompatApisUsageDetector.kt
privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeatureName.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211506668810055?focus=true
* Check WebView attached before calling `WebViewCompat` and `postMessage` methods
* Check coroutine active before calling `WebViewCompat` and `postMessage` methods
* Launch WebViewCompat` and `postMessage` methods with `lifecycleScope` or `viewModelScope` whenever possible
_Feature 1_
_Message replies_ 
n/a

Apply lifecycle checks and fixes to addDocumentStartJavaScript

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1211450043710855?focus=true
Added support for better handling app links in custom tabs. When an app link is opened in a custom tab, the app will now directly open the app link without showing the app link prompt, regardless of the user's app link prompt settings.
_App Links in Custom Tabs_
_Regular App Links_
No UI changes, only behavior changes in Custom Tab for app links.

Implement custom tab handling for app links in BrowserTabViewModel.

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/menu/BrowserPopupMenu.kt
app/src/main/java/com/duckduckgo/app/browser/menu/VpnMenuStateProvider.kt
app/src/main/java/com/duckduckgo/app/browser/viewstate/BrowserViewState.kt
app/src/test/java/com/duckduckgo/app/browser/BrowserTabViewModelVpnMenuTest.kt
app/src/test/java/com/duckduckgo/app/browser/menu/BrowserPopupMenuVpnTest.kt
app/src/test/java/com/duckduckgo/app/browser/menu/VpnMenuStateProviderTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211443366455926?focus=true
Adjust VPN menu item dismiss behavior
_Pre-steps_
_Not Subscribed_
_Frequency cap_
_no UK_

Adjust VPN menu item dismiss behavior

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/ContentScopeScriptsAddDocumentStartJavaScriptPlugin.kt
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsPostMessageWrapperPlugin.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/ContentScopeScriptsPostMessageWrapperPluginTest.kt
js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/AddDocumentStartJavaScriptPlugin.kt
js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/PostMessageWrapperPlugin.kt

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211506668810056?focus=true
* Add RC flag to support only removing/adding script when protection status changes, not every time page load finishes
_Pre-requisites_
_Feature 1_
_Flag disabled_
n/a

FF not removing/adding script on page finished, only protection status changes

---

node_modules/@duckduckgo/content-scope-scripts/build/android/adsjsContentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Update content scope scripts to version 11.32.0

---

pir/pir-impl/schemas/com.duckduckgo.pir.impl.store.PirDatabase/11.json
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebAddAddressToCurrentUserProfileMessageHandler.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebAddNameToCurrentUserProfileMessageHandler.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebGetCurrentUserProfileMessageHandler.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebRemoveAddressAtIndexFromCurrentUserProfileMessageHandler.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebRemoveNameAtIndexFromCurrentUserProfileMessageHandler.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebSaveProfileMessageHandler.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebSetAddressAtIndexInCurrentUserProfileMessageHandler.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebSetBirthYearForCurrentUserProfile.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebSetNameAtIndexInCurrentUserProfileMessageHandler.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/dashboard/state/PirWebProfileStateHolder.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/PirDatabase.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/PirRepository.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/db/UserProfileDao.kt
pir/pir-impl/src/main/java/com/duckduckgo/pir/impl/store/db/UserProfileEntities.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebAddAddressToCurrentUserProfileMessageHandlerTest.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebAddNameToCurrentUserProfileMessageHandlerTest.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebGetCurrentUserProfileMessageHandlerTest.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebRemoveAddressAtIndexFromCurrentUserProfileMessageHandlerTest.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebRemoveNameAtIndexFromCurrentUserProfileMessageHandlerTest.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebSaveProfileMessageHandlerTest.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebSetAddressAtIndexInCurrentUserProfileMessageHandlerTest.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebSetBirthYearForCurrentUserProfileTest.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/messaging/handlers/PirWebSetNameAtIndexInCurrentUserProfileMessageHandlerTest.kt
pir/pir-impl/src/test/java/com/duckduckgo/pir/impl/dashboard/state/RealPirWebProfileStateHolderTest.kt

Task/Issue URL: https://app.asana.com/1/137249556945/project/488551667048375/task/1210822763676213?focus=true
Adds support for storing, deleting and updating profiles as a result of profile edit.
Note: handling scan/opt-out jobs will be done in next PRs, this only contains the profile storing logic
There are three commits:
- First one is renaming only - no actual code changes
- Second one has the changes needed to support the storing logic
- Third one updates tests
https://app.asana.com/1/137249556945/task/1211524792263651?focus=true
No UI changes

PIR: Add support for storing edited profiles

---

node_modules/@duckduckgo/content-scope-scripts/build/android/adsjsContentScope.js
node_modules/@duckduckgo/content-scope-scripts/build/android/autofillImport.js
node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1211583450630234/f 
----- 

Update content scope scripts to version 11.33.0
