duckduckgo/Android

app/src/main/AndroidManifest.xml
app/src/release/AndroidManifest.xml

Asana Issue URL: n/a
Noticed that the tools were (rightly) complaining about the definition of the crash reporting activity for DEBUG builds; it is only defined as a `RELEASE` dependency.
This PR moves the definition into a separate RELEASE-only manifest which is merged in during RELEASE builds.
1. Set build variant to `debug`
1. Open the `AndroidManifest.xml`
1. Ensure in the `merged manifest` tab, you **don't** see the ACRA activity
1. Set build variant to `release`
1. Open the `AndroidManifest.xml`
1. Ensure in the `merged manifest` tab, you **do** see the ACRA activity

Move ACRA activity definition to release variant only

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Asana Issue URL: https://app.asana.com/0/471012189846020/490474714901190
Attempt at making the back animation nicer by explicitly dismissing the keyboard sooner.
1. From landing page, goto search view
1. When the keyboard is showing, hit the back button to dismiss the keyboard
1. See if the animation is nice

Add earlier attempt to dismiss keyboard to make activity transition nice

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/KeyboardAwareEditText.kt

Asana Issue URL: https://app.asana.com/0/488551667048375/498315314295393
Previously when long pressing text in the omnibar a crash occurred. 
1. Navigate to a webpage
1. Once it has finished loading, long press on the text in the omnibar. Be sure to long press the text itself, not just the text field.
1. The app should no longer crash

Fix crash when long pressing omnibar text

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Asana Issue URL: https://app.asana.com/0/488551667048375/495254191196640
Loads webpages in overview mode, fixing issues where pages were initially too zoomed in and only partially rendered on screen
1. Open http://falkirkrpg.org.uk
1. Ensure that page fits nicely on screen and no scrolling is needed to see it unless page is intentionally zoomed in

Webview scaling

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Asana Issue URL: https://app.asana.com/0/488551667048375/497618874776656
Previously a user needed to tap the done button to submit a query. Pressing enter on a keyboard (as may happen when debugging on an emulator) did not work
1. Run the app on an emulator
1. Enter a search term in the omnibar
1. Press the computer's keyboard "enter" key to submit the query

Allow omnibar queries to be submitted with the "enter" key

---

app/src/main/java/com/duckduckgo/app/trackerdetection/model/TrackerNetworks.kt

https://app.asana.com/0/inbox/361428290920650/504059114070396/503772744089477
Updates the maxcdn major tracker network entry (which currently does nothing) to stackpath to match upcoming changes to the disconnect list
We are still waiting on the server change for this. You can test it by pointing to my version of the json file. In TrackerListService.kt change the disconnect url entry to
`@GET("https://raw.githubusercontent.com/subsymbolic/disconnect-tracking-protection/f91c29eece76d889cfee9b2e2aaaae4f77f5b91a/services.json")`
1. Visit http://www.truthorfiction.com
1. Open the privacy dashboard
1. Note that there are now two major networks

Update maxcdn to stackpath

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacymonitor/PrivacyMonitorGradeExtensionTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacymonitor/ui/PrivacyDashboardViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/privacymonitor/ui/PrivacyDashboardViewModel.kt
app/src/main/java/com/duckduckgo/app/privacymonitor/ui/PrivacyMonitorGradeExtension.kt
app/src/main/res/drawable/privacygrade_icon_a.xml
app/src/main/res/drawable/privacygrade_icon_b.xml
app/src/main/res/drawable/privacygrade_icon_c.xml
app/src/main/res/drawable/privacygrade_icon_d.xml
app/src/main/res/menu/menu_browser_activity.xml

Asana Issue URL: https://app.asana.com/0/488551667048375/500109750623815
Currently we only show a "?" for the privacy grade as the user browses pages. This PR displays the privacy grade icon.
TEST ONE
1. Visit duckduckgo.com
1. Ensure the privacy toggle is on
1. Note the grade is A
TEST TWO
1. Visit cnn.com
1. Ensure the privacy toggle is on
1. Note that the grade in the omnibar shows an C (the upgraded grade not a D the original grade)
1. Repeat the test again with the toggle off
1. Note the grade is now D

Add privacy grade to omnibar

---

app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoRequestRewriter.kt

This allows the functionality for devices running below Android API 24
Asana Issue URL: https://app.asana.com/0/414730916066338/508841948388772
GitHub Issue URL: https://github.com/duckduckgo/Android/issues/79
We are missing the inclusion of a deprecated method, required to satisfy users running Android API 23 or below.
Reported through public GitHub issues.
Set breakpoints in `BrowserWebViewClient` inside both implementations of `shouldOverrideUrlLoading`
1. Run the app on a device API 24 or greater; ensure the correct method is called
1. Run the app on a device API 23 or lesser; ensure the correct method is called
1. In both cases above, ensure the URL overriding is correctly determined.

Add deprecated shouldOverrideUrlLoading implementation

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/DuckDuckGoUrlDetectorTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoUrlDetector.kt
app/src/main/res/layout/activity_browser.xml

Also, made some parameters non-null to simplify the logic in the DuckDuckGoUrlDetector class. There's only a single place that could have been supplying nulls, so handling that at the original call-site instead.
Asana Issue URL: https://app.asana.com/0/488551667048375/494978153394812
Fixing a bug where the omnibar would show the previous query erroneously under certain conditions.
1. Enter search query "test search" into omnibar (ensure "test search" is shown in the omnibar bar with the DDG search results page)
1. Enter "duckduckgo.com" (ensure full url containing "https://" is shown)
1. Enter term into the DDG web field; ensure the omnibar shows search query and not full url

Extract query from DDG url (rather than storing the last searched query)

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/privacymonitor/model/PrivacyGrade.kt
app/src/main/java/com/duckduckgo/app/privacymonitor/model/PrivacyMonitorGradeExtension.kt
app/src/main/java/com/duckduckgo/app/privacymonitor/ui/PrivacyDashboardViewModel.kt

Asana Issue URL:  https://app.asana.com/0/488551667048375/507672913295807
The progress bar was often failing to move to 100% and hide even after the page had finished loading. This was caused by mutable live data being updated by both set and post (thread safe) methods.
This PR moved the PrivacyGrade to its own live data object.
1. Browse to cnn.com
1. Note the progress indicator no longer stalls art 95%. It reaches 100% and then hides.

Fix issue where progress indicator continued to show

---

app/src/main/res/layout/content_tracker_networks.xml

Asana Issue URL: N/A
Fixes capitalisation on network list
1. Go to theguardian.com
1. Open the Privacy Dashboard
1. Open Tracker Networks
1. Ensure that the text under the domain is capitalised e.g "7 TRACKER NETWORKS BLOCKED"

Make text unselectable as it is breaking allCaps

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/KeyboardAwareEditText.kt
app/src/main/java/com/duckduckgo/app/global/IntentExtension.kt
app/src/main/java/com/duckduckgo/app/home/HomeActivity.kt

https://app.asana.com/0/414730916066338/492769985844014
https://app.asana.com/0/414730916066338/364465928695406
Allows our app to be set as the default system browser. Also allows our app to open shared urls and text.
TEST ONE
1. Clear any default browsers you have set
1. Open an app with a url in it e.g SMS, evernote etc
1. Tap the link and select to open it with DuckDuckGo, select always
1. Ensure our app launches and opens the url
1. Ensure Duckduckgo is now the default browser (this can be checked under applications in settings)
TEST TWO
1. Open Chrome
1. Navigate to a page
1. Open the menu and select share
1. Select DuckDuckGo
1. Ensure our app launches and opens the url
TEST THREE
1. Open an application which contains text e.g email
1. Highlight some text and …

Allow app to be default browser and receive shared urls from other browsers

---

app/build.gradle
app/schemas/com.duckduckgo.app.global.db.AppDatabase/2.json

Asana Issue URL: https://app.asana.com/0/414730916066338/510868278192003
Enables Room DB schema generation.
This will be useful when we need to test DB schema migrations. Not needed now before proper release, as we just deleting the DB when there is a breaking change while in development.
As an ongoing exercise, if we up the DB version number, it will generate a new JSON schema for that new version, which should be added to source control.
1. Build the app.
1. Ensure JSON is generated under `app/schemas`

Enable room schema generation, and add to source control

---

app/src/main/AndroidManifest.xml

Asana Issue URL: https://app.asana.com/0/414730916066338/526690622695017
The default implementation of `WebView` will upload usage metrics to Google (if the user has consented). I can only assume we don't want this to happen.
>  WebView may upload anonymous diagnostic data to Google when the user has consented. This data helps Google improve WebView. Data is collected on a per-app basis for each app which has instantiated a WebView. An individual app can opt out of this feature by putting the following tag in its manifest:
>   
>   
`<meta-data android:name="android.webkit.WebView.MetricsOptOut" android:value="true" />`
>
>   Data will only be uploaded for a given app if the user has consented AND the app has not opted out.
1.  Check the AndroidManifest.xml contains the appropriate …

Opt out of web view metrics

---

app/src/main/AndroidManifest.xml

Asana Issue URL: https://app.asana.com/0/488551667048375/526624108986407
Currently, even if the user rotation-locks their device, our app still rotates.
"fullSensor" is the problem; removing this from all activities
1. Lock the device's orientation
1. Return to our app
1. Rotate the device; ensure the orientation doesn't change
1. Unlock the device's orientation and rotate; ensure the orientation does change.

       Removing "fullSensor" to give user back control over rotation locking

---

app/src/androidTest/java/com/duckduckgo/app/httpsupgrade/HttpsUpgraderTest.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/HttpsUpgrader.kt

Asana Issue URL:  https://app.asana.com/0/488551667048375/526624108986426
Treat domains with fewer parts with more caution.
1.  Launch the app and got to localhost - should not crash (will show Webview error page)
1.  Launch the app and got to macpro.localhost - should not crash (will show Webview error page)
1. Go to http://widgets.en.alibaba.com - upgraded to https (and then goes to a 404 page)

fixed crash caused by domain with only one part

---

app/src/main/java/com/duckduckgo/app/trackerdetection/api/TrackerDataDownloader.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/db/TrackerDataDao.kt

Asana Issue URL: https://app.asana.com/0/414730916066338/522562831442810
Clears out any existing `disconnect` data before persisting new data from the network
1. It's hard to test without debugging. 
1. Breakpoint `TrackerDataDownloader.disconnectDownload()` method
1. Test existing data ok with `trackerDataDao.getAll()`
1. Then manually execute `trackerDataDao.deleteAll()`, followed by `trackerDataDao.getAll()` again to ensure no results are then returned

Clear out old disconnect data when new data available

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/di/AppComponent.kt
app/src/main/java/com/duckduckgo/app/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/global/view/FireDialog.kt
app/src/main/java/com/duckduckgo/app/home/HomeActivity.kt

Asana Issue URL: https://app.asana.com/0/414730916066338/526624108986425
Settings for duckduckgo.com are held in cookies. These cookies should be the **only** cookies that can survive being burned by the fire action.
1. Perform a search to land on duckduckgo.com results page
1. Change `Safe Search` from `Strict` to `Moderate`
1. Log in to a website (one that will use cookies to remember you logged in)
1. 🔥  it all
1. Perform another search to land on duckduckgo.com results page
1. Ensure `Safe Search` has remembered your preference for `Moderate`
1. Return to the site you logged in
1. Ensure you are **not** still logged in

Save "duckduckgo" cookies from being deleted when fire action invoked

---

app/src/androidTest/java/com/duckduckgo/app/privacymonitor/ui/PrivacyDashboardViewModelTest.kt
app/src/main/java/com/duckduckgo/app/privacymonitor/ui/PrivacyDashboardActivity.kt
app/src/main/java/com/duckduckgo/app/privacymonitor/ui/PrivacyDashboardViewModel.kt

Asana Issue URL: https://app.asana.com/0/488551667048375/530408363493354
Refreshes the page when landing back on the browser after the PrivacyDashboard is toggled
1. Visit a webpage
1. Open the privacy dashboard
1. Toggle it
1. Return to the site - the page should refresh

Refresh webpage after privacy change

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacymonitor/model/PrivacyGradeTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacymonitor/model/PrivacyMonitorGradeExtensionTest.kt
app/src/main/java/com/duckduckgo/app/privacymonitor/model/PrivacyGrade.kt
app/src/main/java/com/duckduckgo/app/privacymonitor/model/PrivacyMonitorGradeExtension.kt

Reviewer: Caine
Asana: https://app.asana.com/0/318512979878271/530377544792268
Add ceiling of B to privacy grades without a ToS;DR classification of A
1. Visit netflix.com with content blocking on
1. Note that result is a "B" now not an "A"

Privacy grade ceiling

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

This relates to my previous stack PR
https://app.asana.com/0/361428290920652/532687991106939
Move privacy grade observer to onCreateMenuOptions so that privacy grade isn't updated before menu is available
1. Open settings
1. Tap the about page
1. The privacy grade should show without needing a reload

Start privacy grade observer when menu is inflated

---

app/src/main/AndroidManifest.xml

Github Issue: Assistant App no longer working #142
Added intent to set this app as default assistant. Now you can open the app with a long press on the home button.
1. Set DuckDuckGo as deafult assistent  
Android 8: Android Settings > Apps & Notifications > Default-Apps > Assistant & Language > Assistant-App > select DuckDuckGo  
2. Long Press the home button  
3. DuckDuckGo opens

Allow app to be default assistant

---

app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/privacymonitor/store/PrivacyMonitorRepository.kt

Asana Issue URL: https://app.asana.com/0/488551667048375/533891143524674
There's a crash report that privacy monitor was not initialised. the existing code initialised it only in one activity, and if the process died while the user was on another activity, this would not be initialised again.
1. Hard to test as it is hard to reproduce. Make sure the new implementation doesn't break anything around privacy grade.

Initialise the privacy monitor live data directly in singleton instance

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/home/HomeActivity.kt

Asana Issue URL: https://app.asana.com/0/488551667048375/532221766945306
Some users are reporting that the popup menu crashes for them. It appears the view used as an _anchor_ is `null` for them.
Instead of trying to use the menu item itself, this PR switches to using the `toolbar` itself as the anchor, which should be visually identical but guaranteed to be non-null instead.
1. Hard to test unless you have a device which is crashing. But make sure it doesn't break anything or change the existing look and feel of the menu on both:
1. HomeActivity
1. BrowserActivity

Use toolbar as the popup menu's anchor view instead of toolbar menu item

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/res/layout/activity_browser.xml

https://app.asana.com/0/488551667048375/533375498923960
https://app.asana.com/0/488551667048375/533891143524672
Done button doesn't submit query on some 3rd party software keyboards
This also tackles the crash reports for when `keyEvent` is `null`.
1. Install TouchPal (https://play.google.com/store/apps/details?id=com.cootek.smartinputv5&hl=en_GB)
1. Set TouchPal as the keyboard
1. Use the app, and ensure the query submits when you hit the software "Done" button

Add special handling for 3rd party keyboards which submit \n for done

---

app/src/main/java/com/duckduckgo/app/home/HomeActivity.kt

Asana Issue URL: https://app.asana.com/0/488551667048375/535704136592727
Capture the intent if launched as an assist action, and skip the home screen if so
1. Set up DDG as assist (instructions below)
1. Launch the app using the long press on the home button - ensure the app is immediately ready to query
1. With the app already running (try in various screens), do the same and ensure it works as expected
Android 8: Android Settings > Apps & Notifications > Default-Apps > Assistant & Language > Assistant-App > select DuckDuckGo

Skip home screen if launched as an assist intent

---

build.gradle

Asana Issue URL: n\a
Latest kotlin version

Latest kotlin version

---

app/src/main/res/values/styles.xml

Asana Issue URL: https://app.asana.com/0/414730916066338/533891143524670
MinWidth set to 0 caused the crash. setting to 1 fixes the crash without changing anything visually
1. Test on a Samsung Lollipop device that long pressing on the URL doesn't break it (neither does double tapping)

caused by minWidth=0; setting to 1 fixes crash with no visual changes

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt

Asana Issue URL: https://app.asana.com/0/413877547933099/536146347309401
Stop hiding the keyboard when the user enters an empty keyboard and hits the `done` button. 
1. Launch the app from the widget 
1. Hit the `done` button on the keyboard without typing any query
1. Verify nothing happens (keyboard remains visible; omnibar keeps focus; no navigation occurs)

Handle user entering empty query by not dismissing the keyboard

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Asana Issue URL: https://app.asana.com/0/413877547933099/502265450553619
Fixes a minor visual glitch when returning from the BrowserActivity to the HomeActivity. Without this fix, the privacy grade would flash up momentarily in an uninitialised state (showing `?`)
1. Navigate back from BrowserActivity to HomeActivity
1. Ensure the privacy grade button doesn't flash onscreen at all during the transition

Hiding privacy grade toolbar button when returning to home activity

---

app/src/main/res/layout/popup_window_browser_menu.xml

Asana Issue URL: https://app.asana.com/0/488551667048375/567110983215934
Add scroll view to popup menu, and fix the horizontal squishing that happens to the back/forward/refresh controls on landscape.
1. Launch the popup menu in both portrait and landscape; verify the controls look good 
1. To test the scroll view, you will either need a small screen (in landscape most likely) or artificially create the problem by adding new menu items into `popup_window_browser_menu.xml`

Fix landscape layout's squished controls; add scroll view to menu items

---

app/src/androidTest/java/com/duckduckgo/app/statistics/api/StatisticsRequesterTest.kt
app/src/main/java/com/duckduckgo/app/statistics/api/StatisticsRequester.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/578616594437384
CC:
Add variant to exti installation statistics call
1. Watch for a networking call to exti e.g https://duckduckgo.com/exti/?atb=v79-3ma
1. Ensure the atb parameter in the exti call includes the atb variant e.g v79-3ma
---

Add variant to exti call

---

app/src/androidTest/java/com/duckduckgo/app/tabs/TabDataRepositoryTest.kt
app/src/main/java/com/duckduckgo/app/tabs/TabDataRepository.kt

Fixes null timing issue with post
1. Kill the app
1. Launch the app from teh widget and ensure there is no crash
---

Fix null timing issue with post

---

app/build.gradle
app/src/main/java/com/duckduckgo/app/statistics/store/StatisticsSharedPreferences.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/578616594437384
Fix incorrect shared preferences keys
1. On an app fresh install, note the exti request is made (either by watching traffic or adding a breakpoint to `initializeAtb` method)
1. Relaunch and note that it is not made a second time
---

Fix keys for statistics so exti call is only made once

---

app/src/main/java/com/duckduckgo/app/job/AppConfigurationDownloader.kt

…ne grinds devices to a halt
Task/Issue URL: https://app.asana.com/0/414730916066338/592667188539745
CC: 
Moves scheduled jobs onto one scheduler as app is grinding to a halt when multiple are launched at once. This is a bandaid - we will improve the performance of this int he future
1. Launch fresh app
1. Note faster transition from onboarding to browser
---

Run all config on one scheduler

---

app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt
app/src/main/res/layout/fragment_browser_tab.xml
app/src/main/res/layout/include_duckduckgo_browser_webview.xml

Task/Issue URL: https://app.asana.com/0/search/587554197702895/567594137922103
CC: 
By default, any text the user types into the app can be used for personalisation by whichever keyboard is in use.
This PR will add the non-personalisation flag to request that doesn't happen for text typed in our app. Note, this isn't a guarantee and is just a request; the keyboard app can do whatever it wants still.
There are two places to apply the flag; one is on the omnibar `EditText` as that is a native component, and another is for keyboards spawned through the `WebView`.
The flag is only applicable for devices running Oreo and upwards.
**Discussion**
Do you think this needs to be a user-preference? It feels safe enough to me to _always_ have it enabled.
**Steps to …

Add flag so that users' typed text isn't used for personalisation

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/596538433213756
Fixes issues:
• Where a fragment could be null
• Where keyboard might not be dismissed when opening popover menu
• Youtube video could keep playing when opening new tab via assist
Check that the above are fixed
---

Fix fragment reference and small tidy ups

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/res/layout/fragment_browser_tab.xml

Task/Issue URL: https://app.asana.com/0/547792610048271/542801398504155
CC: 
Requests the keyboard displays a "GO" button instead of a "DONE" button. But this is IME specific; don't expect all keyboards to honor it. (Google's own GBoard displays it as an -> arrow now)
1. Tap on the omnibar bar to show the keyboard
1. Check the action button's text or icon. Respected on Samsung and SwiftKey.
1. Check that tapping the button actually submits the query ❗️ 
---

Change from "done" to "go" button.

---

app/src/androidTest/java/com/duckduckgo/app/browser/WebDataManagerTest.kt
app/src/main/java/com/duckduckgo/app/browser/WebDataManager.kt
app/src/main/java/com/duckduckgo/app/global/view/FireDialog.kt

Task/Issue URL: https://app.asana.com/0/413877547933099/611090365191865
CC: 
This is only needed on pre-Oreo devices. From Oreo onwards, the auto-fill framework kicks instead of the WebView saved form data (as per https://codereview.chromium.org/2794113002)
On a pre-Oreo device;
1. Visit a site which has the autocomplete flag set in the HTML form element (e.g., https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_form_autocomplete)
1. Enter a value in `First Name` field (you can ignore email for quicker entry)
1. Hit submit
1. Refresh the webpage
1. Click on the `First name` field again - you **should** see the first name suggested for you.
1. 🔥 
1. Repeat
1. This time you **should not** see the value you entered in the …

Clear form data on fire button

---

app/src/main/java/com/duckduckgo/app/global/job/JobBuilder.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/622674467677606
CC: 
This is only used when there has been a failure in the job. The default is 30 seconds so we're making the retries less aggressive.
1. Just checking the code is probably fine
1. But if you want to really test it, you could go make the job fail and see if it retries 30 seconds later or 30 minutes later.
1. But checking the code is probably fine 😄 
---

Set JobScheduler backoff policy to 30 minutes exponential back-off

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/board
Updates omnibar to show controls (fire, tabs, menu) when textfield is empty
1. Launch the app to the home screen
1. Ensure that the fire, tabs and menu buttons are visible
1. Start typing and ensure that the textfield expands to cover the buttons
1. Clear the text to show them again
Note: refer to images in https://app.asana.com/0/488551667048375/board
---

Update omnibar to show controls when input is empty

---

app/src/main/java/com/duckduckgo/app/global/api/ResponseExtension.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/646509999202748
Fix issue where we consider a network response to come from the cache even when caching is off or there is new data
TEST ONE
1. Run the app and watch network data in charles
1. Allow the app to sync and download everything
1. In Charles, right click the https://duckduckgo.com/contentblocking.js?l=easylist request and select the "No caching" option
1. Start the app again and logs should show an entry of "Updating EASYLIST data store with new data"
TEST TWO
1. In Charles, right click the https://duckduckgo.com/contentblocking.js?l=easylist request and *deselect* the "No caching" option from the previous test
1. Kill and launch the app again let it sync (do this twice)
1. Logs …

Fix network caching bug

---

app/src/androidTest/java/com/duckduckgo/app/statistics/api/StatisticsRequesterTest.kt
app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoRequestRewriter.kt
app/src/main/java/com/duckduckgo/app/global/AppUrl.kt
app/src/main/java/com/duckduckgo/app/statistics/api/StatisticsRequester.kt
app/src/main/java/com/duckduckgo/app/statistics/api/StatisticsService.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/649057775699176 
Temporarily adds the app version number (tappv) to exti and atb calls to help diagnose unexpected additional calls to exti
1. Run the app from a clean installation and watch traffic in charles
1. Note that the exti and atb calls contain the tappv parameter
1. Perform a search note the the atb call again contains the tappv parameter
---

Add app version to backend stats calls

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/QueryUrlConverterTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/UriStringTest.kt
app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApi.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarEntryConverter.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/QueryUrlConverter.kt
app/src/main/java/com/duckduckgo/app/global/UriString.kt
app/src/main/java/com/duckduckgo/app/global/ViewModelFactory.kt
app/src/main/java/com/duckduckgo/app/migration/LegacyMigration.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabEntitiy.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabRendererExtension.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/656938381127814 and https://app.asana.com/0/361428290920652/611385370877136
• Removes the manual launching of share intents into tabs allowing live data updates to trigger them. This fixes an issue where sharing from an external app such as Chrome sometimes failed, resulting in a blank tab.
• Clears unused blank tabs
*SHARE TESTS:*
- With the app open, share a url from chrome to our app and ensure the shared url displays
- With the app closes, share a url from chrome to our app and ensure the shared url displays
- Now repeat the above steps with developer settings set to "Don't keep activities" on and "Background process limit" set to one
- Reset the settings changed in …

Fix share failure and blank tabs

---

app/src/androidTest/java/com/duckduckgo/app/browser/DuckDuckGoRequestRewriterTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/QueryUrlConverterTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/api/ApiRequestInterceptorTest.kt
app/src/main/java/com/duckduckgo/app/di/NetworkModule.kt
app/src/main/java/com/duckduckgo/app/global/AppUrl.kt
app/src/main/java/com/duckduckgo/app/global/api/ApiRequestInterceptor.kt
app/src/main/java/com/duckduckgo/app/global/api/Header.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/TrackerDataLoader.kt

Task/Issue URL:  https://app.asana.com/0/193817002363848/661090964923373
CC: @nilnilnil 
Adds a networking interceptor to include a custom user agent to API requests. Also:
• Removes some dead code
• Updates the appversion to include dots rather than underscores
1. Run a fresh install of the app and watch traffic using a traffic sniffing tool e.g Charles
1. Ensure that api requests (e.g atb, exti, contentblocking.js?l=https2, contentblocking.js?l=disconnect, https2 etc) now contain a full user agent string e.g `ddg_android/5.2.0 (com.duckduckgo.mobile.android; Android API 22)` and not
` okhttp/3.10.0`
1. Run the app again and ensure that caching still works e.g contentblocking.js?l=disconnect should respond with a 304 now
---
[Software …

Add user agent to api calls

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/675239971772914
Fixes issue where queries e.g http://duckduckgo.com?q=test display full url rather than just "test" query part in the omnibar.
*TEST 1:*
1. Submit a query e.g "test" in the app
2. Ensure that only test appears in the omnibar
*TEST 2:*
1. Enter a full (non ddg) url e.g http://www.bbc.co.uk
2. Ensure the full url is displayed in the omnibar
---

Fix query bug

---

app/src/androidTest/java/com/duckduckgo/app/browser/DuckDuckGoRequestRewriterTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/QueryUrlConverterTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/api/StatisticsRequesterTest.kt
app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoRequestRewriter.kt
app/src/main/java/com/duckduckgo/app/global/AppUrl.kt
app/src/main/java/com/duckduckgo/app/statistics/api/StatisticsRequester.kt
app/src/main/java/com/duckduckgo/app/statistics/api/StatisticsService.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/649057775699177
Remove tappv parameter from app searches
1. Run a clean install of the app and watch network traffic
1. Submit a search
1. Ensure the tappv parameter is no longer in our atb, exti or search requests
---

Remove app version from requests

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: #168 
After loading a webpage with a large address it wasn't easy to see the webpage domain name. This PR fixes this issue.
- Open the app and enter a large url 
- Click on a link that loads a large url
---

Move address bar text to start after loading page

---

app/src/main/res/layout/popup_window_browser_menu.xml

The last item from the popup menu can now be shown and clicked on small screens or landscape mode.
Task/Issue URL: https://github.com/duckduckgo/Android/issues/241
CC: 
Fix popup menu scroll when height is out of bounds
- Open the app
- Click on the menu item on the toolbar in a small screen or in landscape mode
---

Fix popup menu scroll when height is out of bounds

---

app/src/main/res/layout/fragment_browser_tab.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/701529969506244
CC: 
Changes the position and elevation of the fullscreen `View` used for when the `WebView` goes fullscreen.
1. Go to a site that supports going into full screen mode; such as youtube.com, vimeo.com etc...
1. Start watching a video, and click to enable full screen mode
1. Verify the omnibar (and all other UI elements) are hidden by the full screen video container
1. Exit full screen mode, and very everything looks as you'd expect
---

Ensure full screen webView container covers all other UI elements

---

app/src/androidTest/java/com/duckduckgo/app/feedback/ui/FeedbackViewModelTest.kt
app/src/main/java/com/duckduckgo/app/feedback/api/FeedbackSender.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/FeedbackActivity.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/FeedbackViewModel.kt
app/src/main/res/values/strings.xml
build.gradle

Task/Issue URL:  https://app.asana.com/0/361428290920652/724386484375024
- Makes the comment field mandatory on broken sites
- Adds broken site specific hint message
_TEST 1_
1. Open the "Report broken site" form
1. Enter a url and note that the submit button is NOT activated
1. Enter text in the comment field and note the button IS activated
_TEST 2_
1. Open the "Report broken site" form
1. Toggle the switch on and off and ensure that message hint text changes to "broken site" specific text when the switch is on
---

Make comment field mandatory

---

app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt

Task/Issue URL: https://app.asana.com/0/inbox/361428290920650/726269452565961/726269452565964
Fixes issue where the webview rather than the onPageFinished callback url was used, showing an incorrect url on some devices on a failed page load
1. Visit a pages e.g bbc.com
1. Now enter nonsense.url in the omnibar and press enter
1. The page will fail to load
1. Ensure the omnibar shows the failed text 'nonsense.ulr` rather than the previously sucessful text
---

Fix issue where last loaded url could show in omnibar when page fails

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/726263852905235/f
Fixes issues where omnibar could be hidden away and inaccessible
1. Go to a webpage
1. Scroll the page up to hide the bars
1. Press the back button to go home.
1. Observe that the bar is shown
---

Ensure omnibar shows on reset

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/724933382879815
Use site model url (rather than live url which is designed to trigger a navigation) for broken site form
1. Visit a broken site e.g drudgereport.com
1. Select "Report broken site"
1. Ensure the correct url appears in the Url field
---

Fix issue where url can sometimes be out-of-date on broken url form

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/727172188146397
CC: 
A regression meant that the view state was checked to see if it was identical to the last seen view state. If it was, rendering would skip. But for these forward/back buttons, they also relied on `WebView `state; not just the view state. So we were erroneously skipping updates for them because the view state was identical.
The fix is to include these in the view state itself, meaning it won't skip the rendering if `canGoBack()` or `canGoForward()` has changed.
`onProgressChanged` is the earliest place where the `WebView` starts reporting the correct new states. But I've included the update in `loadingFinished()` too just in case `onProgressChanged()` could be bypassed somehow. …

Fix back/forward browser navigation buttons

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/res/layout/fragment_browser_tab.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/757906361496519
CC: 
Previously we programmatically hid the view when it wasn't needed as the logo would otherwise have overlapped the WebView. However, that isn't needed if we re-order the view hierarchy to let the WebView sit on top of the logo anyway
1. Turn on developer settings to destroy activities immediately
1. From the new tab screen, hit the home button
1. Return to the app. Verify that the DDG logo is still visible.
---

Stop hiding newTabLayout on global state change

---

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/392891325557410/757819156125525
CC: 
Add `sa` and `sb` variants for use by the SERP.
1. Fresh install (or clear data) and ensure you get an `sa` and `sb` 
1. Ensure no regression on existing variants
---

add serp variants and use equal normalised weighting across the board

---

app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/761289873985324
CC: 
Previously, we only added the flag for no personalization to Oreo devices as the flag was only defined from there onwards.
However, it's now apparent we can just grab the value of the flag and directly apply that value, and the keyboard will still respect it.
1. Grab a Nougat or earlier device, using GBoard as your keyboard
1. Tab the omnibar - verify the keyboard shown is marked as incognito
1. Visit a website which contains a text field - eg, bbc.co.uk
1. Click on the search icon, and it'll reveal a text field. Tap on this and verify the keyboard shown is marked as incognito.
--- …

Add flag to request no personalization on keyboard for all OS versions

---

app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
app/src/main/java/com/duckduckgo/app/global/ViewModelFactory.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/763395487483363
CC: 
Adds the variant to the settings string in settings
1. Visit settings when you have a variant; verify the settings now ends `variant=(xx)` where `xx` is your variant key
1. Visit settings when you don't have a variant; verify the settings now ends `variant=()`
---

Add variant key to the app version in settings

---

app/src/androidTest/java/com/duckduckgo/app/browser/WebViewLongPressHandlerTest.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewLongPressHandler.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardViewModel.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
app/src/main/res/layout/content_privacy_dashboard.xml

Task/Issue URL: https://app.asana.com/0/392891325557410/772541567088307
CC: 
Adds new pixels for the Privacy Dashboard and Long Press Menu.
Note, is subject to pixels.json changes being approved but currently has no conflicts.
Check each pixel is fired under the specified circumstances.  Can be verified by monitoring Kibana with specified query or using network proxy to sniff traffic.
Privacy Protection dashboard:
Kibana `ddg_app:pixel AND pixel_id:mp AND url:/\/t\/mp_._(.?+)_(.?+)/`
1. Tap on grade to view score card, fires `mp_c`
1. Tap on encryption type, fires `mp_e`
1. Tap on Tracker Networks found/blocked, fires `mp_n`
1. Tap on Privacy Practices, fires `mp_p`
1. Tap on Global Stats, fires `mp_s`
Long press menu:
Kibana …

add new pixels for dashboard and long press

---

app/src/main/cpp/https-bloom-lib.cpp

Task/Issue URL: https://app.asana.com/0/72649045549333/721626625236432
JNI cleanup to release chars after use
1. Visit http://example.com and make sure it is upgraded to https
1. Visit a site from https://staticcdn.duckduckgo.com/https/https-mobile-whitelist.json e.g azara.org and make sure it is not upgraded to https
---

Release JNI string chars after use

---

app/src/main/java/com/duckduckgo/app/httpsupgrade/api/HttpsUpgradeDataDownloader.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/model/HttpsBloomFilterSpec.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/721626625236432
I noticed the https binary being downloaded at times when it should have come from the cache. This PR replaces the bloom filter download cache check with a check against the stored bloom specification in the db. The bloom filter is a large download and we definitely do not want to duplicate it!
1. Run a new installation of the app and note "Updating https bloom data store with new data" in the logs when the initial app configuration run
1. Now kill and run the app again to trigger another download note that the logs now say "Https bloom data already stored for this spec"
--- …

Use stored specification rather than etag download check for https binary

---

app/build.gradle
app/src/main/res/xml/network_security_config.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/615543272514906
CC: 
Apps targeting Android Pie have cleartext comms disabled by default. That doesn't really work for a browser. So we enable cleartext comms but disable cleartext comms for *duckduckgo.com sites to enforce secure comms with our server.
Repeat these steps for both an Android Pie device and a pre-Pie device.
1. Verify the https/tracker lists are successfully downloaded from duckduckgo.com servers upon app installation
1. Visit an insecure site (e.g., http://stealmylogin.com). Verify the site loads as expected
1. Visit a secure site, such as https://bbc.co.uk and verify that loads correctly.
⚠️ Since we're updating the `targetSdk`, there are additional …

Update to target Android Pie 🥧

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/0/608920331025315/794822164879962
CC: 
Small fix to remove duplicate call to `finish()` the Activity when clearing the data from an app shortcut.
1. Use the app shortcut to clear the data
1. Once the browser restarts, use the in-app fire button
1. Verify the app restarts and doesn't just disappear
---

Remove duplicate call to finish() when clearing data from app shortcut

---

app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/FeedbackActivity.kt
app/src/main/java/com/duckduckgo/app/fire/FireActivity.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoActivity.kt
app/src/main/java/com/duckduckgo/app/launch/LaunchActivity.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyPracticesActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/ScorecardActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/TrackerNetworksActivity.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt

No Asana issue for this one, as it's just a code tidy up.
Although I haven't functionally changed anything, this PR reduces the boilerplate needed in each `Activity` to obtain its `ViewModel`. We do this by moving the worst of the boilerplate to the parent `Activity` as a function.
The result now is that in each `Activity`, obtaining the `ViewModel` is as simple as 
**Now 👇**
private val viewModel: BookmarksViewModel by bindViewModel()
**Before 👇**
@Inject	
lateinit var viewModelFactory: ViewModelFactory
private val viewModel: BookmarksViewModel by lazy { 
private val viewModel: BookmarksViewModel by bindViewModel()
ViewModelProviders.of(this, viewModelFactory).get(BookmarksViewModel::class.java)	
}
1. Just make sure the app is compiled and …

Reduce boilerplate in each Activity in the way the ViewModel is obtained

---

app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/res/menu/menu_tab_switcher_activity.xml

Task/Issue URL: https://app.asana.com/0/608920331025315/797446954126366
CC: 
When we added "close all tabs", it felt strange having an overflow with only one menu item in it. Furthermore, Chris M has expressed a desire to have a way to reach Settings from here too, and a look at some other browsers showed they were also duplicating the "new tab" option in their overflows too.
1. Visit tab switcher, and tap on the overflow
1. Ensure that "new tab" works identically to the existing `+` button
1. Ensure that "settings" takes you to settings 
---

Add new items to the Tab Switcher's overflow menu

---

app/src/androidTest/java/com/duckduckgo/app/onboarding/ui/OnboardingViewModelTest.kt
app/src/main/java/com/duckduckgo/app/global/ViewModelFactory.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingViewModel.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/803981054805900
CC: 
Roll out the onboarding screen for default browser to everyone
1. Install on a `>= Nougat` device; verify you see the third onboarding page
1. Install on a `< Nougat` device; verify you do not see the third onboarding page 
---

Remove onboarding as an experimental feature

---

app/build.gradle
app/src/androidTest/java/com/duckduckgo/app/browser/WebViewLongPressHandlerTest.kt
app/src/androidTest/java/com/duckduckgo/app/di/StubStatisticsModule.kt
app/src/androidTest/java/com/duckduckgo/app/global/UriExtensionTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/ApiBasedPixelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/global/UriExtension.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/HttpsUpgrader.kt
app/src/main/java/com/duckduckgo/app/statistics/api/PixelService.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/832602107339144/f
Tech Design URL: N/A however spec was discussed in https://app.asana.com/0/56420494107937/832602107339145/f
Fire pixel on https upgrade failures to allow bad data to be removed from lists
1. Go to a broken https upgrade site ensure that the new ehd pixel is fired.
It may be easier to remove the `httpsUpgrader.shouldUpgrade` check in the `isHttpsUpgradeSite` and visit https://badssl.com and ensure the pixel fires from there.
1. Ensure that existing pixels fire as normal
---

Fire pixel on https upgrade failures

---

app/build.gradle
app/src/androidTest/java/com/duckduckgo/app/di/StubStatisticsModule.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/api/HttpsUpgradeDataDownloader.kt
app/src/main/java/com/duckduckgo/app/job/AppConfigurationDownloader.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
app/src/main/java/com/duckduckgo/app/statistics/store/StatisticsDataStore.kt
app/src/main/java/com/duckduckgo/app/statistics/store/StatisticsSharedPreferences.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/839627367764303
Tech Design URL: N/A however spec was discussed in https://app.asana.com/0/361428290920652/832602107339150
- Add a summary `ehs` pixel to determine https failures versus successes
- Remove status error from `ehd` pixel. Status errors are generally connectivity (we never see them in kibana as the `ehd` pixel fails too) but they could skew summary counts
- Restrict errors to main frame
1. Go to a broken https upgrade site ensure that the failure `ehd` pixel is still fired.
It may be easier to remove the `httpsUpgrader.shouldUpgrade` check in the `isHttpsUpgradeSite` and visit https://badssl.com and ensure the pixel fires from there.
1. Navigate to a few sites successfully
1. …

Add https upgrades summary pixel

---

app/src/main/res/values/strings.xml

Task/Issue URL: https://app.asana.com/0/413877547933099/850924127668095
CC: 
Improve grammar in about page
1. Go to Settings, then `About DuckDuckGo`
1. Verify grammar is fixed
---

Fix type in about page

---

app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
app/src/main/java/com/duckduckgo/app/global/ViewModelFactory.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/816426578517930
Tech Design URL: https://app.asana.com/0/361428290920652/814618797160182
Adds pixel for settings and switching between light and dark theme
1. Comment out all variants other than `mh` and `mj` in `VariantManager`
1. Open Settings note that the mp pixel fires
1. Toggle the theme a few times and note that the mp_tl (light theme) and mp td (dark theme) fire as appropriate
---

Add light theme pixels

---

app/src/androidTest/java/com/duckduckgo/app/httpsupgrade/BloomFilterTest.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/api/HttpsBloomFilterFactory.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/api/HttpsUpgradeDataDownloader.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/850930018552054
Fixes issue where bad bloom data could cause the app to crash. Also performed some tidy up.
1. Run the app on an emulator
1. Once a sync has finished delete the file at /data/data/com.duckduckgo.mobile.android/files/HTTPS_BINARY_FILE
1. Run the app again, note that the app does not crash and the file is downloaded again during the next sync
---

Verify bloom checksum before load

---

app/src/androidTest/java/com/duckduckgo/app/statistics/ExperimentationVariantManagerTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/global/Theming.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/api/HttpsUpgradeDataDownloader.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherAdapter.kt
app/src/main/res/drawable/tab_background_selected.xml
app/src/main/res/drawable/tab_unread.xml
app/src/main/res/layout/activity_tab_switcher.xml
app/src/main/res/layout/content_tab_switcher.xml
app/src/main/res/layout/include_omnibar_toolbar.xml
app/src/main/res/layout/include_toolbar.xml
app/src/main/res/layout/item_tab.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml
app/src/main/res/xml/search_widget_info_light.xml

Task/Issue URL: https://app.asana.com/0/361428290920652/832439960662903
Light theme polish
NOTE: it may be helpful to comment out the `sa`, `sb` and `mg`  variants in `VariantManager.kt`.
Light theme tweaks:
1. Go to settings
1. Switch to light theme
1. Note the gray background of the toggles show
1. Press the up button, note the ripple/shadow shows
1. Visit the tabs switcher screen, note the lighter background.
1. Note also that the unselected tabs are no longer grayed out (this also applies in dark mode)
Ensure omnibar does not disappear
1. Open the settings and switch between light and dark modes a few times
1. Press the back button to go back to the browser screen
1. Ensure the omnibar is still visible
--- …

Light theme polish

---

app/src/androidTest/java/com/duckduckgo/app/global/UriExtensionTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/global/UriExtension.kt
app/src/main/java/com/duckduckgo/app/global/job/JobBuilder.kt

https://app.asana.com/0/361428290920652/863340012156759
https://app.asana.com/0/361428290920652/863340012155762
* Removes the url path from EHD pixels.
* Increases app sync to 12 hours and failure backoff to 1 hour to reduce data usage and load on the backend
* Removes the simpleUrl extension method based on previous team conversations that it is not needed
**TEST PIXEL**
1. Turn on charles and watch app traffic
1. Visit https://badssl.com/abcd
1. Note the EHD pixel fires as https://badssl.com (without a path)
**CHECK SYNC LOGIC**
Check the code to ensure sync time has been updated to 12 hours.
--- …

Reduce sync frequency and remove https path from EHD pixel

---

app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoActivity.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/global/Theming.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/inbox/361428290920650/816830036286389/889504268656433
Remove the light theme A/B experiment and release the light theme as a settings option, maintaining the dark theme default.
***Upgrade installation***
1. Install the develop versions of the app, ensuring that you are allocated to varianr mj
1. Go to settings and switch to light theme
1. Now install this branch over the top
1. Ensure your light theme selection was maintained
***New installation***
1. Install a fresh version of the app
1. Ensure that the dark theme is the default
1. Ensure the theme can be changed to light in settings
--- …

Remove light theme experiment and enable for all

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/392891325557410/898065300990903
CC: 
Remove ATB and source params from search URLs when sharing. 
1. Perform a search and use the browsing menu to share the URL.  Copy it and paste it in to Chrome - should be no ATB or source parameters.
1. Share other non-search links - URLs should be unaffected.
---

remove atb and source from search urls when sharing

---

app/src/androidTest/java/com/duckduckgo/app/global/UriExtensionTest.kt
app/src/main/java/com/duckduckgo/app/global/UriExtension.kt

Task/Issue URL: https://app.asana.com/0/inbox/608920331025313/945591783985791/945614451233295
CC: 
Adds "mobile." in as a recognised mobile-specific URL
1. Visit facebook.com - it'll redirect to the mobile site by default
1. Verify "request desktop site" takes you back to the main facebook.com page
Ideally, if you know a site which uses the "mobile." format for mobile pages, test that too. I don't know of one to hand though*
*Twitter does use mobile.twitter.com, but it also forcefully puts us back to that even if request desktop site is requested, so it's not a great test case.
--- …

When detecting mobile URLs, also includes "mobile."

---

app/src/androidTest/java/com/duckduckgo/app/feedback/api/SurveyDownloaderTest.kt
app/src/androidTest/java/com/duckduckgo/app/feedback/db/SurveyDaoTest.kt
app/src/main/java/com/duckduckgo/app/feedback/api/SurveyDownloader.kt
app/src/main/java/com/duckduckgo/app/feedback/db/SurveyDao.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/945831998597279
There are cases when we want to switch a survey off on the backend to make changes and then switch it back on again, however doing so sets the survey to a cancelled status so existing users will never see it (new users will).
When syncing, delete old surveys that the user has not interacted with. This data is irrelevant (we only care about surveys they have dismissed or submitted) and clearing it allows us to reschedule easily.
**TEST 1: Undismissed survey appears again after a sync**
- Install a fresh version of the app
- Using a tool such as Charles intercept the survey request to https://staticcdn.duckduckgo.com/survey/survey-mobile.json and replace with
```
{
"id": …
```

Delete unused surveys when syncing

---

app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/193817002363848/948421103947412
CC: 
Adds pixels for when the what/when settings dialogs are shown
1. Enable proxy
1. Click on the "Automatically clear..." _what_ option; verify the **macwhat_s** pixel is created
1. Click on the "Clear on..." _when_ option; verify the **macwhen_s** pixel is created
---

Add pixel for when automatic clear settings dialogs are shown

---

app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt

Task/Issue URL: https://app.asana.com/0/193817002363848/948558473017839
CC: 
The `SettingsViewModel` wasn't correctly updating the `ViewState` to reflect new values of autocomplete and light theme.
This was always the case, but before the changes for automatic data clearing, it wasn't important as the view state was never changed beyond initial creation. Now it does change.
1. Visit settings
1. Change settings for "Automatically clear..."; verify the autocomplete/light theme radio buttons don't change
1. Toggle autocomplete radio button
1. Change settings for "Automatically clear..."; verify the autocomplete/light theme radio buttons don't change
1. Toggle light theme radio button
1. Change settings for "Automatically …

Add missing updates to view state

---

app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
app/src/main/java/com/duckduckgo/app/settings/db/SettingsDataStore.kt

Task/Issue URL: https://app.asana.com/0/193817002363848/984805359865213
CC: 
Previously we fired a pixel every time the user hit SAVE on a dialog for the automatic data clearing settings. 
Now, we only do it if they've actually changed the setting.
From a clean app state:
1. Go to app settings
1. Tap on the "Automatically clear..." setting so that the dialog appears
1. Hit "Save" (with `None` selected)
1. Verify a pixel is sent for this (even though `None` appears as default, it wasn't previously selected by the user)
1. Open the dialog again, and again, choose `None` and hit save button
1. Verify a pixel is NOT sent
1. Change the option again to something else; verify the pixel is sent
Repeat the above for the "Clear on..." …

Fire pixels for data clearing settings only when new value selected

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Fixes https://github.com/duckduckgo/Android/issues/431
Task/Issue URL: https://app.asana.com/0/488551667048375/1108574295820133
CC: 
In certain conditions, the autocomplete suggestions weren't showing, as reported and discussed in #431 
The fix for this was actually two separate fixes:
1. Improve the check for if the query has changed
1. Remove the optimisation to filter distinct results from the Rx chain
Fix 1 improved the original case described, whereby if you had a single character query, deleted it, and then repeated that query you wouldn't see the suggestions.
Fix 2 improved a related case where if you had a single character query, deleted it and **quickly** typed the same character again, you wouldn't see the suggestions.
**Steps to test this …

Fix for autocomplete suggestions sometimes not showing

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarScrolling.kt
app/src/main/res/layout/include_omnibar_toolbar.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1108456845546451
CC: 
Prevents the omnibar from scrolling when there is no `WebView` visible.
1. In blank tab view, swipe up on the omnibar; verify it doesn't scroll
1. Perform a search; verify you can now scroll the omnibar again
1. Scroll the search results; verify the omnibar scrolls in and out as expected
1. Return to blank tab view; verify the omnibar is visible and unscrollable
---

Programmatically disable omnibar scrolling on new tab page

---

app/src/androidTest/java/com/duckduckgo/app/notification/NotificationSchedulerTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/ExperimentationVariantManagerTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt
app/src/main/java/com/duckduckgo/app/di/VariantModule.kt
app/src/main/java/com/duckduckgo/app/notification/NotificationScheduler.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1111526030478043
Makes the fire notification available to all
**TEST ONE**
1. Updated the `NotificationScheduler` to scheduleClearDataNotification after seconds not days:
```scheduleClearDataNotification(SCHEDULE_AFTER_INACTIVE_DAYS , TimeUnit.DAYS, scope)```
becomes 
```scheduleClearDataNotification(SCHEDULE_AFTER_INACTIVE_DAYS, TimeUnit.SECONDS, scope)```
1. Freshly install the app
1. Launch and make sure that the notification does not show
1. Wait a few seconds to ensure the notification shows
**TEST TWO**
1. Freshly install the app
1. Run the app
1. Go to settings add an auto clear option
1. Make sure that the notification does not show
--- …

Make fire notification available to all

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserChromeClientTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt

- https://app.asana.com/0/361428290920652/1111382543212308
- https://app.asana.com/0/414730916066338/728296763895517
- Fix issue where urlChanged was being called multiple times
- Remove url live data as we have the current url stored in a number of places and it was causing confusion when debugging this issue
1. Visit cnn.com and note that urlChanged is only called once, it was previously called twice.
1. Perform a search on the SERP and note that urlChanged is only called once
1. Visit https://geekboy.ninja/p0c/spoof-bar.html and ensure that changes made in https://github.com/duckduckgo/Android/pull/390 still apply, namely that gmail url cannot be spoofed.
--- …

Fix issue where onUrlChanged is called multiple times

---

app/src/main/java/com/duckduckgo/app/trackerdetection/DisconnectClient.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1113514142528499
CC: 
When loading cnn.com, we generate ~160k instances of a `List<String>` where one instance would do.
1. Ensure this doesn't alter the functionality of the `DisconnectClient` to detect trackers
---

Stop allocating new list every time a tight inner loop is called

---

app/src/main/java/com/duckduckgo/app/privacy/model/Grade.kt

Task/Issue URL: https://app.asana.com/0/inbox/361428290920650/1114937051540633/1115009060889228
Remove mutable map (which is not thread safe) from privacy grade calculation to fix ConcurrentModificationException. Note this map generally only holds a small number of items so there is no performance issue with recreating the map when it changes.
1. Run the app and ensure that loading urls still works as expected
Note I couln't generale ConcurrentModificationException naturally however it was clear where this was coming from and I can force it to happen by spawning more threads in the `addEntityBlocked` method and then visiting a site with many trackers such as cnn.com:
```
for(i in 1..100) { …
```

Make privacy grade thread safe by using copy over mutating map

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/WebViewLongPressHandlerTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewLongPressHandler.kt
app/src/main/java/com/duckduckgo/app/browser/model/LongPressTarget.kt

Task/Issue URL: #449 
CC: 
When long pressing the page, depending on the mark up of the page, the `hitTestResult` can return the URL to an image that is embedded in the anchor tag and not the URL of the anchor tag itself.
The [Le Monde](https://www.lemonde.fr) which was mentioned in the issue (#449), has the following mark up for the article lists:
```
<a href="https://www.lemonde.fr/international/article/2019/03/21/donald-trump-pret-a-reconnaitre-de-la-souverainete-d-israel-sur-le-golan_5439399_3210.html"> 
<div class="article__media-container">
<picture class="article__media">
<source data-srcset="...." media="(min-width: 576px)" srcset="...">
</picture>
</div>
<p class="article__title">Donald Trump se dit prêt à reconnaître la souveraineté d’Israël …
```

Fix 449 - long pressing on an article link

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1119368905666087
Fixes an issue where launching from recents could load an old share intent
1. Install the app and kill it
1. Share a ulr from another app to our app.
1. Open a new tab.
1. Now press, back (a few times!) to close our app
1. Go to recents to launch our app again
1. Note that the previously shared url is not loaded in the second tab
---

Fix issue where launching from recents could create a duplicate tab

---

app/schemas/com.duckduckgo.app.global.db.AppDatabase/12.json
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/db/AppDatabaseTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
app/src/main/java/com/duckduckgo/app/global/UriExtension.kt
app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/HttpsUpgrader.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabEntitiy.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1117886846776279
Tech Design URL: https://app.asana.com/0/361428290920652/1118398381563523 and https://app.asana.com/0/361428290920652/1118398381563522
Improves three aspects of android back navigation:
- Pressing back after launching from another app takes user back to the previous application (rather than via home screen)
- When pressing back to get to the home screen, users can now press forward again to return to webpage they were viewing
- Pressing back on a https-upgraded site navigates two steps to avoid sending user back to the http site which just upgrades again
MIGRATION TEST
1. Install the develop version of the app.
1. Open some tabs
1. Install this version and make sure nothing …

Improve android back navigation

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/di/StubStatisticsModule.kt
app/src/androidTest/java/com/duckduckgo/app/notification/NotificationHandlerServiceTest.kt
app/src/androidTest/java/com/duckduckgo/app/notification/NotificationRegistrarTest.kt
app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/ApiBasedPixelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserDetector.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserInfoActivity.kt
app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserObserver.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/di/AppComponent.kt
app/src/main/java/com/duckduckgo/app/global/AppUrl.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/global/device/Device.kt
app/src/main/java/com/duckduckgo/app/global/install/AppInstallStore.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingPageFragment.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
app/src/main/java/com/duckduckgo/widget/SearchWidget.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1119886581463189
TIdy up pixels to for better widgets and default browser counts. Also add pixel to detect widget engagement.
**TEST 1: Add / Remove widget Test**
1. Run the app add a bunch of widgets
1. Note the add widget pixel "m_w_a" is fired with lang and country only once
1. Launch the app from the widget and check that the "m_w_l" pixel launches with lang and country
1. Delete all the widgets
1. Note the delete widget pixel "m_w_d" is fired once when the last widget is removed
1. Check that other pixels do not contain lang and country
**TEST 2: Set / Unset default browser** 
1. From settings, set the app as the default browser
1. Note the default …

Add new pixels for android instrumentation

---

app/src/androidTest/java/com/duckduckgo/app/global/UriExtensionTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/global/UriExtension.kt

Task/Issue URL: https://app.asana.com/0/inbox/361428290920650/1120790452461796/1120758001420790
Fix back navigation on sites like reddit that report same url onPageFinished as previous page.
1. Open a webpage e.g facebook.com
1. Now go to reddit.com
1. Select a subcategory e.g movies
1. Press back
1. You should still be on reddit.com
---

Fix back navigation on that report same url onPageFinished

---

app/src/main/java/com/duckduckgo/app/di/PrivacyModule.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/privacy/HistoricTrackerBlockingObserver.kt
app/src/main/java/com/duckduckgo/app/privacy/store/PrivacySettingsSharedPreferences.kt
app/src/main/java/com/duckduckgo/app/privacy/store/PrivacySettingsStore.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardViewModel.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1122462911344278
Add pixels for content blocking on/off
TEST HISTORIC USERS CONTENT BLOCKING ON
1. Install this version over an installation that has been running for a few days with content blocking already on (you may need to hack this in!)
1. Run the app and watch for the pixel "m_tb_on_h" to indicate that content blocking is on
1. Run launch, resume etc the app again. This pixel should never fire again.
TEST HISTORIC USERS CONTENT BLOCKING OFF
1. Install this version over an installation that has been running for a few days with content blocking already off (you may need to hack this in!)
1. Run the app and watch for the pixel "m_tb_off_h" to indicate that content blocking is off
1. Run …

Added pixels for content blocking

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1124956056611274
CC: 
Allows `WebView`s to be remotely debugged when the app is running in `BuildConfig.DEBUG` mode only.
1. From a `DEBUG` build, using Chrome on the desktop, visit `chrome://inspect` and verify the `WebView` shows and can be inspected
1. Repeat the above on a `RELEASE` build and ensure it cannot be inspected
---

Enable WebView debugging during BuildConfig.DEBUG builds

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserChromeClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1125316196364807
The app relies on onPageStarted and onPageFinished to update its navigation stack. Some sites like reddit do not call these on subpages, which can cause navigation quirks like skipping two pages when pressing the back and forward buttons.
1. Go to reddit.com
1. Navigate to a subpage
1. Press back, this should go back to reddit.com
1. Press back, this should go home
1. Press forward, this should go to reddit.com
1. Press forward, this should go to subpage
---

Update navigation options more frequently

---

app/src/androidTest/java/com/duckduckgo/app/notification/NotificationSchedulerTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt
app/src/main/java/com/duckduckgo/app/notification/NotificationScheduler.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

https://app.asana.com/0/361428290920652/1114172401555990
https://app.asana.com/0/361428290920652/1114174327194184
Removes various notification scenarios and releases **privacy stats** notification on day 1 of inactivity (also maintains existing **clear data**  notification on day 3).
Open the notification scheduler and change the privacy notification worker schedule from 1 day to 10 seconds:
```
scheduleNotification(OneTimeWorkRequestBuilder<PrivacyNotificationWorker>(), 10, TimeUnit.SECONDS)
```
And the clear data notification from 3 days to 30 seconds
```
scheduleNotification(OneTimeWorkRequestBuilder<ClearDataNotificationWorker>(), 30, TimeUnit.SECONDS)
```
1. Run a clean install of the app and background …

Release privacy notification on day one of inactivity to all users

---

app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserSystemSettings.kt

Task/Issue URL: https://app.asana.com/0/608920331025315/1125869815569488
CC: 
Highlights the default browser system setting after launching the default app system setting activity
1. Using our app's settings page, choose "Set as Default Browser" option
1. Verify that the "Browser app" (or equivalent if slightly different) is highlighted
It will be highlighted differently depending on the OS version (with older versions being a more subtle highlighting implementation) but testing that it works across a few different OS versions would be good.
---

Add intent extras so that default browser system setting is highlighted

---

app/src/androidTest/java/com/duckduckgo/app/browser/WebViewLongPressHandlerTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewLongPressHandler.kt
app/src/main/java/com/duckduckgo/app/browser/model/LongPressTarget.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/QueryUrlConverter.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
app/src/main/res/values/strings.xml

Task/Issue URL: https://app.asana.com/0/186344451334986/1124956056611278
CC: 
Adds ability to "Open Image in Background Tab"
1. Browse to a site which contains images, such as bbc.co.uk and click through into an article. Long press on an image and verify you can open the image in a bg tab, and that existing functionality such as downloading the image still works.
1. Browse to a site which uses image anchor links, such as https://lemonde.fr or ebay.co.uk, and verify that long pressing works as expected for the new and existing menu options
---

Add long press option to "open image in background tab"

---

app/src/androidTest/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt

Task/Issue URL: [Issue 347](https://github.com/duckduckgo/Android/issues/347)
CC: 
Added `checkForIntent` method to `SpecialUrlDetector` to check if entered uri is a search query or a request to open another app. 
Added a couple of tests for added functionality.
_Custom search query_: 
1. Type "foo site:duckduckgo.com"
2. It opens search page with said query
_Custom search query_: 
1. Type "myapp:foobar"
2. It looks for an app waiting for such queries  
---

347 — Parametrized queries are no longer detected as custom URIs 

---

app/schemas/com.duckduckgo.app.global.db.AppDatabase/13.json
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/db/AppDatabaseTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/db/NetworkLeaderboardDaoTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/renderer/TrackersRendererTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
app/src/main/java/com/duckduckgo/app/privacy/db/NetworkLeaderboardDao.kt
app/src/main/java/com/duckduckgo/app/privacy/db/NetworkLeaderboardEntry.kt
app/src/main/java/com/duckduckgo/app/privacy/db/SitesVisitedEntity.kt
app/src/main/java/com/duckduckgo/app/privacy/renderer/TrackersRenderer.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardViewModel.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/TrackerNetworkLeaderboardPillView.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1127123170200348
Switches to counts in the tracker leaderboard
Test migration and new data:
1. Switch to develop branch
1. Update`PrivacyDashboardViewModel.kt` variable `LEADERBOARD_MIN_DOMAINS_EXCLUSIVE` to 3
1. Run the app, visit a few pages and make sure the tracker leaderboard is showing
1. Switch to this branch
1. Run the app and ensure the migration succeeds
1. Visit the privacy dash, the leaderboard should reset
1. Visit a few pages and make sure the tracker leaderboard shows again
Check updated database:
1. Download the app.db database from app storage
1. Check the network_leaderboard table and ensure network entries are now counts not strings
1. Check the sites_visited table and …

Use counts in leaderboard

---

app/src/androidTest/java/com/duckduckgo/app/global/view/ClearPersonalDataActionTest.kt
app/src/main/java/com/duckduckgo/app/di/PrivacyModule.kt
app/src/main/java/com/duckduckgo/app/fire/AppCacheClearer.kt
app/src/main/java/com/duckduckgo/app/global/view/ClearPersonalDataAction.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1127121283487017
CC: 
Clears the app cache when the fire button is invoked.
1. Ensure you can verify app data (e.g., use an emulator / rooted device)
1. Do a DDG search
1. Clear the data using the fire button
1. Examine the `data/data/com.duckduckgo.mobile.android/cache` directory and verify there are no remnants of the previous search.
---

Delete app cache when clearing data using fire button

---

app/src/androidTest/java/com/duckduckgo/app/privacy/db/NetworkLeaderboardDaoTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/renderer/TrackersRendererTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardViewModelTest.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardViewModel.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/TrackerNetworkLeaderboardPillView.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1127250943978133
CC: 
This task covers the tidy up feedback in PR https://github.com/duckduckgo/Android/pull/509 which was reviewed post-merge.
Run the app and tests, everything should work as expected.
---

Small typo and method name tweaks

---

app/src/main/java/com/duckduckgo/app/browser/WebDataManager.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1127922529954338
CC: 
Despite the `WebView` API claiming it will delete the data, it doesn't appear to remove "Local Storage" when using their APIs. As a result, past site remnants can continue to be present in this directory.
This PR manually ensures the "Local Storage" directory is deleted, by removing it from our excluded list.
1. Test this change removes sensitive data
1. Test this changes doesn't limit the `Local Storage` abilities to perform after clearing
---

Remove "Local Storage" from the deletion exclusion list

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/api/HttpsUpgradeDataDownloader.kt
app/src/main/java/com/duckduckgo/app/job/AppConfigurationDownloader.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
app/src/main/java/com/duckduckgo/app/statistics/store/StatisticsDataStore.kt
app/src/main/java/com/duckduckgo/app/statistics/store/StatisticsSharedPreferences.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1127961676181366
Remove unused https pixels.
1. Run the app and watch traffic with Charles proxy on
1. Navigate to a few pages and then kill and restart the app
1. Note that a `ehs` pixel **does not** fire on startup sync (it previously did)
1. Using Charles proxy, blacklist duckduckgo.com
1. Navigate to http://duckduckgo.com (which will fail) and note that an `ehd` pixel does **not** fire (it previously did)
1. Remove Charles blacklist ;-)
---

Remove legacy https pixels

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://github.com/duckduckgo/Android/issues/519
The root cause of the issue seemed to be not setting the 'browserShowing' view state when view gets restored. That led to home screen showing even for tabs with url as the default setting is false.
Added a trigger to set 'browserShowing' to true if there is an url after view restore.
1. Turn on the "Don't keep activities" in developer settings
1. Open a few webpages in separate tabs and switch between them
---

Issue/519 Tabs show home instead of webpage

---

app/src/androidTest/java/com/duckduckgo/app/statistics/api/StatisticsRequesterJsonTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/api/StatisticsRequesterTest.kt
app/src/androidTest/resources/json/atb_update_response_valid.json
app/src/main/java/com/duckduckgo/app/statistics/api/StatisticsRequester.kt
app/src/main/java/com/duckduckgo/app/statistics/model/Atb.kt

Task/Issue URL: https://app.asana.com/0/392891325557410/1114152243888973
CC: 
When the `udpateVersion` property is available in the atb.js response then it is stored as the main atb version.
With Charles proxy running and a breakpoint for atb.js
1. clean install
1. edit the `atb.js` response to set the atb version to something old
1. perform a search, observe the `updateVersion` in the response
1. subsequent `set_atb` calls should use the new cohort for the atb
---

when updateVersion is present store it

---

app/src/androidTest/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt

Task/Issue URL:https://app.asana.com/0/414730916066338/1133861428497755 
CC: 
Adds special handling of `javascript:` URLs (e.g., `javascript:alert(0)`) so that they aren't treated as a reason to launch a 3rd party app. right now, the special URL is detected as being a URL that another app might want to handle, and offers it up to the system to show a launcher. This is unnecessary, and in the worst case, can result in a crash.
1. type `javascript:alert(0)` into the omnibar; verify a search is performed (and it isn't treated as invitation to launch a 3rd party app)
1. visit `http://one.vulnerableweb.site` and verify that the 3rd party app chooser is NOT shown
--- …

Add special handling for javascript URLs

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/0/inbox/608920331025313/1134626034285298/1134568220205427
CC: 
Allows the app to be launched from an external intent action `com.duckduckgo.mobile.android.NEW_SEARCH`
To test this PR, you'll need to use a third party app to launch an intent. It is important to test launching the app from outside our own app. The code to do this is:
val intent = Intent("com.duckduckgo.mobile.android.NEW_SEARCH")
startActivity(intent)
1. From a fresh install, **having never opened the app before**, run the code to launch the action; verify our app launches and displays the `BrowserActivity` and is ready to perform a search (and that the onboarding screen are **not shown**)
1. From a more usual setup, of …

Add action to launch app ready to perform a text search

---

app/src/androidTest/java/com/duckduckgo/app/browser/WebViewRequestInterceptorTest.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt

Task/Issue URL: https://app.asana.com/0/608920331025315/1134654612159126
Tech Design URL:
CC:
Description:
Change the way we load HTTPS versions of site during HTTPS-upgrades to avoid a WebView crash
Steps to test this PR:
The easiest way to test this out is to hack BrowserTabFragment.launchPopupMenu as follows
private fun launchPopupMenu() {
//popupMenu.show(rootView, toolbar)
webView?.loadUrl("http://dealnews.com")
}
Now, you can tap the overflow menu to attempt to load that site. Within a few taps of that (or certainly less than 10) on my Pixel 2, the app crashes.
Test the hack above against develop, and verify it crashes
Test the hack above against this branch, and verify it does not crash
Verify all the interceptor logic still works as before (still blocks trackers, still upgrades …

Fix timing issue which can cause a crash when performing HTTPS upgrades

---

app/src/main/res/drawable/icon_fire_glyph_24dp.xml
app/src/main/res/layout/content_bookmarks.xml

- Replace `FrameLayout` with `merge` which is more faster.
- Remove Redundant `namespace`

Lint layout tidy-up

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/store/OfflinePixelSharedPreferencesTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/di/AppConfigurationDownloadModule.kt
app/src/main/java/com/duckduckgo/app/di/StatisticsModule.kt
app/src/main/java/com/duckduckgo/app/di/StoreModule.kt
app/src/main/java/com/duckduckgo/app/job/AppConfigurationDownloader.kt
app/src/main/java/com/duckduckgo/app/statistics/api/OfflinePixelSender.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
app/src/main/java/com/duckduckgo/app/statistics/store/OfflinePixelDataStore.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1135024870354624
Adds a diagnostic pixel when the webview renderer disappear so we can determine if this is caused by a crash or memory pressure
This is a little tricky to test however one path can be tested by causing a webview crash.
1. Open Charles to watch app traffic
1. Update `BrowserTabFragment.navigate(url: String)` method to load a crashing url when "crash" entered into the omnibar
```
if(url.contains("crash")) {
webView?.loadUrl("chrome://crash")
} else {
webView?.loadUrl(url)
}
```
3. Now open the app and type crash in the omnibar. The app will crash.
1. Launch the app to start a sync
1. Ensure the pixel is fired
--- …

Add webview renderer gone diagnositc pixel

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/duckduckgo/app/global/shortcut/AppShortcutCreator.kt
app/src/main/res/drawable/ic_app_shortcut_bookmarks.xml
app/src/main/res/drawable/ic_app_shortcut_fire.xml
app/src/main/res/drawable/ic_app_shortcut_new_tab.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1132517241064881
CC: 
Adds an additional app shortcut for accessing bookmarks. This can be accessed by long pressing the app icon.
1. Long press the app icon, and verify you see bookmarks as an option
1. Verify that pressing on the bookmarks shortcut launches bookmarks
1. Choose a bookmark; verify it loads correctly
1. Long press again to see bookmarks
1. Hit the back button; verify back button takes you back to the browser activity
1. Kill the process
1. Long press again to see bookmarks
1. Hit the back button; verify back button takes you back to the browser activity (ie, checking the activity stack is created correctly)
--- …

add bookmarks app shortcut

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1134874424977664
CC: 
Stops the keyboard from showing during data clearing
1. With a webpage showing, use the 🔥button to clear the data
1. Verify the keyboard is shown once and only once, and is ready for the user to start typing
---

Remove observers when clearing starts to avoid showing the keyboard

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/bookmarks/db/BookmarkEntity.kt
app/src/main/java/com/duckduckgo/app/bookmarks/db/BookmarksDao.kt
app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt
app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModel.kt
app/src/main/java/com/duckduckgo/app/bookmarks/ui/EditBookmarkDialogFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/res/layout/edit_bookmark.xml
app/src/main/res/values/strings.xml

Task/Issue URL: https://app.asana.com/0/715106103902962/1134717259951641
CC: 
Removes the modal dialog presented to a user when they add a bookmark. Instead, the bookmark is added immediately and a `Snackbar` with an `Edit` action is shown. 
If the user does nothing, then the bookmark has already been added. If the user taps the `Edit` button, then they can choose to edit the title and/or URL.
1. Add a bookmark, and don't interact with the snackbar. 
1. verify it disappears momentarily.
1. verify the bookmark has been added
1. Add another bookmark, and this time swipe the snackbar away
1. verify it disappears momentarily.
1. verify the bookmark has been added
1. Add another bookmark, and this time hit the `edit` button
1. …

Make adding a bookmark a one-click operation (can edit from snackbar)

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/ApiBasedPixelTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/store/OfflinePixelSharedPreferencesTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/di/AppConfigurationDownloadModule.kt
app/src/main/java/com/duckduckgo/app/di/DaggerWorkerFactory.kt
app/src/main/java/com/duckduckgo/app/di/WorkerModule.kt
app/src/main/java/com/duckduckgo/app/global/AlertingUncaughtExceptionHandler.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/global/device/Device.kt
app/src/main/java/com/duckduckgo/app/job/AppConfigurationDownloader.kt
app/src/main/java/com/duckduckgo/app/statistics/api/OfflinePixelScheduler.kt
app/src/main/java/com/duckduckgo/app/statistics/api/OfflinePixelSender.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
app/src/main/java/com/duckduckgo/app/statistics/store/OfflinePixelDataStore.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1135707350642503
- Add a high level crash pixel to allow us to monitor overall crash numbers
- Send pixels via regular scheduled job, to protect against case where app is too unstable to run.
- Include app version globally in pixels.
- Update existing web render pixels to be separate entities to allow us to use standard Grafana dashboards (ClickHouse is too slow)
**Setup**
Open Charles to watch app traffic
**Test web pixel sent**
1. Update `BrowserTabFragment.navigate(url: String)` method to load a crashing url when "crash" entered into the omnibar
```
if(url.contains("crash")) {
webView?.loadUrl("chrome://crash")
} else {
webView?.loadUrl(url)
}
```
2. Open the app and type "crash" in the …

Update crash pixels and add work scheduler to send these offline

---

app/build.gradle
app/src/androidTest/java/com/duckduckgo/app/fire/AutomaticDataClearerTest.kt
app/src/androidTest/java/com/duckduckgo/app/notification/NotificationSchedulerTest.kt
app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt
app/src/main/java/com/duckduckgo/app/di/PrivacyModule.kt
app/src/main/java/com/duckduckgo/app/di/WorkerModule.kt
app/src/main/java/com/duckduckgo/app/fire/AutomaticDataClearer.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/notification/NotificationScheduler.kt
app/src/main/java/com/duckduckgo/app/statistics/api/OfflinePixelScheduler.kt
app/version/version.properties

Task/Issue URL: https://app.asana.com/0/361428290920652/1135925618579905
CC: 
Hotfix to update WorkManger and resolve RejectedExecutionException bug on APIs 21 and 22. Do not merge, hotfix will be merges as part of release.
**Setup**
Update `BrowserTabFragment.navigate(url: String)` method to crash after a url is loaded
```
webView?.loadUrl(url)
throw Exception("")
```
Test the following scenarios on API 21 AND a recent API
**Test work manager schedules immediate task**
1. Open the app and type in a search term e.g "test" in the omnibar. The app will crash.
1. Launch the app to start an immediate sync
1. Ensure the `m_d_ac` pixel is fired
**Test work manager schedules in background**
1. Set:
```
private const val …
```

Hotfix to update WorkManger and resolve Exception

---

app/src/main/res/values-hr/strings.xml

Task/Issue URL: #559 
CC: 
Previous text **_Tema svjetla_** could be translated as Theme of light or Light's theme
where as **_Svijetla tema_** might be more in line with Light Theme.
Svjetlo - noun. the natural agent that stimulates sight and makes things visible.
Svijetlo - adjective. when something is full of light.
1. 
1.

Improve string translation settingLightTheme (croatian-hr)

---

app/src/androidTest/java/com/duckduckgo/app/browser/WebNavigationStateTest.kt
app/src/main/java/com/duckduckgo/app/browser/WebNavigationState.kt

Task/Issue URL: https://app.asana.com/0/inbox/361428290920650/1134826030433169/1135999501704081
Updates the url logic to also trigger a page change when the original url is unchanged but the current page has changed to a different domain
**Test privacy practices are updated**
1. Search for cnn on the SERP
1. Note that the logs log only one page change
```
Page changed: https://duckduckgo.com/?q=cnn&atb=v105-1se&t=ddg_android
2019-08-28 01:57:46.643 31240-31240/com.duckduckgo.mobile.android V/BrowserTabViewModel: Page url updated: https://duckduckgo.com/?q=cnn&atb=v105-1se&t=ddg_android&ia=web
``` 
3. Kill the app
4. Start the app again
5. Tap on the first SERP result for cnn
6. Open the privacy dash and ensure that privacy practices are correct. …

Fix issue where page change not triggered when on SERP

---

app/src/androidTest/java/com/duckduckgo/app/browser/useragent/UserAgentProviderTest.kt
app/src/androidTest/java/com/duckduckgo/app/di/StubStatisticsModule.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/useragent/UserAgentProvider.kt
app/src/main/java/com/duckduckgo/app/global/device/Device.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1136878908228409
Append application to user agent following RFC and the format of other browsers.
1. Run the app
1. Search for "what is my user agent"
1. Note the Instant Answer displaying our UA shows the suffix as "DuckDuckGo/5"
1. Visit https://github.com/duckduckgo/Android and note that the mobile version of the site is showing
1. From the menu select, "Desktop Site" and note the desktop site is loaded
1. Now  search for "what is my user agent" again
1. Note that the desktop UA suffix also shows as "DuckDuckGo/5"
--- …

Append DuckDuckGo to user agent

---

app/src/androidTest/java/com/duckduckgo/app/feedback/ui/BrokenSiteViewModelTest.kt
app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/di/AppConfigurationDownloadModule.kt
app/src/main/java/com/duckduckgo/app/global/ViewModelFactory.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1137628760317279
Grafana: https://grafana.duckduckgo.com/d/sawhWhOWk/mobile-sre
Add a simple pixel to the broken site reports so we can visualize these in Grafana and add alerts should the numbers unexpectedly rise.
1. Run the app and browse to a site
1. Tap the browser settings button and select "Report Broken Site"
1. Enter "test.com" for the url and "TEST" in the comment section
1. Submit the report and ensure the "m_bsr" pixel fires, checking Kibana https://kibana.duckduckgo.com/goto/6bf29a6e1d9053c7395b9ddcf2338371
--- …

Add broken site report pixel

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/1126768040926570/1137859260897020
CC: 
Was accidentally generating WebView previews on control variant, which is erroneous and wasteful. This PR ensures that WebView previews are only generated when you have the experimental variant.
1. Breakpoint `BrowserTabFragment.generateWebViewPreviewImage()`
1. Ensure it is never called during page loads on the control group variant
---

Ensure bitmaps aren't generated on control group

---

TRANSLATIONS.md

Task/Issue URL: https://app.asana.com/0/414730916066338/1139003998368552/f
CC: 
Updates the community translation docs now that we don't use the intermediate app translations branch any longer
1. Check the documentation makes sense and renders correctly
---

Update instructions to remove references to old translations branch

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/integration/AtbIntegrationTest.kt
app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/ApiBasedPixelTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/ExperimentationVariantManagerTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/api/StatisticsRequesterJsonTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/api/StatisticsRequesterTest.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1138059002087732
Tech Design: https://app.asana.com/0/481882893211075/1139758288255945
Adds a new filterBy lambda parameter to Variant so each of them can specify conditions for them to be allocated or not.
**Doesn't filter when filter returning true added**
1. Add a variant using `filterBy = { true }`
1. Install the app notice how that variant does not get filtered out after being allocated.
**Doesn't filter when no filter added**
1. Add a variant without creating a filter
1. Install the app notice how that variant does not get filtered out after being allocated.
**Filters correctly when filter returning false added**
1. Add a variant using `filterBy = { false }`
1. Install the app notice …

Filter experimental variants

---

app/src/main/res/layout/content_feedback_negative_broken_site_feedback.xml
app/src/main/res/layout/content_feedback_open_ended_feedback.xml
app/src/main/res/values/styles.xml

Fix issue #605.  It is my understanding that hint colors cannot be changed from a `TextInputLayout`directly (since `TextInputLayout` extends `LinearLayout` and not `EditText`) unless it is sub-classed further, which seems like an unnecessary hassle.
To test this PR, verify that everything appears as intended on Dark and Light theme.
---

Fix improper floating hint text color (Issue #605)

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/1126768040926570/1140520481588209
CC: 
This fixes an issue whereby a page might be loaded in a tab (TAB A) but the callback for page loaded is fired before anything is visible, producing a blank WebView preview. This would normally be fine if the user hit the tab switcher button. But if they instead leave the app, then they might return to the app later launching another tab (TAB B). From TAB B, they could launch the tab switcher. TAB B preview would be re-generated, but TAB A would remain white.
This PR ensures the preview is generated when the user is leaving the screen altogether, and this removes the need to generate a bitmap every time the page loads.
1. Launch a tab, and browse to a …

Generate webview image when leaving BrowserActivity

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1145265836949881
https://github.com/duckduckgo/Android/pull/602 introduce a bug where the privacy grade was updated before being calculated in some instances.
1. Navigate using the browser and notice how the `?` symbol is not permanently displayed once a site has been loaded.
1. Make sure tests are not flakey and CI passes several times (usually 2 or 3 times is enough)
---

Fix privacy grade

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/TabSwitcherButton.kt
app/src/main/res/layout/view_tab_switcher_button.xml

Add "long click opens new tab" functionality to tab switcher button as per issue #607.
1. Verify that normal clicks on the tab switcher button work as intended.
2. Verify that long clicks open a new tab, with no unintended side effects.
---

Add long click opens new tab functionality to tab switcher button

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt

Task/Issue URL: https://app.asana.com/0/392891325557410/1147336208469615
CC: 
Adds a pixel for when the fire button is pressed so we can see what level of conversion there is.
1. From the browser/home screen press the fire button, check Kibana for the `mf.bp` pixel.
1. From the tab switcher press the fire button, check Kibana for the `mf.tp` pixel.
1. Check Grafana
---

add pixel for fire button pressed

---

app/src/androidTest/java/com/duckduckgo/app/CoroutineTestRule.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/global/DispatcherProvider.kt

Task/Issue URL: https://app.asana.com/0/276630244458377/1147610969828114
CC: 
Ensures `onSiteChanged()` (which contains an expensive operation) is safe to call on the main thread (or any thread).
We might want to consider making this function a `suspend` function later, but that would result in a much larger change footprint. For now, it uses `coroutines` under the hood, and introduces some changes to the way in which we make coroutine-using code more testable
- Injects dispatchers into view model instead of having them be hardcoded
- Introduces a `DispatcherProvider` interface, which is used to grab a dispatcher (or uses the `TestCoroutineDispatcher` during tests)
- Makes use of the new `runBlockingTest` from the coroutines test library
(as per advice …

Make call to `onSiteChanged` safe for any thread to call

---

app/src/main/AndroidManifest.xml
app/src/main/res/values-bg/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-da/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-el/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-hr/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-nb/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-ro/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sk/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values/strings.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1139205254334657
CC: 
Android 10 introduces some UI changes in the chooser dialog, one of those is the ability to add a description below the app's name. Right now we don't have one and when using the dialog there is a blank space below the app's name which doesn't look very good.
**Note**
The copy already existed in the app as `aboutHeading`. I had to remove the dot at the end but the translations should be the same.
1. Install DuckDuckGo on a Pixel device with Android 10 (UI will be different on a Samsung so best to check on a Pixel)
1. In the onboarding screen select "Let's do it" to trigger the dialog. If DuckDuckGo is the default option you won't see the subtitle …

Add subtitle to system dialog

---

app/src/androidTest/java/com/duckduckgo/app/statistics/ApiBasedPixelTest.kt
app/src/main/java/com/duckduckgo/app/statistics/api/PixelService.kt

Task/Issue URL: https://app.asana.com/0/inbox/608920331025313/1148562571541097/1148555304057513
CC: 
Adds `test=1` as query parameter to pixels
1. Send a pixel in `DEBUG` mode; verify `test=1` flag is added to request
---

Add devMode parameter onto PixelService requests

---

app/src/main/java/com/duckduckgo/app/global/AlertingUncaughtExceptionHandler.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1149245630738707
CC: 
With the use of `GlobalScope.launch`, we'd potentially be allowing some other code to run after this exception had been thrown, and before the uncaughtException function here had fully executed. Use of `runBlocking` to ensure execution waits for this function to complete makes more sense and it is likely to result in less unpredictable issues.
1. Trigger an exception that is otherwise uncaught, and ensure no execution continues on that thread after the exception has been thrown
---
[Technical Design Template](https://app.asana.com/0/59792373528535/18470997131194 …

For the global exception catcher, use `runBlocking` to preserve exception handling behavior

---

app/src/androidTest/java/com/duckduckgo/app/browser/navigation/WebViewBackForwardListSafeExtractorTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebNavigationState.kt
app/src/main/java/com/duckduckgo/app/browser/navigation/WebViewBackForwardListSafeExtractor.kt

- https://app.asana.com/0/0/1148502601574098
- https://app.asana.com/0/0/1148504523095289
CC: 
Adds safer handling around access to `WebView`'s `copyBackForwardList` calls
1. With no easy way to replicate this for real, you might want to hack a line into `WebViewBackForwardListSafeExtractor` which randomly throws a `NullPointerException`, and check the app handles that happening. This should be a fair test 
---

Add safer null handling around WebView copyBackForwardList calls

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebDataManager.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1147449930490345
Fixes issue where cookies are lost when app killed and ddg settings cookies are not maintained when fire pressed.
**Setup**
Get a device running the latest version of Chrome and confirm it is suffering the cookie loss issue:
1. From develop branch, visit duckduckgo.com and change the SERP theme to something different e.g Terminal
1. Press the fire button
1. Visit the SERP and note the theme is not persisted
1. Now switch to this branch ready to test
**Test DGG cookies maintained on app kill and after fire**
1. Visit the SERP and change the theme to something different e.g Terminal
1. Kill the app, launch it again
1. Visit the SERP and ensure the theme still persists
1. Press the fire button
1. Visit …

Ensure cookies are flushed and ddg cookies saved on clear

---

app/src/main/res/values-bg/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-da/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-el/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-hr/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-nb/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-ro/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sk/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values/strings.xml

Task/Issue URL: https://app.asana.com/0/1125189844152671/1152127350816673 
CC: 
In https://github.com/duckduckgo/Android/pull/622 we added a new string as an app description which read "Privacy, simplified" in order to avoid alignment issues with Android 10. Since we released that, some changes seem to have happened and we don't show "DuckDuckGo" as the app name in the system dialog anymore in Android 9 and below.
**Android 10**:
1. Launch the app on Android 10
1. Tap on Let's do It
1. Notice how DuckDuckGo should show as the app name and description in the system dialog
**Android 9**:
1. Launch the app on Android 9 or below
1. Tap on Let's do It
1. Notice how DuckDuckGo should show as the app in the system dialog
---
[Software …

Amend app description string

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/EmptyNavigationStateTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/TestNavigationState.kt
app/src/androidTest/java/com/duckduckgo/app/browser/WebNavigationStateTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/WebNavigationState.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
app/src/main/java/com/duckduckgo/app/global/view/NonDismissibleBehavior.kt
app/src/main/java/com/duckduckgo/app/survey/ui/SurveyActivity.kt
app/src/main/res/layout/activity_user_survey.xml
app/src/main/res/values/string-untranslated.xml
app/src/main/res/values/strings.xml

Task/Issue URL: https://app.asana.com/0/0/1152512237237203/f
Tech Design URL: https://app.asana.com/0/0/1151307893053517/f
CC: 
Introducing gracefully handling WebView crash errors into our Browser.
A WebView render process can be gone due to a rendering crash or memory pressure situations. When we receive such event from WebViewClient we will avoid crashing, and instead, we will show a snackbar to inform about what happened and the possibility to reload the current URL. Also, application will still be usable so users will be able to perform other actions as closing the tab or navigate to a new URL.
As we can't reproduce easily memory pressure situations or crashes, we will need to change our source code a bit in order to manually produce a crash.
Easiest way is to call …

Allow users to recover from WebView renderer failures

---

app/src/androidTest/java/com/duckduckgo/app/fire/DataClearerTimeKeeperTest.kt
app/src/main/java/com/duckduckgo/app/fire/AutomaticDataClearer.kt
app/src/main/java/com/duckduckgo/app/fire/DataClearerTimeKeeper.kt

Task/Issue URL: https://app.asana.com/0/4665784270797/1154355783227569/f
CC: 
This offers more resiliency vs `System.currentTimeMillis()` against someone meddling with the device clock in an effort to delay data being cleared when expected.
`elapsedRealtime` will start again from 0 when the system is restarted, but in that scenario, we'd wipe the data anyway since it's a new process launch, so we don't have to worry about the recorded timestamp being smaller than the current one.
ℹ️You should temporarily disable the background data clearing worker from firing for this test. (comment out `scheduleBackgroundTimerToTriggerClear(clearWhenOption.durationMilliseconds())` from `DuckDuckGoApplication`)
1. Choose automatic data clearing …

Use SystemClock.elapsedRealtime() for data clearing

---

app/src/main/res/layout/include_omnibar_toolbar.xml

CC: 
Hides the scanning view by default
**Other variants**:
1. Launch the app hardcoding the variant to `mc` and `md` and with no variant.
1. Notice how the scanning text doesn't show by default on the omnibar.
**Concept test variant**:
1. Launch the app hardcoding the variant to `me`.
1. Notice how the scanning text doesn't show by default on the omnibar but it shows as normally when the animations are triggered.
---

Hide scanning view by default

---

app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt

Task/Issue URL: https://app.asana.com/0/608920331025315/1154793601732017
CC: 
App crashes during the welcome screen if a rotation is performed at the correct time
1. Use the `me` variant.
1. On the welcome screen rotate the screen several times.
1. App should not crash.
---

Cancel animations on rotation

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTrackersAnimatorHelper.kt

Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1154851166658734/1154795110641012
CC: 
In some cases using `requireActivity()` crashes the app, we didn't expect the activity to be null at the point where its called but it can happen.
1. Navigating in the with `me` variant should still have the omnibar animation working as expected.
1. You can simulate the crash by adding `throw IllegalStateException("Test Fragment $this not attached to an activity.")`before calling to `animatorHelper.createLoadedAnimation()` in the `BrowserTabFragment`
---

Fix crash when activity is null

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/global/view/DaxDialog.kt

Task/Issue URL: https://app.asana.com/0/1154851166658740/1154845361621030
CC: 
I _think_ attempting to cancel the animations after detecting the `activity` is null is bad, and can actually be a cause of new `IllegalStateExceptions` being triggered.
1. Increase `TRACKERS_SECONDARY_DELAY` to a large value (~ 7_000L)
1. Load a webpage (e.g., cnn.com)
1. Wait for "scanning" text to appear
1. Press `back` a few times, until you have exited back to home screen
1. Wait for remainder of `TRACKERS_SECONDARY_DELAY` time to finish
1. Verify no exception thrown (in logcat)
If you try the above on `develop`, you should be able to see an `IllegalStateException` being thrown
--- …

When activity is found to be null, don't attempt further UI calls

---

app/src/main/AndroidManifest.xml

**Problem:** DDG is not able to open certain links that use html redirects.
**Steps to test this PR:**
1. First, before pulling these changes, open the YouTube app.
2. Find a YouTube video with a link in the description, or in the comments (**or use the one I have provided below [which contains a link in its description] to save time)
3. Click on the link and verify that DDG browser is **NOT** listed as an app that is capable of opening the link, or that Chrome automatically handles the link if it is the only installed app with the appropriate intent filter.
4. Pull these changes and verify that DDG **IS** now able to open links from the the description of YouTube videos via the YouTube app.
** https://youtu.be/GnrwM7vFn_U (or search by title: "Thomas The Tank Engine Theme Song")
To be …

Allow DDG to handle links from certain external applications

---

app/src/main/AndroidManifest.xml

This is a continuation of PR #659.  The issue, as well as the original solution's shortcomings, are already well-documented there, so I will skip to the testing steps.
1. Install DDG and ensure that it asks to become default browser for variants that are not "me" or "md".
2. Set DDG as default browser.
3. Visit our good friend "Thomas The Tank Engine" once again via the YouTube app (https://youtu.be/GnrwM7vFn_U).  Any YouTube video with a link in the description/comments should be fine, but I'd be lying if I said I wasn't partial to Thomas :steam_locomotive: :smirk: 
4. Confirm that the link in the video description launches, by default, using DDG.
Also, I thought that there should be a comment above the new intent filter, so I added one.  I am, …

Allow DDG to handle different MIME types

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/0/608920331025315/1157077742629569
CC: 
Catch Exception instead of RuntimeException for WebView preview. Crash reports show instances of FileNotFoundException which wouldn't be caught by the the RuntimeException catch block
1. You can force an `Exception` being thrown by hardcoding that into the `WebView` preview generator code, and verify there are no crashes as a result
---

Catch Exception instead of RuntimeException for WebView preview

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
app/src/main/res/values/string-untranslated.xml

Task/Issue URL: https://app.asana.com/0/72649045549333/1157213430036874
CC: 
Minor bugs and amends to the new onboarding experience.
Use the `me` variant.
**Longer delay to welcome message**
https://app.asana.com/0/1125189844152671/1157012774769366
1. After a clean install launch the app.
1. Notice how the "Welcome to DuckDuckGo" message stays longer than before.
**Trackers blocked copy changed**
https://app.asana.com/0/1125189844152671/1157012774769367
1. After a clean install launch the app.
1. Navigate to cnn.com
1. Notice how the trackers blocked copy has changed to the one in https://app.asana.com/0/1125189844152671/1157012774769367
**Trackers blocked bug**
https://app.asana.com/0/1125189844152671/1157012774769368
1. After …

New onboarding tweaks and bug fixes

---

app/src/androidTest/java/com/duckduckgo/app/ValueCaptorObserver.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt

Task/Issue URL: https://app.asana.com/0/0/1154748750174826/f
Tech Design URL: https://app.asana.com/0/0/1157240085321108/f
CC: 
These changes allow us to rely on `browserShowing` property instead of using hardcoded boolean values and only call refresCta when a tab is visible to the user.
1. Keeps all the previous behavior described on how to test https://github.com/duckduckgo/Android/pull/651
---

Better handling of browser state to obtain a Cta

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingPageManager.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPage.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModel.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1158110040574203
Adds CTA retention experiments to help up determine effectiveness of CTAa
**Check CTAs are shown for control:**
1. Open VariantManager.kt and comment out all variants other than `mq` control
1. Run a fresh installation of the app and launch it to the welcome screen
1. Ensure the `m_odb_v` pixel has NOT fired yet
1. Press `Continue`
1. Ensure the the `Make DuckDuckGo Your Default` onboarding is shown and the `m_odb_v` pixel now fires
1. Select `Maybe later` to get to the home screen
1. Ensure the widget CTA shows
**Check that only widget CTA is shown on high end device and triggers correct pixels when default browser CTA feature is suppressed:**
1. Open …

Add CTA experiments

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1154748750174828 and https://app.asana.com/0/1125189844152671/1154586839765577
Tech Design URL: https://app.asana.com/0/1125189844152671/1158928566141337
CC: 
We used to have one Cta interface that dealt with the creation of a view cta and a dialog cta making it complicated to understand what method should be used for each of them plus they were very specific to a concrete type. This PR changes that to include two new interfaces depending on the cta type. 
It also fixes the issue when more than one dialog cta could be displayed at the same time.
**Concept test**
1. Using variant `me`
1. Launch the app and navigate to get the different CTAs
**Normal CTAs**
1. Using variant `mc`
1. Launch …

Cta new interfaces

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1159930185369809/f
This fixes some crashes when trying to commit a Fragment transaction when the activity is destroyed.
Additionally, I'm removing also a reference to the `currentFragment` when activity is destroyed as this is causing a leak.
**How to reproduce the crash**
In order to reproduce the crash, we need to hardcode a `delay` in our code and enable activities being killed. Also, we need to use current `develop` branch.
- Developer settings -> enable don't keep activities
- In code ->
```
fun openMessageInNewTab(message: Message) {
launch {
val tabId = viewModel.onNewTabRequested()
delay(5000)
val fragment = openNewTab(tabId, null, false)
fragment.messageFromPreviousTab = message
} …
```

Fix: cancel coroutine when activity gets destroyed

---

app/src/androidTest/java/com/duckduckgo/app/referral/QueryParamReferrerParserTest.kt
app/src/main/java/com/duckduckgo/app/di/PlayStoreReferralModule.kt
app/src/main/java/com/duckduckgo/app/referral/AppInstallationReferrerParser.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/inbox/608920331025313/1154468535608530/1160451607351813
CC: 
Removes unused pixels and now redundant logic for capturing an app installation referrer type
1. Uninstall production app
1. Enable Play Store internal app sharing (more info: https://app.asana.com/0/414730916066338/1138191120120193)
1. Install app using [ATB Override](https://play.google.com/apps/test/RQl8L2Oq05Y/ahAAvZMmiYl6uhEW6GBQ885xne4f8IdOGBuJwU-Ur0q9hluCKfctwCtXB-1T3AsShS8VxAXYieOu80gsEkRyHGxT0w?&referrer=utm_source%3Dgoogle%26utm_medium%3Dcpc%26anid%3Dadmob%26utm_campaign%3DDDGRAXX)
1. Verify variant is set to `XX` (look for logcat message for variant)
1. Uninstall app
1. Install app using [No ATB …

Remove unused app referrer logic

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/global/view/DaxDialog.kt
app/src/main/res/layout/content_dax_dialog.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

Task/Issue URL: https://app.asana.com/0/0/1162132608576977/f
CC: https://app.asana.com/0/0/1158941144031452/f
This PR is some preparation work that will be related (and be used) in a future task, where we will implement new Ctas with two buttons. 
For context: To show our CTAs as Dax dialogs we will make use of a Dax dialog with two buttons. Usually, the secondary button will be used to dismiss the dialog.
Design can be found here: https://app.asana.com/0/0/1158941144031452/f
Within the scope of this PR, you will find the following changes:
* Refactor current DaxDialog to handle a new secondary button
* Decoupling view-highlighting related logic from simple Dax dialogs into a more concrete dialog.
* Changes in UI according to new design
* Enable sending …

Dax dialog with two buttons

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/onboarding/ui/OnboardingPageManagerTest.kt
app/src/androidTest/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/global/Theming.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingPageManager.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModel.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/0/1162228349959213/f
CC: 
- Introducing a new variant to control displaying Ctas as Dax dialogs during Dax journey.
- According to https://app.asana.com/0/72649045549333/1161278038072568/f, the new control group will be the concept test without any Ctas.
- Additionally, removing theme-variant logic to avoid allocating users into any variant before referrer logic is executed. This will avoid overriding an initial variant if the installation comes from an ad campaign.
1. 
1. 
---

New variant: Showing DefaultBrowserCta and SearchWidgetCta as Dax dialogs

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTrackersAnimatorHelper.kt
app/src/main/res/layout/include_omnibar_toolbar.xml
app/src/main/res/values/string-untranslated.xml

Task/Issue URL: https://app.asana.com/0/72649045549333/1157213430036875
CC: 
This PR removes the "Scanning" part of the new URL animation. I have removed all the code related to that animation and took the opportunity to rename some methods and variables to make them more meaningful. I did also adjust the animation timings to make them a little bit quicker while still giving the results we want (i.e. returning trackers, etc).
1. Use a variant that has the concept test feature, `mv` would do.
1. Go to cnn.com and notice how the "Scanning" animation doesn't exist anymore but we still have the trackers blocked animation.
1. Go to SERP and notice how the "Scanning" animation is gone and since we do not detect trackers there are no …

Remove scanning animation

---

.github/CODEOWNERS

Task/Issue URL: https://app.asana.com/0/0/1160050773844673/f
CC: 
Adding @cmonfortep and @malmstein as codeowners.
1. Open a PR
1. Ensure new ducks are added as reviewers
---

Add David and Cristian to codeowners file

---

app/src/main/res/values-v27/themes.xml
app/src/main/res/values/colors.xml

Task/Issue URL: https://app.asana.com/0/1157893581871903/1162814661890319
When the user selected Light Mode, the navigation bar was still showed in Dark. This PR fixes that.
Fixes: https://github.com/duckduckgo/Android/issues/695
1. Open current app in Google Play
2. Open Settings and select Light Theme
3. Check that Navigation bar is shown in Dark
Building this branch
1. Open app
2. Open Settings and select Light Theme
3. Check that Navigation bar is shown in Light
**Screenshots**:
| Before | After |

light theme will now use light navigation bar

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelNextCtaTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/0/1163707393081881/f
CC: https://app.asana.com/0/0/1163228561849713/f
>_VariantManager changes_
Moving as a control group a variant with concept test + Ctas.
Dropping variant only showing concept test.
>_SearchWidget cta changes_
Only show search widget Cta if the user has seen at least on nonSerp Cta.
>_VariantManager changes_
**Concept test variant ml: Concept test with old ctas**
1. Hardcode into variantManager variant **"ml"**
1. Perform a fresh install
1. Run the app and ensure during the onboarding Default browser cta appears
1. Visit a web with trackers like cnn.com
1. Ensure dax dialog appears informing about trackers found
1. Click on "High five!"
1. Ensure no more Ctas are shown
1. Visit duckduckgo.com
1. Ensure dax …

New control group and changes on when to show search widget cta

---

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1165064320902505/f
CC: https://app.asana.com/0/0/1163921857441241/f
Enable variants SC and SE as they are going to be used in project https://app.asana.com/0/0/1135937698028536
> SC variant
1. Hardcode variant "sc"
1. Fresh install
1. open the app and navigate to Browser screen
1. perform a search
1. Ensure from the logs that duckduckgo url contains "sc" as part of atb
> SC variant
1. Hardcode variant "se"
1. Fresh install
1. open the app and navigate to Browser screen
1. perform a search
1. Ensure from the logs that duckduckgo url contains "se" as part of atb
--- …

Enable [se,sc] variants

---

app/src/main/res/layout/popup_window_browser_menu.xml

When in landscape or split-screen mode, the `ScrollView` in the overflow menu clips into the `LinearLayout` header.  This is fixed by adding `app:layout_constrainedHeight="true"` to the `ScrollView`.  I also added `app:layout_constraintTop_toTopOf="parent"` to the `LinearLayout`, which really isn't necessary since we want it up top anyway, but it suppresses an Android Studio warning about not having vertical constraints on the LL and is more explicit than using the possibly ambiguous `tools:ignore="MissingConstraints"`. See GIF below.
1. Ensure that the overflow menu is properly rendered and that all hitboxes work as intended in both landscape and portrait mode.
--- …

Prevent elements in overflow menu from overlapping

---

app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherAdapter.kt

**Description:** Image previews for tabs can load incorrectly due to uncleared pending requests from recycling for instances when `loadTabPreviewImage(...)` returns without calling `glide.into(...)`.
**Relevant Documentation:** https://bumptech.github.io/glide/doc/getting-started.html - Read the part titled "ListView and RecyclerView" which states:
> By calling clear() or into(View) on the View, you’re cancelling the load and guaranteeing that Glide will not change the contents of the view after the call completes. If you forget to call clear() and don’t start a new load, the load you started into the same View for a previous position may complete after you set your special Drawable and change the contents of the View to an old image.
**Steps to reproduce:**
There are many ways to …

Prevent incorrect tab image previews from loading

---

app/src/androidTest/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1163849208167805/f
Fix issue where view state would update and delete space from user query
1. Install the app and add the widget to your home screen
1. Tap the widget to launch the interstitial search screen
1. Type a few words really fast and check that the spaces are not being deleted.
---

Fix space deletion from user query

---

app/src/main/res/values-pt/strings.xml

CC: N/A
The word anonymous in Portuguese is: anônimo and NOT anónimo.
1. Change your device language to Portuguese, in order to see the app in Portuguese
2. Open App
3. Select Definições ( Settings ) 
4. Select Deixar comentários ( Leave Feedback )
5. Look at the message on the bottom of the screen

Fix typo in Portuguese translation

---

app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPage.kt

CC: 
This PR fixes an issue in the onboarding default browser screen where the toast message shown is not aligned with the instructions card.
1. Launch the app and navigate to the default browser screen.
1. Click let's do it and notice how the toast and the instructions card are aligned.
1. Dismiss the default browser popup.
1. Press the back button to go back to the first onboarding screen.
1. Styles have been applied and the status bar is not white.
---

Fix onboarding style

---

app/src/main/res/layout-land/content_onboarding_welcome.xml
app/src/main/res/layout/content_dax_dialog.xml
app/src/main/res/layout/content_onboarding_welcome.xml
app/src/main/res/layout/include_new_browser_tab.xml

Task/Issue URL: https://app.asana.com/0/0/1169355936992923/f
Tech Design URL: https://app.asana.com/0/0/1169315285491563/f
CC: 
When making the new onboarding and Dax dialogs the new default experience, we noticed that the UI for some big screens (specially tablets) could be improved. To avoid delaying the release, we decided just to introduce a few quick improvements. Those include:
- introducing a max width of 600dp for all devices
- centering the dialog
**Onboarding dialog**
**Intro dialog:**
**Dax dialog:**
1. Fresh install on a big screen device -> use a tablet
1. Ensure this first dialog during the onboarding process is shown as the attached image
1. Navigate to the browser screen
1. Ensure intro dialog is shown as the attached image (test …

Android: Dax Dialogs - quick improvements on big screens

---

app/src/androidTest/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt

Task/Issue URL: https://app.asana.com/0/0/1169575807989121/f
CC: 
This crash happens because init block inside ViewModel will initialise two viewStates: Onboarding and Results.
OnboardingViewState now needs some info from the database in order to be initialised, and ResultsViewState will initialise after OnboardingViewState.
If the database produces any delay (maybe because migration or just thread suspends), user might be able to submit a query before ViewStates are initialised, producing a nullPointer exception.
**Fix**
Initialise ResultsViewState out of the coroutine used to initialise OnboardingViewState.
> To reproduce the crash:
1. Hardcode the following code inside `SystemSearchViewModel.resetViewState()`
``` …
```

Fix: initialise ResultViewState before user submits a new query

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTrackersAnimatorHelper.kt
app/src/main/java/com/duckduckgo/app/global/view/DaxDialog.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1170001449666321
CC: 
In some cases when the trackers blocked CTA is shown it could lead to a crash when the tracker blocked animation finishes if some of the views have been killed and not longer exist.
**App crashes**
1. In the developer options set `Don't keep activities` to true.
1. Launch the existing app from develop.
1. Navigate to cnn.com and wait until the trackers blocked CTA is shown.
1. Send the app to the background and see a crash.
**App does not crash**
1. In the developer options set `Don't keep activities` to true.
1. Launch the app from this branch.
1. Navigate to cnn.com and wait until the trackers blocked CTA is shown.
1. Send the app to the background …

Animator helper crash

---

app/src/main/res/drawable/onboarding_primary_cta_button_rounded_bg.xml
app/src/main/res/drawable/onboarding_secondary_cta_button_rounded_bg.xml
app/src/main/res/values/styles.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1170298171161577/f
CC: 
The new Onboarding experience shows buttons that have a wrong pressed state.
**Before** 
**After**
1. Fresh install
1. Go to default browser screen
1. Ensure ripple effect gets rendered inside background button
Test this on different API levels.
---

Fix pressed state in buttons that appear in the Onboarding

---

app/src/androidTest/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
app/src/main/java/com/duckduckgo/app/systemsearch/DeviceAppLookup.kt
app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchActivity.kt
app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt

**Task/Issue URL:**
- https://app.asana.com/0/488551667048375/1161178882056507
- https://app.asana.com/0/488551667048375/1170451534984707
* Coordinate timing so interstitial results drop in smoothly together rather than shifting items on screen
* Update the list order to prefer items that start with search query, then alphabetically
* Remove circular updates between the omnibar and ViewModel to improve text input experience.
**Test Interstitial Results**
1. Install a fresh version of the app and add the widget to your home screen (it is recommended that other versions are uninstalled first as it is really easy to add the wrong widget)
1. Tap the widget to launch the interstitial screen
1. Enter a query for example "Pl" notice that the …

Interstitial search screen tweaks

---

app/src/main/AndroidManifest.xml

Task/Issue URL: https://app.asana.com/0/715106103902962/1171807866325827
CC: 
Adds `android.permission.REQUEST_INSTALL_PACKAGES` so that our app can download APKs on Android Oreo and newer
**On >= Android Oreo device**
1. Download an APK (e.g., Visit github.com/duckduckgo/android/releases, click on an APK from the assets)
2. Wait for download to complete
3. Click on the notification for the downloaded file; verify the system offers to take the user to settings to let you enable installing from our DDG app
4. Verify the app installs correctly
If you try repeating the above from `develop` instead of this feature branch, you'll note that you can't install any APK you downloaded from our app.
**On < Android Oreo device**
1. Verify …

Add REQUEST_INSTALL_PACKAGES permission to help improve browser parity

---

app/src/main/java/com/duckduckgo/app/global/AlertingUncaughtExceptionHandler.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1172194044332907
CC: 
This might be a temporary change for beta only; need to put this out to get more insight into elevated crashes in 5.52.1 which is a beta-only release. It's currently unclear if the use of runBlocking in this handler is causing an issue, or covering up another issue.
---

Change uncaught exception handling not to use runBlocking

---

app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1172307373191458
CC: 
After updating the app dependencies to newest versions of all libraries, we noticed an increase in UndeliverablExceptions. This, it seems, is most likely caused by our sync job being interrupted, so we in turn dispose of the RxJava subscription. However in cases where the networking capabilities have just dropped (a potential cause of the sync job being stopped) we would then get a bunch of IO-related exceptions being called and since we'd already disposed, RxJava would have nowhere to deliver the exception to, hence it would throw an UndeliverableException.
This UndeliverableException wouldn't be caught by a custom RxJava global error handler (as we don't set one) so it would …

Add global RxJava error handler to look for UndeliverableExceptions

---

app/src/main/java/com/duckduckgo/app/global/AlertingUncaughtExceptionHandler.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1172356004360461
CC: 
Adds `InterruptedIOException` and `InterruptedException` to the list that we don't want to crash the app on. These exceptions were observed to be happening in the 5.22.3 release. These are essentially the ones signalling that there was an internet issue or that the sync job was instructed to stop mid way through; they aren't real exceptions that should cause the app to stop.
1. Similar to https://github.com/duckduckgo/Android/pull/787, it's hard to replicate. But I found I could replicate by making the `TrackerDataDownloader` do lots of extra work, and killing the wifi off while it's looping. e.g., 👇
```
for (i in 0..100) {
Timber.i("Running TDS …
```

InterruptedException and IOException now excluded exceptions to alert on

---

app/src/main/res/layout/edit_bookmark.xml
app/src/main/res/layout/http_authentication.xml
app/src/main/res/values/themes.xml

Task/Issue URL: https://app.asana.com/0/1157893581871903/1172335675952700
The changes in Android Release 5.52.1 (Beta) have somehow messed up with the theming in the Edit Bookmark dialog. This PR fixes that.
**Screenshots**:
| Before | After SDK 21 | After SDK > 23 |
| ------ | ----- | ----- | 
1. Open app
2. Add a Bookmark
3. Tap on Edit

Fix Edit Bookmark and Authentication dialog theming

---

app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1172723636495153/f
CC: 
After updating to the latest version of material library `com.google.android.material`, seems like the color used for the action on snackbars is not `colorAccent` anymore. Even if the documentation says the opposite. 
Develop:
Fix:
1. Open the app
1. Visit any site
1. Bookmark
1. Ensure snackbar action color is blue
---

Snackbar action button color using accent color

---

app/src/androidTest/java/com/duckduckgo/app/global/AlertingUncaughtExceptionHandlerTest.kt
app/src/main/java/com/duckduckgo/app/global/AlertingUncaughtExceptionHandler.kt
app/src/main/java/com/duckduckgo/app/global/exception/UncaughtExceptionModule.kt

Task/Issue URL: https://app.asana.com/0/608920331025315/1173206265028385
CC: 
Add `try/catch` to uncaught exception handler. We've observed scenarios where the exception handling can itself throw an exception which would cause an infinite loop.
1. Throw exception from the uncaught exception handler
---

add catch to exception handler

---

app/schemas/com.duckduckgo.app.global.db.AppDatabase/19.json
app/src/androidTest/java/com/duckduckgo/app/global/db/AppDatabaseTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/exception/UncaughtExceptionDaoTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/api/OfflinePixelSenderTest.kt
app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
app/src/main/java/com/duckduckgo/app/global/exception/UncaughtExceptionEntity.kt
app/src/main/java/com/duckduckgo/app/statistics/api/OfflinePixelSender.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1172744955314993
CC: 
This PR adds two new fields to the UncaughtException table (version and timestamp).
**Update from previous version**:
1. Build the app from `develop`.
1. Create a crash.
1. Without re-launching the app again build the app from this branch.
1. Make sure the UncaughtException table is empty.
1. Make sure the previous crash recorder is not sent (filter the log by `Sent pixel with params:`)
**Crash on new version**
1. Launch the app and create a crash.
1. Without re-launching the app make sure the UncaughtException table has the exception recorded including the timestamp and version.
1. Re-launch the app.
1. Make sure the pixel is sent …

Add version and timestamp to crashes

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1174383396125025
CC: 
I forgot to remove an extra filtering bit from the `CtaViewModel`, since the prevalence value has changed this is now affecting the trackers blocked dialog which is not showing anymore.
1. In develop, open cnn.com and notice how the trackers blocked dialog is not showing but the user can see logos being blocked.
1. In this branch go to cnn.com and notice how the trackers blocked dialog does now show.
---

Blocked Trackers dialog is not showing

---

app/src/main/res/drawable/privacygrade_icon_small_a.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1173797528771833/f
CC: 
Reported issue: https://github.com/duckduckgo/Android/issues/802
When showing enhanced grade 'A' in Privacy Dashboard, letter gets rendered out of view bounds. 
| Before | After |
| - | - |
| Before | After |
<image src="https://user-images.githubusercontent.com/4747865/81266064-667f0e00-9044-11ea-8c86-680f99ad8b84.png" width="300px"/>|<image src="https://user-images.githubusercontent.com/4747865/81266133-86aecd00-9044-11ea-824e-a66372a30c08.png" width="360px"/>|
1. Visit github.com
1. Access privacy dashboard
1. Ensure A privacy grade is displayed correctly
---
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/19906486582255 …

Fix: Enhanced grade 'A' not shown correctly in Privacy Dashboard

---

app/src/main/res/layout/activity_user_survey.xml

Hi,
I found there is a issue in activity_user_survey.xml, you did not set `android:indeterminateTintMode="src_in"`, which can cause inconsistent color of ProgressBar in API Level 21. This pull request help you fix it.
Thanks and wish the information is useful for you.

Fix issue in activity_user_survey.xml

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Issue URL: #686
**Steps to test this PR:**
1.Navigate to Find in page
2.Click on back button on browser

Pressing back after dismissing keyboard in find in page close find in page view

---

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/715106103902962/1175100132980404
In preparation for the new SERP header features we want to add the new variants that represent them.
The experiment definition can be found [here](https://app.asana.com/0/1157893581871903/1174053487728482)
There are no visual identifications of the feature, but the `VariantManagerTest` hast the tests that verify the new variants.
---

added variants for serp header experiments

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1176838543253371 
CC: 
There are two bugs related with the new privacy grade animation.
**Grade does not show in SERP**
In some cases we get notified twice about the progress reaching 100, when this happens the state of the privacy changes to be hidden.
1. Go to cnn.com, animation happens as usual.
1. Go to SERP, you can briefly see the grade and then it disappears.
**Grade shows during the animation for a brief time**
In some cases while navigating to a different page you can see the old grade showing up during the animation for a split second. This happens because the privacy state returns shouldAnimate as true and showEmptyGrade as false, showEmptyGrade takes precedence and hides the grade.
1. Go …

Fix privacy grade bugs

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTrackersAnimatorHelper.kt

Task/Issue URL: https://app.asana.com/0/392891325557410/1179212544274947
CC: 
Sorts the icons to show so that vowels are at the end of the list to avoid dodgy words being spelled.
1. Visit imgur.com - the tracker icons that appear should spell GYA (A might be Amazon's logo)
1. Browse a few other sites and confirm no breakage
---

sort vowels to the end of the trackers animation to avoid dodgy words

---

app/src/main/java/com/duckduckgo/app/global/view/FireDialog.kt
app/src/main/res/values-v27/themes.xml
app/src/main/res/values/styles.xml

Resolves [#754 ](https://github.com/duckduckgo/Android/issues/754)
* Added style to `FireDialog`, and override some properties in order to fix this issue :)
1. `windowIsFloating` as `true`
2. `navigationBarColor` as `?toolbarBgColor` (light/dark theme)
3. `statusBarColor` as `@android:color/transparent`
**Tested on:**
- Pixel XL api 29 emulator
- Pixel 3XL api 29 emulator
- Pixel 3a XL api 29 device
Old  |  New
:-------------------------:|:-------------------------:
**Live preview**
---

Add FireDialog theme in order to fix navigation buttons hiden on some devices

---

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/inbox/1157893581871899/1182447818353798/1181690429267188
**Description**
We've reached sample size, therefore this feature can now be removed
1. Launch the app twice.
1. Kill the app and wait ~10 seconds
1. The usual privacy notification should show
1. Tap the notification
1. After ~10 seconds the clear data notification should show
---

Deactivate experiment: Android: Test notification drip campaign with inactive users

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1182605057307457
As part of Test improvements to the double search header we added a new pixel because. We should have only added this for the SERP Header Removal Experiment Variant, but it was enabled for all experiments.
Objective
Fix this, so the Pixel is only fired in this variant
*SERP Header Removal Variant*
1. Enable variant zi
2. Open the app
3. Type a query in the native toolbar
4. Check that pixel rq_1 has been fired
5. Type the same query again
6. Check that the pixel rq_0 has been fired  
*Control group*
1. Enable variant zg
2. Open the app
3. Type a query in the native toolbar
4. Check that pixel rq_1 has not been fired
5. Type the same query again
6. Check that the pixel rq_0 …

Rq Pixel should only be fired in SERP Header removal experiment

---

app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1183093181516711
CC: 
App crashes when unregistering twice on application stopped. We don't really need to unregister here because it is done when the app gets killed anyways as per the documentation `If you register with the Application context, you receive broadcasts as long as the app is running.`
**Reproduce the crash**
1. Add another `unregisterReceiver(shortcutReceiver)` below the one that already exists in the `DuckDuckGoApplication` (line 317).
1. Launch the app and close it, you should see the crash in the logcat.
**Make sure the toast doesn't crash the app when is taken to the background by an OEM**
@CDRussell might be able to help with this one. This is an edge …

Don't unregister shortcut receiver

---

app/src/main/res/values-es/strings.xml

CC: 
First time doing a fork/pull request in Github, so figure I pick something super easy!
"Si" can mean "if" or the musical note "B" in Spanish, but it needs an accent if written out to specify as "yes."
Added accent in edit.
1. No test needed
---

Spanish translation - Changing "Si" to "Sí" with correct accent

---

app/src/main/res/values/styles.xml

Tech Design URL: https://github.com/duckduckgo/Android/issues/687
CC: 
1. go to feedback form
1. type something
1. see cursor appearing
---

duckduckgo#687 make cursor in feedback edit text visible

---

app/src/main/java/com/duckduckgo/app/browser/useragent/UserAgentProvider.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1183556013880866
tirerack.com no longer loads mobile site by default on some devices, it instead loads the desktop site. 
1. Using a Pixel API 29 device or emulator and launch our app
1. Visit tirerack.com
1. Note that the mobile rather than desktop page loads
---

Add ua application exclusion for tirerack to allow mobile site detection

---

app/schemas/com.duckduckgo.app.global.db.AppDatabase/23.json
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/shortcut/ShortcutReceiverTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/db/AppDatabaseTest.kt
app/src/androidTest/java/com/duckduckgo/app/notification/AndroidNotificationSchedulerTest.kt
app/src/androidTest/java/com/duckduckgo/app/notification/model/UseOurAppNotificationTest.kt
app/src/androidTest/java/com/duckduckgo/app/onboarding/store/AppUserStageStoreTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/androidTest/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/shortcut/ShortcutBuilder.kt
app/src/main/java/com/duckduckgo/app/browser/shortcut/ShortcutReceiver.kt
app/src/main/java/com/duckduckgo/app/di/DatabaseModule.kt
app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/global/ViewModelFactory.kt
app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
app/src/main/java/com/duckduckgo/app/global/useourapp/UseOurAppDetector.kt
app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
app/src/main/java/com/duckduckgo/app/notification/model/UseOurAppNotification.kt
app/src/main/java/com/duckduckgo/app/onboarding/store/UserStageStore.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1186436893520548
CC: 
This PR prepares the in app usage flow for the second experiment, includes:
1. New variants.
1. Removes the migration to move old user into the new in app flow.
1. New pixel when a user visits the use our app URL before the initial notification.
1. Removes CTA checks before firing some pixels to be consistent with the control group.
1. Removes day 1 and 3 notifications and onboarding on day 3 in 2 of the new variants.
1. When opening a shortcut we now try to match the domain rather than the full URL only for use our app URLs.
1. Sets to 0 weight on old variants.
1. Removes code around old notifications used on a previous experiment for more readability purposes.
**Before …

In app usage flows now only applies to new users under a new variant.

---

app/schemas/com.duckduckgo.app.global.db.AppDatabase/24.json
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt
app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabEntitiy.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1187653972293689/f
CC: 
Tries to fix the following issue:
Current behavior:
- User clicks on a link from tab A
- New tab is opened (Tab B)
- User presses back
- Home page shown (in Tab B)
- User presses back again (in Tab B)
- App is closed
Expected behavior:
- User clicks on a link from tab A
- New tab is opened (Tab B)
- User presses back (Tab B)
- Tab B closed
- Tab A opened
**Related open issues:**
https://github.com/duckduckgo/Android/issues/815
https://github.com/duckduckgo/Android/issues/696
Test: Open link on a new tab
1. Open the app
1. Perform a search or visit any website (Tab A)
1. long press on a link
1. open on a new tab (Tab B)
1. ensure new tab is opened …

Back navigation to previous tab

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/DownloadConfirmationFragment.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewLongPressHandler.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/browser/downloader/DataUriDownloader.kt
app/src/main/java/com/duckduckgo/app/browser/downloader/FileDownloader.kt
app/src/main/java/com/duckduckgo/app/browser/downloader/NetworkFileDownloader.kt
app/src/main/java/com/duckduckgo/app/global/ViewModelFactory.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1187803392412385/f
CC: 
We saw crash instances when a user attempts to save a data URI. This PR fixes that, and has a few related improvements to that area
- Simplifies the `DownloadConfirmationFragment`
- Previously it was responsible for asking what the user wanted to do, as well as handling the response and trying to delete files, trigger the download etc...
- Now it is just responsible for passing the user's choice back to the parent fragment
- Removed a leak with this dialog
- Limits the title length for the long press menu. An exceedingly long data URI could trigger an ANR as we were trying to populate a `TextView` with potentially megabytes of data (and the UI already capped what it could …

Fix crash that could happen when trying to download a large data URI image

---

app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt

- Do not abort nestedScroll
- Enable swipe to refresh only when no vertical nestedOffset is indicated
Fixes #900
See #900 linked websites
While this fixes the issue it's not pretty unfortunately. I observed the following behavior with Chrome, but not quite sure how to implement it:
1. Swipe refresh enabled on load
2. User swipes down -> Swipe refresh disabled
3. User swipes up and triggers the overscroll animation (swipe refresh still disabled)
a) If user swipes up again while the overscroll animation is active -> Swipe refresh stays disabled
or
b) Overscroll animation finishes -> Swipe refresh enabled

Fixes swipe to refresh triggers early when address bar is hidden

---

app/src/androidTest/java/com/duckduckgo/app/browser/downloader/UriUtilsFilenameExtractorTest.kt
app/src/main/java/com/duckduckgo/app/browser/DownloadConfirmationFragment.kt
app/src/main/java/com/duckduckgo/app/browser/downloader/FileDownloader.kt
app/src/main/java/com/duckduckgo/app/browser/downloader/FilenameExtractor.kt
app/src/main/java/com/duckduckgo/app/browser/downloader/NetworkFileDownloader.kt

Task/Issue URL: https://app.asana.com/0/0/1187737416677993/f
CC: 
When trying to download images, our app currently tries to guess what a good filename for the download will be, and often fails to produce something nice; it'll often end in a .*bin file type as its current implementation is somewhat naive in turning a URL into a filename.
This PR improves that situation by walking back the URL path, trying each to make a filename, and then returning the best filename produced. Worst case, this should produce the same result as the old algorithm, but best case it will pick out a much better filename.
1. Visit https://vignette3.wikia.nocookie.net/guns/images/b/b1/FHJ84.jpg/revision/latest?cb=20160824141549 and long press to …

Improve algorithm to generate a filename from an image download

---

app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
app/src/main/res/values/string-untranslated.xml
app/src/main/res/values/strings.xml

Task/Issue URL: https://app.asana.com/0/1125189844152671/1187357199382446
CC: 
This PR updates the English copy for the network Dax dialog. The translations are delayed and in the meantime we prefer to do this only in English. Because the copy is different from the previous one we have to check in the CTA if the locale is English to apply the correct substitutions.
**New copy** 
_Heads up! Since Facebook owns instagram.com, I can't stop them from seeing your activity here.
But browse with me, and I can reduce what Facebook knows about you overall by blocking their trackers on lots of other sites._
1. Launch the app in English.
1. Go to `instagram.com`
1. New copy should be shown 
**Non-English**:
1. Re-install and launch the …

Update network Dax dialog copy

---

app/build.gradle
app/src/androidTest/java/com/duckduckgo/app/browser/filechooser/FileChooserIntentBuilderTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/logindetection/NextPageLoginDetectionTest.kt
app/src/androidTest/java/com/duckduckgo/app/di/StubJobSchedulerModule.kt
app/src/androidTest/java/com/duckduckgo/app/fire/RemoveCookiesTest.kt
app/src/androidTest/java/com/duckduckgo/app/icon/ui/ChangeIconViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/ui/ScorecardViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/logindetection/NavigationAwareLoginDetector.kt
app/src/main/java/com/duckduckgo/app/global/view/StringHtmlExtension.kt
app/src/main/java/com/duckduckgo/app/notification/NotificationHandlerService.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1187618988784913/f
CC: 
Bumping the target and compile SDK versions resulted in some compilation errors, mostly around stricter nullability checks. 
There is the possibility of a subtle problem being introduced anywhere though, so need to verify the whole app is still working as expected. 
---

Update tooling to targetSdkVersion 29 and compileSdkVersion 29

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1186457042345566/f
CC: 
This PR tries to fix some weird behavior we detected in some emulators that lately has been reported by some users: https://github.com/duckduckgo/Android/issues/919
The issue might be related to injecting javascript on a paused webview. We will add an additional check to avoid adding javascript if user is in home screen.
The problem seems possible to be reproduced if using a pixel 2 api 29 emulator:
1. Open the app
1. Open a new tab
1. Perform a search
1. The site will not load, instead, it appears a blank page
Using this branch, the site will load correctly.
---
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/1990648658225 …

Avoid injecting javascript on paused webview

---

app/src/main/java/com/duckduckgo/app/fire/DuckDuckGoCookieManager.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1192531917430354
CC: 
This PR adds a comment to explain why we preserve DuckDuckGo cookies when using the fire button.
---

Add comment to explain why we preserve DuckDuckGo cookies

---

app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/global/AppUrl.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1177278105868185
CC: 
In Chromium 84 a change was introduce to add SameSite cookies. This triggered a change in the frontend to always set the secure flag whenever the protocol is https. 
Because of that change we are not able to fetch DDG settings cookies anymore and preserve them.
If possible test with different Chromium versions. We know we can't fetch secure cookies on older Chromium versions, i.e. 57 but it should work on newer ones (i.e. 80, 81, 82...)
1. Go to SERP.
1. Change the theme to dark.
1. Use the fire button.
1. Go back to SERP.
1. Dark theme should still be applied.
---
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/1990648658225 …

Add schema to host when retrieving and storing cookies

---

app/src/main/java/com/duckduckgo/app/httpsupgrade/HttpsUpgrader.kt

Task/Issue URL: https://app.asana.com/0/361428290920652/1195088920676367
Don't send https upgrade service pixels when local filter is reloading as doing so inflates service percentage when in reality the item may exist in local filter. This is a temporary change to get better percentages, a PR to remove service altogether is already implemented on another branch and will be released soon.
**TEST ONE: Service pixel fires when local filter loaded**
1. Run the app give it a few seconds to let everything load (if it's a fresh install allow it to download all the config)
1. Make up a super long random url that won't be in the https upgrade list e.g `http://abclksdfhsdjfadhsjfgakfgdshfgdshjfgdsfdfdsfgjfgdsjfgf.com`
1. Note from the console that a …

Don't send https update service pixels when local filter is reloading.

---

app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1197140896017476
CC: 
A while ago in https://github.com/duckduckgo/Android/pull/907 we added an if/else statement while waiting for translations. However in https://github.com/duckduckgo/Android/pull/929 we never removed that if/else statement and the substitutions in one dialog are wrong.
1. Change the language of your phone to Spanish.
1. Install the app and go to `instagram.com`
1. The copy should say `Facebook es el dueño de instagram.com` where before it was saying `instagram.com es el dueño de Facebook`
--- …

Fix copy substitutions in other languages

---

app/src/androidTest/java/com/duckduckgo/app/global/db/AppDatabaseTest.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1182726235746673
CC: 
We have historically used the database() function to validate some migrations, however that function executes all the migrations to the latest schema version which invalidates any intermediate steps.
We deprecated that method a while ago and this PR removes all of its usages.
1. Run the App Database Tests
1. Tests pass
---

Remove deprecated method from database tests

---

app/src/main/res/layout/view_tab_switcher_button.xml

Task/Issue URL: https://github.com/duckduckgo/Android/issues/961
CC: 
Switcher button is not visible on RTL language
1. Use RTL language or RTL developer mode.
2. Run app and try to open new tab.
3. The switcher button Is not visible.
**Overview**:
Before changes toolbar layout:
After changes toolbar layout:
Layout inspector:

Fixed toolbar issue with RTL #961

---

app/src/main/AndroidManifest.xml

Task/Issue URL: https://github.com/duckduckgo/Android/issues/851
CC: 
On scanning an NFC tag that holds web URL, the DuckDuckGo Android app was unable able to open the URL. This PR now fixes that issue. I needed to set up a new `<intent-filter>` in `Manifest.xml`, that would look for `android.nfc.action.NDEF_DISCOVERED`.
1. Ideally should be tested using an NFC tag that holds a web URL.
2. I tested my changes by building another small application that sends a `android.nfc.action.NDEF_DISCOVERED` intent, thus mocking a physical NFC tag. I used the following code snippet to achieve this - 
```
Intent intent = new Intent();
intent.setAction("android.nfc.action.NDEF_DISCOVERED"); …
```

Added support - NFC tags

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/1157893581871903/1198881849371917
In a previous release, we allowed sites to request the user's location. In order to remind our users that a site has location permission, we show a Toast indicating it. 
However, this Toast is very repetitive, because every time the site is refreshed this message appears again. This is particularly intrusive in sites that are refreshed often, like our SERP.
This PR fixes this, making sure that the message is only shown once per tab life span. Closing the tab and open another will prompt this message once.
***In current version in Production:***
1. Open app
2. Search for "Restaurants near me" in our SERP
3. Enable Precise Location
4. Allow system permission
5. Allow …

Show Location Permission message only once

---

app/src/main/java/com/duckduckgo/app/browser/useragent/UserAgentProvider.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1198974644439945
CC: 
Our user agent is breaking comments in thesun.co.uk
1. Open an article in thesun.co.uk, i.e. https://www.thesun.co.uk/news/13051418/france-terror-attack-nice-church-beheaded/  
1. Scroll down between all the ads until you find the comments section. I think just below the `more from the sun` section and above `promoted stories`.
1. Comments should be shown.
1. If you follow the same process using `develop` you will see an error message like the screenshot attached.
---

Add thesun.co.uk to the ua exclusion list

---

app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoCompleteService.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1199086911994413/f
CC: 
This PR adds a language code onto the autocomplete requests, to help get autocomplete results in the right language for the user. We do this by adding the `kl` query param onto the requests, and including the two-letter language code (e.g., `en`, `es`, `ar` etc...)
As discussed in the task, we will use the device preferred language in the first instance, even though that can be a different language than the app shows in. We might quickly revisit that to make it match the app language.
Set up some way of monitoring the network requests made from the app (`Charles`, `AS Network Profiler` etc...)
1. Set device language to Spanish
1. Make a request to …

Includes language in autocomplete service requests, using device preferred language

---

app/src/androidTest/java/com/duckduckgo/app/browser/favicon/DuckDuckGoFaviconManagerTest.kt
app/src/main/java/com/duckduckgo/app/browser/favicon/FaviconDownloader.kt
app/src/main/java/com/duckduckgo/app/browser/favicon/FaviconManager.kt

Task/Issue URL: https://app.asana.com/0/1198194956794324/1198918323600485/f
CC: 
Favicons are displayed in a number of places, eg. tab switcher, bookmarks, fireproof websites etc.
All those places use a listview adapter. The bug appears when the view holder is recycled and the new item
to be displayed in it does not have a favicon. In which case, whatever icon was set in the recycled holder is showed.
This PR fixes that issue in the `FaviconManager` as it is the common entry point for bookmarks, tab switcher, fireproof websites etc
Fixes #975
NOTE: I also considered doing this in the `FaviconDownloader` by allowing a nullable `File` in the `loadFaviconToView` method. However this is too late as results in a UX that shows the previous (holder) icon and …

Fix favicon display view recycling

---

app/src/androidTest/java/com/duckduckgo/app/global/api/ApiRequestInterceptorTest.kt

Task/Issue URL: https://app.asana.com/0/1157893581871903/1198978983891185
This test was using a hardcoded string instead of the package name. This was making the test fail in other build types.
---

ApiRequestInterceptorTest.kt should not use literal for package name

---

app/build.gradle

Task/Issue URL: https://app.asana.com/0/1125189844152671/1199164056051997
CC: 
When I upgraded Mockito to the latest version that caused some issues with testing on lower APIs. By fixing those problems we then created more testing issues on devices with API > 26. This PR downgrades Mockito to the last "stable" version which should fix all the tests.
I have also created https://app.asana.com/0/1125189844152671/1199164056052000 to add J8 desugaring which will allow us to upgrade to the latest version.
1. Run tests on API < 24, API 26 and API > 26 (you can rely on Bitrise for any API < 26)
--- …

Downgrade mockito version

---

app/schemas/com.duckduckgo.app.global.db.AppDatabase/28.json
app/src/androidTest/java/com/duckduckgo/app/TestApplication.kt
app/src/androidTest/java/com/duckduckgo/app/di/TestAppComponent.kt
app/src/androidTest/java/com/duckduckgo/app/global/db/AppDatabaseTest.kt
app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
app/src/androidTest/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/duckduckgo/app/di/AppComponent.kt
app/src/main/java/com/duckduckgo/app/di/AppCoroutineScope.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDbSanitizer.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabEntitiy.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
app/src/main/res/values/strings.xml

Task/Issue URL: https://app.asana.com/0/1198194956794324/1199173078173336/f
CC: 
Impement the feature to be able to undo a tab close action in the tab switcher
* DB methods to get tabs filter out "deletable" tabs
* Added specific methods to mark/undo/delete "deletable" tabs in DB, repository and viewmodel classes
* TabSwitcher shows snackbar upon tab close(d) to undo the action
* Register `TabDbSanitizer` app lifecycle observer to clean pending "deletable" tabs upon app launch
Check DB migration
1. update app and relaunch
2. Verify app works normally
Check tab close undo
1. Open several tabs in background
2. Go to tabs screen
3. Close one tab
4. Verify snackbar to undo action pops
5. Let snackbar to auto-dismiss
6. Navitage to …

Allow to UNDO a closed tab

---

app/src/androidTest/java/com/duckduckgo/app/browser/downloader/UriUtilsFilenameExtractorTest.kt
app/src/main/java/com/duckduckgo/app/browser/downloader/FilenameExtractor.kt
app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/1198194956794324/1199376188899581/f
CC: 
Add a pixel that will file when the `FilenameExtractor` is not able to guess the filename and extension (type) from the information provided in the `PendingFileDownload` data class.
When that happens, the resulting filename has extension `.bin` which causes issues when later opening file from the notification.
1. Go to https://placekitten.com/g/200/300
2. Long press in the image and select download file
3. Verify file is downloaded as `g.bin`
4. Verify in the logcat that `Pixel sent: mdf_dgn with params: {} {}` message is logged
--- …

Added pixel for when download filename/type is not detected

---

app/src/main/res/values/strings.xml

Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1199566695393753/1199576744018385
CC: 
Capitalizes a location toggle string
1. Go to google.maps.com and accept all the permissions
1. Go to settings
1. Go to Location
1. The toggle should read `Sites Can Ask For My Location` 
---

Capitalize location string

---

app/build.gradle
app/src/main/java/com/duckduckgo/app/global/image/GlobalGlideModule.kt

Task/Issue URL: https://app.asana.com/0/0/1199598987755231/f
CC: 
We need to add the LE root certificates to Glide so that fetchinf favicons don't fail in old devices (API <= 25) when LE starts issuing certificates with its own self-signed cert chain
* created custom okHttp and added LE root certs to its SSL socket factory
* registered custom okHttp as `GlideUrl` extension to handle fetches
API <= 25
1. Install app from develop
2. Navigate to https://valid-isrgrootx1.letsencrypt.org/
3. Verify in logcat that glide throws `CertPathValidatorException` when trying to fetch site favicon
API <= 25
1. Install app from this branch
2. Verify `Registering OkHttp-based ModelLoader for GlideUrl` message appears in logcat
3. Navigate to …

Add LE root certificates to Glide

---

app/build.gradle

Task/Issue URL: https://app.asana.com/0/0/1199654613486886/f
CC: 
The PR https://github.com/duckduckgo/Android/pull/1037 added the `okhttp-tls` which start causing internal crashes in okhttp when getting favicons from domains that contain underscores.
Bumping the patch version of okhttp to 3.14.9 fixes the internal crash, surfacing it like it did before so that we can catch it
1. Install develop branch
2. Navigate to https://example_underscore_123.s3.amazonaws.com/
3. App crashes
1. Install this branch
2. Navigate to https://example_underscore_123.s3.amazonaws.com/
3. verify app does not crash
(perform those tests for devices above and below N)
--- …

Fix crash for underscored domains when getting favicons

---

app/src/androidTest/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/UriExtensionTest.kt
app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
app/src/main/java/com/duckduckgo/app/bookmarks/db/BookmarksDao.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/global/UriExtension.kt

Task/Issue URL: https://app.asana.com/0/0/1199525460093862/f
Tech Design URL: https://app.asana.com/0/0/1199656369239103/f
CC: 
Align the autocomplete matching algorithm with iOS. This diff:
* removes the max limit of 6 auto complete items
* impose a max limit of 2 bookmark autocomplete items
* aligns with the iOS algorithm to select bookmark autocomplete items
Autocomplete results limit
1. install app from develop
2. clean all bookmarks
3. search for "cnn"
4. verify the autocomplete result items are limited to 6 items
1. install app from this branch
2. clean all bookmarks
3. search for "cnn"
4. verify the autocomplete result items are not limited to 6 suggestions
Bookmark autocomplete items limit
1. install app from develop
2. search for "cnn" …

Aligned bookmarks autocomplete matching algorithm with iOS

---

app/src/androidTest/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt
app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1199525460093862/f
CC: 
Fixes the URL matching when returning bookmark results upon search query.
1. Install the app from this branch
2. Bookmark `https://www.reddit.com` and `https://www.reddit.com/r/duckduckgo`
3. In the search bar, search for `reddit`
4. Verify both bookmarks appear
(In develop branch, only `https://www.reddit.com` will appear)
---

Fixed the bookmark url matching when domain has www.

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL:  #879
It seems that what caused #879 was that after the tab is automatically closed `BrowserChromeClient::onCloseWindow` is called and  `BrowserTabViewModel::closeCurrentTab` will then be called but `removeCurrentTabFromRepository()` uses `tabRepository.delete(currentTab)` instead of `tabRepository.deleteCurrentTabAndSelectSource()` (which fixes the issue).
1. Have two tabs open, the second tab should have some sort of social login (I used canva.com).
2. On the second tab login into your account.
3. When the login finishes it must go back to the previous tab instead of the first one.
--- …

Fix tab being redirected to first tab #879

---

app/schemas/com.duckduckgo.app.global.db.AppDatabase/30.json
app/src/androidTest/java/com/duckduckgo/app/global/db/AppDatabaseTest.kt
app/src/main/java/com/duckduckgo/app/bookmarks/db/BookmarkEntity.kt
app/src/main/java/com/duckduckgo/app/bookmarks/db/BookmarksDao.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/di/DatabaseModule.kt
app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt

Task/Issue URL:  https://github.com/duckduckgo/Android/issues/1067
**Description**: In this scenario if user tap on Add bookmark menu multiple times, then it creates multiple entry to database. 
**Solution approach**: In this case we have taken action to either update if exist or insert bookmark item if this doesn't.
**Impact**: There is several impact for this solution. If user taps multiple times then it will always show **Bookmark added**.
Technically this is updating into database. In other browser they have handled this kind of different approach.  
Steps to test if the behavior persist or not:
1. Go to any website
2. Tap on Add Bookmark in the kebab menu a couple of times
3. Going to Bookmarks, there are multiple bookmarks of the same page.

fix for duplicate bookmarks #1067

---

app/src/androidTest/java/com/duckduckgo/app/di/TestAppComponent.kt
app/src/androidTest/java/com/duckduckgo/app/onboarding/ui/OnboardingPageManagerPageCountTest.kt
app/src/androidTest/java/com/duckduckgo/app/onboarding/ui/OnboardingPageManagerTest.kt
app/src/androidTest/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/di/AndroidBindingModule.kt
app/src/main/java/com/duckduckgo/app/di/AppComponent.kt
app/src/main/java/com/duckduckgo/app/global/DefaultRoleBrowserDialog.kt
app/src/main/java/com/duckduckgo/app/global/DefaultRoleBrowserDialogExperiment.kt
app/src/main/java/com/duckduckgo/app/onboarding/di/OnboardingModule.kt
app/src/main/java/com/duckduckgo/app/onboarding/di/WelcomePageModule.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingPageManager.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModel.kt
app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1199628713920165/f
CC: https://app.asana.com/0/1142021229838617/1199633113249889/f
After the successfull experiment, see https://app.asana.com/0/0/1199361498013999/f, this PR:
* Removes the `zu` and `zt` variants
* Modifies the `DefaultRoleBrowserDialogExperiment#shouldShowExperiment` to remove the variant check
* Modifies the `OnboardingPageManagerWithTrackerBlocking` to remove the variant check and to ensure it shows when the "new Chrome default browser dialog" does not
* Fixed the tests
==Test case 1==
Device API >=29
* Fresh install the app and launch it
* In Welcome page press "let's do it"
* Select ddg as default browser in the dialog
* Verify app proceeds to main …

Removed the experiment for the new default browser dialog for full release

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/api/ApiRequestInterceptorTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/api/FakeChain.kt
app/src/androidTest/java/com/duckduckgo/app/global/api/PixelReQueryInterceptorTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/KeyboardAwareEditText.kt
app/src/main/java/com/duckduckgo/app/di/NetworkModule.kt
app/src/main/java/com/duckduckgo/app/global/api/ApiRequestInterceptor.kt
app/src/main/java/com/duckduckgo/app/global/api/PixelReQueryInterceptor.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1199568299173487/f
Tech Design URL: https://app.asana.com/0/481882893211075/1199538898514883/f
CC: 
This PR fixes the `rq_x` pixels that got broke when removing the double search header. The main issue was that pixels have a suffix `android_{formFactor}`, but also under the [iOS implementation](https://app.asana.com/0/481882893211075/1199403269515656/f) a few more fine tuning was done to improve them. This PR will:
* Remove the android_tablet/phone suffix from the rq_x pixels
* Override the user agent so that rq_x pixels are sent with the same UA as the webview
* Align the search bar behavior with iOS
* rq.0 will fire when
* the user resubmits the search through the search box in our app.
* the SERP is reloaded 
* …

Fix query change pixels

---

app/src/androidTest/java/com/duckduckgo/app/di/TestAppComponent.kt
app/src/main/java/com/duckduckgo/app/di/AppComponent.kt
app/src/main/java/com/duckduckgo/app/di/DaggerWorkerFactory.kt
app/src/main/java/com/duckduckgo/app/di/WorkerModule.kt
app/src/main/java/com/duckduckgo/app/fire/DataClearingWorker.kt
app/src/main/java/com/duckduckgo/app/global/job/AppConfigurationSyncWorkRequestBuilder.kt
app/src/main/java/com/duckduckgo/app/global/plugins/PluginPoint.kt
app/src/main/java/com/duckduckgo/app/global/plugins/worker/WorkerInjectorPlugin.kt
app/src/main/java/com/duckduckgo/app/global/plugins/worker/WorkerPluginsModule.kt
app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
app/src/main/java/com/duckduckgo/app/statistics/api/OfflinePixelScheduler.kt

Task/Issue URL: https://app.asana.com/0/0/1199633113249884/f
CC: 
Use dagger multibindings to decouple the `DaggerWorkerFactory`.
The `DaggerWorkerFactory` is a big object that creates the workers AND inject its dependencies. For that reason it needs to know and depend on ALL dependencies all the app workers require. Which makes it a god object.
In this PR I use dagger multibindings to setup a kind of plugin system where the `DaggerWorkerFactory` can delegate the injection of dependencies to the worker plugins.
1. install/update the app
2. app should work as before
3. all workes should just work as before
--- …

Decouple the DaggerWorkerFactory using plugins

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1191242003013179
CC: 
This PR makes the privacy grade clickable while the grade is loading.
1. Go to a site that takes a few seconds to load, a good example is the first time that `cnn.com` loads.
1. While loading (privacy grade is completely black) click on the privacy grade.
1. You should be taken to the privacy dashboard.
---

Make privacy grade clickable when grade is loading

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://github.com/duckduckgo/Android/issues/1070
CC: https://app.asana.com/0/414730916066338/1199905075709368/f
Fixed the issue by passing the current tab id to onOpenInNewTabRequested function while performing web search
1. Perfrom "Web search" on a tab. Consider this as tab 1.
2. The user will be in a new tab, Now press back button
3. The current tab should close. The user will be seeing the tab1.
---

Fixed the back navigation after web search

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1199905759163742/f
CC: 
We should not send rq.1 pixels when the user is in NOT in the SERP, ie. the search bar contains a valid URL
Repro steps of the bug
* open browser
* load website, eg. http://example.com
* tap on search bar
* search for "reddit"
* select "🔎 reddit"
* verify rq.1 pixel is wrongly fired ❌
(to see when rq pixels are sent, filter logcat with `rq_`)
Verify the following test flow
* open app and search reddit
* Verify `rq.x` pixels are NOT sent
* pull to refresh
* verify `rq.0` pixel is sent
* overflow menu -> refresh
* verify `rq.0` is sent
* tap on search bar 
* select "🔎 reddit" from autocomplete
* verify `rq.0` is sent
* tap on search bar and select "🔎 …

Do not send rq.1 when the user is NOT in the SERP

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/KeyboardAwareEditText.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1199931182139250/f
CC: 
When we fixed the requery pixels (https://github.com/duckduckgo/Android/pull/1065) we also had to tune the search bar behavior, causing a side effect where URLs in thee search bar would never be selected when the user taps on the search bar.
This PR fixes that issue
1. install/update from this branch
2. Ensure tests in https://app.asana.com/0/0/1199922227966104/f pass (to see when rq pixels are sent, filter by `rq_` in logcat)
1. install/update from this branch
2. open app and tap on search bar
3. search for "reddit"
4. select "🔎 reddit"
5. tap on the search bar
6. verify text is not selected and autocomplete results show up
7. open the first URL in …

Fixed search bar selection behavior

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1199888021167463
CC: 
This PR changes how we enable swipe to refresh so it only happens once a website is clamped at the top AND a new gesture begins. This should fix https://github.com/duckduckgo/Android/issues/1081
1. Go to any site with scrollable content, i.e. `https://m.xkcd.com/2425/`
1. When the page loads for the first time, pulling to refresh should be enabled.
1. Scroll down a bit, then up to reach the top and then back again all within the same gesture.
1. Pull to refresh should not be activated.
1. Pull to refresh is only enabled if the site is clamped at the top and you being a new gesture.
--- …

Swipe to refresh is too sensitive

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1199969297683315
CC: 
When you are watching a video or any content in fullscreen, after you come back from fullscreen if there is an edit/search field in the website the keyboard won't show anymore until you click on the omnibar to get the focus back. This PR requests the focus back when coming back from fullscreen.
1. Go to youtube.com
1. Start watching any video
1. Change the video so you watch it in fullscreen (click on the square on the bottom right side)
1. Go back to normal mode (click on the square on the bottom right side or the back button)
1. Click on the search icon
1. Keyboard should show up
--- …

Keyboard not showing up after coming back from fullscreen

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/KeyboardAwareEditText.kt

Task/Issue URL: https://github.com/duckduckgo/Android/issues/1074
- This PR modifies `KeyboardAwareEditText` to be aware of pasting text from the clipboard and clear its style beforehand.
- If API level >= M, we can just use [R.id.pasteAsPlainText](https://developer.android.com/reference/android/R.id#pasteAsPlainText)
- If API level < M, we need to manually clear and set the data to primary clip again(see `ClipboardManager.convertClipToPlainText`)
- Now `KeyboardAwareEditText` has kind of two responsibilities and I was thinking I should rename the class as `OmniToolbarEditText` or something, but since this is my 1st PR as an external contributor I'd like to keep the diff smaller as much as I can. Let me know your thoughts around here🙏
1. API …

fix: convert clip data into plain text before pasting to omnibar

---

app/src/main/java/com/duckduckgo/app/browser/omnibar/KeyboardAwareEditText.kt

Task/Issue URL: https://app.asana.com/0/0/1200004870762512/f
CC: 
The search bar shall behave as follows when we open the app and have a tab with a search query:
* first time the user taps on the search bar → query shall be selected so that the user can start typing a new query
* no AC results shall show in this case
* any subsequent taps on the search bar will not select the query but rather show AC results
This behavior regressed in 5.77.x and now we always don't select the query in the search bar and show AC results.
Repro steps
1. open the app and open a new tab
2. search for anything and wait for SERP results
3. close and re-open the app
4. tap on search bar
* expected → the query text is selected and AC results don't show
* actual →  the query text …

Fixed regression query selection on search bar

---

app/src/main/java/com/duckduckgo/app/trackerdetection/api/TrackerListService.kt

Task/Issue URL: https://app.asana.com/0/11472677167855/1185888722207947
CC: 
**Depends on SERP repo being merged**: https://dub.duckduckgo.com/duckduckgo/ddg/pull/21513
---

Rename unprotected URL

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/0/1199921546480466/1199948623134658/f
CC: 
Fixes reported memory leak when any AppEnjoyment dismissed in our app.
To reproduce:
1. Using develop, force any AppEnjoyment dialog (you can hardcode a value in `InitialPromptTypeDecider`) to displayed
2. Dismiss dialog
3. Wait until leakcanary reports the leak, or dump heap manually 
To test:
1. Using this branch, force any AppEnjoyment dialog (you can hardcode a value in `InitialPromptTypeDecider`) to be displayed
2. Dismiss dialog
3. Dump heap manually 
4. Ensure no memory leaks (use leak canary) when any AppEnjoyment dialog displayed and dismissed.
(see report in https://app.asana.com/0/1199921546480466/1199948623134658/f)
---
[Software …

Leak after responding to Rate dialog

---

TRANSLATIONS.md

Task/Issue URL: https://app.asana.com/0/488551667048375/1200074995172333/f
CC: 
To update our contribution and translations guidelines to highlight that we only accept translation fixes and not minor changes.
1. N/a
1. 
---

Update translations guidelines

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1199674134590488
CC: 
This PR fixes a bug where we close the wrong tab after receiving a close window event.
**Google Sign in**
1. Open a tab and go to SERP
1. Open another tab and go to a site with a google login like `etsy.com`
1. Sign in with your google account, once the flow has finished you should be returned to the tab which initiated the flow
1. Some sites require us to enable 3p cookies for the login with Google to work, in those cases you will not be signed in but you should still be returned to the correct tab.
**Facebook Sign in**
1. Open a tab and go to SERP
1. Open another tab and go to a site with a Facebook login like …

Close correct tab when close window called

---

app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModel.kt
app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/common/FeedbackViewModel.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/initial/InitialFeedbackFragmentViewModel.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/negative/brokensite/BrokenSiteNegativeFeedbackViewModel.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/negative/openended/ShareOpenEndedNegativeFeedbackViewModel.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/positive/initial/PositiveFeedbackLandingViewModel.kt
app/src/main/java/com/duckduckgo/app/fire/fireproofwebsite/ui/FireproofWebsitesViewModel.kt
app/src/main/java/com/duckduckgo/app/globalprivacycontrol/ui/GlobalPrivacyControlViewModel.kt
app/src/main/java/com/duckduckgo/app/icon/ui/ChangeIconViewModel.kt
app/src/main/java/com/duckduckgo/app/launch/LaunchViewModel.kt
app/src/main/java/com/duckduckgo/app/location/ui/LocationPermissionsViewModel.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingViewModel.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModel.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardViewModel.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyPracticesViewModel.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/ScorecardViewModel.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/TrackerNetworksViewModel.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/WhitelistViewModel.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
app/src/main/java/com/duckduckgo/app/survey/ui/SurveyViewModel.kt
app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt

Task/Issue URL: https://app.asana.com/0/30173902528854/1200098175084894/f
CC: 
https://github.com/duckduckgo/Android/pull/1123 introduced a bug that was detected by our pixels.
* That pull request delegated the creation of the view models (VMs) to its own factory
* The VM factories are `singleton` -- as they should be
* The VM factories create the VMs and inject their dependencies
* Because the VM factories are `singleton` that effectively makes all VM dependencies `singleton`. Regardless of whether they are actually declare as such or not
* This is not desired, VM factories thouls be singleton, but it should respect the di semantics of its deps
This PR makes all the factories to provide `providers` of the dependencies, rather than the actual instance. …

Use providers in the VM factories to respect the dep di semantics

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/global/IntentExtension.kt

Task/Issue URL: https://github.com/duckduckgo/Android/issues/953
CC: 
This issue happened because every time an intent.getX (X being string, bool, etc) was called, internally it would eventually call unparcel() on BaseBundle, and if there is a class that was passed somewhere on the intent that duckduckgo can't unserialize (either by Serializable or Parcelable) it would throw an exception and close the app. One thing to note is that I tracked all current calls of where the app received intents that were not under the app control, and it seems that this point is in BrowserActivity in onNewIntent. So before any call could be made to any intent `getSomething` call I called sanitize, which is the preferred design that duckduckgo team mentioned on the original …

Sanitize intents in BrowserActivity

---

app/src/androidTest/java/com/duckduckgo/app/httpsupgrade/HttpsUpgraderTest.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/HttpsUpgrader.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1200168757349077
CC: 
This PR removes all the https pixels
**Install from develop**
1. Go to serp.
1. You should see the pixel `m_https_nl`.
1. Go to a long and random url like `http://asdasdqweasdasedqweasd.com`
1. You should see the pixel `m_https_nu`.
**Install from the branch**
1. Go to serp.
1. You should not see the pixel `m_https_nl`.
1. Go to a long and random url like `http://asdasdqweasdasedqweasd.com`
1. You should not see the pixel `m_https_nu`.
---

Remove https pixels

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1184175637619353/f
CC: 
Adds call to sanitise `Intent` in the `BrowserActivity.onCreate()` function
1. Same steps to test as in #953, use the snippet provided [here](https://github.com/duckduckgo/Android/issues/953#issuecomment-712151654) and verify no crash happens
---

Sanitize Intent in BrowserActivity.onCreate(), same as in onNewIntent()

---

app/src/main/res/values-cs/strings.xml

Czech translation of "Light theme" is wrong. The word "Lehký" is being used when something is not heavy (it's related to weight and not to brightness). The proper translation is "Světlý".

Czech - Fixed translation of 'Light Theme'

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt

Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1200092328111314/1200200821708976
CC: 
This PR fixes some bug reports where pull to refresh is triggered incorrectly while scrolling on a map or some other interactive content. This also can happen if the site has its own toolbar. This PR fixes https://github.com/duckduckgo/Android/issues/1132
1. Visit some of the following problematic sites. With the prod app pull to refresh should be triggered very easily whereas with this branch that should not happen:
- SERP with a map search.
- https://makecode.microbit.org/projects/guitar/displaybuttons
- https://www.openstreetmap.org/
- https://tiktok.com
- https://www.walmart.com/grocery/
--- …

Pull to refresh sensitivity fix

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://github.com/duckduckgo/Android/issues/1162
Fixed by disabling swipeRefreshContainer at home
Resolves: #1162
1. Open new tab 
2. Visit any site
3. Press back (this will go back to the home tab)
4. Now user will not be able to pull to refresh

Fix Swipe To Refresh On NTP

---

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1200222336221916/1200225465042460
CC: 
This PR disables the SERP variants
1. Check `se` and `sc` are disabled
---

Disable serp variants

---

app/schemas/com.duckduckgo.app.global.db.AppDatabase/32.json
app/src/androidTest/java/com/duckduckgo/app/brokensite/BrokenSiteDataTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/WebViewRequestInterceptorTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaTest.kt
app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/db/AppDatabaseTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/model/SiteMonitorTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/ui/TrackerNetworksAdapterTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/ui/TrackerNetworksViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/surrogates/ResourceSurrogateLoaderTest.kt
app/src/androidTest/java/com/duckduckgo/app/surrogates/ResourceSurrogatesTest.kt
app/src/androidTest/java/com/duckduckgo/app/trackerdetection/TdsClientTest.kt
app/src/androidTest/java/com/duckduckgo/app/trackerdetection/TrackerDetectorClientTypeTest.kt
app/src/androidTest/java/com/duckduckgo/app/trackerdetection/TrackerDetectorTest.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewRequestInterceptor.kt
app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
app/src/main/java/com/duckduckgo/app/surrogates/ResourceSurrogateLoader.kt
app/src/main/java/com/duckduckgo/app/surrogates/ResourceSurrogates.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/Client.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/TdsClient.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/TrackerDetector.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/model/TdsTracker.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/model/TrackingEvent.kt

Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1200216229834032/1200216231039639
Tech Design URL: https://app.asana.com/0/1198207348643509/1200195761608655
CC: 
This PR changes the way we find surrogates for requests, rather than matching the full URL of the intercepted request we now rely on Tracker Radar data for this.
**Migrate from develop**
1. Install and launch the app from `develop`
1. In the logcat you should see a few statements like `Found new surrogate rule: google-analytics.com/ga.js - application/javascript`
1. Go to `autotrader.co.uk`, insert a postcode like `LS9 8BA` and press search.
1. The search results should not show and the progress indicator should be stuck.
1. In the logcat you should not see `Surrogate …

Fix surrogates algorithm

---

app/src/main/java/com/duckduckgo/app/global/view/FireDialog.kt

Task/Issue URL: https://github.com/duckduckgo/Android/issues/1159
Tech Design URL:
CC:
When we check that the animation is enabled we can also check that the animator duration scale is set, if it is set to 0 then we skip the animation.
1. Set `Animator duration scale` to `Animation off`
2. Select `Clear all tabs and data`. 
3. Now we skip the animation unlike previously where we would get stuck on a black screen.
---

Fix fire animation

---

app/src/androidTest/java/com/duckduckgo/app/notification/AndroidNotificationSchedulerTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt
app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1200252649107473/1200229532781040
CC: 
This PR disabled the previous experiment and creates two new variants. The experimental variant now enables all the inactive notification as long as the don't clash with the UOA notification. If that's the case we delay the inactive notification by one day.
**Before testing**
In the `AndroidNotificationScheduler` change lines `85` and `89` so they pass `TimeUnit.SECONDS` instead of days.
In the `AndroidNotificationScheduler` change line 102 to `return duration * 10` to give the notification more than 1 second to be sent.
**ZY experimental variant**
Change the variant to always use `zy`
**Day 0**
1. Before installing the app …

UOA experiment 2nd iteration

---

app/src/main/java/com/duckduckgo/app/global/view/FireDialog.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200266002668723/f
CC: 
This PR avoids disabling fire animations if no value provided from global settings. In that case we will assume is active.
1. Disable scale animation on dev settings
1. Fire Animation should not be triggered when clearing data
2. Enable scale animation on dev settings
3. Fire Animation should be triggered when clearing data
---

Fix: avoid disabling animation if no value provided

---

gradle.properties

Task/Issue URL: https://app.asana.com/0/414730916066338/1200284402862753/f
CC: 
Enable the gradle build local cache
Incidentally I have also enabled the parallel GC. I use JDK 14 to compile locally and I realised that parallel GC is not enabled for JDK 9 and above. [See docs for more info](https://developer.android.com/studio/build/optimize-your-build)
1. from `develop` branch
2. execute `./gradlew clean asesmblePlayDebug` twice
3. verify the build time is more or less the same
1. from this branch
2. execute `./gradlew clean asesmblePlayDebug` twice
3. verify the second time around, the build time is way smaller
--- …

Enable gradle local build cache

---

app/build.gradle
common/build.gradle

Task/Issue URL: https://app.asana.com/0/414730916066338/1200271718763060/f
CC: 
The `lifecycle-extensions` artifact is now deprecated, see [docs for more info](https://developer.android.com/jetpack/androidx/releases/lifecycle).
The `lifecycle-extensions` are no longer upgraded and until we don't remove them we wont be able to update the `lifecycle` artifacts.
This PR removes the artifact and, as suggested by the documentation, adds the specific artifacts for view models etc.
We are not updating any version in this PR
This change is safe a lons as the branch compiles, however also check the main features of the app
1. install/upgrade from this branch
2. vefiry navigation, bookmarks, fireproof sites and fire button work as …

Replaced lifecycle-extensions by specific artifacts

---

fastlane/Fastfile
fastlane/README.md

Task/Issue URL: https://app.asana.com/0/488551667048375/1200292136839127/f
CC: 
ℹ️   Open `Fastfile`, and comment out line 145 (so it becomes `#ensure_git_branch( branch: 'develop' )`)
1. Run `bundle exec fastlane release` 
2. Verify you see the existing release notes
3. Choose option `1` which is to "KEEP EXISTING" release notes
4. Enter any version number (e.g., `0`)
5. Verify the release notes that are printed are the same as before
6. 🛑  enter `n` to end this flow
1. Run `bundle exec fastlane release` 
2. Choose option `2` which is to use "CUSTOM" release notes
3. Verify you are prompted to enter custom release notes. Enter some (test multi-line release notes) and terminate the notes by entering `END` and pressing enter
4. …

improve entering release notes into fastlane

---

app/src/main/java/com/duckduckgo/app/location/ui/SiteLocationPermissionDialog.kt
app/src/main/res/values/string-untranslated.xml

Task/Issue URL: https://app.asana.com/0/1174433894299346/1200197271421338
We would like to replace the text in the location dialog in our DDG Android app with the copy that was in the black notification tooltip that appears for other browsers.  
**Screenshots**:
| duckduckgo.com  | other sites |
| ------ | ----- | 
***For duckduckgo.com***
1. Open app and search for restaurants near me
2. Enable Location Services
3. Allow system location permission
4. The site permission dialog should now be shown
5. Check that the message is "We only use your anonymous location to deliver better results, closer to you. You can always change your mind later."
***For other sites**
1. Open app and navigate to maps.google.com
2. Ask for current position
3. Allow …

Replace location dialog subtitle copy in requests from our SERP

---

app/src/androidTest/java/com/duckduckgo/app/di/StubCoroutinesModule.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/browser/httpauth/WebViewHttpAuthStore.kt
app/src/main/java/com/duckduckgo/app/browser/rating/di/RatingModule.kt
app/src/main/java/com/duckduckgo/app/di/AppComponent.kt
app/src/main/java/com/duckduckgo/app/di/DatabaseModule.kt
app/src/main/java/com/duckduckgo/app/di/NetworkModule.kt
app/src/main/java/com/duckduckgo/app/di/PrivacyModule.kt
app/src/main/java/com/duckduckgo/app/di/StatisticsModule.kt
app/src/main/java/com/duckduckgo/app/di/StoreModule.kt
app/src/main/java/com/duckduckgo/app/di/SystemComponentsModule.kt
app/src/main/java/com/duckduckgo/app/fire/DataClearerForegroundAppRestartPixel.kt
app/src/main/java/com/duckduckgo/app/fire/LottieFireAnimationLoader.kt
app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/global/install/AppInstallStore.kt
app/src/main/java/com/duckduckgo/app/global/plugin/LifecycleObserverPluginPoint.kt
app/src/main/java/com/duckduckgo/app/global/rating/AppEnjoymentLifecycleObserver.kt
app/src/main/java/com/duckduckgo/app/global/shortcut/AppShortcutCreator.kt
app/src/main/java/com/duckduckgo/app/icon/api/AppIconModifier.kt
app/src/main/java/com/duckduckgo/app/job/AppConfigurationSyncer.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDbSanitizer.kt
app/src/main/java/com/duckduckgo/app/usage/di/AppUsageModule.kt
common/src/main/java/com/duckduckgo/app/global/plugins/PluginPoint.kt
statistics/src/main/java/com/duckduckgo/app/statistics/api/PixelSender.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200284402862810/f
CC: 
The `DuckDuckGoAppliation` adds all application observers manually, like so:
```kotlin
ProcessLifecycleOwner.get().lifecycle.also {
it.addObserver(this)
it.addObserver(dataClearer)
it.addObserver(appDaysUsedRecorder)
it.addObserver(defaultBrowserObserver)
it.addObserver(appEnjoymentLifecycleObserver)
it.addObserver(dataClearerForegroundAppRestartPixel)
it.addObserver(userStageStore)
it.addObserver(pixelSender)
it.addObserver(fireFireAnimationLoader)
it.addObserver(tabsDbSanitizer)
it.addObserver(webViewHttpAuthStore)
}
```
The main drawback is that the appliation has to depend on all the observer types, and every time we add/remove one observer we need to touch the …

Move the app lifecycle observers to be plugins

---

app/src/main/res/layout/include_new_browser_tab.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1199709896363266
CC: 
This PR adds a `ScrollView` around the logo and dialog to prevent Dax from being cutoff on some screen sizes.
| Without `ScrollView`  | With `ScrollView` |
| ------ | ----- | 
1. Launch a fresh version of the app on a S7 Edge/OnePlus 6T/480 x 800 | hdpi emulator
2. Wait for the keyboard to pop-up when the onboarding dialog with Dax appears
3. Check that Dax is not cut off (If there is not enough space for the whole dialog to appear, the dialog (including Dax) should be scrollable)
--- …

Add ScrollView to fix Dax being cutoff when keyboard appears

---

app/src/main/res/values/styles.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1200353412494330/f
CC: 
Fixes text size for titles in the Settings screen.
Before:
After:
1. 
1. 
---

Fix text size for titles in settings activity

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/global/view/FireDialog.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200308959421574/f
CC: 
Removes unused listener inside FireDialog.
Nothing should have changed with this PR. The removed callback method was not being called, so removed logic was never executed.
However, as a smoke test:
1. Run the app
2. Clear all data (from browser / from tab screen)
1. Ensure fire animations runs, process restarts, and nothing crashes
---

Remove unused listener clearComplete

---

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1200352843630432/1200349932611404
CC: 
This task enables SERP variants and disables variants from the UOA experiment.
1. Make sure `sc` and `se` are the only active variants
---

Enable serp variants

---

app/src/androidTest/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/QueryUrlConverterTest.kt
app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoCompleteService.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarEntryConverter.kt
app/src/main/java/com/duckduckgo/app/browser/omnibar/QueryUrlConverter.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1200343978632902
CC: 
This PR introduces the new autocomplete parameter `is_nav`. The extra `isNav=true` field will then be used as a navigation query (meaning when the user clicks that autocomplete suggestion we load that URL). Results where this is `false` should be treated as searches (even if they look like a URL).
This PR also handles the case where `nav=null` in which case we default to the old way.
**Previous steps, setting up Charles**
1. Connect your device to charles and use the `autocomplete.json` response provided in the task.
1. Install and launch the app.
1. Add a bookmark to `http://m.youtube.com`
1. Do a search (i.e. `you`) and in Charles map the response …

Add nav parameter to autocomplete

---

fastlane/Fastfile

Task/Issue URL: https://app.asana.com/0/488551667048375/1200390729242552/f
CC: 
Updates fastlane release script to allow empty commits. This is handy when both release number and release notes are unchanged.
1. Confirm new parameters match https://docs.fastlane.tools/actions/git_commit/#parameters
---

Allow empty commits, for when version and release notes are unchanged

---

app/src/main/res/values-cs/strings.xml

This PR improves/fixes the translation of two menu items in the Czech language. Namely:
- `requestDesktopSiteMenuTitle` - "Stránka plochy" means pretty much nothing and the purpose of this menu items is not clear at all. I've changed it to "Verze pro počítač". It is the same string firefox uses in it's mobile web browser and it is actually understandable.
- `fireproofWebsiteMenuTitleAdd` - "Web s ochranou" is good, but I also feel like it is not clear and doesn't describe an action (the English version does). That is why I've changed it to "Ochránit web" which is an action.
Initially I also wanted to fix `settingsLightTheme`, but someone was a bit quicker than me 😃

Fixed Czech translation for two menu items

---

build.gradle

**_Details / rationale_:**
- JCenter repository sunset is announced for a May 01st 2021 (and hence Jcenter references must be changed to a Maven Central)
- `'com.android.tools.build:gradle'` plugin version is bumped: 4.1.0-->> 4.1.2 
ℹ️ Please note that bump to an upcoming Android Studio/android gradle plugin version **4.1.3** is required in order to solve issues with gradle dependency refresh/project sync (after `jcenter()` repository references are removed, that is... see pending issue here: https://issuetracker.google.com/issues/179291081)
**_Related links:_**
- https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter
- https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure
- https://blog.sonatype.com/dear-bintray-and-jcenter-users-heres-what-you-need-to …

Switching from JCenter to Maven Central

---

app/src/main/java/com/duckduckgo/app/browser/favicon/FaviconDownloader.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200403069635810/f
CC: 
This PR tries to bring a fix for GlideExceptions crash reports.
We have not being able to reproduce the exception so this workaround only addresses one of the areas where exceptions from Glide are not captured.
This change should not affect current app behavior.
However, we could try to force a crash in that part of the code by trying to read a non existing file:
1. checkout the code
1. add `val file = File(file.path+"err")` in line 40 file `GlideFaviconDownloader`
1. Add a few favorites or bookmarks
3. Go to bookmarks screen
4. Ensure all bookmarks or favorites show the placeholder and the app did not crash (some sites may show a …

Fix glide exception in some edge cases

---

app/src/main/java/com/duckduckgo/app/browser/serviceworker/ServiceWorkerLifecycleObserver.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200407932131592
CC: 
This PR wraps the `getInstance()` call from the Service Worker to avoid crashing the app.
1. Build the app and make sure it doesn't crash!
---

Fix service worker crash

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200270570497000
CC: 
This PR clears the navigation stack when a user has gone back to the home screen and makes a new search or goes to a new URL.
1. Open a new tab
1. Go to as.com (site A)
1. Press back → going back to home tab
1. Go to marca.com (site B)
1. Site A doesn't load
1. Press back
1. You should now be on the home screen
---

Correctly reset navigation stack 

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200484661445644/f
CC: 
Follow up of https://github.com/duckduckgo/Android/pull/1284
We fixed clearing the navigation when the user submits a new query from the home tab, however, when the user clicks on a favorite the issue was still present.
We detected that `ResetHistory` was emitted from the viewmodel but not received in the fragment, and we don't know why that happens.
Bug behavior:
-> quickAccessAdapter item clicked -> `viewModel.onQuickAccesItemClicked` -> `Command.SubmitQuery` -> `viewModel.onUserSubmittedQuery`-> `Command.ResetHistory` and `Command.Navigate` -> ❌ `ResetHistory` command not received, ✅`Navigate` command received
Fix:
-> quickAccessAdapter item clicked -> …

Fix: nav history not cleared when favorite clicked

---

app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt

- Internal: https://app.asana.com/0/414730916066338/1200504463069262/f
- Fixes https://github.com/duckduckgo/Android/issues/1273
Ensures the `RecyclerView` in the tab switcher doesn't have its scroll position set until it's ready to receive that
On `develop`
1. Open up 12 tabs (hint, wikipedia is a good site to use to find lots of links to open in background)
1. Switch to the tab in position 7 or 8
2. Open tab switcher again; you _might_ see the bug whereby it doesn't scroll (repeat a few times if you don't see it immediately)
3. Install this branch
4. Repeat the experiment; you should see it set scroll position correctly
5. Repeat for other elements in the list (first, last etc...) and confirm all work as expected
---
[Software …

Delay setting scroll position until Recycler is ready for it

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserChromeClientTest.kt
app/src/androidTest/java/com/duckduckgo/app/drm/DrmRequestManagerTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
app/src/main/java/com/duckduckgo/app/drm/DrmRequestManager.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1200498850561025
CC: 
This PR grants DRM permissions when requested so protected media content can be played. We only grant `RESOURCE_PROTECTED_MEDIA_ID` and ignore any other media permissions.
1. Go to spotify.com
1. Log in with your account
1. The player should successfully show up and you should be able to play songs, etc.
1. If you try the same in `develop` you will see a `Not supported` message after logging in and/or opening the web player.
---

Grant DRM permissions when requested

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/privacy/ui/ScorecardViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/trackerdetection/TrackerDetectorClientTypeTest.kt
app/src/androidTest/java/com/duckduckgo/app/trackerdetection/TrackerDetectorTest.kt
app/src/androidTest/java/com/duckduckgo/app/trackerdetection/db/TemporaryTrackingWhitelistDaoTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardViewModel.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/ScorecardActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/ScorecardViewModel.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/TrackerDetector.kt
app/src/main/java/com/duckduckgo/app/trackerdetection/db/TemporaryTrackingWhitelistDao.kt
app/src/main/res/layout/include_privacy_dashboard_header.xml
app/src/main/res/values/string-untranslated.xml
common-ui/src/main/res/values/colors.xml

Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1200517965702749/1200538500897521
CC: 
This PR changes the privacy dashboard UI when a visited site is in the temporary allowed list to correctly show that Privacy Protections are disabled.
1. Go to `vanguard.com` and wait until the site loads
1. The privacy grade should be black
1. Click in the privacy grade
1. The privacy dashboard should have the toggle disabled (as in non changeable)
1. The privacy dashboard should show trackers found rather than blocked.
1. The privacy dashboard should show a warning saying the protections is disabled due to a breakage
1. The privacy dashboard should not show the Unprotected Sites and the Report Broken Site …

Fix UI when a site is in temp allowed list

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/applinks/DuckDuckGoAppLinksHandlerTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/applinks/AppLinksHandler.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200571376274550/f
CC: 
User-entered app links that redirect to intent:// links are not being handled after adding the app links feature.
This PR handles those cases.
1. Paste https://photoprints.page.link/t-mobile into the search bar
2. Verify that the "Open in another app" dialog is shown
3. Verify that clicking open, opens the Google Play app page
4. (Ensure that DuckDuckGo is the default browser)
5. Using a physical device, scan the QR code for the same link: https://duckduckgo.com/?q=qrcode+https%3A%2F%2Fphotoprints.page.link%2Ft-mobile
5. Verify that the "Open in another app" dialog is shown
6. Verify that clicking open, opens the Google Play app page
---
[Software …

Handle user-entered app link redirects

---

app/src/main/res/values-tr/strings.xml

This PR fixes Turkish grammatical errors in order to improve the understanding.
In English description of `defaultBrowserDescriptionNoDefault` _open_ word is a verb however in Turkish translation it's been used as a noun. Other word I've preferred _link_ instead of _bağlantı_ although it's not a necessary change however _link_ is most common used in I.T and daily speech.
Corrected translation `omnibarInputHint`. Previous translation was "Search URL or Type an URL". Now it means exactly like in English.
About `settingsAutomaticallyClearWhenAppExit5Seconds` and  other `settingsAutomaticallyClearWhenAppExit{n}Minutes` are little bit ambiguous even for English, I guess. 
In my opinion, English translation can be like these;
**App exit, inactive for 5 second** => _(If) Inactive for 5 seconds …

Update Turkish localization strings

---

app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoActivity.kt
app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/email/ui/EmailProtectionActivity.kt
app/src/main/java/com/duckduckgo/app/email/ui/EmailWebViewActivity.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/common/FeedbackActivity.kt
app/src/main/java/com/duckduckgo/app/fire/fireproofwebsite/ui/FireproofWebsitesActivity.kt
app/src/main/java/com/duckduckgo/app/globalprivacycontrol/ui/GlobalPrivacyControlActivity.kt
app/src/main/java/com/duckduckgo/app/icon/ui/ChangeIconActivity.kt
app/src/main/java/com/duckduckgo/app/location/ui/LocationPermissionsActivity.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyDashboardActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyPracticesActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/ScorecardActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/TrackerNetworksActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/WhitelistActivity.kt
app/src/main/java/com/duckduckgo/app/survey/ui/SurveyActivity.kt
app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchActivity.kt
app/src/main/java/com/duckduckgo/app/widget/ui/AddWidgetInstructionsActivity.kt
common-ui/src/main/java/com/duckduckgo/mobile/android/ui/viewbinding/ActivityViewBindingDelegate.kt
gradle/android-library.gradle

Task/Issue URL: https://app.asana.com/0/414730916066338/1200552671375508/f
CC: 
In PR https://github.com/duckduckgo/Android/pull/1302 we migrated some of the activities to use view binding. This PR creates an activity view binding delegate that makes viewbinding a bit simpler for activities.
The idea is to do the same for views and fragments. Fragments will be the ones that benefit the most out of using a delegate because we won't need to remember to `null` the `binding` in `onDestroy`
1. repeat tests from https://github.com/duckduckgo/Android/pull/1302
---
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943 …

Activity view binding delegate

---

app/src/main/java/com/duckduckgo/app/browser/TabSwitcherButton.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsOptionWithSubtitle.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsPillWithSubtitle.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsToggleOptionWithSubtitle.kt
app/src/main/res/layout/content_settings_privacy.xml
common-ui/src/main/java/com/duckduckgo/mobile/android/ui/viewbinding/ViewBindingDelegate.kt
common-ui/src/main/res/values/attrs-settings-item-with-subtitle-and-pill.xml

Task/Issue URL: https://app.asana.com/0/0/1200640982441046/f
CC: 
This PR adds a view binding delegate for `Views` and migrates some of the following custom views to use view binding
* SettingsOptionWithSubtitle
* SettingsToggleOptionWithSubtitle
* TabSwitcherButton (it was already using view binding but now it uses the delegate)
1. verify the tab switcher button in top right of the browser works properly
1. go to settings
1. verify all toggle views veriry properly
---

Add view binding delegate and use it in custom views

---

app/src/main/java/com/duckduckgo/app/email/ui/EmailProtectionFragment.kt
app/src/main/java/com/duckduckgo/app/email/ui/EmailProtectionSignInFragment.kt
app/src/main/java/com/duckduckgo/app/email/ui/EmailProtectionSignOutFragment.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/common/FeedbackFragment.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/initial/InitialFeedbackFragment.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/negative/brokensite/BrokenSiteNegativeFeedbackFragment.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/negative/mainreason/MainReasonNegativeFeedbackFragment.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/negative/openended/ShareOpenEndedFeedbackFragment.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/negative/subreason/SubReasonNegativeFeedbackFragment.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/positive/initial/PositiveFeedbackLandingFragment.kt
app/src/main/java/com/duckduckgo/app/global/view/DaxDialog.kt
common-ui/src/main/java/com/duckduckgo/mobile/android/ui/viewbinding/FragmentViewBindingDelegate.kt

Task/Issue URL: https://app.asana.com/0/0/1200640982441041/f
CC: 
Some of the Fragments were already using view binding. This PR:
* adds a fragment viewbinding delegate to make viewbinding in fragments easier
* uses the delegate in all fragments that were using viewbinding already
With the delegate the viewbinding for fragments will be done as follows
```kotlin
class MyNewFragment : Fragment(R.layout.my_new_fragment) {
// This will create/null the binding
private val binding: MyNewFragmentBinding by viewBinding()
...
}
```
1. fresh install from this branch and run the app
1. verify the dax dialog during onboarding works properly
1. verify the broken site works
1. verify the feedback feature works
1. verify the email protection …

Add fragment viewBinding delegate and migrate current fragments

---

app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200654961949540
CC: 
When we updated the Settings Activity to use flows we broke the state in some cases. This PR fixes that by changing the `minActiveState` to `RESUMED`
1. If you default browser is DDG, set a different one.
1. Go to settings
1. The default toggle should be disabled
1. Click on the default browser toggle
1. Go back without adding a default browser
1. The toggle should be disabled
---

Update settings ViewState correctly

---

app/src/main/java/com/duckduckgo/app/feedback/ui/negative/mainreason/MainReasonNegativeFeedbackFragment.kt
app/src/main/java/com/duckduckgo/app/feedback/ui/negative/subreason/SubReasonNegativeFeedbackFragment.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200701185339109/f
CC: 
This PR fixes a crash that happened when submitting negative feedback.
In `MainReasonNegativeFeedbackFragment` and `SubReasonNegativeFeedbackFragment` we were doing some logic in `onCreateView` and then returning `binding.root`. But Android does not allow to use view binding inside `onCreateView` that should return an inflated view, which at that point it is not.
This PR moves the logic performed in the `onCreateView` method to the `onActivityCreated` method--which is the next lifecycle method to be called--so that we can continue using view binding
1. install from develop and launch the app
1. go to settings -> share feedback
1. click in sad face …

[BUG] Fix crash when accidentally returning binding.root in onCreateView

---

app/src/androidTest/java/com/duckduckgo/app/global/api/PixelAtbRemovalInterceptorTest.kt
app/src/main/java/com/duckduckgo/app/di/NetworkModule.kt
app/src/main/java/com/duckduckgo/app/global/api/PixelAtbRemovalInterceptor.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200714585958657/f
CC: 
All our pixels currently send the ATB as a parameter but some pixels should not send such information, for instance `EMAIL_TOOLTIP_DISMISSED`, `EMAIL_USE_ALIAS`, `, EMAIL_USE_ADDRESS`.
This PR:
* Adds a `PixelAtbRemovalInterceptor` that is added to the pixel `okHttp` instance that will redact the `atb` parameter from the pixel if necessary
* Adds an inline interceptor to the pixel `okHttp` instance that just logs the final `request` url that is sent so that we can easily check in the console in debug builds
* we already had some `timbers` that logged the pixel params etc, but as we are modifying the request using an interceptor, those timber may not contain the request params …

Remove ATB params from email pixels

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Task/Issue URL: https://app.asana.com/0/414730916066338/1200761020174190/f
CC: 
Fixes a typo on the yaml file. 
This should fix the problem and enable GitHub forms.
I’ve also noticed the placeholder attribute doesn’t support multiline, so changed the schema to show hint as description.
1. Nothing to test
1. 
---

Fix typo on Form yaml file

---

app/src/main/java/com/duckduckgo/app/surrogates/api/ResourceSurrogateListService.kt

Task/Issue URL: https://app.asana.com/0/0/1200747843240362/f
CC: 
https://duckduckgo.com/contentblocking.js?l=surrogates is deprecated as it's bound to SERP releases, https://staticcdn.duckduckgo.com/surrogates.txt is the new recommended url.
1. Go to https://output.jsbin.com/sekeyeh/4
1. Make sure that the second message displayed on the page (after 5s since the first one), is equal to:
> answer: 42, typeof getAll(): "object", getAll() stringify: [null], getAll() isArray: true
---

Update surrogates.txt file location

---

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200765651134621/f
CC: 
This PR changes the weight in the new SERP variants to 1.0
1. Make sure new weight for the variant matches 1.0 and you can be allocated to them
---

Change weight in serp variants to 1.0

---

app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200757594616707
CC: 
This PR fixes a bug where the screen starts a party of its own after changing the theme in the settings screen. It checks if the toggle state has changed before emitting the command which causes the "party"
1. Go to settings
1. Change the theme to dark
1. App should now have our dark theme
1. Change the theme to light
1. App should now have our light theme
**Default browser toggle**
I could only reproduce with a Samsung device
1. Go to settings
1. Select DDG as the default browser
1. Go back to settings
1. Change the theme to dark
1. Default browser screen should not show up
--- …

Screen freezes after changing theme

---

app/src/main/res/layout/sheet_fire_clear_data.xml

Task/Issue URL:  https://github.com/duckduckgo/Android/issues/1390
Tech Design URL: No, just pick the closest attribute as the background color.
CC: 
Burn menu dialog(FireDialog) items' background color should be styled because the color of items' text has been styled.
I pick the the closest attribute, _dialogBgColor_, from file [Android\common-ui\src\main\res\values\attrs.xml](https://github.com/duckduckgo/Android/blob/develop/common-ui/src/main/res/values/attrs.xml) as the background color.
1. Open FireDialog when Light Theme is on, nothing should be changed after this PR
1. Open FireDialog when Light Theme is off, before the PR cancel button is "invisible", after the PR it will be "visible"
--- …

Fix bug (#1390)

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
app/src/test/java/com/duckduckgo/app/fire/DataClearerTimeKeeperTest.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1200914515606072
CC: 
This PR improves our CI a bit (nothing drastic). We now run our Android tests in APIs 22 and 29 (instead of 26) and always upload the test report. There are also a few tests that were a bit flaky in API 22 so this PR should either fix them or at least get us close to the reason of why they fail.
1. Make sure the workflow runs JVM tests and Android tests (22 and 29) and all of them are green
---

Improve CI

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/email/AppEmailManagerTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/api/PixelEmailRemovalInterceptorTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/di/NetworkModule.kt
app/src/main/java/com/duckduckgo/app/email/EmailManager.kt
app/src/main/java/com/duckduckgo/app/email/db/EmailDataStore.kt
app/src/main/java/com/duckduckgo/app/global/api/PixelEmailRemovalInterceptor.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1200757676857895
This PR removes the `appVersion` parameter from the email pixels. Renames the Pixel interceptor to something specific to email since it is only used by email pixels. We have also introduced a new parameter with the date when autofill was used for the last time.
_Clipboard Pixel_
1. Install the app and sign in using your duck email address.
1. Use Charles to intercept the calls or filter the logcat by `pixel url request`
1. In the overflow menu click on `Create Duck Address`
1. Pixel `email_generated_button` should be sent with the following parameters: `test`, `cohort` and `duck_address_last_used`
1. Note that the `duck_address_last_used` parameter is empty
1. In the overflow menu click on `Create Duck Address`
1. …

Amend email pixels

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
common/src/main/java/com/duckduckgo/app/global/plugins/migrations/MigrationPlugin.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/PrivacyConfigPersister.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/di/PrivacyConfigModule.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/contentblocking/RealContentBlocking.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/gpc/RealGpc.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/unprotectedtemporary/UnprotectedTemporary.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/models/JsonPrivacyConfig.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigDownloaderTest.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigPersisterTest.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/contentblocking/RealContentBlockingTest.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/gpc/RealGpcTest.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/unprotectedtemporary/RealUnprotectedTemporaryTest.kt
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabaseModels.kt
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/unprotectedtemporary/UnprotectedTemporaryDao.kt
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/unprotectedtemporary/UnprotectedTemporaryRepository.kt
privacy-config/privacy-config-store/src/test/java/com/duckduckgo/privacy/config/store/features/unprotectedtemporary/RealUnprotectedTemporaryRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1200853087962160
This PR implements the unprotected temporary list which disables all privacy protections for specific domains to avoid breakages. 
_Config parsed correctly and unprotected works as expected_
1. In the PR task, you will find a `privacy-config.json` file to be used during these tests.
1. Using Charles, map the call to `/trackerblocking/config/v1/android-config.json` with the json file from the task.
1. Go to `global-privacy-control.glitch.me`
1. In the logcat if you filter by `upgradable` you should see `global-privacy-control.glitch.me is in the remote exception list and so not upgradable`
1. Both the header and DOM signals should not be present.
1. Privacy grade icon should be solid black.
1. Click …

Remote Config (VI): Unprotected Temporary

---

app/src/main/java/com/duckduckgo/app/launch/LaunchBridgeActivity.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
app/src/main/res/layout/activity_settings.xml
app/src/main/res/layout/content_settings.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1200998021794668/f
Updates `SettingsActivity` to use `ViewBinding` instead of Kotlin synthetics
1. Launch the app and visit settings; verify everything looks as expected
2. Change **every** setting on the page, and verify the setting is applied correctly and any visual states are updated (subtitles, toggles etc...)
3. Repeat for the opposite theme color

migrate settings activity to viewbinding

---

app/src/main/java/com/duckduckgo/app/browser/favorites/FavoritesQuickAccessAdapter.kt
app/src/main/res/layout/view_quick_access_item.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1200841231124618/f
This PR increases the clickable area of the favorites quick access item to include the whole item and not just the card.
1. Add a favorite
2. Open a new tab
3. Test that a favorite is still clickable and long-clickable
| Clickable area before | Clickable area after|
|![clickable_area_before](https://user-images.githubusercontent.com/3471025/132759311-828817ca-08f9-4b95-b869-be368736d999.jpg)|![clickable_area_after](https://user-images.githubusercontent.com/3471025/132759322-eb489776-9612-4657-9c55-051b9ca3a010.jpg)|

Increase clickable area of favorite quick access item

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/duckduckgo/app/di/component/FireAnimationActivityComponent.kt
app/src/main/java/com/duckduckgo/app/settings/FireAnimationActivity.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsFireAnimationSelectorFragment.kt
app/src/main/res/layout/activity_fire_animation.xml
app/src/main/res/values/styles.xml

Task/Issue URL: https://app.asana.com/0/42792087274227/1200315340580172/f
This PR adds fire animation previews to the selection dialog in settings.
1. Go settings and tap "Fire Button animation"
2. Verify that the different options show the corresponding animation when tapped
https://user-images.githubusercontent.com/3471025/132840907-b9dd5ac7-b075-440c-b970-192e2ba4f597.mp4

Add fire animation preview to settings

---

app/src/androidTest/java/com/duckduckgo/app/bookmarks/model/BookmarksDataRepositoryTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/bookmarks/model/BookmarksRepository.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1200996756744658/f
Replaced the usage of bookmarksDao with bookmarksRepository in BrowserTabViewModel and updated BookmarksDataRepository with the needed functions.
Regression testing for the bookmark feature (add / edit / remove).

Remove bookmarksDao from BrowserTabViewModel

---

common-ui/src/main/res/values/themes.xml

Resolves #1513 
Changed text color of list items in drop down list to set as per selected mode.
1. Set DuckDuckGo Browser to dark mode
2. Find a page with a dropdown list (example: https://archlinux.org/mirrorlist/)
3. Tap the list to bring up the popup
| Before |
| After |

Issue fixed #1513 : [Bug] Dropdown menu items hard to read in dark mode

---

app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201241685107301/f
This adds pixels to the app link functionality.
**To check if these pixels are being sent, search for "app_links" in Logcat**.
1. Go to _maps.google.com_.
2. Verify that the app links Snackbar is shown with pixel `m_app_links_snackbar_shown`.
3. Tap "Open in app" on the Snackbar.
4. Verify pixel sent: `m_app_links_snackbar_open_action_pressed`.
5. Go back and open the overflow menu.
6. Tap the "Open in App" menu item.
7. Verify pixel sent: `m_nav_app_links_open_menu_item_pressed`.
8. Go back and go to "Settings".
9. Tap "Open Links in Apps".
10. Verify pixel sent: `ms_app_links_setting_pressed`.
11. Select "Ask every time" and click "Save".
12. Verify pixel sent: `ms_app_links_ask_every_time_setting_selected`.
13. …

Add app link pixels

---

app/src/androidTest/java/com/duckduckgo/app/privacy/ui/PrivacyPracticesViewModelTest.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyPracticesActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/PrivacyPracticesViewModel.kt

Task/Issue URL: https://app.asana.com/0/0/1201307807827049/f
Removed the reference to tab repository from PrivacyPracticesActivity.
- install / upgrade from this branch
- navigate to a website (e.g https://www.amazon.com, https://www.theguardian.com)
- tap on the score bubbles displayed at the left side of the URL and you'll open the "Privacy Dashboard" screen
- on "Privacy Dashboard" screen tap on "Privacy Practices" (can be "Poor Privacy Practices" / "Unknown Privacy Practices" / etc) and you'll open the "Privacy Practices" screen
-  check the "Privacy Practices" screen behaves as expected (correct information displayed for poor / unknown / etc)
https://user-images.githubusercontent.com/7963079/140561826-a635f132-bded-4c51-8430-0ca97f9b568e.mp4

Remove the usage of TabRepository in PrivacyPracticesActivity

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/requestingapp/DetectOriginatingAppPackageModern.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1200811292912063/f
Changes the way we detect the originating app package to overcome some edge cases with the existing implementation.
- Enable appTP as normal
- Use some apps with known trackers to smoke test. Verify they show up correctly in the tracker dashboard
- Launch `Noom Health & Weight` app and `MX Player`. Verify both of these show up correctly in the tracker dashboard (these are two apps which weren't correctly identified using the existing method of obtaining app package)

Alternative method of determining originating app package

---

vpn/src/main/AndroidManifest.xml
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/appupdates/AppUpdateReceiver.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201383124676579/f
During an app update, the app is killed while the APK is being swapped. The app is not automatically opened again afterwards, meaning the underlying VPNService in AppTP will not resume immediately.
By adding a BroadcastReceiver to listen for "app update" events, our process will be created and therefore the VPN Service will restart itself if it was previously running.
Add logcat filter: "Notified of app"
* Run the app and enable appTP
* Build the APK using `gradlew assembleID`
* Install it using `adb install -r`   (e.g., `adb install -r app/build/outputs/apk/internal/debug/duckduckgo-5.102.2-internal-debug.apk`)
* Verify that after a few seconds, appTP restarts (you'll see the VPN icon showing) and there is a …

Ensure AppTP restarts after an app update

---

fastlane/Fastfile
fastlane/README.md

Task/Issue URL: https://app.asana.com/0/414730916066338/1201360798240277/f
Updates fastlane script to _chomp_ string to a single line when generating the fastlane release code, instead of accepting multiple lines
There are two private lanes which cannot be called directly; make them public to make testing this easier.
- `Fastfile`, lines **128** and **142**
- change `private_lane` to `lane`
1. Run `fastlane update_fastlane_release_notes`
2. Verify there are 3 files changed
- `fastlane/metadata/android/en-CA/changelogs/51010000.txt`
- `fastlane/metadata/android/en-GB/changelogs/51010000.txt`
- `fastlane/metadata/android/en-US/changelogs/51010000.txt`
1. Run `fastlane cleanup_fastlane_release_notes`
2. Verify the 3 files above are deleted

Fix fastlane version code retrieval to trim to a single line

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/di/VpnModule.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/tracker/VpnTrackerDetector.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201395604254223/f
This PR removes the `m_atp_ev_tracker_blocked_c` pixel that was fired every time we blocked an app tracker.
The pixel is no longer needed in production
1. enable AppTP
1. open apps that send trackers
1. verify the `m_atp_ev_tracker_blocked_c` is no longer send when trackers are blocked
Same test in `develop` branch should send the `m_atp_ev_tracker_blocked_c` pixel

Remove m_atp_ev_tracker_blocked_c pixel

---

app/src/androidTest/java/com/duckduckgo/app/survey/api/SurveyDownloaderTest.kt
app/src/main/java/com/duckduckgo/app/survey/api/SurveyDownloader.kt
app/src/main/java/com/duckduckgo/app/survey/api/SurveyService.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201395604254213/f
This PR fixes (temporarily) the AppTP survey. See [asana task](https://app.asana.com/0/414730916066338/1201395604254213/f) for more details about the approach
_Test this branch_
1. install form this branch
1. ensure [v2 endpoint](https://staticcdn.duckduckgo.com/survey/v2/survey-mobile.json) does not contain a survey
1. ensure [apptp endpoint](https://staticcdn.duckduckgo.com/survey/apptp/survey-mobile.json) does not exist - open in brower should show error
1. open app
1. get past onboarding and all Dax dialogs and search widget (you'll have to open several new tabs)
1. force close the app
1. open app
1. verify app does not crash and survey is not shown
1. verify `Returning v2 response` message appears in logcat
1. …

Fix AppTP survey

---

versions.properties

Task/Issue URL: https://app.asana.com/0/414730916066338/1201403896220544/f
Room has a [bug](https://issuetracker.google.com/issues/174695268?pli=1) prior to 2.4.0-alpha03, in the native SQL library, that makes it not compile in M1 chips.
This PR just bumps room to unblock M1 developers
If you're amongst the lucky to have an M1, just build and enjoy :rocket:

Bump room version to fix build in M1 builds

---

app/src/main/java/com/duckduckgo/app/process/ProcessDetector.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201395476838293/f
This PR fixes an NPE we're seeing in some devices when getting the running procss on `Application#onCreate`.
The `getSystemService` call can return a nullable value
Nothing to test

Fix NPE when getting the running process

---

app/src/androidTest/java/com/duckduckgo/app/browser/downloader/UriUtilsFilenameExtractorTest.kt
app/src/main/java/com/duckduckgo/app/browser/downloader/FilenameExtractor.kt

This is a simplified version of https://github.com/duckduckgo/Android/pull/1530, focusing on improved handling when a `.` character is present in the guess. It also addresses an issue where URLs with multiple path segments and a MIME type was guessing the first segment of the path as the filename, as opposed to the last.
Navigate to any of the following URLs and observe the filename they're downloaded as
| URL      |  5.101.0 | This branch |
| ----------- | ----------- | ----------- | 
| https://d1x9zcshh2aa46.cloudfront.net/abc.def/example.pdf  | abc.def  | example.pdf |
| https://d1x9zcshh2aa46.cloudfront.net/abc.123/example.pdf | abc.123  | example.pdf |
| https://d1x9zcshh2aa46.cloudfront.net/123.abc/example.pdf | 123.abc  | example.pdf |
| …

Fix guessing logic when a dot is present

---

app/src/androidTest/java/com/duckduckgo/app/global/exception/UncaughtExceptionDaoTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/exception/UncaughtExceptionRepositoryDbTest.kt
common/src/main/java/com/duckduckgo/app/global/exception/UncaughtExceptionDao.kt
common/src/main/java/com/duckduckgo/app/global/exception/UncaughtExceptionRepository.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1182255336053236/f
This PR limits the frequency of duplicate exceptions from being stored into the `UncaughtException` DB. The time threshold between storing duplicates has been set to 1s.
This one is tricky to test but with some patience the issue can be simulated.
_To simulate several duplicate `UnsatisfiedLinkErrors` being sent, do the following:_
1. Checkout this branch.
2. Comment out the following in the app `build.gradle` (Line 94-99):
3. Set the `TIME_THRESHOLD_MILLIS` in `UncaughtExceptionRepository` (Line 97) to `0L`.
4. Filter Logcat with "m_d_ac_g".
5. Run the app, it should crash on startup.
6. Keep opening the app until the system shows the "DuckDuckGo keeps crashing" dialog.
7. At this point several enqueued …

Only record pixel when different exception or over time threshold

---

app/src/androidTest/java/com/duckduckgo/app/privacy/ui/ScorecardViewModelTest.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/ScorecardActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/ScorecardViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201307807827051/f
Removed the reference to tab repository from ScorecardActivity.
- install / upgrade from this branch
- navigate to a website (e.g https://www.amazon.com, https://www.duckduckgo.com)
- tap on the score bubbles displayed at the left side of the URL and you'll open the "Privacy Dashboard" screen
- on "Privacy Dashboard" screen tap on the image at the top which displays the privacy grade and you'll open the "Privacy Grade" screen
-  check the "Privacy Grade" screen behaves as expected (correct information displayed for Grade A / B+ / etc)
https://user-images.githubusercontent.com/7963079/142637932-8ba88671-c423-4492-b2b8-85b24a0e0853.mp4

Remove the usage of TabRepository in ScorecardActivity

---

app/src/androidTest/java/com/duckduckgo/app/privacy/ui/TrackerNetworksViewModelTest.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/TrackerNetworksActivity.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/TrackerNetworksViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201307807827050/f
Removed the reference to tab repository from TrackerNetworksActivity.
- install / upgrade from this branch
- navigate to a website (e.g https://www.amazon.com, https://www.nfl.com)
- tap on the score bubbles displayed at the left side of the URL and you'll open the "Privacy Dashboard" screen
- on "Privacy Dashboard" screen tap on "Trackers Blocked" and you'll open the "Tracker Networks" screen
-  check the "Tracker Networks" screen behaves as expected (correct information displayed for 0 trackers / at least one tracker)
https://user-images.githubusercontent.com/7963079/142636604-b649f69e-6c1d-4ab4-968c-641af372662e.mp4

Remove the usage of TabRepository in TrackerNetworksActivity

---

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/rating/InitialPromptTypeDeciderTest.kt
app/src/androidTest/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/rating/di/RatingModule.kt
app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/global/rating/PromptTypeDecider.kt
app/src/main/java/com/duckduckgo/app/onboarding/di/WelcomePageModule.kt
app/src/main/java/com/duckduckgo/app/onboarding/store/OnboardingSharedPreferences.kt
app/src/main/java/com/duckduckgo/app/onboarding/store/OnboardingStore.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageView.kt
app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/res/layout-land/content_onboarding_welcome.xml
app/src/main/res/layout-w600dp/include_experiment_returning_users_cta.xml
app/src/main/res/layout/include_dax_dialog_cta.xml
app/src/main/res/layout/include_experiment_returning_users_cta.xml
app/src/main/res/layout/include_experiment_returning_users_cta_buttons.xml
app/src/main/res/layout/include_experimental_cta_content.xml
app/src/main/res/values/string-untranslated.xml
common-ui/src/main/res/values/styles.xml
statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt

Task/Issue URL: https://app.asana.com/0/0/1201408441367239/f
This adds a 3-way experiment (control and 2 variants). Videos for all versions and exact details can be found in https://app.asana.com/0/1142021229838617/1201393848577545/f
**_Control_**
_**Code changes before testing**: Change the weighting of all variants in the VariantManager to 0.0 and keep the weight of "zk" to 1.0_
1. Freshly install the app.
2. On the Welcome page you should see the normal welcome screen:
- text: _The Internet can be kinda creepy. Not to worry! Searching and browsing privately is easier than you think._
- only one button with the label: _Let’s Do It!_
3. Tap on Let’s Do It! button (Pixel: _m_odp_p_)
4. You should see the normal onboarding.
**_Variant 1 - New users path_**
_**Code changes before testing**: …

Android: Implement retention experiment to treat returning users differently

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpPacketProcessor.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/udp/UdpPacketProcessor.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201433035781456/f
It is possible to experience a cancelled key exception when registering for events using the selector. These represent local issues with that connection and shouldn't propagate up to affect the `VPNService` running
This was initially observed when using [Lazada](https://play.google.com/store/apps/details?id=com.lazada.android&hl=en_US&gl=US), however it is intermittent there and unclear what the exact steps are to reproduce.
You can simulate what happens by manually cancelling the key.
**TcbDeviceToNetwork**, line 280
Add this: `tcb.selectionKey.cancel()`

Catch CancelledKeyExceptions to prevent service crashing

---

common-ui/src/main/res/values/themes.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1201451355283252/f
This PR fixes the list item color on the Broken Sites dialog when using the dark theme.
1. Activate the dark theme.
2. Tap the overflow menu and then "Report Broken Site".
3. Tap "Describe what happened".
4. Verify that the dialog list items are the correct color.
(Tested on API 21 and 30)

Bugfix: BrokenSite dialog using incorrect theme

---

app/src/main/java/com/duckduckgo/app/di/component/AppEnjoymentDialogFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/BrokenSiteNegativeFeedbackFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/BrowserTabFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/DefaultBrowserPageComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/DownloadConfirmationFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/EmailProtectionNotSupportedFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/EmailProtectionSignInFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/EmailProtectionSignOutFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/GiveFeedbackDialogFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/InitialFeedbackFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/MainReasonNegativeFeedbackFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/PositiveFeedbackLandingFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/RateAppDialogFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/ShareOpenEndedFeedbackFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/SiteLocationPermissionDialogComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/SubReasonNegativeFeedbackFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/WelcomePageComponent.kt
common-ui/src/main/java/com/duckduckgo/app/global/DuckDuckGoActivity.kt
di/build.gradle
di/src/main/java/dagger/android/AndroidInjector.kt
di/src/main/java/dagger/android/DaggerActivity.kt
di/src/main/java/dagger/android/support/AndroidSupportInjection.kt
vpn-main/src/main/java/com/duckduckgo/mobile/android/vpn/di/DeviceShieldActivityFeedFragmentComponent.kt
vpn-main/src/main/java/com/duckduckgo/mobile/android/vpn/di/DeviceShieldFragmentComponent.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201432423603230/f
In PR #1597 we're harmonising the way we name dagger components and how we contribute dependencies to them. As a recap:
* Use @SingletonIn(AppScope::class) for app scope
* Use @SingletonIn(ActivityScope::class) for activity scope
* Use @SingletonIn(FragmentScope::class) for fragment scope
This a follow up PR to enable nesting those scopes:
* AppScope -> ActivityScope -> FragmentScope
Nesting means:
* child scopes can get access to dependencies in their parent scopes (but not the other way around), ie.
* `FragmentScope` would get access to deps in Fragment, Activity and App scopes
* `ActivityScope` would get access to deps in Activity and App scopes
* `AppScope` would get access to deps in App scope
The PR changes …

Implement Activity->Fragment dagger component nesting

---

settings.gradle

Task/Issue URL: https://app.asana.com/0/414730916066338/1201433136298885/f
* Some time ago we enabled gradle local build cache
* Bugs in kotlin incremental compilation sometimes interfere with the local cache
* This generally happens when modifying Dagger components
* The changes are sometimes not picked up by the compiler
* The easy fix when that happens is to remove the local cache directory
* Given that this is a local cache, it makes sense to be able to enable/disable it locally through local.properties
This PR will:
* allow to enable/disable local build cache through a property in local.properties file
* the name of the property will be local.build.cache and will take true or false values
1. remove `build-cache` directory from root project directory
1. run `./gradlew clean`
1. ensure …

Allow configure local cache using local.properties file

---

app/src/androidTest/java/com/duckduckgo/app/browser/WebViewRequestInterceptorTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/useragent/UserAgentProviderTest.kt
app/src/androidTest/java/com/duckduckgo/app/global/api/ApiRequestInterceptorTest.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/browser/useragent/UserAgentProvider.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201472407198007
We currently try to access the default user agent from `WebSettings` on startup. This is not necessary and having two side effects:
1. Delaying our startup time and hence being a factor in the cause of ANRs
2. Crash the app in some cases where the WebView process is not ready yet.
_User agent creation correctly referred_
1. Go to the task and apply the `Reproduce_ANR.patch` patch. This will create a new trace when the app launches.
2. Download https://github.com/Grigory-Rylov/android-methods-profiler to analyze the trace.
3. Launch the app, wait a few seconds and then close the app.
4. From the device file explorer, go to `data/data/com/duckduckgo.com.mobile.android.debug` and download the trace created.
5. Analyze …

Use a Provider to lazily initialize the default user agent

---

app/src/main/java/com/duckduckgo/app/privacy/cleanup/TrackersDbCleanerScheduler.kt

Task/Issue URL: https://app.asana.com/0/0/1201472407198058/f
We're seeing an increase of the app `onCreate` execution time. Some of the lifecycle observers may have a role in that increase. In particular the `TrackersDbCleanerScheduler` class was executing some useless code to try skip scheduling a worker when it was already scheduled.
That resulted in calling `getWorkInfosByTag` which is rather slow.
We can safely remove that call as we're already using `enqueueUniquePeriodicWork` in cobination with `KEEP` policy, which achieves the same
1. open the app
1. VERIFY `Registering application lifecycle observer: com.duckduckgo.app.privacy.cleanup.TrackersDbCleanerScheduler` appears in the logcat

Remove useless call to getWorkInfosByTag to reduce app onCreate execution time

---

app/src/main/java/com/duckduckgo/app/email/ui/EmailProtectionSignOutFragment.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201458023475315/f
App crashing in email sign out screen when the device is rotated.
- open the app and go to Settings → Email Protection
- add your Duck email address
- when on Email protection screen rotate the device (the screen mentioning your Personal Duck Address at the top)
- notice app doesn't crash

BUG: Crash on Email protection sign in screen rotation

---

app/src/main/res/layout/fragment_email_protection_sign_in.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1201451970726639/f
Email sign in screen was not scrollable and not all content could be seen in landscape.
- open the app and go to Settings → Email Protection
- notice you have the 3 buttons on screen "Join the Private Waitlist", "I have an Invite Code", "I already have a Duck Address" and a text at the bottom mentioning "We do not save your emails. Learn more."
- rotate the device
- make sure you can scroll and see the whole content as in portrait, including the 3 buttons mentioned above and the text at the bottom.

BUG: Screen not scrolling and buttons are not reachable in landscape

---

common-ui/src/main/java/com/duckduckgo/app/global/DuckDuckGoActivity.kt
di/build.gradle
di/src/main/java/dagger/android/AndroidInjector.kt
di/src/main/java/dagger/android/DaggerActivity.kt
di/src/main/java/dagger/android/support/AndroidSupportInjection.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201432423603230/f
In PR #1597 we're harmonising the way we name dagger components and how we contribute dependencies to them. As a recap:
* Use @SingletonIn(AppScope::class) for app scope
* Use @SingletonIn(ActivityScope::class) for activity scope
* Use @SingletonIn(FragmentScope::class) for fragment scope
This a follow up PR to enable nesting those scopes:
* AppScope -> ActivityScope -> FragmentScope
Nesting means:
* child scopes can get access to dependencies in their parent scopes (but not the other way around), ie.
* `FragmentScope` would get access to deps in Fragment, Activity and App scopes
* `ActivityScope` would get access to deps in Activity and App scopes
* `AppScope` would get access to deps in App scope
The PR changes …

Allow AppScope -> ActivityScope -> FragmentScope dagger scope nesting

---

app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
app/src/main/java/com/duckduckgo/app/pixels/EnqueuedPixelWorker.kt
app/src/test/java/com/duckduckgo/app/pixels/EnqueuedPixelWorkerTest.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201464810536290/f
* The current app onCreate path takes longer than it should
* One of the main contributors is the pixel dependency in the app class
* The pixel dependency is used to:
* send the mf pixel onCreate
* send the ml pixel onStart
* the ml pixel doesn't affect the onCreate path
* the mf pixel doesn't need to be sent at onCreate, and can be scheduled to be sent later
This PR removes the pixel dependency from the app class by:
* creating a LifecycleEventObserver that will:
* send the ml pixel onStart--except when the app is launched as a result of a fire button press
* schedules the sending of the mf pixel
_test the ml pixel_
* install from this branch
* launch the app
* verify the ml pixel is sent
* press the fire button
* …

Move the pixel dependency out of application class

---

app/src/main/java/com/duckduckgo/app/browser/useragent/UserAgentProvider.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201519018374192/f
This PR intends to capture a crash when getting WebView default user agent on some devices.
_No changes_
1. run the app
2. visit any website
3. Filter logs by `User Agent is`
4. Ensure your UA matches the one on your device (e.g: check if chrome version is the one installed on your device)
_Capture crash_
1. Go to `provideDefaultUserAgent` method in `UserAgentProvider`
2. hardcode `throw RuntimeException("")`  before `WebSettings.getDefaultUserAgent(context)`
3. run the app
4. visit any website
5. Ensure app does not crash

Capture default UserAgent crashes

---

app/src/androidTest/java/com/duckduckgo/app/email/AppEmailManagerTest.kt
app/src/androidTest/java/com/duckduckgo/app/email/db/EmailEncryptedSharedPreferencesTest.kt
app/src/main/java/com/duckduckgo/app/email/EmailManager.kt
app/src/main/java/com/duckduckgo/app/email/db/EmailDataStore.kt
app/src/main/java/com/duckduckgo/app/email/di/EmailModule.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/waitlist/store/DefaultAppTrackingProtectionWaitlistDataStore.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201464810536292/f
Adding a `by lazy` to both the ATP encrypted preferences.
Simplified the `EmailDataStore` so that encrypted preferences are not needed during instance creation
2. run smoke tests for email waitlist and appTP waitlist
3. go to "Settings" -> "Developer settings" and enable start up tracing
4. close and reopen app
5. download the trace
6. ensure encrypted preferences is only present in the SurveyDownloader path -- in develop it's present in many other paths during app onCreate

Lazily initialize encrypted shared preferences

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201451355283242/f
**Problem**
When a `NonHttpAppLink` is intercepted (_intent://_ etc.) and the `fallbackUrl` is used (When no activities are found for the initial `Intent`), then the `fallbackUrl` is loaded as a normal web link.
This is problematic if the `fallbackUrl` is a _market://_ link for example, which will fail to load in the `WebView`.
**Solution**
If the `fallbackUrl` is a `NonHttpAppLink`, then an `Intent` for that link is created and launched if the initial `Intent` does not resolve any activities.
_Before_
1. Build the app from _develop_.
2. Visit: https://studio.click.godaddy.com/FVXM/f2c4755d
3. Verify that the link does not load.
_After_
1. Build the app from this branch.
2. Visit: …

Bugfix: Handle non-http fallback URL

---

vpn-store/build.gradle
vpn-store/schemas/com.duckduckgo.mobile.android.vpn.store.VpnDatabase/18.json
vpn-store/schemas/com.duckduckgo.mobile.android.vpn.store.VpnDatabase/19.json
vpn-store/src/androidTest/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabaseTest.kt
vpn-store/src/androidTest/java/com/duckduckgo/mobile/android/vpn/trackers/AppTrackerRepositoryTest.kt
vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/VpnAppTrackerSystemAppsOverridesDao.kt
vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabase.kt
vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/trackers/AppTracker.kt
vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/trackers/AppTrackerRepository.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/apps/TrackingProtectionAppsRepository.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/blocklist/AppTrackerExclusionListUpdateWorker.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/blocklist/AppTrackerListDownloader.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/blocklist/AppTrackerListService.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/di/VpnAppModule.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201403499648047/f
Some beta users have flagged that some of the popular apps that are installed in their device don't appear under the "Manage protection for your apps" screen. This is the case for eg. Chrome
These apps don't appear because they're flagged by Android as "system apps" as all system apps are unprotected but also don't show in the "Manage protection for your apps" screen:
* they don't appear in there because there's a lot of internal Android libraries are also system apps
* showing them all would clutter that screen and create confusion
However we need to add those that are popular apps so that users have control over their protection.
This PR uses a new endpoint to fetch the system app overrides and also modifies the …

Add logic to provide system app overrides

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/requestingapp/DetectOriginatingAppPackageModern.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/processor/requestingapp/requestingapp/DetectOriginatingAppPackageModernTest.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201522043688142/f
* We're seeing some crashes when getting the connection owner UID.
* the result of these crashes is likely to disable AppTP
* easy fix is try-catch the call to `getConnectionOwnerUid` and return `Process.INVALID_UID`
Optional, just code review

Fix crash when getting connection owner UID

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/udp/UdpPacketProcessor.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201501533153172/f
We're seeing a crash in the UDP pipeline, in the `deviceToNetworkProcessing` method when trying to write in the datagram channel.
The exception is `IllegalArgumentException` but we're only catching `IOExceptions`.
At the time of writing this is affecting 284 users, which is a lot when considering how many we've got in the beta waitlist.
We can't reproduce this issue, so just code review.

Catch IllegalArgumentException in deviceToNetworkProcessing

---

app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
build.gradle
versions.properties
vpn/src/main/java/dummy/ui/VpnControllerActivity.kt

Task/Issue URL: https://app.asana.com/0/0/1201539840759397/f
Upgrades the kotlin version. This creates some compilation errors, and an incompatibility with Anvil so that is updated too.
|Library|Before|After|Notes|
|---|---|---|---|
|Kotlin|1.5.10|1.6.10||
|Anvil|2.3.3|2.3.10-1-6-0|See [Anvil releases](https://github.com/square/anvil/releases) to explain prefix

Upgrade to Kotlin 1.6.10

---

vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsActivity.kt
vpn-internal/src/main/res/layout/activity_vpn_internal_settings.xml

Task/Issue URL: https://app.asana.com/0/414730916066338/1201546096051166/f
Enable a way to access the diagnostics view on `INTERNAL` builds
- On an **INTERNAL** build flavor, visit settings.
- Open **AppTP dev settings**
- Verify **View Diagnostics Data** shows up
- Verify clicking on it reveals the diagnostics view

Add link to diagnostics from internal settings

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/downloader/FileDownloadBroadcastReceiver.kt
app/src/main/java/com/duckduckgo/app/browser/downloader/NetworkFileDownloader.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201507366427630/f
Send 3 types of pixels to roughly understand how many downloads fail compared to all downloads.
- install the app from this branch and have logcat filtered by `V/RxBasedPixel: Pixel sent: m_download_request_`
- download various files and check you get in the log the `m_download_request_started` / `m_download_request_succeeded` / `m_download_request_failed` as expected
_Example URLs:_
- Data URL success -> Go to https://dopiaza.org/tools/datauri/examples/index.php long press on the photo and select `Download Image`. It should trigger `m_download_request_started` and `m_download_request_succeeded`
- Can't find a way to test Data URL fail.
- Network URL success -> Go to …

Send Pixels for download start / success / fail

---

app/src/main/java/com/duckduckgo/app/buildconfig/RealAppBuildConfig.kt
appbuildconfig-api/src/main/java/com/duckduckgo/appbuildconfig/api/AppBuildConfig.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/DeviceInfoCollector.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/bugreport/DeviceInfoCollectorTest.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201472311099046/f
Some of the app breakage reports we get relate to specific OEM issues. We are adding some device information to the report to aid during debugging
Add logcat filter: `m_atp_breakage_report`
_Test app breakage report_
2. enable AppTP
3. go to "App Tracking Protection Screen"
4. click on "Please report an issue"
5. select any app and click SUBMIT
6. click NEXT
7. select any option and click SUBMIT
8. copy the `breakageMetadata` base64 value
9. you can use https://onlinestringtools.com/convert-base64-to-string and jsonlint to convert to JSON
10. verify the json contains a `deviceInfo` section with manufacturer, bildFlavor, model and os params

Add device info to the app breakage report

---

app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201620824138997/f
The "Choose default browser" dialog is displayed twice when you switch the app from foreground to background and back and then you tap on "I've been here before". See the video attached to the Asana task.
- checkout this branch
- tweak the variant manager by changing the weight of "zk" to 0.0 in VariantManager.kt
- install
- on Welcome Page screen you should see 2 buttons "I'm new!" and "I've been here before." Don't tap any of them yet.
- while on Welcome Page screen put the app in background and back to foreground a couple of times
- on Welcome Page screen tap on "I've been here before." and you should see a dialog to choose the default browser. Once you choose you'll not see the same dialog again, you'll see the …

Bug: Choose default browser displayed twice

---

privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/Gpc.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/gpc/GpcFeature.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/gpc/GpcPlugin.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/gpc/RealGpc.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/gpc/GpcPluginTest.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/gpc/RealGpcTest.kt
privacy-config/privacy-config-impl/src/test/resources/json/gpc.json
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabaseModels.kt
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/gpc/GpcExceptionsDao.kt
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/gpc/GpcHeadersDao.kt
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/gpc/GpcRepository.kt
privacy-config/privacy-config-store/src/test/java/com/duckduckgo/privacy/config/store/features/gpc/RealGpcRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1201624035922285
This PR deletes the hardcoded headers list for GPC in the app and instead uses the list from the remote config.
_Headers sent when navigating via links_
1. Install and launch the app
2. Go to https://globalprivacycontrol.org 
3. On the top of the site it should say `GPC signal detected`
4. Click below where it says `Test against the reference server`
5. Header should be present in the next site.

Move GPC headers to remote config

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/DeviceShieldOnboardingViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201641519620987/f
Fix bug where the ATP onboarding pixel was not sent. The onboarding activity was finished, cancelling the VM coroutine scope, that cancel the pixel sender job.
The fix uses the app coroutine scope to ensure the pixel goes through.
_Test onboarding pixel_

Ensure ATP onboarding pixel is sent

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ExcludedAppsViewModel.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/apps/ExcludedAppsViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201640572393751/f
We were not honour the skip reportint intent from the user.
_Repro steps_
* Go to Manage Protections for your Apps
* Disable protection for an app
* Select It stopped working as expected
* Click SKIP
* Expected results: Prompt closes, app is disabled
* Actual results: Issue report screen shown (which should only be shown when SUBMIT is clicked)
_Test fix_

Fix: honour user intent to skip reporting

---

app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteActivity.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewVersionProvider.kt
app/src/main/java/com/duckduckgo/app/browser/WebViewVersionSource.kt
app/src/main/java/com/duckduckgo/app/pixels/EnqueuedPixelWorker.kt
app/src/test/java/com/duckduckgo/app/browser/MajorWebViewVersionProviderTest.kt
app/src/test/java/com/duckduckgo/app/pixels/EnqueuedPixelWorkerTest.kt
statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1157223223343562/f
This PR adds the following:
1.) A provider for the webview's major version that uses the `WebViewCompat.getCurrentWebViewPackage` as the underlying implementation.
2.) Adds the "`webview_version`" as a parameter for the `ml` pixel.
1. Install and launch the debug version of the app from this branch
2. FIlter logcat by `V/RxBasedPixel: Pixel sent: ml`
3. The filtered message should include the webview_version=X in the params. Example: `V/RxBasedPixel: Pixel sent: ml with params: {webview_version=91} {}`
4. For API level 26 and below, the `webview_version` could be `unknown` in some cases.
Needs to be tested in API Level 25 or below.

Add webview version to ml pixel

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/DeviceShieldTileService.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201550925053701/f
There's an NPE in the tile service. However it is not clear why it happens.
One thing I saw is that the `pollDeviceShieldState` may not be cancelled correctly all the time. So adding a `ConflatedJob` to ensure of that.
NA

Ensure the deviceShieldStatePollingJob is properly cancelled

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/VpnAppTrackerListInfoCollector.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201539333793164/f
During the breakage it is benefitial to know whether the reported app was enabled by default of not.
This PR adds a field inside the `vpnTrackerLists` JSON object that contains whether the package ID was unprotected (ie. inside the exclusion list) or not. 
The new field is called `reportedAppUnprotectedByDefault` and can take a "true" or "false" value.
_Test_

Add reported app default protection info to breakage report

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201656298066485/f
Description
One of the issues described in Bug: AppTP can't be toggled ON is that the switch to enable the VPN doesn't work properly. 
Looking at the code, we are currently using the wrong API to listen to the widget updates.
Objective
Ensure we use the proper API for the Switch,  that is the CheckedChangeListener instead of the ClickListener
_Enable VPN_
_Disable VPN_

AppTP: Ensure Enable VPN Switch uses proper API

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/heartbeat/VpnServiceHeartbeat.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201677777496441/f
Do not restart the VPN when revoked by other VPNs
The HB mechanism works already in both branches:
* when restarting upon error/revoke
* when not restarting when VPN was OFFed as result of user intent
As we're only changing the `revoke` form one branch to the other, there's no need to test

Do not restart VPN when revoked

---

vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/health/BadHealthMitigationFeature.kt
vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsActivity.kt
vpn-internal/src/main/res/layout/activity_vpn_internal_settings.xml
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppBadHealthStateHandler.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201677777496472/f
* we currently can disable the entire bad health detection
* but can't keep detection running and disable mitigation
* while this is important both for triaging breakage and debugging purposes
This PR simply adds an internal feature toggle for the bad health mitigation
_Test feature toggle_

Internal feature to disable mitigation

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ExcludedAppsViewModel.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/apps/ExcludedAppsViewModelTest.kt

Task/Issue URL:  https://app.asana.com/0/1157893581871903/1201688799714577
One of the potential causes that may have caused Incident: unexpected spike in app breakage reports 2022-01-15 is a fix in the flow to open the feedback form (✓ Bug: Increase scrolling area for Disabling app Dialog)
There are two user journeys that end up in that feedback form:
Via the Info panel in the Tracker activity screen "Report issues"
Via the App Protection Management screen, when using the toggle
_ Disable App Protection Dialog_
_ Trackers activity screen_

added pixels to ctas that open the feedback form

---

vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/rules/ExclusionRulesRepository.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/AppHealthStateCollector.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPHealthMonitor.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201677777496562/f
The tracer packet alert it too noisy at the moment with a lot of false positives. Lowering the sensitivity so that it needs to be sustain for at least one minute
Incidentally also making MTU and MSS values match, which was something we overlooked int he past
Smoke tests for ApptP

Adjust sensitivity of tracer packets and tune MTU size

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/TunPacketWriter.kt
vpn/src/main/java/xyz/hexene/localvpn/ByteBufferPool.java

Task/Issue URL: https://app.asana.com/0/0/1201701653646856/f
This PR fixes the memory leak caused by tracer buffer.
Tracer packets have an associated `ByteBuffer` needed to inser the packet in the network-to-device queue. One we take the packet out and process it, we were not releasing it. Causing a memory leak.
This PR:
* releases the bytebuffer associated to the tracer packet
* Incidentally
* adds some log statements for RUN write errors
* double ensures that `acquire` buffers are cleared so that they're ready to be used
Smoke tests for AppTP

Fix TracerPacket memory leak

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt

Task/Issue URL: https://app.asana.com/0/0/1201660793106474/f
Fix bug where the `m_atp_ev_selected_disable_protection_c` was not sent.
_Verify pixel is sent_

Fix bug where m_atp_ev_selected_disable_protection_c was not sent

---

vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/health/HealthStatsStore.kt
vpn/src/androidTest/java/com/duckduckgo/mobile/android/vpn/health/HealthClassifierTest.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPHealthMonitor.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/HealthClassifier.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/HealthMetricCounter.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/TunPacketReader.kt
vpn/src/main/java/dummy/ui/VpnDiagnosticsActivity.kt
vpn/src/main/java/xyz/hexene/localvpn/Packet.java
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt

Task/Issue URL: https://app.asana.com/0/0/1201677777496539/f
The VPN currently drops any IP packet which protocol is other than UDP or TCP.
We want to undertand how widespread those protocols are and whether they may have any relation to breakage. This PR:
* adds a pixel `m_atp_ev_unknown_packet_%d_c` that will fire every time we drop an unknown packet
* adds the unknown packets count to the bad health report
_Test_

Add unknown (protocol) packets to the tunReads alert report information

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt

Task/Issue URL: https://app.asana.com/0/0/1201677777496527/f
We want to know the impact on first ever reports from users that the bad health mitigation will have.
This PR adds a unique pixel `m_atp_breakage_report_u` that will fire only once ever the first time a user submits reports a breakage.
The pixel will carry the same info as the `m_atp_breakage_report`.
_Test Pixel_

Send unique pixel upon first breakage report

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
app/src/main/java/com/duckduckgo/app/widget/AddWidgetLauncher.kt
app/src/main/java/com/duckduckgo/app/widget/WidgetAddedReceiver.kt
app/src/main/res/layout/content_settings_general.xml
app/src/main/res/values/string-untranslated.xml
app/src/test/java/com/duckduckgo/app/widget/AddWidgetCompatLauncherTest.kt
app/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Task/Issue URL: https://app.asana.com/0/488551667048375/1201677824560317/f
This PR adds the following:
- Add a new entry in Setting page for "Home Screen Widget" that allows the user to add widget through the settings page
- Send a new Pixel `ms_add_home_screen_widget_clicked` when the new setting item is clicked.
- Introduces a reusable `AddWidgetLauncher` that contains the logic on when to use the `AppWidgetManager` vs the `AddWidgetInstructions`.
- Use the `AddWidgetLauncher` in `BrowseTabFragment`.
- Introduce `WidgetAddedReceiver` that shows a toast whenever a widget is added through the app (both CTA and Settings)
- Changed the label for the widgets to "Favorites" and "Search" instead of "Favorites Widget" and "Search Widget"
Scenario 1: User has a device that supports automatically …

Promote Add Widget in Settings

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201677777496544/f
Adding network information to the breakage report, the network information added is:
* current network the device is in (WIFI or CELLULAR)
* previous network the device was in
* how many seconds since the last network switch
Example:
```json
"networkInfo": {
"previousNetwork": "CELLULAR",
"currentNetwork": "WIFI",
"secondsSinceLastSwitch": 33
}
```
_Test network info inside breakage report_

Add network switch to breakage report

---

vpn-store/schemas/com.duckduckgo.mobile.android.vpn.store.AppHealthDatabase/4.json
vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/AppHealthDao.kt
vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/model/AppHealthState.kt
vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/AppHealthDatabase.kt
vpn/src/androidTest/java/com/duckduckgo/mobile/android/vpn/health/AppBadHealthStateHandlerTest.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/AppHealthStateCollector.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppBadHealthStateHandler.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppHealthMonitorManager.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/TunPacketWriter.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/health/AppHealthMonitorManagerTest.kt

* https://app.asana.com/0/0/1201677777496526/f
* https://app.asana.com/0/0/1201677777496524/f
* https://app.asana.com/0/0/1201711685020933/f
This PR enables the bad health mitigation in production (Play flavor) and adds some instrumentations
_Test mitigation is enabled in production_
_Test first-ever breakage report pixel_
_Test bad health instrumentation_

Enable bad health mitigation in production

---

vpn-main/src/main/java/com/duckduckgo/mobile/android/vpn/di/VpnStateCallbackServiceComponent.kt
vpn/src/main/AndroidManifest.xml
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/state/VpnStateMonitorService.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201711685020940/f
Currently it is the HeartBeat that detects when the VPN has been killed for reasons other than user intent or revokes. In such cases the HB will bring the VPN back up.
The HB is a worker, and so it is the scheduled periodically every 15min (min period supported for work manager).
The main issu with that approach is that many users may noticed the VPN switched off (as a result of VPN process killed) way before the HB had the time to bring it back up.
This PR uses a complementary new way to bring-up the VPN upon sudden kill.
* Added a new service `VpnStateMonitorService`
* The `TrackerBlockingVpnService` will bind to the new `VpnStateMonitorService` when started and stopped (or killed)
* Every time the binding is …

Faster VPN bring-up

---

vpn/src/main/AndroidManifest.xml

Task/Issue URL:  https://app.asana.com/0/1157893581871903/1201759869770201
Our HB is currently listening to the [ACTION_BOOT_COMPLETED](https://developer.android.com/reference/android/content/Intent#ACTION_BOOT_COMPLETED) intent, which tells us that the device has finished booting. 
There is another intent, [ACTION_REBOOT](https://developer.android.com/reference/android/content/Intent#ACTION_REBOOT), that is called by system apps after the phone has finished rebooting.
The theory is that we might be missing device restarts that could be used to restart our VPN.  [Other VPNs are listening to both of these intents with high priority](https://developer.android.com/reference/android/content/Intent#ACTION_REBOOT), therefore being able to start their service before ours.

added priority and reboot intent to the HB

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201757992830589/f
App Links will now open in a new task. This resolves some usability issues with certain App Links.

Add FLAG_ACTIVITY_NEW_TASK to App Link Intents

---

vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppHealthCallback.kt
vpn/src/androidTest/java/com/duckduckgo/mobile/android/vpn/health/AppBadHealthStateHandlerTest.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppBadHealthStateHandler.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPHealthMonitor.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/HealthClassifier.kt
vpn/src/main/java/dummy/ui/VpnDiagnosticsActivity.kt
vpn/src/main/java/xyz/hexene/localvpn/ByteBufferPool.java

Task/Issue URL: https://app.asana.com/0/0/1201752109049661/f
In order to monitor the impact of the upcoming memory leak fixes, we are instrumenting the AppTP buffer allocations to be sent in breakage reports.
_Feature 1_

Add buffer alloc health metrics

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpDeviceToNetwork.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpNetworkToDevice.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpSocketWriter.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/udp/UdpPacketProcessor.kt

Task/Issue URL: https://app.asana.com/0/0/1201748194657736/f
After auditing the AppTP runtime, [these](https://app.asana.com/0/0/1201778487362550/f) are the memory leaks we've found. Basically places where the buffers need to be released because they're no longer in used, but they're not.
_Memory leak test_
_AppTP smoke tests_

Fix native memory leaks

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/cohort/CohortPixelInterceptor.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1201790503855341/f
Allow the onboarding pixel to be sent without AppTP cohort
_Test onboarding pixel_
Doing the same test above in current develop would not send the pixel and `Pixel URL request dropped` would appear for all onboarding pixels

Allow onboarding pixel to be sent without cohort

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/AppTPCompanyTrackersActivity.kt

Task/Issue URL:  https://app.asana.com/0/1157893581871903/1201814886085130
When launch the feedback screen from the Tracker details screen we are showing the wrong page of the Feedback report journey. Instead of showing the Description form, we are showing the page that asks about the login information
This PR fixes it

Tracker details screen should open feedback description form

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldMostRecentActivity.kt
vpn/src/main/res/layout/activity_device_shield_all_tracer_activity.xml

Task/Issue URL:  https://app.asana.com/0/1157893581871903/1201814886085137
The Most Recent activity screen is crashing upon opening. The wrong view reference is being used.

Fix crash in Most Recent Activity

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppBadHealthStateHandler.kt

Task/Issue URL: https://app.asana.com/0/0/1201748194657735/f
* https://github.com/duckduckgo/Android/pull/1731 implemented the VPN-process restart mitigation for internal builds only
* This PR enables that in production builds
_Test VPN process restart_

Enable the VPN-process restart mitigation in production builds

---

vpn-store/schemas/com.duckduckgo.mobile.android.vpn.store.AppHealthDatabase/5.json
vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/model/AppHealthState.kt
vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/AppHealthDatabase.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppBadHealthStateHandler.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201814931393743/f
Adds the `badHealthDurationSeconds` parameter to the bad health pixel
_Test fresh install_
_Test fresh install_

Add badHealthDurationSeconds to the bad health reports

---

anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/AnrSupervisor.kt

Task/Issue URL: https://app.asana.com/0/0/1201861300112042/f
The `ANR Supervisor` is prone to false negatives when the debugger is attached, especially if stepping through code on the main thread for instance.
Suggested logcat filter: `AnrSupervisor checking for ANRs`
1. Run (not debug) the project, and ensure you **do see** the log lines above
2. Debug (not run) the project, and ensure you **do not** see the log lines

AnrSupervisor will not run if debugger is attached

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201864646357756/f
Ditto
_Test lastSwitchTimestampMillis is redacted_

Remove lastSwitchTimestampMillis from breakage report

---

app/src/main/java/com/duckduckgo/app/global/view/TypeAnimationTextView.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201874321697430/f
Uses `BreakIterator` to iterate over the correct text boundaries in the `TypeAnimationTextView`.
This prevents emojis from showing their component chars during the typing animation.
_CTAs_
Tested on: API 30, API 21 emulators, Pixel 5 (Android 12).

Improve text typing animation

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/network/connection/ConnectionMonitor.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/network/connection/NetworkRequestHandler.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/network/connection/NetworkRequestHandlerTest.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201814931393750/f
To improve network hand-off, monitor the network switches and set underlying networks accordingly.
Do this only in internal builds for now to verify there's no side effects.
**Notes for the reviewer**
Why using a `Handler` in `NetworkRequestHandler`?
* For the same network switch, the `NetworkCallback`s can be called several times with slightly different values
* We want to ensure order of execution so we need a queue
* And also we want the creation of the underlying network set to happen in a background thread
* `HandlerThread` give us both the queue and the thread for free
_Test underlying networks are set only in internal builds_
In addition, smoke AppTP tests

Monitor network switches and set underlying networks in internal builds

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppBadHealthStateHandler.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPHealthMonitor.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201862327796480/f
Lowerin the bad health detection thresholds to improve the time to repair. See [task](https://app.asana.com/0/1199371158290272/1201862327796480/f) for more dettails
_Test new thresholds_

Adjust bad health detection thresholds

---

app/src/main/java/com/duckduckgo/app/email/EmailJavascriptInterface.kt
app/src/main/java/com/duckduckgo/app/email/EmailManager.kt
app/src/test/java/com/duckduckgo/app/email/AppEmailManagerTest.kt
app/src/test/java/com/duckduckgo/app/email/EmailJavascriptInterfaceTest.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1201900580321807/f
Update to allow requesting user data from Android devices
1. Update `common/src/main/java/com/duckduckgo/app/global/AppUrl.kt` to have host value align with dev instance
2. Update autofill to https://github.com/duckduckgo/duckduckgo-autofill/pull/52
3. Build browser
4. Go to my dev instance
5. If needed, log in with production duck email username
6. See "Autofill" tab with duck email and private address generator

Get data from device for email settings page

---

vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/VpnServiceStateStatsDao.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/stats/VpnServiceStateLogger.kt

Task/Issue URL: https://app.asana.com/0/1174433894299346/1201913071568577
In [AppTP: Improve communication for AppTP disables](https://app.asana.com/0/1174433894299346/1201630444699765) we changed how the Trackers screen toggle receives its information. 
Before we polled the VpnService state every second, now we relay on a callback that tells us when the VPN as started / stopped.
After doing the change, we've seen cases where the toggle and the vpn state are out of sync. The toggle shows AppTP as disabled, but the VPN service is running.

solve race condition in vpn state query

---

app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201921632645241
This PR reverts a bug introduced in the previous release, that messes up with the tab positioning in the Tab Switcher
_Check tab ordering in tab switcher_
Reverts duckduckgo/Android#1757
Fixes https://github.com/duckduckgo/Android/issues/1785

Revert "Replaced liveTabs with flowTabs."

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnRoutes.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/service/VpnRoutesTest.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201438077555953/f
There seems to be a bug in some OEMs that breaks wi-fi calling when there's an active android VPN.
Samsung seems to be one of the OEMs affected. As Samsung footprint is very high amongst our users, we fix this issue by adding exclusion routes to the t-mobile and verizon ePDG servers.
Perform smoke tests for AppTP
Verify that the `VpnRoutes` contain the following routes:
* T-mobile wi-fi calling
* 66.94.2.0/24  -> 66.94.2.255
* 66.94.6.0/23  -> 66.94.7.255
* 66.94.8.0/22  -> 66.94.11.255 
* 208.54.0.0/16 -> 208.54.255.255
* Verizon wi-fi calling
* 66.174.0.0/16 -> 66.174.255.255
* 69.82.0.0/15  -> 69.83.255.255
* 69.96.0.0/13  -> 69.103.255.255
* 70.192.0.0/11 -> 70.223.255.255
* 72.96.0.0/9   -> 72.127.255.255
* …

Exclude VPN routes to fix wi-fi calling

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/TunPacketReader.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/packet/PacketExtension.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/requestingapp/DetectOriginatingAppPackageLegacy.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpDeviceToNetwork.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpNetworkToDevice.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/hostname/PayloadBytesExtractor.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/tracker/VpnTrackerDetector.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/udp/UdpPacketProcessor.kt
vpn/src/main/java/xyz/hexene/localvpn/IP4Header.java
vpn/src/main/java/xyz/hexene/localvpn/IP6Header.java
vpn/src/main/java/xyz/hexene/localvpn/IPHeader.java
vpn/src/main/java/xyz/hexene/localvpn/Packet.java
vpn/src/main/java/xyz/hexene/localvpn/TransportProtocol.java
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/processor/requestingapp/requestingapp/ConnectionInfoTestUtil.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/processor/requestingapp/requestingapp/OriginatingAppPackageIdentifierStrategyTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201928304609012/f
Add support for IPv6 traffic in AppTP.
See [this task](https://app.asana.com/0/488551667048375/1201928304609012/f) and [this other task](https://app.asana.com/0/488551667048375/1201862327796575) for full context.
_Best effort test_
* Testing if Ipv6 works is hard because it depends on external factors like the ISP.
* This why we enable it for internal builds only for now. Because we have some internal users that were hitting IPv6 issues and they already verified this improvement should work
* The best you can do is to switch to cellular network
* Filter logcat by `TcpNetworkToDevice`
* And see if you spot any IPv6 address in the logs
_Smoke tests for AppTP_
Repat smoke tests below for both PLAY and INTERNAL builds

Add support for IPv6 in internal builds only

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/network/RealVpnDetector.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1201931173358115/f
But was introduced in #1763 where AppTP can't no longer be turned OFF
_Verify appTP can be turned off_

Fix issue where AppTP can't be turned off

---

vpn/src/main/java/xyz/hexene/localvpn/ByteBufferPool.java
vpn/src/test/java/xyz/hexene/localvpn/ByteBufferPoolTest.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201949747150726/f
Releasing the byte buffers that back the packets is a tedious process, and it can happen that we try to release the same buffer twice.
As the buffers a direct `ByteBuffers`, when released, they end up in a pool of available buffers, which is implemented by a linked queue. It can happen that the same buffer is released twice, resulting in a duplicated entry in the queue, eventually ending up in possible buffer corruption as it can be allocated twice.
This PR ensures that it won't be possible to release the same buffer twice.
Smoke tests in AppTP.
The newly added tests pass.

Guard against duplicated byte buffer pool releases

---

common/src/main/java/com/duckduckgo/app/global/extensions/ContextExtensions.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/dns/PrivateDnsSettingMonitor.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
vpn/src/main/java/dummy/ui/VpnPreferences.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201931173358074/f
Try to fix the issues with private DNS settings.
When users go to Android settings and set the private DNS, the systems expects to use DoT[H] however the VPN default DNS will not support it. And that will create issues in certain cases.
The PR listens for the `private_dns_mode` setting and adds those as well to the VPN configuration.
This is done for now in internal builds only to give it some bake time
_Check private DNS is added to VPN config in internal builds_
Repeat this tests above for both WIFI and CELLULAR connections. The one difference may be that in CELLULAR you may also see IPv6 DNS addresses.

Detect and set private DNS in AppTP

---

app/src/main/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptor.kt
app/src/test/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptorTest.kt

Task/Issue URL: https://app.asana.com/0/72649045549333/1201931173358064/f
Remove ATB information from all AppTP pixels
_Test ATB info is gone_

Remove ATB information from AppTP pixels

---

vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpFeatureName.kt
vpn-internal/build.gradle
vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsActivity.kt
vpn-internal/src/main/res/layout/activity_vpn_internal_settings.xml
vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/VpnFeatureToggleStore.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpFeatureToggleRepository.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpFeatureTogglesPlugin.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/feature/FeatureToggleExtensions.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/TunPacketReader.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpFeatureTogglesPluginTest.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/feature/RealAppTpFeatureToggleRepositoryTest.kt
vpn/vpn-build.gradle

Task/Issue URL: https://app.asana.com/0/1199371158290272/1201967142475482/f
Some of the current AppTP features are only available in internal builds:
* IP6 support
* network switching handling
* private DNS handling
However internal users are not able to enable/disable them, making it hard to know whether they cause side (breakage) effects.
This PR adds entries in the AppTP internal settings screen for those features. And does that in a way that in the future is ready to integrate with [remote privacy config](https://app.asana.com/0/1199371158290272/1201967142475463/f)
_Test the feature enable/disable

Add ipv6, private DNS and network switching handling to AppTP internal settings

---

app/src/androidTest/java/com/duckduckgo/app/referencetests/FireproofingReferenceTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202000811071024/f
Skips a few Fireproof-related tests if running on API 28 which would otherwise fail.
Check`FireproofingReferenceTest` runs on API 28

Skip Fireproofing tests on API 28 due to known issues

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnUncaughtExceptionHandler.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/service/VpnUncaughtExceptionHandlerTest.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202000697555267/f
The crashes coming from the `vpn` process do not currently appear in SAFE, but now that it's more mainstream we do want to have them in there. See [this task](https://app.asana.com/0/414730916066338/1202000697555267/f) for more context.
Just code review, we're basically copy-pasting the logic from the `AlertingUncaughtExceptionHandler`

Record the VPN process crashes as GLOBAL

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202050072225379/f
Remove the `netId` value from breakage

Redact netId values from breakage

---

app/src/main/java/com/duckduckgo/app/global/shortcut/AppShortcutCreator.kt

Task/Issue URL: https://app.asana.com/0/276630244458377/1202055094426961/f
Wraps the call interacting with `ShortcutManager` in a `runCatching` block. There are times when this call will fail with an `IllegalStateException`. When this happens, we don't want a crash but can silently swallow the exception given the low-importance of app shortcuts being registered.
1. Test the app starts as normal
2. Tests the app shortcuts are created as normal (ie, that you can long press on the app icon and use the shortcuts)

Wrap shortcut creation in a runCatching

---

app/src/main/java/com/duckduckgo/app/di/component/AppEnjoymentDialogFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/BrokenSiteNegativeFeedbackFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/BrowserTabFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/DefaultBrowserPageComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/DownloadConfirmationFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/EmailProtectionNotSupportedFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/EmailProtectionSignInFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/EmailProtectionSignOutFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/GiveFeedbackDialogFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/InitialFeedbackFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/MainReasonNegativeFeedbackFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/PositiveFeedbackLandingFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/RateAppDialogFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/ShareOpenEndedFeedbackFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/SiteLocationPermissionDialogComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/SubReasonNegativeFeedbackFragmentComponent.kt
app/src/main/java/com/duckduckgo/app/di/component/WelcomePageComponent.kt
vpn-main/src/main/java/com/duckduckgo/mobile/android/vpn/di/DeviceShieldActivityFeedFragmentComponent.kt
vpn-main/src/main/java/com/duckduckgo/mobile/android/vpn/di/DeviceShieldFragmentComponent.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202049355677833/f
fix nesting hierarchy for fragments by:
Change from @ContributesTo(AppScope::class) to @ContributesTo(ActivityScope::class) on *FragmentComponentProvider
Change from @ContributesTo(AppScope::class) to @ContributesTo(ActivityScope::class) on *FragmentBindingModule

Fix dependency injection hierarchy for fragments 

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/cookies/AppThirdPartyCookieManagerTest.kt
app/src/androidTest/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClientTest.kt
app/src/androidTest/java/com/duckduckgo/app/referencetests/FireproofingReferenceTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/cookies/CookieManagerProvider.kt
app/src/main/java/com/duckduckgo/app/browser/cookies/ThirdPartyCookieManager.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClient.kt
app/src/main/java/com/duckduckgo/app/fire/CookieRemover.kt
app/src/main/java/com/duckduckgo/app/fire/DuckDuckGoCookieManager.kt
app/src/test/java/com/duckduckgo/app/fire/WebViewCookieManagerTest.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202085579672992/f
This makes the CookieManager dependency lazy (In a similar way to: https://github.com/duckduckgo/Android/pull/1775) which should address some related crashes.
_Feature 1_

Make CookieManager lazy

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/blocklist/AppTrackerListService.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1202122946916649/f
[This task](https://app.asana.com/0/414730916066338/1201619168694507/f) mistakenly left the `blocklist.json` in beta endpoint.
Revert back to production endpoint

Revert back to production endpoint for AppTP blocklist.json

---

app/src/androidTest/java/com/duckduckgo/espresso/privacy/RequestBlockingTest.kt
app/src/androidTest/java/com/duckduckgo/espresso/privacy/SurrogatesTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202159825360139/f
This PR tries to fix 2 failing privacy tests after we renamed some views in the new menu.
_Feature 1_

Fix broken privacy test due to wrong view id

---

common/src/main/java/com/duckduckgo/app/global/extensions/ContextExtensions.kt
vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSetting.kt
vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsActivity.kt
vpn-internal/src/main/res/layout/activity_vpn_internal_settings.xml
vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/health/HealthStatsStore.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/feature/settings/ConnectivityChecksSettingPlugin.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPHealthMonitor.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/HealthClassifier.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/HealthMetricCounter.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/NetworkConnectivityHealthHandler.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpFeatureConfigImplTest.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSettingTest.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/feature/settings/BadHealthMitigationSettingPluginTest.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/feature/settings/ConnectivityChecksSettingPluginTest.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/feature/settings/Ipv6PrivacySettingPluginTest.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/feature/settings/NetworkSwitchSettingPluginTest.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/feature/settings/PrivateDnsSettingPluginTest.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/feature/settings/SetActiveNetworkSettingPluginTest.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1202061499094755/f
Periodically check whether the VPN has network connectivity and report when it does not but the device continues having connectivity
_Test connectivity checks doesn't trigger health alert when device has no connection_
_Test connectivity checks trigger health alert when only VPN has no connection_

Check and report VPN connectivity issues

---

downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/NetworkFileDownloader.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1201550925053703/f
Wrapped code in try/catch for Android 10 specific crash in NetworkFileDownloader.
Can't be reproduced. It happens only on Android 10 and it's very infrequent on Pixel devices -> only 0.23% in the last 30 days.
Instead of crashing, now we display a snackbar and a notification to inform the user about the failed download. See the 2 attached screenshots.
| Show snackbar  | Show notification |

Crash in NetworkFileDownloader

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModel.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/apps/TrackingProtectionAppsRepository.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageAppListViewModel.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageAppListViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202185118693825/f
_Reproduce crash (install from develop)_
_Crash fix (install from this branch)_

fixed crash when trying to grab info from uninstalled apps

---

app/src/main/java/com/duckduckgo/app/fire/fireproofwebsite/ui/FireproofWebsiteAdapter.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202170635398721/f
We are showing by mistake an 'Edit' option in overflow menu for a Fireproof Site. It is removed now
_Feature 1_
- Go to Settings > Fireproof Sites and make sure you have 1 or more fireproof sites added
- Tap on fireproof site overflow menu

Remove 'Edit' option from Fireproof Sites

---

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesPluginPointCodeGenerator.kt
anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesSubComponentCodeGenerator.kt
anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesViewModelCodeGenerator.kt
anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/Extensions.kt
app/src/main/java/com/duckduckgo/app/browser/httpauth/WebViewHttpAuthStore.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/HttpsUpgrader.kt
build.gradle
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/cohort/CohortStore.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpSocketWriter.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/tracker/AppTrackerRecorder.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/udp/UdpChannelCache.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202216477980438/f
Bump Anvil to 2.4.0
* This requires to update the anvil codegen
Incidentally modified the following classes now that anvil supports repeatable annotations
* WebViewHttpAuthStore
* HttpsUpgrader
* NetworkTypeCollector
* CohortStore
* TcpSocketWriter
* AppTrackerRecorder
* UdpChannelCache
_Build_
_Other classes_
_Smoke tests_
_Code inspection_
For the following classes:
* WebViewHttpAuthStore
* HttpsUpgrader
* NetworkTypeCollector
* CohortStore
* TcpSocketWriter
* AppTrackerRecorder
* UdpChannelCache

Update anvil to 2.4.0

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/apps/AppCategoryDetector.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202260283121034/f
`packageManager.getApplicationInfo` can throw `NameNotFoundException` but we were never catching that in the `AppCategoryDetector`.
The PR catches the exception and returns `AppCategory.Undefined` when it happens
Just code review

Ensure getApplicationInfo doesn't crash when app name not found

---

app/src/androidTest/java/com/duckduckgo/app/statistics/api/RxPixelSenderTest.kt
statistics/src/main/java/com/duckduckgo/app/statistics/AtbInitializer.kt
statistics/src/main/java/com/duckduckgo/app/statistics/api/PixelSender.kt

Task/Issue URL: https://app.asana.com/0/0/1202260594569391/f
@OnLifecycleEvent is now deprecated. Updated code in statistics module to use `DefaultLifecycleObserver`
- Launch the app
- Check in the Logcat that the following Logs appear:

Migrate from @OnLifecycleEvent - statistics module

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202236755602993/f
Fixed isServiceRunning on API 23.
On API 23 services are still reported as running up to 1 min after they're stopped. Changed the code to check the started property for this API version only.
- install from this branch on a device running Android M
- go to Settings and enable AppTP
- enable and disable AppTP and check it's indeed enabled / disabled
- check the Before / After videos attached on the Asana task.

AppTP: Disabling tracking protection issue on API 23

---

vpn/src/androidTest/java/com/duckduckgo/mobile/android/vpn/prefs/VpnSharedPreferencesProviderImplTest.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/cohort/CohortStore.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/prefs/VpnSharedPreferencesProvider.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnStore.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/cohort/RealCohortStoreTest.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/SharedPreferencesVpnStoreTest.kt

Task/Issue URL: https://app.asana.com/0/1199371158290272/1202279501986167/f
The Harmony multi process shared preferences creates the shared prefs file under a different folder and does not migrate previously existing shared preferences.
This causes a bug in DDG, to repro the bug:
* install from `5.124.0.1-nightly`
* launch app and enable AppTP
* update from develop
* launch app and go to Settings -> App Tracking Protection
* expected: AppTP screen is open
* actual: onboarding is shown again
This PR adds a migration to the `VpnSharedPreferencesProviderImpl` that is executed when shared prefs are returned using the provider
_Check migration_
(cohort and AppTP pixels are also migrated, but not tested as migration works the same in all instalces)

Migrate prefs to harmony when necessary

---

vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsActivity.kt
vpn-internal/src/main/res/layout/activity_vpn_internal_settings.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1202290988165066/f
This PR adds couple internal options in the "AppTP dev settings" to:
* protect all apps
* restore default protections
To keep the PR simple as this is convenience internal feature for testing, the following limitations/cases are not tackled:
* when protecting or restoring protections the screen may flicker a bit, this is because we automatically restart the VPN for the config changes to take affect, and the Internal settings activity has a banner that appears when VPN is OFF and goes away when OFF
* `Protect all apps` option has no effect on Games. This is because games are detected at runtime
* If the user unprotects an app that is not in the exclusion list, clicking on `Protect all apps` will not undo this change …

Add internal features to protect all apps or restore default protections

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpDeviceToNetwork.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpNetworkToDevice.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/udp/UdpPacketProcessor.kt

Task/Issue URL: https://app.asana.com/0/1200905986587319/1202311975987092/f
Updated the code to stop packet processing when InterruptedException is caught. This ensures we won't have more threads processing packets after a VPN restart.
To reproduce the issue:
- fresh install from develop (internal build)
- enable App Tracking Protection
- go to Settings -> AppTP dev settings and tap on Protect all apps. This will ensure Slack is protected and also triggers a VPN restart
- open Slack and upload a photo
- notice it takes a long time and then fails.
To test the fix:
- fresh install from this branch (internal build)
- enable App Tracking Protection
- go to Settings -> AppTP dev settings and tap on Protect all apps. This will ensure Slack is protected and also triggers a VPN restart
- open …

AppTP: Slack upload fails consistently after VPN restart

---

privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/observers/LocalPrivacyConfigObserver.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/workers/RemoteConfigDownloadWorker.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/observers/LocalPrivacyConfigObserverTest.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1202260594569388
This PR migrates the privacy config module to LifecycleEventObserver
_Observers still work_

Migrate privacy config to LifecycleObserver

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt

Task/Issue URL: https://app.asana.com/0/1202279501986195/1202331659918964/f
The `registerNetworkCallback` can throw SecurityException. According to [this issue](https://issuetracker.google.com/issues/175055271) that should have been solved, but we see crashes. I found [examples](https://github.com/microsoft/cpp_client_telemetry/pull/798/files) of code that try-catch the registering. We already do so for the call to unregister, so it make sense to have it symetric anyway.
Nothing to test

Try-catch registerNetworkCallback

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202329383243646/f
This PR fixes an exception that occurs when clicking on an AMP link that opens in a new tab.
_Test pages_
_Links that open in a new tab_
_Pasting into the search bar_
_Opening from another app_

Use post to load extracted new tab AMP links

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/VpnAppTrackerListInfoCollector.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/bugreport/VpnAppTrackerListInfoCollectorTest.kt

Task/Issue URL: https://app.asana.com/0/1202279501986195/1202345990054913/f
Full context in [this task](https://app.asana.com/0/1202279501986195/1202345990054913/f)
Incidentally added some unit tests that were missing before.
_Test report metadata_
- fresh install from this branch
- launch app and enable AppTP
- filter logcay by `breakage_report`
- report breakage for any app
- override protection for any app and then report breakage for it

Add protection info to breakage reports

---

app/src/androidTest/java/com/duckduckgo/app/browser/WebViewRequestInterceptorTest.kt
app/src/androidTest/java/com/duckduckgo/app/fakes/FeatureToggleFake.kt
app/src/androidTest/java/com/duckduckgo/app/fakes/UserAgentFake.kt
app/src/androidTest/java/com/duckduckgo/app/fakes/UserAllowListRepositoryFake.kt
app/src/androidTest/java/com/duckduckgo/app/global/api/ApiRequestInterceptorTest.kt
app/src/androidTest/java/com/duckduckgo/app/referencetests/DomainsReferenceTest.kt
app/src/androidTest/java/com/duckduckgo/app/referencetests/SurrogatesReferenceTest.kt
app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/browser/useragent/UserAgentProvider.kt
app/src/main/java/com/duckduckgo/app/privacy/db/UserAllowListRepository.kt
app/src/test/java/com/duckduckgo/app/browser/useragent/UserAgentProviderTest.kt
privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeatureName.kt
privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/UserAgent.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/di/PrivacyConfigModule.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/useragent/RealUserAgent.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/useragent/UserAgentFeature.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/useragent/UserAgentPlugin.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/useragent/RealUserAgentTest.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/useragent/UserAgentPluginTest.kt
privacy-config/privacy-config-impl/src/test/resources/json/useragent.json
privacy-config/privacy-config-impl/src/test/resources/json/useragent_disabled.json
privacy-config/privacy-config-impl/src/test/resources/json/useragent_min_supported_version.json
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabaseModels.kt
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/useragent/UserAgentDao.kt
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/useragent/UserAgentRepository.kt
privacy-config/privacy-config-store/src/test/java/com/duckduckgo/privacy/config/store/features/useragent/RealUserAgentRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1202317386594677
This PR moves the hardcoded UA exception lists to the remote config.
Before you begin, using Charles or similar map the request to `https://staticcdn.duckduckgo.com/trackerblocking/config/v2/android-config.json` to return the json attached in the Asana task.
Our UA looks like `Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.61 Mobile DuckDuckGo/5 Safari/537.36`
Notice the application component: `DuckDuckGo/5`
and the version component: `Version/4.0`
_User Agent works as expected_
_Disable User Agent_

Move UA exceptions to remote config

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
device-auth/device-auth-impl/src/main/java/com/duckduckgo/deviceauth/impl/AuthLauncher.kt
device-auth/device-auth-impl/src/main/java/com/duckduckgo/deviceauth/impl/RealDeviceAuthenticator.kt
modules/autofill/autofill-impl/build.gradle
modules/autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementActivity.kt

Task/Issue URL: https://app.asana.com/0/0/1202418883857448/f
PR depends on: https://github.com/duckduckgo/Android/pull/1994
This PR integrates the device auth flow into the autofill flow.
This doesn't include the full flow in management page since the page will likely change in implementation since it is still in the MVP stage. Will address this in https://app.asana.com/0/0/1202418883857449/f
_User has device auth enrolled on device_
_User has no device auth enrolled on device_

Integrate device authentication to autofill

---

modules/autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorage.kt
secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorageException.kt
secure-storage/secure-storage-impl/build.gradle
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/L2DataTransformer.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/RealSecureStorage.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/SecureStorageKeyGenerator.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/SecureStorageKeyManager.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/SecureStorageKeyProvider.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/di/SecureStorageModule.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/encryption/EncryptionHelper.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/encryption/RandomBytesGenerator.kt
secure-storage/secure-storage-store/schemas/com.duckduckgo.securestorage.store.db.SecureStorageDatabase/1.json
secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageKeyStore.kt
secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/db/WebsiteLoginCredentialsEntity.kt

Task/Issue URL: https://app.asana.com/0/0/1202210732792279/f
This PR adds the L2 encryption for  passwords in the secure storage.
**What's not yet included:**
- expiring sessions / passwords
- user authentication on secure storage
Use autofill [Make sure to clear storage before you install this changes)

Implement L2 encryption on secure storage

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
common/src/main/java/com/duckduckgo/app/global/UriExtension.kt
privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/TrackingParameters.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/trackingparameters/RealTrackingParameters.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/trackingparameters/TrackingParameterReferenceTest.kt
privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackingparameters/tracking_parameters_matching_tests.json
privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackingparameters/tracking_parameters_reference.json
privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/trackingparameters/TrackingParametersRepository.kt
privacy-config/privacy-config-store/src/test/java/com/duckduckgo/privacy/config/store/features/trackingparameters/RealTrackingParametersRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202431148390057/f
This PR adds updated tracking parameter removal reference tests and associated code changes.
Changes:
- Parameter removal is now case-sensitive.
- Values are no longer decoded when rebuilding the URI.
- An initiator URL is now passed from the `BrowserWebViewClient`. This is used for exception checking.

Update tracking parameter removal reference tests

---

app/src/main/java/com/duckduckgo/app/global/image/GlobalGlideModule.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202472465643896/f
Override UA for Glide requests and use our default UA.
_Repro bug_
_Test Fix

Override Glide UA

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpDeviceToNetwork.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpNetworkToDevice.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpPacketProcessor.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnQueues.kt
vpn/src/main/java/xyz/hexene/localvpn/TCB.java

Task/Issue URL: https://app.asana.com/0/1202279501986195/1202454731900853/f
**Background**: We were changing channel keys' interest sets in two threads (`TcpNetworkToDevice` and `TcpDeviceToNetwork`), which is unsafe [[1]](http://rox-xmlrpc.sourceforge.net/niotut/) [[2]](https://stackoverflow.com/a/12824411). To get around the problem, we were using `sleep(10)` in between `select` operations. Without the `sleep`, a deadlock occurs between the two threads (where one is stuck on `register` and the other on `select`), indicating a thread-safety issue. There is a related discussion [here](https://stackoverflow.com/a/3191377) on the dangers of using `sleep` to make Selectors behave.
**This PR**: Fixes how we use the Selector by making sure all Selector-related operations are done on a single …

Thread Safety for Selector Operations

---

modules/autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/jsbridge/response/AutofillResponseWriter.kt

Task/Issue URL: https://app.asana.com/0/0/1202520205565765/f
Ensure we don't offer to save credentials when autofill global toggle disabled

Disable save prompt when autofill toggle disabled

---

modules/autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/internal/RealInternalTestUserChecker.kt
modules/autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/internal/RealInternalTestUserCheckerTest.kt

Task/Issue URL: https://app.asana.com/0/0/1202494823153095/f
This PR includes automatically making the user an internal test user when using an internal build.
_Internal build_
_Internal build, failed verifications_
_Other builds_

use buildflavor to determine internal test user

---

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpDeviceToNetwork.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/hostname/ByteArrayExtension.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/hostname/HostnameExtractor.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/hostname/HostnameHeaderExtractor.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/tracker/VpnTrackerDetector.kt
vpn/src/main/java/xyz/hexene/localvpn/TCB.java
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/processor/tcp/hostname/ByteArrayExtensionTest.kt
vpn/src/test/java/com/duckduckgo/mobile/android/vpn/processor/tcp/hostname/PlaintextHostExtractorTest.kt

Task/Issue URL: https://app.asana.com/0/276630244458377/1202400910824455/f
This PR eliminates bottlenecks caused by hostname extraction. With the bottlenecks removed, our upload speeds can now reach ~300Mbps (up from ~100Mbps). Main changes were:
1. Do not extract the hostname twice
2. Avoid making copies of the payload - eliminate `ByteArray` to `String` conversion of the payload
3. Try TLS-based extraction first since most of the traffic is encrypted
- open apps that have trackers and verify it blocks
- perform speed tests and verify the download is similar and upload is better than develop
- downloads and uploads work as in develop

Increase Upload Speeds

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/BrowserAutofill.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/AutofillJavascriptInterface.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/ExistingCredentialStoreInterrogatingMatchDetector.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/AutofillStoredBackJavascriptInterfaceTest.kt

Without this delay, the form submission / navigation web events can be blocked, meaning we save the credentials but the user is left on the form, needing to hit the submission button again.
Task/Issue URL: https://app.asana.com/0/488551667048375/1202612639205162/f
As noted in the linked task, we can hit a problem with forms not submitting correctly if we immediately show a DialogFragment from the @Javainterface function. This is a strange problem, but also one hit on other platforms like iOS.
The workaround is to introduce a short delay before showing the DialogFragments for saving or updating a credential
Also included is a small tidy-up of coroutine usage around these areas, which weren't quite right before.
1. Visit https://trello.com/login
2. Enter credentials and hit login button
3. …

Add delay before showing autofill save/update prompts

---

autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202611392391295/f
- Fix for logic when updating credentials for a specific domain url
- Add more tests for class SecureStoreBackedAutofillStore
_Updating credentials from browser_

Fix update bug for autofill

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/AutofillJavascriptInterface.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/InlineBrowserAutofill.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillClipboardInteractor.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/AutofillStoredBackJavascriptInterfaceTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202621847351497/f
- Remove injected context in ActivityScoped AutofillManagement Screen ViewModel
- Move device auth check from browser fragment into AutofillJavascript to have a single place that defines availability of autofill. This also fixes the issue where when device auth is removed from device anduser attempts to autofill aftyer refreshing website. Previously, autofill is still enabled (bottom sheet is shown) but can't autofill since no device auth is available. Now that is fixed.
_Clipboard changes_
_Auth check changes_

Address remaining comments on MVP autofill

---

downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DefaultFileDownloadNotificationManager.kt
downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/UrlFileDownloadCallManager.kt
downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/UrlFileDownloader.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202612974845126/f
When the app is closed all ongoing downloads are cancelled, but the in progress notifications linger.
This PR ensures the download in progress notifications are also cancelled.
_Test bug fix_
- Install from https://github.com/duckduckgo/Android/pull/2039
- open app and start downloading several files from http://ipv4.download.thinkbroadband.com
- close the app
- expected: download in progress notifications should be dismissed
- actual:   download in progress notifications are NOT dismissed
- open app and start downloading several files from http://ipv4.download.thinkbroadband.com
- close the app

Dismiss download in progress notifications on app close

---

common-ui/build.gradle
common-ui/src/main/java/com/duckduckgo/mobile/android/ui/viewbinding/FragmentViewBindingDelegate.kt

Task/Issue URL: https://app.asana.com/0/0/1202260594569384/f
@OnLifecycleEvent is now deprecated. Updated code in common-ui module to use `DefaultLifecycleObserver`
- Launch the app
- Open any fragment which uses viewBinding (e.g. Email Protection)
- Check in the Logcat that the following Logs appear:

Migrate from @OnLifecycleEvent: common-ui module

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/store/AutofillStore.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/ui/ExistingCredentialMatchDetector.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/ExistingCredentialStoreInterrogatingMatchDetector.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/saving/AutofillSavingCredentialsViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/selecting/AutofillSelectCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/selecting/CredentialTextExtractor.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/selecting/CredentialsPickerRecyclerAdapter.kt
autofill/autofill-impl/src/main/res/layout/content_autofill_save_new_credentials.xml
autofill/autofill-impl/src/main/res/values/autofill-impl-strings-untranslated.xml
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/saving/AutofillSavingCredentialsViewModelTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/selecting/CredentialTextExtractorTest.kt
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt

Task/Issue URL: https://app.asana.com/0/0/1202630343540911/f
Supports savings logins without usernames. This includes accepting the login, the "save" dialog and the "choose login" dialog when autofilling.
**Setup**
I don't have a suggestion for a site which only saves the password, so need to hack this unless you know one. 
In `BrowserTabFragment.onCredentialsAvailableToSave()`, add this as the first line of the function to fake the username coming through as `null` 
👉 `val credentials = credentials.copy(username = null)`
**Setup**
- Ensure the hack from the previous test case is still in place.
- Ensure a previous login was saved (so onboarding dialog not shown)
**Instructions**
Easiest way to test this scenario is to manually edit an existing login; edit it by manually deleting the …

Support logins with missing usernames

---

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/Theming.kt

Task/Issue URL: https://app.asana.com/0/414730916066338/1202360890245126/f
Use `ResourcesCompat.getDrawable` instead of `context.resources.getDrawable` when getting `getThemedDrawable()`.

Replace context.resources.getDrawable with ResourcesCompat.getDrawable

---

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/store/AutofillStore.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/di/AutofillModule.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementActivity.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/LastUpdatedTimeProvider.kt
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt
secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorage.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/RealSecureStorage.kt
secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageRepository.kt
secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/db/WebsiteLoginCredentialsDao.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202666734291055/f
- Saving of last updated time upon saving of the credential
- Update of last updated time (UI and DB) when saving edits to a credential
- Update of notes and domain title(UI and DB) when saving edits to a credential
- Move reference to currently being edited credential from the CredentialModeFragment to the ViewModel removing any reference to the state from the fragment.
_Save credential saves last updated time_
_Updating credentials persists_

Autofill engine: support saving and updating last updated time and notes along with credentials

---

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/domain/app/LoginCredentials.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/AutofillDomainFormatter.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillCharacterValidator.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementRecyclerAdapter.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/CredentialGrouper.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/CredentialInitialExtractor.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/CredentialListSorter.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementListMode.kt
autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_list_mode.xml
autofill/autofill-impl/src/main/res/layout/item_row_autofill_credentials_management_screen_header.xml
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/AutofillDomainFormatterDomainNameOnlyTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/CredentialGrouperTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/CredentialInitialExtractorTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/CredentialListSorterTest.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/LatinCharacterValidatorTest.kt

- [Management screen (List view): sort entries alphabetically](https://app.asana.com/0/1202630133908322/1202630133908322/f)
- [Management screen (List view): add visual groupings to the credential list view](https://app.asana.com/0/1202630133908323/1202630133908323/f)
Sorts the list of credentials and adds the visual groupings between them in the credential management screen.

Improve autofill list UX

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/AutofillJavascriptInterface.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/AutofillStoredBackJavascriptInterfaceTest.kt
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202696748120680/f
- In `AutofillStoredBackJavascriptInterface`, ensure that `AvailableInputTypes` json has `credentials` set to `false` if autofill is disabled (either through setting or when user is not internal tester). There's no real need to query for that data here since when `autofillCredentials` is set to `false`, the `credentials` field doesn't really matter.
- In `SecureStoreBackedAutofillStore`, `getCredentials(rawUrl: String`) returns `emptylist` when autofill is disabled. This is necessary since we call  SecureStoreBackedAutofillStore in the DuckDuckGoFaviconManager and we don't need the real Autofill data when the feature is not available at this point.
_Not internal user_
_Is internal user and feature …

Remove queries to secure storage when autofill feature is disabled

---

app/src/internal/java/com/duckduckgo/app/dev/settings/privacy/TrackerDataDevReceiver.kt
app/src/main/java/com/duckduckgo/app/di/StoreModule.kt
app/src/main/java/com/duckduckgo/app/onboarding/store/UserStageStore.kt
lint-rules/src/main/java/com/duckduckgo/lint/DuckDuckGoIssueRegistry.kt
lint-rules/src/main/java/com/duckduckgo/lint/NoLifecycleObserverDetector.kt
lint-rules/src/test/java/com/duckduckgo/lint/NoLifecycleObserverTest.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/debug/DeviceShieldNotificationsDebugReceiver.kt
vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/report/PrivacyReportViewModel.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202643385187950/f
Ditto, no more extending `LifecycleObserver`
_Test lint rule_

Add a lint rule to not extend LifecycleObserver

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/0/0/1202574319510580/f
Android 10 introduced scope-storage that require the `requestLegacyExternalStorage` set to `true` and request the `WRITE_EXTERNAL_STORAGE` permission to be able to directly create files in the `Downloads` folder.
_Bug repro and fix_

Fix permission issues with API 29 related to scope-storage

---

app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/store/AutofillStore.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/AutofillJavascriptInterface.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/AutofillStoredBackJavascriptInterfaceTest.kt
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt
secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorage.kt
secure-storage/secure-storage-impl/build.gradle
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/RealSecureStorage.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/RealSecureStorageRepositoryFactory.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/SecureStorageDatabaseFactory.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/di/SecureStorageModule.kt
secure-storage/secure-storage-impl/src/test/java/com/duckduckgo/securestorage/impl/RealSecureStorageTest.kt
secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageRepository.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202696696022583/f
- Check SecureStorage.canAccessSecureStorage when determining if autofill is available. There's no point in enabling autofill if we can't decrypt/encrypt data correctly.
- Separate autofillEnabled and autofillAvailable since they are 2 separate things and have different side effects to the autofill feature.
- Handle scenarios where encryptedsharedprefs failed to load AND room database creation. We want to avoid encrypting / decrypting the database when the l1key is null. Moreover we don't want to automatically regenerate the L1key and use it to encrypt the database since it is possible that the encryptedsharedprefs failed and just can't access the already existing L1key.
_Autofill is not available …

Autofill: Fix net.sqlcipher.database.SQLiteException in WebsiteLoginCredentialsDao

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/0/1202682552759994/f
This PR includes the viewmodel changes part for the task above. Changes include:
- ViewModel onDeleteCredentials and onEditCredentials now accepts the LoginCredentials instead of obtaining it from the Viewing/Editing CredentialMode.
- Update AutofillManagementCredentialsMode to obtain its own LoginCredentials from the ViewState when editing and deleting.
_Edit and delete still works!_

Allow Autofill viewmodel edit and delete to pass logincredentials

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/SaveStateWatcher.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt
common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/OutLinedTextInput.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202673680180939/f
- Add logic for hiding the save icon in Edit mode when all fields are set to empty.
_Remove all fields on edit mode_

Disable save in edit mode when all fields are empty

---

common/build.gradle
common/src/main/java/com/duckduckgo/app/global/formatters/time/TimeDiffFormatter.kt
common/src/main/java/com/duckduckgo/app/global/formatters/time/model/TimePassed.kt
common/src/main/res/values/strings.xml
common/src/test/java/com/duckduckgo/app/global/formatters/time/model/TimePassedTest.kt
vpn/src/androidTest/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModelTest.kt
vpn/src/main/java/dummy/ui/VpnControllerActivity.kt
vpn/src/main/java/dummy/ui/VpnDiagnosticsActivity.kt

Task/Issue URL: https://app.asana.com/0/715106103902962/1202697459365558/f
Extracts hardcoded strings used in Common module as String resources
- Ensure unit tests are green
_App TP activity list_

Extract hardcoded strings into resources

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
app/src/main/java/com/duckduckgo/app/browser/serviceworker/ServiceWorkerLifecycleObserver.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202712032214375/f
Another attempt to fix the crashes / anrs related to ServiceWorkerClient. Instead of setting the ServiceWorkerClient on application onStart() which might be too early in the process, we are delaying it to BrowserActivity's onCreate just before any webview is rendered.

Add ServiceWorkerLifecycleObserver to BrowserActivity lifecycle instead of Application

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/di/AutofillModule.kt
autofill/autofill-store/build.gradle
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/AutofillPrefsStore.kt
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt

Task/Issue URL: https://app.asana.com/0/0/1202768144082716/f
- Fix incorrect loging for autofillEnabled. Previously when setting, it takes into account the incoming value, isInternalTestUser and canAccessSecureStorage which is incorrect since autofillEnabled is only used primarily for the user controlled toggled.
- Additional tests for the incorrect logic
_Enable and disable works as expected_

Fix logic for set autofillEnabled

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/AutofillDomainFormatter.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/AutofillJavascriptInterface.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementRecyclerAdapter.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/AutofillStoredBackJavascriptInterfaceTest.kt

Task/Issue URL: https://app.asana.com/0/0/1202630343540910/f 
When saving a credential, the title will be populated alongside the usual URL, username and password.

Save page title (extracted domain) along with credentials

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/AutofillCredentialDialogs.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/CredentialAutofillDialogAndroidFactory.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/selecting/AutofillSelectCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/updating/AutofillUpdatingExistingCredentialsDialogFragment.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202722378440328/f 
Simplification of the way we create and show the DialogFragments in autofill.
(Make sure you build using `internal` variant)

Expose autofill dialogs as DialogFragment to simplify API

---

privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/PrivacyConfigPersister.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/di/ConfigPersisterPreferences.kt
privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/di/PrivacyConfigModule.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigPersisterTest.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/privacyconfig/PrivacyConfigDisabledReferenceTest.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/privacyconfig/PrivacyConfigEnabledReferenceTest.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/privacyconfig/PrivacyConfigGlobalExceptionsReferenceTest.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/privacyconfig/PrivacyConfigLocalExceptionsReferenceTest.kt
privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/privacyconfig/PrivacyConfigMissingReferenceTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202765110225461/f
This is related to [this asana task](https://app.asana.com/0/1202552961248957/1202738585521624/f).
We want to ensure that changes in privacy config plugins trigger a config update when version is `==` to current version.
This covers the scenario where existing configuration in the current version is not given to a newly added plugin.
The table truth should be the following
| version / signature | `=` | `!=` |
| `<` | noop | noop |
| `==` | noop | update |
| `>` | update | update |
See steps in [this task](https://app.asana.com/0/1202552961248957/1202738585521624/f)
Alternatively, do the following:

Ensure new/different privacy config plugins get configuration

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1201994777472691/f
This PR adds a check to ignore non-http app links that are not from mainframe.
Before
https://user-images.githubusercontent.com/3471025/183907792-9daac406-c139-4d87-8cae-705c5a91c9b9.mp4
After
https://user-images.githubusercontent.com/3471025/183907850-07d6c5dd-7764-4cd4-af44-81798ebabfb5.mp4

Ignore non-http app links that are not for mainframe

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementActivity.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/FragmentUtils.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementListMode.kt
autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_disabled.xml
autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_edit_mode.xml
autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_list_mode.xml
autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_locked.xml
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt
common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/OutLinedTextInput.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202659292537112/f
- Adding support to launch edit mode directly through viewmodel
- Adding support to launch view mode autofill credential management 
- Fixing handling for config chnages / backgrounding for credential mode
_Autofill management works as expected!_
_Handling back/config changes_

Autofill management: Better state handling 

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
autoconsent/autoconsent-api/src/main/java/com/duckduckgo/autoconsent/api/Autoconsent.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/AutoconsentInterface.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/MessageHandlerPlugin.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/EvalMessageHandlerPlugin.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPlugin.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/OptOutAndAutoconsentDoneMessageHandlerPlugin.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/PopUpFoundMessageHandlerPlugin.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/SelfTestResultMessageHandlerPlugin.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/Fakes.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/EvalMessageHandlerPluginTest.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPluginTest.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/OptOutAndAutoconsentDoneMessageHandlerPluginTest.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/PopUpFoundMessageHandlerPluginTest.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/SelfTestResultMessageHandlerPluginTest.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1202768897662116
This PRs adds support for OptOut, selfTest and autoconsentDone

Support other messages

---

app-tracking-protection/vpn-internal/build.gradle
app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/flipper/PreferencesFlipperPlugin.kt
app/src/internal/java/com/duckduckgo/app/flipper/FlipperInitializer.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202290988165053/f
Create a flipper plugin that supports both sharedPreferences and Harmony shared preferences (used for multi-process)

Add sharedPrefs flipper-plugin that considers Harmony prefs

---

app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteData.kt
app/src/test/java/com/duckduckgo/app/brokensite/BrokenSiteDataTest.kt

Task/Issue URL: https://app.asana.com/0/1125189844152671/1202794100930314
After changing the trackers algorithm we broke broken sites a bit. We send the full list of domains that we intercept instead of only the ones that we blocked.

Fix broken site reports

---

downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/FileDownloadCallback.kt
downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/MediaScanner.kt
downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/FileDownloadCallbackTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202798538526983/f
Ensure we scan the media folder so that downloaded media files immediately appear to the user when trying to open from apps other than the DDG browser
_Before_
- expected
- actual
_After_

Scan media files after download

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/autofill/AutofillCredentialsSelectionResultHandler.kt
app/src/main/res/values/string-untranslated.xml
app/src/test/java/com/duckduckgo/app/browser/autofill/AutofillCredentialsSelectionResultHandlerTest.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/store/AutofillStore.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/ui/AutofillSettingsActivityLauncher.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementActivity.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModel.kt
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt
secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorage.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/RealSecureStorage.kt
secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageRepository.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202630343540915/f
Shows a snackbar after saving and updating login credentials. The snackbar has an action button letting you directly shortcut into viewing the credential.

Show snackbar when saving/updating credentials

---

ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickManager.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202820659663269/f
Return null instead of crashing when the `toTldPlusOne` (`PublicSuffixDatabase.getEffectiveTldPlusOne`) encounters an exception.
- we couldn't replicate

Crash: DuckDuckGoAdClickManager.toTldPlusOne

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/AutofillCredentialDialogs.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/CredentialAutofillDialogAndroidFactory.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/selecting/AutofillSelectCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/updating/AutofillUpdatingExistingCredentialsDialogFragment.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202829664561720/f
Task/Issue URL: [Bug: Unable to save credentials](https://app.asana.com/0/1202820940582292/1202820940582292/f)
Task/Issue URL: [Flaky behavior of snackbar after saving](https://app.asana.com/0/0/1202821157855651/f)
Ensures that the fragment result listeners are not overwritten by another tab, which would mean the results get delivered to the most newly-created tab, which isn't always the current tab.
Repeat the steps listed in [Flaky behavior of snackbar after saving](https://app.asana.com/0/0/1202821157855651/f) and [Bug: Unable to save credentials](https://app.asana.com/0/1202820940582292/1202820940582292/f) and make sure the problems no longer appear

Ensure fragment result listeners respond to correct tab

---

autofill/autofill-impl/src/main/AndroidManifest.xml
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementActivity.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt

https://app.asana.com/0/488551667048375/1202821446406981/f
https://app.asana.com/0/488551667048375/1202828695381297/f
- Ensuring that only one device auth flow is launched until it is completed. The issue is originally caused by the auth flow in older android device that launches a new activity. Once the auth is completed, the auth activity is closed and triggers the management screen's `onStart` where we call `launchDeviceAuth`. To fix this, we add a check before launching auth that there is no already ongoing auth. An auth flow is considered `ended` once we have received the result in the AutofillManagementActivity.
- Don't reauth when orientation changes. Used https://developer.android.com/guide/topics/manifest/activity-element#config …

Fix infinite authentication loop on older Android

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/selecting/AutofillSelectCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/updating/AutofillUpdatingExistingCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/res/values/styles.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1202820530980762/f
Improves the UX for the autofill dialogs when in landscape (or split screen) view, ensuring it defaults to the full state and doesn't shrink down to peek mode when dragging down.

Improve UX of dialogs in landscape

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/0/0/1202828695381301/f
- Change try-catch for ServiceWorkerControllerCompat initialization to catch Throwable instead of Exception only.
- So far all Throwable thrown by ServiceWorkerControllerCompat are webview/chromium related which we don't have controll of. Instead of letting the app crash and become unusable, we just hide this specific type of crashes.

Catch throwble if ServiceWorkerControllerCompat init

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteActivity.kt
app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteData.kt
app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteViewModel.kt
app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt
app/src/main/java/com/duckduckgo/app/brokensite/model/BrokenSite.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/global/model/Site.kt
app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt
app/src/test/java/com/duckduckgo/app/feedback/BrokenSiteViewModelTest.kt
app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesReferenceTest.kt
app/src/test/resources/reference_tests/brokensites/tests.json
autoconsent/autoconsent-api/src/main/java/com/duckduckgo/autoconsent/api/Autoconsent.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPlugin.kt
autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/OptOutAndAutoconsentDoneMessageHandlerPlugin.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPluginTest.kt
autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/OptOutAndAutoconsentDoneMessageHandlerPluginTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202833726990280/f 
This PR adds autoconsent flags to broken sites report

Add autoconsent flags to broken sites

---

app/src/androidTest/java/com/duckduckgo/app/browser/shortcut/ShortcutReceiverTest.kt
app/src/main/java/com/duckduckgo/app/browser/shortcut/ShortcutBuilder.kt
app/src/main/java/com/duckduckgo/app/browser/shortcut/ShortcutReceiver.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202836102778380/f 
This PR changes the shortcut intent from implicit to explicit
See steps in the above task. Try first from develop to recreate the issue and then from this branch to see the issue does not exist anymore.

Change shortcut implicit intent to explicit

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/AutofillJavascriptInterface.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/jsbridge/response/AutofillResponseWriter.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/AutofillStoredBackJavascriptInterfaceTest.kt

Task/Issue URL: https://app.asana.com/0/0/1202856772457648/f
Shows the inline key icon in the WebView fields which can be autofilled.

Show key icon on compatible WebView fields

---

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/OutLinedTextInput.kt

Task/Issue URL: https://app.asana.com/0/0/1202854142935498/f
Disables the TextInputLayout's hint animation when it is first being intialised.

Disable hint animation when first setting value

---

app/build.gradle
app/src/androidTest/java/com/duckduckgo/app/httpsupgrade/BloomFilterTest.kt
app/src/androidTest/java/com/duckduckgo/app/httpsupgrade/HttpsUpgraderTest.kt
app/src/androidTest/java/com/duckduckgo/app/referencetests/HttpsReferenceTest.kt
app/src/androidTestPlay/java/com/duckduckgo/app/integration/HttpsEmbeddedDataIntegrationTest.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/BloomFilter.kt
app/src/main/java/com/duckduckgo/app/httpsupgrade/HttpsBloomFilterFactory.kt
library-loader/library-loader-api/build.gradle
library-loader/library-loader-api/src/main/java/com/duckduckgo/library/loader/LibraryLoader.kt
lint-rules/src/main/java/com/duckduckgo/lint/DuckDuckGoIssueRegistry.kt
lint-rules/src/main/java/com/duckduckgo/lint/NoSystemLoadLibraryDetector.kt
lint-rules/src/test/java/com/duckduckgo/lint/NoSystemLoadLibraryDetectorTest.kt
versions.properties

Task/Issue URL: https://app.asana.com/0/488551667048375/1202242362471737/f
Use `ReLinker` (as also suggested by Google in [here](https://developer.android.com/training/articles/perf-jni#native-libraries)) to avoid issues when linking native libraryes. Like the ones we see with the bloom filter.
ReLinker internaly uses `System.loadLibrary()` but falls back to do their own thing when that fails. So it should not worsen the situation.
_Test libary loading_

Use relinker to load native libraries

---

autofill/autofill-impl/src/main/AndroidManifest.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1202882686065977/f
- Adjust autofill activity main window when soft input is visible
_Edit mode is scrollable_

Fix scroll issue for edit mode autofill credential

---

app/src/main/java/com/duckduckgo/widget/SearchAndFavoritesWidget.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202864079845783/f
Updated `SearchAndFavoritesWidget` to use the mutable flag for pending intent on sdk 31 (Android 12) and above.
Perform the below tests on Android 6, 11, 12, 13:

Favorites widget stopped working on 5.134.0.4-nightly

---

app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202885885052668/f
This PR resets the listeners (Add folder, edit folder and edit bookmark) when BookmarksActivity has been destroyed in the background and recreated.
_Editing from Bookmarks screen_
_Editing from BrowserTabFragment_

Reset listeners when BookmarksActivity is recreated

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/0/1202898149609662/f
1. Enable StrictMode (see [here](https://app.asana.com/0/0/1202897877101652/f))
1. Add Logcat filter: onCtaShown
1. Clean install of the app, and do the following to reproduce StrictMode warning in develop:
1. Visit [cnn.com](https://cnn.com/)
1. Wait for Dax onboarding dialog to appear

Fix disk io on main thread, BrowserTabViewModel.onCtaShown

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/TrackingProtectionAppsRepository.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202844197903911/f
- Prior to this PR, In `RealTrackingProtectionAppsRepository.isAppProtectionEnabled` we always check the SystemAppOverrideList first to determine if App Protection is Enabled. However, if the user has manually changed the protection for the App, it should be respected first.
_System overrides are respected_
_Manual overrides respected and persisted_

Respect manual exclusion list first before SystemAppOverrideList

---

ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/AdClickAttributionFeature.kt
ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/AdClickAttributionPlugin.kt
ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/RealAdClickAttribution.kt
ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt
ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/AdClickAttributionPluginTest.kt
ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/RealAdClickAttributionTest.kt
ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/referencetests/AdClickAttributionLinkFormatsReferenceTest.kt
ad-click/ad-click-impl/src/test/resources/json/ad_click_attribution.json
ad-click/ad-click-impl/src/test/resources/json/ad_click_attribution_disabled.json
ad-click/ad-click-impl/src/test/resources/json/ad_click_attribution_min_supported_version.json
ad-click/ad-click-impl/src/test/resources/reference_tests/adclickattribution/ad_click_attribution_matching_tests.json
ad-click/ad-click-impl/src/test/resources/reference_tests/adclickattribution/ad_click_attribution_reference.json
ad-click/ad-click-store/src/main/java/com/duckduckgo/adclick/store/AdClickDatabase.kt
ad-click/ad-click-store/src/main/java/com/duckduckgo/adclick/store/AdClickEntities.kt
ad-click/ad-click-store/src/test/java/com/duckduckgo/adclick/store/RealAdClickAttributionRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1202815075182083/f
Removed the usage of parameterName and parameterValue from link_formats.
1/ Test update (important for DB migrations)
- Go to: https://www.search-company.site/
Click "[Ad 5]"
✅ Loaded:
[https://convert.ad-company.site/convert.js](https://convert.ad-site.example/convert.js)
❌ Blocked:
[https://track.ad-company.site/track.js](https://track.ad-site.example/track.js)
2/ Test fresh install
- Go to: https://www.search-company.site/
Click "[Ad 5]"
✅ Loaded:
[https://convert.ad-company.site/convert.js](https://convert.ad-site.example/convert.js)
❌ Blocked:
[https://track.ad-company.site/track.js](https://track.ad-site.example/track.js)

Android: Remove support for non-ad_domain parameters

---

app/src/main/java/com/duckduckgo/app/browser/favicon/DuckDuckGoFaviconManager.kt

Task/Issue URL: https://app.asana.com/0/0/1202897565527408/f
1. Enable StrictMode (see [here](https://app.asana.com/0/0/1202897877101652/f))
1. Add Logcat filter: DuckDuckGoFaviconManager.loadToViewFromLocalOrFallback
1. Run app, and do the following to reproduce StrictMode warning:
1. Visit a site (e.g., [cnn.com](https://cnn.com/))
1. Open tab switcher

Fix disk io on main thread, FaviconManager

---

app/src/androidTest/java/com/duckduckgo/app/fire/AutomaticDataClearerTest.kt
app/src/main/java/com/duckduckgo/app/fire/AutomaticDataClearer.kt
app/src/main/java/com/duckduckgo/app/global/view/ClearPersonalDataAction.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202899711152150/f
- Enable StrictMode (see [here](https://app.asana.com/0/0/1202897877101652/f))
- Add Logcat filter (regex):
- `SettingsSharedPreferences.setAppUsedSinceLastClear|SettingsSharedPreferences.setAppBackgroundedTimestamp`
- Run the app, and do the following to reproduce StrictMode warning in develop:
- Go through onboarding
- Go to settings, and configure it to automatically clear tabs only, after 5s
- Open a webpage, then hit the home button to background the app
- Wait for >=6 seconds
- Return to the app, and you'll see the StrictMode warning about disk IO writing
Verify no behaviour changes to automatic data clearing and fire button: 
**Disabling WM**
There is a scenario whereby the WM task to clear the data in the …

Fix disk io on main thread, data clearing

---

build.gradle

Task/Issue URL: https://app.asana.com/0/488551667048375/1202931331947206/f 
This PR crashes the build whenever it detect Android tests that are not in the app module.

Crash build if Android tests exist out of the app module

---

app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202925412789676/f
Filters duplicate liveTabs events triggered by updates on Tabs database that don't change any actual data.
_Test_
_Advanced Test (optional)_
```
viewModel.tabs.observe(this) {
<ADD YOUR LOG HERE>
clearStaleTabs(it)
launch { viewModel.onTabsUpdated(it) }
}
```

Filters LiveTabs duplicated events

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistryImpl.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/cohort/CohortStore.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnStore.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202952441304133/f
Adds `SharedPreferences` references behind a `get()`, which can reduce the work done on main thread when first initialising app process, and is inline with how we do it elsewhere in the app.

Add getter to VPN shared preferences

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/DeviceShieldTileService.kt

Task/Issue URL: https://app.asana.com/0/0/1202994567277582/f
Fixes a crash with an uninitialized property in VpnPermissionRequesterActivity
1. Fresh install of the app
1. Swipe down on the system status bar (possibly twice depending on OEM) to reveal quick tiles
1. If App Tracking Protection not visible, choose to edit the tiles and make it visible
1. Click on the tile
1. Choose to grant VPN permissions  ← crash happens here
1. Crash happens because vpnFeaturesRegistry is uninitialized

Fix crash on VpnPermissionRequesterActivity

---

ad-click/ad-click-impl/build.gradle
autofill/autofill-api/build.gradle
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/domain/app/LoginCredentials.kt
autofill/autofill-impl/build.gradle
autofill/autofill-store/build.gradle
build.gradle
downloads/downloads-impl/build.gradle
macos/macos-impl/build.gradle
privacy-config/privacy-config-impl/build.gradle

Task/Issue URL: https://app.asana.com/0/488551667048375/1202728801491359/f
Forbid the usage of `kotlin-android-extension` as it is deprecated.
We use(d) it for two things:
* `@Parcelize`
* synthetics
For some modules like `:app` and `:vpn-impl` I've added an exception
because we first need to migrate way from synthetics
Smoke tests for autofill

Forbid usage of kotlin-android-extensions

---

app/src/main/java/com/duckduckgo/app/accessibility/data/AccessibilityDataStore.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt

Task/Issue URL: https://app.asana.com/0/0/1202908047221081/f
The current implementation of `BrowserTabViewModel.initializeViewStates` can be very slow, as it involves reading persisted data (on the main thread) to populate the view states. This can be pretty taxing on the main thread (measured at blocking UI thread for over 300ms on one device). Most view states don't require providing dynamic init values, leaving only a few offenders:
- autofill
- voice search capabilities
- add to home capabilities
- accessibility preferences
This PR makes the logic to initialise the `BrowserTabViewModel` view states happen in two parts:
- a default init which is instant as it does no disk IO
- async init to update view states which require fetching data from disk
In practice both parts should …

Fix disk io on main thread, BrowserTabViewModel.initializeViewStates

---

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/network/VpnNetworkStack.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/LegacyVpnNetworkStack.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModelTest.kt
vpn-network/vpn-network-impl/src/main/java/com/duckduckgo/vpn/network/impl/RealVpnNetwork.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203002043003671/f
Avoid loading the native (new) networking library when using the legacy
one.
_Test lazy loading_

Lazy init for new networking stack

---

autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt
secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorageModels.kt
secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/RealSecureStorage.kt
secure-storage/secure-storage-impl/src/test/java/com/duckduckgo/securestorage/impl/RealSecureStorageTest.kt
secure-storage/secure-storage-store/schemas/com.duckduckgo.securestorage.store.db.SecureStorageDatabase/3.json
secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/db/SecureStorageDatabase.kt
secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/db/WebsiteLoginCredentialsEntity.kt
secure-storage/secure-storage-store/src/test/java/com/duckduckgo/securestorage/store/RealSecureStorageRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202945231028273/f
- Adding L2 encryption on notes. Store iv for notes in the db as well. We can't reuse the same iv and key for when encrypting.
- Since autofill is still in internal beta, we just drop all notes saved atm instead of migrating it.
_Migration works as expected_
_Adding notes works as expected_

Add L2 encryption for notes

---

app-tracking-protection/vpn-impl/src/main/res/layout/activity_report_breakage_category_single_choice.xml

Task/Issue URL: https://app.asana.com/0/1202279501986195/1202802090030480/f
Fixed style in report breakage screen.
1/ Test in Dark mode
2/ Test in Light mode
| Before (Dark)  | After (Dark) |
| After (Light - unchanged)  | After (Dark - as above) |

AppTP: Select breakage category in Dark theme

---

common-ui/src/main/res/layout/view_message_cta.xml

Task/Issue URL: https://app.asana.com/0/1202552961248957/1203021475583761
In [✓ Android Component: Button](https://app.asana.com/0/1174433894299346/1202861107912487) we standarised the button component across the app. When updating the layout for Remote Messaging I used the wrong style (see screenshot)
Objective
Fix the style, moving from Secondary to Ghost

Fix button style for Remote Messaging

---

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSetting.kt
app-tracking-protection/vpn-impl/build.gradle
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/TrackingProtectionAppsRepository.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/settings/ProtectGamesSettingPlugin.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/apps/TrackingProtectionAppsRepositoryTest.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpFeatureConfigImplTest.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSettingTest.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/FakeAppTpFeatureConfig.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/settings/ProtectGamesSettingPluginTest.kt
app-tracking-protection/vpn-store-test/build.gradle
app-tracking-protection/vpn-store-test/src/main/java/com/duckduckgo/mobile/android/vpn/trackers/FakeAppTrackerRepository.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1202942224713452/f
This protects games and has a remote config to enable/disable that
functionality.
The PR incidentally also fixes a but we had in the
`TrackingProtectionAppsRepository:isAppProtectionEnabled()` method that
was causing games to show always as protected when going to the app
details screen.
This bug probably didn't manifest very often given that games protection
are disabled by default.
_Test the bug fix_
- expected: Among us toggle should be OFF in the screen that opens
- actual: Among us toggle is ON in the screen that opens
_Test game protection_

Protect games

---

app-tracking-protection/vpn-impl/src/main/AndroidManifest.xml
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/state/RealVpnStateMonitor.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/state/VpnTrampolineService.kt

Task/Issue URL: https://app.asana.com/0/1202279501986195/1202332814862288/f
Comprehensive discussion in the [Asana
task](https://app.asana.com/0/1202279501986195/1202332814862288/f).
TL;DR
* VpnService runs in its own process
* But it is started from the main browser process
* majority of the time is spent on Android creating the `:vpn` process
* which increases the likehood of exceptions because the time between startForegroundService() and startForeground() exceeds the Android predefine threshold
* this PR uses a trapoline service whenever possible so that the process
creation time doesn't account
Sanity checks on AppTP enable/disable, ie:
AppTP normally

VPN start trampoline

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt

Task/Issue URL: https://app.asana.com/0/1202279501986195/1203038225582363/f
Added daily pixel for the unprotected apps bucket.

AppTP: Android pixels needed (daily) - percentage of unprotected apps

---

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203023500295199/f
Updated to use dismissNow() instead of dismiss() for App Enjoyment dialog.
See the crash:
https://github.com/duckduckgo/Android/blob/develop/app/src/main/java/com/duckduckgo/app/global/rating/ShowInitialPromptDecider.kt#L33-L36
https://github.com/duckduckgo/Android/blob/develop/app/src/main/java/com/duckduckgo/app/global/rating/PromptTypeDecider.kt#L45-L47
https://github.com/duckduckgo/Android/blob/develop/app/src/main/java/com/duckduckgo/app/global/rating/PromptTypeDecider.kt#L54-L57
Test the fix:
https://github.com/duckduckgo/Android/blob/develop/app/src/main/java/com/duckduckgo/app/global/rating/ShowInitialPromptDecider.kt#L33-L36
https://github.com/duckduckgo/Android/blob/develop/app/src/main/java/com/duckduckgo …

Android crash: Exception kotlin.UninitializedPropertyAccessException: lateinit property listener has not been initialized

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/LegacyVpnNetworkStack.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203049628891378/f
Swap the networking layer
_Smoke tests for AppTP
_Test it uses the new networking layer_
_Test Private DNS_
_Test networkg switches_

Replace networking stack

---

app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
app/src/main/java/com/duckduckgo/app/browser/tabpreview/WebViewPreviewGenerator.kt

Task/Issue URL: https://app.asana.com/0/0/1202973737705663/f
Moves the work to generate a `Bitmap` from the `WebView` off of the main thread. We do this work to generate `WebView` image previews for the tab switcher but it can be too heavy to do on the main thread and is showing up as ANRs. 
From testing, it is safe to generate the `Bitmap` off of the main thread.
_WebView image preview generator_

Move bitmap generation off of main thread

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt

Task/Issue URL: https://app.asana.com/0/1202552961248957/1203064213689934/f
1. Catches `SecurityException` when trying to start certain app links and shows the "unableToOpenLink" toast.
2. Sends a pixel containing the exception message for debugging purposes.
Code review.

Catch app link SecurityException

---

common-ui/src/main/res/values/themes.xml

Task/Issue URL:  https://app.asana.com/0/1157893581871903/1203056086367606
Previous Theme updates forgot to update this screen. Making it crash when opened...
_From develop_
_From this branch_

Fix WidgetInstructions Activity crash

---

app/src/main/res/layout/activity_settings.xml

Task/Issue URL:  https://app.asana.com/0/1202552961248957/1203071545508078
Merging [✓ Android Component: Section Header](https://app.asana.com/0/1202552961248957/1203032895896306) messed with the Settings screen, hiding the Default Browser item. This fixes it.
Smoke test

Fix Settings missalignment

---

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesWorkerCodeGenerator.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203056086367700/f
Honor property annotations when using the `@ContributesWorker` annotation. Example:
```kotlin
@ContributesWorker(AppScope::class)
class FooWorker(context: Context, workerParameters: WorkerParameters) :
CoroutineWorker(context, workerParameters) {
@Inject
@Named("foo")
lateinit var foo: Foo
}
```
Should build

Carry over property annotations when generating worker plugins

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt
app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1202937064608957/f
Show a toast when users click to see app tracking details for an app that is no longer installed
_Test uninstalled app_

Handle uninstalled apps in AppTP

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/removal/VpnFeatureRemover.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
app-tracking-protection/vpn-store/schemas/com.duckduckgo.mobile.android.vpn.store.VpnDatabase/25.json
app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/VpnAddressLookup.kt
app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabase.kt

Task/Issue URL: https://app.asana.com/0/1202279501986195/1203152743665997/f
AppTP keeps an in memory LRU cache that is used while blocking. But that cache is lost every time AppTP is OFF.
It'd be more efficient to not have to re-build it by persisting it to disk both when AppTP is turned OFF and periodically.
Smoke test for AppTP for both fresh install and app update

Persist LRU cache

---

app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml

Task/Issue URL: https://app.asana.com/0/1202279501986195/1203165097819219/f
Set the primary text on the cta_show_all view.
Check the issue:
Check the fix:
|![before_fix](https://user-images.githubusercontent.com/7963079/195818372-74fe4261-ec7f-4e6d-be40-2c9b05f16a9b.png)|![after_fix](https://user-images.githubusercontent.com/7963079/195818383-e5987b3c-b101-4fd3-a216-84340a01e3c0.png)|

AppTP: Bug - The button to see All Activity is hidden (but you can still click it)

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/saving/declines/AutofillDisablingDeclineCounter.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/saving/declines/AutofillDisablingDeclineCounterTest.kt

Task/Issue URL: https://app.asana.com/0/0/1203135243423252/f
Simplify the logic used to detect when a user doesn't want to use autofill. Removes the in-memory decline counter.
Logcat filter: `AutofillDisablingDeclineCounter`

Autofill decline counter: remove in-memory counter

---

.github/workflows/build-debug-apk.yaml
.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/privacy.yml

Task/Issue URL: https://app.asana.com/0/488551667048375/1203189277953937/f
Update workflows that uses `v2` of `actions/setup-java` and `actions/checkout` to use `v3.`
This PR can't fix the "save-state" warnings since it's caused by `gradle/gradle-build-action` which is still to be fixed https://github.com/gradle/gradle-build-action/issues/461
Workflows should complete as usual without deprecated warnings except for "save-state".

Update deprecated actions/commands in workflows 

---

content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScripts.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScriptsTest.kt
node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
package-lock.json
package.json

Task/Issue URL: https://app.asana.com/0/488551667048375/1203156990301220/f
This PR updates to latest version of content scope scripts ([3.1.0](https://github.com/duckduckgo/content-scope-scripts/releases/tag/3.1.0))
_Privacy Test Pages_
_Global Privacy Control_

Update content scope scripts to 3.1.0

---

app/src/main/res/mipmap-anydpi-v26/ic_launcher_black.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_black_round.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_blue.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_blue_round.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_gold.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_gold_round.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_green.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_green_round.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_purple.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_purple_round.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_red.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_red_round.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_silhouette.xml
app/src/main/res/mipmap-anydpi-v26/ic_launcher_silhouette_round.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1203156990301208/f
This PR adds support for the new "Themed icons" feature in Android 13.

Support themed icons

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/stats/VpnServiceStateLogger.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/alwayson/AlwaysOnAlertDialogFragment.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/alwayson/AlwaysOnLockDownDetector.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldAlertNotificationBuilder.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnStore.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt
app-tracking-protection/vpn-impl/src/main/res/layout/content_vpn_always_on_alert.xml
app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml

https://app.asana.com/0/0/1203149173362393
This stacked PR implements the notification triggered when detecting always-on lockdown mode. As per [figma](https://www.figma.com/file/yJqzxIICeXw6F8co5uffnX/AppTP-%3A-Re-think-Always-on-Promotion?node-id=1202%3A56156)
The logic is the following:
* When we detect the user sets the lockdown mode we'll trigger a notification so that user can take action
* Tapping on notification takes the user to AppTP activity screen
* AppTP activity screen will show the bottom sheet dialog
* If rather than tapping on the notification, the user opens the app and goes to AppTP activity screen, bottom sheet dialog should also be shown
* If the user selects "Not now" in the bottom sheet dialog 3 times, we won't show the sheet anymore
Main things that changed:
* …

Improve always on promotion [4/4]–Lockdown notification

---

fastlane/Fastfile
fastlane/README.md

Task/Issue URL: https://app.asana.com/0/0/1203123091630352/f
Add a new Fastlane flow which can be used to trigger some automation to save manual steps when creating a new release. 
- This flow is not required when making a release; the same steps can always still be done manually
- Requires addition configuration, as detailed in [Installation](https://app.asana.com/0/0/1203116937958002/f)
⚠️  Since this would actually make changes to the release board, you will not be able to test that out for this PR. However, there is a fake release board which can be used to test against.
To run against the fake board, open `fastfile` and replace the existing line 297 with
`sh "#{bridgeLocation}", "version=#{newVersion}", "action=listPendingTasks", "board=fake"`
This does two things:
- configures it to …

Add fastlane flow to automate asana steps for release

---

site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerImpl.kt

Task/Issue URL: https://app.asana.com/0/715106103902962/1203249594027451/f 
Do not remove global permission settings when clearing data
_Test_
_Test 2_

persist global permission settings

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModel.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldNotificationFactory.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/report/PrivacyReportViewModel.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/AppTPCompanyTrackersViewModel.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModel.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/stats/AppTrackerBlockingStatsRepositoryTest.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldDailyNotificationFactoryTest.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldWeeklyNotificationFactoryTest.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModelTest.kt
app-tracking-protection/vpn-store/schemas/com.duckduckgo.mobile.android.vpn.store.VpnDatabase/28.json
app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/VpnTrackerDao.kt
app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/model/VpnDatabaseModels.kt
app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabase.kt
app/src/internal/java/com/duckduckgo/app/flipper/plugins/TrackerProtectionFlipperPlugin.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203195823975934/f
Change the `vpn_tracker` schema so that we don't need one entry per tracking attempt.
This should:
* improve DB access performance
* fix some bugs when we have more than 10,000 tracking attempts
_Test DB migration_
_How to create tracking attempts_
* install Termux
* execute the script below
```bash
for i in {1..10}
do
curl -v https://api2.branch.io &
sleep 0.5
done
```

Re-structure VPN tracker db table

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/NewAppBroadcastReceiver.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/VpnAppTrackerListInfoCollector.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/bugreport/VpnAppTrackerListInfoCollectorTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203238561022240/f
Avoid re-starting AppTP when games are installed, see [asana task](https://app.asana.com/0/488551667048375/1203238561022240/f) for more details
_Test install games_

Avoid reconfiguring VPN when game is installed

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/browser/autofill/AutofillCredentialsSelectionResultHandler.kt
app/src/test/java/com/duckduckgo/app/browser/autofill/AutofillCredentialsSelectionResultHandlerTest.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/AutofillCredentialDialogs.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/store/AutofillStore.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/CredentialAutofillDialogAndroidFactory.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/updating/AutofillUpdatingExistingCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/res/layout/content_autofill_update_existing_credentials.xml
autofill/autofill-impl/src/main/res/values/donottranslate.xml
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203058117400612/f
Detects when a saved login is missing a username, and offers to save the username when logging in again (when a matching password is included)

Support updating username when matching password provided

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/DeviceShieldTileService.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203277450694429/f
Reverts changes made to `DeviceShieldTileService` so that it doesn't use an injected coroutine dispatcher (easiest fix for a niche / hard to test area of code)

Fix crash caused by unitialised dispatcher provider

---

app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/VpnAppTrackerBlockingDao.kt

Task/Issue URL: https://app.asana.com/0/0/1203278838524404/f
Our exceptions are based on SLDs, but we were matching on FQDNs. Fix to match exceptions the same way we match domains in the blocklist.

Fix bug where exceptions were matching full hostname instead of SLD

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
autofill/autofill-api/src/main/java/com/duckduckgo/autofill/BrowserAutofill.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/AutofillJavascriptInterface.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/InlineBrowserAutofill.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/InlineBrowserAutofillTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203130404520146/f
It is possible now for a strange UX if the user clicks the URL bar just before the autofill prompt pops up offering to autofill.
This PR fixes that interaction:
- When the user interacts with the URL bar, we should disable the autofill prompt from automatically appearing until the user navigates page or refreshes. 
- Any manual autofill prompts, triggered by the user interacting with the form fields directly, should still result in the autofill prompt showing.
Useful logcat filter: `AutoPrompt is disabled, not showing dialog`

Prevent autofill cred picker showing after certain user-interactions

---

autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_edit_mode.xml

Task/Issue URL: https://app.asana.com/0/488551667048375/1201131549756850/f
Restricts the autofill edit screen's fields to be single lines only (apart from notes)

Restrict autofill edit fields to be singular lines (except notes)

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/ManageRecentAppsProtectionActivity.kt
app-tracking-protection/vpn-impl/src/main/res/layout/activity_manage_recent_apps_protection.xml
app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml

Task/Issue URL: https://app.asana.com/0/1157893581871903/1203291839292809
This PR updates the UI in Recent Apps, improving the empty state
_Recent Apps
|![Recent Apps (2)](https://user-images.githubusercontent.com/531613/199947988-0d6f57be-fd5b-40c8-8d4e-e52a814ef442.jpg)|![Screenshot_20221104_105955](https://user-images.githubusercontent.com/531613/199947757-7ac9b65c-0bf2-4632-9f8e-ff782c80d4a9.png)|

AppTP - Improve Recent Apps empty state

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/pixel/AutofillPixelNames.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementActivity.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/saving/AutofillSavingPixelEventNamesTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203201174202056/f
When saving credentials, we want separate pixels for each of the following scenarios:
- User is saving just a password
- User is saving both a username + password
- (saving only username is yet not supported)
Ensure testing on a site where both username and password are correctly picked up (e.g., trello.com/login)
- `AUTOFILL_SAVE_LOGIN_PROMPT_SHOWN`
- `AUTOFILL_SAVE_LOGIN_PROMPT_SAVED`
- `AUTOFILL_SAVE_LOGIN_PROMPT_SHOWN`
- `AUTOFILL_SAVE_LOGIN_PROMPT_DISMISSED`
Easiest way to test is to hardcode the credentials parsed in `AutofillStoredBackJavascriptInterface.storeFormData` to only contain a password + `null` username.
- `AUTOFILL_SAVE_PASSWORD_PROMPT_SHOWN`
- `AUTOFILL_SAVE_PASSWORD_PROMPT_SAVED`
- …

Align autofill pixels with iOS

---

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/state/VpnStateMonitor.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionExclusionListActivity.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/heartbeat/VpnServiceHeartbeat.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/state/RealVpnStateMonitor.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/stats/VpnServiceStateLogger.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldReminderNotificationScheduler.kt
app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/model/VpnDatabaseModels.kt

Task/Issue URL: https://app.asana.com/0/0/1203286669056489/f
Updated the way we restart the vpn service in an attempt to reduce the `android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException` exceptions.
**Note**: it's very difficult to reproduce the crash by using the app. See more details in [Asana ](https://app.asana.com/0/0/1203286669056489/f)

CT7–Crash after restoring default protection

---

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/store/AutofillStore.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/saving/AutofillSavingCredentialsViewModel.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/saving/AutofillSavingCredentialsViewModelTest.kt
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/AutofillPrefsStore.kt
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203328858503342/f
If autofill defaults to `off` for now, we'd like to preserve optionality in being able to switch it on by default. This includes existing users who have never tried it.
This PR adds a flag indicating if the user has ever been prompted to save a login or not. It doesn't matter if they chose to save one or declined the prompt.
Add a temporary log message to help determine the state of the flag. e.g., override the fire button or add as a line inside of `AutofillStoredBackJavascriptInterface.getAutofillData` that will get called on each page load. Log the state of: `autofillStore.hasEverBeenPromptedToSaveLogin`

Add flag to tell if user has ever been prompted to save a login

---

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/network/VpnNetworkStack.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203276170799087/f
This PR Includes:
- Allowing VPNNetworkStack impls to  provide additional dns servers (also add it as a route)
- Allowing VPNNetworkStack impls to provide the addresses for the VPNService to use
- Making VPNRoutes accessible outside of vpn-impl 
_Feature 1_
- Smoke test that AppTP works as expected

Allow VpnNetworkStack to provide dns and addresses

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/di/AutofillModule.kt
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/AutofillPrefsStore.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203328858503338/f
Autofill is currently gated behind two mechanisms
- global on/off switch
- available to internal testing only
The current default of the switch is `enabled`; this PR changes that to be enabled if an internal tester, false otherwise. The internal testing gate still applies, so really there is no behaviour change, but it's preparation for when the internal tester gate is removed.

Autofill defaults to off generally, but overridden to on for internal testers

---

app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/PermissionsPerWebsiteViewModel.kt
app/src/test/java/com/duckduckgo/app/sitepermissions/PermissionsPerWebsiteViewModelTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203336099175506/f
Remove logic to show site permissions settings for website denied if global toggle is off. We'll show actual values that user saved.
If child permission setting is Deny or Ask and global toggle is off, websites won't request site permissions.
If child permission was changes to Allow and global toggle is off, websites will grant permissions for that specific website.
- Go to mictest.cc and give access to microphone
- Go to Settings > Site Permissions and toggle off Microphone permission
- Open mictest.cc in a new tab or refresh current one
- Go to Settings > Site Permissions and tap on mictest.cc
- Change microphone setting to "Allow"
- Open mictest.cc in a new tab or refresh current one

Site permissions change when turned off

---

app/src/main/java/com/duckduckgo/app/fire/fireproofwebsite/ui/FireproofWebsiteAdapter.kt
app/src/main/java/com/duckduckgo/app/privacy/ui/WebsitesAdapter.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203386039977800/f
Show trailing icon back in Fireproof websites list and Unprotected sites
_Fireproof sites_
- Go to Settings > Fireproof Sites
_Unprotected sites_
- Go to Settings > Unprotected Sites
| Fireproof Sites screen  | Unprotected Sites screen |

Fix trailing icon removed from Fireproof and WhiteList web list items

---

app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
content-scope-scripts/content-scope-scripts-impl/build.gradle
content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScripts.kt
content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScriptsTest.kt
fingerprint-protection/fingerprint-protection-api/src/main/java/com/duckduckgo/fingerprintprotection/api/FingerprintProtectionManager.kt
fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/FingerprintProtectionSeedManager.kt
fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/FingerprintProtectionSeedWorker.kt
fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/di/FingerprintProtectionModule.kt
fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/FingerprintProtectionSeedWorkerSchedulerTest.kt
fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/FingerprintProtectionSeedWorkerTest.kt
fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/FingerprintProtectionDatabase.kt
fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/FingerprintProtectionEntities.kt
fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/seed/FingerprintProtectionSeedDao.kt
fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/seed/FingerprintProtectionSeedRepository.kt
fingerprint-protection/fingerprint-protection-store/src/test/java/com/duckduckgo/fingerprintprotection/store/seed/RealFingerprintProtectionSeedRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203278063438410/f
This PR adds a random seed that is used in the fingerprint protection feature.
- The seed is supplied to the content scope config as the `sessionKey` variable.
- The seed is refreshed when the app is stopped (Or the repo is re-instantiated) or every 24 hours.
_Privacy Protection Tests_
_In the results, verify that the following values are returned:_
_Cover Your Tracks_
_In the results, verify that the following values are returned:_

Add fingerprint protection random seed

---

.github/workflows/nightly.yml

Task/Issue URL: https://app.asana.com/0/1157893581871903/1203404929443459
In [✓ Android: Trigger KtLint via Kotlinter instead of Spotless](https://app.asana.com/0/1174433894299346/1203115816821758) we changed the tool use to check the code formatting in Kotlin
We made the appropriate changes in CI for PR, but didn't change for Nightly builds. 
https://github.com/duckduckgo/Android/actions/runs/3501659127/jobs/5865491231#step:4:106

Nightly builds should also run KtLint

---

common-ui/src/main/res/layout/view_one_line_list_item.xml
common-ui/src/main/res/layout/view_two_line_item.xml

Task/Issue URL: https://app.asana.com/0/1202857801505092/1203433424223914/f
Increase padding-end for OneLineListItem and TwoLineListItem when showing switch

ADS: Edit padding-end toggle in ListItems

---

fastlane/Fastfile

Task/Issue URL: https://app.asana.com/0/488551667048375/1203398448486630/f
This PR allows passing the following as options for the release lane:
- release_notes -> Actual custom release notes
- notes_type -> "KEEP EXISTING", "CUSTOM" and then others
- release_number -> new release version number

Enable passing release number and release notes through params/options for release lane

---

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/ui/urlmatcher/AutofillUrlMatcher.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/di/AutofillModule.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/suggestion/SuggestionMatcher.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/suggestion/SuggestionMatcherTest.kt
autofill/autofill-store/build.gradle
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/urlmatcher/AutofillDomainNameUrlMatcher.kt
autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt
autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/urlmatcher/AutofillDomainNameUrlMatcherTest.kt
secure-storage/secure-storage-store/build.gradle
secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/db/WebsiteLoginCredentialsDao.kt
secure-storage/secure-storage-store/src/test/java/com/duckduckgo/securestorage/store/RealSecureStorageRepositoryTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203418026431060/f
Updates the autofill URL matching logic to the linked task. Summarizing:
- better use of e-tld+1 for comparisons
- better handling of subdomains
To achieve this fully, we now filter for matching credentials in two steps:
- at the DB level first using etld+1 
- in Kotlin, where we further filter the results based on subdomains
Each of the scenarios listed in the spreadsheet should be tested: [Autofill domain matching rules](https://app.asana.com/0/1203115518054842/1203386153863287/f)
- For each row, make sure you have a saved credential in the form listed. Then visit the site detailed for it and validate if autofill is offered, and whether that matches the expected state (✅ meaning we should autofill, ❌ meaning we …

Improve autofill subdomain/url handling

---

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/network/VpnNetworkStack.kt
app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/state/VpnStateMonitor.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/state/RealVpnStateMonitor.kt
app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/model/VpnDatabaseModels.kt
app/src/test/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStackTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203438587781253/f
- refactoring of the VPNNetworkStack interface
- introducing the VPNRunningState.ENABLING as a middle state when the VPN has been enabled but the VpnRunningState.ENABLED is not yet reached for any reason.
Smoke test apptp

Refactor VPNNetworkStack and introduce Enabling VpnRunningState

---

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/RadioListAlertDialogBuilder.kt

Task/Issue URL: https://app.asana.com/0/1202857801505092/1203456015669172/f
- Selected option was not working for RadioListAlertDialogBuilder
- Disable positive button if no option is selected by default

ADS: Fix selected option in RadioListDialog

---

app/src/main/AndroidManifest.xml

Task/Issue URL: https://app.asana.com/0/1202552961248957/1203238561022217
Background
[✓ Theming](https://app.asana.com/0/1202552961248957/1203142079944553/f) possibly caused this regression in 5.141.x
See [Comment by Aitor on Theming](https://app.asana.com/0/0/1203142079944553/1203245774898368/f)
5.140.x doesn't have that bug
_Any theme in Production_
_Any theme in [5.140](https://github.com/duckduckgo/Android/releases/tag/5.140.0)_
_Light Theme from this branch_
Dark Theme from this branch_
|https://user-images.githubusercontent.com/531613/204055704-13cc233f-1fd5-4e13-9f19-7be6b3b5c469.mp4|(https://user-images.githubusercontent.com/531613/204055702-1dd9d914-7f58-4716-a248-9bdd3b9ed4a0.mp4)|

Bug: Fire animation fades in white in dark theme

---

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementActivity.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModel.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/FragmentUtils.kt
autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt
device-auth/device-auth-api/src/main/java/com/duckduckgo/deviceauth/api/AutofillAuthorizationGracePeriod.kt
device-auth/device-auth-impl/src/main/java/com/duckduckgo/deviceauth/impl/AuthLauncher.kt
device-auth/device-auth-impl/src/main/java/com/duckduckgo/deviceauth/impl/AutofillGracePeriodLifecycleObserver.kt
device-auth/device-auth-impl/src/main/java/com/duckduckgo/deviceauth/impl/AutofillTimeBasedAuthorizationGracePeriod.kt
device-auth/device-auth-impl/src/main/java/com/duckduckgo/deviceauth/impl/RealDeviceAuthenticator.kt
device-auth/device-auth-impl/src/test/java/com/duckduckgo/deviceauth/impl/AutofillTimeBasedAuthorizationGracePeriodTest.kt
device-auth/device-auth-impl/src/test/java/com/duckduckgo/deviceauth/impl/RealDeviceAuthenticatorTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203472964310393/f
There are cases where the user has to authenticate twice in quick succession to access autofill data. In these situations we can reduce friction by not requiring authentication again with a short time period, assuming they haven't backgrounded the app.
The ability to skip auth happens only if:
- last successful auth happened within last 15 seconds
- app has not been backgrounded
- app has not been killed
There's been a fair bit of refactoring in here, around fragments and view state, so thorough testing appreciated 🙏

Autofill: Add grace period where device auth not required

---

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
app/src/main/java/com/duckduckgo/app/global/api/AtbAndAppVersionPixelRemovalInterceptor.kt
app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt

Task/Issue URL: https://app.asana.com/0/0/1203467208458897/f 
This PR adds a pixel whenever a user lands on the unsupported error page on FB and also when londing on login.php. A while ago FB disabled WebView from their auth flow and we get breakage reports every now and then, the idea of this PR is to monitor for a couple of weeks when this error happens using login.php as denominator and then decide next steps.
_Feature 1_

Add pixels when FB login fails due to unsupported WebView

---

app/src/main/res/layout/content_settings_appearance.xml
app/src/main/res/layout/content_settings_customize.xml
app/src/main/res/layout/content_settings_other.xml
app/src/main/res/layout/content_settings_privacy.xml
common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/TwoLineListItem.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203491129613227/f
- Change primaryTextTruncated default value to match specs. 
- Now sections like Bookmarks and Downloads will look as they used to
- Set primaryTextTruncated to false for settings items

ADS: Fix primaryTextTruncated attribute in TwoLineListItem

---

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSetting.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/settings/StartVpnErrorHandlingSettingPlugin.kt
app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpFeatureConfigImplTest.kt
app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSettingTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203455535355535/f
- Not throwing an exception when issues occur on onPrepareVpn and onStartVpn. Instead, we do graceful handling and stop the VPN service instead.
- Introduced a kill switch for the new error handling.
- Don't call stop on ServiceCallbacks if start hasn't been called.
Smoke test appTP

Avoid crash when onPrepareVpn fails

---

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageCategorySingleChoiceActivity.kt
app-tracking-protection/vpn-impl/src/main/res/layout/activity_report_breakage_category_single_choice.xml

Task/Issue URL: https://app.asana.com/0/1202279501986195/1203481901002309/f
By adding categories, we gained more useful signal on breakage even when people don't submit descriptions, but by limiting open text to only the "Something Else" category, we also decreased reports that included any text (down from about 64% before the change to just under 19% overall since). Allowing users to add text for any category would be a quick win to broaden signal a bit.
- Go to AppTP status page (or silent notification)
- Tap `Help us improve` -> `Submit a report` (or `Having problems with an app`) 
- Select an app
- Notice that you still must select a category, but all categories (not just "Something else") will now allow text input

AppTP: Allow text on any breakage category

---

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserChromeClientTest.kt
app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203175666892156/f 
This PR changes the progress value to be used to calculate the value of the progress bar, etc. We were incorrectly using newProgress which would trigger several callbacks reaching 100%.
_Feature 1_

Use the correct progress from webview

---

app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt

Task/Issue URL: https://app.asana.com/0/488551667048375/1203543139728360/f 
This PR fixes a cookie test that was failing when the language of the device/emulator wasn't English.

Make test work when phone in different language
