duckduckgo/Android

.github/PULL_REQUEST_TEMPLATE.md
The template was missing from this repo
=> Add pull request template to project

app/src/main/java/com/duckduckgo/mobile/android/duckduckgo/util/AppUrls.java, app/src/main/java/com/duckduckgo/mobile/android/duckduckgo/util/UrlUtils.java, app/src/test/java/com/duckduckgo/mobile/android/duckduckgo/ui/browser/BrowserPresenterTest.java, app/src/test/java/com/duckduckgo/mobile/android/duckduckgo/util/AppUrlsTest.java, app/src/test/java/com/duckduckgo/mobile/android/duckduckgo/util/UrlUtilsTest.java
Reviewer: @subsymbolic 
Asana: https://app.asana.com/0/0/353085934262755
**Description**: Improve url handling so the app correctly loads IP while perform searches for numbers and display correctly encoded characters in the OmniBar
TEST 1
1. Search an IP address the app should load the IP
2. Search a simple number or partial IP address the app will perform a search based on the input
TEST 2
1. Perform a search using special characters
2. The OmniBar will show the right input query
=> Improve url handling

app/build.gradle, app/src/main/java/com/duckduckgo/mobile/android/duckduckgo/App.java, app/src/main/java/com/duckduckgo/mobile/android/duckduckgo/data/bookmark/BookmarkJsonEntity.java, app/src/main/java/com/duckduckgo/mobile/android/duckduckgo/data/tab/TabJsonEntity.java, app/src/main/java/com/duckduckgo/mobile/android/duckduckgo/util/AppUrls.java
Reviewer: @subsymbolic 
Asana: https://app.asana.com/0/0/365896985611960
CC:
**Description**: Remove any console output from the Release version, and just print in Debug
=> Remove logging in release

app/build.gradle
Reviewer: @subsymbolic 
Asana: https://app.asana.com/0/0/373864980216716
**Description**: Sign the release apk with the same key used for "search and stories" app.
=> Add signing for the release apk

app/build.gradle, build.gradle, gradle.properties, versioning.gradle
Reviewer: @subsymbolic 
Asana: https://app.asana.com/0/0/373864980216715
**Description**: Use MM.mm.pp (Major.minor.patch) format for versionCode and build it from the versionName.
1. build various APK with different versionName and see that the generated versionCode is correct
=> Build versionCode from versionName

app/src/main/res/layout/viewholder_bookmark.xml
Reviewer:
Asana:
CC:
1. Click on 'Edit' button to edit existing bookmarks.
2. Enter a very long title in the title EditText field to check if the view overlaps or not.
=> Fix viewholder_bookmark layout for long Bookmark titles

app/src/main/java/com/duckduckgo/app/ui/editbookmark/EditBookmarkDialogFragment.java, app/src/main/res/values/strings.xml
Reviewer:
Asana:
CC:
1. Save or edit any bookmark.
=> Add 'Bookmark Saved' Toast

.github/PULL_REQUEST_TEMPLATE.md
Reviewer: Craig and Chris
Asana: https://app.asana.com/0/19626896268257/378961107749800
Tweak the PR template to for mobile
N/A
=> Tweak PR template for mobile

app/src/androidTest/java/com/duckduckgo/app/trackerdetection/AdBlockInstrumentationTest.kt, app/src/main/cpp/adblockplus-lib.cpp, app/src/main/java/com/duckduckgo/app/trackerdetection/AdBlockPlus.kt
Fixes travis test issue due to memory deallocation.
=> Release input memory later

.github/PULL_REQUEST_TEMPLATE.md
Asana Issue #: https://app.asana.com/0/414730916066338/486014412583136
Simplified PR template. This PR is itself representative of how a PR should look IMO. Discussion welcomed.
1. View this PR in GitHub 😀
=> Change GitHub PR template

.travis.yml, app/build.gradle, install_tools.sh
Asana Issue URL: https://app.asana.com/0/414730916066338/471193197990015
Allow jenkins to build and sign an android APK ready for release to the google play store.
1. Run the Jenkins release job at duckduckgo_app_release. Jenkins will pause to allow a tag to be entered
1. Once the build is complete validate that the apk produced is signed and can be uploaded to the play store.
We will also eventually automate the play store upload however this is not currently possible due to permissions.
=> Jenkins release build

app/src/main/java/com/duckduckgo/app/privacymonitor/ui/PrivacyDashboardViewModel.kt, app/src/main/res/values/strings.xml
Asana Issue URL: https://app.asana.com/0/471012189846020/502691608468014
Adding plural and non-plural version of strings.
**With privacy protection enabled**
1. Visit cnn.com
1. Open privacy dashboard as soon as possible
1. Observe the correct terms are used for network/major network tracking when count is 0 (pluralised)
1. Observe the correct terms are used for network/major network tracking when count is 1 (singular)
1. Observe the correct terms are used for network/major network tracking when count is 2 or more (pluralised)
Repeat the above steps, but with privacy protection **disabled**.
=> Pluralize networks tracked/blocked

app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Asana Issue URL: https://app.asana.com/0/414730916066338/492564757947847
Replaces the hitTest check for identifying if a user has intentionally navigated to a url, with a main frame check. This is a cleaner and mitigates concerns around whether a hittest would break on some javascript navigation.
1. Navigate to a tracker site such as facebook.com or google.com
1. Ensure it is not blocked
=> Replace hit test with main frame check to identify top level url

app/src/androidTest/java/com/duckduckgo/app/privacymonitor/ui/PrivacyDashboardViewModelTest.kt, app/src/main/res/values/strings.xml
https://app.asana.com/0/193817002363848/514702352138256
Copy update
1. Visit a site with trackers e.g theguardian.com
1. Open the privacy dashboard
1. Ensure upgrade text now says "enhanced" e.g "Enhanced from D to B"
=> Update copy from "upgraded" to "enhanced"

app/src/main/java/com/duckduckgo/app/job/AppConfigurationDownloader.kt, app/src/main/java/com/duckduckgo/app/trackerdetection/AdBlockClient.kt
Asana Issue URL: https://app.asana.com/0/414730916066338/521058321484735
Allow simultaneous processing of server requests
**BEFORE:**
**AFTER:**
Run the app and see that processing is happening simultaneously now. Also see logs above.
=> Allow merged download tasks to be executed at the same time

app/src/main/AndroidManifest.xml, app/src/main/java/com/duckduckgo/app/privacymonitor/ui/PrivacyDashboardActivity.kt, app/src/main/res/menu/menu_browser_activity.xml, app/src/main/res/values/strings.xml
Asana Issue URL: https://app.asana.com/0/414730916066338/523311310865090
Fix up navigation losing current page
1. Navigate to a web page
1. Open settings
1. Press the "up" button
1. App now returns to the page being browsing (like chrome) rather than empty search
=> Make browser singleTask to fix up behavior

app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingActivity.kt, app/src/main/res/layout/content_onboarding_no_trace.xml, app/src/main/res/layout/content_onboarding_protect_data.xml, app/src/main/res/values/colors.xml
https://app.asana.com/0/488551667048375/524930676159873
Update placeholder onboarding colors with design colors now that they have been provided
1. Run onboaridng
1. Note that the colors now blend with the onboarding images
=> Update placeholder colors

app/src/main/res/values/strings.xml
Asana Issue URL: https://app.asana.com/0/414730916066338/525598974713886
Correct "Terms of Service; Didn't Read" abbreviation
1. Navigate to a page
1. Open the Privacy Dashboard, Privacy Practices
1. Check the link is now ToS;DR
=> Update tosdr text

app/src/main/res/raw/tosdr.json
Asana Issue URL: https://app.asana.com/0/414730916066338/526624108986384
Updates tosdr data with latest version generated by extensions to include our static sites.
1. Visit "spreadprivacy.com"
1. Ensure it is listed as having "good privacy practices"
=> Add latest tosdr data

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt, app/src/main/res/values/strings.xml
Asana Issue URL: https://app.asana.com/0/488551667048375/524078036165570
Allow webview pdfs (and other files) to be downloaded
1. Visit https://espc.com/properties.aspx?area=stockbridge
1. Select a property
1. Tap schedule, it should download
=> Allow files such as pdfs to be downloaded

app/build.gradle, app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt, app/src/androidTest/java/com/duckduckgo/app/privacymonitor/model/TrustedSitesTest.kt, app/src/androidTest/java/com/duckduckgo/app/trackerdetection/TrackerDetectorTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt, app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt, app/src/main/java/com/duckduckgo/app/privacymonitor/model/TrustedSites.kt, app/src/main/java/com/duckduckgo/app/trackerdetection/TrackerDetector.kt, app/src/main/res/layout/content_onboarding_no_trace.xml
Asana Issue URL: https://app.asana.com/0/488551667048375/509644293434231
• Reduces incidence of resource load mismatch from other sites (still not perfect will revist)
• Optimises page speed by removing content blocking on trusted sites
• Improves parent tracker network matching
• Remove code coverage as it breaks unit test inspection
TEST ONE
1. Visit duckduckgo.com 
2. Note faster load speed now that we don’t run full site monitoring on trusted sites
TEST TWO
1. Visit cnn.com
2. In the middle of a load visit duckduckgo.com
3. Ensure site rating is still A
TEST THREE
1. Visit youtube.com
2. Note that google (which is parent network) is no longer blocked
=> Tracking improvements

app/src/androidTest/java/com/duckduckgo/app/trackerdetection/TrackerDetectorListTest.kt, app/src/main/java/com/duckduckgo/app/job/AppConfigurationDownloader.kt, app/src/main/java/com/duckduckgo/app/trackerdetection/Client.kt, app/src/main/java/com/duckduckgo/app/trackerdetection/TrackerDataLoader.kt, app/src/main/java/com/duckduckgo/app/trackerdetection/TrackerDetector.kt, app/src/main/java/com/duckduckgo/app/trackerdetection/api/TrackerDataDownloader.kt, app/src/main/java/com/duckduckgo/app/trackerdetection/api/TrackerListService.kt
Asana Issue URL: https://app.asana.com/0/488551667048375/524078036165568
Checks resources against a custom tracker whitelist before any further processing, ignoring them if found to be a match.
1.  Visit the apple.com/shop/buy-ipad and watch the logs
1. The page should render correctly and the logs should contain messages that resources are whitelisted, e.g.
`/com.duckduckgo.mobile.android V/TrackerDetector: https://www.apple.com/shop/buy-ipad/ipad-9-7 resource https://store.storeimages.cdn-apple.com/4974/as-images.apple.com/is/image/AppleInc/aos/published/images/i/pa/ipad/201703/ipad-201703-gallery4?wid=4000&hei=3072&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1505422693371 is whitelisted`
=> tracker whitelist

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserPopupMenu.kt, app/src/main/java/com/duckduckgo/app/global/ViewModelFactory.kt, app/src/main/java/com/duckduckgo/app/home/HomeActivity.kt, app/src/main/java/com/duckduckgo/app/privacymonitor/ui/PrivacyDashboardActivity.kt, app/src/main/res/color/browser_menu_icon.xml, app/src/main/res/color/browser_menu_text.xml, app/src/main/res/drawable/ic_arrow_back_24px.xml, app/src/main/res/drawable/ic_arrow_forward_24px.xml, app/src/main/res/drawable/ic_bookmark_24px.xml, app/src/main/res/drawable/ic_clear_browsnish_24px.xml, app/src/main/res/drawable/ic_overflow_24px.xml, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/popup_window_brower_menu.xml, app/src/main/res/layout/sheet_fire_clear_data.xml, app/src/main/res/menu/menu_browser_activity.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Asana Issue URL: https://app.asana.com/0/488551667048375/477327275839581
Add menu styling to the app
Check that the menu renders well across devices and has the correct buttons enabled/disabled on the home and browser screens
=> Browsing menu

app/src/main/java/com/duckduckgo/app/di/AndroidBindingModule.kt, app/src/main/java/com/duckduckgo/app/home/HomeActivity.kt
Fixes crash when pressing fire button
1. Tap on the fire button. It will no longer crash.
=> Adds home activity to DI so cookie dependency is injected

build.gradle
Asana Issue URL: n/a
Upgrade to latest stable Kotlin version - 1.2.20
You should also update the AS Kotlin plugin, using the `Tools`->`Kotlin`->`Configure Kotlin Plugin Updates` menu
Release Notes: https://blog.jetbrains.com/kotlin/2018/01/kotlin-1-2-20-is-out/
See Also: [explicitly opting in for using Kotlin Style Guide formatter in IDE](https://twitter.com/trionkidnapper/status/955361080192090112)
=> Upgrade to latest stable kotlin - `1.2.20`

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
Asana Issue URL: https://app.asana.com/0/392891325557410/529727022544678
Trim whitespace from queries.
1.  Enter " nytimes.com " and tap enter
1.  The nytimes site is opened
1. Do other searches and confirm everything is behaving as expected
=> trim user input on submission

app/src/main/java/com/duckduckgo/app/job/AppConfigurationJobService.kt
Asana Issue URL: https://app.asana.com/0/488551667048375/532267986401038
Fixes crash on failure to download app config
1. Turn on areplane mode
1. Launch fresh app
1. It should not crash
=> Fix no-network crash on download task

app/build.gradle, app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt, app/src/main/java/com/duckduckgo/app/browser/NestedWebView.kt, app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt, app/src/main/res/layout/activity_browser.xml
Asana Issue URL: https://app.asana.com/0/413877547933099/532522547697239
There appears to be a leak in WebView, so managing it manually allows us to use the application context which then allows the view model to be cleaned up properly and in turn fixes the bug.
Also added leak canary to the project to aid in future leak detection.
1.  Go to cnn.com
1.  Before it finishes loading, "burn" it and return to the home screen
1. Go to cnn.com again - should load properly
=> manually manage the web view in order to make sure it does not leak

app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt, app/src/main/java/com/duckduckgo/app/job/AppConfigurationDownloader.kt, app/src/main/java/com/duckduckgo/app/job/AppConfigurationJobService.kt
Asana Issue URL: https://app.asana.com/0/488551667048375/532267986401038
Use mergeDelayError to keep completable alive until all requests are done
TEST ONE:
1. Put mobile in airplane mode
1. Launch it, wait for 30 seconds
1. If it doesn't force close things are good
1. Now kill and repeat another 5 times
TEST TWO:
1. Put mobile in airplane mode
1. FRESH INSTALL it, launch the app, wait for 30 seconds
1. If it doesn't force close things are good
1. Repeat 5 times
=> Fix RX network error Crash

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt, app/src/main/AndroidManifest.xml, app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoActivity.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt, app/src/main/java/com/duckduckgo/app/global/DuckDuckGoActivity.kt, app/src/main/java/com/duckduckgo/app/global/ViewModelFactory.kt, app/src/main/java/com/duckduckgo/app/home/HomeActivity.kt, app/src/main/java/com/duckduckgo/app/privacymonitor/ui/PrivacyDashboardActivity.kt, app/src/main/java/com/duckduckgo/app/privacymonitor/ui/PrivacyPracticesActivity.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
Asana Issue URL: https://app.asana.com/0/361428290920652/532687991106939
Clean up the activity stack
Ensure the following still work:
1. Bookmarks
1. About page link
1. Tosdt lin
1. Sharing from outside the app
=> Clean up app stack

app/src/main/res/layout/activity_browser.xml
Asana Issue URL: N/A
Removing dead / unused xml
Make sure the app runs and this really is not needed
=> Remove unused icon

app/src/main/res/raw/tosdr.json
Asana Issue URL: https://app.asana.com/0/414730916066338/536777057011321
Update to use the latest ToSDR data
1.
=> Use latest tosdr data, as of 2018-01-25

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserPopupMenu.kt, app/src/main/java/com/duckduckgo/app/home/HomeActivity.kt, app/src/main/res/layout/popup_window_browser_menu.xml
https://app.asana.com/0/414730916066338/550678398757789
Low hanging fruit refactor. Make activities enable popup menu options they want rather than disabling options they don't want
TEST ONE:
1. Run the app
1. Go to the home page
1. Ensure the disabled options do nothing & the enabled ones continue to perform the correct options
TEST TWO:
1. Run the app
1. Go to the home page
1. Ensure the disabled options do nothing & the enabled ones continue to perform the correct options
=> Make activities enable popup options they want

app/src/main/res/drawable/search_background.xml, app/src/main/res/layout/activity_browser.xml, app/src/main/res/layout/content_home.xml
Asana Issue URL: https://app.asana.com/0/414730916066338/547792610048275
Adds a corner radius to search bars to match designs.
1. Open app
1. Note that the home search bar is slightly rounded
1. Tap the search bar and note that the browsing search bar is also rounded
=> Add search bar radius

app/src/androidTest/java/com/duckduckgo/app/browser/WebDataManagerTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt, app/src/main/java/com/duckduckgo/app/browser/WebDataManager.kt, app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt, app/src/main/java/com/duckduckgo/app/global/view/FireDialog.kt, app/src/main/java/com/duckduckgo/app/home/HomeActivity.kt
Asana Issue URL: https://app.asana.com/0/488551667048375/560129298337416
• Fixes issue where only one ddg cookie was maintained on fire
• Small refactor to allow unit testing
1. Got to ddg serp and change a bunch of settings
1. Press fire
1. Ensure those settings are still set
=> Fix issue where internal cookies were deleted by fire

app/src/main/res/values/styles.xml
Asana Issue URL: https://app.asana.com/0/414730916066338/574830763339677
Fixes incorrect padding for the enhanced grade in the scorecard activity
1. Visit cnn.com
1. Open the Privacy Dashboard
1. Tap on the Scorecard
1. Note that the "enhanced grade padding" is now aligned (it looked odd before)
=> Update incorrect scorecard padding

.github/PULL_REQUEST_TEMPLATE.md
Terribly important PR; adds spaces after the colons so I don't have to add them manually every PR. 
I'm not even sorry. 😎
=> Add spaces after colons

app/src/androidTest/java/com/duckduckgo/app/tabs/ui/TabRendererExtensionKtTest.kt, app/src/main/java/com/duckduckgo/app/tabs/ui/TabRendererExtension.kt, app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherAdapter.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/548822694948640
Adds favicons to the tab switcher. Also adds unit tests for tabs renderer.
1. Open tabs
1. Ensure that favicons appear
---
=> Add favicon and render unit tests

app/src/main/res/values/strings.xml
Fix typo in `strings.xml` file
=> Fix typo in strings.xml for autocomplete setting

NOTICE
Task/Issue URL: https://app.asana.com/0/557005053610373/656964099893868
CC: 
This seems to be a requirement for Apache Software Foundation projects:
https://www.apache.org/dev/apply-license.html#new
and good for us too IMO, as somewhere for copyright/attribution.
1. 
1. 
---
=> Added NOTICE file

README.md
**Task/Issue URL:**
https://app.asana.com/0/inbox/361428290920650/678639821475432/678102645353502
**Description:**
Remove email reference from project and replace with anonymous feedback link.
---
=> Remove email from readme

build.gradle, gradle/wrapper/gradle-wrapper.properties
Latest kotlin, gradle and AGP versions
1. Make sure you can build it and your AS is happy
---
=> Tooling update

README.md
Task/Issue URL: https://app.asana.com/0/361428290920652/725959318643122
Add hiring note to README page
---
=> Update README.md to include hiring

app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt, app/src/main/java/com/duckduckgo/app/httpsupgrade/api/HttpsUpgradeDataDownloader.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/787625704869940
Moves a heavy operation out of a database transaction that we are seeing SQLite errors in.
1. Run a clean install of the app
1. Give it a moment to download configuration
1. Go to http://example.com and make sure the page loads fine and that it is upgraded to https
---
=> Move https reload out of transaction

app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt, app/src/main/java/com/duckduckgo/app/global/DuckDuckGoActivity.kt, app/src/main/java/com/duckduckgo/app/global/Theming.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt, app/src/main/java/com/duckduckgo/app/settings/db/SettingsDataStore.kt, app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/361428290920652/816426578517931
Tech Design URL: https://app.asana.com/0/361428290920652/814618797160182
Adds light theme experiments this includes:
- Control, 50%, dark theme, no toggle
- Dark, 25%, dark theme default, theme toggle in settings
- Light, 25%, light theme default, theme toggle in settings
See the Asana task for more detail.
**Test one: Upgrading**
1. Install the app as an upgrade
1. Ensure the theme is dark and there **is no** theme toggle in Settings
**Test two: Control Group**
1. Comment out the mh & mj variants in `Variant Manager`
1. Run the app and ensure the theme is **dark**
1. Go to settings and ensure there **is no** theme toggle in Settings
**Test three: Light Theme with Switch** …
=> Add light theme experiments

app/src/androidTest/java/com/duckduckgo/app/global/install/AppInstallSharedPreferencesTest.kt
CC: 
In preparation from disabling the test orchestrator from CI builds (to dramatically improve build times), we need a small fix to a test.
1. Make sure CI doesn't fail
---
=> Use the target context for the unit test clearing

CONTRIBUTING.md, README.md
Task/Issue URL: https://app.asana.com/0/856498667320406/1107787706804409
Update README and contributions files to match iOS tweaks.
---
=> Tweak open source documentation

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt, app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt, app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt, app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1107763461148278
Release "add search widget to home" call-to-action a/b test globally
**TEST ONE: CTA shows on supported device**
1. Install on API >21 device
1. Ensure CTA **is** shown
**TEST TWO: CTA not shown on unsupported device**
1. Install on API 21 device
1. Ensure the CTA **is not** shown
---
=> Release add widget CTA globally

app/src/main/java/com/duckduckgo/app/notification/NotificationScheduler.kt
CC: 
Update return types as a result of a breaking change to the WorkManager api
1. Check it compiles
---
=> Use `Result.success()` style; what the latest WorkManager requires

bitrise.yml
CC: 
Attempt at fixing the build
1. Let's see if the checks complete successfully 👀 
---
=> Update bitrise.yml configuration file

app/src/main/java/com/duckduckgo/app/entities/api/EntityListDownloader.kt
Task/Issue URL: https://app.asana.com/0/361428290920652/1111964631553193
Removes recreation of entity list on every addition
1. Run a fresh install of the app
1. Allow entities to be downloaded (might take some time to sync)
1. Visit cnn.com and ensure that tracker list entities appear
---
=> Fix list recreation

.github/CODEOWNERS
Task/Issue URL: https://app.asana.com/0/488551667048375/1112655599625890
@brindy seems only fitting that you review this one 😉 
---
=> Remove brindy from codeowners file

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/361428290920652/1115524851215033
Check to ensure the ` hitTestResult.extra` is non-null before constructing a HitTestResult object. Fixes issue introduced in https://github.com/duckduckgo/Android/pull/458 where long pressing a non-link element (e.g facebook like buttons) could cause a crash.
1. Visit facebook
1. Long press on a like button to choose a non-standard one e.g laughing emoji
1. Ensure there is no crash
---
=> Fix crash on null url long-press

app/src/main/java/com/duckduckgo/app/httpsupgrade/HttpsUpgrader.kt
=> Add try/finally around bloom filter creation

app/src/androidTest/java/com/duckduckgo/app/httpsupgrade/BloomFilterTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1116259190409343
CC: 
Removes test which sometimes fails; a better test will be built soon.
---
=> Remove bloom filter test which isn't deterministic (sometimes fails)

app/src/main/java/com/duckduckgo/app/global/UriExtension.kt
Task/Issue URL: https://app.asana.com/0/inbox/608920331025313/893935403459752/1116986626461619
CC: 
Update to use new endpoint for favicon retrieval
1. Add a bookmark; then visit bookmarks and verify the favicon downloads correctly
1. Add to home screen; verify favicon is retrieved if available for that site
---
=> Update favicon service url

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1123251403566015 & https://app.asana.com/0/488551667048375/1123285964662985
Update variants:
- add clarity around shared/serp variants 
- set all existing variants to 0 allocation to make room for new upcoming variants.
@CDRussell I thought it might be helpful to you to have this in before you start adding your own variants. If not, I'm happy to close it out.
1. Run the app
1. Ensure only default allocation occurs
---
=> Remove old variants

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/java/com/duckduckgo/app/browser/LogoHidingLayoutChangeLifecycleListener.kt, app/src/main/java/com/duckduckgo/app/browser/LogoHidingLayoutChangeListener.kt, app/src/main/res/drawable/text_cursor.xml, app/src/main/res/layout/include_new_browser_tab.xml, app/src/main/res/layout/include_omnibar_toolbar.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1121885608456266
Improve widget animation. Changes include:
- making the omnibar text cursor more prominent
- having the logo fade in so that it doesn't suddenly "grab" attention away from the omnibar
1. Add a widget
1. Launch the app from the widget
1. Note that the omnibar text cursor is now more prominent and the logo fades in so that it doesn't suddenly "grab" attention away from the omnibar.
---
=> Improve widget animation

README.md
Task/Issue URL: https://app.asana.com/0/414730916066338/1129503565759423
CC: 
Removes "Android Engineer" from what we're currently looking to hire.
---
=> Update readme to remove "Android Engineer" from the hiring section

app/src/main/res/raw/tosdr.json
Task/Issue URL: https://app.asana.com/0/715106103902962/1132072455093653
CC: 
Updated privacy data for duck.com
---
=> Add privacy data for duck.com

app/src/androidTest/java/com/duckduckgo/app/statistics/api/StatisticsRequesterJsonTest.kt
Task/Issue URL: https://app.asana.com/0/547792610048271/1135166478475988
CC: 
1. Ensure the CI builds successfully
1. Ensure none of the logic in `StatisticsRequesterJsonTest.kt` has changed since this is an important test
---
=> Change JSON tests to ensure it works even when a proxy is enabled

app/src/main/java/com/duckduckgo/app/feedback/ui/negative/FeedbackTypeDisplay.kt, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/715106103902962/1134060828640424/f
CC: 
Adds translations for 21 extra languages
1. Test the app in English, and ensure there are no changes
1. Set your device language to some of the languages included in this PR, and check the translations look to be valid (as best as you can, given you might not understand the language!)
---
=> add additional language files

app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
Task/Issue URL:  #559 
- Removed non-translatable strings from all translations except default string resources.
- Changed Play Store to the correct official name: Google Play.
- Slightly corrected Russian translation.
- Slightly cleaned up the code in the resources.
1. Check the changes in the source code.
3. Run the app.
4. Check the correct placement of the changed labels.
---
Regards,
Ilya. )
=> Improved and cleaned up the string resources, especially Russian translation

.github/CODEOWNERS
Task/Issue URL: https://app.asana.com/0/608920331025315/1139003998368551
Adds a new codeowner
---
=> Add Marcos as codeowner

app/src/main/java/com/duckduckgo/app/feedback/api/SubReasonApiMapper.kt, app/src/main/java/com/duckduckgo/app/feedback/ui/common/FeedbackActivity.kt, app/src/main/java/com/duckduckgo/app/feedback/ui/negative/mainreason/MainReasonNegativeFeedbackFragment.kt, app/src/main/java/com/duckduckgo/app/feedback/ui/negative/subreason/SubReasonNegativeFeedbackFragment.kt
CC: 
Android studio was displaying various warnings like redundant declarations and declaration can be shifted to 'when' block. I resolved them
---
=> resolve warnings in feedback package

app/src/androidTest/java/com/duckduckgo/app/statistics/pixels/PixelNameTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1148195783707952
CC: 
Add unit test which checks for duplicate pixel names
1. verify the tests pass
1. deliberately add a duplicate pixel name; verify the test fails with a helpful message
---
=> Add unit test which checks for duplicate pixel names

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt, app/src/main/java/com/duckduckgo/app/global/Theming.kt, app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/1125189844152671/1147958843207995
CC: 
Before releasing https://app.asana.com/0/1125189844152671/1139689832008857 we want to test again which theme performs better by running a quick experiment.
**Dark Theme**
1. Launch the app and use the `mp` variant
1. Theming should default to dark
**Light Theme**
1. Launch the app and use the `mo` variant
1. Theming should default to light
---
=> Add experiment for light vs dark theme.

app/build.gradle, app/src/androidTest/java/com/duckduckgo/app/TestApplication.kt, app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1150206398963875
CC: 
Upgrades to latest LeakCanary
1. add a logcat filter for "leak"
1. Set logcat to DEBUG level
1. Run the app; verify you see logs for leak canary, as it checks for retained objects etc...
---
=> Upgrade to LeakCanary 2 (beta)

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt, app/src/main/java/com/duckduckgo/app/global/Theming.kt, app/src/main/java/com/duckduckgo/app/global/view/DaxDialog.kt, app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/1125189844152671/1151953812937609
CC: 
Removes the light vs dark theme experiment
1. Notice how the default theme is set to dark
---
=> Remove light/dark theme experiment

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/inbox/608920331025313/1144690884594465/1152114680049710
CC: 
Enables SERP variants
---
=> Enable `sc` and `se` SERP variants

app/src/main/java/com/duckduckgo/app/referral/AppInstallationReferrerStateListener.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1152880752098009
CC: 
During the slow rollout of this, we noticed some SecurityExceptions being thrown. So that's now IllegalStateException and SecurityExceptions thrown that we've observed when trying to connect to the library. Since this is non-crucial, I'd rather play this code safe and use a wider net to catch exceptions.
1. Check the change to catching a more general exception type is acceptable
---
=> Catch RuntimeException instead of IllegalStateException

app/src/main/res/values-nb/strings.xml
Task/Issue URL: https://github.com/duckduckgo/Android/blob/develop/TRANSLATIONS.md
I've made some minor changes to the Norwegian translations. Some summary/explanations/justifications as follows. 
* "Slett dine nettleserdata med et tastetrykk." 
Essentially: "Erase your browser data with the tap of a button."
Before: "(...) by pressing a button." 
* "Fremover"
Essentially: "Forward"
Before: "Further"
* "Del lenke," Kopier lenke"
"lenke" is more widely used and understood than "koplingadresse" or "delingskobling"
* "Det trengs forbedringer"
Essentially: "Needs work"
Before: "It should be worked a little with" 
* "Nettleserfunksjoner mangler eller fungerer dårlig"
Essentially: "(...) missing or not working well"
Before: "(...) missing or is obstructed"
**Steps to test this …
=> Some improvements to Norwegian translations

app/src/main/AndroidManifest.xml
Reverts duckduckgo/Android#659
=> Revert "Allow DDG to handle links from certain external applications"

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt, app/src/main/java/com/duckduckgo/app/browser/SmoothProgressAnimator.kt
Task/Issue URL: https://app.asana.com/0/1125189844152671/1161499456202321
CC: 
The way the progress bar is updated it stalls most of the time giving our users a not great experience. This PR adds a smoother progress bar animation starting to 50% and overriding it if a newer update comes through. 
1. Launch different websites: SERP, youtube, etc and notice how the progress bar animation is smoother than with the previous version.
---
=> Smoother progress bar

app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1161183674646970/f
CC: 
Removing `CoroutineScope` and `CoroutineContext` from `BrowserChromeClient` as currenlty is not used by any part inside that class.
---
=> Removing coroutineScope and context from BrowserChromeClient

app/src/main/java/com/duckduckgo/app/global/view/ClearPersonalDataAction.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1161183674646969/f
CC: 
Removing `coroutineScope` from `ClearPersonalDataAction`. That scope was not used internally in the class.
---
=> Remove coroutineScope from ClearPersonalDataAction

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/361428290920652/1158791274046897
Removes CTA validation variants, these were a retention only check so no product changes are being released. Experimental features were not deleted as these are still in use by other variants.
N/A just check the PR to ensure the experiment was deleted
---
=> Remove CTA validation variants

TRANSLATIONS.md, app/src/main/res/layout/include_system_search_onboarding.xml, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-et/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-lv/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/string-untranslated.xml, app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/inbox/361428290920650/1162245830220530/1165874149878470
- Adds full app translations for Estonian, Latvian and Turkish 
- Fills translation gaps for already supported languages
- Omits new onboarding experience strings as we are waiting for translator to correct these. These are not required yet as that feature is still under English-only experimentation
Note: We have requested translation feedback and will process this in subsequent follow-up PRs.
1. Run the app and make sure all looks ok!
---
=> Add Estonian, Latvian and Turkish support plus fill gaps in other languages

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
=> Keyboards hides when address bar loses focus

app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1170058833433224
CC: 
Adds suppress annotation to prevent code from automatically converting `OldOnboardingStore` to `UserStageStore`
1. From `develop`, launch the reformat dialog in Android Studio ("Show Reformat File Dialog")
1. Allow it to format the whole file. Verify it incorrectly converts to `UserStageStore` causing compilation issues
1. Revert changes
1. Switch to this branch and repeat. Verify it doesn't change the code.
---
=> Add suppress annotation for deprecation warning; prevents autoformatting

app/src/main/res/values-de/strings.xml
Task/Issue URL: https://app.asana.com/0/0/1168339814074823/f
CC: 
Updating german translations after internal review.
---
=> German translations reviewed

app/build.gradle
Task/Issue URL: https://app.asana.com/0/414730916066338/1171976226096753
CC: 
Adds explicit NDK version to the `build.gradle` file
1. Build and run the app; verify no behavioral changes introduced
2. Ensure the app builds on Bitrise
---
=> Add explicit NDK version to keep CI stable and happy

README.md
Hiring section of README was out of date, referencing a job no longer on the site. Text from Zbig, more generic so as not to require regular updates.
iOS PR is here: https://github.com/duckduckgo/iOS/pull/653
=> Update hiring section of readme

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/1157893581871903/1182470726458373
This PR enables the SERP header features. 
Tests were completed at https://github.com/duckduckgo/Android/pull/841
---
=> Activate Experiment: Test improvements to the double search header

app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-et/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-lv/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/string-untranslated.xml, app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1186419958972137/1186395188273577
CC: 
Adds translations for the rest of the languages we didn't do in https://github.com/duckduckgo/Android/pull/867
---
=> Add rest of translations to remove harmful strings

app/src/main/res/values/string-untranslated.xml
Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1188216308725793/1188318715658135
CC: 
Small change to amend the copy of the error message when we detect a dos security issue.
---
=> Amend copy

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/1125189844152671/1188820032478226
CC: 
Enables SERP variants and disables use our app variants.
---
=> Disable use our app flow experiment and enable serp variants.

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, app/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1198214882326082/f
CC: 
Disable se/sc variants
1. Ensure no users are allocated inside sc/se variants when performing a fresh install
1. 
---
=> Disable sc se variants

build.gradle, gradle/wrapper/gradle-wrapper.properties
Task/Issue URL: https://github.com/duckduckgo/Android/issues/964
CC: N/A
Upgrade gradle and android gradle plugin
1. Import app into Android Studio and build
---
=> Upgrade gradle and android gradle plugin #964

app/src/main/java/com/duckduckgo/app/browser/useragent/UserAgentProvider.kt
Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1198949801865453/1198949794416162
CC: 
Sovietgames seems to have a WP exploit that targets our UA. When our application is used as part of the UA the WP plugin from WooCommerce loads a few malicious links.
1. Go to sovietgames.su
1. Site should load and you should see 3 flags to change the language.
1. Going to the site from the `develop` branch would show malicious links instead of the flags.
---
=> Add ua application exclusion for sovietgames

app/src/main/res/values-de/strings.xml
Small changes I just came across, keep up the great work 🙌
Changes explained:
1. **Line 165:** "Abgeben" is closer to "submit" and sounds more natural in German. "Hinterlassen" has more a notion of "leaving sth behind" and is not as suitable AFAIK.
2. **Line 186:** Added the correct ending for " intelligenter" (female accusative). Small nit-pick.
3. **Line 410:** Replace the "sie" referring to the trackers with a "diese" (equals "those") to avoid the confusing "sie Sie" situation
4. **Line 411:** Added a missing colon after "Hinweis". Works the same as "Note: There will be dragons." in English.
=> Small updates to German translation

build.gradle
Task/Issue URL: https://app.asana.com/0/1198194956794324/1189595853338100/f
CC: 
Update to Kotlin 1.4.10
Have run the automatic migrations in Andorid Studio, no changes came back
1. clean build the app
2. app update and perform manual testing for browsing, bookmarks, fireproof sites etc
3. clean app install and perform manual testing for browsing, bookmarks, fireproof sites etc
---
=> Update to kotlin 1.4.10

app/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1199127532699907/f
CC: 
This PR adds a comment to document the usage of our new method `enqueuePixel`.
1. N/A
1. 
---
=> Document usage of Pixel.enqueueFire

app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt, app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt, app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/715106103902962/1194951515911867/f
CC: 
This PR updates the Dax Major Tracker Network copy.
We will use the same copy in cases where the visited site is a Major Tracker Site, or if the visited site is owned by a Major Tracker Site.
1. Fresh install
1. Visit any site owned by a major tracker
1. Ensure new copy is used
---
=> Use same Dax Cta Network copy for all major trackers

CONTRIBUTING.md
Task/Issue URL: https://app.asana.com/0/414730916066338/1199392787548853/f
CC: 
Remove duplicate line from contributing guide
---
=> Remove duplicate line from contributing guide

app/build.gradle, app/src/androidTest/java/com/duckduckgo/app/global/api/ApiRequestInterceptorTest.kt, app/src/androidTest/java/com/duckduckgo/app/statistics/api/StatisticsRequesterJsonTest.kt, app/src/main/java/com/duckduckgo/app/global/api/ResponseExtension.kt, app/src/main/java/com/duckduckgo/app/global/image/GlobalGlideModule.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1199688805752093/f
CC: 
Upgrade okHttp to 4.9.0. This should solve some crashes we're seeing that are happening in 3.x and are not to be fixed, see https://github.com/square/okhttp/issues/6144
1. Install app from this branch
2. Navigate, load bookmarks, add bookmarks, etc.
3. Check app behaves normally, favicons loaded, pages loaded etc
---
=> Upgraded okhttp to 4.9.0

CONTRIBUTING.md
Task/Issue URL: https://app.asana.com/0/0/1199563191310921/f
CC: 
Updating our contribution guidelines:
- How to report issues
- How to share feature requests (Github discussions)
- Brief description about labels we use to work with bug reports
1. 
1. 
---
=> Update contribution guidelines before enabling Github discussions

app/build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1199900494889724/f
CC: 
Since we added refresh versions, we no longer need the version deps in the build.gradle file
App shall compile
Project shall sync
---
=> Removed unused version deps

app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
CC: 
Cleaned up unused deps from the Application class
1. App compiles
---
=> Cleaned up unused injected deps in DuckDuckGoApplication

build.gradle
Task/Issue URL: https://app.asana.com/0/414730916066338/1200068884038476/f
CC: 
Jcenter will stop accepting new updates via their API staring by the end of this month. We are declaring mavenCentral before jcenter to give that repository more priority.
1. Project compiles without issues.
1. 
---
=> Add mavencentral as repository

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt, app/src/androidTest/java/com/duckduckgo/app/browser/downloader/UriUtilsFilenameExtractorTest.kt, app/src/androidTest/java/com/duckduckgo/app/fire/DataClearerTimeKeeperTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt, app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1200151077460478/f
CC: 
Makes a test class more deterministic, and ensures another can return reliable results on all platforms
1. Ensure all tests are passing
---
=> fix flakey tests

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/500019618144197/1200193866819187
CC: 
This PR enables the SERP variants
1. Make sure serp variants are enabled and you can get assigned to them when installing the app
---
=> Enable SERP variants

fastlane/Fastfile
Task/Issue URL: https://app.asana.com/0/0/1200265360186034/f
CC: 
Fixes two minor issues in the build/release scripts
- locale `en-CA` didn't receive receive notes (only `en-GB` and `en-US` did previously)
- release script still mentioned `master` instead of `main` branch
1. Minor changes to build script so no need to actually build it; just verify changes make sense
---
=> Update release script

app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteActivity.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserChromeClient.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt, app/src/main/java/com/duckduckgo/app/browser/session/WebViewSessionStorage.kt, app/src/main/java/com/duckduckgo/app/survey/ui/SurveyActivity.kt, build.gradle
Task/Issue URL: https://app.asana.com/0/414730916066338/1200258326618091/f
CC: 
Bump the *compile* SDK to 30. Please read [the asana task](https://app.asana.com/0/414730916066338/1200258326618091/f) for more context about why.
The PR also fixes some compile errors as in API 30 android fixed some nullability issues
NOTE: *this PR does not change the target SDK* that remains at 29
1. install/upgrade from this branch
2. verify the browser works as expected for the main features, bookmarks, fire button, fireproof sites, navigation, settings
---
=> Bump the compile SDK to 30

common/src/main/java/com/duckduckgo/app/global/ViewModelFactory.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1200319078848279/f
CC: 
Moved the VM factory into the `common` gradle module so that it can be used from other gradle modules.
See https://app.asana.com/0/414730916066338/1200319078848279/f for full context
This change is guarded by the compiler.
---
=> Moved ViewModelFactory.kt into common gradle module

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/inbox/1125189844075764/1200365711073665/1200367143246976
CC: 
This PR disabled the SERP variants
1. Make sure SERP variants are disable
---
=> Disable SERP variants

app/build.gradle, app/src/internal/java/com/duckduckgo/app/feature/DummyInternalFeature.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt, app/src/main/java/com/duckduckgo/app/settings/extension/InternalFeaturePlugin.kt, app/src/main/res/layout/content_settings.xml, app/src/main/res/layout/content_settings_internal.xml
Task/Issue URL: https://app.asana.com/0/0/1200587063988790/f
CC: 
This PR adds some infrastructure to easily create `internal` features what will have an entry point in the settings screen.
**How to add a new `internal` feature?**
After this PR, the process to add a new entry point to an internal feature is easy:
* Create a class that extends `InternalFeaturePlugin` and return it as a multibinding
```kotlin
@ContributesMultibinding(AppObjectGraph::class)
class MyInternalFeature @Inject constructor() : InternalFeaturePlugin {
override fun internalFeatureTitle(): String {
return "My Internal feature"
}
override fun internalFeatureSubtitle(): String {
return "brief summary of the feature"
}
override fun onInternalFeatureClicked(activityContext: Context) { …
```
=> Internal feature entry point

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt, app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt, app/src/androidTest/java/com/duckduckgo/app/email/AppEmailManagerTest.kt, app/src/androidTest/java/com/duckduckgo/app/email/EmailInjectorJsTest.kt, app/src/androidTest/java/com/duckduckgo/app/email/EmailJavascriptInterfaceTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt, app/src/main/java/com/duckduckgo/app/email/EmailInjector.kt, app/src/main/java/com/duckduckgo/app/email/EmailJavascriptInterface.kt, app/src/main/java/com/duckduckgo/app/email/EmailManager.kt, app/src/main/java/com/duckduckgo/app/email/db/EmailDataStore.kt, statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Task/Issue URL: https://app.asana.com/0/1125189844152671/1200635726526715
CC: 
This PR updates autofill to 3.1.1. This new version contains a breaking change so we now also need to support email cohorts. Furthermore this PR moves the injection of the JS code to the `onPageStarted` method which simplifies the code a bit (not having to check if the JS was already injected) and prepares the app for future autofill versions.
You might need to run this command before doing anything to fetch the changes from the submodule.
`git submodule update submodules/autofill`
1. Checkout branch
1. Run `git submodule`
1. Confirm autofill commit hash is`e4a5cc4543eb350bd0da197947ccd3423c999f92 `
**Autofill still works**
1. Sign in with your duck …
=> Update to autofill 3.1.1

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt, app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
Task/Issue URL: https://app.asana.com/0/30173902528854/1200582678097841/f
CC: 
Remove the pixel as it is noisy. 
1. install/upgrade from this branch
1. verify pixel is not sent
---
=> Remove m_fwu_r pixel

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1200701185339096
CC: 
This PR adds two new SERP variants and enables them to allocate 10% of users
1. Make sure variants are enabled and you can be allocated to them
---
=> Add new SERP variants and enable them

app/src/main/java/com/duckduckgo/app/browser/useragent/UserAgentProvider.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1200724333019262
CC: 
This PR adds `digid.nl` to the version exception list
1. Install from develop
1. Go to `digid.nl/inloggen`
1. Notice how the screen prompts you for a user/password
1. Install from this branch
1. Go to `digid.nl/inloggen`
1. Notice how in this case you can see a `Using the DigiD app` (Met de DigiD app in dutch) login to option
---
=> Remove version for digid.nl

app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt, app/src/main/res/layout/activity_bookmarks.xml
Task/Issue URL: https://app.asana.com/0/414730916066338/1200552671375508/f
CC: 
Migrates BookmarksActivity to use view binding.
1. Add a bookmark/favorite
2. Check that SnackBar is shown for export, import and delete bookmark/favorite
---
=> Migrate BookmarksActivity to view binding

.github/ISSUE_TEMPLATE/bug_report.yaml
Task/Issue URL: https://app.asana.com/0/414730916066338/1200542817901372/f
CC: 
Create a `bug_report.yaml` issue form that contains the same information that our `bug_report.md` issue template.
The idea to use issue forms rather than issue templates to further improve the quality of the information provided in the bug reports.
No need to test this PR. Only when merged we'll see the issue form.
---
=> Convert bug_report.md to issue form

app/src/androidTest/java/com/duckduckgo/app/browser/DuckDuckGoUrlDetectorTest.kt, app/src/androidTest/java/com/duckduckgo/app/email/EmailInjectorJsTest.kt, app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoUrlDetector.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1200756844139941/f
CC: 
This PR changes the `isDuckDuckGoEmailUrl` method to be more exact when matching our ddg email url.
1. Check the test case in the above task
---
=> Autofill ddg domain fix

.github/ci-gradle.properties, .github/workflows/ci.yml, .github/workflows/nightly.yml, gradle.properties
Task/Issue URL: https://app.asana.com/0/414730916066338/1200791973688147/f
CC: 
This PR uses GitHub actions as CI. 
For each push to develop/main or pull request created:
1. Runs spotless
1. Runs all JVM tests
1. Runs all Android tests on API 22 and 26
1. There is a nightly workflow to do all of the above every night at 2am UTC
1. Check the runs and make sure everything looks good -> https://github.com/duckduckgo/Android/actions/runs/1138623632 
---
=> Add GHA as CI

.github/PULL_REQUEST_TEMPLATE.md
Task/Issue URL: https://app.asana.com/0/1157893581871903/1200913299956876
This PR proposes new changes to the PR template, so that it's more up to date with our current way of working
=> first iteration of changes to the PR template

app/src/androidTest/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1200939440534399/f
Disables SERP experiment
1. Ensure no more installs are allocated in SERP variants
2.
=> Disable SERP experiment

common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/0/1200737087921823/1200940409297533
The items in the current Browser Menu are not using the correct text style. This PR ensures all items in the Browser menu use the correct style
_Browser Menu_
1. Open app
2. Open overflow menu, see difference
=> use proper text appeareance style in BrowserMenu

app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1200969709347490/f
This PR fixes the tests failing from #1398
1. Tests pass
=> Fix tests from #1398

app/src/main/AndroidManifest.xml, build.gradle
Task/Issue URL: https://app.asana.com/0/414730916066338/1200094754307600/f
This reverts commit 7614d64dcd44ef9fbde11718121600bc51e51ccf.
1. App should function as usual
=> Revert "Change target sdk to API 30 (#1385)"

app/src/main/res/values-ro/strings.xml
Task/Issue URL: https://app.asana.com/0/414730916066338/1201020163749457/f
Just improved a translation.
=> Updated Romanian translation for onboardingLetsDoItButton

app/src/main/java/com/duckduckgo/app/bookmarks/db/BookmarksDao.kt, app/src/main/java/com/duckduckgo/app/bookmarks/db/FavoritesDao.kt
https://app.asana.com/0/414730916066338/1201064723446061/f
Could not reproduce the issue.
Updated queries for favorites and bookmarks to use `=` instead of `like`.
Regression testing for the bookmark / favorite features (add / edit / remove).
=> Android crash on Favorite by URL

app/schemas/com.duckduckgo.app.global.db.AppDatabase/40.json, app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt, app/src/androidTest/java/com/duckduckgo/app/global/db/AppDatabaseTest.kt, app/src/androidTest/java/com/duckduckgo/app/survey/api/SurveyDownloaderTest.kt, app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt, app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt, app/src/main/java/com/duckduckgo/app/survey/api/SurveyDownloader.kt, app/src/main/java/com/duckduckgo/app/survey/api/SurveyGroup.kt, app/src/main/java/com/duckduckgo/app/survey/api/SurveyService.kt, app/src/main/res/layout/include_new_browser_tab.xml
This PR adds a few changes around surveys to be able to support a new email survey.
In the `SurveyService`, change the url to `http://ddg-sandbox.s3.amazonaws.com/survey/v2/survey-mobile.json`
_Survey doesn't show up in old app versions_
1. Build and launch the app from develop
1. In the app database check the survey table, you should the survey schedule with `daysInstalled = -1`
1. Perform a search and click `Hide` when the CTA shows up and then `Hide tips forever` to dismiss all the onboarding CTAs
1. Go to the new tab (home) screen, the survey CTA should not show up.
_Survey doesn't show up in old app versions after more than 30 days_
1. In the `AppInstallStore` change the method `AppInstallStore.daysInstalled()` to return 40L.
1. Rebuild and launch the app
1. Go to the …
=> Add email survey

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1200560158314978/f
Tries to avoid memory issues in production (if caused by our log).
_Feature 1_
1. 
2.
=> Change log to reduce memory footprint

.gitignore, app/build.gradle, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/com/duckduckgo/build_time/BuildAndTaskExecutionListener.kt, buildSrc/src/main/kotlin/com/duckduckgo/build_time/BuildTimePlugin.kt, buildSrc/src/main/kotlin/com/duckduckgo/build_time/TaskTimeRecorder.kt, buildSrc/src/main/kotlin/com/duckduckgo/build_time/reporter/BuildTimePluginExtension.kt, buildSrc/src/main/kotlin/com/duckduckgo/build_time/reporter/BuildTimeReporter.kt, buildSrc/src/main/kotlin/com/duckduckgo/build_time/reporter/CSVReporter.kt, buildSrc/src/main/kotlin/com/duckduckgo/build_time/reporter/ConsoleReporter.kt, buildSrc/src/main/kotlin/com/duckduckgo/build_time/reporter/PixelReporter.kt, buildSrc/src/main/resources/META-INF/gradle-plugins/com.duckduckgo.buildtime.properties
Task/Issue URL: https://app.asana.com/0/414730916066338/1201214088471062/f
Measure build times.
Look at the [Asana task](https://app.asana.com/0/414730916066338/1201214088471062/f) for more information
Follow the instructions from [this task](https://app.asana.com/0/0/1201306706687024/f)
=> Android build times

app/src/main/java/com/duckduckgo/app/browser/useragent/UserAgentProvider.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1201293036966100/f
_Feature 1_
1. Visit https://www.xfinity.com/stream/
2. Ensure you don't see a disclaimer saying our browser is not compatible.
=> Add new exception in ua provider

privacy-config/privacy-config-impl/build.gradle, versions.properties
Task/Issue URL: https://app.asana.com/0/414730916066338/1201411526897036/f
Fixes robolectric tests which fail on Apple Silicon (M1) hardware
Ensure all tests pass: `./gradlew checks`
=> Fix failing robolectric tests

install_tools.sh
Task/Issue URL: https://app.asana.com/0/414730916066338/1201403896220536/f
Add the git commit hooks configuration to the `install_tools.sh` script
Execute scripts and check hooks are setup correctly
=> Add git hooks configuration to install script

build.gradle, buildSrc/src/main/kotlin/com/duckduckgo/build_time/BuildAndTaskExecutionListener.kt, gradle/wrapper/gradle-wrapper.properties
Task/Issue URL: https://app.asana.com/0/414730916066338/1200759779300446/f
CC: 
Updates Gradle version, as well as the AGP version.
ℹ️  Requires >= JDK 11 to be used when building the app. This is bundled by default in newer Android Studio versions but might require configuring on the command line
1. Build the project in Android Studio and/or IntellJ IDEA
1. Build the project from command line: `./gradlew clean assemblePD`
---
=> update gradle and android gradle plugin versions

.github/workflows/ci.yml, app/build.gradle, feature-toggles/feature-toggles-api/build.gradle, feature-toggles/feature-toggles-impl/build.gradle, gradle/android-library.gradle, privacy-config/privacy-config-api/build.gradle, privacy-config/privacy-config-impl/build.gradle, privacy-config/privacy-config-store/build.gradle
Task/Issue URL: https://app.asana.com/0/414730916066338/1201415411850079/f
Use `gradle checks` in the `ci.yml` for GHA. More detailed information in the [asana task](https://app.asana.com/0/414730916066338/1201415411850079/f). It will run:
* spotless
* unit tests for all modules
* android tests for all modules
The `gradle checks` has been split in two to aid while executing in the GHA:
* `jvm_checks` -> runs spotless and unit tests
* `android_checks` -> runs Android tests
`gradle checks` runs both so that it can still be use locally in dev machines
This PR should have all checks green
=> Use gradle checks for CI GHA

app/src/main/AndroidManifest.xml, versions.properties
Task/Issue URL: https://app.asana.com/0/414730916066338/1201445526459254
This PR upgrades Work Manager to the latest version.
_Make sure Work Manager still works!_
Some areas to check
1. Remote privacy config is downloaded correctly
1. Notifications work as expected (change the notifications scheduler to a few seconds rather than day to test this)
1. Overall filter for "work" in the logcat to check everything is being scheduled.
=> Upgrade WorkManager to 2.7.1

gradle/android-library.gradle
Task/Issue URL: https://app.asana.com/0/414730916066338/1201480938769898/f
Ensures that invoking the top-level `./gradlew checks` runs all tests across all modules
- Make a test deliberately fail, such as  one of the `RealPrivacyConfigDownloaderTest` tests
- Run `/gradlew checks` and verify the failing test is captured (repeating this on `develop` wouldn't catch this test failure)
=> Restore gradle checks task in android-library

app/src/androidTest/java/com/duckduckgo/app/email/ui/EmailProtectionSignInViewModelTest.kt, app/src/main/java/com/duckduckgo/app/email/ui/EmailProtectionSignInFragment.kt, app/src/main/java/com/duckduckgo/app/email/ui/EmailProtectionSignInViewModel.kt, app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt, app/src/main/java/com/duckduckgo/app/waitlist/email/EmailWaitlistNotificationDialog.kt, app/src/main/java/com/duckduckgo/app/waitlist/trackerprotection/ui/AppTPWaitlistActivity.kt, app/src/main/java/com/duckduckgo/app/waitlist/trackerprotection/ui/AppTPWaitlistViewModel.kt, app/src/test/java/com/duckduckgo/app/waitlist/trackerprotection/ui/AppTPWaitlistViewModelTest.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt, vpn/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1201468074269655/f
Add pixels to both ATP and email products to understand the funnel for the waitlist.
The following pixels will be added:
* waitlist dialog impression
* m_atp_imp_waitlist_dialog_c
* email_did_show_waitlist_dialog
* user clicks on "notify me" in the waitlist dialog
* m_atp_ev_waitlist_dialog_notify_me_c
* email_did_press_waitlist_dialog_notify_me
* user clicks on "no thanks" in the waitlist dialog
* m_atp_ev_waitlist_dialog_dismiss_c
* email_did_press_waitlist_dialog_dismiss
_requirements_
1. go to `InternalAppTrackingProtectionWailistDataStore` and comment lines 24-27 for this branch
_test notify me_
1. fresh install from this branch
1. open app and go to email waitlist
1. join the waitlist
1. click on "notify me" …
=> Add pixels around waitlist beta dialog

app/src/androidTest/java/com/duckduckgo/app/referencetests/DomainsReferenceTest.kt, app/src/androidTest/resources/reference_tests/domain_matching_tests.json
Task/Issue URL: https://app.asana.com/0/1125189844152671/1201486268425745
This PR adds reference tests for domain blocking
All tests should pass
=> Add reference tests for domain blocking

privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/gpc/RealGpc.kt, privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/GpcHeaderReferenceTest.kt, privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/GpcJavascriptReferenceTest.kt, privacy-config/privacy-config-impl/src/test/resources/reference_tests/gpc/config_reference.json, privacy-config/privacy-config-impl/src/test/resources/reference_tests/gpc/tests.json
Task/Issue URL: https://app.asana.com/0/1125189844152671/1201486268425749
Adds reference tests for GPC. It also adds a new domain to the GPC list to be aligned with iOS.
_All tests pass_
1. All tests pass
=> GPC reference tests

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/HealthClassifier.kt, vpn/src/main/java/dummy/ui/VpnDiagnosticsActivity.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1201572832925525/f
Adds extra raw metrics to be included in AppTP health report
=> Add extra metrics for TUN inputs

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/InfoPanel.kt, common-ui/src/main/res/values/styles.xml, vpn-internal/src/main/res/layout/activity_exception_rules_debug.xml, vpn-internal/src/main/res/values/strings.xml, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionExclusionListActivity.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt, vpn/src/main/res/layout/activity_device_shield_activity.xml, vpn/src/main/res/values/strings-vpn.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1201027352531949/f
With AppTP, we introduced a new component called "InfoPanel". However, this component was not standarized across all screens that use it. This PR fixes that
=> remove duplicate styles, ensure InfoPanel is used properly

app/src/androidTest/java/com/duckduckgo/app/browser/downloader/DownloaderUtilTest.kt, app/src/androidTest/java/com/duckduckgo/app/browser/downloader/UriUtilsFilenameExtractorInternalTest.kt, app/src/main/java/com/duckduckgo/app/browser/downloader/DownloaderUtil.kt, app/src/main/java/com/duckduckgo/app/browser/downloader/FilenameExtractor.kt, app/src/main/java/com/duckduckgo/app/browser/downloader/NetworkFileDownloader.kt, app/src/main/res/values/string-untranslated.xml
Task/Issue URL: https://app.asana.com/0/0/1201640175947326/f
Made the new approach for downloads available to Internal builds and kept the original one for the public builds.
Internal build
- fresh install from this branch using the Internal flavor
- double check in Settings that you are indeed using Internal
- download this image https://miro.medium.com/max/1050/0*BRkMUINdhCYPk1KM.jpg
- notice it works as expected
Play build
- fresh install from this branch using the Play flavor
- double check in Settings that you are indeed using Play
- download this image https://miro.medium.com/max/1050/0*BRkMUINdhCYPk1KM.jpg
- notice that nothing happens, there is no download notification and the file is not in Downloads 
Other downloads with issues can be found in …
=> Add download changes to internal builds only

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/1199371158290272/1201674863186132/f
Rather than restarting the VPN when establishing the tun fails - which can conflict with the stop action the `establishVpnInterface()` method performs upon error - we'll just pixel the event to know how common this issue is.
Code review
=> Pixel VPN tun establish error

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppBadHealthStateHandler.kt
Task/Issue URL: https://app.asana.com/0/1199371158290272/1201674863186125/f
In internal builds, build flavor is send as `model` value instead of `model`.
Fix that
code reivew
=> Fix model pixel value in internal builds

app/src/main/java/com/duckduckgo/app/waitlist/trackerprotection/ui/AppTPWaitlistViewModel.kt
Task/Issue URL: https://app.asana.com/0/1199371158290272/1201677777496387/f
Waitlist dialog pixels are sent inside the dialog scope which is rapidly dismissed, so they're not sent according to our dashboards.
Ensure they're send inside the VM scope
code review
=> Ensure waitlist dialog pixels are sent

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldStatusReporting.kt
Task/Issue URL: https://app.asana.com/0/1199371158290272/1201677777496518/f
* The DAU and DIU first-in-day pixels are currently scheduled to fire every 12h
* This causes consistency issues as potentially the same users could be booked as both DAU and DIU
This PR will schedule the pixels to fire every 24h
The PR also migrates from `LifecycleObserver` to `LifecycleEventObserver` as described in [here](https://app.asana.com/0/414730916066338/1201421366311636/f)
_Test schedule_
We can't test whether the `m_atp_ev_enabled_d` without waiting 24h. That part should be easy to verify in code review
=> Schedule enabled unique pixel every 24h

app/src/androidTest/java/com/duckduckgo/app/referencetests/FireproofingReferenceTest.kt, app/src/androidTest/resources/reference_tests/fireproofing/tests.json
Task/Issue URL: https://app.asana.com/0/1125189844152671/1201707025099113
This PR adds reference tests for fireproofing
Tests pass
=> Add reference tests for fireproofing

privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/trackerallowlist/RealTrackerAllowlist.kt, privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/trackerallowlist/RealTrackerAllowlistTest.kt
Task/Issue URL:  https://app.asana.com/0/1125189844152671/1201646552983568
Rather than throwing an exception when we cannot parse a URL, return the URL.
Test pass
=> Return URL when we cannot parse it rather than throw an exception

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt
Task/Issue URL: https://app.asana.com/0/1199371158290272/1201752109049663/f
The `secondsSinceLastSwitch` JSON field in the `networkInfo` object was not sent properly. This PR fixes it.
The PR changes the shared preferences key to ensure a proper migration.
* filter logcat by `New network info`
_Test fresh install_
_Test app update_
=> Fix secondsSinceLastSwitch param in networkInfo JSON object

vpn/src/test/java/com/duckduckgo/mobile/android/vpn/cohort/RealCohortCalculatorTest.kt
Task/Issue URL: https://app.asana.com/0/0/1201758804893369/f
ditto
Test pass
=> Fix whenLocalDateIsFirstDayOfLastDayOf2021ThenReturnCohort test

app/src/main/res/layout/activity_app_tp_waitlist.xml, app/src/main/res/layout/activity_app_tp_waitlist_redeem_code.xml, app/src/main/res/layout/include_toolbar.xml, common-ui/src/main/res/layout/component_buttons.xml, common-ui/src/main/res/layout/include_default_toolbar.xml, common-ui/src/main/res/values/styles.xml, common-ui/src/main/res/values/widgets.xml, vpn/src/main/res/layout/activity_device_shield_activity.xml, vpn/src/main/res/layout/activity_device_shield_onboarding.xml, vpn/src/main/res/layout/activity_report_breakage_app_list.xml, vpn/src/main/res/layout/activity_report_breakage_text_form.xml, vpn/src/main/res/layout/activity_report_breakage_text_single_choice.xml, vpn/src/main/res/layout/activity_vpn_diagnostics_get_user_health_report.xml, vpn/src/main/res/layout/dialog_tracking_protection_confirm_disable.xml, vpn/src/main/res/layout/dialog_tracking_protection_manually_disable_app.xml, vpn/src/main/res/layout/dialog_tracking_protection_manually_enable_app.xml, vpn/src/main/res/layout/dialog_tracking_protection_restore_defaults.xml, vpn/src/main/res/layout/include_trackers_toolbar.xml
Task/Issue URL:  https://app.asana.com/0/1157893581871903/1201778980455784
With the implementation of new screens, some designs ask for the same button and toolbar styles we've used in the AppTP.
However, those styles are still living under the vpn module. This PR moves them to the proper place and renames them.
Usual smoke test
=> Created styles for Buttons, moved default toolbar to common-ui 

app/src/internal/AndroidManifest.xml
Task/Issue URL: https://app.asana.com/0/72649045549333/1201790503579802/f
Allow "always-on" configuration in internal builds only
_Verify always-on in internal builds_
_Verify always-on in internal builds_
=> Allow always-on in internal builds

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1201814931393696/f
* The NetworkTypeCollector registers a network callback to know when we have a network switch (eg. WIFI → CELLULAR)
* There seems to be an edge case where the unregisterNetworkCallback method is called however the registerNetworkCallback is not
* This seems to happen when we fail to create the TUN interface
* In such case the unregisterNetworkCallback method throws an Exception
This PR try-catches and proceeds.
Code review and run the steps below to ensure enable/disable AppTP is not affected
* Install from this branch
* Enable AppTP
* Verify AppTP is enabled
* Disable AppTP
* Verify AppTP is disabled
=> Safely unregisterNetworkCallback

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt, app/src/main/java/com/duckduckgo/app/privacy/ui/TrackerNetworkLeaderboardPillView.kt, app/src/main/res/layout/fragment_browser_tab.xml, app/src/main/res/layout/include_new_browser_tab.xml, app/src/main/res/layout/include_omnibar_toolbar.xml, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionAppsAdapter.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageAppListAdapter.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/PastWeekTrackerActivityContentView.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1201831685197526/f
Reverts https://github.com/duckduckgo/Android/pull/1699
_smoke test_
- open the browser
- test the onboarding
- visit any site and add a few favorites
- ensure widget cta works as expected
- ensure favorites shortcuts work as expected
- enable AppTP and validate app trackers history and list of apps inside their settings works
- visit privacy dashboard
- use the app as usual, just to see if we spot any bug coming from this migration
=> Revert ViewBinding fragment migration

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/DeviceShieldFAQActivity.kt
Task/Issue URL: https://app.asana.com/0/1199371158290272/1201814931393797/f
Fix crash when going to AppTP FAQ screen
_Check fix_
=> Fix AppTP FAQ crash

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/TwoLineListItem.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1201842748138411/f
Added `setImageDrawable` to `TwoLineListItem` and updated `setImageResource`.
The method is not yet used.
=> Update TwoLineListItem component

app/build.gradle, app/src/androidTest/java/com/duckduckgo/app/notification/AndroidNotificationSchedulerTest.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1201850526618162/f
Remove kotlin-reflect dependency
_Checks are green_
=> Remove kotlin-reflect dependency

versions.properties
Task/Issue URL: https://app.asana.com/0/0/1201852462006433/f
Updated some library dependencies
- Glide
- AppCompat
- localbroadcastmanager
- androidx.fragment
- androidx.lifecycle
- room
- glide
- LeakCanary
- Mockito
General smoke test to ensure no regressions
=> Update project library dependencies

app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt, app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt, app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt, app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt, app/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt, app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt, app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt, app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1201550925053699/f
Removed the usage of `liveTabs` and replaced them with `flowTabs`.
- open a 8-9 tabs using different methods: search something / open link in background tab / open in new tab
- switch between tabs
- close tabs from tab switcher activity
- open new tabs from tab switcher activity
- close all tabs from tab switcher activity
- open tabs and use the fire button
- check there is no unusual behaviour
https://user-images.githubusercontent.com/7963079/154678444-54cbe293-9d90-41c9-8e72-301afec741d1.mp4
=> Replaced liveTabs with flowTabs.

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/TunPacketReader.kt
Task/Issue URL: https://app.asana.com/0/1199371158290272/1201862327796488/f
When we detect an unknown packet we drop it, but we don't release the memory of the backing buffer
code review
=> Release backing buffer when dropping unknown packet

.github/workflows/ci.yml, build.gradle
Task/Issue URL: https://app.asana.com/0/414730916066338/1200947794830295/f
This PR bumps our minSdk to 23. 
_Checks are green_
=> Bump minSdk to 23

.github/workflows/nightly.yml
Task/Issue URL: https://app.asana.com/0/414730916066338/1201937305183222/f
Fixes nightly Github Action
N/A
=> Update nigthly emulator api level

app/src/main/java/com/duckduckgo/app/waitlist/trackerprotection/ui/AppTPWaitlistViewModel.kt, app/src/test/java/com/duckduckgo/app/waitlist/trackerprotection/ui/AppTPWaitlistViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1157893581871903/1201947193038576
We've made the decision to remove the notification prompt that we show after a user joins the waitlist, see [✓ Product Feedback Request: Drop beta waitlist notification permission prompt](https://app.asana.com/0/1175293949586521/1201907852539451)
_Join Waitlist_
=> removing notification from waitlist

app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt, app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
Task/Issue URL: [https://app.asana.com/0/1201807753394693/1201781057786340](https://app.asana.com/0/1201807753394693/1201781057786340)
Fix for a crash if user tries to load `file` scheme. For consistency `about` scheme is returning now SearchQuery UrlType instead Unknown.
_Feature 1_
=> Load file scheme searches

app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt, app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt, app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1201997255231410/f
This PR deletes the tracking parameter removal variants and releases the feature to 100% of users.
=> Delete tracking parameter removal variants

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1201997255231399/f
`try-catch` calls to `InetAddress.getAllByName` that are currently causing some crashes
code review
=> try-catch InetAddress.getAllByName() call

app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt, app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt, app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1202000801814766/f
This PR removes the unused `VariantManager` variable from the `SpecialUrlDetector`.
Code review
=> Remove VariantManager from SpecialUrlDetector

app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt, app/src/test/java/com/duckduckgo/app/browser/SpecialUrlDetectorImplTest.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1201998883341288/f
This adds the ability to handle the "site:" scheme correctly.
=> Handle site scheme

app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt, app/src/main/java/com/duckduckgo/app/pixels/EnqueuedPixelWorker.kt
Task/Issue URL: https://app.asana.com/0/0/1202000801814756/f
This PR removes the WebView feature supported pixel.
Code review
=> Remove WebView feature supported pixel

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1202005414608865/f
We expected Android to call the `onAvailable` and `onLost` callbacks in order. Meaning when there is a network switch, eg. from WIFI to CELL, Android would call `onLost(WIFI)` and then `onAvailable(CELL)`.
However that's not happening. Android can (in the example above) call `onAvailable(CELL)` when the WIFI signal is getting lost, and then `onLost(WIFI)` when it's definitely lost.
This was messing with our implementation because we never bother tracking what network was available or lost, we just assumed they'd be called in order.
The consequence of that was that we would report `currentNetwork` as `NO_NETWORK` when that was not the case.
_Test network connectivity_
=> Improve the network connection monitor reporting

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt
Task/Issue URL: https://app.asana.com/0/1199371158290272/1202010931522429/f
Add the Mobile Network Code (MNC) to reports
_Feature 1_
=> Report MNC

app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/1157893581871903/1202042345278979
Description
This PR updates the copy of the survey CTA.
=> update survey cta

app/src/main/java/com/duckduckgo/app/di/VariantModule.kt, app/src/test/java/com/duckduckgo/app/statistics/ExperimentationVariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1202062842238048/f
Enable variants to use the `AppBuildConfig` class so that we can filter on build configurations
* code review
* check unit tests
=> Pass AppBuildConfig to the Variant manager

app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
Task/Issue URL: https://app.asana.com/0/0/1202055398558039/f
Removes a duplicate, redundant line from application `onCreate`. 
- If the check wasn't true the first time, it won't be true the second time either. 
- If it was true the first time, the code wouldn't reach the second check
Eyeball the change; sense-check it. Make sure it really is redundant.
=> Remove redundant check from app onCreate

versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1202107830231731/f
Bumping some dependencies minor versions
Smoke tests for both browser and AppTP
=> Bump some deps minor versions

app/src/androidTest/java/com/duckduckgo/app/integration/HttpsEmbeddedDataIntegrationTest.kt, app/src/androidTest/java/com/duckduckgo/app/referencetests/HttpsReferenceTest.kt, app/src/main/java/com/duckduckgo/app/httpsupgrade/HttpsBloomFilterFactory.kt, app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1201965674208884/f
`try...catch` the bloom filter creation to avoid the crash spikes we're seeing.
=> Mitigate UnsatisfiedLinkError crash

build.gradle, common-ui/build.gradle, di/build.gradle
Task/Issue URL: https://app.asana.com/0/414730916066338/1202129306298790/f
Bump Anvil to 2.3.11 and fix missing dependencies in modules that used member injection
(optional) app builds and smoke tests
=> Bump anvil to 2.3.11

app/src/main/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptor.kt, app/src/test/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptorTest.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1202140108363807/f
Add ATB information to retention study metrics.
_Verify ATB is included_
=> Add ATB info to retention study metrics

app/src/main/res/values-ro/strings.xml
Task/Issue URL: https://app.asana.com/0/715106103902962/1202122274405234/f
Updated Ro translations.
- Change device language to Romanian
- Use the app and look at the texts
=> Romanian translations on Smartling

app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/1125189844152671/1202124607767411
This PR changes store to save in a Dax dialog. Translations will be handled separately whenever we request new ones.
N/A
=> Change copy in onboarding

app/src/main/res/values-it/strings.xml
Task/Issue URL: https://github.com/duckduckgo/Android/issues/559
Fixed/improved some it strings
Should not need tests
=> It translation improvement

.github/PULL_REQUEST_TEMPLATE.md, versions.properties
Task/Issue URL: https://app.asana.com/0/414730916066338/1202233226010705/f
Updates the following dependencies:
version.app.cash.turbine → 0.7.0 to 0.8.0
version.app.cash.turbine..turbine → 0.7.0 to 0.8.0
version.com.github.bumptech.glide..compiler → 4.13.1 to 4.13.2
version.com.github.bumptech.glide..glide → 4.13.1 to 4.13.2
version.com.github.bumptech.glide..okhttp3-integration → 4.13.1 to 4.13.2
version.google.android.material → 1.5.0 to 1.6.0
All unit tests should pass.
Run through the app and check that there isn't any unexpected behavior.
Smoke test:
Onboarding CTAs
Add bookmarks and favorites and check the snackbars
Disable/enable privacy protection
Share feedback
Fireproof a site and clear all data
Opening multiple tabs (and closing tabs + undo)
Download a file and check the …
=> Updated libraries.

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/DeviceInfoCollector.kt, vpn/src/test/java/com/duckduckgo/mobile/android/vpn/bugreport/DeviceInfoCollectorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202217410650615/f
Remove manuf/model from breakage report
(optional)
=> Remove device info from breakage report

versions.properties
Task/Issue URL: https://app.asana.com/0/0/1202242362476733/f
See [task](https://app.asana.com/0/0/1202242362476733/f)
Build passes
=> Update dagger to 2.42

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TCBCloser.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpConnectionInitializer.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpDeviceToNetwork.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpPacketProcessor.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpStateFlow.kt, vpn/src/main/java/xyz/hexene/localvpn/TCB.java
Task/Issue URL: https://app.asana.com/0/488551667048375/1202254803269921/f
Some cleanup of the TCP processor pipeline
Fix memory leak ie. we were not releasing the `responseBuffer` when sending the reset packet
Smoke tests for AppTP
=> Audit/clean up TCP processor chain

versions.properties
Task/Issue URL: https://app.asana.com/0/0/1202269450379817/f
Updated library:
- facebook.flipper 0.144.0 -> 0.145.0
1. Smoke test the app
=> Updated flipper library

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TCBCloser.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpConnectionInitializer.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpDeviceToNetwork.kt, vpn/src/main/java/xyz/hexene/localvpn/TCB.java
Task/Issue URL: https://app.asana.com/0/488551667048375/1202254803269921/f
We forgot in https://github.com/duckduckgo/Android/pull/1931 to be explicit about the TCB being a nullable type. This is done in this PR
smoke AppTP tests
=> Ensure we're explicit about TCB being null

app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-et/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-lv/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/string-untranslated.xml, app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/414730916066338/1202248365771000/f
Updated translations in all languages for downloads and automatic fireproof projects
- Change device language to any (but English)
=> Updated translations

app/src/main/java/com/duckduckgo/app/survey/api/SurveyService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202313204158627/f
New endpoint for the AppTP retention survey. For more context see [main task](https://app.asana.com/0/488551667048375/1202313204158627/f)
Test needs to be performed in devices below Android 12 and install PLAY flavor
_Test survey_
(it is needed to clear data and relaunch to get ATB variant associated)
_Test Android 12_
(This has been already verify but adding here for completeness)
_Test older app versions_
=> New endpoint for AppTP retention survey

privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/workers/RemoteConfigDownloadWorker.kt
Task/Issue URL: https://app.asana.com/0/1125189844152671/1202329383243640
Reduces the remote config interval to 1h
N/A
=> Reduce remote config interval

app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt, app/src/main/java/com/duckduckgo/app/pixels/EnqueuedPixelWorker.kt, app/src/test/java/com/duckduckgo/app/pixels/EnqueuedPixelWorkerTest.kt
This reverts commit 483d216e
Task/Issue URL: https://app.asana.com/0/1125189844152671/1202331639559224
This PR reverts #1927, more info in the task.
_App Launch_
_Fire button_
=> Revert "Fix App Launch Pixel (#1927)"

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1202348097691048/f
This PR removes tracking parameters before processing google.com AMP links.
=> Handle parameterized AMP links

secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorage.kt, secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorageModels.kt, secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/UserNotAuthenticatedException.kt, secure-storage/secure-storage-impl/build.gradle, secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/RealSecureStorage.kt, secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/di/SecureStorageModule.kt, secure-storage/secure-storage-store/build.gradle, secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageKeyStore.kt, secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageRepository.kt, secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/db/WebsiteLoginCredentialsDao.kt
Addressing all comments mentioned in https://github.com/duckduckgo/Android/pull/1924
N/A
N/A
=> Address comments in https://github.com/duckduckgo/Android/pull/1924

vpn/src/main/res/drawable/tracking_network_logo_microsoft_corporation.xml
Task/Issue URL: https://app.asana.com/0/1202279501986195/1202358703943372/f
Adding missing network icons
(Optional)
=> Add missing tracking network icons

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/network/channels/NetworkChannelCreator.kt
Task/Issue URL: https://app.asana.com/0/1202279501986195/1202397948211643/f
We don't need to protect sockets for 21 <= API <= 30.
See [asana task](https://app.asana.com/0/1202279501986195/1202397948211643/f) for more info
Perform AppTP smoke tests for Android 12 devices and devices with apis 21<= API <= 30.
We don't need to check all APIs, pick some of them.
Smoke test:
=> Avoid unnecessary socket protections

app/src/main/java/com/duckduckgo/app/onboarding/ui/page/vpn/VpnPermissionPage.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ApplicationInfoExtensions.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnOnboardingActivity.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1202360890245130/f
Fix some of the lint wranings.
_API 23_
_API < 26_
=> Alternative for older APIs

app/src/main/res/drawable/network_logo_microsoft_corporation.xml
Task/Issue URL: https://app.asana.com/0/0/1202451470485777/f
PR updates company logo icon.
See details in https://app.asana.com/0/0/1202451470485777/f
=> Update company icon

versions.properties
Task/Issue URL: https://app.asana.com/0/414730916066338/1202464623944581/f
version.androidx.appcompat=1.4.1 -> 1.4.2
version.androidx.constraintlayout=2.1.3 -> 2.1.4
version.androidx.core=1.7.0 -> 1.8.0
version.com.airbnb.android..lottie=5.1.1 -> 5.2.0
version.kotlinx.coroutines=1.6.1 -> 1.6.2
General smoke test
=> Update android library dependencies

secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorage.kt, secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorageModels.kt, secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/RealSecureStorage.kt
Task/Issue URL: https://app.asana.com/0/0/1202434443764031/f
Removal of user authentication from the secure storage API v1
Not applicable
=> Remove auth in secure storage

bandwidth/bandwidth-impl/src/main/java/com/duckduckgo/bandwidth/impl/AppTpBandwidthCollector.kt
Task/Issue URL: https://app.asana.com/0/0/1202474907741366/f
This PR adds sanity checks to ensure that values cannot be negative.
=> AppTP Beta bandwidth sanity checks

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/memory/VpnNetworkMemoryCollector.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/RecentAppTrackerCache.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TCBCloser.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpDeviceToNetwork.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpNetworkToDevice.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpPacketProcessor.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpSocketWriter.kt, vpn/src/main/java/xyz/hexene/localvpn/TCB.java
Task/Issue URL: https://app.asana.com/0/488551667048375/1202454731900854/f
The TCB sequence numbers and ack numbers are accessed/modified from different threads but that access is not synchronised.
This PR fixes that
- open apps that have trackers and verify it blocks
- perform speed tests and verify the perf is similar to develop
- downloads and uploads work as in develop
=> Thread Safety for TCB modifications

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpSocketWriter.kt
Task/Issue URL: https://app.asana.com/0/1202279501986195/1202494324737001/f
Updated TCB.writeQueue() to make use of the thread safe getOrPut(). This way we can remove the `@Synchronized` annotation.
- fresh install from this branch
- smoke tests on AppTP
- open apps that have trackers and verify it blocks
- perform speed tests and verify the perf is similar to develop
- downloads and uploads work as in develop
=> AppTP: Audit synchronized usage in RealTcpSocketWriter

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt, app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt, app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt, modules/autofill/autofill-api/src/main/java/com/duckduckgo/autofill/InternalTestUserChecker.kt, modules/autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/di/AutofillModule.kt, modules/autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/internal/RealInternalTestUserChecker.kt, modules/autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/internal/RealInternalTestUserCheckerTest.kt, modules/autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/InternalTestUserStore.kt, modules/autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt, modules/autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt
Task/Issue URL: https://app.asana.com/0/0/1202494823153095/f
This PR includes
- Introducing a mechanism to allow users to be internal test users
- Enabled autofill only for internal test users
_User is NOT an internal tester_
_User is opens internal tester success url_
_User is signs up to be internal test user_
_User is signs up to be internal test user but autofill is disbled_
=> Restrict autofill to internal test users

app/src/main/java/com/duckduckgo/app/global/store/AndroidAppProperties.kt, app/src/play/java/com/duckduckgo/referral/PlayStoreAppReferrerStateListener.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1202352847707236/f
Catches `RemoteExceptions` (`DeadSystemException`, `DeadObjectException`) in two places:
- When getting the `WebView` version name.
- When getting the install referrer.
=> Catch RemoteExceptions

modules/autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementDisabledMode.kt, modules/autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementEditMode.kt, modules/autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementListMode.kt, secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/L2DataTransformer.kt, secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/encryption/EncryptionHelper.kt, secure-storage/secure-storage-impl/src/test/java/com/duckduckgo/securestorage/impl/Fakes.kt, secure-storage/secure-storage-impl/src/test/java/com/duckduckgo/securestorage/impl/RealL2DataTransformerTest.kt
https://app.asana.com/0/0/1202518798495133/f
https://app.asana.com/0/0/1202518798495138/f
- Add handling for Xiaomi devices when launching settings page
- Synchronizing functions accessing the Cipher and separating cipher for encryption and decryption
=> Fix known issues for Autofill

app/src/main/AndroidManifest.xml, macos/macos-impl/src/main/AndroidManifest.xml, vpn-internal/src/main/AndroidManifest.xml, vpn/src/main/AndroidManifest.xml
Task/Issue URL: https://app.asana.com/0/414730916066338/1202373454969597/f
- `android:export` is set for all relevant components as required for Android 12
=> Set android:eexported to all necessary components in manifests

.github/workflows/create-asana-attachment.yaml
Task/Issue URL: https://app.asana.com/0/414730916066338/1202480033560072/f
Add workflow to perform GH<>Asana integration. The workflow will automatically add PR links to the Asana task linked in the PRs
PR link should automatically be added to the Asana task linked into this task
=> GH<>Asana integration

node_modules/.package-lock.json, node_modules/@duckduckgo/autofill/dist/autofill-debug.js, node_modules/@duckduckgo/autofill/dist/autofill.js, node_modules/@duckduckgo/autofill/integration-test/helpers/pages.js, node_modules/@duckduckgo/autofill/integration-test/tests/login-form.ios.spec.js, node_modules/@duckduckgo/autofill/packages/password/rules.json, node_modules/@duckduckgo/autofill/src/Form/Form.js, node_modules/@duckduckgo/autofill/src/Form/Form.test.js, node_modules/@duckduckgo/autofill/src/Form/matching.js, node_modules/@duckduckgo/autofill/src/Form/selectors-css.js, node_modules/@duckduckgo/autofill/src/Form/test-cases/index.js, node_modules/@duckduckgo/autofill/src/Form/test-cases/poor-markup-form.html, node_modules/@duckduckgo/autofill/src/Form/test-cases/vancity_login.html, node_modules/@duckduckgo/autofill/src/Scanner.js, node_modules/@duckduckgo/autofill/swift-package/Resources/assets/autofill-debug.js, node_modules/@duckduckgo/autofill/swift-package/Resources/assets/autofill.js, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/414730916066338/1202606878993713/f
Bump autofill version. Minor fixes and improvements.
_Fix for instagram_
=> Update autofill version

vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/processor/VpnPacketInterceptor.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpSocketWriter.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/udp/UdpPacketProcessor.kt, vpn/src/test/java/com/duckduckgo/mobile/android/vpn/processor/RealPacketInterceptorChainTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202611570636281/f
See asana task for more info
No test needed
=> Add source address/port to PacketInfo

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt, app/src/test/java/com/duckduckgo/app/browser/autofill/AutofillCredentialsSelectionResultHandlerTest.kt, app/src/test/java/com/duckduckgo/app/global/UriExtensionTest.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/di/AutofillModule.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/AutofillStoredBackJavascriptInterfaceTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/InlineBrowserAutofillTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/internal/RealInternalTestUserCheckerTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/jsbridge/response/AutofillJsonResponseWriterTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt, autofill/autofill-store/build.gradle, autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt, autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202611392391285/f
This PR includes the following:
- Add missing tests identified for autofill related classes/ logic
- Minor cleanup: Use AndroidJunit4 test runner instead of RobolectricTestRunner (http://robolectric.org/androidx_test/)
- Minor cleanup: Remove dagger/Anvil from autofill-store to align with our recommended standard
=> Increase test coverage for autofill related logic

downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/UrlFileDownloader.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202622298800481/f
When downloading a file, `contentLength` may not be known. This PR handles that case
_Test Bug fix_
- install from https://github.com/duckduckgo/Android/pull/2039
- download an MP3 file from "https://filesamples.com/formats/mp3"
- expected: in progress notification has % values above zero
- actual: in progress notification has negative % values
- download the same file from "https://filesamples.com/formats/mp3"
=> Handle unknown contentLength when downloading files

anrs/anrs-impl/build.gradle, app/build.gradle, bandwidth/bandwidth-impl/build.gradle, browser-api/build.gradle, downloads/downloads-impl/build.gradle, macos/macos-impl/build.gradle, privacy-config/privacy-config-api/build.gradle, privacy-config/privacy-config-impl/build.gradle, privacy-config/privacy-config-store/build.gradle, remote-messaging/remote-messaging-impl/build.gradle, voice-search/voice-search-impl/build.gradle, vpn-api/build.gradle, vpn-store/build.gradle, vpn/vpn-build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1202597451015882/f
This PR removes the usage of migrates to the approach 1 mentioned in the linked asana task. This also fixes other usages of api project.
=> Align how we define dependencies in app:build.gradle and other modules

downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DefaultFileDownloadNotificationManager.kt
Task/Issue URL: https://app.asana.com/0/0/1202633541688750/f
Setting the priority for the file download notifications
Nothing to test
=> Set notification priority

app/src/main/java/com/duckduckgo/app/pixels/OsVersionPixelInterceptor.kt, downloads/downloads-api/src/main/java/com/duckduckgo/downloads/api/DownloadCommand.kt, downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/FileDownloadCallback.kt, downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/FileDownloadNotificationActionReceiver.kt, downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/pixels/DownloadsPixelName.kt, downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/FileDownloadCallbackTest.kt
Task/Issue URL: https://app.asana.com/0/0/1202643385187948/f
Complement with couple more metrics, ie. file download retried, and file download cancelled by user
Incidentally I have also cleaned-up the `showNotification` field in the `DownloadCommand` model as it was no longer used for the new DL manager implementation
(optional)
=> Add DL manager metrics

app/src/androidTest/java/com/duckduckgo/app/notification/NotificationRegistrarTest.kt, app/src/main/java/com/duckduckgo/app/notification/NotificationPluginPoint.kt, app/src/main/java/com/duckduckgo/app/notification/NotificationRegistrar.kt, browser-api/src/main/java/com/duckduckgo/app/notification/model/NotificationPlugin.kt, downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/notifications/DownloadNotificationChannels.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1202643385187958/f
Avoid directly accessing `:download-impl` to register the DL notification channels
_Test notification channels_
=> Clean access to DL notification channels

secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorageModels.kt, secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/RealSecureStorage.kt, secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/di/SecureStorageModule.kt, secure-storage/secure-storage-impl/src/test/java/com/duckduckgo/securestorage/impl/RealSecureStorageTest.kt, secure-storage/secure-storage-store/schemas/com.duckduckgo.securestorage.store.db.SecureStorageDatabase/2.json, secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/db/SecureStorageDatabase.kt, secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/db/WebsiteLoginCredentialsEntity.kt, secure-storage/secure-storage-store/src/test/java/com/duckduckgo/securestorage/store/RealSecureStorageRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202631464736272/f
This PR includes the addition of the new data for that is required for autofill and the necessary migration for the database.
=> Add new columns for Autofill in secure storage

vpn/src/androidTest/java/com/duckduckgo/mobile/android/vpn/health/HealthClassifierTest.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/health/HealthClassifier.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202664362404535/f
See https://app.asana.com/0/488551667048375/1202664362404535/f for better context
Nothing, just unit testing
=> Disable socketReadExceptionAlerts mitigation 

app/src/main/java/com/duckduckgo/app/browser/SpecialUrlDetector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202373454969591/f
This replaces the 0 constant with a valid URI flag during parsing.
_App links_
_Non-HTTP URLs_
=> Replace URI_NO_FLAG with URI_ANDROID_APP_SCHEME

autofill/autofill-api/build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1202681060245086/f
Clean up
Should build
=> Remove unnecessary autofill-api deps

vpn-internal/build.gradle, vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsActivity.kt, vpn-internal/src/main/res/layout/activity_vpn_internal_settings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1202352847707245/f
Add an internal feature to force updating the AppTP bloclist.
_Test force update_
=> Internal feature to update blocklist

vpn/src/main/java/com/duckduckgo/mobile/android/vpn/processor/tcp/TcpNetworkToDevice.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202701239936870/f
Delay the network to device processing not to be so CPU intensive
Optional. Smoke test for AppTP
=> Delay network to device processing

autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt
- Due to merging order, this new test was merged even though it is broken. The tests have been passing but another PR that changes the viewmodel has been merged first.
=> Fix broken test for AutofillViewModel

build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1202717423070870/f
Ditto
=> No module can depend on :app

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/java/com/duckduckgo/app/email/ui/EmailProtectionFragment.kt, app/src/main/java/com/duckduckgo/app/feedback/ui/common/FeedbackFragment.kt, app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPage.kt, app/src/main/java/com/duckduckgo/app/onboarding/ui/page/OnboardingPageFragment.kt, app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementDisabledMode.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementListMode.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementLockedMode.kt, common-ui/src/main/java/com/duckduckgo/app/global/DuckDuckGoFragment.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/ComponentFragment.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/dialogs/DialogsFragment.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/palette/ColorPaletteFragment.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/typography/TypographyFragment.kt, di/src/main/java/dagger/android/DaggerFragment.kt, lint-rules/src/main/java/com/duckduckgo/lint/DuckDuckGoIssueRegistry.kt, lint-rules/src/main/java/com/duckduckgo/lint/NoFragmentDetector.kt, lint-rules/src/test/java/com/duckduckgo/lint/NoFragmentDetectorTest.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/report/DeviceShieldFragment.kt, vpn/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202717423070878/f
`Fragments` currently have an associated dagger component but are not dagger injectors.
Similar to what we did for Activities, create a `DuckDuckGoFragment` and `DaggerFragment` that contains all the logic so that we don't need to repeat it in every single fragment.
Smoke tests for:
* autofill fragments
* email fragments
* AppTP fragments
* browser fragment
* feedback fragment
=> Add DuckDuckgoFragment and use it

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesSubComponentCodeGenerator.kt, app/src/internal/java/com/duckduckgo/app/di.component/VpnInternalSettingsActivityComponent.kt, app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt, bandwidth/bandwidth-impl/src/main/java/com/duckduckgo/bandwidth/impl/AppTpBandwidthCollector.kt, di/src/main/java/dagger/android/AndroidInjector.kt, di/src/main/java/dagger/android/DaggerActivity.kt, vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/logs/DebugLoggingReceiver.kt, vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/remote/VpnRemoteFeatureReceiver.kt, vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/rules/ExceptionRulesDebugReceiver.kt, vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/trackers/DeleteTrackersDebugReceiver.kt, vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/transparency/VpnTransparencyModeDebugReceiver.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1202710479869519/f
See the [asana task](https://app.asana.com/0/1202552961248957/1202710479869519/f) for full context and explanation
=> Delay subcomponent generation

settings.gradle
Task/Issue URL: https://app.asana.com/0/1125189844152671/1202719320351812
Automate adding projects to settings.gradle
=> Clean up settings.gradle and automate how modules are added

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/domain/app/LoginCredentials.kt, autofill/autofill-api/src/main/java/com/duckduckgo/autofill/store/AutofillStore.kt, autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt, autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt, secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorage.kt, secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorageModels.kt, secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/RealSecureStorage.kt, secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageRepository.kt, secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/db/WebsiteLoginCredentialsDao.kt, secure-storage/secure-storage-store/src/main/java/com/duckduckgo/securestorage/store/db/WebsiteLoginCredentialsEntity.kt
Task/Issue URL: https://app.asana.com/0/0/1202727528852586/f
=> Convert autofill db primary keys to longs

app/src/main/java/com/duckduckgo/app/privacy/ui/WebsitesAdapter.kt, app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1202605670624090/f
Update unprotected sites header copy from "Fireproof sites" to "Unprotected sites".
=> Update unprotected sites copy

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/AutofillJavascriptInterface.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/jsbridge/request/AutofillStoreFormDataRequest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/AutofillStoredBackJavascriptInterfaceTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/jsbridge/request/AutofillJsonRequestParserTest.kt, autofill/autofill-impl/src/test/resources/json/storeFormData_additionalUnknownPropertiesIncluded.json, autofill/autofill-impl/src/test/resources/json/storeFormData_passwordMissing.json, autofill/autofill-impl/src/test/resources/json/storeFormData_usernameAndPasswordMissing.json, autofill/autofill-impl/src/test/resources/json/storeFormData_usernameAndPasswordNull.json, autofill/autofill-impl/src/test/resources/json/storeFormData_usernameAndPasswordProvided.json, autofill/autofill-impl/src/test/resources/json/storeFormData_usernameMissing.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1202705344705784/f 
Changes the domain object for credentials coming from JS to support nullable fields.
~Additionally, adds a coroutine handler in the autofill processing to ensure exceptions don't crash the whole app.~
=> Support incomplete logins from JS

app/src/main/java/com/duckduckgo/app/trackerdetection/TrackerDetector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202768642236786/f
This PR allows the tracker detector to return null which we then match to Client.Result(matches = false, isATracker = false)
=> Fix tracker detector crash

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/sorting/CredentialInitialExtractor.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/CredentialGrouperTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/CredentialInitialExtractorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202727215234443/f
Sorts all numbers into the # placeholder group.
=> Sort all numbers into # placeholder

autofill/autofill-api/src/main/java/com/duckduckgo/autofill/store/AutofillStore.kt, secure-storage/secure-storage-api/src/main/java/com/duckduckgo/securestorage/api/SecureStorage.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202776712844773/f 
Updates javadoc to reference the new return type when saving a credentials (a long indicating the new primary key of newly created credential)
n/a
=> Update javadoc for AutofillStore for saving credentials

privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackingparameters/tracking_parameters_matching_tests.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1202788884291393/f
Adds the last two tests found here:
https://github.com/duckduckgo/privacy-reference-tests/blob/main/url-parameters/tests.json
=> Add latest URL param reference tests

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementActivity.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillManagementRecyclerAdapter.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModel.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/FragmentUtils.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementListMode.kt, autofill/autofill-impl/src/main/res/layout/item_row_autofill_credentials_management_screen.xml, autofill/autofill-impl/src/main/res/layout/overflow_menu_list_item.xml, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/ui/credential/management/AutofillSettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202682552759994/f
- Adding the overflow menu with edit and delete to the list view item
- Adding functionality to the edit and delete through overflow menu
- Add a fix to the issue when autofill is backgrounded and device auth is removed.
_Overflow works as expected_
_Verify device auth bug is fixed_
-
=> Implement overflow for list items in autofill list view

.github/workflows/complete-asana-on-merge.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1202810419472777/f
Change the GH action for the Asana<>GH integration
Comment should be automatically created in the Asana task above
=> Asana<>GH integration

.github/workflows/complete-asana-on-merge.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1202810419472788/f
Ensure we only complete Asana tasks mentioned in the trigger-phrase
NA
=> Add trigger-phrase to complete asana workflow

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementListMode.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202821157855652/f 
Fixes memory leak from view binding in fragment
Smoke test credential management; ensure list loads ok
=> Fix memory leak on view binding in autofill management list mode fragment

app/src/androidTest/java/com/duckduckgo/app/bookmarks/db/BookmarkFoldersDaoTest.kt, app/src/androidTest/java/com/duckduckgo/app/bookmarks/db/BookmarksDaoTest.kt, app/src/androidTest/java/com/duckduckgo/app/bookmarks/model/BookmarksDataRepositoryTest.kt, app/src/androidTest/java/com/duckduckgo/app/bookmarks/model/FavoritesDataRepositoryTest.kt, app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsActivity.kt, app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsViewModel.kt, app/src/internal/res/layout/activity_dev_settings.xml, app/src/internal/res/values/strings.xml, app/src/main/java/com/duckduckgo/app/bookmarks/db/BookmarkFoldersDao.kt, app/src/main/java/com/duckduckgo/app/bookmarks/db/BookmarksDao.kt, app/src/main/java/com/duckduckgo/app/bookmarks/db/FavoritesDao.kt, app/src/main/java/com/duckduckgo/app/bookmarks/model/BookmarksRepository.kt, app/src/main/java/com/duckduckgo/app/bookmarks/model/FavoritesRepository.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202828754075050/f
This adds a developer setting to clear all folders, bookmarks and favorites.
=> Add clear SavedSites developer setting

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/state/AlwaysOnMonitor.kt
Task/Issue URL: https://app.asana.com/0/1202279501986195/1202829949879812/f
See the Asana task for more information
_Test always on_
* install from this branch
* go to Android settings -> Network&internet -> VPN -> DDG gear and enable "always on"
* filter logcat by `m_atp_ev_always_on`
* open DDG browser and enable AppTP
* verify `m_atp_ev_always_on_enabled_d` is sent
* disable AppTP
* go to Android settings -> Network&internet -> VPN -> DDG gear and enable "always on" and "block connections without VPN"
* open DDG browser and enable AppTP
* verify `m_atp_ev_always_on_lockdown_enabled_d` is sent 
* disable AppTP
* go to Android settings -> Network&internet -> VPN -> DDG gear and disable both "always on" and "block connections without VPN"
* open DDG browser and enable AppTP
* verify …
=> Report always-on mode

app/src/main/java/com/duckduckgo/app/autofill/FileBasedJavascriptInjector.kt
Task/Issue URL: https://app.asana.com/0/0/1202860399421629/f
This PR ensures that there's only a single instance of FileBasedJavascriptInjector
=> Mark FileBasedJavascriptInjector singleinstance

autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_edit_mode.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1202854142935495/f
Fixes the scrolling in credential view/edit modes so that all content is always reachable and visible.
=> Fix scrolling in view and edit mode

autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_list_mode.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1202882686065976/f
Update style from Title to Body1
=> Fix autofill toggle style

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/privacy.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1202897073590639/f 
This PR changes out CI setup to only allow one job at a time per branch to avoid running duplicated jobs at the same time for the same branch
N/A
=> Change concurrency to only allow one job at a time per branch

autofill/autofill-store/build.gradle, autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt, autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt
Task/Issue URL: https://app.asana.com/0/0/1202897877101654/f
=> Fix disk io on main thread, SecureStoreBackedAutofillStore

ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/1_-_y.js_heuristic;_no_ad_domain_param;_u3_param_included.yaml, ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/2_-_m.js_heuristic;_no_ad_domain_param;_dsl_param_included.yaml, ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/1_-_Single-site,_single-tab,_session.yaml, ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/2_-_Single-site,_new-tab,_session.yaml, ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/3_-_Single-site,_new-tab,_session_variant_two.yaml, ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/4_-_Single-site,_multi-tab_session.yaml, ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/5_-_Multi-site,_single-tab,_session.yaml, ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/6_-_Multi-tab.yaml, ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/7_-_Browser_restart_mid-session.yaml, ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/8_-_Navigation_with_back_forward.yaml, ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/9_-_Navigation_with_refresh.yaml
Task/Issue URL: https://app.asana.com/0/1200905986587319/1202905097109011/f
Updated maestro tests to reflect the new config changes.
- run all maestro tests
=> Updated maestro tests to reflect the new config changes.

app-tracking-protection/vpn-impl/build.gradle, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/health/AppBadHealthStateHandlerTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/prefs/VpnSharedPreferencesProviderImplTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/stats/AppTrackerBlockingStatsRepositoryTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/PrivacyReportViewModelTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldDailyNotificationFactoryTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldNotificationFactoryTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldReminderNotificationSchedulerTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldWeeklyNotificationFactoryTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModelTest.kt, app-tracking-protection/vpn-store/build.gradle, app-tracking-protection/vpn-store/src/test/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabaseTest.kt, app-tracking-protection/vpn-store/src/test/java/com/duckduckgo/mobile/android/vpn/trackers/AppTrackerRepositoryTest.kt, remote-messaging/remote-messaging-store/build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1202904518049662/f 
Move android tests from VPN modules to JVM
=> Move vpn tests to JVM

app/src/main/java/com/duckduckgo/widget/SearchAndFavoritesWidget.kt
Task/Issue URL: https://app.asana.com/0/0/1202898288430601/f
- Enable StrictMode (see [here](https://app.asana.com/0/0/1202897877101652/f))
- Add Logcat filter: AppWidgetThemePreferences
- Run the app, and do the following to reproduce StrictMode warning in develop:
- Go through onboarding
- Hit the home button, and add a widget, choosing the SearchAndFavorites Widget
- Resize it
=> Fix disk io on main thread, SearchAndFavoritesWidget

app/src/androidTest/java/com/duckduckgo/app/browser/favicon/DuckDuckGoFaviconManagerTest.kt, app/src/main/java/com/duckduckgo/app/bookmarks/db/FavoritesDao.kt, app/src/main/java/com/duckduckgo/app/bookmarks/di/BookmarksModule.kt, app/src/main/java/com/duckduckgo/app/bookmarks/service/SavedSitesImporter.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksAdapter.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksEntityQueryListener.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/FavoritesAdapter.kt, app/src/main/java/com/duckduckgo/app/browser/favicon/DuckDuckGoFaviconManager.kt, app/src/main/java/com/duckduckgo/app/global/view/FaviconImageView.kt, browser-api/src/main/java/com/duckduckgo/app/browser/favicon/FaviconManager.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/TwoLineListItem.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1202088634690441/f
Changes:
1/ Updated to insert all bookmarks in one go and all favorites in one go. 
2/ Removed the ListAdapter along with the DiffCallback from BookmarksAdapter / FavoritesAdapter. This was incredibly slow, taking more than 20 seconds to display a list, unlike a regular implementation of RecyclerView.Adapter.
3/ Removed the usage of findViewById() when updating the viewholder in both BookmarksAdapter and FavoritesAdapter. Updated the TwoLineListItem custom view to give access to the image.
4/ Updated the loadFavicon in both BookmarksAdapter and FavoritesAdapter to do all operations needed to find the favicon using the IO dispatcher. Updated the actual Glide call which loads the image to use the Main dispatcher and …
=> Improved bookmarks screen performace.

app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1201078435129729/f
PR introduces max active size on BrowserActivity.
This will test the hypothesis that allowing to have infinite tabs alive in the browserActivity causes memory and binder exceptions.
To validate the assumption, we are going to keep track of the latest 40 visited tabs in memory, and remove from the fragment manager the rest of them.
_Test 1_
_Test 2_
=> Introduce max active tabs in BrowserActivity

app/src/main/java/com/duckduckgo/app/fire/AutomaticDataClearer.kt
Task/Issue URL: https://app.asana.com/0/0/1202965571775116/f
Fixes a regression introduced in https://github.com/duckduckgo/Android/pull/2249, whereby the work manager request was erroneously dropped.
=> Restore enqueing work request

node_modules/@duckduckgo/privacy_dashboard/build/android/public/css/base.css, node_modules/@duckduckgo/privacy_dashboard/build/android/public/js/base.js, node_modules/@duckduckgo/privacy_dashboard/build/windows/public/css/base.css, node_modules/@duckduckgo/privacy_dashboard/build/windows/public/js/base.js, package-lock.json, package.json, privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/RequestDataViewStateMapper.kt
Task/Issue URL:  https://app.asana.com/0/0/1202981176451227/f
Limit the 'category' field of the `DetectedRequest.category` to a known subset.
_Feature 1_
=> fix categories + latest PD

app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksAdapter.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksEntityQueryListener.kt
Task/Issue URL: https://app.asana.com/0/1200905986587319/1203036016848820/f
Added debounce for bookmarks filtering.
=> Android: Debounce filtering for bookmarks

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203029803311273/f
Handle the case when android does not find the app given its uid.
* AppTP should continue blocking as usual
* code review
=> Handle unknown apps

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserChromeClientTest.kt, app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt, app/src/main/java/com/duckduckgo/app/di/PrivacyModule.kt, app/src/main/java/com/duckduckgo/app/location/data/LocationPermissionsRepository.kt, app/src/main/java/com/duckduckgo/app/sitepermissions/SitePermissionsViewModel.kt, site-permissions/site-permissions-api/src/main/java/com/duckduckgo/site/permissions/api/SitePermissionsDialogLauncher.kt, site-permissions/site-permissions-api/src/main/java/com/duckduckgo/site/permissions/api/SitePermissionsManager.kt
Added few tests and documentation for site permissions API
=> Documentation and tests

app/src/androidTest/java/com/duckduckgo/app/referencetests/FireproofingReferenceTest.kt, app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt, app/src/main/java/com/duckduckgo/app/fire/DuckDuckGoCookieManager.kt, app/src/test/java/com/duckduckgo/app/fire/WebViewCookieManagerTest.kt, common/src/main/java/com/duckduckgo/app/global/AppUrl.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203054500211636/f 
This PR expands the firebuttons to domains to include surveys.duckduckgo.com
Survey has already been tested internally, see https://app.asana.com/0/0/1202940869127166/1203066880046697/f
=> Expand Firebutton domains

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt, statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Task/Issue URL: https://app.asana.com/0/0/1203077746927173/f
Removes the app links exception pixel.
Code review
=> Remove app links exception pixel

app/src/androidTestPlay/java/com/duckduckgo/app/integration/HttpsEmbeddedDataIntegrationTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203035277827863/f
Ignore `whenUpgraderLoadedWithEmbeddedDataAndItemInBloomListThenUpdgraded` as it is flaky right now
NA
=> Ignore flaky bloom filter test

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203098895207076/f
VPN test routes only allowed in debug builds
NA. Just code review
=> VPN test routes only allowed in DEBUG builds

app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203093229437389/f
Adds an initialization check before accessing `searchListener`.
=> Add searchListener initialization check

.github/workflows/build-debug-apk.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203105723037252/f
- Adds a new workflow that builds an unsigned debuggable apk for every PR (opened, synchronised etc). APK will be an artifact on the workflow and uploaded as a zip. Just unzip the file to obtain the apk and it should be ready to install.
Sample: https://github.com/duckduckgo/Android/actions/runs/3190315636
Should build
=> Add build-debug-apk.yaml

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt, app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml
Task/Issue URL: https://app.asana.com/0/38424471409662/1203033091251185/f
Add instructions for AppTP translations
=> Add instructions for AppTP translations

node_modules/@duckduckgo/autofill/dist/autofill-debug.js, node_modules/@duckduckgo/autofill/dist/autofill.js, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/0/1203115049792256/f
- Bump json-schema-to-typescript from 10.1.5 to 11.0.2 by @dependabot in https://github.com/duckduckgo/duckduckgo-autofill/pull/203
- Fix incorrect schema by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/211
- Bump ts-to-zod from 1.10.0 to 1.13.1 by @dependabot in https://github.com/duckduckgo/duckduckgo-autofill/pull/210
- Update Asana token name by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/218
- More fixes and improvements by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/222
- Specific changes tested during the autofill release
- Instructions for smoke tests in the Asana task
=> Update autofill to 5.1.0

app/src/androidTest/java/com/duckduckgo/app/global/view/ClearPersonalDataActionTest.kt, app/src/main/java/com/duckduckgo/app/di/PrivacyModule.kt, app/src/main/java/com/duckduckgo/app/fire/ClearDataPixel.kt, app/src/main/java/com/duckduckgo/app/global/view/ClearPersonalDataAction.kt, app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt, app/src/test/java/com/duckduckgo/app/fire/ClearDataPixelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1202955482651646/f 
PR allows us to store the first data cleared event
https://app.asana.com/0/0/1203142405566885/f
=> Store unique daily data cleared event

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/OneLineListItem.kt
Task/Issue URL:https://app.asana.com/0/488551667048375/1203157076904288/f
Fix leading icon setter in OneLineListItem
=> Fix set leading icon in OneLineListItem

app/src/androidTest/java/com/duckduckgo/app/referencetests/FirstPartyCookiesReferenceTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203162345927866/f 
This PR fixes a flaky test for cookies ref tests
=> Fix flaky cookies test

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203152743665997/f
https://github.com/duckduckgo/Android/pull/2392 had a db `delete` statement in the wrong place that was overlooked and resulted in only writing 1 element in the DB
=> Fix DB delete statement

app/src/androidTest/resources/reference_tests/domain_matching_tests.json, app/src/main/java/com/duckduckgo/app/trackerdetection/TdsClient.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203150323419031/f 
This PR removes the port from the URL before calling evaluate as per the reference tests
=> Remove port from URL before calling evaluate

.github/workflows/build-debug-apk.yaml, .github/workflows/ci.yml, .github/workflows/update-ref-tests.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203158712142231/f 
This PR adds a new workflow to automatically update reference tests once a day. In case of a new version published it will create a new PR with those changes triggering all the necessary tests.
=> Automate update ref tests

package-lock.json, package.json, privacy-config/privacy-config-impl/src/test/resources/reference_tests/gpc/tests.json
=> Update reference tests to latest version

app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203198577387959/f 
This PRs fixes a 1st party cookies flaky test
=> Make diff between +-5 seconds

.github/workflows/update-ref-tests.yml, package-lock.json, package.json, privacy-config/privacy-config-impl/src/test/resources/reference_tests/gpc/tests.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1203205916393919/f 
This PR removes the trailing .0.0 version from ref-tests which is wrong.
=> Remove trailing .0.0 from ref tests version

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldStatusReporting.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/stats/VpnServiceStateLogger.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/alwayson/AlwaysOnAlertDialogFragment.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/alwayson/AlwaysOnLockDownDetector.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldAlertNotificationBuilder.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnStore.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt, app-tracking-protection/vpn-impl/src/main/res/layout/content_vpn_always_on_alert.xml, app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt, app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/VpnServiceStateStatsDao.kt, app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/model/VpnDatabaseModels.kt
https://app.asana.com/0/0/1203149173362393
Removal of unused pixels.
Ensure always on pixels are sent from `VpnServiceStateLogger`
NA
=> Improve always on promotion [3/N] - pixel cleanup

app/src/main/java/com/duckduckgo/app/browser/history/NavigationHistorySheet.kt, app/src/main/java/com/duckduckgo/app/email/EmailAutofillTooltipFragment.kt, app/src/main/java/com/duckduckgo/app/global/view/FireDialog.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/ActionBottomSheetDialog.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/PromoBottomSheetDialog.kt, lint-rules/src/main/java/com/duckduckgo/lint/ui/DuckDuckGoDesignSystemRegistry.kt, lint-rules/src/main/java/com/duckduckgo/lint/ui/NoAlertDialogDetector.kt, lint-rules/src/main/java/com/duckduckgo/lint/ui/NoBottomSheetDialogDetector.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203198140265612/f
Create Lint rule that prevents classes to extend BottomSheetDialog type
CI checks should pass ✅
=> ADS: Lint rule for BottomSheetDialog components

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/di/VpnModule.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt, app/src/test/java/com/duckduckgo/mobile/android/vpn/integration/FakeVpnAddressLookupDao.kt, app/src/test/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStackTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203195823975924/f
This PR:
* checks EMFile error coming from the networking layer and mitigates it
* also updates the networking layer submodule so that the change is atomic. See https://github.com/duckduckgo/netguard/pull/4
* Incidentally reduces the logging priority of some logs from warning to debug
Hard to reproduce in any reasonable amount of time. Added unit tests to NgVpnNetworkStack, tho in subsequent tasks we should break that class and separate responsibilities
=> Mitigate EMFILE error

app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/VpnTrackerDao.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203268720887505/f
Coalesce the `SUM` db queries to avoid null return values
_Fresh install_
=> Coalesce sum queries

app-tracking-protection/vpn-impl/src/main/res/values-cs/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-ro/strings-vpn.xml, autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values/donottranslate.xml, autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/0/1203251583505090/f
Adding strings in correct place to trigger translations
=> Trigger translations for autofill: updating username

lint-rules/src/main/java/com/duckduckgo/lint/MissingSmartlingRequiredDirectivesDetector.kt, lint-rules/src/main/java/com/duckduckgo/lint/registry/DuckDuckGoIssueRegistry.kt, lint-rules/src/test/java/com/duckduckgo/lint/MissingSmartlingRequiredDirectivesDetectorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203189982895630/f
- Lint check to ensure that all Smartling required directives are added in all String files.
Lint should pass.
=> Add lint detector for missing smartling directives in String files

app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabase.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203298219744166/f
See full context in [asana task](https://app.asana.com/0/488551667048375/1203298219744166/f)
_Test production app update_
_Test migration_
_Test fresh install_
=> Partial migration to avoid SQL exceptions

app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/store/VpnDatabase.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203321400465512
Replace the old vpn_tracker db with the new one, no migration—see [this](https://app.asana.com/0/488551667048375/1203321400465512) and [this](https://app.asana.com/0/488551667048375/1203298219744200/f) for full context
_Test production app update_
_Test 5.141.x_
_Test fresh install_
=> New vpn_tracker db table

build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1203189982895626/f
Fails the Gradle build a strings.xml file is added outside of :app
=> Add check that new strings file is not named strings.xml

app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-et/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-lv/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203325981968858/f
Fixed incorrect placeholder.
Test the crash:
Test the fix:
=> Fixed placeholder.

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt, app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1203285431672054/f
Remove "Beta instructions" from AppTP activity screen
_Test_
=> Remove beta instructions

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSetting.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/settings/OpenBetaSettingPlugin.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/waitlist/store/AtpWaitlistStateRepository.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpFeatureConfigImplTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSettingTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/waitlist/store/WaitlistStateRepositoryTest.kt, app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsActivity.kt, app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/waitlist/InternalAppTrackingProtectionWaitlistDataStore.kt, app-tracking-protection/vpn-internal/src/main/res/layout/activity_vpn_internal_settings.xml, app/src/main/java/com/duckduckgo/app/di/AppTrackingProtectionModule.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt, app/src/main/java/com/duckduckgo/app/waitlist/trackerprotection/AppTPWaitlistCodeFetcher.kt, app/src/main/java/com/duckduckgo/app/waitlist/trackerprotection/AppTPWaitlistWorkRequestBuilder.kt, app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt, app/src/test/java/com/duckduckgo/app/waitlist/trackerprotection/AppTrackingProtectionWaitlistCodeFetcherTest.kt
Task/Issue URL: https://app.asana.com/0/0/1203330041259203/f
Remote waitlist, see [task](https://app.asana.com/0/0/1203330041259203/f) for more context
Perform tests from [asana task](https://app.asana.com/0/0/1203330041259203/f)
=> Remote waitlist

app-tracking-protection/vpn-impl/src/main/res/values-bg/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-cs/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-da/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-de/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-el/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-es/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-et/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-fi/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-fr/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-hr/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-hu/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-it/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-lt/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-lv/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-nb/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-nl/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-pl/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-pt/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-ro/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-ru/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-sk/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-sl/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-sv/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values-tr/strings-vpn.xml, app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml
Task/Issue URL: https://app.asana.com/0/0/1203305488412078/f
Trigger translations, see [this task](https://app.asana.com/0/0/1203305488412078/f) for more info.
=> Trigger AppTP open beta translations

app-tracking-protection/vpn-impl/src/main/res/layout/dialog_tracking_protection_confirm_disable.xml, app-tracking-protection/vpn-impl/src/main/res/layout/dialog_tracking_protection_remove_feature_confirm_disable.xml, app-tracking-protection/vpn-impl/src/main/res/layout/fragment_device_shield_cta.xml, app/src/main/res/layout/activity_app_tp_waitlist_redeem_code.xml, common-ui/src/main/res/layout/dialog_single_choice_alert.xml, common-ui/src/main/res/layout/dialog_stacked_alert.xml, common-ui/src/main/res/layout/dialog_text_alert.xml, common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/0/1157893581871903/1203335319785554
Task/Issue URL: https://app.asana.com/0/1157893581871903/1203337053171233
Task/Issue URL: https://app.asana.com/0/1157893581871903/1203190182019249
Final UI adjustments needed for Open Beta
_Dialogs_
_Redeem Waitlist code screen_
_Padding in New Tab_
=> AppTP: UI glitches

ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt, anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/di/AnrModule.kt, autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/di/AutoconsentModule.kt, cookies/cookies-impl/src/main/java/com/duckduckgo/cookies/impl/di/CookiesModule.kt, downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/di/DownloadsModule.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/di/RemoteMessagingModule.kt, secure-storage/secure-storage-impl/src/main/java/com/duckduckgo/securestorage/impl/SecureStorageDatabaseFactory.kt, site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/di/SitePermissionsModule.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1203276170799080/f
Remove usages of enableMultiInstanceInvalidation
Smoke test app
=> Remove enableMultiInstanceInvalidation for databases where it is not necessary

voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/PermissionRationale.kt, voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/PermissionRequest.kt, voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/MicrophonePermissionRequestTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203335123473946/f
Wrap call to ActivityCompat.shouldShowRequestPermissionRationale in another class so it can be mocked.
Smoke test voice
=> Wrap ActivityCompat.shouldShowRequestPermissionRationale

common-ui/src/main/res/layout/bottom_sheet_action.xml, common-ui/src/main/res/layout/bottom_sheet_promo.xml, common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/0/1201807753394693/1203055904606468
Update ADS Bottom Sheet components to latest specs
| PromoBottomSheetDialog  | PromoBottomSheetDialog |
| ActionBottomSheetDialog  | ActionBottomSheetDialog |
=> ADS: Bottom Sheet Specs

common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/ComponentViewHolder.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/OneLineListItem.kt, common-ui/src/main/res/layout/component_one_line_item.xml, common-ui/src/main/res/layout/view_one_line_list_item.xml, common-ui/src/main/res/layout/view_two_line_item.xml, common-ui/src/main/res/values/design-system-dimensions.xml
Task/Issue URL: https://app.asana.com/0/0/1203311442337887/f
Update List Items with latests specs
_OneLineListItem_
- Tap on List Items tab
_TwoLineListItem_
- Tap on List Items tab
| OneLineListItem  | OneLineListItem |
| TwoLineListItem  | TwoLineListItem |
=> ADS: List Items specs

common-ui/src/main/res/values/design-system-colors.xml, common-ui/src/main/res/values/design-system-theming.xml
Task/Issue URL: https://app.asana.com/0/0/1203335094220935/f
Update `colorControlHighlight` to show correct ripple background color in light and dark mode
=> ADS Ripple background color

app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/PermissionsPerWebsiteViewModel.kt, app/src/test/java/com/duckduckgo/app/sitepermissions/PermissionsPerWebsiteViewModelTest.kt
Revert changes in site permissions as we'll be making more changes for better user experience
PR reverted: https://github.com/duckduckgo/Android/pull/2528
Asana task reverted: https://app.asana.com/0/488551667048375/1203336099175506/f
=> Remove Site Permissions change when toggle off permission

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModel.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/model/TrackerFeedItem.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/AppsProtectionStateView.kt, app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_activity_apps.xml, app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_activity_apps_protection.xml, app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_activity_feed.xml, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModelTest.kt, common/src/main/java/com/duckduckgo/app/global/formatters/time/TimeDiffFormatter.kt
Task/Issue URL: https://app.asana.com/0/1200905986587319/1203352268410406/f
Updated device shield screen (activity, fragment, adapter, layouts). Fixed sticky headers.
Check the Asana task (section "Testing - check the attached videos as well" at the bottom of the description) https://app.asana.com/0/1200905986587319/1203352268410406/f and comment https://app.asana.com/0/0/1203352268410406/1203374322675674/f
=> AppTP: Improvements for DeviceShieldActivityFeedFragment

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/debug/DeviceShieldNotificationsDebugReceiver.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPHealthMonitor.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/HealthMetricCounter.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldNotificationScheduler.kt, di/src/main/java/com/duckduckgo/vpn/di/VpnCoroutineScope.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203372565103790/f
Move VPNCoroutineScope to :di module
=> Move VPNCoroutineScope to :di module

common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/typography/TypographyFragment.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/TypedArrayUtils.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/text/DaxTextView.kt, common-ui/src/main/res/layout/bottom_sheet_action.xml, common-ui/src/main/res/layout/dialog_single_choice_alert.xml, common-ui/src/main/res/layout/dialog_stacked_alert.xml, common-ui/src/main/res/layout/dialog_text_alert.xml, common-ui/src/main/res/layout/fragment_components_typography.xml, common-ui/src/main/res/layout/view_two_line_item.xml, common-ui/src/main/res/values/attrs-typography.xml, common-ui/src/main/res/values/design-system-typograhy.xml, lint-rules/src/main/java/com/duckduckgo/lint/registry/DuckDuckGoIssueRegistry.kt, lint-rules/src/main/java/com/duckduckgo/lint/ui/DaxTextViewStylingDetector.kt
Task/Issue URL: https://app.asana.com/0/1202857801505092/1203418290512953
- Support the textColor attribute from Android
- When textType and textColor are both set, textType will take priority.
=> ADS DaxTextView: Support for android:textColor

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/DaxAlertDialog.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/RadioListAlertDialogBuilder.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/StackedAlertDialogBuilder.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/dialog/TextAlertDialogBuilder.kt
Task/Issue URL: https://app.asana.com/0/1202857801505092/1203426646213788/f
Created DaxAlertDialog interface which includes all public methods:
- build()
- show()
- dismiss()
=> ADS: DaxAlertDialog interface with public methods

app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/PermissionSettingAdapter.kt, app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/PermissionsPerWebsiteViewModel.kt, app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/PermissionsSettingsSelectorFragment.kt, app/src/main/res/values/donottranslate.xml, app/src/test/java/com/duckduckgo/app/sitepermissions/PermissionsPerWebsiteViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203336099175506/f
Remove logic to show site permissions settings for website denied if global toggle is off. We'll show actual values unless "Ask" and global permission disabled:
_Settings logic:_
- If child permission setting is Deny or Allow and global toggle is off, website permission will show actual value
- If child permission setting is Ask and global toggle is off, website permission will show as "Ask" disabled for all sites
_Alert dialog logic:_
- If child permission setting is Deny or Ask and global toggle is off, websites won't request site permissions
- If child permission was changed to Allow and global toggle is off, websites will grant permissions for that specific website
_Request permissions on website_
- Install …
=> Disable global site permission toggle change

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnRoutes.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/service/VpnRoutesTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203425545589572/f
This PR:
* Removes loopback addresses from VPN routes 127.0.0.0 -> 127.255.255.255
* Removes Class E addresses from VPN routes 240.0.0.0 -> 255.255.255.255—as they're not assigned to hosts and only for research purposes
* Checks the route address before calling `VpnService:addroute()` method
See the [asana task](https://app.asana.com/0/488551667048375/1203425545589572/f) for more info
Just code review and smoke tests for AppTP
=> Check before adding VPN route

common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/Component.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/ComponentViewHolder.kt, common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/buttons/ComponentInteractiveElementsFragment.kt, common-ui/src/main/res/layout/component_slider.xml, common-ui/src/main/res/values/design-system-colors.xml, common-ui/src/main/res/values/design-system-dimensions.xml, common-ui/src/main/res/values/design-system-theming.xml, common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/0/1202857801505092/1203433470862092/f
Update track and thumb colors for Slider
- Tap on Interactive tab
| Light  | Dark |
=> ADS: Slider specs

app/src/main/java/com/duckduckgo/app/globalprivacycontrol/ui/GlobalPrivacyControlActivity.kt, app/src/main/res/layout/activity_global_privacy_control.xml
Task/Issue URL: https://app.asana.com/0/0/1203418963160798/f
Global Privacy Control screen 100% migrated to new components
- Go to Settings > Global Privacy Control (GPC)
=> ADS: GPC screen migration

autoconsent/autoconsent-impl/build.gradle, autoconsent/autoconsent-impl/src/main/res/layout/activity_autoconsent_settings.xml, common-ui/src/main/res/values/design-system-typograhy.xml
Task/Issue URL: https://app.asana.com/0/0/1203418963160799/f
Manage Cookie Pop-ups screen 100% migrated to new components
- Go to Settings > Manage Cookie Pop-ups
=> ADS: Manage Cookie Pop-ups migration

versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1203433470862130/f
⬆️  Update following libraries:
- version.google.android.material=1.6.1 -> [1.7.0](https://github.com/material-components/material-components-android/releases/tag/1.7.0)
1. All unit tests should pass.
2. Run through the app and check that there isn't any unexpected behavior.
Smoke test:
- Onboarding CTAs
- Add bookmarks and favorites
- Disable/enable privacy protection
- Share feedback
- Fireproof a site and clear all data
- Opening multiple tabs (and closing tabs + undo)
- Enable App Tracking Protection
=> Update material library version to 1.7.0

app/src/main/res/layout/activity_accessibility_settings.xml, common-ui/src/main/res/drawable/background_text_view_container.xml
Task/Issue URL: https://app.asana.com/0/0/1203418963160797/f
Accessibility screen 100% migrated to new components
- Go to Settings > Accessibility
=> ADS: Accessibility screen migration

app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsActivity.kt, app-tracking-protection/vpn-internal/src/main/res/layout/activity_vpn_internal_settings.xml, app/src/internal/res/layout/activity_audit_settings.xml, app/src/internal/res/layout/activity_dev_settings.xml, app/src/internal/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/0/1203418963160800/f
Migrate internal features settings section to new components
=> ADS: Internal Features Settings migration

app/src/androidTest/java/com/duckduckgo/app/integration/AtbIntegrationTest.kt, app/src/androidTest/java/com/duckduckgo/app/statistics/api/StatisticsRequesterJsonTest.kt, app/src/main/java/com/duckduckgo/app/di/StatisticsModule.kt, app/src/main/java/com/duckduckgo/app/email/AppEmailManager.kt, app/src/main/java/com/duckduckgo/app/email/di/EmailModule.kt, app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt, app/src/test/java/com/duckduckgo/app/email/AppEmailManagerTest.kt, app/src/test/java/com/duckduckgo/app/statistics/api/StatisticsRequesterTest.kt, common/src/main/java/com/duckduckgo/app/global/AppUrl.kt, statistics/build.gradle, statistics/src/main/java/com/duckduckgo/app/statistics/api/StatisticsRequester.kt, statistics/src/main/java/com/duckduckgo/app/statistics/api/StatisticsService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203393655574809/f
Add a few metrics around email signin/signout
_Feature 1_
=> Add pixel metrics

app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203479857979842/f
Enable [se,sc] experiment variants
_Feature 1_
=> enable se/sc variants

app/src/main/res/layout/include_omnibar_toolbar.xml
Task/Issue URL: https://app.asana.com/0/1202552961248957/1203336877132940/f 
Disabled Lottie view being recreated when fragment is destroyed. This will fix the issue we are having when changing theme makes the cookie lottie view visible.
_Feature 1_
=> Disable Cookie animation being restored

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/configuration/AutofillRuntimeConfigProvider.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/configuration/RuntimeConfigurationWriter.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/jsbridge/response/AutofillDataResponses.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/configuration/RealAutofillRuntimeConfigProviderTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/configuration/RealRuntimeConfigurationWriterTest.kt, node_modules/@duckduckgo/autofill/dist/TopAutofill.html, node_modules/@duckduckgo/autofill/dist/autofill-debug.js, node_modules/@duckduckgo/autofill/dist/autofill.css, node_modules/@duckduckgo/autofill/dist/autofill.js, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1203479831772471/1203479831772471
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.0.0
Updates Autofill to version [6.0.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.0.0).
**⚠️ This is a breaking change for Android and Windows. We will get in touch with details. ⚠️**
* Add support for Bitwarden integration
* Make Asana release script more resilient by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/234
* Reuse webkit messaging by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/226
* Send js pixels by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/237
* Further bitwarden js changes by @GioSensation in …
=> Update autofill to 6.0.0

app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203515134209733/f 
This PR fixes the url bar when showing the serp dialog
_Feature_
=> URL bar when showing SERP dialog should be dimmed

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/Theming.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203522199735784/f 
Fix lint error
CI passes
=> Fix lint error

common-ui/src/main/res/color/text_input_box_color_selector.xml, common-ui/src/main/res/layout/view_dax_text_input.xml, common-ui/src/main/res/values/design-system-colors.xml, common-ui/src/main/res/values/design-system-theming.xml, common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/0/1202857801505092/1203501746286791
Description
Update TextInput to latest specs
=> ADS: DaxTextInput specs

app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/FakeVpnFeaturesRegistry.kt, app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/network/FakeVpnNetworkStack.kt, app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistry.kt, app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/integration/VpnNetworkStackProvider.kt, app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/network/VpnNetworkStack.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistryImpl.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/VpnNetworkLayerStateCollector.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/VpnNetworkStackProvider.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistryImplTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStackTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/integration/VpnNetworkStackProviderTest.kt, versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1203491696462420/f
See details in [asana task](https://app.asana.com/0/488551667048375/1203491696462420/f)
_Test Fresh Install_
_Test App Update With AppTp Enabled_
_Test App Update With AppTp Disabled_
=> Refactor the AppTP ON/OFF mechanism

app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/network/FakeVpnNetworkStack.kt, app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/network/VpnNetworkStack.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStackTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203529428649463/f
Move the exclusion list to the VPN network config instead of being "hardcoded" in the VPN service
Just code review
=> Move exclusion list to VPN config

app/build.gradle, app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203228473135603/f
Forgot to register the `logcat` logger for the VPN process. done
(optional)
=> Register logcat logger

app/src/main/java/com/duckduckgo/app/global/DuckDuckGoApplication.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203553001428517/f
see [asana task](https://app.asana.com/0/488551667048375/1203553001428517/f)
See [asana task](https://app.asana.com/0/488551667048375/1203553001428517/f)
=> Remove logs

site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
Task/Issue URL: https://app.asana.com/0/0/1203553010470144/f
Migrate camera and microphone permission request dialogs to new components
- Go to a website which requests mic, camera or both permissions
- Go to Apps > DDG > Permissions and disable microphone permission
- Go back to a website which requests microphone permission and allow it
=> ADS: Mic and Camera permissions dialogs migration

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203621326448635/f
Remove unused AppTP pixels
N/A, CI shall pass.
=> Remove unused AppTP pixels

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203621692416589/f
Remove check for ENABLED when starting VPN
N/A
=> Remove check for enabled state

app/src/test/java/com/duckduckgo/app/downloads/DownloadsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203632525807129/f
Fix the test so that it doesn't depend on what date it's executed.
N/A, CI shall pass
=> Fix whenDownloadsCalledAndMultipleDownloadsThenViewStateEmittedWith test to widstand time

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/cohort/CohortCalculator.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/cohort/RealCohortCalculatorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203665160734213/f
Fix the tests for cohort calculation as they were affected by new year change. That was making nightlies to fail
Took the opportunity to split that failing test in several of them.
CI shall pass
=> Fix CohortCalculator tests

downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DataUriParser.kt, downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/DataUriParserTest.kt
Task/Issue URL: https://app.asana.com/0/1200905986587319/1203594326324933/f
Updated the data URI parsing.
=> Improved parsing for data URL scheme.

autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values/donottranslate.xml, autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/0/1203600593126224/f
Translations for the new strings for searching credential management screen
=> Trigger translations for searching credentials

autofill/autofill-impl/src/main/res/drawable/ic_baseline_search_24.xml
Task/Issue URL: https://app.asana.com/0/0/1203634853584226/f
Simple PR removing defined tint on the search icon
=> Remove tint on search drawable

app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/network/FakeVpnNetworkStack.kt, app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/network/VpnNetworkStack.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203703971307576/f
- Passing StopReason to VpnNetworkStack.onStopVpn()
- Moving down the setting of DISABLED state after  calling all plugins and unbinding the ServiceConnection
Smoke test AppTP
=> Pass StopReason to VpnNetworkStack.onStopVpn()

common-ui/src/main/res/values/design-system-colors.xml, common-ui/src/main/res/values/design-system-theming.xml
Task/Issue URL: https://app.asana.com/0/1202857801505092/1203560741717081
This PR updates the colors of destructive primary and ghost buttons
=> ADS: Destructive Colors

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/shape/DaxBubbleCardView.kt
Task/Issue URL: https://app.asana.com/0/1157893581871903/1203641318924982
This PR fixes. the issue in Android 8 where the dax bubble wasn't appearing
_Fresh install_
=> ADS: Fix Dax Bubble

fastlane/Fastfile
Task/Issue URL: https://app.asana.com/0/0/1203713455988743/f
Updates the fastlane script which integrates with the Asana release bridge tool, needed since tweaking the way the tool is distributed and installed.
- ⚠️ Don't progress past the prompt for a version number; if it makes here, all is working well. Don't continue unless cutting a real release!
=> Update Fastlane/aarb integration for new aarb distribution method

app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchActivity.kt, app/src/main/res/layout/activity_system_search.xml, app/src/main/res/layout/include_system_search_onboarding.xml, common-ui/src/main/res/drawable/cookies_dummy_background.xml
Task/Issue URL: https://app.asana.com/0/0/1203455585574665/f
This PR fixes the search interstitial screen 
=> ADS: System Search

app/src/main/res/layout/activity_system_search.xml, common-ui/src/main/res/values/design-system-dimensions.xml
Task/Issue URL: https://app.asana.com/0/1174433894299346/1203411129606111
Final changes before Ship Review
=> ADS: Final bits and pieces

.maestro/release_tests/5_-_app_tp_onboarding.yaml
Task/Issue URL: https://app.asana.com/0/414730916066338/1203710267421767/f
See [asana task](https://app.asana.com/0/414730916066338/1203710267421767/f) for full decription
https://github.com/duckduckgo/Android/actions/runs/3910354353 should pass
=> Update appTP release tests

.github/workflows/update-ref-tests.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203766026095655/f 
This PR automatically create a task in Asana for the automated reference tests GHA workflow when succeeds.
See https://app.asana.com/0/414730916066338/1203766465043062/f for the Asana task created which should point to the following PR https://github.com/duckduckgo/Android/pull/2734
=> Create task for ref tests PR

.github/workflows/end-to-end.yml, .maestro/ad_click_detection_flows/10_-_m.js_bing-provided;_ad_domain_provided_but_incorrect_(dsl_not_needed).yaml, .maestro/ad_click_detection_flows/11_-_y.js_bing-provided;_ad_domain_provided_but_it's_not_a_domain_(i.e.,_abcedf)_(u3_not_needed).yaml, .maestro/ad_click_detection_flows/12_-_m.js_bing-provided;_ad_domain_provided_but_it's_not_a_domain_(i.e.,_abcedf)__(dsl_not_needed).yaml, .maestro/ad_click_detection_flows/13_-_y.js_bing-provided;_ad_domain_provided_but_it's_a_subdomain_of_advertiser_(i.e.,_foo.www.search-company-site)_(u3_not_needed).yaml, .maestro/ad_click_detection_flows/14_-_m.js_bing-provided;_ad_domain_provided_but_it's_a_subdomain_of_advertiser_(i.e.,_foo.www.search-company-site)__(dsl_not_needed).yaml, .maestro/ad_click_detection_flows/4_-_m.js_heuristic;_no_ad_domain_param,_but_missing_dsl_param.yaml, .maestro/ad_click_detection_flows/5_-_y.js_heuristic;_ad_domain_provided,_but_empty_(u3_not_needed).yaml, .maestro/ad_click_detection_flows/6_-_m.js_heuristic;_ad_domain_provided,_but_empty_(dsl_not_needed).yaml, .maestro/ad_click_detection_flows/7_-_y.js_bing-provided;_ad_domain_provided_(u3_not_needed).yaml, .maestro/ad_click_detection_flows/8_-_m.js_bing-provided;_ad_domain_provided_(dsl_not_needed).yaml, .maestro/ad_click_detection_flows/9_-_y.js_bing-provided;_ad_domain_provided_but_incorrect_(u3_not_needed).yaml
Task/Issue URL: https://app.asana.com/0/0/1203779725035936/f
Use scroll for scrolling pages in meastro ad click tests
Should pass all ad click detection flows https://github.com/duckduckgo/Android/actions/runs/3960656806/jobs/6785109216
=> Fix failing end to end tests due to scroll issues

app/build.gradle, install_tools.sh
Task/Issue URL: https://app.asana.com/0/1157893581871903/1203769237130039
This PR updates NDK to 25, since the version we were using is no longer available
Usual smoke tests
=> Update install script NDK to 21

versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1203795289908380/f
Bump to 1.2.0 of net layer
Smoke test for AppTP
=> Update to net layer 1.2.0

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnStore.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/SharedPreferencesVpnStoreTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1203779620618429/f
See [asana](https://app.asana.com/0/1202552961248957/1203779620618429/f) for context
_AppTP onboarding_
=> Fix AppTP screen banner copy trigger

.maestro/release_tests/5_-_app_tp_onboarding.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203814083810715/f
Add additional scroll to find AppTP in settings
Should pass: https://github.com/duckduckgo/Android/actions/runs/3994381005
=> Add additional scroll in release apptp onboarding

.github/workflows/ci.yml, .github/workflows/end-to-end.yml, .github/workflows/nightly.yml, .github/workflows/privacy-dashboard-end-to-end.yml, .github/workflows/privacy.yml, .github/workflows/update-ref-tests.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203827189225739/f 
This PR updates the workflow concurrencies
N/A
=> Update workflows concurrency

app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoRequestRewriter.kt, app/src/main/java/com/duckduckgo/app/browser/omnibar/QueryUrlConverter.kt, app/src/test/java/com/duckduckgo/app/browser/DuckDuckGoRequestRewriterTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203533204483529/f 
This PR ignores the email path when re-writing a URL.
Check Asana task for steps
=> Ignore email path when rewriting requests

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203844800330872/f
Fixes a regression that was causing a crash when prompting to fireproof a site.
=> Fix crash when prompting to fireproof site

node_modules/@duckduckgo/autofill/dist/autofill-debug.js, node_modules/@duckduckgo/autofill/dist/autofill.js, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1203845335740043/1203845335740043
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.2.0
Updates Autofill to version [6.2.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.2.0).
* Send autofill pixels on macOS by @sixers in https://github.com/duckduckgo/duckduckgo-autofill/pull/249
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/6.1.2...6.2.0
=> Update autofill to 6.2.0

app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203849465655164/f 
This PR adds a message to an assertion that has failed a few times to try and add more clarity as why the test is flaky.
N/A
=> Add message to assertion to try and figure out why a test is flaky

.maestro/ads_preview_flows/1-_design-system-components.yaml
Task/Issue URL:  https://app.asana.com/0/home/1157893581871899/1203863863772464
This PR fixes the Maestro flow, so it check the proper text.
Maestro test
---
- https://app.asana.com/0/0/1203863863772464
=> ADS: Maestro Flow Fix

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncRepository.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncService.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncServiceRemote.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupActivity.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupViewModel.kt, sync/sync-impl/src/main/res/layout/activity_sync_setup.xml, sync/sync-impl/src/test/java/com/duckduckgo/sync/AppSyncDeviceIdsTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncRepositoryTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncServiceRemoteTest.kt, sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203840491979607/f 
PR adds to the internal setting screen options to login via recovery code!
_Feature 1_
=> Login user flow

sync/sync-impl/build.gradle, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncDeviceId.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncRepository.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncService.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncServiceRemote.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/di/SyncModule.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupActivity.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupViewModel.kt, sync/sync-impl/src/main/res/layout/activity_sync_setup.xml, sync/sync-impl/src/test/java/com/duckduckgo/sync/AppSyncDeviceIdsTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncRepositoryTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncServiceRemoteTest.kt, sync/sync-lib/src/main/java/com/duckduckgo/sync/crypto/SyncNativeLib.kt, sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203804027992477/f 
PR adds to the internal setting screen options to allow user to create a sync account.
Some addons for testing purposes:
- show errors as toast (testing purposes)
- Print data related to the account created
- Store recovery code (testing purposes)
- Reset clears all data store (testing purposes)
_Feature 1_
=> Create account user flow

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/service/connectivity/VpnConnectivityLossListenerPlugin.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/connectivity/VpnConnectivityLossListenerPluginPoint.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/NetworkConnectivityHealthHandler.kt
Task/Issue URL: https://app.asana.com/0/0/1203874955117844/f
Add ability to set custom handling for vpn connectivity loss depending on the VpnFeature registered
_Smoke test App_
=> Add vpn connecivity loss listener

autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/feature/AutofillFeatureToggleStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203892797544793/f 
This PR changes the store interface to use the proper interface for subfeatures rather than the real
=> Interface should use AutofillSubfeature rather than AutofillSubfeatureName

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesSubComponentCodeGenerator.kt, di/src/main/java/com/duckduckgo/di/scopes/ViewScope.kt, di/src/main/java/dagger/android/AndroidInjector.kt, di/src/main/java/dagger/android/support/AndroidSupportInjection.kt
Task/Issue URL: https://app.asana.com/0/0/1203918439243863/f
Added ViewScope.
`ViewScope` is not yet used.
Tested with a clean assemble, install and smoke tested a few screens.
=> Implementation task: Add DI ViewScope

autofill/autofill-impl/src/main/res/layout/item_row_autofill_credentials_management_screen.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203911394442538/f
Ensures the title text in the credential management list view doesn't get clipped when text size is larger
QA-optional, but if you want to test:
=> Ensure credential list items don't have their text clipped

app/version/release-notes-hiring
Task/Issue URL: https://app.asana.com/0/0/1203947793226419/f
QA-optional change to release notes
=> Update hiring release notes

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/res/layout/cookie_cosmetic_scene_1.xml, app/src/main/res/layout/cookie_cosmetic_scene_2.xml, app/src/main/res/layout/cookie_scene_1.xml, app/src/main/res/layout/cookie_scene_2.xml, app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/RealAutoconsent.kt, autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPlugin.kt, autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/RealAutoconsentTest.kt, autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPluginTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203956750670569/f
This PR adds a cookie prompt management experiment.
_Change all variants to 0 except for the `mr` variant_
_Non-European Country_
_European Country_
=> Add cookie prompt management experiment

request-filterer/request-filterer-impl/src/main/java/com/duckduckgo/request/filterer/impl/RequestFiltererImpl.kt, request-filterer/request-filterer-impl/src/test/java/com/duckduckgo/request/filterer/impl/RequestFiltererImplTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203960565869467/f
This PR handles an `IllegalArgumentException` that is thrown when `toHttpUrl()` is called on malformed URLs.
=> Handle request filterer IllegalArgumentException

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Reverts duckduckgo/Android#2847
=> Revert "Call stopvpn upon tun iface creation"

node_modules/@duckduckgo/autofill/dist/autofill-debug.js, node_modules/@duckduckgo/autofill/dist/autofill.js, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1203937331479725/1203937331479725
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.3.0
Updates Autofill to version [6.3.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/6.3.0).
* Email protection in-context signup for extensions by @alistairjcbrown in https://github.com/duckduckgo/duckduckgo-autofill/pull/243
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/6.2.0...6.3.0
=> Update autofill to 6.3.0

app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPage.kt, app/src/main/java/com/duckduckgo/app/onboarding/ui/page/OnboardingPageFragment.kt, app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt, app/src/main/res/layout-land/content_onboarding_welcome.xml, app/src/main/res/layout/content_onboarding_welcome.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203978814811922/f
Migrates WelcomePage to use ViewBinding instead of Kotlin Synthetics.
=> Migrate WelcomePage to use ViewBinding

.github/workflows/privacy.yml, .github/workflows/update-content-scope.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203979567756828/f 
This PR adds a workflow to automatically update content scope scripts.
=> Add workflow to automatically update content scope scripts

.github/workflows/privacy.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203986899650851/f 
Let the privacy workflow be executed manually
N/A
=> Let privacy workflow execute manually

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/app/tracking/RealAppTrackerDetector.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/processor/requestingapp/AppNameResolver.kt, app/src/test/java/com/duckduckgo/mobile/android/app/tracking/AppTrackerDetectorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204000827263085/f
See [asana task](https://app.asana.com/0/488551667048375/1204000827263085/f) for context
NA, AppTP smoke tests
=> Return null to signify unknown packageID

autofill/autofill-impl/src/main/res/layout/item_row_autofill_credentials_management_screen_header.xml
Task/Issue URL: https://app.asana.com/0/0/1203994395965552/f
Ensures the list headings' widths aren't clipped. This will be addressed in `SectionHeaderListItem`; patching it here with `match_parent` for now.
QA-optional
=> Ensure autofill login list headings' widths aren't clipped

autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values/donottranslate.xml, autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1203977892435426/f
Translations for new labels on autofill picker dialog
=> Trigger translations for autofill picker labels

app/build.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1204020855860985/f
This configures sync related modules to be built for internal flavor only.
_Build internal_
=> use internalImplementation for sync related modules

app/schemas/com.duckduckgo.app.global.db.AppDatabase/45.json, app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt, app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsActivity.kt, app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsViewModel.kt, app/src/internal/java/com/duckduckgo/app/dev/settings/db/DevSettingsDataStore.kt, app/src/internal/res/layout/activity_dev_settings.xml, app/src/internal/res/values/donottranslate.xml, app/src/main/java/com/duckduckgo/app/bookmarks/di/BookmarksModule.kt, app/src/main/java/com/duckduckgo/app/bookmarks/migration/AppDatabaseBookmarksMigrationCallback.kt, app/src/main/java/com/duckduckgo/app/bookmarks/model/BookmarksFacade.kt, app/src/main/java/com/duckduckgo/app/bookmarks/model/SavedSitesRepository.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModel.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt, app/src/main/java/com/duckduckgo/app/di/DaoModule.kt, app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt, app/src/test/java/com/duckduckgo/app/bookmarks/mapper/migration/BookmarksMigrationTest.kt, app/src/test/java/com/duckduckgo/app/bookmarks/model/SavedSitesRepositoryTest.kt, app/src/test/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModelTest.kt, sync/sync-impl/src/main/res/layout/activity_sync_setup.xml, sync/sync-store/build.gradle, sync/sync-store/src/main/java/com/duckduckgo/sync/store/RoomEntities.kt, sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncEntitiesDao.kt, sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncRelationsDao.kt
Task/Issue URL: https://app.asana.com/0/1174433894299346/1203844082782764
- This PR uses the new DB model to interact with Bookmarks / Favourites. 
- The new business logic is in place
=> Sync (3/N): Business Logic

autofill/autofill-impl/src/main/res/layout/content_autofill_save_new_credentials.xml, autofill/autofill-impl/src/main/res/layout/content_autofill_select_credentials_tooltip.xml, autofill/autofill-impl/src/main/res/layout/content_autofill_update_existing_credentials.xml, autofill/autofill-impl/src/main/res/values/styles.xml
Task/Issue URL: https://app.asana.com/0/0/1204065887049176/f
Fixes the style applied to the URLs in autofill dialogs
QA-optional (or make sure the URLs look good for saving, updating and selecting credentials)
=> Fix styles used on the bottom sheet URLs

autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204105095056229/f
Updates the autofill save dialog subtitle to use newer copy. 
QA-optional
=> Update autofill save dialog subtitle

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
Task/Issue URL: https://app.asana.com/0/0/1204066372530691/f
Ensures `lintKotlin` passes
QA-optional (but `./gradlew lintKotlin` should pass)
=> Fix code formatting issues in ContributesRemoteFeatureCodeGenerator

.github/workflows/privacy.yml
Task/Issue URL: https://app.asana.com/0/1202552961248957/1204116417359303/f
This PR updates the privacy workflow to run for these conditions:
- A branch with the "content scope scripts" label is pushed.
- The nightly runs.
- Manually (On failure, a task is not created in this case).
=> Fix privacy workflow conditions

autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/0/1204100098948920/f
Translations for new copy
=> Trigger translations

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnRoutes.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/service/VpnRoutesTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204121327572584/f
Exclude CGNAT IP range
Smoke AppTP tests
=> Exclude CGNAT address range

app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/remote_config/VpnConfigTogglesDao.kt, privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/RealPrivacyConfigPersisterTest.kt, privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/privacyconfig/PrivacyConfigDisabledReferenceTest.kt, privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/privacyconfig/PrivacyConfigEnabledReferenceTest.kt, privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/privacyconfig/PrivacyConfigGlobalExceptionsReferenceTest.kt, privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/privacyconfig/PrivacyConfigLocalExceptionsReferenceTest.kt, privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/privacyconfig/PrivacyConfigMissingReferenceTest.kt, versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1204121347514343/f
Updates `Room` version from 2.4.3 to 2.5.0, including one minor code change required for compatibility.
Since this affects the DBs, a general smoke test of the app is needed to test this PR.
=> Update library version: Room [2.4.3 -> 2.5.0]

versions.properties
Task/Issue URL: https://app.asana.com/0/0/1204130571566362/f
=> Update Robolectric from 4.9.1 to 4.9.2

autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/0/1204135364308886/f
Updates the copy used on the search field for the hint. 
- Before: "Search"
- Now: "Search logins"
Translations to follow in stacked branch.
=> Update copy for searching logins (from 'Search' to 'Search logins')

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt, app/src/test/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt, app/src/test/java/com/duckduckgo/app/bookmarks/BookmarkTestUtils.kt, app/src/test/java/com/duckduckgo/app/bookmarks/model/SavedSitesRepositoryTest.kt, app/src/test/java/com/duckduckgo/app/bookmarks/service/SavedSitesExporterTest.kt, app/src/test/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModelTest.kt, saved-sites/saved-sites-api/build.gradle, saved-sites/saved-sites-api/src/main/java/com/duckduckgo/savedsites/api/SavedSitesRepository.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/SavedSitesRepository.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/service/SavedSitesExporter.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/service/SavedSitesParser.kt, saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/service/SavedSitesParserTest.kt, saved-sites/saved-sites-store/src/main/java/com/duckduckgo/savedsites/store/RoomEntities.kt, saved-sites/saved-sites-store/src/main/java/com/duckduckgo/savedsites/store/SyncEntitiesDao.kt, saved-sites/saved-sites-store/src/main/java/com/duckduckgo/savedsites/store/SyncRelationsDao.kt, sync/sync-lib/src/androidTest/java/com/duckduckgo/sync/crypto/SyncNativeLibTest.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1203865060570370
- This PR fixes the import / export functionality
- Being the top PR from the stack, it also fixes remaining broken tests.
- Testing scenarios added to the Asana task
=> Sync (5/5): Bookmarks Import / Export

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncRepository.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncService.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncServiceRemote.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupActivity.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupViewModel.kt, sync/sync-impl/src/main/res/layout/activity_sync_setup.xml, sync/sync-impl/src/main/res/layout/item_connected_device.xml, sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncRepositoryTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncServiceRemoteTest.kt
Task/Issue URL: https://app.asana.com/0/0/1204039315134729/f
This PR adds functionality to show connected devices and allow do logout on them
_Feature 1_
=> Connected devices to sync account

app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt, app/src/test/java/com/duckduckgo/app/global/model/SiteMonitorTest.kt
Task/Issue URL: https://app.asana.com/0/1157893581871903/1204131903581464
Read Asana task for all relevant info
=> Major Network Red Dot

autofill/autofill-impl/src/main/res/layout/content_autofill_save_new_credentials.xml, autofill/autofill-impl/src/main/res/layout/content_autofill_update_existing_credentials.xml
Task/Issue URL: https://app.asana.com/0/0/1204135366588347/f
Allows the dialogs for saving/updating a credential to vertically scroll if necessary to access all the content.
QA-optional
=> Make autofill save/update credential dialogs scrollable

app/src/main/res/values-bg/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/0/1204136063908932/f
Translations for updated search logins hint
=> Translations for changing search logins hint

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204170937918667/f
Check valid `jniContext` before proceeding with VPN network start
Smoke tests for AppTP
=> Validate jniContext before network start

app/src/main/res/values/donottranslate.xml, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt, autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_locked.xml, autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml, device-auth/device-auth-impl/src/main/res/values/strings-device-auth.xml
Task/Issue URL: https://app.asana.com/0/0/1204186964283917/f
Updates copy based on copy review feedback.
Translations will follow separately.
=> Update strings based on copy review

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204180634737561/f
Catch errors when stopping the VPN network, log them and proceed with
thread cancellation
Smoke tests for AppTP, focus on enable, disable, kill VPN process etc.
=> Try-catch stopping VPN network and proceed with thread cancellation

app-tracking-protection/app-tracking-api/src/main/java/com/duckduckgo/mobile/android/app/tracking/AppTrackingProtection.kt, app-tracking-protection/vpn-impl/build.gradle, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/app/tracking/RealAppTrackingProtection.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt, app/src/main/java/com/duckduckgo/app/browser/remotemessage/CommandActionMapper.kt, app/src/main/java/com/duckduckgo/app/di/DevicePropertiesModule.kt, app/src/main/java/com/duckduckgo/app/global/store/AndroidUserBrowserProperties.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt, app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt, remote-messaging/remote-messaging-api/src/main/java/com/duckduckgo/remote/messaging/api/AttributeMatcherPlugin.kt, remote-messaging/remote-messaging-api/src/main/java/com/duckduckgo/remote/messaging/api/RemoteMessage.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/AppRemoteMessagingRepository.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/RemoteMessagingConfigMatcher.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/di/RemoteMessagingModule.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/mappers/JsonRemoteMessageMapper.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/mappers/JsonRulesMapper.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/matchers/AndroidAppAttributeMatcher.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/matchers/DeviceAttributeMatcher.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/matchers/EvaluationResult.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/matchers/UserAttributeMatcher.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/models/JsonRemoteMessagingConfig.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/models/MatchingAttributes.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/models/RemoteConfig.kt, remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/JsonRulesMapperTest.kt, remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/RemoteMessagingConfigJsonMapperTest.kt, remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/RemoteMessagingConfigMatcherTest.kt, remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/matchers/AndroidAppAttributeMatcherTest.kt, remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/matchers/DeviceAttributeMatcherTest.kt, remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/matchers/UserAttributeMatcherTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204117090973403/f
Note: [this JSON blob](https://jsonblob.com/api/jsonBlob/1083005270376071168) has an example remote config
_Feature 1_
=> Add AppTP onboarding action and matching attr for remote messaging

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/network/ExternalVpnDetector.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/network/RealVpnDetector.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnOnboardingViewModel.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1204192315277492/f
Move VPNDetector to vpn-api (more info on the task above).
QA optional
=> Move VPNDetector to vpn-api

.maestro/release_tests/3_-_favorites.yaml
Task/Issue URL: https://app.asana.com/0/414730916066338/1204212154487237/f
Fixes maestro favourites assertions
---
- https://app.asana.com/0/0/1204212154487237
=> Fix Maestro Favourites Assertions

app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-et/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-lv/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204165389273283/f
Translations for a new string resource added later for the Optimise Onboarding experiment
=> Smartling: Translations for "Skip This Step"

app/src/main/res/layout/item_autocomplete_bookmark_suggestion.xml, app/src/main/res/layout/item_autocomplete_search_suggestion.xml
Task/Issue URL: https://app.asana.com/0/1202552961248957/1163739970038420/f
Added touch feedback on autocomplete items.
| Touch feedback on bookmark suggestion  | Touch feedback on search suggestion |
|![suggestion_bookmark_selected](https://user-images.githubusercontent.com/7963079/226928196-080a9463-ceea-40d9-95fa-3e14bfad26ed.png)|![suggestion_selected](https://user-images.githubusercontent.com/7963079/226928208-8d50dc7c-c96d-4c94-a4cf-9c1b0e098a6f.png)|
=> Android: No tap feedback on autocomplete

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/state/VpnStateMonitor.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/state/RealVpnStateMonitor.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnStore.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/service/state/RealVpnStateMonitorTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/SharedPreferencesVpnStoreTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204236351560637/f
See task description.
_Test always on promotion_
=> Add API for always-on status

app/src/main/java/com/duckduckgo/app/global/view/FaviconImageView.kt, autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/encoding/UrlUnicodeNormalizer.kt, autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/urlmatcher/AutofillUrlMatcher.kt, autofill/autofill-impl/build.gradle, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/di/AutofillModule.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/encoding/UrlUnicodeNormalizerDelegator.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/sorting/CredentialInitialExtractor.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/sorting/CredentialListSorterByTitleAndDomain.kt, autofill/autofill-impl/src/main/res/layout/item_row_search_no_results.xml, autofill/autofill-impl/src/main/res/menu/autofill_list_mode_menu.xml, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/encoding/LegacyUrlUnicodeNormalizerTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/encoding/ModernUrlUnicodeNormalizerTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/encoding/UrlUnicodeNormalizerDelegatorTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/CredentialGrouperTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/CredentialInitialExtractorTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/CredentialListSorterTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/suggestion/SuggestionListBuilderTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/suggestion/SuggestionMatcherTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/selecting/RealAutofillSelectCredentialsGrouperTest.kt, autofill/autofill-store/build.gradle, autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/urlmatcher/AutofillDomainNameUrlMatcher.kt, autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt, autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/urlmatcher/AutofillDomainNameUrlMatcherTest.kt, autofill/autofill-test/src/main/java/com/duckduckgo/autofill/api/TestUrlUnicodeNormalizer.kt
Task/Issue URL: https://app.asana.com/0/0/1204204968457589/f
Addressing design review feedback (round 3)
- Fixing icon inconsistencies
- "No results" text should be _secondary_ type
- URLs containing non-ascii should be sorted correctly
- Favicon placeholder letter should be bold to match designs
=> Autofill design review, round 3 feedback

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementActivity.kt, autofill/autofill-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/1203115518054842/1204258140066139/f
Replaces a hardcoded string literal with a new string from string resources
Translations to follow separately.
=> Update autofill snackbar text when copying username/password

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/Theming.kt, sync/sync-impl/src/main/AndroidManifest.xml, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/QREncoder.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/di/SyncModule.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/ShowQRCodeActivity.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/ShowQRCodeViewModel.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivity.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModel.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncConnectActivity.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncConnectViewModel.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncLoginViewModel.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/ConnectFlowContract.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/ConnectViaQRCodeContract.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/SaveRecoveryCodeFragment.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/SaveRecoveryCodeViewModel.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/SetupAccountActivity.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/setup/SetupAccountViewModel.kt, sync/sync-impl/src/main/res/drawable/ic_qr_24.xml, sync/sync-impl/src/main/res/layout/activity_connect_sync.xml, sync/sync-impl/src/main/res/layout/activity_show_qr_code.xml, sync/sync-impl/src/main/res/layout/fragment_recovery_code.xml, sync/sync-impl/src/main/res/values/dimens.xml, sync/sync-impl/src/main/res/values/donottranslate.xml, sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/ShowQRCodeViewModelTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModelTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncConnectViewModelTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/setup/SaveRecoveryCodeViewModelTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/setup/SetupAccountViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204259168623409/f 
Implements UI for connecting flow.
(Disclaimer: to test the feature, please remove `FakeDeviceSyncState` to make the option appear in Settings)
For the tests you will need 2 devices here.
_Feature 1_
=> Connect flow UI

app/src/androidTest/java/com/duckduckgo/app/referencetests/SurrogatesReferenceTest.kt, app/src/main/java/com/duckduckgo/app/trackerdetection/TdsClient.kt, app/src/main/java/com/duckduckgo/app/trackerdetection/model/TdsTracker.kt, app/src/test/java/com/duckduckgo/app/trackerdetection/TdsClientTest.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1204098767504730/f
See task description.
See task description. Modify `ApiDevTdsInterceptor` and `TrackerListService` to  use test tds json.
=> Add option support for tracker matching

app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-et/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-lv/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/0/1204270630225683/f
Added copy for AppTP retention experiment.
=> Translations for [Experiment] Increase retention through AppTP promotions

node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js, package-lock.json, package.json
=> Update content scope scripts to latest version

windows/windows-impl/src/main/res/layout/activity_windows_waitlist.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204334742139053/f
Apply a quick fix if possible to ensure UI is rendered correctly for any invitation code
_Feature 1_
=> fix invitation code UI

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/OneLineListItem.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204330863073014/f
OneLineListItem, setLeadingIcon(idRes: Int) doesn't apply theme correctly
When using that method, icon may not appear due to not resolving attr color.
Apply same logic as in TowLineLisItem for iconRes
_Feature 1_
=> Fix OneLineListItem iconRes

app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1203865270279971/f
Disable experiment variants until determining whether to remove, edit, or implement based on experiment success
=> Disable Optimise Onboarding Experiment

app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/0/1204321069675643/f
Enable variants for onboarding Customization Experiment
=> Enable Onboarding Cutomization Experiment

.maestro/notifications_permissions_android13_plus/1_-_permissions_allowed.yaml, .maestro/notifications_permissions_android13_plus/2_-_permissions_denied.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204350276401779/f 
This PR fixes the maestro tests for notifications
=> Fix notifications maestro tests

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
Task/Issue URL: https://app.asana.com/0/0/1204362630647971/f
Ensures the `minSupportedVersion` on remote config subfeatures are treated as ints
QA-optional
=> Ensure that minSupportedVersion for subfeatures is parsed as int

app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203854694899572/f
Ignores a test which intermittently fails.
QA-optional
=> Ignore flakey cookie test

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivity.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModel.kt, sync/sync-impl/src/main/res/layout/activity_sync.xml, sync/sync-impl/src/main/res/values/donottranslate.xml, sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModelTest.kt
Task/Issue URL:https://app.asana.com/0/0/1204316129840759/f 
User can: logout local device and delete sync account.
_Feature 1_
_Feature 2_
=> Logout-delete local device

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204371051688553/f
When creating two feature flags in the same module, the codegen
inadvertently shared some variables that should otherwise be local to
each codegen execution.
Mods in this PR makes sure the codegen methods are reentrant.
Bug repro steps described in [here](https://app.asana.com/0/0/1204371051688553/1204392375144199/f) don't repro any more
=> Fix codegen for multiple flags in same module

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementDisabledMode.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204401517511624/f
We saw a crash attempting to launch the system settings for a particular intent:
`android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.FINGERPRINT_ENROLL }`
Fix up the logic to make launching to the relevant system settings screens safer.
**Test on Android R or newer**
**Test on Android P**
**Test on older than Android P**
=> Better handle attempt to launch settings for securing device

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt, app/src/main/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptor.kt, app/src/test/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptorTest.kt
Task/Issue URL: https://app.asana.com/0/0/1204253343689086/f
Added 2 new temporary pixels and temporary ATB info.
See https://app.asana.com/0/0/1204253343689086/1204389170821809/f
=> Add ATB to relevant pixels

app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/0/1204410815275749/f
Updated to not open the keyboard when the `DaxEndEnableAppTpCta` message is displayed (variant zo).
It was already tested during Design Review. See task and comments -> https://app.asana.com/0/0/1204383785890397/f
=> Don't open the keyboard when the Dax message is displayed (variant zo)

app/src/main/java/com/duckduckgo/app/installer/InstallSourceExtractor.kt, app/src/main/java/com/duckduckgo/app/installer/InstallSourceLifecycleObserver.kt, app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt, app/src/test/java/com/duckduckgo/app/installer/InstallSourceLifecycleObserverTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204413310429877/f
Detects the app installation source package ID.
See https://app.asana.com/0/488551667048375/1204413310429877/f
=> Detect app install source package

app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204422679141860/f 
This PR deletes a flaky test
N/A
=> Delete flaky test

app/src/main/java/com/duckduckgo/app/global/shortcut/AppShortcutCreator.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204427411055565/f
Fixes an ANR which can happen because we're making a potentially slow binder call from the main thread, which is on the hot path for main process creation.
The fix is to simply move the call off of the main thread.
=> Move app shortcut creation away from main thread to avoid ANR

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, content-scope-scripts/content-scope-scripts-api/build.gradle, content-scope-scripts/content-scope-scripts-api/src/main/java/com/duckduckgo/contentscopescripts/api/ContentScopeScripts.kt, content-scope-scripts/content-scope-scripts-api/src/main/java/com/duckduckgo/contentscopescripts/api/MessageHandlerPlugin.kt, content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScripts.kt, content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/MessagingInterface.kt, content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/RealMessagingContentScopeScripts.kt, content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/ReplyHandler.kt, content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScriptsTest.kt, content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/MessagingInterfaceTest.kt, content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/RealMessagingContentScopeScriptsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204439726864819/f
This PR adds two way messaging between the Android app and C-S-S.
=> Add content scope messaging

app/src/main/java/com/duckduckgo/app/browser/menu/BrowserPopupMenu.kt
Task/Issue URL: https://app.asana.com/0/0/1204447846397811/f
Removes Kotlin synthetics from the `BrowserPopupMenu`
=> Remove synthetics from BrowserPopupMenu

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/RealAutoconsent.kt, autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPlugin.kt, autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/RealAutoconsentTest.kt, autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPluginTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204462127127228/f
This PR removes the cookie prompt management experiment.
=> Remove CPM experiment

app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/rules/ExceptionRulesDebugReceiver.kt
Task/Issue URL: https://app.asana.com/0/1202279501986195/1204239874324815/f
Fixed app tracker exception rules in dev settings.
This is only for internal builds. Check task description.
=> AppTP: Fix app/tracker exception dev setting

app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/ui/VpnScreens.kt, app-tracking-protection/vpn-impl/build.gradle, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModel.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/ManageRecentAppsProtectionActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionExclusionListActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/AppFeedbackContract.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageAppListActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageCategorySingleChoiceActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageContract.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/AppTPCompanyTrackersActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModelTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageContractTest.kt, app/src/main/java/com/duckduckgo/app/feedback/ui/common/FeedbackActivity.kt, browser-api/src/main/java/com/duckduckgo/browser/api/ui/BrowserScreens.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204478230288070/f
See linked task description
Smoke test AppTP Breakage reporting flow
=> Allow breakage reporting to be launched outside of vpn-impl

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncRepository.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupActivity.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupViewModel.kt, sync/sync-impl/src/main/res/layout/activity_sync_setup.xml, sync/sync-impl/src/test/java/com/duckduckgo/sync/AppSyncDeviceIdsTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncRepositoryTest.kt, sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204323155244517/f 
Remove testing deprecated methods no more used (e.g: storing recovery key in shared prefs)
Tests should pass, no changes in production code.
=> Remove testing deprecated methods

common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/text/DaxTextView.kt, common-ui/src/main/res/layout/fragment_components_typography.xml, common-ui/src/main/res/values/attrs-typography.xml, common-ui/src/main/res/values/design-system-typograhy.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204477707557554/f
Added new typography style `Mono`
- Go to Settings > ADS Preview
=> ADS: Mono Typography

versioning.gradle
Task/Issue URL: https://app.asana.com/0/488551667048375/1204511269850278/f
See task
NA
=> Revert buildNumberCode modifications

.github/workflows/end-to-end.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204511269850311/f
See asana task
NA just code review
=> Temp disable tests

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/blocklist/AppTrackerListService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204523907098131/f
Bump the android-tds endpoint
_Test endpoint update_
_Test Entity Changes_
Repeat tests in #3115
=> Bump android-tds to 2.1

.github/workflows/ci.yml, .github/workflows/external-css-tests.yml, .github/workflows/external-ref-tests.yml, .github/workflows/nightly.yml, .github/workflows/privacy.yml
Task/Issue URL: https://app.asana.com/0/1202552961248957/1202007033047366/f 
This PR adds for each workflow running Android tests a new print report so we don't have to go to Firebase to see what test failed and why.
=> Improve CI reporting

anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ExceptionModels.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1204410260530429/f
See asana for more info
Run same tests that in PR #3052
=> Align ANR and Crash reporting

app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1204137541408857/f
Disable experiment variants [mi,mj] until determining whether to remove, edit, or implement based on experiment success
=> Disable Onboarding Cutomization experiment

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillClipboardInteractor.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/passwordgeneration/AutofillGeneratePasswordDialogFragment.kt, autofill/autofill-impl/src/main/res/layout/content_autofill_generate_password_dialog.xml, autofill/autofill-impl/src/main/res/values/donottranslate.xml, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1204521636614367/f
_Feature 1_
=> Add copy button to password generation prompt

versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1204551916732877/f
_Autofill Logins_
_General smoke testing_
=> Update OkHttp to 4.11.0

app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/0/1204431384408586/f
Enabled control ze and variants zi, zn, zo.
This was tested as part of https://app.asana.com/0/1142021229838617/1204380807766486/f
=> Enable the variants [ze (control), zi, zn, zo]

app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsActivity.kt, app-tracking-protection/vpn-internal/src/main/res/layout/activity_vpn_internal_settings.xml, app-tracking-protection/vpn-store-test/src/main/java/com/duckduckgo/mobile/android/vpn/trackers/FakeAppTrackerRepository.kt, app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/dao/VpnAppTrackerBlockingDao.kt, app-tracking-protection/vpn-store/src/main/java/com/duckduckgo/mobile/android/vpn/trackers/AppTrackerRepository.kt
Task/Issue URL: https://app.asana.com/0/1202279501986195/1202407442660860/f
Added dev option to unprotect all apps.
This is an internal dev feature, see task details.
This is an internal dev feature, see task details.
=> AppTP: AppTP dev setting to unprotect all apps

app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/FakeVpnFeaturesRegistry.kt, app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistry.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistryImpl.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistryImplTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204549388878335/f
Removing unused code in VpnFeatureRegistryImpl
QA optional
=> Remove OnSharedPreferenceChangeListener in VpnFeatureRegistryImL

app/src/androidTest/java/com/duckduckgo/app/referencetests/DomainsReferenceTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1204587749511820/f
This PR mocks the needed headers on the test's request when `requestType` is set to `stylesheet`.
See: https://app.asana.com/0/0/1204504672745452/f
Update the `domain_matching_tests.json` and `tracker_radar_reference.json` to the one in the PR in the linked task. All tests should pass.
=> Add needed headers to mockRequest when test requestType is stylesheet

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1204371051688547/f
See asana task
NA, just CI
=> Enforce braces in some of the code gen

windows/windows-impl/src/main/res/values-bg/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-cs/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-da/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-de/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-el/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-es/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-et/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-fi/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-fr/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-hr/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-hu/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-it/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-lt/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-lv/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-nb/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-nl/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-pl/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-pt/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-ro/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-ru/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-sk/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-sl/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-sv/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-tr/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values/strings-waitlist-windows.xml
Task/Issue URL: https://app.asana.com/0/0/1204569901701349/f
Added new strings.
Nothing to test. These strings are not used yet.
=> Android: Translations for the removal of windows waitlist in the Android app

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204513195956997/f 
Add crashlog for crash events inside webview shouldOverride method
_Feature 1_
=> add crash log for shouldoverride method

app/src/main/java/com/duckduckgo/app/email/db/EmailDataStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204602761381113/f
Ditto
NA
=> Catch all exceptions when creating encryptedPreferences

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncService.kt
Task/Issue URL: https://app.asana.com/0/0/1204271813589864/f
As per https://app.asana.com/0/1201493110486074/1204281350459316/f, we have removed `device_` prefix for device data model.
_Feature 1_
=> Remove device prefix (json sync)

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgServerApi.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/FakeWgVpnControllerService.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/RealWgServerApiTest.kt, network-protection/network-protection-store/src/main/java/com/duckduckgo/networkprotection/store/remote_config/NetPServerRepository.kt, network-protection/network-protection-store/src/main/java/com/duckduckgo/networkprotection/store/remote_config/NetPServersDao.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204626421744357/f
See asana task for complete description
See asana task for test description
=> Fix server selection

autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml, windows/windows-impl/src/main/res/values-bg/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-cs/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-da/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-de/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-el/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-es/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-et/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-fi/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-fr/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-hr/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-hu/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-it/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-lt/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-lv/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-nb/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-nl/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-pl/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-pt/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-ro/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-ru/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-sk/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-sl/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-sv/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values-tr/strings-waitlist-windows.xml, windows/windows-impl/src/main/res/values/strings-waitlist-windows.xml
Task/Issue URL: https://app.asana.com/0/0/1204610738544043/f
Updated string as it has changed.
Nothing to test. These strings are not used yet.
=> Android: Update windows description string

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/heartbeat/VpnServiceHeartbeat.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204602761381238/f
See asana task
Repeate repro steps in asana task for develop and this branch
* develop should repro the bug
* this branch should not repro
=> Fix race condition when disabling VPN

privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/amplinks/AmpFormatReferenceTest.kt, privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/amplinks/AmpKeywordReferenceTest.kt, privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/trackingparameters/TrackingParameterReferenceTest.kt
Task/Issue URL: https://app.asana.com/0/414730916066338/1204642091102640/f
This adds `exceptPlatform` support to the AMP links and tracking parameter reference tests.
Checked here: https://github.com/duckduckgo/Android/actions/runs/5039790552.
=> Add exceptPlatforms to AMP links and tracking parameter reference tests

autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_edit_mode.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204323981016883/f
Sets the input type on the URL entry field so it doesn't autocorrect
=> Set inputType on url field to avoid autocorrect/capitalisation

app-tracking-protection/vpn-impl/build.gradle, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt, versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1204632863750325/f
See [asana task](https://app.asana.com/0/488551667048375/1204632863750325/f).
Follow steps in [asana task](https://app.asana.com/0/488551667048375/1204632863750325/f).
=> Improve tun persistance

.maestro/release_tests/3_-_favorites.yaml
Task/Issue URL: https://app.asana.com/0/0/1204658573545767/f
Disables problematic steps in the favorites test.
=> Disable favorites test undo asserts

network-protection/network-protection-impl/src/main/res/layout/activity_netp_waitlist_redeem_code.xml
Task/Issue URL:  https://app.asana.com/0/1174433894299346/1204569170948777/f
Ensure TextInput is showing the text in capital letters
See [asana task](https://app.asana.com/0/488551667048375/1204569170948777/f)
=> NP Invites in Capital letters

app/src/internal/java/com/duckduckgo/app/dev/settings/api/ApiDevTdsInterceptor.kt, app/src/main/java/com/duckduckgo/app/trackerdetection/api/TrackerListService.kt
Task/Issue URL: https://app.asana.com/0/0/1204602434877138/f
Updated blocklist endpoints.
See the "Testing" section in https://app.asana.com/0/0/1204602434877138/f and comment https://app.asana.com/0/0/1204602434877138/1204666905736745/f.
=> Update platforms to use new blocklist endpoints - Android

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgServerApi.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/RealWgServerApiTest.kt, network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/di/NetPInternalModule.kt, network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/WgServerInternalProvider.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204649568621587/f
See [asana task](https://app.asana.com/0/488551667048375/1204649568621587/f)
See [asana task](https://app.asana.com/0/488551667048375/1204649568621587/f)
=> Internal build srv selection

versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1204675443069720/f
See [asana task](https://app.asana.com/0/488551667048375/1204675443069720/f)
* Pull https://github.com/duckduckgo/netguard/pull/21
* go to netguard android folder and run `./gradlew clean assemble publishToMavenLocal`
* checkout this branch
* modify `versions.properties` to be `version.com.duckduckgo.netguard..netguard-android=1.5.0-SNAPSHOT`
* modify root `build.gradle` and add `mavenLocal()` ander `allprojects -> repositories`
* in Android repo, execute `rm -rf build-cache/; ./gradlew clean assembleID`
* smoke tests AppTP and NetP, one enabled, other enabled, both enabled
=> Update to netguard 1.5.0

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldAlertNotificationBuilder.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/VpnEnabledNotificationBuilder.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/VpnReminderNotificationBuilder.kt, app/src/androidTest/java/com/duckduckgo/app/notification/NotificationRegistrarTest.kt, app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt, app/src/main/java/com/duckduckgo/app/notification/NotificationRegistrar.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1203771987668114/f
Replaced `NotificationManager` with `NotificationManagerCompat`.
=> Implementation task: NotificationManager vs NotificationManagerCompat

privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/PrivacyConfigPersister.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204684922596621/f
Adds an extra log statement which shows whether fetched private config will be persisted or not.
QA-optional
=> Add extra log statement which shows whether config will be persisted or not

app/src/main/java/com/duckduckgo/app/sync/FakeDeviceSyncState.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/AppDeviceSyncState.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204676817319311/f 
Enables, and makes feature visible, to internal flavor (aka. internal users)
_Feature 1_
=> Enable sync for internal

autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values/donottranslate.xml, autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/selecting/CredentialTextExtractorTest.kt, macos/macos-impl/src/main/res/values-sl/strings-macos-waitlist.xml, windows/windows-impl/src/main/res/values-fr/strings-waitlist-windows.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204587889053408/f
Copy changes and getting translations for previously untranslated strings.
=> Update autofill copy and trigger translations

saved-sites/saved-sites-store/build.gradle, sync/sync-store/build.gradle, versions.properties
Task/Issue URL: https://app.asana.com/0/1202552961248957/1204495622342184/f
Removed deprecated dependency (also unused).
Tests should pass.
=> Android: Remove android.arch.persistence.room dependencies 

common-test/src/main/java/com/duckduckgo/app/global/api/FakeChain.kt, network-protection/network-protection-impl/build.gradle, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgServerApi.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerRequestInterceptor.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerRequestInterceptorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204684146330430/f
See [asana](https://app.asana.com/0/488551667048375/1204684146330430/f) task.
Follow test cases in asana [asana](https://app.asana.com/0/488551667048375/1204684146330430/f) task.
=> Add NP internal debug server capability

app/src/main/java/com/duckduckgo/app/di/NetworkModule.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1204588257103865/f
Fix odd crash in okhttp interceptors. See asana task for more info
Smoke tests
=> Fix crashes on DefaultProxySelector

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204735656268741/f
Ditto
Smoke tests for AppTP/NP
=> Stop VPN on null activeTun

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/cohort/CohortPixelInterceptor.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/cohort/CohortPixelInterceptorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204747165538748/f
See asana  task description
See asana  task description
=> Exclude atp breakge from CohortPixelInterceptor

versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1204763839445769/f
Ditto
Test should have been done as part of https://app.asana.com/0/1198194956794324/1204752999420523
=> Update the networking layer to 1.6.0

app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoActivity.kt, app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModel.kt, app/src/main/java/com/duckduckgo/app/about/FeedbackContract.kt, app/src/main/res/layout/content_about_duck_duck_go.xml, app/src/test/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1204670283311481/f
Updated the `About DuckDuckGo` screen.
|![about_ddg_before](https://github.com/duckduckgo/Android/assets/7963079/50a047d8-fc74-488a-8fe5-a60b222a7cd4)|![about_ddg_after](https://github.com/duckduckgo/Android/assets/7963079/a7b8b71f-8d4f-449a-a3db-74a74ab9e570)|
=> Update the existing "About DuckDuckGo" screen to match the new design

app/src/main/AndroidManifest.xml, app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoActivity.kt, app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModel.kt, app/src/main/java/com/duckduckgo/app/about/FeedbackContract.kt, app/src/main/java/com/duckduckgo/app/appearance/AppearanceActivity.kt, app/src/main/java/com/duckduckgo/app/appearance/AppearanceViewModel.kt, app/src/main/java/com/duckduckgo/app/appearance/ChangeIconContract.kt, app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt, app/src/main/res/layout/activity_appearance.xml, app/src/main/res/layout/content_about_duck_duck_go.xml, app/src/main/res/values/donottranslate.xml, app/src/test/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModelTest.kt, app/src/test/java/com/duckduckgo/app/appearance/AppearanceViewModelTest.kt, app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1204670443433650/f
New Appearance screen.
|![old_appearance_section](https://github.com/duckduckgo/Android/assets/7963079/df7ac822-97cd-47ca-8d5a-1878fa982763)|![appearance_screen](https://github.com/duckduckgo/Android/assets/7963079/33bb70b4-0655-44d4-a8f9-46837dc20dec)|
=> Create the new Appearance screen

app/src/main/AndroidManifest.xml, app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoActivity.kt, app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModel.kt, app/src/main/java/com/duckduckgo/app/about/FeedbackContract.kt, app/src/main/java/com/duckduckgo/app/appearance/AppearanceActivity.kt, app/src/main/java/com/duckduckgo/app/appearance/AppearanceViewModel.kt, app/src/main/java/com/duckduckgo/app/appearance/ChangeIconContract.kt, app/src/main/java/com/duckduckgo/app/permissionsandprivacy/PermissionsAndPrivacyActivity.kt, app/src/main/java/com/duckduckgo/app/permissionsandprivacy/PermissionsAndPrivacyViewModel.kt, app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt, app/src/main/res/layout/activity_appearance.xml, app/src/main/res/layout/activity_permissions_and_privacy.xml, app/src/main/res/layout/content_about_duck_duck_go.xml, app/src/main/res/layout/content_permissions_and_privacy.xml, app/src/main/res/layout/content_permissions_and_privacy_section_customize.xml, app/src/main/res/layout/content_permissions_and_privacy_section_privacy.xml, app/src/main/res/values/donottranslate.xml, app/src/test/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModelTest.kt, app/src/test/java/com/duckduckgo/app/appearance/AppearanceViewModelTest.kt, app/src/test/java/com/duckduckgo/app/permissionsandprivacy/PermissionsAndPrivacyViewModelTest.kt, app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/0/1204667877992130/f 
Created the new "Permissions and Privacy" screen.
| New screen  | New screen scrolled to bottom |
|![permissions_and_privacy_1](https://github.com/duckduckgo/Android/assets/7963079/b87e9ec3-4351-425d-abb2-3f0d619f14b6)|![permissions_and_privacy_2](https://github.com/duckduckgo/Android/assets/7963079/34313aea-e906-4b36-88ce-e369394d6599)|
=> Create the new "Permissions and Privacy" screen

versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1204810793215818/f
Update ng library to 1.6.1 that provides a fix for [this](https://app.asana.com/0/488551667048375/1204810793215818/f)
=> Update ng lib to 1.6.1

.github/workflows/create-issue-asana-task.yaml
Task/Issue URL: https://app.asana.com/0/1174433894299346/1204778116780349
This PR adds an action that will be triggered after an issue has been opened / reopened. The action will take the issue and create a task in the Android app project
=> Add workflow for Github issues

.github/workflows/create-issue-asana-task.yaml
Task/Issue URL: https://app.asana.com/0/1174433894299346/1204778116780349
Description
This PR adds an action that will be triggered after an issue has been opened / reopened. The action will take the issue and create a task in the Android app project
=> 06 13 add workflow for GitHub issues

common-ui/src/main/res/values/design-system-dimensions.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204723717455130/f
Updated header component. 
| Before  (grid is 4dpx4dp)| After (grid is 4dpx4dp)|
|![header_before](https://github.com/duckduckgo/Android/assets/7963079/6222834c-7446-4fde-a0cc-a70c4a7bdeb8)|![header_12dp_top_bottom](https://github.com/duckduckgo/Android/assets/7963079/9a86c50e-5ec4-49b6-90ba-52b0eb1eb77c)|
=> ADS: Update Android Component - SectionHeaderListItem

app/src/main/java/com/duckduckgo/app/settings/CheckListItem.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt, app/src/main/res/drawable/ic_check_green_round_16.xml, app/src/main/res/drawable/ic_check_grey_round_16.xml, app/src/main/res/drawable/ic_exclamation_yellow_16.xml, app/src/main/res/layout/content_settings_privacy.xml, app/src/main/res/layout/view_check_list_item.xml, app/src/main/res/values/attrs-settings-check-list-item.xml, app/src/main/res/values/donottranslate.xml, app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt, common-ui/src/main/res/values/attrs-settings-check-list-item.xml, common-ui/src/main/res/values/design-system-dimensions.xml, common-ui/src/main/res/values/design-system-theming.xml, common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/0/0/1204823525139316/f
Created the `CheckListItem` component and updated the `Settings` screen to use it.
See Asana.
=> Create the CheckListItem component

app/src/main/java/com/duckduckgo/app/settings/CheckListItem.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt, app/src/main/res/drawable/ic_check_green_round_16.xml, app/src/main/res/drawable/ic_check_grey_round_16.xml, app/src/main/res/drawable/ic_exclamation_yellow_16.xml, app/src/main/res/layout/content_settings_other.xml, app/src/main/res/layout/content_settings_privacy.xml, app/src/main/res/layout/view_check_list_item.xml, app/src/main/res/values/donottranslate.xml, app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt, common-ui/src/main/res/values/attrs-settings-check-list-item.xml, common-ui/src/main/res/values/design-system-dimensions.xml, common-ui/src/main/res/values/design-system-theming.xml, common-ui/src/main/res/values/widgets.xml
Task/Issue URL: https://app.asana.com/0/0/1204823525139300/f
Moved NetP to the Privacy section. 
See Asana.
=> Move Network Protection item in the Privacy section

common-ui/src/main/res/layout/view_one_line_list_item.xml, common-ui/src/main/res/layout/view_two_line_item.xml, common-ui/src/main/res/values/design-system-dimensions.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204725232875765/f
Updated one line item component. 
|![one_line_item_before](https://github.com/duckduckgo/Android/assets/7963079/1eb28f20-4c6f-47dc-92c1-e33ab3ad126c)|![one_line_item_after](https://github.com/duckduckgo/Android/assets/7963079/c23a59d3-1390-4db6-99d6-e0444c0831e0)|
=> ADS: Update Android Component - OneLineItem

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/ui/AppExclusionListAdapter.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/ui/NetpAppExclusionListActivity.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt
Task/Issue URL: https://app.asana.com/0/0/1204915772487620/f
See linked task description
See linked task description
=> Fix visibility of exclusion list entry

.github/workflows/action-issue-opened.yaml, .github/workflows/action-pr-approved.yaml, .github/workflows/action-pr-merged.yaml, .github/workflows/action-pr-opened.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204923293773595/f 
- Ensure comment mentioning a PR has been opened is pinned
- Ensure comment for PR approved says “has been approved"
=> Github Action: PR related actions

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/ExclusionListAdapter.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/ManageRecentAppsProtectionActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionAppsAdapter.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionExclusionListActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/AppTPCompanyTrackersActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204675444473104/f
This PR includes: 
- When AppTP is disabled, all places where the app can be included/excluded should be disabled. (View apps, Having issues with an app? and App tracking details)
=> Align exclusion list inconsistencies

app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt, statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Task/Issue URL: https://app.asana.com/0/0/1204957687799632/f
Disabled the AppTP promo experiment.
=> Disable the AppTP promotion experiment

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/NetworkConnectivityHealthHandler.kt
Task/Issue URL: https://app.asana.com/0/1202279501986195/1204984864703009/f
See [asana](https://app.asana.com/0/1202279501986195/1204984864703009/f) description
See Asana task
=> Fix connectivity checks

app/src/androidTest/java/com/duckduckgo/app/browser/favicon/DuckDuckGoFaviconManagerTest.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksAdapter.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/FavoritesAdapter.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/java/com/duckduckgo/app/browser/favicon/DuckDuckGoFaviconManager.kt, app/src/main/java/com/duckduckgo/app/browser/favorites/FavoritesQuickAccessAdapter.kt, app/src/main/java/com/duckduckgo/app/browser/history/NavigationHistoryAdapter.kt, app/src/main/java/com/duckduckgo/app/fire/fireproofwebsite/ui/FireproofWebsiteAdapter.kt, app/src/main/java/com/duckduckgo/app/privacy/ui/WebsitesAdapter.kt, app/src/main/java/com/duckduckgo/app/sitepermissions/SitePermissionsAdapter.kt, app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherAdapter.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementRecyclerAdapter.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/selecting/AutofillSelectCredentialsDialogFragment.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/updating/AutofillUpdatingExistingCredentialsDialogFragment.kt, browser-api/src/main/java/com/duckduckgo/app/browser/favicon/FaviconManager.kt, saved-sites/saved-sites-store/src/main/java/com/duckduckgo/savedsites/store/SavedSitesEntitiesDao.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204866768913622/f
Refactor usage of remote fallback when showing list of sites.
_Feature 1_
=> refactor usages of Remote Fallback method

saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataObserver.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/RealSyncStateMonitor.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/RealSyncEngine.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1204997928543695/f
Details in task
=> Sync: DataObserver

app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/network/FakeDnsProvider.kt, app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSetting.kt, app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/network/DnsProvider.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/NetworkTypeCollector.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/settings/InterceptDnsTrafficSettingPlugin.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/network/DnsProviderImpl.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/network/util/NetworkUtil.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnActiveNetworkManager.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpFeatureConfigImplTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/AppTpSettingTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/feature/settings/InterceptDnsTrafficSettingPluginTest.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStackTest.kt, app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsActivity.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/WgVpnNetworkStack.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/WgVpnNetworkStackTest.kt
Task/Issue URL: https://app.asana.com/0/0/1204861228999911/f
Draft PR, see https://app.asana.com/0/0/1204861228999911/f
Smoke testing AppTP
=> DNS-based blocking

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt, app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt, app/src/main/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptor.kt, app/src/test/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptorTest.kt
Task/Issue URL: https://app.asana.com/0/69071770703008/1204310988015989/f
Removed atb info and temporary pixels added for AppTP promo experiment.
Tests are passing.
=> Follow up: Remove ATB info from AppTP pixels + 2 new(-ish) pixels + other AppTP pixels

.github/workflows/end-to-end.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205016568978171/f 
Reenable Maestro privacy tests
=> Reenable privacy tests on Maestro

.github/PULL_REQUEST_TEMPLATE.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205064083287336/f
Updates testing expectations re API levels. Instead of specifying API 26 specifically, recommends generally choosing one of the more recent API levels.
=> Update API level testing expectations in PR template

network-protection/network-protection-impl/src/main/res/layout/activity_netp_faqs.xml, network-protection/network-protection-impl/src/main/res/layout/item_about_qa.xml, network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/0/1204977026793263/f
QA-optional
=> Update copy to approved

package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205044375141053/f 
----- 
=> Update reference tests to version 1689232034

node_modules/@duckduckgo/autofill/dist/autofill-debug.js, node_modules/@duckduckgo/autofill/dist/autofill.js, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1205060095332912/1205060095332912
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.0.0
Updates Autofill to version [8.0.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.0.0).
* Remove in-context eligible pixel by @alistairjcbrown in https://github.com/duckduckgo/duckduckgo-autofill/pull/330
* Run password rules workflow on schedule by @alistairjcbrown in https://github.com/duckduckgo/duckduckgo-autofill/pull/334
* Add build step after pulling password rules by @alistairjcbrown in https://github.com/duckduckgo/duckduckgo-autofill/pull/338
* Update password rules (2023-06-23) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/341
* Update password rules (2023-06-27) by …
=> Update autofill to 8.0.0

app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt, app/src/main/res/values/donottranslate.xml, app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt, network-protection/network-protection-api/src/main/java/com/duckduckgo/networkprotection/api/NetworkProtectionState.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/state/NetworkProtectionStateImpl.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205056561538274/f
Fix a lag in setting the NetP state when coming into settings
Verify repro steps in [asana task](https://app.asana.com/0/488551667048375/1205056561538274/f) don't repro anymore
=> Fix lag setting state in settings

node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205071124454514/f 
----- 
=> Update content scope scripts to version 4.26.0

app/src/main/java/com/duckduckgo/app/browser/webview/WebViewActivity.kt, autoconsent/autoconsent-api/src/main/java/com/duckduckgo/autoconsent/api/WebViewScreens.kt, autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/ui/AutoconsentSettingsActivity.kt, autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/ui/AutoconsentSettingsViewModel.kt, autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/ui/AutoconsentSettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205073613446674/f
Added title to the webview activity when displaying the cookie pop-up management web page.
=> Android: Add title for the Cookie management screen

app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserDetector.kt
Task/Issue URL: https://app.asana.com/0/0/1205085072577091/f
Updated DefaultBrowserDetector to use the new resolveActivity method for Android 13+.
Test on Android 13
Test on Android 12 or below
---
- https://app.asana.com/0/0/1205083156611885
=> Default browser - Address the usage of deprecated resolveActivity

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnActiveNetworkManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205099555454598/f
See [asana task](https://app.asana.com/0/488551667048375/1205099555454598/f)
Smoke tests for AppTP
=> Unregister network callbacks when re-configuring VPN interface

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt, autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml, autofill/autofill-impl/src/main/res/values/donottranslate.xml, autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204999104726155/f
Translations for managing duck addresses
=> Translations for managing duck addresses

.github/workflows/docs.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205102720433089/f
Set the docs github action to use Java 17.
=> Set Docs GHA to use Java 17

package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205106074725525/f 
----- 
=> Update reference tests to version 1689858388

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-et/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-lv/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1204861300332754/f 
This PR adds a toast message whenever the screen goes to full screen
=> Add toast when screen goes to full screen

.maestro/release_tests/7_-_app_tp_onboarding.yaml
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205122248406615/f
Updated the `7_-_app_tp_onboarding.yaml` file to match the latest changes in the `Settings` screen. 
End-to-end tests should pass.
Or checkout this branch and run locally:
`maestro test .maestro/release_tests/7_-_app_tp_onboarding.yaml`
=> Update maestro tests - AppTP onboarding

app/src/test/resources/reference_tests/brokensites/tests.json, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205119798286782/f 
----- 
=> Update reference tests to version 1689964986

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt, app/src/androidTest/java/com/duckduckgo/app/email/EmailInjectorJsTest.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/AutofillCapabilityCheckerImplTest.kt, content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScriptsTest.kt, feature-toggles/feature-toggles-api/src/main/java/com/duckduckgo/feature/toggles/api/FeatureToggles.kt, feature-toggles/feature-toggles-impl/build.gradle, feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/api/FeatureTogglesTest.kt, feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt, feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/TestTriggerFeature.kt
Task/Issue URL: https://app.asana.com/0/72649045549333/1204971805879942/f
Add incremental feature rollouts
Follow test steps in [asana](https://app.asana.com/0/0/1205103489376199/f) task
=> Incremental feature flags rollout

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt, autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/di/AutofillModule.kt, autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStoreTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205158969433228/f
Moves `SecureStoreBackedAutofillStore` to `autofill-impl` module
=> Move SecureStoreBackedAutofillStore to autofill-impl module

node_modules/@duckduckgo/content-scope-scripts/README.md, node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205167766988669/f 
----- 
=> Update content scope scripts to version 4.29.0

app/src/androidTest/java/com/duckduckgo/app/privacy/db/UserAllowListRepositoryTest.kt, app/src/main/java/com/duckduckgo/app/browser/useragent/UserAgentProvider.kt, app/src/main/java/com/duckduckgo/app/privacy/db/RealUserAllowListRepository.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205112415074822/f
Removed uneeded `runblocking` block. Updated `RealUserAllowListRepository`.
See Asana comment https://app.asana.com/0/0/1205112415074822/1205142849992749/f
=> Android ANR: com.duckduckgo.app.browser.useragent.UserAgentProvider.isHostInUserAllowedList

app/src/main/java/com/duckduckgo/app/firebutton/FireButtonActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205175111966221/f
Updated the "Fire Button" screen to correctly display the selected fire animation.
Reproduce:
Test the fix:
=> Android: Chosen "Fire button animation" not displayed 

common/common-ui/src/main/res/values-h600dp/dimens.xml, common/common-ui/src/main/res/values-land/dimens.xml, common/common-ui/src/main/res/values/design-system-dimensions.xml
Task/Issue URL: https://app.asana.com/0/414730916066338/1205173858382786/f
Updated dimens value for `dialogRadioGroupHeightMax` used when reporting broken sites.
Check the issue on a small device (e.g Nexus 4)
Check the issue on any device in landscape
Test on different screen sizes and landscape.
| Device portrait | Device landscape |
|![normal_device_portrait](https://github.com/duckduckgo/Android/assets/7963079/929b4341-b851-489f-930d-08253b23db24)|![normal_device_land](https://github.com/duckduckgo/Android/assets/7963079/50939cd9-9680-4afe-b0cd-f6d02ca591be)|
| Small device portrait | Small Device landscape |
|![samll_device_portrait](https://github.com/duckduckgo/Android/assets/7963079/cda808ef-125b-4b70-8610-03c5ddc3e9ab)|![small_device_land](htt …
=> Report Broken Site Not Working?

common/common-ui/src/main/res/drawable/ic_paste.xml, sync/sync-impl/src/main/res/drawable/ic_qr_24.xml, sync/sync-impl/src/main/res/layout/activity_enter_code.xml, sync/sync-impl/src/main/res/layout/activity_show_qr_code.xml
Task/Issue URL: https://app.asana.com/0/0/1205190692260211/f
Address comments from design review
- Open settings
- Open sync
- Turn sync on
- Tap on “Turn on Sync"
- Tap on “Sync another device"
- Check ScanQR Code screen, and tap on “Manually Enter Code” and “Show QR Code"
=> Design improvements on sync

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/alwayson/AlwaysOnLockDownDetector.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldAlertNotificationBuilder.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt, app-tracking-protection/vpn-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/0/1205084208625049/f
See attached task description.
See attached task description.
=> Implement reconciled lockdown notifs

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerService.kt, network-protection/network-protection-internal/build.gradle, network-protection/network-protection-internal/src/main/AndroidManifest.xml, network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/NetPEnvironmentSettingActivity.kt, network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/NetPInternalSettingsActivity.kt, network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/NetPInternalEnvDataStore.kt, network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/NetPInternalEnvInterceptor.kt, network-protection/network-protection-internal/src/main/res/layout/activity_netp_env_internal_settings.xml, network-protection/network-protection-internal/src/main/res/layout/activity_netp_internal_settings.xml, network-protection/network-protection-internal/src/main/res/values/donottranslate.xml, privacy-config/privacy-config-internal/src/main/java/com/duckduckgo/privacy/config/internal/store/DevPrivacyConfigSettingsDataStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205236994263036/f
Dev settingn to change NP environment.
See [asana](https://app.asana.com/0/488551667048375/1205236994263036/f) task
=> Internal setting to change NP environments

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsActivity.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsViewModel.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/BillingClientWrapper.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/BillingUtils.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/repository/SubscriptionsRepository.kt, subscriptions/subscriptions-impl/src/main/res/layout/activity_subscriptions.xml, subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/RealSubscriptionsRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205077126622545/f 
This PR adds multiple subs for testing
See https://app.asana.com/0/488551667048375/1205077126622545/f
=> Add multiple subs

app-tracking-protection/app-tracking-api/src/main/java/com/duckduckgo/mobile/android/app/tracking/AppTrackingProtection.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/app/tracking/RealAppTrackingProtection.kt, app/src/main/java/com/duckduckgo/app/di/DevicePropertiesModule.kt, app/src/main/java/com/duckduckgo/app/global/store/AndroidUserBrowserProperties.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt, app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt, browser-api/src/main/java/com/duckduckgo/browser/api/UserBrowserProperties.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/mappers/JsonRulesMapper.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/matchers/UserAttributeMatcher.kt, remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/models/MatchingAttributes.kt, remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/matchers/UserAttributeMatcherTest.kt
Task/Issue URL: https://app.asana.com/0/1203137811378537/1205187503800387/f
RMF for NetP beta closure
See [asana task](https://app.asana.com/0/1203137811378537/1205187503800387/f)
See [Asana task](https://app.asana.com/0/0/1205202021117989/f)
=> RMF for NP beta

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerRequestInterceptor.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205234536443669/f
Change the NP environment
NetP smoke test
=> Change NP environment

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/cohort/NetPCohortUpdater.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/cohort/NetPCohortUpdaterTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205241408463304/f
See attached task description.
See attached task description.
=> Fix bug in cohort updater

app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205234536443750/f
See Asana for more info
Repeat tests in https://github.com/duckduckgo/Android/pull/3316
=> Fix ANRs in BrowserTabViewModel

anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt, feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205234536443803/f
Handle the case where a sub-feature FF is present remotely but not present locally
Test case in [here](https://app.asana.com/0/488551667048375/1205234536443803/f)
Also the integration test added verifies the same thing (that test would fail in develop witht the same error)
=> Allow for locally missing feature flags

app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPage.kt, app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModel.kt, app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt, app/src/test/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205241408463310/f
Remove old pixels since they are not actively monitored anymore.
QA-Optional
=> Remove irrelevant m_odb pixels

.maestro/ads_preview_flows/1-_design-system-components.yaml, .maestro/app_tp/app_tp_onboarding.yaml, .maestro/bookmarks/ensure_bookmarks_can_be_added_and_deleted.yaml, .maestro/browsing/visit_site.yaml, .maestro/favorites/favorites_bookmarks_delete.yaml, .maestro/favorites/favorites_bookmarks_undo.yaml, .maestro/favorites/favorites_menu_add_remove.yaml, .maestro/fire_button/fire_during_onboarding.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205234542811812/f
Refactors release tests to make use of the shared onboarding flow, removing the need to duplicate those steps inside every individual test.
Other test types will be done in separate PRs.
=> Re-use shared onboarding flow across all release tests

autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSyncDataObserver.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/triggers/AppLifecycleSyncObserver.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205266828096285/f
See [asana task](https://app.asana.com/0/488551667048375/1205266828096285/f)
Smoke tests sync
=> Move EncryptedSharedPrefsProvider.getSharedPrefs to IO dispatcher

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/DeviceInfoCollector.kt, app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml, app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt, app/src/main/res/layout/view_item_downloads_notify_me.xml, common/common-ui/src/main/res/layout/view_notify_me_view.xml, network-protection/network-protection-api/src/main/java/com/duckduckgo/networkprotection/api/NetworkProtectionWaitlist.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/about/AboutQAItemView.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/cohort/NetpCohortPixelInterceptor.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetPWaitlistActivity.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetPWaitlistChecker.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetPWaitlistCodeNotification.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetworkProtectionWaitlistImpl.kt, network-protection/network-protection-impl/src/main/res/layout/activity_netp_terms.xml, network-protection/network-protection-impl/src/main/res/layout/activity_netp_waitlist.xml, network-protection/network-protection-impl/src/main/res/layout/activity_netp_waitlist_invited.xml, network-protection/network-protection-impl/src/main/res/layout/item_about_qa.xml, network-protection/network-protection-impl/src/main/res/layout/view_waitlist_check_list_item.xml, network-protection/network-protection-impl/src/main/res/values/donottranslate.xml, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/waitlist/NetworkProtectionWaitlistTest.kt, request-filterer/request-filterer-store/src/test/java/com/duckduckgo/request/filterer/store/RealRequestFiltererRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/0/1205258659015741/f
See [asana task](https://app.asana.com/0/0/1205258659015741/f)
QA optional (see [asana task](https://app.asana.com/0/0/1205258659015741/f))
=> Address design/copy comments for NP 

app/src/androidTest/java/com/duckduckgo/app/referencetests/FireproofingReferenceTest.kt, app/src/androidTest/resources/reference_tests/fireproofing/tests.json, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205281758442461/f 
----- 
=> Update reference tests to version 1692081744

app/src/main/java/com/duckduckgo/app/global/api/AtbAndAppVersionPixelRemovalInterceptor.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/cohort/NetpCohortPixelInterceptor.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/test/NetPIncrementalRolloutTestFeature.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/test/NetPIncrementalRolloutTestLogger.kt
Task/Issue URL: https://app.asana.com/0/1203137811378537/1205266828096214/f
See [asana task](https://app.asana.com/0/1203137811378537/1205266828096214/f)
see [asana task](https://app.asana.com/0/0/1205278669759816/f)
=> Incremental rollout test

anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/AnrSupervisor.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205278679036125/f
Make ANR supervisor a singleton in app scope
QA optional
=> Make AnrSupervisor a singleton inside app scope

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
Task/Issue URL: https://app.asana.com/0/0/1205291624442178/f
=> Add count pixel for dry run

.github/workflows/ads-end-to-end.yml, .github/workflows/end-to-end.yml, .github/workflows/privacy-dashboard-end-to-end.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205278679036154/f
Update to maestro cloud 1.4.1
N/A
https://github.com/duckduckgo/Android/actions/runs/5893941393 passes
=> Update to maestro cloud 1.4.1

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgServerApi.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/FakeWgVpnControllerService.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/RealWgServerApiTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205275826500700/f
QA optional
Smoke test NP
=> Update server loc to new correct format

app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt, app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt, app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205310661579618/f
=> Fix bug in np settings entry

privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeatureName.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205310661579709/f
This PR updates privacy config to v3 to have support for incremental rollouts.
Smoke test app
=> Use v3 privacy config

anrs/anrs-impl/src/main/java/com/duckduckgo/app/anr/ExceptionModels.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205323168595965/f
Improve exception entity info
QA Optional
=> Improve ExceptionEntity

network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205323168596043/f
Remove duplicated bullet point in copy
QA optional
=> Remove duplicated copy

app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-et/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-lv/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/donottranslate.xml, app/src/main/res/values/strings.xml
Task/Issue URL: https://app.asana.com/0/0/1205315686777306/f
Trigger translations.
Ensure translations job is completed -> https://dashboard.smartling.com/app/projects/b01b53ede/account-jobs/b01b53ede:bzw5tplxzrdi
=> [Allow users to delete bookmarks from edit screen] Android translations

app/src/main/java/com/duckduckgo/app/survey/api/SurveyDownloader.kt, app/src/main/java/com/duckduckgo/app/survey/api/SurveyGroup.kt, app/src/main/java/com/duckduckgo/app/survey/api/SurveyService.kt, app/src/main/java/com/duckduckgo/app/survey/notification/SurveyNotificationScheduler.kt, app/src/test/java/com/duckduckgo/app/survey/api/SurveyDownloaderTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205301853498999/f
Add support for the NP survey. See asana task for more info
Follow the test steps in [here](https://app.asana.com/0/0/1205318335997484/f).
=> Add NP survey

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/DeviceShieldTileService.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205342055595355/f
Fix AppTP quick setting to only affect the AppTp feature and not the whole VPN.
=> Fix appTp quick setting

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetPWaitlistChecker.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetPWaitlistManager.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/waitlist/RealNetPWaitlistManagerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205323168596147/f
Avoid moot endpoint calls
Perform test cases as per [this task](https://app.asana.com/0/0/1205145153997779/f)
=> Avoid moot endpoint calls

app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksScreens.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt, app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205122648906217/f
Fixed the back navigation when opening bookmarks or favorites.
Fixed the back navigation when gesture navigation is enabled.
Tests the main change:
Test the gesture navigation in Production to notice the issue:
Test the fixed gesture navigation:
=> Implement changes for back button

versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1205417864899546/f
Update to latest NetGuard that fixes a TLS extensions parsing issue
=> Update to netguard 1.6.2

network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/414730916066338/1205445458339620/f
Fix T/C copy
See [asana task](https://app.asana.com/0/0/1205432938975253/f)
=> Fix TC copy

app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteViewModel.kt, app/src/test/java/com/duckduckgo/app/feedback/BrokenSiteViewModelTest.kt
https://app.asana.com/0/488551667048375/1205479210146644/f
=> Fix breakage report category

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/store/NetPWaitlistDataStore.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205278679036099/f
See task description.
QA optional
=> Fix IOException in DataStore

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205475699000105/f 
Disable encryption pixels
=> Sync: Disable error pixel

app/src/main/java/com/duckduckgo/app/survey/api/SurveyDownloader.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205480399304937/f
Fix NPE in survey that triggers when cohort is null
QA-optional
=> Fix NPE in survey

.maestro/bookmarks/open_bookmark_in_folder_and_navigate_back.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205497967969358/f
Ensure maestro tests have unique names (fails if not)
QA optional
=> Ensure maestro bookmark tests have unique names

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205489571133500/f 
This PR allows changing subs
See task
=> Allow changing subs

ad-click/ad-click-api/build.gradle, build.gradle, content-scope-scripts/content-scope-scripts-api/build.gradle, content-scope-scripts/content-scope-scripts-impl/build.gradle, content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/MessageHandlerPlugin.kt, content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/MessagingInterface.kt, content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/messaging/RealMessagingContentScopeScripts.kt, content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/MessagingInterfaceTest.kt, content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/messaging/RealMessagingContentScopeScriptsTest.kt, cookies/cookies-api/build.gradle, downloads/downloads-api/build.gradle, fingerprint-protection/fingerprint-protection-api/build.gradle, privacy-config/privacy-config-api/build.gradle, request-filterer/request-filterer-api/build.gradle, sync/sync-api/build.gradle, sync/sync-impl/build.gradle, windows/windows-api/build.gradle, windows/windows-impl/build.gradle
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205498067979776/f 
Add gradle check to avoid di dependencies on api modules
=> Add rule to avoid anvil/dagger/di dependencies on api modules

sync/sync-impl/src/main/res/layout/activity_show_code.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205209353449313/f
Update design for show text code
=> Update design for show text code

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/RealSyncEngine.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205521340054477/f
When sending local data, if a feature has no data to send, we just skip.
However, instead of skipping just the feature, we are skipping sync.
The PR introduces the fix for that
_Feature 1_
=> Fix wrong return when feature empty

app/src/main/java/com/duckduckgo/app/email/AppEmailManager.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205528656118798/f 
Moves an expensive call to a worker thread as it was a source of ANRs, as it was being called from main thread and immediately upon process creation.
- QA optional
- [optional]: Check Email Protection still working as expecting, both when signed in and not (e.g., check `Generate Duck Address` shows in the overflow when logged in)
=> Move EmailManager's isSignedIn() init to worker thread

app/src/main/java/com/duckduckgo/app/browser/logindetection/FireproofDialogsEventHandler.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205529287331306/f 
Ensures we update live data value on the main thread
QA optional
=> Ensure Fireproof dialog live data updated on main thread

subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/Subscriptions.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt, subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt, subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205514901344597/f 
This PR adds a public api for entitlements
See task
=> Add entitlement api

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt
Task/Issue URL: https://app.asana.com/0/1200905986587319/1205523935698288/f
Changed dispatcher.
=> Android Crash: DeviceShieldTrackerActivity.kt:195

app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksAdapter.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksEntityQueryListener.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205529341460922/f
Reverted dispatcher change for bookmarks.
See https://app.asana.com/0/0/1205529341460922/1205538146674625/f
---
- https://app.asana.com/0/0/1205529341460922
=> Bookmarks, index out of bounds exceptions

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldStatusReporting.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionStatusReporting.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205480399304955/f
Ensure users that have AppTP and/or NetP enabled are properly accounted for in DAUs.
QA optinoal
=> Improve AppTP/NP DAU reporting

subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsViewModel.kt, subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205538346631078/f 
This PR changes the subs manager to avoid creating account when is not needed
See task
=> Amend subs manager

node_modules/@duckduckgo/autofill/dist/autofill-debug.js, node_modules/@duckduckgo/autofill/dist/autofill.js, node_modules/@duckduckgo/autofill/dist/shared-credentials.json, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1205538042573894/1205538042573894
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.4.0
Updates Autofill to version [8.4.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/8.4.0).
* Improve non-English matching by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/374
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/8.3.0...8.4.0
=> Update autofill to 8.4.0

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt
Task/Issue URL: https://app.asana.com/0/0/1205530419817943/f
Fixed crash in TrackerFeedAdapter.
=> TrackerFeedAdapter, index out of bounds exceptions

app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksAdapter.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksEntityQueryListener.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModel.kt, app/src/main/java/com/duckduckgo/app/bookmarks/ui/FavoritesAdapter.kt, app/src/test/java/com/duckduckgo/app/bookmarks/model/SavedSitesRepositoryTest.kt, app/src/test/java/com/duckduckgo/app/bookmarks/ui/BookmarksViewModelTest.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/SavedSitesRepository.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205531244553377/f
- Fixes an issue where favorites would disappear when searching.
- Also fixes an issue where folders would display incorrectly when searching.
=> Fix issues with bookmarks search

network-protection/network-protection-api/src/main/java/com/duckduckgo/networkprotection/api/NetworkProtectionScreens.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetPWaitlistInvitedActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205504063130381/f
Enable NetP upon accepted T&C
Steps in [this task](https://app.asana.com/0/0/1205568337189845/f)
=> Auto-enable NetP on terms accepted

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205504063130381/f
Enable directly instead of going through the UI toggle. It's faster
Repeat tests in https://app.asana.com/0/0/1205568337189845/f
=> Improve NetP auto-enable upon accepted T&C

versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1205523868092348/f
Update to latest NetGuard that attempts to fix a crash in TLS parsing
AppTP smoke tests
=> Update to netguard 1.6.3

network-protection/network-protection-subscription-internal/build.gradle, network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetpSubscriptionManager.kt
Task/Issue URL: https://app.asana.com/0/0/1205527836299755/f
See attached task description.
See attached task description.
=> Integrate client pat to NP

autofill/readme.md
Task/Issue URL: https://app.asana.com/0/0/1205583933405572/f 
Adds a `readme` to the autofill module
=> Add a readme for autofill module

network-protection/network-protection-subscription-internal/build.gradle, network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetworkProtectionWaitlistWithSubsImpl.kt
Task/Issue URL: https://app.asana.com/0/0/1205581046554461/f
=> Integrate entitlement check in settings

node_modules/@duckduckgo/autofill/dist/autofill-debug.js, node_modules/@duckduckgo/autofill/dist/autofill.js, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/488551667048375/1205602210479337/f 
Updates Autofill to `8.4.1`
Outlined in task
=> Update Autofill to 8.4.1

network-protection/network-protection-impl/src/main/res/layout/activity_netp_terms.xml, network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205581341025832/f
=> Make easier to accept TC

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/report/PrivacyReportViewModel.kt
Task/Issue URL: https://app.asana.com/0/0/1205605324183239/f 
ANR prevention: Moves a potentially expensive call to the IO thread instead of main thread
QA optional
=> Ensure `shouldShowCTA` impl happens off of main thread

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncServiceRemote.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/SyncAccountDisabledObserver.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/SyncApiClient.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/SyncStateObserver.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupViewModel.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncAccountRepositoryTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncServiceRemoteTest.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/engine/SyncStateObserverTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205585239189279/f
Handles 401 http error codes for sync data operations.
_Feature 1_
_Feature 2_
=> clear sync keys if BE returns invalid code

app/src/test/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModelTest.kt, app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt, network-protection/network-protection-api/src/main/java/com/duckduckgo/networkprotection/api/NetworkProtectionWaitlist.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/cohort/NetpCohortStore.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerRequestInterceptor.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetPWaitlistManager.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetworkProtectionWaitlistImpl.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/store/NetPWaitlistDataStore.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/store/NetPWaitlistRepository.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/WgVpnControllerRequestInterceptorTest.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/waitlist/NetworkProtectionWaitlistTest.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/waitlist/RealNetPWaitlistManagerTest.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/waitlist/store/FakeNetPWaitlistRepository.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/waitlist/store/RealNetPWaitlistRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205601953283917/f
Move `getState` method to a background thread
Smoke test NetP onboarding flow and feature itself.
=> Move getState call to a background thread

versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1205622025465782/f
Revert to ng 1.6.2 (see https://app.asana.com/0/488551667048375/1205622025465782/f for more details)
AppPT smoke testing
=> Revert to ng 1.6.2

privacy-config/privacy-config-internal/src/main/java/com/duckduckgo/privacy/config/internal/plugins/ApiDevPrivacyConfigInterceptor.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205640347277520/f 
Not crash the app if invalid custom endpoint for privacy config (internal settings)
_Feature 1_
=> Custom endpoint, capture host empty crash

saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/service/SavedSitesDataCleaner.kt, statistics/src/main/java/com/duckduckgo/app/statistics/pixels/FeatureRetentionPixelSender.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/di/SyncModule.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/triggers/SyncBackgroundWorker.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModel.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/triggers/BackgroundSyncWorkerSchedulerTest.kt, sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncStore.kt, sync/sync-store/src/test/java/com/duckduckgo/sync/store/SyncSharedPrefsStoreTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205605425435832/f 
Usual sync smoke tests
=> Sync: Move access to SharedPrefs to a bg thread

network-protection/network-protection-impl/src/main/AndroidManifest.xml, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/di/NetworkProtectionModule.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/di/ProdNetPConfigTogglesDao.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementActivity.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/notification/NetPDisabledNotificationScheduler.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPNotificationSettingsActivity.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPSettingsLocalConfig.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsActivity.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/NetPRemoteFeature.kt, network-protection/network-protection-impl/src/main/res/layout/activity_netp_notification_settings.xml, network-protection/network-protection-impl/src/main/res/layout/activity_netp_vpn_settings.xml, network-protection/network-protection-impl/src/main/res/layout/section_settings.xml, network-protection/network-protection-impl/src/main/res/values/donottranslate.xml, network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/di/InternalNetPConfigTogglesDao.kt, network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/di/NetPInternalModule.kt, network-protection/network-protection-store/src/main/java/com/duckduckgo/networkprotection/store/db/NetPDatabase.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205553375632152/f
Implement the NetP settings, see [asana](https://app.asana.com/0/488551667048375/1205553375632152/f) for more info
See [test cases](https://app.asana.com/0/0/1205629751016526/f)
=> NetP settings

.github/workflows/action-pr-opened.yaml
Task/Issue URL: https://app.asana.com/0/1174433894299346/1205611423977807/f
Remove external contributor step, it’s not needed.
=> GHA: Remove external contributor step

.github/workflows/update-content-scope.yml, .github/workflows/update-ref-tests.yml
Task/Issue URL: https://app.asana.com/0/1157893581871903/1205064193224452
Update workflow to stop using the custom GHA for checking the latest release.
=> GHA: Latest release step

js-messaging/js-messaging-api/src/main/java/com/duckduckgo/js/messaging/api/JsMessaging.kt, js-messaging/js-messaging-impl/src/main/java/com/duckduckgo/js/messaging/impl/RealJsMessageHelper.kt, js-messaging/js-messaging-impl/src/test/java/com/duckduckgo/js/messaging/impl/RealJsMessageHelperTest.kt, subscriptions/subscriptions-impl/build.gradle, subscriptions/subscriptions-impl/src/main/AndroidManifest.xml, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/JSONObjectAdapter.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsActivity.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsManager.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsViewModel.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsWebViewActivity.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsWebViewClient.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/auth/AuthService.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/billing/BillingClientWrapper.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterface.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/repository/SubscriptionsRepository.kt, subscriptions/subscriptions-impl/src/main/res/layout/activity_subscriptions.xml, subscriptions/subscriptions-impl/src/main/res/layout/activity_subscriptions_webview.xml, subscriptions/subscriptions-impl/src/main/res/menu/menu_subscriptions_activity.xml, subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsManagerTest.kt, subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt, subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/messaging/SubscriptionMessagingInterfaceTest.kt, subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/repository/RealSubscriptionsRepositoryTest.kt, subscriptions/subscriptions-store/src/main/java/com/duckduckgo/subscriptions/store/AuthDataStore.kt
Task/Issue URL: https://app.asana.com/0/0/1205077126622547/f 
This PR integrates the FE for subs
See task
=> Integrate FE for subs

.github/workflows/ci.yml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205677379617787/f 
Temporary use ubuntu-20.04 to fix flakiness on ci
_Feature 1_
=> Use ubuntu 20.04 on ci

app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/prefs/FakeVpnSharedPreferencesProvider.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/connectionclass/ConnectionClassManager.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/connectionclass/ConnectionQuality.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/connectionclass/ConnectionQualityStore.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/connectionclass/ExponentialGeometricAverage.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/connectionclass/VpnLatencySampler.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixelNames.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/connectionclass/ConnectionClassManagerTest.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/connectionclass/ConnectionQualityStoreTest.kt, network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/NetPInternalSettingsActivity.kt, network-protection/network-protection-internal/src/main/res/layout/activity_netp_internal_settings.xml, network-protection/network-protection-internal/src/main/res/values/donottranslate.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205631232587242/f
Connection class/latency measurement and reporting.
This PR adds the following NetP classes:
* `ConnectionQuality` - defines the connection quality based on latency (ms)
* `ConnectionQualityStore` - connection latency measurement store
* `ExponentialGeometricAverage` - class that computes a Exponential Moving Average (EMA)
* `ConnectionClassManager` - calculates the connection class by adding latency measurements and applies some hysteresis 
* `VpnLatencySampler` - class that samples latency and reports when connection class is `POOR` or worse
Test cases [here](https://app.asana.com/0/0/1205663579937311/f)
=> Connection class measurement

remote-messaging/readme.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205591105939937/f
Adds Readme for remote messaging module.
_Feature 1_
=> Add RMF readme

network-protection/network-protection-subscription-internal/src/main/java/com/duckduckgo/networkprotection/subscription/NetpSubscriptionManager.kt, subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/Subscriptions.kt, subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt, subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/RealSubscriptionsTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205697780079110/f 
See task
See task
=> Refactor pat to access token

downloads/readme.md
Task/Issue URL: https://app.asana.com/0/0/1205657770178729/f
Added readme file for the downloads module.
No tests needed.
=> Add readme for feature: downloads

versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1205675418279581/f
Bump version to the one that contains https://github.com/duckduckgo/netguard/pull/27
AppTP/NetP smoking tests
=> Bump ddg-netguard-android to 1.6.4

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/RealSyncEngine.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205581521828312/f 
Adds reason to persister error pixels.
just smoke test
=> Add code and reason to persister error pixel

common/common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/expand/DaxExpandableMenuItem.kt
https://github.com/duckduckgo/Android/pull/3616 introduced a suggestion that broke the build
Smoke test
=> Fix PR Suggestion

sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncServiceRemote.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/RealSyncEngine.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/pixels/SyncPixels.kt, sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncAccountRepositoryTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205640564992756/f 
Adds code and reason when error in sync api calls.
Just smoke testing
=> Add Error to pixel when attempt fails

common/common-ui/src/main/res/layout/view_remote_message_cta.xml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205678747351628/f
Fix margins in remote message component
- Go to Settings > App components design preview
- Go to Messaging tab
=> ADS: Fix RMF margins

.maestro/ads_preview_flows/1-_design-system-components.yaml
Task/Issue URL: https://app.asana.com/0/488551667048375/1205707058640578/f 
Fixes maestro tests that were broken after the release of ExpandableMenu
Run ADS Maestro workflow
=> ADS: Fix maestro tests for ExpandableView

installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/InstallSourceExtractor.kt, installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/InstallSourceLifecycleObserver.kt, installation/installation-impl/src/test/java/InstallSourceLifecycleObserverTest.kt, installation/readme.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205687772894386/f 
Adds a readme for the installation module.
=> Add readme for installation module

privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205723596658068/f 
Force download of v4 config
=> Force reset config

web-compat/readme.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205687772894428/f
Adds a readme for the web compat module.
=> Add web compat readme

content-scope-scripts/readme.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205687770304788/f
Adds a readme for the Content Scope Scripts module.
=> Add Content Scope Scripts readme

fingerprint-protection/readme.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205687772894382/f
Adds a readme for the fingerprint protection module.
=> Add fingerprint protection readme

element-hiding/readme.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205687770304794/f
Adds a readme for the element hiding module.
=> Add element hiding readme

runtime-checks/readme.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205687772894406/f
Adds a readme for the runtime checks module.
=> Add runtime checks readme

httpsupgrade/readme.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205687772894384/f
Adds a readme for the https upgrade module.
=> Add https upgrade readme

saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersister.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205728925183706/f
Send moshi stracktrace if parse fails
Smoke testing around bookmarks sync.
=> Add Json parse error to perister error pixel

site-permissions/readme.md
Task/Issue URL: https://app.asana.com/0/0/1205687772894414/f
Added readme for `site-permissions` module
=> site-permissions module readme

.maestro/ads_preview_flows/1-_design-system-components.yaml
Task/Issue URL: https://app.asana.com/0/414730916066338/1205716607749330/f 
Fixes Maestro test issue 
https://github.com/duckduckgo/Android/actions/runs/6535124479/job/17743840123
=> ADS: Remove extra Dialog test

.github/CODEOWNERS, saved-sites/readme.md
Task/Issue URL: https://app.asana.com/0/0/1205687772894408/f 
Adds readme file for saved sites
Adds @malmstein to the codeowners file for that module
=> Saved Sites: add readme and codeowners

app/src/main/java/com/duckduckgo/widget/VoiceSearchWidgetUpdaterReceiver.kt, voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/ActivityResultLauncherWrapper.kt, voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/PermissionAwareVoiceSearchLauncher.kt, voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/PermissionAwareVoiceSearchLauncherTest.kt
Task/Issue URL: https://app.asana.com/0/1202552961248957/1205732562346495/f 
**Requires Android 13+, English US locale. Use ADB logcat to verify crashes**
_Feature 1_
_Feature 2_
No UI changes
=> Fix crash when changing locale

app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt, app/src/main/java/com/duckduckgo/widget/VoiceSearchWidgetUpdaterReceiver.kt, voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/ActivityResultLauncherWrapper.kt, voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/PermissionAwareVoiceSearchLauncher.kt, voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/PermissionAwareVoiceSearchLauncherTest.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205729473857462/f 
Fix favorites grid not shown when focusing a site
_Check favorites shown when focusing site_
_Check favorites not shown when focusing SERP_
=> Fix favorites not triggered when focusing site

secure-storage/readme.md
Task/Issue URL: https://app.asana.com/0/488551667048375/1205687772894410/f 
Adds readme for `secure-storage` modules
=> Add readme for secure-storage modules

app/src/test/java/com/duckduckgo/app/bookmarks/model/SavedSitesRepositoryTest.kt, app/src/test/java/com/duckduckgo/app/sync/SavedSitesSyncDataProviderTest.kt, saved-sites/saved-sites-api/src/main/java/com/duckduckgo/savedsites/api/SavedSitesRepository.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/SavedSitesRepository.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/RealSavedSitesSyncStore.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataObserver.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersister.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesDeduplicationPersister.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesLocalWinsPersister.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesRemoteWinsPersister.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithm.kt, saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesTimestampPersister.kt, saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersisterTest.kt, saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithmTest.kt, sync/sync-api/src/main/java/com/duckduckgo/sync/api/engine/Models.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/RealSyncStateMonitor.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncServiceRemote.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/RealSyncEngine.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/SyncApiClient.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/SyncScheduler.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/engine/SyncStateRepository.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/internal/SyncInternalEnvInterceptor.kt, sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/triggers/AppLifecycleSyncObserver.kt, sync/sync-store/src/main/java/com/duckduckgo/sync/store/dao/SyncAttemptDao.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205212669786577/f
Update the timestamp usage to server / client, to mimic what other features are doing.
This PR also solves https://app.asana.com/0/1174433894299346/1204732743092820/f
Check in Asana task
=> Sync: Saved Sites timestamps

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgServerApi.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsActivity.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/NetPVpnSettingsViewModel.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/DisplayablePreferredLocationProvider.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModel.kt, network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoswitchingCityChoiceDialogFragment.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/NetpGeoSwitchingViewModelTest.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/settings/geoswitching/RealDisplayablePreferredLocationProviderTest.kt, network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/feature/NetPInternalSettingsActivity.kt, network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/WgServerInternalProvider.kt, network-protection/network-protection-store/src/main/java/com/duckduckgo/networkprotection/store/db/NetPDatabase.kt, network-protection/network-protection-store/src/main/java/com/duckduckgo/networkprotection/store/remote_config/NetPEgressServer.kt, network-protection/network-protection-store/src/main/java/com/duckduckgo/networkprotection/store/remote_config/NetPInternalConfigDatabase.kt
Task/Issue URL:  https://app.asana.com/0/0/1205709458693499/f
https://app.asana.com/0/0/1205746352061414/f
=> Implement logic for preferred loc subtitle

app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteActivity.kt, app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteViewModel.kt, app/src/main/java/com/duckduckgo/app/brokensite/api/BrokenSiteSender.kt, app/src/main/java/com/duckduckgo/app/brokensite/model/BrokenSite.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt, app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt, app/src/main/java/com/duckduckgo/app/browser/WebViewClientListener.kt, app/src/main/java/com/duckduckgo/app/global/model/SiteFactoryImpl.kt, app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt, app/src/test/java/com/duckduckgo/app/feedback/BrokenSiteViewModelTest.kt, app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesReferenceTest.kt, browser-api/src/main/java/com/duckduckgo/app/global/model/Site.kt, browser-api/src/main/java/com/duckduckgo/browser/api/brokensite/BrokenSiteNav.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205608778367074/f
Add error codes to broken site reports
=> Add error codes to reports

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModel.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/TrackerDividerItemDecoration.kt, app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml, app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_activity_entry.xml, app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_excluded_app_entry_skeleton.xml
Task/Issue URL: https://app.asana.com/0/0/1205217801169327/f 
See title
_Feature 1_
=> Fix shimmer layout from my apps

privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
Task/Issue URL: https://app.asana.com/0/488551667048375/1205746390734021/f 
This PR fixes a bad DB migration that crashes on update
=> Fixes bd crash after update

app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionExclusionListActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModel.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt, app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/TrackerDividerItemDecoration.kt, app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml, app-tracking-protection/vpn-impl/src/main/res/layout/activity_vpn_onboarding.xml, app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_activity_entry.xml, app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_excluded_app_entry_skeleton.xml
Task/Issue URL: https://app.asana.com/0/0/1205271927356436/f
=> Fix touch feedback in AppTP onboarding

network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/configuration/WgTunnel.kt, network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/configuration/WgTunnelTest.kt, versions.properties
Task/Issue URL: https://app.asana.com/0/488551667048375/1205771358861884/f
See asana
Smoke test AppTP
=> Bump to ng 1.6.6

voice-search/readme.md
Task/Issue URL: https://app.asana.com/0/0/1205687772894424/f
Add readme for voice search
QA-optional
=> Add readme for voice search
